-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Students Table
CREATE TABLE IF NOT EXISTS students (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  school_id UUID, -- Can be linked to a schools table if it exists, or just store ID
  state_unique_id TEXT UNIQUE, -- Código único do aluno no sistema do estado (RA/Matrícula)
  name TEXT NOT NULL,
  current_class_id UUID,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Index for faster search
  CONSTRAINT students_state_id_key UNIQUE (state_unique_id)
);

-- 2. PDI Documents (The core entity)
CREATE TABLE IF NOT EXISTS pdi_documents (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  student_id UUID NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  year INT NOT NULL DEFAULT date_part('year', CURRENT_DATE),
  status TEXT CHECK (status IN ('draft', 'active', 'archived')) DEFAULT 'draft',
  
  -- JSONB column to store the validated PDI Data (Sections I through VIII)
  content_data JSONB DEFAULT '{}'::jsonb,
  
  -- Section XI: Final Report / Parecer Final generated by AI or human
  final_report TEXT,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. PDI Teacher Entries (Normalized Seção X)
-- This allows querying evaluations by subject/teacher easier than inside JSONB
CREATE TABLE IF NOT EXISTS pdi_teacher_entries (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  pdi_document_id UUID NOT NULL REFERENCES pdi_documents(id) ON DELETE CASCADE,
  teacher_id UUID NOT NULL, -- Reference to auth.users or profiles
  bimester INT CHECK (bimester BETWEEN 1 AND 4),
  subject TEXT NOT NULL, -- e.g., 'Matemática', 'História'
  
  autonomy_level TEXT CHECK (autonomy_level IN ('MUITO_SUPORTE', 'POUCO_SUPORTE', 'ALTA_COMPREENSAO', 'POUCA_COMPREENSAO')),
  observations TEXT, -- The diagnosis/parecer
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- Ensure one entry per teacher/subject/bimester per PDI
  CONSTRAINT unique_teacher_entry UNIQUE (pdi_document_id, teacher_id, subject, bimester)
);

-- RLS Policies (Examples)
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE pdi_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE pdi_teacher_entries ENABLE ROW LEVEL SECURITY;

-- Policy: Allow authenticated users to view definitions (Adjust based on role logic later)
CREATE POLICY "Enable read access for authenticated users" ON students FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable read access for authenticated users" ON pdi_documents FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable read access for authenticated users" ON pdi_teacher_entries FOR SELECT TO authenticated USING (true);

-- Indexes for JSONB performance
CREATE INDEX IF NOT EXISTS idx_pdi_content ON pdi_documents USING gin (content_data);
