-- ==============================================================================
-- PDI MODULE SCHEMA IMPLEMENTATION
-- Phase 1: Cycles and Teacher Evaluations
-- ==============================================================================

BEGIN;

-- 1. Create Enum Types (if not exists, though text is safer for Supabase Dashboard interactions usually, but Enums enforce data integrity)
-- We will stick to TEXT with CHECK constraints in Tables for easier management.

-- 2. Create PDI CYCLES Table
-- Represents a PDI document for a specific year.
CREATE TABLE IF NOT EXISTS pdi_cycles (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    student_id UUID REFERENCES school_students(id) ON DELETE CASCADE,
    year INTEGER NOT NULL DEFAULT EXTRACT(YEAR FROM CURRENT_DATE),
    status TEXT CHECK (status IN ('DRAFT', 'IN_PROGRESS', 'COMPLETED', 'ARCHIVED')) DEFAULT 'DRAFT',
    
    -- The consolidated report generated by AI (Section XI)
    final_report TEXT,
    
    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Constraint: Only one active PDI per student per year
    UNIQUE(student_id, year)
);

-- 3. Create PDI TEACHER EVALUATIONS Table (Section X)
-- One record per teacher, per bimester.
CREATE TABLE IF NOT EXISTS pdi_teacher_evaluations (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    pdi_cycle_id UUID REFERENCES pdi_cycles(id) ON DELETE CASCADE,
    teacher_id UUID REFERENCES auth.users(id),
    
    subject TEXT NOT NULL, -- Matéria (e.g., 'Matemática')
    bimester INTEGER CHECK (bimester IN (1, 2, 3, 4)),
    
    -- Evaluation Fields (Enums mapped from PDF)
    autonomy_level TEXT CHECK (autonomy_level IN ('MUITO_SUPORTE', 'POUCO_SUPORTE', 'AUTONOMO', 'NAO_OBSERVADO')),
    comprehension_level TEXT CHECK (comprehension_level IN ('ALTA', 'MEDIA', 'BAIXA', 'NENHUMA')),
    
    pedagogical_diagnosis TEXT, -- Observações discursivas
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Constraint: One evaluation per teacher per subject per bimester per cycle
    UNIQUE(pdi_cycle_id, teacher_id, subject, bimester)
);

-- 4. ENABLE RLS
ALTER TABLE pdi_cycles ENABLE ROW LEVEL SECURITY;
ALTER TABLE pdi_teacher_evaluations ENABLE ROW LEVEL SECURITY;

-- 5. RLS POLICIES

-- PDI CYCLES
-- School Manager: Full Access (Create, Read, Update)
CREATE POLICY "Managers Manage PDI Cycles" ON pdi_cycles 
FOR ALL TO authenticated 
USING (
    exists (
        select 1 from school_students ss
        join profiles p on p.school_id = ss.school_id
        where ss.id = pdi_cycles.student_id
        and p.id = auth.uid()
        and p.role IN ('school_manager', 'school_admin', 'admin')
    )
);

-- Teachers: Read Only (They need to see the cycle to attach evaluations)
CREATE POLICY "Teachers Read PDI Cycles" ON pdi_cycles 
FOR SELECT TO authenticated 
USING (
    exists (
        select 1 from school_students ss
        join profiles p on p.school_id = ss.school_id
        where ss.id = pdi_cycles.student_id
        and p.id = auth.uid()
        and p.role = 'teacher'
    )
);

-- TEACHER EVALUATIONS
-- Teachers: Manage OWN evaluations
CREATE POLICY "Teachers Manage Own Evaluations" ON pdi_teacher_evaluations
FOR ALL TO authenticated
USING (teacher_id = auth.uid())
WITH CHECK (teacher_id = auth.uid());

-- Managers: Read All Evaluations (To consolidate)
CREATE POLICY "Managers View Evaluations" ON pdi_teacher_evaluations
FOR SELECT TO authenticated
USING (
    exists (
        select 1 from pdi_cycles pc
        join school_students ss on ss.id = pc.student_id
        join profiles p on p.school_id = ss.school_id
        where pc.id = pdi_teacher_evaluations.pdi_cycle_id
        and p.id = auth.uid()
        and p.role IN ('school_manager', 'school_admin', 'admin')
    )
);

COMMIT;
