packages:
  - 'apps/*'
  - 'packages/*'
  - 'services/*'
  - 'infra/*'
allowBuilds:
  '@prisma/engines': false
  core-js: set this to true or false
  esbuild: set this to true or false
  prisma: true
  sharp: true
  unrs-resolver: true
