-- Lote 6 de 7
-- Updates 1501 a 1800

BEGIN;

-- EE MARIA DE MAGALHÃES (ARAXÁ) - INEP: 158275
UPDATE schools 
SET inep_code = '158275' 
WHERE UPPER(TRIM(name)) = 'EE MARIA DE MAGALHÃES' 
  AND UPPER(TRIM(city)) = 'ARAXÁ' 
  AND inep_code IS NULL;

-- EE PADRE ANACLETO GIRALDI (ARAXÁ) - INEP: 158216
UPDATE schools 
SET inep_code = '158216' 
WHERE UPPER(TRIM(name)) = 'EE PADRE ANACLETO GIRALDI' 
  AND UPPER(TRIM(city)) = 'ARAXÁ' 
  AND inep_code IS NULL;

-- EE PROFESSOR LUIZ ANTÔNIO CORRÊA OLIVEIRA (ARAXÁ) - INEP: 158194
UPDATE schools 
SET inep_code = '158194' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR LUIZ ANTÔNIO CORRÊA OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'ARAXÁ' 
  AND inep_code IS NULL;

-- EE ROTARY (ARAXÁ) - INEP: 218502
UPDATE schools 
SET inep_code = '218502' 
WHERE UPPER(TRIM(name)) = 'EE ROTARY' 
  AND UPPER(TRIM(city)) = 'ARAXÁ' 
  AND inep_code IS NULL;

-- EE VASCO SANTOS (ARAXÁ) - INEP: 158313
UPDATE schools 
SET inep_code = '158313' 
WHERE UPPER(TRIM(name)) = 'EE VASCO SANTOS' 
  AND UPPER(TRIM(city)) = 'ARAXÁ' 
  AND inep_code IS NULL;

-- EE PADRE HENRIQUE PEETERS (CAMPO FLORIDO) - INEP: 278904
UPDATE schools 
SET inep_code = '278904' 
WHERE UPPER(TRIM(name)) = 'EE PADRE HENRIQUE PEETERS' 
  AND UPPER(TRIM(city)) = 'CAMPO FLORIDO' 
  AND inep_code IS NULL;

-- EE DOUTOR JOSÉ CORDEIRO DE CAMPOS (CAMPOS ALTOS) - INEP: 158534
UPDATE schools 
SET inep_code = '158534' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR JOSÉ CORDEIRO DE CAMPOS' 
  AND UPPER(TRIM(city)) = 'CAMPOS ALTOS' 
  AND inep_code IS NULL;

-- EE PADRE CLEMENTE DE MALETO (CAMPOS ALTOS) - INEP: 158569
UPDATE schools 
SET inep_code = '158569' 
WHERE UPPER(TRIM(name)) = 'EE PADRE CLEMENTE DE MALETO' 
  AND UPPER(TRIM(city)) = 'CAMPOS ALTOS' 
  AND inep_code IS NULL;

-- EE BOM SUCESSO (CARNEIRINHO) - INEP: 159255
UPDATE schools 
SET inep_code = '159255' 
WHERE UPPER(TRIM(name)) = 'EE BOM SUCESSO' 
  AND UPPER(TRIM(city)) = 'CARNEIRINHO' 
  AND inep_code IS NULL;

-- EE MARECHAL HERMES (CARNEIRINHO) - INEP: 159271
UPDATE schools 
SET inep_code = '159271' 
WHERE UPPER(TRIM(name)) = 'EE MARECHAL HERMES' 
  AND UPPER(TRIM(city)) = 'CARNEIRINHO' 
  AND inep_code IS NULL;

-- EE PROFESSOR ANTÔNIO DA SILVA (CARNEIRINHO) - INEP: 159301
UPDATE schools 
SET inep_code = '159301' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ANTÔNIO DA SILVA' 
  AND UPPER(TRIM(city)) = 'CARNEIRINHO' 
  AND inep_code IS NULL;

-- EE COMENDADOR GOMES (COMENDADOR GOMES) - INEP: 330671
UPDATE schools 
SET inep_code = '330671' 
WHERE UPPER(TRIM(name)) = 'EE COMENDADOR GOMES' 
  AND UPPER(TRIM(city)) = 'COMENDADOR GOMES' 
  AND inep_code IS NULL;

-- EE HERCULÉGIO ANTÔNIO BORGES (CONCEIÇÃO DAS ALAGOAS) - INEP: 316041
UPDATE schools 
SET inep_code = '316041' 
WHERE UPPER(TRIM(name)) = 'EE HERCULÉGIO ANTÔNIO BORGES' 
  AND UPPER(TRIM(city)) = 'CONCEIÇÃO DAS ALAGOAS' 
  AND inep_code IS NULL;

-- EE JOSÉ ALEXANDRE MIZIARA (CONCEIÇÃO DAS ALAGOAS) - INEP: 158674
UPDATE schools 
SET inep_code = '158674' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ ALEXANDRE MIZIARA' 
  AND UPPER(TRIM(city)) = 'CONCEIÇÃO DAS ALAGOAS' 
  AND inep_code IS NULL;

-- EE DR LINDOLFO BERNARDES (CONQUISTA) - INEP: 310883
UPDATE schools 
SET inep_code = '310883' 
WHERE UPPER(TRIM(name)) = 'EE DR LINDOLFO BERNARDES' 
  AND UPPER(TRIM(city)) = 'CONQUISTA' 
  AND inep_code IS NULL;

-- EE IVAN MATTAR SOUKEF (DELTA) - INEP: 322644
UPDATE schools 
SET inep_code = '322644' 
WHERE UPPER(TRIM(name)) = 'EE IVAN MATTAR SOUKEF' 
  AND UPPER(TRIM(city)) = 'DELTA' 
  AND inep_code IS NULL;

-- EE JOÃO KOPKE (FRONTEIRA) - INEP: 158801
UPDATE schools 
SET inep_code = '158801' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO KOPKE' 
  AND UPPER(TRIM(city)) = 'FRONTEIRA' 
  AND inep_code IS NULL;

-- EE PROFESSORA MARIA DO CARMO PIRES ROSA (FRONTEIRA) - INEP: 361356
UPDATE schools 
SET inep_code = '361356' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA DO CARMO PIRES ROSA' 
  AND UPPER(TRIM(city)) = 'FRONTEIRA' 
  AND inep_code IS NULL;

-- EE LAURISTON SOUZA (FRUTAL) - INEP: 158909
UPDATE schools 
SET inep_code = '158909' 
WHERE UPPER(TRIM(name)) = 'EE LAURISTON SOUZA' 
  AND UPPER(TRIM(city)) = 'FRUTAL' 
  AND inep_code IS NULL;

-- EE MAESTRO JOSINO DE OLIVEIRA (FRUTAL) - INEP: 158879
UPDATE schools 
SET inep_code = '158879' 
WHERE UPPER(TRIM(name)) = 'EE MAESTRO JOSINO DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'FRUTAL' 
  AND inep_code IS NULL;

-- EE PRESIDENTE TANCREDO NEVES (FRUTAL) - INEP: 319201
UPDATE schools 
SET inep_code = '319201' 
WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE TANCREDO NEVES' 
  AND UPPER(TRIM(city)) = 'FRUTAL' 
  AND inep_code IS NULL;

-- EE PROFESSOR BANDEIRA (FRUTAL) - INEP: 319104
UPDATE schools 
SET inep_code = '319104' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR BANDEIRA' 
  AND UPPER(TRIM(city)) = 'FRUTAL' 
  AND inep_code IS NULL;

-- EE VICENTE MACEDO (FRUTAL) - INEP: 158941
UPDATE schools 
SET inep_code = '158941' 
WHERE UPPER(TRIM(name)) = 'EE VICENTE MACEDO' 
  AND UPPER(TRIM(city)) = 'FRUTAL' 
  AND inep_code IS NULL;

-- EE ALONSO DE MORAIS ANDRADE (ITAPAGIPE) - INEP: 159131
UPDATE schools 
SET inep_code = '159131' 
WHERE UPPER(TRIM(name)) = 'EE ALONSO DE MORAIS ANDRADE' 
  AND UPPER(TRIM(city)) = 'ITAPAGIPE' 
  AND inep_code IS NULL;

-- EE SANTO ANTÔNIO (ITAPAGIPE) - INEP: 159158
UPDATE schools 
SET inep_code = '159158' 
WHERE UPPER(TRIM(name)) = 'EE SANTO ANTÔNIO' 
  AND UPPER(TRIM(city)) = 'ITAPAGIPE' 
  AND inep_code IS NULL;

-- EE SERRA DA MOEDA (ITAPAGIPE) - INEP: 159140
UPDATE schools 
SET inep_code = '159140' 
WHERE UPPER(TRIM(name)) = 'EE SERRA DA MOEDA' 
  AND UPPER(TRIM(city)) = 'ITAPAGIPE' 
  AND inep_code IS NULL;

-- EE ANTÔNIO FERREIRA BARBOSA (ITURAMA) - INEP: 159166
UPDATE schools 
SET inep_code = '159166' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO FERREIRA BARBOSA' 
  AND UPPER(TRIM(city)) = 'ITURAMA' 
  AND inep_code IS NULL;

-- EE DOM ALEXANDRE (ITURAMA) - INEP: 159247
UPDATE schools 
SET inep_code = '159247' 
WHERE UPPER(TRIM(name)) = 'EE DOM ALEXANDRE' 
  AND UPPER(TRIM(city)) = 'ITURAMA' 
  AND inep_code IS NULL;

-- EE JOAQUIM TIAGO DE QUEIROZ (ITURAMA) - INEP: 205605
UPDATE schools 
SET inep_code = '205605' 
WHERE UPPER(TRIM(name)) = 'EE JOAQUIM TIAGO DE QUEIROZ' 
  AND UPPER(TRIM(city)) = 'ITURAMA' 
  AND inep_code IS NULL;

-- EE NOSSA SENHORA DE LOURDES (ITURAMA) - INEP: 159182
UPDATE schools 
SET inep_code = '159182' 
WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DE LOURDES' 
  AND UPPER(TRIM(city)) = 'ITURAMA' 
  AND inep_code IS NULL;

-- EE TIRADENTES (ITURAMA) - INEP: 159212
UPDATE schools 
SET inep_code = '159212' 
WHERE UPPER(TRIM(name)) = 'EE TIRADENTES' 
  AND UPPER(TRIM(city)) = 'ITURAMA' 
  AND inep_code IS NULL;

-- EE IZOLDINO SOARES DE FREITAS (LIMEIRA DO OESTE) - INEP: 159280
UPDATE schools 
SET inep_code = '159280' 
WHERE UPPER(TRIM(name)) = 'EE IZOLDINO SOARES DE FREITAS' 
  AND UPPER(TRIM(city)) = 'LIMEIRA DO OESTE' 
  AND inep_code IS NULL;

-- EE PROFESSOR LEÃO COELHO DE ALMEIDA (PEDRINÓPOLIS) - INEP: 159328
UPDATE schools 
SET inep_code = '159328' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR LEÃO COELHO DE ALMEIDA' 
  AND UPPER(TRIM(city)) = 'PEDRINÓPOLIS' 
  AND inep_code IS NULL;

-- EE CORONEL OSCAR DE CASTRO (PIRAJUBA) - INEP: 311855
UPDATE schools 
SET inep_code = '311855' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL OSCAR DE CASTRO' 
  AND UPPER(TRIM(city)) = 'PIRAJUBA' 
  AND inep_code IS NULL;

-- EE ALYSSON ROBERTO BRUNO (PLANURA) - INEP: 159417
UPDATE schools 
SET inep_code = '159417' 
WHERE UPPER(TRIM(name)) = 'EE ALYSSON ROBERTO BRUNO' 
  AND UPPER(TRIM(city)) = 'PLANURA' 
  AND inep_code IS NULL;

-- EE MARLENE MARTINS REIS (PRATINHA) - INEP: 319112
UPDATE schools 
SET inep_code = '319112' 
WHERE UPPER(TRIM(name)) = 'EE MARLENE MARTINS REIS' 
  AND UPPER(TRIM(city)) = 'PRATINHA' 
  AND inep_code IS NULL;

-- EE BARÃO DA RIFAINA (SACRAMENTO) - INEP: 159484
UPDATE schools 
SET inep_code = '159484' 
WHERE UPPER(TRIM(name)) = 'EE BARÃO DA RIFAINA' 
  AND UPPER(TRIM(city)) = 'SACRAMENTO' 
  AND inep_code IS NULL;

-- EE CORONEL JOSÉ AFONSO DE ALMEIDA (SACRAMENTO) - INEP: 159506
UPDATE schools 
SET inep_code = '159506' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL JOSÉ AFONSO DE ALMEIDA' 
  AND UPPER(TRIM(city)) = 'SACRAMENTO' 
  AND inep_code IS NULL;

-- EE ESCRITORA CAROLINA MARIA DE JESUS (SACRAMENTO) - INEP: 361224
UPDATE schools 
SET inep_code = '361224' 
WHERE UPPER(TRIM(name)) = 'EE ESCRITORA CAROLINA MARIA DE JESUS' 
  AND UPPER(TRIM(city)) = 'SACRAMENTO' 
  AND inep_code IS NULL;

-- EE SINHANA BORGES (SACRAMENTO) - INEP: 159565
UPDATE schools 
SET inep_code = '159565' 
WHERE UPPER(TRIM(name)) = 'EE SINHANA BORGES' 
  AND UPPER(TRIM(city)) = 'SACRAMENTO' 
  AND inep_code IS NULL;

-- EE SANTA JULIANA (SANTA JULIANA) - INEP: 159611
UPDATE schools 
SET inep_code = '159611' 
WHERE UPPER(TRIM(name)) = 'EE SANTA JULIANA' 
  AND UPPER(TRIM(city)) = 'SANTA JULIANA' 
  AND inep_code IS NULL;

-- EE SÃO FRANCISCO DE SALES (SÃO FRANCISCO DE SALES) - INEP: 159646
UPDATE schools 
SET inep_code = '159646' 
WHERE UPPER(TRIM(name)) = 'EE SÃO FRANCISCO DE SALES' 
  AND UPPER(TRIM(city)) = 'SÃO FRANCISCO DE SALES' 
  AND inep_code IS NULL;

-- EE PROFESSORA CECÍLIA MARIA DE REZENDE NEVES (TAPIRA) - INEP: 310166
UPDATE schools 
SET inep_code = '310166' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA CECÍLIA MARIA DE REZENDE NEVES' 
  AND UPPER(TRIM(city)) = 'TAPIRA' 
  AND inep_code IS NULL;

-- CENTRO DE ORIENTAÇÃO E PESQUISA EM EDUCAÇÃO ESPECIAL (UBERABA) - INEP: 218588
UPDATE schools 
SET inep_code = '218588' 
WHERE UPPER(TRIM(name)) = 'CENTRO DE ORIENTAÇÃO E PESQUISA EM EDUCAÇÃO ESPECIAL' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- CENTRO INTERESCOLAR ESTADUAL DE LÍNGUAS (UBERABA) - INEP: 210005
UPDATE schools 
SET inep_code = '210005' 
WHERE UPPER(TRIM(name)) = 'CENTRO INTERESCOLAR ESTADUAL DE LÍNGUAS' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- CESEC PROFESSORA MARIA EMÍLIA DA ROCHA (UBERABA) - INEP: 313751
UPDATE schools 
SET inep_code = '313751' 
WHERE UPPER(TRIM(name)) = 'CESEC PROFESSORA MARIA EMÍLIA DA ROCHA' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- COLÉGIO TIRADENTES PMMG (UBERABA) - INEP: 160253
UPDATE schools 
SET inep_code = '160253' 
WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- CONSERVATÓRIO ESTADUAL DE MÚSICA RENATO FRATESCHI (UBERABA) - INEP: 159921
UPDATE schools 
SET inep_code = '159921' 
WHERE UPPER(TRIM(name)) = 'CONSERVATÓRIO ESTADUAL DE MÚSICA RENATO FRATESCHI' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE ALOÍZIO CASTANHEIRA (UBERABA) - INEP: 342556
UPDATE schools 
SET inep_code = '342556' 
WHERE UPPER(TRIM(name)) = 'EE ALOÍZIO CASTANHEIRA' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE AMÉRICA (UBERABA) - INEP: 159735
UPDATE schools 
SET inep_code = '159735' 
WHERE UPPER(TRIM(name)) = 'EE AMÉRICA' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE AURÉLIO LUIZ DA COSTA (UBERABA) - INEP: 159662
UPDATE schools 
SET inep_code = '159662' 
WHERE UPPER(TRIM(name)) = 'EE AURÉLIO LUIZ DA COSTA' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE BERNARDO VASCONCELOS (UBERABA) - INEP: 159786
UPDATE schools 
SET inep_code = '159786' 
WHERE UPPER(TRIM(name)) = 'EE BERNARDO VASCONCELOS' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE BOULANGER PUCCI (UBERABA) - INEP: 159841
UPDATE schools 
SET inep_code = '159841' 
WHERE UPPER(TRIM(name)) = 'EE BOULANGER PUCCI' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE BRASIL (UBERABA) - INEP: 159867
UPDATE schools 
SET inep_code = '159867' 
WHERE UPPER(TRIM(name)) = 'EE BRASIL' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE CARMELITA CARVALHO GARCIA (UBERABA) - INEP: 160261
UPDATE schools 
SET inep_code = '160261' 
WHERE UPPER(TRIM(name)) = 'EE CARMELITA CARVALHO GARCIA' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE DOM EDUARDO (UBERABA) - INEP: 159981
UPDATE schools 
SET inep_code = '159981' 
WHERE UPPER(TRIM(name)) = 'EE DOM EDUARDO' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE DOUTOR JOSÉ MENDONÇA (UBERABA) - INEP: 160024
UPDATE schools 
SET inep_code = '160024' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR JOSÉ MENDONÇA' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE FELÍCIO DE PAIVA (UBERABA) - INEP: 160067
UPDATE schools 
SET inep_code = '160067' 
WHERE UPPER(TRIM(name)) = 'EE FELÍCIO DE PAIVA' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE FIDÉLIS REIS (UBERABA) - INEP: 160008
UPDATE schools 
SET inep_code = '160008' 
WHERE UPPER(TRIM(name)) = 'EE FIDÉLIS REIS' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE FRANCISCO CÂNDIDO XAVIER (UBERABA) - INEP: 349321
UPDATE schools 
SET inep_code = '349321' 
WHERE UPPER(TRIM(name)) = 'EE FRANCISCO CÂNDIDO XAVIER' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE FREI LEOPOLDO DE CASTELNUOVO (UBERABA) - INEP: 160083
UPDATE schools 
SET inep_code = '160083' 
WHERE UPPER(TRIM(name)) = 'EE FREI LEOPOLDO DE CASTELNUOVO' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE GABRIEL TOTI (UBERABA) - INEP: 160105
UPDATE schools 
SET inep_code = '160105' 
WHERE UPPER(TRIM(name)) = 'EE GABRIEL TOTI' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE GERALDINO RODRIGUES CUNHA (UBERABA) - INEP: 160237
UPDATE schools 
SET inep_code = '160237' 
WHERE UPPER(TRIM(name)) = 'EE GERALDINO RODRIGUES CUNHA' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE HENRIQUE KRUGER (UBERABA) - INEP: 160121
UPDATE schools 
SET inep_code = '160121' 
WHERE UPPER(TRIM(name)) = 'EE HENRIQUE KRUGER' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE HORIZONTA LEMOS (UBERABA) - INEP: 160148
UPDATE schools 
SET inep_code = '160148' 
WHERE UPPER(TRIM(name)) = 'EE HORIZONTA LEMOS' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE IRMÃO AFONSO (UBERABA) - INEP: 160164
UPDATE schools 
SET inep_code = '160164' 
WHERE UPPER(TRIM(name)) = 'EE IRMÃO AFONSO' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE LAURO FONTOURA (UBERABA) - INEP: 160172
UPDATE schools 
SET inep_code = '160172' 
WHERE UPPER(TRIM(name)) = 'EE LAURO FONTOURA' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE LEANDRO ANTÔNIO DE VITO (UBERABA) - INEP: 160245
UPDATE schools 
SET inep_code = '160245' 
WHERE UPPER(TRIM(name)) = 'EE LEANDRO ANTÔNIO DE VITO' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE MARECHAL HUMBERTO ALENCAR CASTELO BRANCO (UBERABA) - INEP: 159671
UPDATE schools 
SET inep_code = '159671' 
WHERE UPPER(TRIM(name)) = 'EE MARECHAL HUMBERTO ALENCAR CASTELO BRANCO' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE MIGUEL LATERZA (UBERABA) - INEP: 159719
UPDATE schools 
SET inep_code = '159719' 
WHERE UPPER(TRIM(name)) = 'EE MIGUEL LATERZA' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE MINAS GERAIS (UBERABA) - INEP: 159751
UPDATE schools 
SET inep_code = '159751' 
WHERE UPPER(TRIM(name)) = 'EE MINAS GERAIS' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE NOSSA SENHORA DA ABADIA (UBERABA) - INEP: 159794
UPDATE schools 
SET inep_code = '159794' 
WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DA ABADIA' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE PAULO JOSÉ DERENUSSON (UBERABA) - INEP: 159891
UPDATE schools 
SET inep_code = '159891' 
WHERE UPPER(TRIM(name)) = 'EE PAULO JOSÉ DERENUSSON' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE PRESIDENTE JOÃO PINHEIRO (UBERABA) - INEP: 159956
UPDATE schools 
SET inep_code = '159956' 
WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE JOÃO PINHEIRO' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE PROFESSOR ALCEU NOVAES (UBERABA) - INEP: 159999
UPDATE schools 
SET inep_code = '159999' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ALCEU NOVAES' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE PROFESSOR CHAVES (UBERABA) - INEP: 160016
UPDATE schools 
SET inep_code = '160016' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR CHAVES' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE PROFESSOR HILDEBRANDO PONTES (UBERABA) - INEP: 160059
UPDATE schools 
SET inep_code = '160059' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR HILDEBRANDO PONTES' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE PROFESSOR MINERVINO CESARINO (UBERABA) - INEP: 327280
UPDATE schools 
SET inep_code = '327280' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR MINERVINO CESARINO' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE PROFESSORA CORINA DE OLIVEIRA (UBERABA) - INEP: 159972
UPDATE schools 
SET inep_code = '159972' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA CORINA DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE PROFESSORA NEIDE OLIVEIRA GOMES (UBERABA) - INEP: 349313
UPDATE schools 
SET inep_code = '349313' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA NEIDE OLIVEIRA GOMES' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE QUINTILIANO JARDIM (UBERABA) - INEP: 160075
UPDATE schools 
SET inep_code = '160075' 
WHERE UPPER(TRIM(name)) = 'EE QUINTILIANO JARDIM' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE ROTARY (UBERABA) - INEP: 160091
UPDATE schools 
SET inep_code = '160091' 
WHERE UPPER(TRIM(name)) = 'EE ROTARY' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE SANTA TEREZINHA (UBERABA) - INEP: 160130
UPDATE schools 
SET inep_code = '160130' 
WHERE UPPER(TRIM(name)) = 'EE SANTA TEREZINHA' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE SÃO BENEDITO (UBERABA) - INEP: 160156
UPDATE schools 
SET inep_code = '160156' 
WHERE UPPER(TRIM(name)) = 'EE SÃO BENEDITO' 
  AND UPPER(TRIM(city)) = 'UBERABA' 
  AND inep_code IS NULL;

-- EE DOM PEDRO II (UNIÃO DE MINAS) - INEP: 159310
UPDATE schools 
SET inep_code = '159310' 
WHERE UPPER(TRIM(name)) = 'EE DOM PEDRO II' 
  AND UPPER(TRIM(city)) = 'UNIÃO DE MINAS' 
  AND inep_code IS NULL;

-- EE GERALDINO RODRIGUES DA CUNHA (VERÍSSIMO) - INEP: 160326
UPDATE schools 
SET inep_code = '160326' 
WHERE UPPER(TRIM(name)) = 'EE GERALDINO RODRIGUES DA CUNHA' 
  AND UPPER(TRIM(city)) = 'VERÍSSIMO' 
  AND inep_code IS NULL;

-- CESEC JK (ARAGUARI) - INEP: 166821
UPDATE schools 
SET inep_code = '166821' 
WHERE UPPER(TRIM(name)) = 'CESEC JK' 
  AND UPPER(TRIM(city)) = 'ARAGUARI' 
  AND inep_code IS NULL;

-- COLÉGIO TIRADENTES DA PMMG - CTPM - UNIDADE ARAGUARI (ARAGUARI) - INEP: 369993
UPDATE schools 
SET inep_code = '369993' 
WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES DA PMMG - CTPM - UNIDADE ARAGUARI' 
  AND UPPER(TRIM(city)) = 'ARAGUARI' 
  AND inep_code IS NULL;

-- CONSERVATÓRIO ESTADUAL MÚSICA E CENTRO INTERESCOLAR ARTES RAUL BELÉM (ARAGUARI) - INEP: 166642
UPDATE schools 
SET inep_code = '166642' 
WHERE UPPER(TRIM(name)) = 'CONSERVATÓRIO ESTADUAL MÚSICA E CENTRO INTERESCOLAR ARTES RAUL BELÉM' 
  AND UPPER(TRIM(city)) = 'ARAGUARI' 
  AND inep_code IS NULL;

-- EE ANTÔNIO NUNES CARVALHO FILHO (ARAGUARI) - INEP: 166618
UPDATE schools 
SET inep_code = '166618' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO NUNES CARVALHO FILHO' 
  AND UPPER(TRIM(city)) = 'ARAGUARI' 
  AND inep_code IS NULL;

-- EE ARTUR BERNARDES (ARAGUARI) - INEP: 166839
UPDATE schools 
SET inep_code = '166839' 
WHERE UPPER(TRIM(name)) = 'EE ARTUR BERNARDES' 
  AND UPPER(TRIM(city)) = 'ARAGUARI' 
  AND inep_code IS NULL;

-- EE CORONEL LINDOLFO RODRIGUES CUNHA (ARAGUARI) - INEP: 166855
UPDATE schools 
SET inep_code = '166855' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL LINDOLFO RODRIGUES CUNHA' 
  AND UPPER(TRIM(city)) = 'ARAGUARI' 
  AND inep_code IS NULL;

-- EE COSTA SENA (ARAGUARI) - INEP: 166626
UPDATE schools 
SET inep_code = '166626' 
WHERE UPPER(TRIM(name)) = 'EE COSTA SENA' 
  AND UPPER(TRIM(city)) = 'ARAGUARI' 
  AND inep_code IS NULL;

-- EE DONA ELEONORA PIERUCCETTI (ARAGUARI) - INEP: 166634
UPDATE schools 
SET inep_code = '166634' 
WHERE UPPER(TRIM(name)) = 'EE DONA ELEONORA PIERUCCETTI' 
  AND UPPER(TRIM(city)) = 'ARAGUARI' 
  AND inep_code IS NULL;

-- EE ISOLINA FRANÇA SOARES TORRES (ARAGUARI) - INEP: 166651
UPDATE schools 
SET inep_code = '166651' 
WHERE UPPER(TRIM(name)) = 'EE ISOLINA FRANÇA SOARES TORRES' 
  AND UPPER(TRIM(city)) = 'ARAGUARI' 
  AND inep_code IS NULL;

-- EE JOSÉ CARNEIRO DA CUNHA (ARAGUARI) - INEP: 166812
UPDATE schools 
SET inep_code = '166812' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ CARNEIRO DA CUNHA' 
  AND UPPER(TRIM(city)) = 'ARAGUARI' 
  AND inep_code IS NULL;

-- EE MADRE MARIA BLANDINA (ARAGUARI) - INEP: 166685
UPDATE schools 
SET inep_code = '166685' 
WHERE UPPER(TRIM(name)) = 'EE MADRE MARIA BLANDINA' 
  AND UPPER(TRIM(city)) = 'ARAGUARI' 
  AND inep_code IS NULL;

-- EE PADRE DAMIÃO (ARAGUARI) - INEP: 166693
UPDATE schools 
SET inep_code = '166693' 
WHERE UPPER(TRIM(name)) = 'EE PADRE DAMIÃO' 
  AND UPPER(TRIM(city)) = 'ARAGUARI' 
  AND inep_code IS NULL;

-- EE PADRE EDUARDO JORDI (ARAGUARI) - INEP: 330779
UPDATE schools 
SET inep_code = '330779' 
WHERE UPPER(TRIM(name)) = 'EE PADRE EDUARDO JORDI' 
  AND UPPER(TRIM(city)) = 'ARAGUARI' 
  AND inep_code IS NULL;

-- EE PADRE ELÓI (ARAGUARI) - INEP: 166804
UPDATE schools 
SET inep_code = '166804' 
WHERE UPPER(TRIM(name)) = 'EE PADRE ELÓI' 
  AND UPPER(TRIM(city)) = 'ARAGUARI' 
  AND inep_code IS NULL;

-- EE PAES DE ALMEIDA (ARAGUARI) - INEP: 166715
UPDATE schools 
SET inep_code = '166715' 
WHERE UPPER(TRIM(name)) = 'EE PAES DE ALMEIDA' 
  AND UPPER(TRIM(city)) = 'ARAGUARI' 
  AND inep_code IS NULL;

-- EE PROFESSOR ANTÔNIO MARQUES (ARAGUARI) - INEP: 166731
UPDATE schools 
SET inep_code = '166731' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ANTÔNIO MARQUES' 
  AND UPPER(TRIM(city)) = 'ARAGUARI' 
  AND inep_code IS NULL;

-- EE PROFESSORA KATY BELEM (ARAGUARI) - INEP: 166782
UPDATE schools 
SET inep_code = '166782' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA KATY BELEM' 
  AND UPPER(TRIM(city)) = 'ARAGUARI' 
  AND inep_code IS NULL;

-- EE RAUL SOARES (ARAGUARI) - INEP: 166740
UPDATE schools 
SET inep_code = '166740' 
WHERE UPPER(TRIM(name)) = 'EE RAUL SOARES' 
  AND UPPER(TRIM(city)) = 'ARAGUARI' 
  AND inep_code IS NULL;

-- EE SÃO JUDAS TADEU (ARAGUARI) - INEP: 166766
UPDATE schools 
SET inep_code = '166766' 
WHERE UPPER(TRIM(name)) = 'EE SÃO JUDAS TADEU' 
  AND UPPER(TRIM(city)) = 'ARAGUARI' 
  AND inep_code IS NULL;

-- EE MÁRIO SIDNEY FRANCESCHI (ARAPORÃ) - INEP: 167207
UPDATE schools 
SET inep_code = '167207' 
WHERE UPPER(TRIM(name)) = 'EE MÁRIO SIDNEY FRANCESCHI' 
  AND UPPER(TRIM(city)) = 'ARAPORÃ' 
  AND inep_code IS NULL;

-- CESEC PROFESSORA ROMILDA DINIZ (CAMPINA VERDE) - INEP: 158429
UPDATE schools 
SET inep_code = '158429' 
WHERE UPPER(TRIM(name)) = 'CESEC PROFESSORA ROMILDA DINIZ' 
  AND UPPER(TRIM(city)) = 'CAMPINA VERDE' 
  AND inep_code IS NULL;

-- EE ANA CHAVES (CAMPINA VERDE) - INEP: 158356
UPDATE schools 
SET inep_code = '158356' 
WHERE UPPER(TRIM(name)) = 'EE ANA CHAVES' 
  AND UPPER(TRIM(city)) = 'CAMPINA VERDE' 
  AND inep_code IS NULL;

-- EE DOUTOR NICODEMUS DE MACEDO (CAMPINA VERDE) - INEP: 319147
UPDATE schools 
SET inep_code = '319147' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR NICODEMUS DE MACEDO' 
  AND UPPER(TRIM(city)) = 'CAMPINA VERDE' 
  AND inep_code IS NULL;

-- EE NOSSA SENHORA DAS GRAÇAS (CAMPINA VERDE) - INEP: 158399
UPDATE schools 
SET inep_code = '158399' 
WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DAS GRAÇAS' 
  AND UPPER(TRIM(city)) = 'CAMPINA VERDE' 
  AND inep_code IS NULL;

-- EE OLINDA CORREA BORGES (CAMPINA VERDE) - INEP: 158437
UPDATE schools 
SET inep_code = '158437' 
WHERE UPPER(TRIM(name)) = 'EE OLINDA CORREA BORGES' 
  AND UPPER(TRIM(city)) = 'CAMPINA VERDE' 
  AND inep_code IS NULL;

-- EE NÉLSON SOARES DE OLIVEIRA (INDIANÓPOLIS) - INEP: 166871
UPDATE schools 
SET inep_code = '166871' 
WHERE UPPER(TRIM(name)) = 'EE NÉLSON SOARES DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'INDIANÓPOLIS' 
  AND inep_code IS NULL;

-- EE EUFRAUSINA DA COSTA ARAÚJO (MONTE ALEGRE DE MINAS) - INEP: 166961
UPDATE schools 
SET inep_code = '166961' 
WHERE UPPER(TRIM(name)) = 'EE EUFRAUSINA DA COSTA ARAÚJO' 
  AND UPPER(TRIM(city)) = 'MONTE ALEGRE DE MINAS' 
  AND inep_code IS NULL;

-- EE MONTE ALEGRE DE MINAS (MONTE ALEGRE DE MINAS) - INEP: 166936
UPDATE schools 
SET inep_code = '166936' 
WHERE UPPER(TRIM(name)) = 'EE MONTE ALEGRE DE MINAS' 
  AND UPPER(TRIM(city)) = 'MONTE ALEGRE DE MINAS' 
  AND inep_code IS NULL;

-- EE TANCREDO MARTINS (MONTE ALEGRE DE MINAS) - INEP: 166952
UPDATE schools 
SET inep_code = '166952' 
WHERE UPPER(TRIM(name)) = 'EE TANCREDO MARTINS' 
  AND UPPER(TRIM(city)) = 'MONTE ALEGRE DE MINAS' 
  AND inep_code IS NULL;

-- EE JOSIAS PINTO (NOVA PONTE) - INEP: 166979
UPDATE schools 
SET inep_code = '166979' 
WHERE UPPER(TRIM(name)) = 'EE JOSIAS PINTO' 
  AND UPPER(TRIM(city)) = 'NOVA PONTE' 
  AND inep_code IS NULL;

-- EE CORONEL PEDRO NERY (PRATA) - INEP: 319163
UPDATE schools 
SET inep_code = '319163' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL PEDRO NERY' 
  AND UPPER(TRIM(city)) = 'PRATA' 
  AND inep_code IS NULL;

-- EE DO PRATA (PRATA) - INEP: 167045
UPDATE schools 
SET inep_code = '167045' 
WHERE UPPER(TRIM(name)) = 'EE DO PRATA' 
  AND UPPER(TRIM(city)) = 'PRATA' 
  AND inep_code IS NULL;

-- EE NORALDINO LIMA (PRATA) - INEP: 319171
UPDATE schools 
SET inep_code = '319171' 
WHERE UPPER(TRIM(name)) = 'EE NORALDINO LIMA' 
  AND UPPER(TRIM(city)) = 'PRATA' 
  AND inep_code IS NULL;

-- EE PROFESSOR VALENTIN (PRATA) - INEP: 167053
UPDATE schools 
SET inep_code = '167053' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR VALENTIN' 
  AND UPPER(TRIM(city)) = 'PRATA' 
  AND inep_code IS NULL;

-- EE ANA ESTERLITA ALVES (TUPACIGUARA) - INEP: 167118
UPDATE schools 
SET inep_code = '167118' 
WHERE UPPER(TRIM(name)) = 'EE ANA ESTERLITA ALVES' 
  AND UPPER(TRIM(city)) = 'TUPACIGUARA' 
  AND inep_code IS NULL;

-- EE BRAULINO MAMEDE (TUPACIGUARA) - INEP: 167185
UPDATE schools 
SET inep_code = '167185' 
WHERE UPPER(TRIM(name)) = 'EE BRAULINO MAMEDE' 
  AND UPPER(TRIM(city)) = 'TUPACIGUARA' 
  AND inep_code IS NULL;

-- EE CLERTAN MOREIRA DO VALE (TUPACIGUARA) - INEP: 167169
UPDATE schools 
SET inep_code = '167169' 
WHERE UPPER(TRIM(name)) = 'EE CLERTAN MOREIRA DO VALE' 
  AND UPPER(TRIM(city)) = 'TUPACIGUARA' 
  AND inep_code IS NULL;

-- EE DE ENSINO MÉDIO (TUPACIGUARA) - INEP: 361305
UPDATE schools 
SET inep_code = '361305' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' 
  AND UPPER(TRIM(city)) = 'TUPACIGUARA' 
  AND inep_code IS NULL;

-- EE SEBASTIÃO DIAS FERRAZ (TUPACIGUARA) - INEP: 167193
UPDATE schools 
SET inep_code = '167193' 
WHERE UPPER(TRIM(name)) = 'EE SEBASTIÃO DIAS FERRAZ' 
  AND UPPER(TRIM(city)) = 'TUPACIGUARA' 
  AND inep_code IS NULL;

-- CESEC DE UBERLÂNDIA (UBERLÂNDIA) - INEP: 167835
UPDATE schools 
SET inep_code = '167835' 
WHERE UPPER(TRIM(name)) = 'CESEC DE UBERLÂNDIA' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- COLÉGIO TIRADENTES PMMG (UBERLÂNDIA) - INEP: 362298
UPDATE schools 
SET inep_code = '362298' 
WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- CONSERVATÓRIO EST MÚSICA CORA PAVAN CAPPARELLI (UBERLÂNDIA) - INEP: 167452
UPDATE schools 
SET inep_code = '167452' 
WHERE UPPER(TRIM(name)) = 'CONSERVATÓRIO EST MÚSICA CORA PAVAN CAPPARELLI' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE 13 DE MAIO (UBERLÂNDIA) - INEP: 167657
UPDATE schools 
SET inep_code = '167657' 
WHERE UPPER(TRIM(name)) = 'EE 13 DE MAIO' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE AFONSO ARINOS (UBERLÂNDIA) - INEP: 167240
UPDATE schools 
SET inep_code = '167240' 
WHERE UPPER(TRIM(name)) = 'EE AFONSO ARINOS' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE ALDA MOTA BATISTA (UBERLÂNDIA) - INEP: 167282
UPDATE schools 
SET inep_code = '167282' 
WHERE UPPER(TRIM(name)) = 'EE ALDA MOTA BATISTA' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE AMADOR NAVES (UBERLÂNDIA) - INEP: 167363
UPDATE schools 
SET inep_code = '167363' 
WHERE UPPER(TRIM(name)) = 'EE AMADOR NAVES' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE AMÉRICO RENÉ GIANNETTI (UBERLÂNDIA) - INEP: 167321
UPDATE schools 
SET inep_code = '167321' 
WHERE UPPER(TRIM(name)) = 'EE AMÉRICO RENÉ GIANNETTI' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE ÂNGELA TEIXEIRA DA SILVA (UBERLÂNDIA) - INEP: 167401
UPDATE schools 
SET inep_code = '167401' 
WHERE UPPER(TRIM(name)) = 'EE ÂNGELA TEIXEIRA DA SILVA' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE ANGELINO PAVAN (UBERLÂNDIA) - INEP: 167461
UPDATE schools 
SET inep_code = '167461' 
WHERE UPPER(TRIM(name)) = 'EE ANGELINO PAVAN' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE ANTÔNIO LUIS BASTOS (UBERLÂNDIA) - INEP: 167487
UPDATE schools 
SET inep_code = '167487' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO LUIS BASTOS' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE ANTÔNIO THOMAZ FERREIRA DE REZENDE (UBERLÂNDIA) - INEP: 167771
UPDATE schools 
SET inep_code = '167771' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO THOMAZ FERREIRA DE REZENDE' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE BOM JESUS (UBERLÂNDIA) - INEP: 167525
UPDATE schools 
SET inep_code = '167525' 
WHERE UPPER(TRIM(name)) = 'EE BOM JESUS' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE BUENO BRANDÃO (UBERLÂNDIA) - INEP: 167568
UPDATE schools 
SET inep_code = '167568' 
WHERE UPPER(TRIM(name)) = 'EE BUENO BRANDÃO' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE CLARIMUNDO CARNEIRO (UBERLÂNDIA) - INEP: 167681
UPDATE schools 
SET inep_code = '167681' 
WHERE UPPER(TRIM(name)) = 'EE CLARIMUNDO CARNEIRO' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE CORONEL JOSE TEOFILO CARNEIRO (UBERLÂNDIA) - INEP: 167720
UPDATE schools 
SET inep_code = '167720' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL JOSE TEOFILO CARNEIRO' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE CUSTÓDIO DA COSTA PEREIRA (UBERLÂNDIA) - INEP: 167223
UPDATE schools 
SET inep_code = '167223' 
WHERE UPPER(TRIM(name)) = 'EE CUSTÓDIO DA COSTA PEREIRA' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE DA CIDADE INDUSTRIAL (UBERLÂNDIA) - INEP: 167649
UPDATE schools 
SET inep_code = '167649' 
WHERE UPPER(TRIM(name)) = 'EE DA CIDADE INDUSTRIAL' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE DE ENSINO FUNDAMENTAL E MÉDIO (UBERLÂNDIA) - INEP: 338893
UPDATE schools 
SET inep_code = '338893' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL E MÉDIO' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE DE UBERLÂNDIA (UBERLÂNDIA) - INEP: 167690
UPDATE schools 
SET inep_code = '167690' 
WHERE UPPER(TRIM(name)) = 'EE DE UBERLÂNDIA' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE DO BAIRRO JARDIM DAS PALMEIRAS (UBERLÂNDIA) - INEP: 167665
UPDATE schools 
SET inep_code = '167665' 
WHERE UPPER(TRIM(name)) = 'EE DO BAIRRO JARDIM DAS PALMEIRAS' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE DO BAIRRO MARAVILHA (UBERLÂNDIA) - INEP: 167789
UPDATE schools 
SET inep_code = '167789' 
WHERE UPPER(TRIM(name)) = 'EE DO BAIRRO MARAVILHA' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE DO PARQUE SÃO JORGE (UBERLÂNDIA) - INEP: 167797
UPDATE schools 
SET inep_code = '167797' 
WHERE UPPER(TRIM(name)) = 'EE DO PARQUE SÃO JORGE' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE DONA ALEXANDRA PEDREIRO (UBERLÂNDIA) - INEP: 167801
UPDATE schools 
SET inep_code = '167801' 
WHERE UPPER(TRIM(name)) = 'EE DONA ALEXANDRA PEDREIRO' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE DR DUARTE PIMENTEL DE ULHOA (UBERLÂNDIA) - INEP: 167827
UPDATE schools 
SET inep_code = '167827' 
WHERE UPPER(TRIM(name)) = 'EE DR DUARTE PIMENTEL DE ULHOA' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE ENÉAS DE OLIVEIRA GUIMARÃES (UBERLÂNDIA) - INEP: 167444
UPDATE schools 
SET inep_code = '167444' 
WHERE UPPER(TRIM(name)) = 'EE ENÉAS DE OLIVEIRA GUIMARÃES' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE ENÉIAS VASCONCELOS (UBERLÂNDIA) - INEP: 167215
UPDATE schools 
SET inep_code = '167215' 
WHERE UPPER(TRIM(name)) = 'EE ENÉIAS VASCONCELOS' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE FELISBERTO ALVES CARREJO (UBERLÂNDIA) - INEP: 167231
UPDATE schools 
SET inep_code = '167231' 
WHERE UPPER(TRIM(name)) = 'EE FELISBERTO ALVES CARREJO' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE FREI EGÍDIO PARISI (UBERLÂNDIA) - INEP: 167584
UPDATE schools 
SET inep_code = '167584' 
WHERE UPPER(TRIM(name)) = 'EE FREI EGÍDIO PARISI' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE GUIOMAR DE FREITAS COSTA (UBERLÂNDIA) - INEP: 167258
UPDATE schools 
SET inep_code = '167258' 
WHERE UPPER(TRIM(name)) = 'EE GUIOMAR DE FREITAS COSTA' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE HERCÍLIA MARTINS REZENDE (UBERLÂNDIA) - INEP: 167703
UPDATE schools 
SET inep_code = '167703' 
WHERE UPPER(TRIM(name)) = 'EE HERCÍLIA MARTINS REZENDE' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE HONÓRIO GUIMARÃES (UBERLÂNDIA) - INEP: 167274
UPDATE schools 
SET inep_code = '167274' 
WHERE UPPER(TRIM(name)) = 'EE HONÓRIO GUIMARÃES' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE HORTÊNCIO DINIZ (UBERLÂNDIA) - INEP: 167266
UPDATE schools 
SET inep_code = '167266' 
WHERE UPPER(TRIM(name)) = 'EE HORTÊNCIO DINIZ' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE IGNÁCIO PAES LEME (UBERLÂNDIA) - INEP: 167291
UPDATE schools 
SET inep_code = '167291' 
WHERE UPPER(TRIM(name)) = 'EE IGNÁCIO PAES LEME' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE JARDIM IPANEMA (UBERLÂNDIA) - INEP: 167878
UPDATE schools 
SET inep_code = '167878' 
WHERE UPPER(TRIM(name)) = 'EE JARDIM IPANEMA' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE JERÔNIMO ARANTES (UBERLÂNDIA) - INEP: 167606
UPDATE schools 
SET inep_code = '167606' 
WHERE UPPER(TRIM(name)) = 'EE JERÔNIMO ARANTES' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE JOÃO REZENDE (UBERLÂNDIA) - INEP: 167622
UPDATE schools 
SET inep_code = '167622' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO REZENDE' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE JOAQUIM SARAIVA (UBERLÂNDIA) - INEP: 167312
UPDATE schools 
SET inep_code = '167312' 
WHERE UPPER(TRIM(name)) = 'EE JOAQUIM SARAIVA' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE JOSÉ GOMES JUNQUEIRA (UBERLÂNDIA) - INEP: 207403
UPDATE schools 
SET inep_code = '207403' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ GOMES JUNQUEIRA' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE JOSÉ ZACHARIAS JUNQUEIRA (UBERLÂNDIA) - INEP: 167355
UPDATE schools 
SET inep_code = '167355' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ ZACHARIAS JUNQUEIRA' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE LOURDES DE CARVALHO (UBERLÂNDIA) - INEP: 167509
UPDATE schools 
SET inep_code = '167509' 
WHERE UPPER(TRIM(name)) = 'EE LOURDES DE CARVALHO' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE MARECHAL CASTELO BRANCO (UBERLÂNDIA) - INEP: 167371
UPDATE schools 
SET inep_code = '167371' 
WHERE UPPER(TRIM(name)) = 'EE MARECHAL CASTELO BRANCO' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE MARIA DA CONCEIÇÃO BARBOSA DE SOUZA (UBERLÂNDIA) - INEP: 167410
UPDATE schools 
SET inep_code = '167410' 
WHERE UPPER(TRIM(name)) = 'EE MARIA DA CONCEIÇÃO BARBOSA DE SOUZA' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE MÁRIO PORTO (UBERLÂNDIA) - INEP: 167398
UPDATE schools 
SET inep_code = '167398' 
WHERE UPPER(TRIM(name)) = 'EE MÁRIO PORTO' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE MÁRIO QUINTANA (UBERLÂNDIA) - INEP: 327964
UPDATE schools 
SET inep_code = '327964' 
WHERE UPPER(TRIM(name)) = 'EE MÁRIO QUINTANA' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE MESSIAS PEDREIRO (UBERLÂNDIA) - INEP: 167436
UPDATE schools 
SET inep_code = '167436' 
WHERE UPPER(TRIM(name)) = 'EE MESSIAS PEDREIRO' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE NEUZA REZENDE (UBERLÂNDIA) - INEP: 167746
UPDATE schools 
SET inep_code = '167746' 
WHERE UPPER(TRIM(name)) = 'EE NEUZA REZENDE' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE NO CONJUNTO HABITACIONAL CRUZEIRO DO SUL (UBERLÂNDIA) - INEP: 167347
UPDATE schools 
SET inep_code = '167347' 
WHERE UPPER(TRIM(name)) = 'EE NO CONJUNTO HABITACIONAL CRUZEIRO DO SUL' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE NOVO HORIZONTE-EDUCAÇÃO ESPECIAL (UBERLÂNDIA) - INEP: 167851
UPDATE schools 
SET inep_code = '167851' 
WHERE UPPER(TRIM(name)) = 'EE NOVO HORIZONTE-EDUCAÇÃO ESPECIAL' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE OSVALDO RESENDE (UBERLÂNDIA) - INEP: 167479
UPDATE schools 
SET inep_code = '167479' 
WHERE UPPER(TRIM(name)) = 'EE OSVALDO RESENDE' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE PADRE MARIO FORESTAN (UBERLÂNDIA) - INEP: 167495
UPDATE schools 
SET inep_code = '167495' 
WHERE UPPER(TRIM(name)) = 'EE PADRE MARIO FORESTAN' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE PRESIDENTE JUSCELINO KUBITSCHEK (UBERLÂNDIA) - INEP: 167754
UPDATE schools 
SET inep_code = '167754' 
WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE JUSCELINO KUBITSCHEK' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE PRESIDENTE TANCREDO NEVES (UBERLÂNDIA) - INEP: 167711
UPDATE schools 
SET inep_code = '167711' 
WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE TANCREDO NEVES' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE PROFESSOR EDERLINDO LANNES BERNARDES (UBERLÂNDIA) - INEP: 167843
UPDATE schools 
SET inep_code = '167843' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR EDERLINDO LANNES BERNARDES' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE PROFESSOR INÁCIO CASTILHO (UBERLÂNDIA) - INEP: 167541
UPDATE schools 
SET inep_code = '167541' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR INÁCIO CASTILHO' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE PROFESSOR JOSÉ IGNÁCIO DE SOUSA (UBERLÂNDIA) - INEP: 167339
UPDATE schools 
SET inep_code = '167339' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOSÉ IGNÁCIO DE SOUSA' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE PROFESSOR LEÔNIDAS DE CASTRO SERRA (UBERLÂNDIA) - INEP: 167380
UPDATE schools 
SET inep_code = '167380' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR LEÔNIDAS DE CASTRO SERRA' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE PROFESSOR NELSON CUPERTINO (UBERLÂNDIA) - INEP: 167428
UPDATE schools 
SET inep_code = '167428' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR NELSON CUPERTINO' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE PROFESSOR PAULO FREIRE (UBERLÂNDIA) - INEP: 327956
UPDATE schools 
SET inep_code = '327956' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR PAULO FREIRE' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE PROFESSORA ALICE PAES (UBERLÂNDIA) - INEP: 167517
UPDATE schools 
SET inep_code = '167517' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ALICE PAES' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE PROFESSORA JUVENÍLIA  FERREIRA DOS SANTOS (UBERLÂNDIA) - INEP: 167304
UPDATE schools 
SET inep_code = '167304' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA JUVENÍLIA FERREIRA DOS SANTOS' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE RIO DAS PEDRAS (UBERLÂNDIA) - INEP: 167533
UPDATE schools 
SET inep_code = '167533' 
WHERE UPPER(TRIM(name)) = 'EE RIO DAS PEDRAS' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE ROTARY (UBERLÂNDIA) - INEP: 167550
UPDATE schools 
SET inep_code = '167550' 
WHERE UPPER(TRIM(name)) = 'EE ROTARY' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE SEGISMUNDO PEREIRA (UBERLÂNDIA) - INEP: 167614
UPDATE schools 
SET inep_code = '167614' 
WHERE UPPER(TRIM(name)) = 'EE SEGISMUNDO PEREIRA' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE SEIS DE JUNHO (UBERLÂNDIA) - INEP: 167576
UPDATE schools 
SET inep_code = '167576' 
WHERE UPPER(TRIM(name)) = 'EE SEIS DE JUNHO' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE SÉRGIO DE FREITAS PACHECO (UBERLÂNDIA) - INEP: 167592
UPDATE schools 
SET inep_code = '167592' 
WHERE UPPER(TRIM(name)) = 'EE SÉRGIO DE FREITAS PACHECO' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE SETE DE SETEMBRO (UBERLÂNDIA) - INEP: 167631
UPDATE schools 
SET inep_code = '167631' 
WHERE UPPER(TRIM(name)) = 'EE SETE DE SETEMBRO' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE TEOTÔNIO VILELA (UBERLÂNDIA) - INEP: 167738
UPDATE schools 
SET inep_code = '167738' 
WHERE UPPER(TRIM(name)) = 'EE TEOTÔNIO VILELA' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- EE TUBAL VILELA DA SILVA (UBERLÂNDIA) - INEP: 167673
UPDATE schools 
SET inep_code = '167673' 
WHERE UPPER(TRIM(name)) = 'EE TUBAL VILELA DA SILVA' 
  AND UPPER(TRIM(city)) = 'UBERLÂNDIA' 
  AND inep_code IS NULL;

-- CESEC AFONSO ARINOS (ARINOS) - INEP: 346268
UPDATE schools 
SET inep_code = '346268' 
WHERE UPPER(TRIM(name)) = 'CESEC AFONSO ARINOS' 
  AND UPPER(TRIM(city)) = 'ARINOS' 
  AND inep_code IS NULL;

-- EE CARMOSINA DURÃES MARTINS (ARINOS) - INEP: 108227
UPDATE schools 
SET inep_code = '108227' 
WHERE UPPER(TRIM(name)) = 'EE CARMOSINA DURÃES MARTINS' 
  AND UPPER(TRIM(city)) = 'ARINOS' 
  AND inep_code IS NULL;

-- EE CHICO MENDES (ARINOS) - INEP: 349291
UPDATE schools 
SET inep_code = '349291' 
WHERE UPPER(TRIM(name)) = 'EE CHICO MENDES' 
  AND UPPER(TRIM(city)) = 'ARINOS' 
  AND inep_code IS NULL;

-- EE GARIBALDINA FERNANDES VALADARES (ARINOS) - INEP: 108219
UPDATE schools 
SET inep_code = '108219' 
WHERE UPPER(TRIM(name)) = 'EE GARIBALDINA FERNANDES VALADARES' 
  AND UPPER(TRIM(city)) = 'ARINOS' 
  AND inep_code IS NULL;

-- EE MAJOR SAINT CLAIR FERNANDES VALADARES (ARINOS) - INEP: 108197
UPDATE schools 
SET inep_code = '108197' 
WHERE UPPER(TRIM(name)) = 'EE MAJOR SAINT CLAIR FERNANDES VALADARES' 
  AND UPPER(TRIM(city)) = 'ARINOS' 
  AND inep_code IS NULL;

-- EE PROFESSOR BENEVIDES (ARINOS) - INEP: 231860
UPDATE schools 
SET inep_code = '231860' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR BENEVIDES' 
  AND UPPER(TRIM(city)) = 'ARINOS' 
  AND inep_code IS NULL;

-- CESEC ESMÉRIA MARIA DO CARMO (BONFINÓPOLIS DE MINAS) - INEP: 108367
UPDATE schools 
SET inep_code = '108367' 
WHERE UPPER(TRIM(name)) = 'CESEC ESMÉRIA MARIA DO CARMO' 
  AND UPPER(TRIM(city)) = 'BONFINÓPOLIS DE MINAS' 
  AND inep_code IS NULL;

-- EE CÂNDIDO ULHÔA (BONFINÓPOLIS DE MINAS) - INEP: 108243
UPDATE schools 
SET inep_code = '108243' 
WHERE UPPER(TRIM(name)) = 'EE CÂNDIDO ULHÔA' 
  AND UPPER(TRIM(city)) = 'BONFINÓPOLIS DE MINAS' 
  AND inep_code IS NULL;

-- EE ANÁLIA CARNEIRO DOS SANTOS (BURITIS) - INEP: 246204
UPDATE schools 
SET inep_code = '246204' 
WHERE UPPER(TRIM(name)) = 'EE ANÁLIA CARNEIRO DOS SANTOS' 
  AND UPPER(TRIM(city)) = 'BURITIS' 
  AND inep_code IS NULL;

-- EE ARGEMIRO ANTÔNIO PRADO (BURITIS) - INEP: 108413
UPDATE schools 
SET inep_code = '108413' 
WHERE UPPER(TRIM(name)) = 'EE ARGEMIRO ANTÔNIO PRADO' 
  AND UPPER(TRIM(city)) = 'BURITIS' 
  AND inep_code IS NULL;

-- EE JOSÉ GOMES PIMENTEL (BURITIS) - INEP: 108430
UPDATE schools 
SET inep_code = '108430' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ GOMES PIMENTEL' 
  AND UPPER(TRIM(city)) = 'BURITIS' 
  AND inep_code IS NULL;

-- EE SÃO DOMINGOS (BURITIS) - INEP: 108421
UPDATE schools 
SET inep_code = '108421' 
WHERE UPPER(TRIM(name)) = 'EE SÃO DOMINGOS' 
  AND UPPER(TRIM(city)) = 'BURITIS' 
  AND inep_code IS NULL;

-- EE DEPUTADO EDUARDO LUCAS (CABECEIRA GRANDE) - INEP: 109100
UPDATE schools 
SET inep_code = '109100' 
WHERE UPPER(TRIM(name)) = 'EE DEPUTADO EDUARDO LUCAS' 
  AND UPPER(TRIM(city)) = 'CABECEIRA GRANDE' 
  AND inep_code IS NULL;

-- EE JUVENAL DIOGO PIRES (CABECEIRA GRANDE) - INEP: 322598
UPDATE schools 
SET inep_code = '322598' 
WHERE UPPER(TRIM(name)) = 'EE JUVENAL DIOGO PIRES' 
  AND UPPER(TRIM(city)) = 'CABECEIRA GRANDE' 
  AND inep_code IS NULL;

-- EE DOM BOSCO (DOM BOSCO) - INEP: 108375
UPDATE schools 
SET inep_code = '108375' 
WHERE UPPER(TRIM(name)) = 'EE DOM BOSCO' 
  AND UPPER(TRIM(city)) = 'DOM BOSCO' 
  AND inep_code IS NULL;

-- EE MARTINHO ANTÔNIO ORNELAS (FORMOSO) - INEP: 108456
UPDATE schools 
SET inep_code = '108456' 
WHERE UPPER(TRIM(name)) = 'EE MARTINHO ANTÔNIO ORNELAS' 
  AND UPPER(TRIM(city)) = 'FORMOSO' 
  AND inep_code IS NULL;

-- EE NOSSA SENHORA DE ABADIA (FORMOSO) - INEP: 205559
UPDATE schools 
SET inep_code = '205559' 
WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DE ABADIA' 
  AND UPPER(TRIM(city)) = 'FORMOSO' 
  AND inep_code IS NULL;

-- EE ALVARENGA PEIXOTO (NATALÂNDIA) - INEP: 108383
UPDATE schools 
SET inep_code = '108383' 
WHERE UPPER(TRIM(name)) = 'EE ALVARENGA PEIXOTO' 
  AND UPPER(TRIM(city)) = 'NATALÂNDIA' 
  AND inep_code IS NULL;

-- CESEC JÚLIO MARTINS FERREIRA (UNAÍ) - INEP: 109070
UPDATE schools 
SET inep_code = '109070' 
WHERE UPPER(TRIM(name)) = 'CESEC JÚLIO MARTINS FERREIRA' 
  AND UPPER(TRIM(city)) = 'UNAÍ' 
  AND inep_code IS NULL;

-- EE DELVITO ALVES DA SILVA (UNAÍ) - INEP: 213292
UPDATE schools 
SET inep_code = '213292' 
WHERE UPPER(TRIM(name)) = 'EE DELVITO ALVES DA SILVA' 
  AND UPPER(TRIM(city)) = 'UNAÍ' 
  AND inep_code IS NULL;

-- EE DOM ELISEU (UNAÍ) - INEP: 108987
UPDATE schools 
SET inep_code = '108987' 
WHERE UPPER(TRIM(name)) = 'EE DOM ELISEU' 
  AND UPPER(TRIM(city)) = 'UNAÍ' 
  AND inep_code IS NULL;

-- EE DOMINGOS PINTO BROCHADO (UNAÍ) - INEP: 108995
UPDATE schools 
SET inep_code = '108995' 
WHERE UPPER(TRIM(name)) = 'EE DOMINGOS PINTO BROCHADO' 
  AND UPPER(TRIM(city)) = 'UNAÍ' 
  AND inep_code IS NULL;

-- EE ELISA DE OLIVEIRA CAMPOS (UNAÍ) - INEP: 342475
UPDATE schools 
SET inep_code = '342475' 
WHERE UPPER(TRIM(name)) = 'EE ELISA DE OLIVEIRA CAMPOS' 
  AND UPPER(TRIM(city)) = 'UNAÍ' 
  AND inep_code IS NULL;

-- EE IZABEL CAMPOS MARTINS (UNAÍ) - INEP: 245836
UPDATE schools 
SET inep_code = '245836' 
WHERE UPPER(TRIM(name)) = 'EE IZABEL CAMPOS MARTINS' 
  AND UPPER(TRIM(city)) = 'UNAÍ' 
  AND inep_code IS NULL;

-- EE JUVÊNCIO MARTINS FERREIRA (UNAÍ) - INEP: 239399
UPDATE schools 
SET inep_code = '239399' 
WHERE UPPER(TRIM(name)) = 'EE JUVÊNCIO MARTINS FERREIRA' 
  AND UPPER(TRIM(city)) = 'UNAÍ' 
  AND inep_code IS NULL;

-- EE MANOELA FARIA SOARES (UNAÍ) - INEP: 109037
UPDATE schools 
SET inep_code = '109037' 
WHERE UPPER(TRIM(name)) = 'EE MANOELA FARIA SOARES' 
  AND UPPER(TRIM(city)) = 'UNAÍ' 
  AND inep_code IS NULL;

-- EE MARIA ASSUNES GONÇALVES (UNAÍ) - INEP: 109045
UPDATE schools 
SET inep_code = '109045' 
WHERE UPPER(TRIM(name)) = 'EE MARIA ASSUNES GONÇALVES' 
  AND UPPER(TRIM(city)) = 'UNAÍ' 
  AND inep_code IS NULL;

-- EE MÚCIO DE CASTRO ALVES (UNAÍ) - INEP: 330698
UPDATE schools 
SET inep_code = '330698' 
WHERE UPPER(TRIM(name)) = 'EE MÚCIO DE CASTRO ALVES' 
  AND UPPER(TRIM(city)) = 'UNAÍ' 
  AND inep_code IS NULL;

-- EE TANCREDO DE ALMEIDA NEVES (UNAÍ) - INEP: 109053
UPDATE schools 
SET inep_code = '109053' 
WHERE UPPER(TRIM(name)) = 'EE TANCREDO DE ALMEIDA NEVES' 
  AND UPPER(TRIM(city)) = 'UNAÍ' 
  AND inep_code IS NULL;

-- EE TEÓFILO MARTINS FERREIRA (UNAÍ) - INEP: 109002
UPDATE schools 
SET inep_code = '109002' 
WHERE UPPER(TRIM(name)) = 'EE TEÓFILO MARTINS FERREIRA' 
  AND UPPER(TRIM(city)) = 'UNAÍ' 
  AND inep_code IS NULL;

-- EE VIGÁRIO TORRES (UNAÍ) - INEP: 109011
UPDATE schools 
SET inep_code = '109011' 
WHERE UPPER(TRIM(name)) = 'EE VIGÁRIO TORRES' 
  AND UPPER(TRIM(city)) = 'UNAÍ' 
  AND inep_code IS NULL;

-- EE VIRGÍLIO DE MELO FRANCO (UNAÍ) - INEP: 109029
UPDATE schools 
SET inep_code = '109029' 
WHERE UPPER(TRIM(name)) = 'EE VIRGÍLIO DE MELO FRANCO' 
  AND UPPER(TRIM(city)) = 'UNAÍ' 
  AND inep_code IS NULL;

-- EE DARCI RIBEIRO (URUANA DE MINAS) - INEP: 322601
UPDATE schools 
SET inep_code = '322601' 
WHERE UPPER(TRIM(name)) = 'EE DARCI RIBEIRO' 
  AND UPPER(TRIM(city)) = 'URUANA DE MINAS' 
  AND inep_code IS NULL;

-- EE CORONEL JOSÉ BENTO (ALFENAS) - INEP: 170755
UPDATE schools 
SET inep_code = '170755' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL JOSÉ BENTO' 
  AND UPPER(TRIM(city)) = 'ALFENAS' 
  AND inep_code IS NULL;

-- EE DIRCE MOURA LEITE (ALFENAS) - INEP: 170828
UPDATE schools 
SET inep_code = '170828' 
WHERE UPPER(TRIM(name)) = 'EE DIRCE MOURA LEITE' 
  AND UPPER(TRIM(city)) = 'ALFENAS' 
  AND inep_code IS NULL;

-- EE DOUTOR ARLINDO SILVEIRA FILHO (ALFENAS) - INEP: 170780
UPDATE schools 
SET inep_code = '170780' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR ARLINDO SILVEIRA FILHO' 
  AND UPPER(TRIM(city)) = 'ALFENAS' 
  AND inep_code IS NULL;

-- EE DOUTOR EMÍLIO SILVEIRA (ALFENAS) - INEP: 170798
UPDATE schools 
SET inep_code = '170798' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR EMÍLIO SILVEIRA' 
  AND UPPER(TRIM(city)) = 'ALFENAS' 
  AND inep_code IS NULL;

-- EE DOUTOR NAPOLEÃO SALLES (ALFENAS) - INEP: 170887
UPDATE schools 
SET inep_code = '170887' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR NAPOLEÃO SALLES' 
  AND UPPER(TRIM(city)) = 'ALFENAS' 
  AND inep_code IS NULL;

-- EE JUDITH VIANNA (ALFENAS) - INEP: 170810
UPDATE schools 
SET inep_code = '170810' 
WHERE UPPER(TRIM(name)) = 'EE JUDITH VIANNA' 
  AND UPPER(TRIM(city)) = 'ALFENAS' 
  AND inep_code IS NULL;

-- EE PADRE JOSÉ GRIMMINCK (ALFENAS) - INEP: 170895
UPDATE schools 
SET inep_code = '170895' 
WHERE UPPER(TRIM(name)) = 'EE PADRE JOSÉ GRIMMINCK' 
  AND UPPER(TRIM(city)) = 'ALFENAS' 
  AND inep_code IS NULL;

-- EE PREFEITO ISMAEL BRASIL CORRÊA (ALFENAS) - INEP: 170844
UPDATE schools 
SET inep_code = '170844' 
WHERE UPPER(TRIM(name)) = 'EE PREFEITO ISMAEL BRASIL CORRÊA' 
  AND UPPER(TRIM(city)) = 'ALFENAS' 
  AND inep_code IS NULL;

-- EE PROFESSOR LEVINDO LAMBERT (ALFENAS) - INEP: 170852
UPDATE schools 
SET inep_code = '170852' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR LEVINDO LAMBERT' 
  AND UPPER(TRIM(city)) = 'ALFENAS' 
  AND inep_code IS NULL;

-- EE PROFESSOR VIANA (ALFENAS) - INEP: 170861
UPDATE schools 
SET inep_code = '170861' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR VIANA' 
  AND UPPER(TRIM(city)) = 'ALFENAS' 
  AND inep_code IS NULL;

-- EE SAMUEL ENGEL (ALFENAS) - INEP: 170879
UPDATE schools 
SET inep_code = '170879' 
WHERE UPPER(TRIM(name)) = 'EE SAMUEL ENGEL' 
  AND UPPER(TRIM(city)) = 'ALFENAS' 
  AND inep_code IS NULL;

-- CESEC PROFESSORA SINHÁ LEITE (BOA ESPERANÇA) - INEP: 171280
UPDATE schools 
SET inep_code = '171280' 
WHERE UPPER(TRIM(name)) = 'CESEC PROFESSORA SINHÁ LEITE' 
  AND UPPER(TRIM(city)) = 'BOA ESPERANÇA' 
  AND inep_code IS NULL;

-- EE ACHILLES NAVES (BOA ESPERANÇA) - INEP: 171271
UPDATE schools 
SET inep_code = '171271' 
WHERE UPPER(TRIM(name)) = 'EE ACHILLES NAVES' 
  AND UPPER(TRIM(city)) = 'BOA ESPERANÇA' 
  AND inep_code IS NULL;

-- EE BELMIRO BRAGA (BOA ESPERANÇA) - INEP: 171107
UPDATE schools 
SET inep_code = '171107' 
WHERE UPPER(TRIM(name)) = 'EE BELMIRO BRAGA' 
  AND UPPER(TRIM(city)) = 'BOA ESPERANÇA' 
  AND inep_code IS NULL;

-- EE CASIMIRO SILVA (BOA ESPERANÇA) - INEP: 171123
UPDATE schools 
SET inep_code = '171123' 
WHERE UPPER(TRIM(name)) = 'EE CASIMIRO SILVA' 
  AND UPPER(TRIM(city)) = 'BOA ESPERANÇA' 
  AND inep_code IS NULL;

-- EE DOUTOR JOAQUIM VILELA (BOA ESPERANÇA) - INEP: 171174
UPDATE schools 
SET inep_code = '171174' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR JOAQUIM VILELA' 
  AND UPPER(TRIM(city)) = 'BOA ESPERANÇA' 
  AND inep_code IS NULL;

-- EE DOUTOR SÁ BRITO (BOA ESPERANÇA) - INEP: 171191
UPDATE schools 
SET inep_code = '171191' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR SÁ BRITO' 
  AND UPPER(TRIM(city)) = 'BOA ESPERANÇA' 
  AND inep_code IS NULL;

-- EE PADRE JOÃO VIEIRA DA FONSECA (BOA ESPERANÇA) - INEP: 171212
UPDATE schools 
SET inep_code = '171212' 
WHERE UPPER(TRIM(name)) = 'EE PADRE JOÃO VIEIRA DA FONSECA' 
  AND UPPER(TRIM(city)) = 'BOA ESPERANÇA' 
  AND inep_code IS NULL;

-- EE PROFESSOR NESTOR LACERDA (BOA ESPERANÇA) - INEP: 229296
UPDATE schools 
SET inep_code = '229296' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR NESTOR LACERDA' 
  AND UPPER(TRIM(city)) = 'BOA ESPERANÇA' 
  AND inep_code IS NULL;

-- EE PROFESSORA SÍLVIA MESQUITA (BOA ESPERANÇA) - INEP: 171255
UPDATE schools 
SET inep_code = '171255' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA SÍLVIA MESQUITA' 
  AND UPPER(TRIM(city)) = 'BOA ESPERANÇA' 
  AND inep_code IS NULL;

-- EE CLÓVIS SALGADO (CAMBUQUIRA) - INEP: 171301
UPDATE schools 
SET inep_code = '171301' 
WHERE UPPER(TRIM(name)) = 'EE CLÓVIS SALGADO' 
  AND UPPER(TRIM(city)) = 'CAMBUQUIRA' 
  AND inep_code IS NULL;

-- EE MARIA UMBELINA DE ANDRADE GOMES (CAMBUQUIRA) - INEP: 171361
UPDATE schools 
SET inep_code = '171361' 
WHERE UPPER(TRIM(name)) = 'EE MARIA UMBELINA DE ANDRADE GOMES' 
  AND UPPER(TRIM(city)) = 'CAMBUQUIRA' 
  AND inep_code IS NULL;

-- EE DOM INOCÊNCIO (CAMPANHA) - INEP: 171468
UPDATE schools 
SET inep_code = '171468' 
WHERE UPPER(TRIM(name)) = 'EE DOM INOCÊNCIO' 
  AND UPPER(TRIM(city)) = 'CAMPANHA' 
  AND inep_code IS NULL;

-- EE VITAL BRASIL (CAMPANHA) - INEP: 171484
UPDATE schools 
SET inep_code = '171484' 
WHERE UPPER(TRIM(name)) = 'EE VITAL BRASIL' 
  AND UPPER(TRIM(city)) = 'CAMPANHA' 
  AND inep_code IS NULL;

-- EE ZOROASTRO DE OLIVEIRA (CAMPANHA) - INEP: 171492
UPDATE schools 
SET inep_code = '171492' 
WHERE UPPER(TRIM(name)) = 'EE ZOROASTRO DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'CAMPANHA' 
  AND inep_code IS NULL;

-- EE DR JOSÉ MESQUITA NETTO (CAMPO DO MEIO) - INEP: 171581
UPDATE schools 
SET inep_code = '171581' 
WHERE UPPER(TRIM(name)) = 'EE DR JOSÉ MESQUITA NETTO' 
  AND UPPER(TRIM(city)) = 'CAMPO DO MEIO' 
  AND inep_code IS NULL;

-- EE PADRE CHICO (CAMPO DO MEIO) - INEP: 171549
UPDATE schools 
SET inep_code = '171549' 
WHERE UPPER(TRIM(name)) = 'EE PADRE CHICO' 
  AND UPPER(TRIM(city)) = 'CAMPO DO MEIO' 
  AND inep_code IS NULL;

-- EE MONSENHOR TEÓFILO SAEZ (CAMPOS GERAIS) - INEP: 239143
UPDATE schools 
SET inep_code = '239143' 
WHERE UPPER(TRIM(name)) = 'EE MONSENHOR TEÓFILO SAEZ' 
  AND UPPER(TRIM(city)) = 'CAMPOS GERAIS' 
  AND inep_code IS NULL;

-- EE PADRE ANTÔNIO VIEIRA (CAMPOS GERAIS) - INEP: 171701
UPDATE schools 
SET inep_code = '171701' 
WHERE UPPER(TRIM(name)) = 'EE PADRE ANTÔNIO VIEIRA' 
  AND UPPER(TRIM(city)) = 'CAMPOS GERAIS' 
  AND inep_code IS NULL;

-- EE PROFESSOR EDUARDO DANIEL FERREIRA DIAS (CAMPOS GERAIS) - INEP: 171646
UPDATE schools 
SET inep_code = '171646' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR EDUARDO DANIEL FERREIRA DIAS' 
  AND UPPER(TRIM(city)) = 'CAMPOS GERAIS' 
  AND inep_code IS NULL;

-- EE PROFESSOR JOAQUIM JOSÉ DE OLIVEIRA (CAMPOS GERAIS) - INEP: 171689
UPDATE schools 
SET inep_code = '171689' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOAQUIM JOSÉ DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'CAMPOS GERAIS' 
  AND inep_code IS NULL;

-- EE PEDRO MESTRE (CARMO DA CACHOEIRA) - INEP: 171824
UPDATE schools 
SET inep_code = '171824' 
WHERE UPPER(TRIM(name)) = 'EE PEDRO MESTRE' 
  AND UPPER(TRIM(city)) = 'CARMO DA CACHOEIRA' 
  AND inep_code IS NULL;

-- EE PROFESSOR WANDERLEY FERREIRA DE REZENDE (CARMO DA CACHOEIRA) - INEP: 171786
UPDATE schools 
SET inep_code = '171786' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR WANDERLEY FERREIRA DE REZENDE' 
  AND UPPER(TRIM(city)) = 'CARMO DA CACHOEIRA' 
  AND inep_code IS NULL;

-- EE JOÃO DE PAULA CAPRONI (CARVALHÓPOLIS) - INEP: 171999
UPDATE schools 
SET inep_code = '171999' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO DE PAULA CAPRONI' 
  AND UPPER(TRIM(city)) = 'CARVALHÓPOLIS' 
  AND inep_code IS NULL;

-- EE PADRE ANCHIETA (COQUEIRAL) - INEP: 172316
UPDATE schools 
SET inep_code = '172316' 
WHERE UPPER(TRIM(name)) = 'EE PADRE ANCHIETA' 
  AND UPPER(TRIM(city)) = 'COQUEIRAL' 
  AND inep_code IS NULL;

-- EE PROFESSORA CELINA DE REZENDE VILELA (CORDISLÂNDIA) - INEP: 172375
UPDATE schools 
SET inep_code = '172375' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA CELINA DE REZENDE VILELA' 
  AND UPPER(TRIM(city)) = 'CORDISLÂNDIA' 
  AND inep_code IS NULL;

-- EE BRASILINO ALVES PEREIRA (ELÓI MENDES) - INEP: 172499
UPDATE schools 
SET inep_code = '172499' 
WHERE UPPER(TRIM(name)) = 'EE BRASILINO ALVES PEREIRA' 
  AND UPPER(TRIM(city)) = 'ELÓI MENDES' 
  AND inep_code IS NULL;

-- EE PROFESSORA NORMA DE BRITO PIEDADE MARTINS (ELÓI MENDES) - INEP: 172618
UPDATE schools 
SET inep_code = '172618' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA NORMA DE BRITO PIEDADE MARTINS' 
  AND UPPER(TRIM(city)) = 'ELÓI MENDES' 
  AND inep_code IS NULL;

-- EE SÃO LUIZ GONZAGA (ELÓI MENDES) - INEP: 319198
UPDATE schools 
SET inep_code = '319198' 
WHERE UPPER(TRIM(name)) = 'EE SÃO LUIZ GONZAGA' 
  AND UPPER(TRIM(city)) = 'ELÓI MENDES' 
  AND inep_code IS NULL;

-- EE TARGINO NOGUEIRA (ELÓI MENDES) - INEP: 172600
UPDATE schools 
SET inep_code = '172600' 
WHERE UPPER(TRIM(name)) = 'EE TARGINO NOGUEIRA' 
  AND UPPER(TRIM(city)) = 'ELÓI MENDES' 
  AND inep_code IS NULL;

-- EE PROFESSORA MARIA OLÍMPIA OLIVEIRA (FAMA) - INEP: 305006
UPDATE schools 
SET inep_code = '305006' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA OLÍMPIA OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'FAMA' 
  AND inep_code IS NULL;

-- EE DONA AGOSTINHA FLOR DE MARIA (GUAPÉ) - INEP: 172715
UPDATE schools 
SET inep_code = '172715' 
WHERE UPPER(TRIM(name)) = 'EE DONA AGOSTINHA FLOR DE MARIA' 
  AND UPPER(TRIM(city)) = 'GUAPÉ' 
  AND inep_code IS NULL;

-- EE DR LAURO CORREA DO AMARAL (GUAPÉ) - INEP: 172693
UPDATE schools 
SET inep_code = '172693' 
WHERE UPPER(TRIM(name)) = 'EE DR LAURO CORREA DO AMARAL' 
  AND UPPER(TRIM(city)) = 'GUAPÉ' 
  AND inep_code IS NULL;

-- EE PROFESSOR ANTÔNIO PASSOS SILVA (GUAPÉ) - INEP: 229326
UPDATE schools 
SET inep_code = '229326' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ANTÔNIO PASSOS SILVA' 
  AND UPPER(TRIM(city)) = 'GUAPÉ' 
  AND inep_code IS NULL;

-- EE NOSSA SENHORA APARECIDA (ILICÍNEA) - INEP: 172804
UPDATE schools 
SET inep_code = '172804' 
WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA APARECIDA' 
  AND UPPER(TRIM(city)) = 'ILICÍNEA' 
  AND inep_code IS NULL;

-- EE JOÃO DE ALMEIDA LISBOA (LAMBARI) - INEP: 173011
UPDATE schools 
SET inep_code = '173011' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO DE ALMEIDA LISBOA' 
  AND UPPER(TRIM(city)) = 'LAMBARI' 
  AND inep_code IS NULL;

-- EE JOÃO NUNES FERREIRA (LAMBARI) - INEP: 173029
UPDATE schools 
SET inep_code = '173029' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO NUNES FERREIRA' 
  AND UPPER(TRIM(city)) = 'LAMBARI' 
  AND inep_code IS NULL;

-- EE PROFESSORA MARIA RITA LISBOA PEREIRA SANTORO (LAMBARI) - INEP: 172987
UPDATE schools 
SET inep_code = '172987' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA RITA LISBOA PEREIRA SANTORO' 
  AND UPPER(TRIM(city)) = 'LAMBARI' 
  AND inep_code IS NULL;

-- EE PROFESSOR FABREGAS (LUMINÁRIAS) - INEP: 134287
UPDATE schools 
SET inep_code = '134287' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR FABREGAS' 
  AND UPPER(TRIM(city)) = 'LUMINÁRIAS' 
  AND inep_code IS NULL;

-- CESEC DOUTOR TANCREDO DE ALMEIDA NEVES (MACHADO) - INEP: 173100
UPDATE schools 
SET inep_code = '173100' 
WHERE UPPER(TRIM(name)) = 'CESEC DOUTOR TANCREDO DE ALMEIDA NEVES' 
  AND UPPER(TRIM(city)) = 'MACHADO' 
  AND inep_code IS NULL;

-- EE DE DOURADINHO (MACHADO) - INEP: 173223
UPDATE schools 
SET inep_code = '173223' 
WHERE UPPER(TRIM(name)) = 'EE DE DOURADINHO' 
  AND UPPER(TRIM(city)) = 'MACHADO' 
  AND inep_code IS NULL;

-- EE DOM PEDRO I (MACHADO) - INEP: 173215
UPDATE schools 
SET inep_code = '173215' 
WHERE UPPER(TRIM(name)) = 'EE DOM PEDRO I' 
  AND UPPER(TRIM(city)) = 'MACHADO' 
  AND inep_code IS NULL;

-- EE GABRIEL ODORICO (MACHADO) - INEP: 173045
UPDATE schools 
SET inep_code = '173045' 
WHERE UPPER(TRIM(name)) = 'EE GABRIEL ODORICO' 
  AND UPPER(TRIM(city)) = 'MACHADO' 
  AND inep_code IS NULL;

-- EE IRACEMA RODRIGUES (MACHADO) - INEP: 173061
UPDATE schools 
SET inep_code = '173061' 
WHERE UPPER(TRIM(name)) = 'EE IRACEMA RODRIGUES' 
  AND UPPER(TRIM(city)) = 'MACHADO' 
  AND inep_code IS NULL;

-- EE PAULINA RIGOTTI DE CASTRO (MACHADO) - INEP: 173088
UPDATE schools 
SET inep_code = '173088' 
WHERE UPPER(TRIM(name)) = 'EE PAULINA RIGOTTI DE CASTRO' 
  AND UPPER(TRIM(city)) = 'MACHADO' 
  AND inep_code IS NULL;

-- EE RUBENS GARCIA (MACHADO) - INEP: 173169
UPDATE schools 
SET inep_code = '173169' 
WHERE UPPER(TRIM(name)) = 'EE RUBENS GARCIA' 
  AND UPPER(TRIM(city)) = 'MACHADO' 
  AND inep_code IS NULL;

-- EE PADRE ROGÉRIO ABDALA (MONSENHOR PAULO) - INEP: 173266
UPDATE schools 
SET inep_code = '173266' 
WHERE UPPER(TRIM(name)) = 'EE PADRE ROGÉRIO ABDALA' 
  AND UPPER(TRIM(city)) = 'MONSENHOR PAULO' 
  AND inep_code IS NULL;

-- EE CORONEL JOAQUIM RIBEIRO (NEPOMUCENO) - INEP: 173282
UPDATE schools 
SET inep_code = '173282' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL JOAQUIM RIBEIRO' 
  AND UPPER(TRIM(city)) = 'NEPOMUCENO' 
  AND inep_code IS NULL;

-- EE DA FAZENDA BELA VISTA (NEPOMUCENO) - INEP: 173291
UPDATE schools 
SET inep_code = '173291' 
WHERE UPPER(TRIM(name)) = 'EE DA FAZENDA BELA VISTA' 
  AND UPPER(TRIM(city)) = 'NEPOMUCENO' 
  AND inep_code IS NULL;

-- EE DE NAZARÉ DE MINAS (NEPOMUCENO) - INEP: 173428
UPDATE schools 
SET inep_code = '173428' 
WHERE UPPER(TRIM(name)) = 'EE DE NAZARÉ DE MINAS' 
  AND UPPER(TRIM(city)) = 'NEPOMUCENO' 
  AND inep_code IS NULL;

-- EE DE SANTO ANTÔNIO DO CRUZEIRO (NEPOMUCENO) - INEP: 173436
UPDATE schools 
SET inep_code = '173436' 
WHERE UPPER(TRIM(name)) = 'EE DE SANTO ANTÔNIO DO CRUZEIRO' 
  AND UPPER(TRIM(city)) = 'NEPOMUCENO' 
  AND inep_code IS NULL;

-- EE DOUTOR ERNANE VILELA LIMA (NEPOMUCENO) - INEP: 173371
UPDATE schools 
SET inep_code = '173371' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR ERNANE VILELA LIMA' 
  AND UPPER(TRIM(city)) = 'NEPOMUCENO' 
  AND inep_code IS NULL;

-- EE LICAS DE LIMA (NEPOMUCENO) - INEP: 173380
UPDATE schools 
SET inep_code = '173380' 
WHERE UPPER(TRIM(name)) = 'EE LICAS DE LIMA' 
  AND UPPER(TRIM(city)) = 'NEPOMUCENO' 
  AND inep_code IS NULL;

-- EE PADRE PICCININI (PARAGUAÇU) - INEP: 173533
UPDATE schools 
SET inep_code = '173533' 
WHERE UPPER(TRIM(name)) = 'EE PADRE PICCININI' 
  AND UPPER(TRIM(city)) = 'PARAGUAÇU' 
  AND inep_code IS NULL;

-- EE PEDRO LEITE (PARAGUAÇU) - INEP: 173622
UPDATE schools 
SET inep_code = '173622' 
WHERE UPPER(TRIM(name)) = 'EE PEDRO LEITE' 
  AND UPPER(TRIM(city)) = 'PARAGUAÇU' 
  AND inep_code IS NULL;

-- EE PROFESSOR ALFREDO GALDINO (PARAGUAÇU) - INEP: 173631
UPDATE schools 
SET inep_code = '173631' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ALFREDO GALDINO' 
  AND UPPER(TRIM(city)) = 'PARAGUAÇU' 
  AND inep_code IS NULL;

-- EE DOUTOR LÉLIO DE ALMEIDA (POÇO FUNDO) - INEP: 173851
UPDATE schools 
SET inep_code = '173851' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR LÉLIO DE ALMEIDA' 
  AND UPPER(TRIM(city)) = 'POÇO FUNDO' 
  AND inep_code IS NULL;

-- EE JOSÉ BONIFÁCIO (POÇO FUNDO) - INEP: 173860
UPDATE schools 
SET inep_code = '173860' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ BONIFÁCIO' 
  AND UPPER(TRIM(city)) = 'POÇO FUNDO' 
  AND inep_code IS NULL;

-- EE SÃO MARCOS (POÇO FUNDO) - INEP: 173878
UPDATE schools 
SET inep_code = '173878' 
WHERE UPPER(TRIM(name)) = 'EE SÃO MARCOS' 
  AND UPPER(TRIM(city)) = 'POÇO FUNDO' 
  AND inep_code IS NULL;

-- EE DONA AUGUSTA (SANTANA DA VARGEM) - INEP: 174009
UPDATE schools 
SET inep_code = '174009' 
WHERE UPPER(TRIM(name)) = 'EE DONA AUGUSTA' 
  AND UPPER(TRIM(city)) = 'SANTANA DA VARGEM' 
  AND inep_code IS NULL;

-- EE PADRE JOÃO NEIVA (SANTANA DA VARGEM) - INEP: 173975
UPDATE schools 
SET inep_code = '173975' 
WHERE UPPER(TRIM(name)) = 'EE PADRE JOÃO NEIVA' 
  AND UPPER(TRIM(city)) = 'SANTANA DA VARGEM' 
  AND inep_code IS NULL;

-- EE PADRE JOSÉ RIBEIRO (SANTANA DA VARGEM) - INEP: 173983
UPDATE schools 
SET inep_code = '173983' 
WHERE UPPER(TRIM(name)) = 'EE PADRE JOSÉ RIBEIRO' 
  AND UPPER(TRIM(city)) = 'SANTANA DA VARGEM' 
  AND inep_code IS NULL;

-- EE PROFESSORA ALDA DE MOURA CARVALHO (SÃO BENTO ABADE) - INEP: 174017
UPDATE schools 
SET inep_code = '174017' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ALDA DE MOURA CARVALHO' 
  AND UPPER(TRIM(city)) = 'SÃO BENTO ABADE' 
  AND inep_code IS NULL;


COMMIT;
