-- Lote 7 de 7
-- Updates 1801 a 1839

BEGIN;

-- EE BÁRBARA HELIODORA (SÃO GONÇALO DO SAPUCAÍ) - INEP: 174033
UPDATE schools 
SET inep_code = '174033' 
WHERE UPPER(TRIM(name)) = 'EE BÁRBARA HELIODORA' 
  AND UPPER(TRIM(city)) = 'SÃO GONÇALO DO SAPUCAÍ' 
  AND inep_code IS NULL;

-- EE DOUTOR JOÃO PINHEIRO (SÃO GONÇALO DO SAPUCAÍ) - INEP: 174025
UPDATE schools 
SET inep_code = '174025' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR JOÃO PINHEIRO' 
  AND UPPER(TRIM(city)) = 'SÃO GONÇALO DO SAPUCAÍ' 
  AND inep_code IS NULL;

-- EE ESPERANÇA (SÃO GONÇALO DO SAPUCAÍ) - INEP: 174106
UPDATE schools 
SET inep_code = '174106' 
WHERE UPPER(TRIM(name)) = 'EE ESPERANÇA' 
  AND UPPER(TRIM(city)) = 'SÃO GONÇALO DO SAPUCAÍ' 
  AND inep_code IS NULL;

-- EE MINISTRO LUCIO DE MENDONÇA (SÃO GONÇALO DO SAPUCAÍ) - INEP: 174084
UPDATE schools 
SET inep_code = '174084' 
WHERE UPPER(TRIM(name)) = 'EE MINISTRO LUCIO DE MENDONÇA' 
  AND UPPER(TRIM(city)) = 'SÃO GONÇALO DO SAPUCAÍ' 
  AND inep_code IS NULL;

-- EE AMÉRICO DIAS PEREIRA (TRÊS CORAÇÕES) - INEP: 174416
UPDATE schools 
SET inep_code = '174416' 
WHERE UPPER(TRIM(name)) = 'EE AMÉRICO DIAS PEREIRA' 
  AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' 
  AND inep_code IS NULL;

-- EE BUENO BRANDÃO (TRÊS CORAÇÕES) - INEP: 174386
UPDATE schools 
SET inep_code = '174386' 
WHERE UPPER(TRIM(name)) = 'EE BUENO BRANDÃO' 
  AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' 
  AND inep_code IS NULL;

-- EE GODOFREDO RANGEL (TRÊS CORAÇÕES) - INEP: 174475
UPDATE schools 
SET inep_code = '174475' 
WHERE UPPER(TRIM(name)) = 'EE GODOFREDO RANGEL' 
  AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' 
  AND inep_code IS NULL;

-- EE HERBERT JOSÉ DE SOUZA (TRÊS CORAÇÕES) - INEP: 328316
UPDATE schools 
SET inep_code = '328316' 
WHERE UPPER(TRIM(name)) = 'EE HERBERT JOSÉ DE SOUZA' 
  AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' 
  AND inep_code IS NULL;

-- EE LUIZA GOMES LEMOS (TRÊS CORAÇÕES) - INEP: 174432
UPDATE schools 
SET inep_code = '174432' 
WHERE UPPER(TRIM(name)) = 'EE LUIZA GOMES LEMOS' 
  AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' 
  AND inep_code IS NULL;

-- EE MONSENHOR JOSÉ GUIMARÃES FONSECA (TRÊS CORAÇÕES) - INEP: 174459
UPDATE schools 
SET inep_code = '174459' 
WHERE UPPER(TRIM(name)) = 'EE MONSENHOR JOSÉ GUIMARÃES FONSECA' 
  AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' 
  AND inep_code IS NULL;

-- EE OLÍMPIA DE BRITO (TRÊS CORAÇÕES) - INEP: 174467
UPDATE schools 
SET inep_code = '174467' 
WHERE UPPER(TRIM(name)) = 'EE OLÍMPIA DE BRITO' 
  AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' 
  AND inep_code IS NULL;

-- EE PROFESSOR  CLÓVIS SALGADO (TRÊS CORAÇÕES) - INEP: 174394
UPDATE schools 
SET inep_code = '174394' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR CLÓVIS SALGADO' 
  AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' 
  AND inep_code IS NULL;

-- EE PROFESSOR FRANCO DA ROSA (TRÊS CORAÇÕES) - INEP: 174483
UPDATE schools 
SET inep_code = '174483' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR FRANCO DA ROSA' 
  AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' 
  AND inep_code IS NULL;

-- EE CÔNEGO JOSÉ MARIA (TRÊS PONTAS) - INEP: 174530
UPDATE schools 
SET inep_code = '174530' 
WHERE UPPER(TRIM(name)) = 'EE CÔNEGO JOSÉ MARIA' 
  AND UPPER(TRIM(city)) = 'TRÊS PONTAS' 
  AND inep_code IS NULL;

-- EE DEPUTADO TEODÓSIO BANDEIRA (TRÊS PONTAS) - INEP: 174688
UPDATE schools 
SET inep_code = '174688' 
WHERE UPPER(TRIM(name)) = 'EE DEPUTADO TEODÓSIO BANDEIRA' 
  AND UPPER(TRIM(city)) = 'TRÊS PONTAS' 
  AND inep_code IS NULL;

-- EE MONSENHOR JOÃO BATISTA DA SILVEIRA (TRÊS PONTAS) - INEP: 174785
UPDATE schools 
SET inep_code = '174785' 
WHERE UPPER(TRIM(name)) = 'EE MONSENHOR JOÃO BATISTA DA SILVEIRA' 
  AND UPPER(TRIM(city)) = 'TRÊS PONTAS' 
  AND inep_code IS NULL;

-- EE PREFEITO JACY JUNQUEIRA GAZOLA (TRÊS PONTAS) - INEP: 174700
UPDATE schools 
SET inep_code = '174700' 
WHERE UPPER(TRIM(name)) = 'EE PREFEITO JACY JUNQUEIRA GAZOLA' 
  AND UPPER(TRIM(city)) = 'TRÊS PONTAS' 
  AND inep_code IS NULL;

-- EE PRESIDENTE TANCREDO NEVES (TRÊS PONTAS) - INEP: 174831
UPDATE schools 
SET inep_code = '174831' 
WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE TANCREDO NEVES' 
  AND UPPER(TRIM(city)) = 'TRÊS PONTAS' 
  AND inep_code IS NULL;

-- EE PROFESSORA MARIA AUGUSTA VIEIRA CORREA (TRÊS PONTAS) - INEP: 174769
UPDATE schools 
SET inep_code = '174769' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA AUGUSTA VIEIRA CORREA' 
  AND UPPER(TRIM(city)) = 'TRÊS PONTAS' 
  AND inep_code IS NULL;

-- EE PROFESSORA MARIETA CASTRO (TRÊS PONTAS) - INEP: 174718
UPDATE schools 
SET inep_code = '174718' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIETA CASTRO' 
  AND UPPER(TRIM(city)) = 'TRÊS PONTAS' 
  AND inep_code IS NULL;

-- EE NOSSA SENHORA DA PIEDADE (TURVOLÂNDIA) - INEP: 174858
UPDATE schools 
SET inep_code = '174858' 
WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DA PIEDADE' 
  AND UPPER(TRIM(city)) = 'TURVOLÂNDIA' 
  AND inep_code IS NULL;

-- CONSERVATÓRIO ESTADUAL DE MÚSICA MAESTRO MARCILIANO BRAGA (VARGINHA) - INEP: 175111
UPDATE schools 
SET inep_code = '175111' 
WHERE UPPER(TRIM(name)) = 'CONSERVATÓRIO ESTADUAL DE MÚSICA MAESTRO MARCILIANO BRAGA' 
  AND UPPER(TRIM(city)) = 'VARGINHA' 
  AND inep_code IS NULL;

-- EE AFONSO PENA (VARGINHA) - INEP: 174882
UPDATE schools 
SET inep_code = '174882' 
WHERE UPPER(TRIM(name)) = 'EE AFONSO PENA' 
  AND UPPER(TRIM(city)) = 'VARGINHA' 
  AND inep_code IS NULL;

-- EE BRASIL (VARGINHA) - INEP: 174921
UPDATE schools 
SET inep_code = '174921' 
WHERE UPPER(TRIM(name)) = 'EE BRASIL' 
  AND UPPER(TRIM(city)) = 'VARGINHA' 
  AND inep_code IS NULL;

-- EE CORAÇÃO DE JESUS (VARGINHA) - INEP: 175099
UPDATE schools 
SET inep_code = '175099' 
WHERE UPPER(TRIM(name)) = 'EE CORAÇÃO DE JESUS' 
  AND UPPER(TRIM(city)) = 'VARGINHA' 
  AND inep_code IS NULL;

-- EE CORONEL GABRIEL PENHA DE PAIVA (VARGINHA) - INEP: 174912
UPDATE schools 
SET inep_code = '174912' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL GABRIEL PENHA DE PAIVA' 
  AND UPPER(TRIM(city)) = 'VARGINHA' 
  AND inep_code IS NULL;

-- EE DEPUTADO DOMINGOS DE FIGUEIREDO (VARGINHA) - INEP: 175013
UPDATE schools 
SET inep_code = '175013' 
WHERE UPPER(TRIM(name)) = 'EE DEPUTADO DOMINGOS DE FIGUEIREDO' 
  AND UPPER(TRIM(city)) = 'VARGINHA' 
  AND inep_code IS NULL;

-- EE DOUTOR WLADIMIR DE REZENDE PINTO (VARGINHA) - INEP: 175030
UPDATE schools 
SET inep_code = '175030' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR WLADIMIR DE REZENDE PINTO' 
  AND UPPER(TRIM(city)) = 'VARGINHA' 
  AND inep_code IS NULL;

-- EE IRMÃO MÁRIO ESDRAS (VARGINHA) - INEP: 175048
UPDATE schools 
SET inep_code = '175048' 
WHERE UPPER(TRIM(name)) = 'EE IRMÃO MÁRIO ESDRAS' 
  AND UPPER(TRIM(city)) = 'VARGINHA' 
  AND inep_code IS NULL;

-- EE PEDRO DE ALCÂNTARA (VARGINHA) - INEP: 175064
UPDATE schools 
SET inep_code = '175064' 
WHERE UPPER(TRIM(name)) = 'EE PEDRO DE ALCÂNTARA' 
  AND UPPER(TRIM(city)) = 'VARGINHA' 
  AND inep_code IS NULL;

-- EE PROFESSOR ANTÔNIO CORREA CARVALHO (VARGINHA) - INEP: 217719
UPDATE schools 
SET inep_code = '217719' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ANTÔNIO CORREA CARVALHO' 
  AND UPPER(TRIM(city)) = 'VARGINHA' 
  AND inep_code IS NULL;

-- EE PROFESSOR ANTÔNIO DOMINGUES CHAVES (VARGINHA) - INEP: 175072
UPDATE schools 
SET inep_code = '175072' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ANTÔNIO DOMINGUES CHAVES' 
  AND UPPER(TRIM(city)) = 'VARGINHA' 
  AND inep_code IS NULL;

-- EE PROFESSOR FÁBIO SALLES (VARGINHA) - INEP: 174904
UPDATE schools 
SET inep_code = '174904' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR FÁBIO SALLES' 
  AND UPPER(TRIM(city)) = 'VARGINHA' 
  AND inep_code IS NULL;

-- EE PROFESSORA ARACY MIRANDA (VARGINHA) - INEP: 175102
UPDATE schools 
SET inep_code = '175102' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ARACY MIRANDA' 
  AND UPPER(TRIM(city)) = 'VARGINHA' 
  AND inep_code IS NULL;

-- EE PROFESSORA SELMA BASTOS (VARGINHA) - INEP: 356719
UPDATE schools 
SET inep_code = '356719' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA SELMA BASTOS' 
  AND UPPER(TRIM(city)) = 'VARGINHA' 
  AND inep_code IS NULL;

-- EE SÃO SEBASTIÃO (VARGINHA) - INEP: 175081
UPDATE schools 
SET inep_code = '175081' 
WHERE UPPER(TRIM(name)) = 'EE SÃO SEBASTIÃO' 
  AND UPPER(TRIM(city)) = 'VARGINHA' 
  AND inep_code IS NULL;

COMMIT;

-- =====================================================
-- VERIFICAÇÃO
-- =====================================================
SELECT COUNT(*) as total_com_inep FROM schools WHERE inep_code IS NOT NULL;
SELECT COUNT(*) as total_sem_inep FROM schools WHERE inep_code IS NULL;

COMMIT;
