-- Lote 3 de 7
-- Updates 601 a 900

BEGIN;

-- EE PROFESSORA NILZA GOMES BERGMAN (SARZEDO) - INEP: 367826
UPDATE schools 
SET inep_code = '367826' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA NILZA GOMES BERGMAN' 
  AND UPPER(TRIM(city)) = 'SARZEDO' 
  AND inep_code IS NULL;

-- COLÉGIO TIRADENTES PMMG- UNIDADE MINASCAIXA (BELO HORIZONTE) - INEP: 307700
UPDATE schools 
SET inep_code = '307700' 
WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG- UNIDADE MINASCAIXA' 
  AND UPPER(TRIM(city)) = 'BELO HORIZONTE' 
  AND inep_code IS NULL;

-- EE MARIA ANDRADE RESENDE (BELO HORIZONTE) - INEP: 253413
UPDATE schools 
SET inep_code = '253413' 
WHERE UPPER(TRIM(name)) = 'EE MARIA ANDRADE RESENDE' 
  AND UPPER(TRIM(city)) = 'BELO HORIZONTE' 
  AND inep_code IS NULL;

-- EE PADRE JOÃO DE MATTOS ALMEIDA (BELO HORIZONTE) - INEP: 322636
UPDATE schools 
SET inep_code = '322636' 
WHERE UPPER(TRIM(name)) = 'EE PADRE JOÃO DE MATTOS ALMEIDA' 
  AND UPPER(TRIM(city)) = 'BELO HORIZONTE' 
  AND inep_code IS NULL;

-- EE PROFESSOR AGNELO CORREIA VIANA (BELO HORIZONTE) - INEP: 317357
UPDATE schools 
SET inep_code = '317357' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR AGNELO CORREIA VIANA' 
  AND UPPER(TRIM(city)) = 'BELO HORIZONTE' 
  AND inep_code IS NULL;

-- EE PROFESSORA ADIR ANDRADE ALBANO (BELO HORIZONTE) - INEP: 246425
UPDATE schools 
SET inep_code = '246425' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ADIR ANDRADE ALBANO' 
  AND UPPER(TRIM(city)) = 'BELO HORIZONTE' 
  AND inep_code IS NULL;

-- EE CARDEAL MOTA (MORRO DO PILAR) - INEP: 141305
UPDATE schools 
SET inep_code = '141305' 
WHERE UPPER(TRIM(name)) = 'EE CARDEAL MOTA' 
  AND UPPER(TRIM(city)) = 'MORRO DO PILAR' 
  AND inep_code IS NULL;

-- EE INTENDENTE CÂMARA (MORRO DO PILAR) - INEP: 141291
UPDATE schools 
SET inep_code = '141291' 
WHERE UPPER(TRIM(name)) = 'EE INTENDENTE CÂMARA' 
  AND UPPER(TRIM(city)) = 'MORRO DO PILAR' 
  AND inep_code IS NULL;

-- CESEC DE JUSTINÓPOLIS (RIBEIRÃO DAS NEVES) - INEP: 346365
UPDATE schools 
SET inep_code = '346365' 
WHERE UPPER(TRIM(name)) = 'CESEC DE JUSTINÓPOLIS' 
  AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' 
  AND inep_code IS NULL;

-- EE ALESSANDRA SALUM CADAR (RIBEIRÃO DAS NEVES) - INEP: 231720
UPDATE schools 
SET inep_code = '231720' 
WHERE UPPER(TRIM(name)) = 'EE ALESSANDRA SALUM CADAR' 
  AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' 
  AND inep_code IS NULL;

-- EE ALIZON THEMÓTER COSTA (RIBEIRÃO DAS NEVES) - INEP: 339156
UPDATE schools 
SET inep_code = '339156' 
WHERE UPPER(TRIM(name)) = 'EE ALIZON THEMÓTER COSTA' 
  AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' 
  AND inep_code IS NULL;

-- EE ANTÔNIO RIGUEIRA DA FONSECA (RIBEIRÃO DAS NEVES) - INEP: 222461
UPDATE schools 
SET inep_code = '222461' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO RIGUEIRA DA FONSECA' 
  AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' 
  AND inep_code IS NULL;

-- EE CARLOS DRUMMOND DE ANDRADE (RIBEIRÃO DAS NEVES) - INEP: 310221
UPDATE schools 
SET inep_code = '310221' 
WHERE UPPER(TRIM(name)) = 'EE CARLOS DRUMMOND DE ANDRADE' 
  AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' 
  AND inep_code IS NULL;

-- EE CIDADE DOS MENINOS (RIBEIRÃO DAS NEVES) - INEP: 277037
UPDATE schools 
SET inep_code = '277037' 
WHERE UPPER(TRIM(name)) = 'EE CIDADE DOS MENINOS' 
  AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' 
  AND inep_code IS NULL;

-- EE CUSTÓDIO FÉLIX (RIBEIRÃO DAS NEVES) - INEP: 317195
UPDATE schools 
SET inep_code = '317195' 
WHERE UPPER(TRIM(name)) = 'EE CUSTÓDIO FÉLIX' 
  AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' 
  AND inep_code IS NULL;

-- EE DE ENSINO FUNDAMENTAL E MÉDIO (RIBEIRÃO DAS NEVES) - INEP: 339040
UPDATE schools 
SET inep_code = '339040' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL E MÉDIO' 
  AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' 
  AND inep_code IS NULL;

-- EE DE ENSINO FUNDAMENTAL E MÉDIO (RIBEIRÃO DAS NEVES) - INEP: 342564
UPDATE schools 
SET inep_code = '342564' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL E MÉDIO' 
  AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' 
  AND inep_code IS NULL;

-- EE DJALMA MARQUES (RIBEIRÃO DAS NEVES) - INEP: 317489
UPDATE schools 
SET inep_code = '317489' 
WHERE UPPER(TRIM(name)) = 'EE DJALMA MARQUES' 
  AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' 
  AND inep_code IS NULL;

-- EE DR REYNALDO MARTINS MARQUES (RIBEIRÃO DAS NEVES) - INEP: 342491
UPDATE schools 
SET inep_code = '342491' 
WHERE UPPER(TRIM(name)) = 'EE DR REYNALDO MARTINS MARQUES' 
  AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' 
  AND inep_code IS NULL;

-- EE GUADALAJARA (RIBEIRÃO DAS NEVES) - INEP: 219045
UPDATE schools 
SET inep_code = '219045' 
WHERE UPPER(TRIM(name)) = 'EE GUADALAJARA' 
  AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' 
  AND inep_code IS NULL;

-- EE HENRIQUE DE SOUZA FILHO - HENFIL (RIBEIRÃO DAS NEVES) - INEP: 239381
UPDATE schools 
SET inep_code = '239381' 
WHERE UPPER(TRIM(name)) = 'EE HENRIQUE DE SOUZA FILHO - HENFIL' 
  AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' 
  AND inep_code IS NULL;

-- EE ITÁLIA CAUTIERO FRANCO (RIBEIRÃO DAS NEVES) - INEP: 317349
UPDATE schools 
SET inep_code = '317349' 
WHERE UPPER(TRIM(name)) = 'EE ITÁLIA CAUTIERO FRANCO' 
  AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' 
  AND inep_code IS NULL;

-- EE JOÃO CORREA ARMOND (RIBEIRÃO DAS NEVES) - INEP: 231738
UPDATE schools 
SET inep_code = '231738' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO CORREA ARMOND' 
  AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' 
  AND inep_code IS NULL;

-- EE JOÃO DE ALMEIDA (RIBEIRÃO DAS NEVES) - INEP: 218758
UPDATE schools 
SET inep_code = '218758' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO DE ALMEIDA' 
  AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' 
  AND inep_code IS NULL;

-- EE JOSÉ SOARES DINIZ E SILVA (RIBEIRÃO DAS NEVES) - INEP: 218715
UPDATE schools 
SET inep_code = '218715' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ SOARES DINIZ E SILVA' 
  AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' 
  AND inep_code IS NULL;

-- EE MANOEL MARTINS DE MELO (RIBEIRÃO DAS NEVES) - INEP: 218995
UPDATE schools 
SET inep_code = '218995' 
WHERE UPPER(TRIM(name)) = 'EE MANOEL MARTINS DE MELO' 
  AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' 
  AND inep_code IS NULL;

-- EE MARIA DA GLÓRIA ASSUNÇÃO (RIBEIRÃO DAS NEVES) - INEP: 212679
UPDATE schools 
SET inep_code = '212679' 
WHERE UPPER(TRIM(name)) = 'EE MARIA DA GLÓRIA ASSUNÇÃO' 
  AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' 
  AND inep_code IS NULL;

-- EE MARIA DA PIEDADE SOUZA ROCHA (RIBEIRÃO DAS NEVES) - INEP: 231711
UPDATE schools 
SET inep_code = '231711' 
WHERE UPPER(TRIM(name)) = 'EE MARIA DA PIEDADE SOUZA ROCHA' 
  AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' 
  AND inep_code IS NULL;

-- EE MARIA PEREIRA DE ARAÚJO (RIBEIRÃO DAS NEVES) - INEP: 322628
UPDATE schools 
SET inep_code = '322628' 
WHERE UPPER(TRIM(name)) = 'EE MARIA PEREIRA DE ARAÚJO' 
  AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' 
  AND inep_code IS NULL;

-- EE NOSSA SENHORA DAS GRAÇAS (RIBEIRÃO DAS NEVES) - INEP: 327492
UPDATE schools 
SET inep_code = '327492' 
WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DAS GRAÇAS' 
  AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' 
  AND inep_code IS NULL;

-- EE NOSSA SENHORA DAS NEVES (RIBEIRÃO DAS NEVES) - INEP: 280160
UPDATE schools 
SET inep_code = '280160' 
WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DAS NEVES' 
  AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' 
  AND inep_code IS NULL;

-- EE PROFESSOR PAULO FREIRE (RIBEIRÃO DAS NEVES) - INEP: 310212
UPDATE schools 
SET inep_code = '310212' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR PAULO FREIRE' 
  AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' 
  AND inep_code IS NULL;

-- EE SÃO JUDAS TADEU (RIBEIRÃO DAS NEVES) - INEP: 219053
UPDATE schools 
SET inep_code = '219053' 
WHERE UPPER(TRIM(name)) = 'EE SÃO JUDAS TADEU' 
  AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' 
  AND inep_code IS NULL;

-- EE WASHINGTON MODESTO GONTIJO DE FARIA (RIBEIRÃO DAS NEVES) - INEP: 339105
UPDATE schools 
SET inep_code = '339105' 
WHERE UPPER(TRIM(name)) = 'EE WASHINGTON MODESTO GONTIJO DE FARIA' 
  AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' 
  AND inep_code IS NULL;

-- EE EPHIGENIA DE JESUS WERNECK (SANTA LUZIA) - INEP: 351040
UPDATE schools 
SET inep_code = '351040' 
WHERE UPPER(TRIM(name)) = 'EE EPHIGENIA DE JESUS WERNECK' 
  AND UPPER(TRIM(city)) = 'SANTA LUZIA' 
  AND inep_code IS NULL;

-- EE PRESIDENTE ITAMAR FRANCO (SANTA LUZIA) - INEP: 356727
UPDATE schools 
SET inep_code = '356727' 
WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE ITAMAR FRANCO' 
  AND UPPER(TRIM(city)) = 'SANTA LUZIA' 
  AND inep_code IS NULL;

-- EE DEPUTADO EMÍLIO DE VASCONCELOS (SANTANA DO RIACHO) - INEP: 330761
UPDATE schools 
SET inep_code = '330761' 
WHERE UPPER(TRIM(name)) = 'EE DEPUTADO EMÍLIO DE VASCONCELOS' 
  AND UPPER(TRIM(city)) = 'SANTANA DO RIACHO' 
  AND inep_code IS NULL;

-- EE BEATRIZ MARIA DE JESUS (SÃO JOSÉ DA LAPA) - INEP: 224103
UPDATE schools 
SET inep_code = '224103' 
WHERE UPPER(TRIM(name)) = 'EE BEATRIZ MARIA DE JESUS' 
  AND UPPER(TRIM(city)) = 'SÃO JOSÉ DA LAPA' 
  AND inep_code IS NULL;

-- CESEC DE VESPASIANO (VESPASIANO) - INEP: 346306
UPDATE schools 
SET inep_code = '346306' 
WHERE UPPER(TRIM(name)) = 'CESEC DE VESPASIANO' 
  AND UPPER(TRIM(city)) = 'VESPASIANO' 
  AND inep_code IS NULL;

-- COLÉGIO TIRADENTES PMMG (VESPASIANO) - INEP: 331121
UPDATE schools 
SET inep_code = '331121' 
WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG' 
  AND UPPER(TRIM(city)) = 'VESPASIANO' 
  AND inep_code IS NULL;

-- EE  DE ENSINO FUNDAMENTAL E MÉDIO (VESPASIANO) - INEP: 374270
UPDATE schools 
SET inep_code = '374270' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL E MÉDIO' 
  AND UPPER(TRIM(city)) = 'VESPASIANO' 
  AND inep_code IS NULL;

-- EE DE ENSINO MÉDIO (VESPASIANO) - INEP: 374288
UPDATE schools 
SET inep_code = '374288' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' 
  AND UPPER(TRIM(city)) = 'VESPASIANO' 
  AND inep_code IS NULL;

-- EE HERBERT JOSÉ DE SOUZA (VESPASIANO) - INEP: 330353
UPDATE schools 
SET inep_code = '330353' 
WHERE UPPER(TRIM(name)) = 'EE HERBERT JOSÉ DE SOUZA' 
  AND UPPER(TRIM(city)) = 'VESPASIANO' 
  AND inep_code IS NULL;

-- EE JOSÉ GABRIEL DE OLIVEIRA (VESPASIANO) - INEP: 218979
UPDATE schools 
SET inep_code = '218979' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ GABRIEL DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'VESPASIANO' 
  AND inep_code IS NULL;

-- EE NILA FARAJ (VESPASIANO) - INEP: 218740
UPDATE schools 
SET inep_code = '218740' 
WHERE UPPER(TRIM(name)) = 'EE NILA FARAJ' 
  AND UPPER(TRIM(city)) = 'VESPASIANO' 
  AND inep_code IS NULL;

-- EE PEDRO ÁLVARES CABRAL (ABADIA DOS DOURADOS) - INEP: 200271
UPDATE schools 
SET inep_code = '200271' 
WHERE UPPER(TRIM(name)) = 'EE PEDRO ÁLVARES CABRAL' 
  AND UPPER(TRIM(city)) = 'ABADIA DOS DOURADOS' 
  AND inep_code IS NULL;

-- EE BENEDITO VALADARES (CASCALHO RICO) - INEP: 200280
UPDATE schools 
SET inep_code = '200280' 
WHERE UPPER(TRIM(name)) = 'EE BENEDITO VALADARES' 
  AND UPPER(TRIM(city)) = 'CASCALHO RICO' 
  AND inep_code IS NULL;

-- EE ALÍRIO HERVAL (COROMANDEL) - INEP: 219011
UPDATE schools 
SET inep_code = '219011' 
WHERE UPPER(TRIM(name)) = 'EE ALÍRIO HERVAL' 
  AND UPPER(TRIM(city)) = 'COROMANDEL' 
  AND inep_code IS NULL;

-- EE CLARINDO GOULART (COROMANDEL) - INEP: 200336
UPDATE schools 
SET inep_code = '200336' 
WHERE UPPER(TRIM(name)) = 'EE CLARINDO GOULART' 
  AND UPPER(TRIM(city)) = 'COROMANDEL' 
  AND inep_code IS NULL;

-- EE JOAQUIM BOTELHO (COROMANDEL) - INEP: 200395
UPDATE schools 
SET inep_code = '200395' 
WHERE UPPER(TRIM(name)) = 'EE JOAQUIM BOTELHO' 
  AND UPPER(TRIM(city)) = 'COROMANDEL' 
  AND inep_code IS NULL;

-- EE JOAQUIM JOSÉ DE ASSUNÇÃO (COROMANDEL) - INEP: 200433
UPDATE schools 
SET inep_code = '200433' 
WHERE UPPER(TRIM(name)) = 'EE JOAQUIM JOSÉ DE ASSUNÇÃO' 
  AND UPPER(TRIM(city)) = 'COROMANDEL' 
  AND inep_code IS NULL;

-- EE JOSÉ EMÍLIO DE AGUIAR (COROMANDEL) - INEP: 200409
UPDATE schools 
SET inep_code = '200409' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ EMÍLIO DE AGUIAR' 
  AND UPPER(TRIM(city)) = 'COROMANDEL' 
  AND inep_code IS NULL;

-- EE OSÓRIO DE MORAIS (COROMANDEL) - INEP: 200328
UPDATE schools 
SET inep_code = '200328' 
WHERE UPPER(TRIM(name)) = 'EE OSÓRIO DE MORAIS' 
  AND UPPER(TRIM(city)) = 'COROMANDEL' 
  AND inep_code IS NULL;

-- EE PADRE LÁZARO MENEZES (COROMANDEL) - INEP: 219002
UPDATE schools 
SET inep_code = '219002' 
WHERE UPPER(TRIM(name)) = 'EE PADRE LÁZARO MENEZES' 
  AND UPPER(TRIM(city)) = 'COROMANDEL' 
  AND inep_code IS NULL;

-- EE SÃO GERALDO (COROMANDEL) - INEP: 200344
UPDATE schools 
SET inep_code = '200344' 
WHERE UPPER(TRIM(name)) = 'EE SÃO GERALDO' 
  AND UPPER(TRIM(city)) = 'COROMANDEL' 
  AND inep_code IS NULL;

-- EE ANITA RAMOS (DOURADOQUARA) - INEP: 307980
UPDATE schools 
SET inep_code = '307980' 
WHERE UPPER(TRIM(name)) = 'EE ANITA RAMOS' 
  AND UPPER(TRIM(city)) = 'DOURADOQUARA' 
  AND inep_code IS NULL;

-- EE DE DOLEARINA (ESTRELA DO SUL) - INEP: 200531
UPDATE schools 
SET inep_code = '200531' 
WHERE UPPER(TRIM(name)) = 'EE DE DOLEARINA' 
  AND UPPER(TRIM(city)) = 'ESTRELA DO SUL' 
  AND inep_code IS NULL;

-- EE MARIA MOREIRA DE VASCONCELOS (ESTRELA DO SUL) - INEP: 313149
UPDATE schools 
SET inep_code = '313149' 
WHERE UPPER(TRIM(name)) = 'EE MARIA MOREIRA DE VASCONCELOS' 
  AND UPPER(TRIM(city)) = 'ESTRELA DO SUL' 
  AND inep_code IS NULL;

-- EE ROBERT KENNEDY (ESTRELA DO SUL) - INEP: 200484
UPDATE schools 
SET inep_code = '200484' 
WHERE UPPER(TRIM(name)) = 'EE ROBERT KENNEDY' 
  AND UPPER(TRIM(city)) = 'ESTRELA DO SUL' 
  AND inep_code IS NULL;

-- EE CORONEL JOSÉ FALEIROS DE AGUIAR (GRUPIARA) - INEP: 200549
UPDATE schools 
SET inep_code = '200549' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL JOSÉ FALEIROS DE AGUIAR' 
  AND UPPER(TRIM(city)) = 'GRUPIARA' 
  AND inep_code IS NULL;

-- CESEC ZENITH CAMPOS (MONTE CARMELO) - INEP: 200671
UPDATE schools 
SET inep_code = '200671' 
WHERE UPPER(TRIM(name)) = 'CESEC ZENITH CAMPOS' 
  AND UPPER(TRIM(city)) = 'MONTE CARMELO' 
  AND inep_code IS NULL;

-- EE CLARA CHAVES (MONTE CARMELO) - INEP: 200573
UPDATE schools 
SET inep_code = '200573' 
WHERE UPPER(TRIM(name)) = 'EE CLARA CHAVES' 
  AND UPPER(TRIM(city)) = 'MONTE CARMELO' 
  AND inep_code IS NULL;

-- EE CORONEL VIRGÍLIO ROSA (MONTE CARMELO) - INEP: 200581
UPDATE schools 
SET inep_code = '200581' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL VIRGÍLIO ROSA' 
  AND UPPER(TRIM(city)) = 'MONTE CARMELO' 
  AND inep_code IS NULL;

-- EE DONA SINDA (MONTE CARMELO) - INEP: 200590
UPDATE schools 
SET inep_code = '200590' 
WHERE UPPER(TRIM(name)) = 'EE DONA SINDA' 
  AND UPPER(TRIM(city)) = 'MONTE CARMELO' 
  AND inep_code IS NULL;

-- EE ELIAS DE MORAES (MONTE CARMELO) - INEP: 200603
UPDATE schools 
SET inep_code = '200603' 
WHERE UPPER(TRIM(name)) = 'EE ELIAS DE MORAES' 
  AND UPPER(TRIM(city)) = 'MONTE CARMELO' 
  AND inep_code IS NULL;

-- EE GREGORIANO CANEDO (MONTE CARMELO) - INEP: 200611
UPDATE schools 
SET inep_code = '200611' 
WHERE UPPER(TRIM(name)) = 'EE GREGORIANO CANEDO' 
  AND UPPER(TRIM(city)) = 'MONTE CARMELO' 
  AND inep_code IS NULL;

-- EE LETÍCIA CHAVES (MONTE CARMELO) - INEP: 200620
UPDATE schools 
SET inep_code = '200620' 
WHERE UPPER(TRIM(name)) = 'EE LETÍCIA CHAVES' 
  AND UPPER(TRIM(city)) = 'MONTE CARMELO' 
  AND inep_code IS NULL;

-- EE MELO VIANA (MONTE CARMELO) - INEP: 200638
UPDATE schools 
SET inep_code = '200638' 
WHERE UPPER(TRIM(name)) = 'EE MELO VIANA' 
  AND UPPER(TRIM(city)) = 'MONTE CARMELO' 
  AND inep_code IS NULL;

-- EE ORDÁLIA ROCHA MUNDIM (MONTE CARMELO) - INEP: 231444
UPDATE schools 
SET inep_code = '231444' 
WHERE UPPER(TRIM(name)) = 'EE ORDÁLIA ROCHA MUNDIM' 
  AND UPPER(TRIM(city)) = 'MONTE CARMELO' 
  AND inep_code IS NULL;

-- EE PROFESSOR VICENTE LOPES PEREZ (MONTE CARMELO) - INEP: 200654
UPDATE schools 
SET inep_code = '200654' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR VICENTE LOPES PEREZ' 
  AND UPPER(TRIM(city)) = 'MONTE CARMELO' 
  AND inep_code IS NULL;

-- EE SANTA MARIA GORETTI (ROMARIA) - INEP: 200689
UPDATE schools 
SET inep_code = '200689' 
WHERE UPPER(TRIM(name)) = 'EE SANTA MARIA GORETTI' 
  AND UPPER(TRIM(city)) = 'ROMARIA' 
  AND inep_code IS NULL;

-- EE CARLOS ANTÔNIO DOS SANTOS (BRASÍLIA DE MINAS) - INEP: 231533
UPDATE schools 
SET inep_code = '231533' 
WHERE UPPER(TRIM(name)) = 'EE CARLOS ANTÔNIO DOS SANTOS' 
  AND UPPER(TRIM(city)) = 'BRASÍLIA DE MINAS' 
  AND inep_code IS NULL;

-- EE FRANCISCO XAVIER ANTUNES (BRASÍLIA DE MINAS) - INEP: 214981
UPDATE schools 
SET inep_code = '214981' 
WHERE UPPER(TRIM(name)) = 'EE FRANCISCO XAVIER ANTUNES' 
  AND UPPER(TRIM(city)) = 'BRASÍLIA DE MINAS' 
  AND inep_code IS NULL;

-- EE BARREIRO DE BAIXO (CORAÇÃO DE JESUS) - INEP: 239291
UPDATE schools 
SET inep_code = '239291' 
WHERE UPPER(TRIM(name)) = 'EE BARREIRO DE BAIXO' 
  AND UPPER(TRIM(city)) = 'CORAÇÃO DE JESUS' 
  AND inep_code IS NULL;

-- EE JOSÉ MARIA DOS MARES GUIA (CORAÇÃO DE JESUS) - INEP: 239283
UPDATE schools 
SET inep_code = '239283' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ MARIA DOS MARES GUIA' 
  AND UPPER(TRIM(city)) = 'CORAÇÃO DE JESUS' 
  AND inep_code IS NULL;

-- EE MARIA DA CONCEIÇÃO CHAVES (CORAÇÃO DE JESUS) - INEP: 239275
UPDATE schools 
SET inep_code = '239275' 
WHERE UPPER(TRIM(name)) = 'EE MARIA DA CONCEIÇÃO CHAVES' 
  AND UPPER(TRIM(city)) = 'CORAÇÃO DE JESUS' 
  AND inep_code IS NULL;

-- EE NOSSA SENHORA DA CONCEIÇÃO (CORAÇÃO DE JESUS) - INEP: 239259
UPDATE schools 
SET inep_code = '239259' 
WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DA CONCEIÇÃO' 
  AND UPPER(TRIM(city)) = 'CORAÇÃO DE JESUS' 
  AND inep_code IS NULL;

-- EE NOSSA SENHORA DAS GRAÇAS (CORAÇÃO DE JESUS) - INEP: 239267
UPDATE schools 
SET inep_code = '239267' 
WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DAS GRAÇAS' 
  AND UPPER(TRIM(city)) = 'CORAÇÃO DE JESUS' 
  AND inep_code IS NULL;

-- EE SÃO JOSÉ (CORAÇÃO DE JESUS) - INEP: 239241
UPDATE schools 
SET inep_code = '239241' 
WHERE UPPER(TRIM(name)) = 'EE SÃO JOSÉ' 
  AND UPPER(TRIM(city)) = 'CORAÇÃO DE JESUS' 
  AND inep_code IS NULL;

-- EE SÃO LUÍS (CORAÇÃO DE JESUS) - INEP: 239704
UPDATE schools 
SET inep_code = '239704' 
WHERE UPPER(TRIM(name)) = 'EE SÃO LUÍS' 
  AND UPPER(TRIM(city)) = 'CORAÇÃO DE JESUS' 
  AND inep_code IS NULL;

-- EE SÃO SEBASTIÃO (CORAÇÃO DE JESUS) - INEP: 239232
UPDATE schools 
SET inep_code = '239232' 
WHERE UPPER(TRIM(name)) = 'EE SÃO SEBASTIÃO' 
  AND UPPER(TRIM(city)) = 'CORAÇÃO DE JESUS' 
  AND inep_code IS NULL;

-- EE DE ENSINO FUNDAMENTAL E MÉDIO (CRISTÁLIA) - INEP: 351067
UPDATE schools 
SET inep_code = '351067' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL E MÉDIO' 
  AND UPPER(TRIM(city)) = 'CRISTÁLIA' 
  AND inep_code IS NULL;

-- EE SÃO GONÇALO (FRANCISCO SÁ) - INEP: 330639
UPDATE schools 
SET inep_code = '330639' 
WHERE UPPER(TRIM(name)) = 'EE SÃO GONÇALO' 
  AND UPPER(TRIM(city)) = 'FRANCISCO SÁ' 
  AND inep_code IS NULL;

-- EE DE ENSINO MÉDIO (GRÃO MOGOL) - INEP: 346098
UPDATE schools 
SET inep_code = '346098' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' 
  AND UPPER(TRIM(city)) = 'GRÃO MOGOL' 
  AND inep_code IS NULL;

-- EE SÃO JOSÉ DO RIO PRETO (ITACAMBIRA) - INEP: 253430
UPDATE schools 
SET inep_code = '253430' 
WHERE UPPER(TRIM(name)) = 'EE SÃO JOSÉ DO RIO PRETO' 
  AND UPPER(TRIM(city)) = 'ITACAMBIRA' 
  AND inep_code IS NULL;

-- EE MANOEL PEREIRA DE ARAÚJO (JAPONVAR) - INEP: 239054
UPDATE schools 
SET inep_code = '239054' 
WHERE UPPER(TRIM(name)) = 'EE MANOEL PEREIRA DE ARAÚJO' 
  AND UPPER(TRIM(city)) = 'JAPONVAR' 
  AND inep_code IS NULL;

-- EE PRESIDENTE CASTELO BRANCO (JAPONVAR) - INEP: 310565
UPDATE schools 
SET inep_code = '310565' 
WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE CASTELO BRANCO' 
  AND UPPER(TRIM(city)) = 'JAPONVAR' 
  AND inep_code IS NULL;

-- EE SÃO JUDAS TADEU (LUISLÂNDIA) - INEP: 276880
UPDATE schools 
SET inep_code = '276880' 
WHERE UPPER(TRIM(name)) = 'EE SÃO JUDAS TADEU' 
  AND UPPER(TRIM(city)) = 'LUISLÂNDIA' 
  AND inep_code IS NULL;

-- EE SANTA MARIA (MIRABELA) - INEP: 242217
UPDATE schools 
SET inep_code = '242217' 
WHERE UPPER(TRIM(name)) = 'EE SANTA MARIA' 
  AND UPPER(TRIM(city)) = 'MIRABELA' 
  AND inep_code IS NULL;

-- EE DE ENSINO FUNDAMENTAL E MÉDIO (MONTES CLAROS) - INEP: 326682
UPDATE schools 
SET inep_code = '326682' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL E MÉDIO' 
  AND UPPER(TRIM(city)) = 'MONTES CLAROS' 
  AND inep_code IS NULL;

-- EE DE ENSINO MÉDIO (MONTES CLAROS) - INEP: 346128
UPDATE schools 
SET inep_code = '346128' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' 
  AND UPPER(TRIM(city)) = 'MONTES CLAROS' 
  AND inep_code IS NULL;

-- EE DE ENSINO MÉDIO (MONTES CLAROS) - INEP: 353833
UPDATE schools 
SET inep_code = '353833' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' 
  AND UPPER(TRIM(city)) = 'MONTES CLAROS' 
  AND inep_code IS NULL;

-- EE DE ENSINO MÉDIO (MONTES CLAROS) - INEP: 353841
UPDATE schools 
SET inep_code = '353841' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' 
  AND UPPER(TRIM(city)) = 'MONTES CLAROS' 
  AND inep_code IS NULL;

-- EE GUTEMBERG TEODORO PENHA (MONTES CLAROS) - INEP: 346110
UPDATE schools 
SET inep_code = '346110' 
WHERE UPPER(TRIM(name)) = 'EE GUTEMBERG TEODORO PENHA' 
  AND UPPER(TRIM(city)) = 'MONTES CLAROS' 
  AND inep_code IS NULL;

-- EE JOÃO MIGUEL TEIXEIRA DE JESUS (MONTES CLAROS) - INEP: 369861
UPDATE schools 
SET inep_code = '369861' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO MIGUEL TEIXEIRA DE JESUS' 
  AND UPPER(TRIM(city)) = 'MONTES CLAROS' 
  AND inep_code IS NULL;

-- EE LEVI DURÃES PERES (MONTES CLAROS) - INEP: 205664
UPDATE schools 
SET inep_code = '205664' 
WHERE UPPER(TRIM(name)) = 'EE LEVI DURÃES PERES' 
  AND UPPER(TRIM(city)) = 'MONTES CLAROS' 
  AND inep_code IS NULL;

-- EE PADRE HENRIQUE MUNÁIZ PUIG (MONTES CLAROS) - INEP: 339571
UPDATE schools 
SET inep_code = '339571' 
WHERE UPPER(TRIM(name)) = 'EE PADRE HENRIQUE MUNÁIZ PUIG' 
  AND UPPER(TRIM(city)) = 'MONTES CLAROS' 
  AND inep_code IS NULL;

-- EE PROFESSORA ELIZABETE PEREIRA SOARES (MONTES CLAROS) - INEP: 346101
UPDATE schools 
SET inep_code = '346101' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ELIZABETE PEREIRA SOARES' 
  AND UPPER(TRIM(city)) = 'MONTES CLAROS' 
  AND inep_code IS NULL;

-- EE PROFESSORA MARIA EMÍLIA SILVA SANTOS (MONTES CLAROS) - INEP: 369853
UPDATE schools 
SET inep_code = '369853' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA EMÍLIA SILVA SANTOS' 
  AND UPPER(TRIM(city)) = 'MONTES CLAROS' 
  AND inep_code IS NULL;

-- ESCOLA TÉCNICA DE SAÚDE DO CENTRO DE EDUCAÇÃO PROFISSIONAL E TECNOLÓGICA DA UNIMONTES (MONTES CLAROS) - INEP: 261891
UPDATE schools 
SET inep_code = '261891' 
WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA DE SAÚDE DO CENTRO DE EDUCAÇÃO PROFISSIONAL E TECNOLÓGICA DA UNIMONTES' 
  AND UPPER(TRIM(city)) = 'MONTES CLAROS' 
  AND inep_code IS NULL;

-- EE DE ENSINO MÉDIO (SÃO JOÃO DA PONTE) - INEP: 346160
UPDATE schools 
SET inep_code = '346160' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DA PONTE' 
  AND inep_code IS NULL;

-- EE DE ENSINO MÉDIO (SÃO JOÃO DA PONTE) - INEP: 353850
UPDATE schools 
SET inep_code = '353850' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DA PONTE' 
  AND inep_code IS NULL;

-- EE LIODORA MARIA DA CONCEIÇÃO (SÃO JOÃO DA PONTE) - INEP: 356735
UPDATE schools 
SET inep_code = '356735' 
WHERE UPPER(TRIM(name)) = 'EE LIODORA MARIA DA CONCEIÇÃO' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DA PONTE' 
  AND inep_code IS NULL;

-- EE DIVANE ROCHA DE SÁ (SÃO JOÃO DO PARAÍSO) - INEP: 254321
UPDATE schools 
SET inep_code = '254321' 
WHERE UPPER(TRIM(name)) = 'EE DIVANE ROCHA DE SÁ' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DO PARAÍSO' 
  AND inep_code IS NULL;

-- EE MÁRIO COELHO (SÃO JOÃO DO PARAÍSO) - INEP: 319074
UPDATE schools 
SET inep_code = '319074' 
WHERE UPPER(TRIM(name)) = 'EE MÁRIO COELHO' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DO PARAÍSO' 
  AND inep_code IS NULL;

-- EE SANTO ANTÔNIO (SÃO JOÃO DO PARAÍSO) - INEP: 246255
UPDATE schools 
SET inep_code = '246255' 
WHERE UPPER(TRIM(name)) = 'EE SANTO ANTÔNIO' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DO PARAÍSO' 
  AND inep_code IS NULL;

-- EE SÃO TIAGO (SÃO JOÃO DO PARAÍSO) - INEP: 254312
UPDATE schools 
SET inep_code = '254312' 
WHERE UPPER(TRIM(name)) = 'EE SÃO TIAGO' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DO PARAÍSO' 
  AND inep_code IS NULL;

-- EE GERALDO ROCHA (ANTÔNIO PRADO DE MINAS) - INEP: 305278
UPDATE schools 
SET inep_code = '305278' 
WHERE UPPER(TRIM(name)) = 'EE GERALDO ROCHA' 
  AND UPPER(TRIM(city)) = 'ANTÔNIO PRADO DE MINAS' 
  AND inep_code IS NULL;

-- CESEC GOVERNADOR BIAS FORTES (MURIAÉ) - INEP: 314129
UPDATE schools 
SET inep_code = '314129' 
WHERE UPPER(TRIM(name)) = 'CESEC GOVERNADOR BIAS FORTES' 
  AND UPPER(TRIM(city)) = 'MURIAÉ' 
  AND inep_code IS NULL;

-- EE MARIA AUXILIADORA FARIA (MURIAÉ) - INEP: 328201
UPDATE schools 
SET inep_code = '328201' 
WHERE UPPER(TRIM(name)) = 'EE MARIA AUXILIADORA FARIA' 
  AND UPPER(TRIM(city)) = 'MURIAÉ' 
  AND inep_code IS NULL;

-- EE ORMEZINDA ALVES DUARTE (SÃO SEBASTIÃO DA VARGEM ALEGRE) - INEP: 276901
UPDATE schools 
SET inep_code = '276901' 
WHERE UPPER(TRIM(name)) = 'EE ORMEZINDA ALVES DUARTE' 
  AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DA VARGEM ALEGRE' 
  AND inep_code IS NULL;

-- EE JOSÉ MODESTO ÁVILA (BELA VISTA DE MINAS) - INEP: 102750
UPDATE schools 
SET inep_code = '102750' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ MODESTO ÁVILA' 
  AND UPPER(TRIM(city)) = 'BELA VISTA DE MINAS' 
  AND inep_code IS NULL;

-- EE PADRE OSWALDO DE PODESTÁ (BELA VISTA DE MINAS) - INEP: 102733
UPDATE schools 
SET inep_code = '102733' 
WHERE UPPER(TRIM(name)) = 'EE PADRE OSWALDO DE PODESTÁ' 
  AND UPPER(TRIM(city)) = 'BELA VISTA DE MINAS' 
  AND inep_code IS NULL;

-- EE PROFESSORA ADELINA DA CONCEIÇÃO MENDES (BELA VISTA DE MINAS) - INEP: 102784
UPDATE schools 
SET inep_code = '102784' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ADELINA DA CONCEIÇÃO MENDES' 
  AND UPPER(TRIM(city)) = 'BELA VISTA DE MINAS' 
  AND inep_code IS NULL;

-- EE DONA JACY FRANCISCA GARCIA (DIONÍSIO) - INEP: 102831
UPDATE schools 
SET inep_code = '102831' 
WHERE UPPER(TRIM(name)) = 'EE DONA JACY FRANCISCA GARCIA' 
  AND UPPER(TRIM(city)) = 'DIONÍSIO' 
  AND inep_code IS NULL;

-- EE JOSÉ MARTINS DRUMOND (DIONÍSIO) - INEP: 102873
UPDATE schools 
SET inep_code = '102873' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ MARTINS DRUMOND' 
  AND UPPER(TRIM(city)) = 'DIONÍSIO' 
  AND inep_code IS NULL;

-- EE PROFESSOR BENJAMIM ARAÚJO (DIONÍSIO) - INEP: 102814
UPDATE schools 
SET inep_code = '102814' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR BENJAMIM ARAÚJO' 
  AND UPPER(TRIM(city)) = 'DIONÍSIO' 
  AND inep_code IS NULL;

-- CESEC PROFESSOR JÚLIO CARVALHO SOARES (FERROS) - INEP: 102971
UPDATE schools 
SET inep_code = '102971' 
WHERE UPPER(TRIM(name)) = 'CESEC PROFESSOR JÚLIO CARVALHO SOARES' 
  AND UPPER(TRIM(city)) = 'FERROS' 
  AND inep_code IS NULL;

-- EE LEOPOLDINA BARROS DRUMOND (FERROS) - INEP: 103021
UPDATE schools 
SET inep_code = '103021' 
WHERE UPPER(TRIM(name)) = 'EE LEOPOLDINA BARROS DRUMOND' 
  AND UPPER(TRIM(city)) = 'FERROS' 
  AND inep_code IS NULL;

-- EE PONCIANO PEREIRA DA COSTA (FERROS) - INEP: 103012
UPDATE schools 
SET inep_code = '103012' 
WHERE UPPER(TRIM(name)) = 'EE PONCIANO PEREIRA DA COSTA' 
  AND UPPER(TRIM(city)) = 'FERROS' 
  AND inep_code IS NULL;

-- EE PROFESSOR ALCIDES FERNANDES DE ASSUNÇÃO (FERROS) - INEP: 102911
UPDATE schools 
SET inep_code = '102911' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ALCIDES FERNANDES DE ASSUNÇÃO' 
  AND UPPER(TRIM(city)) = 'FERROS' 
  AND inep_code IS NULL;

-- EE SILVEIRA DRUMOND (FERROS) - INEP: 102962
UPDATE schools 
SET inep_code = '102962' 
WHERE UPPER(TRIM(name)) = 'EE SILVEIRA DRUMOND' 
  AND UPPER(TRIM(city)) = 'FERROS' 
  AND inep_code IS NULL;

-- CESEC PROFESSORA DORINHA FERREIRA (ITABIRA) - INEP: 103284
UPDATE schools 
SET inep_code = '103284' 
WHERE UPPER(TRIM(name)) = 'CESEC PROFESSORA DORINHA FERREIRA' 
  AND UPPER(TRIM(city)) = 'ITABIRA' 
  AND inep_code IS NULL;

-- COLÉGIO TIRADENTES DA PMMG - CTPM - UNIDADE DOUTOR JOSÉ DE GRISOLIA (ITABIRA) - INEP: 370002
UPDATE schools 
SET inep_code = '370002' 
WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES DA PMMG - CTPM - UNIDADE DOUTOR JOSÉ DE GRISOLIA' 
  AND UPPER(TRIM(city)) = 'ITABIRA' 
  AND inep_code IS NULL;

-- EE ANTÔNIO LINHARES GUERRA (ITABIRA) - INEP: 103098
UPDATE schools 
SET inep_code = '103098' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO LINHARES GUERRA' 
  AND UPPER(TRIM(city)) = 'ITABIRA' 
  AND inep_code IS NULL;

-- EE ANTÔNIO MARTINS PEREIRA (ITABIRA) - INEP: 103314
UPDATE schools 
SET inep_code = '103314' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO MARTINS PEREIRA' 
  AND UPPER(TRIM(city)) = 'ITABIRA' 
  AND inep_code IS NULL;

-- EE DA FAZENDA DA BETÂNIA (ITABIRA) - INEP: 103179
UPDATE schools 
SET inep_code = '103179' 
WHERE UPPER(TRIM(name)) = 'EE DA FAZENDA DA BETÂNIA' 
  AND UPPER(TRIM(city)) = 'ITABIRA' 
  AND inep_code IS NULL;

-- EE DONA ELEONORA NUNES PEREIRA (ITABIRA) - INEP: 103101
UPDATE schools 
SET inep_code = '103101' 
WHERE UPPER(TRIM(name)) = 'EE DONA ELEONORA NUNES PEREIRA' 
  AND UPPER(TRIM(city)) = 'ITABIRA' 
  AND inep_code IS NULL;

-- EE JOSÉ RICARDO MARTINS FONSECA (ITABIRA) - INEP: 103152
UPDATE schools 
SET inep_code = '103152' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ RICARDO MARTINS FONSECA' 
  AND UPPER(TRIM(city)) = 'ITABIRA' 
  AND inep_code IS NULL;

-- EE MAJOR LAGE (ITABIRA) - INEP: 103144
UPDATE schools 
SET inep_code = '103144' 
WHERE UPPER(TRIM(name)) = 'EE MAJOR LAGE' 
  AND UPPER(TRIM(city)) = 'ITABIRA' 
  AND inep_code IS NULL;

-- EE MESTRE ZECA AMÂNCIO (ITABIRA) - INEP: 103161
UPDATE schools 
SET inep_code = '103161' 
WHERE UPPER(TRIM(name)) = 'EE MESTRE ZECA AMÂNCIO' 
  AND UPPER(TRIM(city)) = 'ITABIRA' 
  AND inep_code IS NULL;

-- EE PROFESSOR EMÍLIO PEREIRA DE MAGALHÃES (ITABIRA) - INEP: 103209
UPDATE schools 
SET inep_code = '103209' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR EMÍLIO PEREIRA DE MAGALHÃES' 
  AND UPPER(TRIM(city)) = 'ITABIRA' 
  AND inep_code IS NULL;

-- EE PROFESSOR MANOEL SOARES (ITABIRA) - INEP: 103306
UPDATE schools 
SET inep_code = '103306' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR MANOEL SOARES' 
  AND UPPER(TRIM(city)) = 'ITABIRA' 
  AND inep_code IS NULL;

-- EE PROFESSORA MARCIANA MAGALHÃES (ITABIRA) - INEP: 103241
UPDATE schools 
SET inep_code = '103241' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARCIANA MAGALHÃES' 
  AND UPPER(TRIM(city)) = 'ITABIRA' 
  AND inep_code IS NULL;

-- EE PROFESSORA PALMIRA MORAIS (ITABIRA) - INEP: 103225
UPDATE schools 
SET inep_code = '103225' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA PALMIRA MORAIS' 
  AND UPPER(TRIM(city)) = 'ITABIRA' 
  AND inep_code IS NULL;

-- EE TRAJANO PROCÓPIO DE ALVARENGA SILVA MONTEIRO (ITABIRA) - INEP: 103187
UPDATE schools 
SET inep_code = '103187' 
WHERE UPPER(TRIM(name)) = 'EE TRAJANO PROCÓPIO DE ALVARENGA SILVA MONTEIRO' 
  AND UPPER(TRIM(city)) = 'ITABIRA' 
  AND inep_code IS NULL;

-- EE EMÍDIO DE SALES (ITAMBÉ DO MATO DENTRO) - INEP: 103331
UPDATE schools 
SET inep_code = '103331' 
WHERE UPPER(TRIM(name)) = 'EE EMÍDIO DE SALES' 
  AND UPPER(TRIM(city)) = 'ITAMBÉ DO MATO DENTRO' 
  AND inep_code IS NULL;

-- CESEC PROFESSORA ELZA MARIA (JOÃO MONLEVADE) - INEP: 103373
UPDATE schools 
SET inep_code = '103373' 
WHERE UPPER(TRIM(name)) = 'CESEC PROFESSORA ELZA MARIA' 
  AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' 
  AND inep_code IS NULL;

-- EE ALBERTO PEREIRA LIMA (JOÃO MONLEVADE) - INEP: 103349
UPDATE schools 
SET inep_code = '103349' 
WHERE UPPER(TRIM(name)) = 'EE ALBERTO PEREIRA LIMA' 
  AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' 
  AND inep_code IS NULL;

-- EE ANTÔNIO LOUREIRO SOBRINHO (JOÃO MONLEVADE) - INEP: 103381
UPDATE schools 
SET inep_code = '103381' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO LOUREIRO SOBRINHO' 
  AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' 
  AND inep_code IS NULL;

-- EE ANTÔNIO PAPINI (JOÃO MONLEVADE) - INEP: 103365
UPDATE schools 
SET inep_code = '103365' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO PAPINI' 
  AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' 
  AND inep_code IS NULL;

-- EE DO BAIRRO LARANJEIRAS (JOÃO MONLEVADE) - INEP: 103411
UPDATE schools 
SET inep_code = '103411' 
WHERE UPPER(TRIM(name)) = 'EE DO BAIRRO LARANJEIRAS' 
  AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' 
  AND inep_code IS NULL;

-- EE DONA JENNY FARIA (JOÃO MONLEVADE) - INEP: 103420
UPDATE schools 
SET inep_code = '103420' 
WHERE UPPER(TRIM(name)) = 'EE DONA JENNY FARIA' 
  AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' 
  AND inep_code IS NULL;

-- EE DOUTOR GERALDO PARREIRAS (JOÃO MONLEVADE) - INEP: 103527
UPDATE schools 
SET inep_code = '103527' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR GERALDO PARREIRAS' 
  AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' 
  AND inep_code IS NULL;

-- EE JOÃO XXIII (JOÃO MONLEVADE) - INEP: 103462
UPDATE schools 
SET inep_code = '103462' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO XXIII' 
  AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' 
  AND inep_code IS NULL;

-- EE LUIZ PRISCO DE BRAGA (JOÃO MONLEVADE) - INEP: 103489
UPDATE schools 
SET inep_code = '103489' 
WHERE UPPER(TRIM(name)) = 'EE LUIZ PRISCO DE BRAGA' 
  AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' 
  AND inep_code IS NULL;

-- EE MANOEL LOUREIRO (JOÃO MONLEVADE) - INEP: 103497
UPDATE schools 
SET inep_code = '103497' 
WHERE UPPER(TRIM(name)) = 'EE MANOEL LOUREIRO' 
  AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' 
  AND inep_code IS NULL;

-- EE RUMIA MALUF (JOÃO MONLEVADE) - INEP: 103535
UPDATE schools 
SET inep_code = '103535' 
WHERE UPPER(TRIM(name)) = 'EE RUMIA MALUF' 
  AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' 
  AND inep_code IS NULL;

-- EE DA VILA SANTA ROSA (NOVA ERA) - INEP: 103616
UPDATE schools 
SET inep_code = '103616' 
WHERE UPPER(TRIM(name)) = 'EE DA VILA SANTA ROSA' 
  AND UPPER(TRIM(city)) = 'NOVA ERA' 
  AND inep_code IS NULL;

-- EE NOSSA SENHORA DE FÁTIMA (NOVA ERA) - INEP: 103586
UPDATE schools 
SET inep_code = '103586' 
WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DE FÁTIMA' 
  AND UPPER(TRIM(city)) = 'NOVA ERA' 
  AND inep_code IS NULL;

-- EE PADRE VIDIGAL (NOVA ERA) - INEP: 103594
UPDATE schools 
SET inep_code = '103594' 
WHERE UPPER(TRIM(name)) = 'EE PADRE VIDIGAL' 
  AND UPPER(TRIM(city)) = 'NOVA ERA' 
  AND inep_code IS NULL;

-- EE LUIZA DOS SANTOS FERREIRA (PASSABÉM) - INEP: 103641
UPDATE schools 
SET inep_code = '103641' 
WHERE UPPER(TRIM(name)) = 'EE LUIZA DOS SANTOS FERREIRA' 
  AND UPPER(TRIM(city)) = 'PASSABÉM' 
  AND inep_code IS NULL;

-- CESEC MARTINHA DE OLIVEIRA ARAÚJO (RIO PIRACICABA) - INEP: 103721
UPDATE schools 
SET inep_code = '103721' 
WHERE UPPER(TRIM(name)) = 'CESEC MARTINHA DE OLIVEIRA ARAÚJO' 
  AND UPPER(TRIM(city)) = 'RIO PIRACICABA' 
  AND inep_code IS NULL;

-- EE ANTONINO FERREIRA MENDES (RIO PIRACICABA) - INEP: 103730
UPDATE schools 
SET inep_code = '103730' 
WHERE UPPER(TRIM(name)) = 'EE ANTONINO FERREIRA MENDES' 
  AND UPPER(TRIM(city)) = 'RIO PIRACICABA' 
  AND inep_code IS NULL;

-- EE MARINHO SILVA (RIO PIRACICABA) - INEP: 338656
UPDATE schools 
SET inep_code = '338656' 
WHERE UPPER(TRIM(name)) = 'EE MARINHO SILVA' 
  AND UPPER(TRIM(city)) = 'RIO PIRACICABA' 
  AND inep_code IS NULL;

-- EE PROFESSOR ANTÔNIO FERNANDES PINTO (RIO PIRACICABA) - INEP: 103691
UPDATE schools 
SET inep_code = '103691' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ANTÔNIO FERNANDES PINTO' 
  AND UPPER(TRIM(city)) = 'RIO PIRACICABA' 
  AND inep_code IS NULL;

-- EE AGENOR GUERRA (SANTA MARIA DE ITABIRA) - INEP: 103802
UPDATE schools 
SET inep_code = '103802' 
WHERE UPPER(TRIM(name)) = 'EE AGENOR GUERRA' 
  AND UPPER(TRIM(city)) = 'SANTA MARIA DE ITABIRA' 
  AND inep_code IS NULL;

-- EE DOUTOR COSTA (SANTA MARIA DE ITABIRA) - INEP: 103756
UPDATE schools 
SET inep_code = '103756' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR COSTA' 
  AND UPPER(TRIM(city)) = 'SANTA MARIA DE ITABIRA' 
  AND inep_code IS NULL;

-- EE PROFESSOR JOSÉ MADUREIRA DE OLIVEIRA (SANTO ANTÔNIO DO RIO ABAIXO) - INEP: 103829
UPDATE schools 
SET inep_code = '103829' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOSÉ MADUREIRA DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'SANTO ANTÔNIO DO RIO ABAIXO' 
  AND inep_code IS NULL;

-- EE CORONEL FRANCISCO ROLLA (SÃO DOMINGOS DO PRATA) - INEP: 103845
UPDATE schools 
SET inep_code = '103845' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL FRANCISCO ROLLA' 
  AND UPPER(TRIM(city)) = 'SÃO DOMINGOS DO PRATA' 
  AND inep_code IS NULL;

-- EE CORONEL JOSÉ GOMES DE ARAÚJO (SÃO DOMINGOS DO PRATA) - INEP: 103900
UPDATE schools 
SET inep_code = '103900' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL JOSÉ GOMES DE ARAÚJO' 
  AND UPPER(TRIM(city)) = 'SÃO DOMINGOS DO PRATA' 
  AND inep_code IS NULL;

-- EE CRISTIANO MACHADO (SÃO DOMINGOS DO PRATA) - INEP: 103969
UPDATE schools 
SET inep_code = '103969' 
WHERE UPPER(TRIM(name)) = 'EE CRISTIANO MACHADO' 
  AND UPPER(TRIM(city)) = 'SÃO DOMINGOS DO PRATA' 
  AND inep_code IS NULL;

-- EE MARQUES AFONSO (SÃO DOMINGOS DO PRATA) - INEP: 103888
UPDATE schools 
SET inep_code = '103888' 
WHERE UPPER(TRIM(name)) = 'EE MARQUES AFONSO' 
  AND UPPER(TRIM(city)) = 'SÃO DOMINGOS DO PRATA' 
  AND inep_code IS NULL;

-- EE VICENTE DE PAULA FRAGA (SÃO DOMINGOS DO PRATA) - INEP: 103993
UPDATE schools 
SET inep_code = '103993' 
WHERE UPPER(TRIM(name)) = 'EE VICENTE DE PAULA FRAGA' 
  AND UPPER(TRIM(city)) = 'SÃO DOMINGOS DO PRATA' 
  AND inep_code IS NULL;

-- EE DESEMBARGADOR MOREIRA SANTOS (SÃO GONÇALO DO RIO ABAIXO) - INEP: 104051
UPDATE schools 
SET inep_code = '104051' 
WHERE UPPER(TRIM(name)) = 'EE DESEMBARGADOR MOREIRA SANTOS' 
  AND UPPER(TRIM(city)) = 'SÃO GONÇALO DO RIO ABAIXO' 
  AND inep_code IS NULL;

-- EE ROMEU PERDIGÃO (SÃO JOSÉ DO GOIABAL) - INEP: 104108
UPDATE schools 
SET inep_code = '104108' 
WHERE UPPER(TRIM(name)) = 'EE ROMEU PERDIGÃO' 
  AND UPPER(TRIM(city)) = 'SÃO JOSÉ DO GOIABAL' 
  AND inep_code IS NULL;

-- EE ODILON BEHRENS (SÃO SEBASTIÃO DO RIO PRETO) - INEP: 104141
UPDATE schools 
SET inep_code = '104141' 
WHERE UPPER(TRIM(name)) = 'EE ODILON BEHRENS' 
  AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO RIO PRETO' 
  AND inep_code IS NULL;

-- EE PADRE SIMIM (ACAIACA) - INEP: 106003
UPDATE schools 
SET inep_code = '106003' 
WHERE UPPER(TRIM(name)) = 'EE PADRE SIMIM' 
  AND UPPER(TRIM(city)) = 'ACAIACA' 
  AND inep_code IS NULL;

-- EE PROFESSOR MARTINS (ACAIACA) - INEP: 330663
UPDATE schools 
SET inep_code = '330663' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR MARTINS' 
  AND UPPER(TRIM(city)) = 'ACAIACA' 
  AND inep_code IS NULL;

-- EE CORONEL NICOLAU SAMPAIO (DIOGO DE VASCONCELOS) - INEP: 106101
UPDATE schools 
SET inep_code = '106101' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL NICOLAU SAMPAIO' 
  AND UPPER(TRIM(city)) = 'DIOGO DE VASCONCELOS' 
  AND inep_code IS NULL;

-- EE DOUTOR RAUL SOARES (ITABIRITO) - INEP: 106143
UPDATE schools 
SET inep_code = '106143' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR RAUL SOARES' 
  AND UPPER(TRIM(city)) = 'ITABIRITO' 
  AND inep_code IS NULL;

-- EE ENGENHEIRO QUEIROZ JÚNIOR (ITABIRITO) - INEP: 106151
UPDATE schools 
SET inep_code = '106151' 
WHERE UPPER(TRIM(name)) = 'EE ENGENHEIRO QUEIROZ JÚNIOR' 
  AND UPPER(TRIM(city)) = 'ITABIRITO' 
  AND inep_code IS NULL;

-- EE HENRIQUE MICHEL (ITABIRITO) - INEP: 106160
UPDATE schools 
SET inep_code = '106160' 
WHERE UPPER(TRIM(name)) = 'EE HENRIQUE MICHEL' 
  AND UPPER(TRIM(city)) = 'ITABIRITO' 
  AND inep_code IS NULL;

-- EE INTENDENTE CÂMARA (ITABIRITO) - INEP: 106178
UPDATE schools 
SET inep_code = '106178' 
WHERE UPPER(TRIM(name)) = 'EE INTENDENTE CÂMARA' 
  AND UPPER(TRIM(city)) = 'ITABIRITO' 
  AND inep_code IS NULL;

-- EE PROFESSOR TIBÚRCIO (ITABIRITO) - INEP: 106127
UPDATE schools 
SET inep_code = '106127' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR TIBÚRCIO' 
  AND UPPER(TRIM(city)) = 'ITABIRITO' 
  AND inep_code IS NULL;

-- EE CÔNEGO BRAGA (MARIANA) - INEP: 106372
UPDATE schools 
SET inep_code = '106372' 
WHERE UPPER(TRIM(name)) = 'EE CÔNEGO BRAGA' 
  AND UPPER(TRIM(city)) = 'MARIANA' 
  AND inep_code IS NULL;

-- EE CÔNEGO MAURO DE FARIA (MARIANA) - INEP: 106348
UPDATE schools 
SET inep_code = '106348' 
WHERE UPPER(TRIM(name)) = 'EE CÔNEGO MAURO DE FARIA' 
  AND UPPER(TRIM(city)) = 'MARIANA' 
  AND inep_code IS NULL;

-- EE CORONEL BENJAMIM GUIMARÃES (MARIANA) - INEP: 106399
UPDATE schools 
SET inep_code = '106399' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL BENJAMIM GUIMARÃES' 
  AND UPPER(TRIM(city)) = 'MARIANA' 
  AND inep_code IS NULL;

-- EE DOM BENEVIDES (MARIANA) - INEP: 106275
UPDATE schools 
SET inep_code = '106275' 
WHERE UPPER(TRIM(name)) = 'EE DOM BENEVIDES' 
  AND UPPER(TRIM(city)) = 'MARIANA' 
  AND inep_code IS NULL;

-- EE DOM SILVÉRIO (MARIANA) - INEP: 106291
UPDATE schools 
SET inep_code = '106291' 
WHERE UPPER(TRIM(name)) = 'EE DOM SILVÉRIO' 
  AND UPPER(TRIM(city)) = 'MARIANA' 
  AND inep_code IS NULL;

-- EE DONA REPARATA DIAS DE OLIVEIRA (MARIANA) - INEP: 106259
UPDATE schools 
SET inep_code = '106259' 
WHERE UPPER(TRIM(name)) = 'EE DONA REPARATA DIAS DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'MARIANA' 
  AND inep_code IS NULL;

-- EE DOUTOR GOMES FREIRE (MARIANA) - INEP: 106283
UPDATE schools 
SET inep_code = '106283' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR GOMES FREIRE' 
  AND UPPER(TRIM(city)) = 'MARIANA' 
  AND inep_code IS NULL;

-- EE JOÃO RAMOS FILHO (MARIANA) - INEP: 356808
UPDATE schools 
SET inep_code = '356808' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO RAMOS FILHO' 
  AND UPPER(TRIM(city)) = 'MARIANA' 
  AND inep_code IS NULL;

-- EE MONSENHOR MORAIS (MARIANA) - INEP: 106364
UPDATE schools 
SET inep_code = '106364' 
WHERE UPPER(TRIM(name)) = 'EE MONSENHOR MORAIS' 
  AND UPPER(TRIM(city)) = 'MARIANA' 
  AND inep_code IS NULL;

-- EE PADRE VIEGAS (MARIANA) - INEP: 106381
UPDATE schools 
SET inep_code = '106381' 
WHERE UPPER(TRIM(name)) = 'EE PADRE VIEGAS' 
  AND UPPER(TRIM(city)) = 'MARIANA' 
  AND inep_code IS NULL;

-- EE PROFESSOR SOARES FERREIRA (MARIANA) - INEP: 106321
UPDATE schools 
SET inep_code = '106321' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR SOARES FERREIRA' 
  AND UPPER(TRIM(city)) = 'MARIANA' 
  AND inep_code IS NULL;

-- EE ANTÔNIO PEREIRA (OURO PRETO) - INEP: 106631
UPDATE schools 
SET inep_code = '106631' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO PEREIRA' 
  AND UPPER(TRIM(city)) = 'OURO PRETO' 
  AND inep_code IS NULL;

-- EE DE OURO PRETO (OURO PRETO) - INEP: 106488
UPDATE schools 
SET inep_code = '106488' 
WHERE UPPER(TRIM(name)) = 'EE DE OURO PRETO' 
  AND UPPER(TRIM(city)) = 'OURO PRETO' 
  AND inep_code IS NULL;

-- EE DESEMBARGADOR HORÁCIO ANDRADE (OURO PRETO) - INEP: 106496
UPDATE schools 
SET inep_code = '106496' 
WHERE UPPER(TRIM(name)) = 'EE DESEMBARGADOR HORÁCIO ANDRADE' 
  AND UPPER(TRIM(city)) = 'OURO PRETO' 
  AND inep_code IS NULL;

-- EE DOM PEDRO II (OURO PRETO) - INEP: 106500
UPDATE schools 
SET inep_code = '106500' 
WHERE UPPER(TRIM(name)) = 'EE DOM PEDRO II' 
  AND UPPER(TRIM(city)) = 'OURO PRETO' 
  AND inep_code IS NULL;

-- EE DOM VELLOSO (OURO PRETO) - INEP: 106470
UPDATE schools 
SET inep_code = '106470' 
WHERE UPPER(TRIM(name)) = 'EE DOM VELLOSO' 
  AND UPPER(TRIM(city)) = 'OURO PRETO' 
  AND inep_code IS NULL;

-- EE JOSÉ LEANDRO (OURO PRETO) - INEP: 106721
UPDATE schools 
SET inep_code = '106721' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ LEANDRO' 
  AND UPPER(TRIM(city)) = 'OURO PRETO' 
  AND inep_code IS NULL;

-- EE MARÍLIA DE DIRCEU (OURO PRETO) - INEP: 106526
UPDATE schools 
SET inep_code = '106526' 
WHERE UPPER(TRIM(name)) = 'EE MARÍLIA DE DIRCEU' 
  AND UPPER(TRIM(city)) = 'OURO PRETO' 
  AND inep_code IS NULL;

-- EE NOSSA SENHORA AUXILIADORA (OURO PRETO) - INEP: 106658
UPDATE schools 
SET inep_code = '106658' 
WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA AUXILIADORA' 
  AND UPPER(TRIM(city)) = 'OURO PRETO' 
  AND inep_code IS NULL;

-- EE PADRE AFONSO DE LEMOS (OURO PRETO) - INEP: 106666
UPDATE schools 
SET inep_code = '106666' 
WHERE UPPER(TRIM(name)) = 'EE PADRE AFONSO DE LEMOS' 
  AND UPPER(TRIM(city)) = 'OURO PRETO' 
  AND inep_code IS NULL;

-- EE PROFESSORA DAURA DE CARVALHO NETO (OURO PRETO) - INEP: 338915
UPDATE schools 
SET inep_code = '338915' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA DAURA DE CARVALHO NETO' 
  AND UPPER(TRIM(city)) = 'OURO PRETO' 
  AND inep_code IS NULL;

-- EE PROFESSORA MARIA DO CARMO ALMEIDA (OURO PRETO) - INEP: 351059
UPDATE schools 
SET inep_code = '351059' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA DO CARMO ALMEIDA' 
  AND UPPER(TRIM(city)) = 'OURO PRETO' 
  AND inep_code IS NULL;

-- EE SORAMA GERALDA RICHARD XAVIER (BIQUINHAS) - INEP: 305626
UPDATE schools 
SET inep_code = '305626' 
WHERE UPPER(TRIM(name)) = 'EE SORAMA GERALDA RICHARD XAVIER' 
  AND UPPER(TRIM(city)) = 'BIQUINHAS' 
  AND inep_code IS NULL;

-- EE CORONEL EGÍDIO BENÍCIO DE ABREU (BOM DESPACHO) - INEP: 311898
UPDATE schools 
SET inep_code = '311898' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL EGÍDIO BENÍCIO DE ABREU' 
  AND UPPER(TRIM(city)) = 'BOM DESPACHO' 
  AND inep_code IS NULL;

-- EE JOSÉ RIBEIRO DE ANDRADE (CEDRO DO ABAETÉ) - INEP: 307343
UPDATE schools 
SET inep_code = '307343' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ RIBEIRO DE ANDRADE' 
  AND UPPER(TRIM(city)) = 'CEDRO DO ABAETÉ' 
  AND inep_code IS NULL;

-- EE INDÍGENA CAXIXÓ TAOCA SÉRGIA (MARTINHO CAMPOS) - INEP: 322865
UPDATE schools 
SET inep_code = '322865' 
WHERE UPPER(TRIM(name)) = 'EE INDÍGENA CAXIXÓ TAOCA SÉRGIA' 
  AND UPPER(TRIM(city)) = 'MARTINHO CAMPOS' 
  AND inep_code IS NULL;

-- EE AVANY VILLENA DINIZ (PARÁ DE MINAS) - INEP: 346152
UPDATE schools 
SET inep_code = '346152' 
WHERE UPPER(TRIM(name)) = 'EE AVANY VILLENA DINIZ' 
  AND UPPER(TRIM(city)) = 'PARÁ DE MINAS' 
  AND inep_code IS NULL;

-- EE PADRE LIBÉRIO (PARÁ DE MINAS) - INEP: 353477
UPDATE schools 
SET inep_code = '353477' 
WHERE UPPER(TRIM(name)) = 'EE PADRE LIBÉRIO' 
  AND UPPER(TRIM(city)) = 'PARÁ DE MINAS' 
  AND inep_code IS NULL;

-- EE PROFESSOR AGMAR GOMES DO COUTO - PDPC (PARÁ DE MINAS) - INEP: 326691
UPDATE schools 
SET inep_code = '326691' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR AGMAR GOMES DO COUTO - PDPC' 
  AND UPPER(TRIM(city)) = 'PARÁ DE MINAS' 
  AND inep_code IS NULL;

-- EE PROFESSOR WILSON DE MELO GUIMARÃES (PARÁ DE MINAS) - INEP: 233391
UPDATE schools 
SET inep_code = '233391' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR WILSON DE MELO GUIMARÃES' 
  AND UPPER(TRIM(city)) = 'PARÁ DE MINAS' 
  AND inep_code IS NULL;

-- EE TORQUATO DE ALMEIDA (PARÁ DE MINAS) - INEP: 307408
UPDATE schools 
SET inep_code = '307408' 
WHERE UPPER(TRIM(name)) = 'EE TORQUATO DE ALMEIDA' 
  AND UPPER(TRIM(city)) = 'PARÁ DE MINAS' 
  AND inep_code IS NULL;

-- EE GUSTAVO CAPANEMA (PITANGUI) - INEP: 310522
UPDATE schools 
SET inep_code = '310522' 
WHERE UPPER(TRIM(name)) = 'EE GUSTAVO CAPANEMA' 
  AND UPPER(TRIM(city)) = 'PITANGUI' 
  AND inep_code IS NULL;

-- INSTITUTO TECNOLÓGICO DE AGROPECUÁRIA DE PITANGUI - ITAP (PITANGUI) - INEP: 217905
UPDATE schools 
SET inep_code = '217905' 
WHERE UPPER(TRIM(name)) = 'INSTITUTO TECNOLÓGICO DE AGROPECUÁRIA DE PITANGUI - ITAP' 
  AND UPPER(TRIM(city)) = 'PITANGUI' 
  AND inep_code IS NULL;

-- EE SEBASTIÃO CAMPOS (QUARTEL GERAL) - INEP: 305651
UPDATE schools 
SET inep_code = '305651' 
WHERE UPPER(TRIM(name)) = 'EE SEBASTIÃO CAMPOS' 
  AND UPPER(TRIM(city)) = 'QUARTEL GERAL' 
  AND inep_code IS NULL;

-- EE ALMINDA ALVES DA SILVA (BRASILÂNDIA DE MINAS) - INEP: 239402
UPDATE schools 
SET inep_code = '239402' 
WHERE UPPER(TRIM(name)) = 'EE ALMINDA ALVES DA SILVA' 
  AND UPPER(TRIM(city)) = 'BRASILÂNDIA DE MINAS' 
  AND inep_code IS NULL;

-- EE CYRO GÓES (BRASILÂNDIA DE MINAS) - INEP: 108731
UPDATE schools 
SET inep_code = '108731' 
WHERE UPPER(TRIM(name)) = 'EE CYRO GÓES' 
  AND UPPER(TRIM(city)) = 'BRASILÂNDIA DE MINAS' 
  AND inep_code IS NULL;

-- EE DOUTOR JOSÉ PACHECO PIMENTA (BRASILÂNDIA DE MINAS) - INEP: 108669
UPDATE schools 
SET inep_code = '108669' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR JOSÉ PACHECO PIMENTA' 
  AND UPPER(TRIM(city)) = 'BRASILÂNDIA DE MINAS' 
  AND inep_code IS NULL;

-- EE DOUTOR ANTÔNIO RIBEIRO (GUARDA-MOR) - INEP: 108481
UPDATE schools 
SET inep_code = '108481' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR ANTÔNIO RIBEIRO' 
  AND UPPER(TRIM(city)) = 'GUARDA-MOR' 
  AND inep_code IS NULL;

-- EE ARMINDA MARIA DA COSTA (JOÃO PINHEIRO) - INEP: 108553
UPDATE schools 
SET inep_code = '108553' 
WHERE UPPER(TRIM(name)) = 'EE ARMINDA MARIA DA COSTA' 
  AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' 
  AND inep_code IS NULL;

-- EE CAPITÃO SPERIDIÃO (JOÃO PINHEIRO) - INEP: 108511
UPDATE schools 
SET inep_code = '108511' 
WHERE UPPER(TRIM(name)) = 'EE CAPITÃO SPERIDIÃO' 
  AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' 
  AND inep_code IS NULL;

-- EE JOÃO GUIMARÃES ROSA (JOÃO PINHEIRO) - INEP: 108596
UPDATE schools 
SET inep_code = '108596' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO GUIMARÃES ROSA' 
  AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' 
  AND inep_code IS NULL;

-- EE JOSÉ ROMERO DA SILVEIRA (JOÃO PINHEIRO) - INEP: 220671
UPDATE schools 
SET inep_code = '220671' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ ROMERO DA SILVEIRA' 
  AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' 
  AND inep_code IS NULL;

-- EE MARIA GONÇALVES AZEVEDO (JOÃO PINHEIRO) - INEP: 108561
UPDATE schools 
SET inep_code = '108561' 
WHERE UPPER(TRIM(name)) = 'EE MARIA GONÇALVES AZEVEDO' 
  AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' 
  AND inep_code IS NULL;

-- EE MARIA JOSÉ DE PAULA (JOÃO PINHEIRO) - INEP: 108570
UPDATE schools 
SET inep_code = '108570' 
WHERE UPPER(TRIM(name)) = 'EE MARIA JOSÉ DE PAULA' 
  AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' 
  AND inep_code IS NULL;

-- EE PRESIDENTE OLEGÁRIO (JOÃO PINHEIRO) - INEP: 108529
UPDATE schools 
SET inep_code = '108529' 
WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE OLEGÁRIO' 
  AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' 
  AND inep_code IS NULL;

-- EE PROFESSORA ORLINDA SARAIVA SIMÕES (JOÃO PINHEIRO) - INEP: 108545
UPDATE schools 
SET inep_code = '108545' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ORLINDA SARAIVA SIMÕES' 
  AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' 
  AND inep_code IS NULL;

-- EE QUINTINO VARGAS (JOÃO PINHEIRO) - INEP: 108537
UPDATE schools 
SET inep_code = '108537' 
WHERE UPPER(TRIM(name)) = 'EE QUINTINO VARGAS' 
  AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' 
  AND inep_code IS NULL;

-- EE SEBASTIÃO SIMÃO DE MELO (JOÃO PINHEIRO) - INEP: 256234
UPDATE schools 
SET inep_code = '256234' 
WHERE UPPER(TRIM(name)) = 'EE SEBASTIÃO SIMÃO DE MELO' 
  AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' 
  AND inep_code IS NULL;

-- EE TANCREDO DE ALMEIDA NEVES (JOÃO PINHEIRO) - INEP: 108588
UPDATE schools 
SET inep_code = '108588' 
WHERE UPPER(TRIM(name)) = 'EE TANCREDO DE ALMEIDA NEVES' 
  AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' 
  AND inep_code IS NULL;

-- EE TEOTÔNIO BRANDÃO VILELA (JOÃO PINHEIRO) - INEP: 108766
UPDATE schools 
SET inep_code = '108766' 
WHERE UPPER(TRIM(name)) = 'EE TEOTÔNIO BRANDÃO VILELA' 
  AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' 
  AND inep_code IS NULL;

-- CESEC CÂNDIDA PIMENTEL ULHOA (PARACATU) - INEP: 108928
UPDATE schools 
SET inep_code = '108928' 
WHERE UPPER(TRIM(name)) = 'CESEC CÂNDIDA PIMENTEL ULHOA' 
  AND UPPER(TRIM(city)) = 'PARACATU' 
  AND inep_code IS NULL;

-- EE AFFONSO ROQUETTE (PARACATU) - INEP: 108839
UPDATE schools 
SET inep_code = '108839' 
WHERE UPPER(TRIM(name)) = 'EE AFFONSO ROQUETTE' 
  AND UPPER(TRIM(city)) = 'PARACATU' 
  AND inep_code IS NULL;

-- EE AFONSO ARINOS (PARACATU) - INEP: 108812
UPDATE schools 
SET inep_code = '108812' 
WHERE UPPER(TRIM(name)) = 'EE AFONSO ARINOS' 
  AND UPPER(TRIM(city)) = 'PARACATU' 
  AND inep_code IS NULL;

-- EE ALTINA DE PAULA GUIMARÃES (PARACATU) - INEP: 108863
UPDATE schools 
SET inep_code = '108863' 
WHERE UPPER(TRIM(name)) = 'EE ALTINA DE PAULA GUIMARÃES' 
  AND UPPER(TRIM(city)) = 'PARACATU' 
  AND inep_code IS NULL;

-- EE ANTÔNIO CARLOS (PARACATU) - INEP: 108855
UPDATE schools 
SET inep_code = '108855' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO CARLOS' 
  AND UPPER(TRIM(city)) = 'PARACATU' 
  AND inep_code IS NULL;

-- EE DA FAZENDA RIACHO LAFERSA (PARACATU) - INEP: 108901
UPDATE schools 
SET inep_code = '108901' 
WHERE UPPER(TRIM(name)) = 'EE DA FAZENDA RIACHO LAFERSA' 
  AND UPPER(TRIM(city)) = 'PARACATU' 
  AND inep_code IS NULL;

-- EE DELANO BROCHADO ADJUTO (PARACATU) - INEP: 220663
UPDATE schools 
SET inep_code = '220663' 
WHERE UPPER(TRIM(name)) = 'EE DELANO BROCHADO ADJUTO' 
  AND UPPER(TRIM(city)) = 'PARACATU' 
  AND inep_code IS NULL;

-- EE DOM SERAFIM GOMES JARDIM (PARACATU) - INEP: 108952
UPDATE schools 
SET inep_code = '108952' 
WHERE UPPER(TRIM(name)) = 'EE DOM SERAFIM GOMES JARDIM' 
  AND UPPER(TRIM(city)) = 'PARACATU' 
  AND inep_code IS NULL;

-- EE DOUTOR SÉRGIO ULHOA (PARACATU) - INEP: 108961
UPDATE schools 
SET inep_code = '108961' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR SÉRGIO ULHOA' 
  AND UPPER(TRIM(city)) = 'PARACATU' 
  AND inep_code IS NULL;

-- EE DOUTOR VIRGÍLIO DE MELO FRANCO (PARACATU) - INEP: 108847
UPDATE schools 
SET inep_code = '108847' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR VIRGÍLIO DE MELO FRANCO' 
  AND UPPER(TRIM(city)) = 'PARACATU' 
  AND inep_code IS NULL;

-- EE JÚLIA CAMARGOS (PARACATU) - INEP: 108979
UPDATE schools 
SET inep_code = '108979' 
WHERE UPPER(TRIM(name)) = 'EE JÚLIA CAMARGOS' 
  AND UPPER(TRIM(city)) = 'PARACATU' 
  AND inep_code IS NULL;

-- EE NEUSA PIMENTEL BARBOSA (PARACATU) - INEP: 353205
UPDATE schools 
SET inep_code = '353205' 
WHERE UPPER(TRIM(name)) = 'EE NEUSA PIMENTEL BARBOSA' 
  AND UPPER(TRIM(city)) = 'PARACATU' 
  AND inep_code IS NULL;

-- EE OLINDINA LOUREIRO (PARACATU) - INEP: 108880
UPDATE schools 
SET inep_code = '108880' 
WHERE UPPER(TRIM(name)) = 'EE OLINDINA LOUREIRO' 
  AND UPPER(TRIM(city)) = 'PARACATU' 
  AND inep_code IS NULL;

-- EE PROFESSOR JOSINO NEIVA (PARACATU) - INEP: 108804
UPDATE schools 
SET inep_code = '108804' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOSINO NEIVA' 
  AND UPPER(TRIM(city)) = 'PARACATU' 
  AND inep_code IS NULL;

-- EE TEMÍSTOCLES ROCHA (PARACATU) - INEP: 108821
UPDATE schools 
SET inep_code = '108821' 
WHERE UPPER(TRIM(name)) = 'EE TEMÍSTOCLES ROCHA' 
  AND UPPER(TRIM(city)) = 'PARACATU' 
  AND inep_code IS NULL;

-- EE CAROLINA SILVA (VAZANTE) - INEP: 308412
UPDATE schools 
SET inep_code = '308412' 
WHERE UPPER(TRIM(name)) = 'EE CAROLINA SILVA' 
  AND UPPER(TRIM(city)) = 'VAZANTE' 
  AND inep_code IS NULL;

-- EE DEPUTADO CÂNDIDO ULHOA (VAZANTE) - INEP: 109134
UPDATE schools 
SET inep_code = '109134' 
WHERE UPPER(TRIM(name)) = 'EE DEPUTADO CÂNDIDO ULHOA' 
  AND UPPER(TRIM(city)) = 'VAZANTE' 
  AND inep_code IS NULL;

-- EE DONA MARIANA SOLIS ROSA (VAZANTE) - INEP: 109177
UPDATE schools 
SET inep_code = '109177' 
WHERE UPPER(TRIM(name)) = 'EE DONA MARIANA SOLIS ROSA' 
  AND UPPER(TRIM(city)) = 'VAZANTE' 
  AND inep_code IS NULL;

-- EE PEDRO PEREIRA GUIMARÃES (VAZANTE) - INEP: 109151
UPDATE schools 
SET inep_code = '109151' 
WHERE UPPER(TRIM(name)) = 'EE PEDRO PEREIRA GUIMARÃES' 
  AND UPPER(TRIM(city)) = 'VAZANTE' 
  AND inep_code IS NULL;

-- EE PRESIDENTE JUSCELINO KUBITSCHEK DE OLIVEIRA (VAZANTE) - INEP: 109169
UPDATE schools 
SET inep_code = '109169' 
WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE JUSCELINO KUBITSCHEK DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'VAZANTE' 
  AND inep_code IS NULL;

-- CESEC DOUTOR HÉLIO FERREIRA LOPES (ALPINÓPOLIS) - INEP: 114898
UPDATE schools 
SET inep_code = '114898' 
WHERE UPPER(TRIM(name)) = 'CESEC DOUTOR HÉLIO FERREIRA LOPES' 
  AND UPPER(TRIM(city)) = 'ALPINÓPOLIS' 
  AND inep_code IS NULL;

-- EE DOM JOÃO VI (ALPINÓPOLIS) - INEP: 114863
UPDATE schools 
SET inep_code = '114863' 
WHERE UPPER(TRIM(name)) = 'EE DOM JOÃO VI' 
  AND UPPER(TRIM(city)) = 'ALPINÓPOLIS' 
  AND inep_code IS NULL;

-- EE DONA INDÁ (ALPINÓPOLIS) - INEP: 114855
UPDATE schools 
SET inep_code = '114855' 
WHERE UPPER(TRIM(name)) = 'EE DONA INDÁ' 
  AND UPPER(TRIM(city)) = 'ALPINÓPOLIS' 
  AND inep_code IS NULL;

-- EE CORONEL ANTÔNIO DOMINGOS RIBEIRO (BOM JESUS DA PENHA) - INEP: 123901
UPDATE schools 
SET inep_code = '123901' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL ANTÔNIO DOMINGOS RIBEIRO' 
  AND UPPER(TRIM(city)) = 'BOM JESUS DA PENHA' 
  AND inep_code IS NULL;

-- EE CORONEL LOURENÇO BELO (CAPITÓLIO) - INEP: 317462
UPDATE schools 
SET inep_code = '317462' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL LOURENÇO BELO' 
  AND UPPER(TRIM(city)) = 'CAPITÓLIO' 
  AND inep_code IS NULL;

-- EE MODESTO ANTÔNIO DE OLIVEIRA (CAPITÓLIO) - INEP: 114961
UPDATE schools 
SET inep_code = '114961' 
WHERE UPPER(TRIM(name)) = 'EE MODESTO ANTÔNIO DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'CAPITÓLIO' 
  AND inep_code IS NULL;

-- EE GERALDO DE ANDRADE VILELA (CARMO DO RIO CLARO) - INEP: 115061
UPDATE schools 
SET inep_code = '115061' 
WHERE UPPER(TRIM(name)) = 'EE GERALDO DE ANDRADE VILELA' 
  AND UPPER(TRIM(city)) = 'CARMO DO RIO CLARO' 
  AND inep_code IS NULL;

-- EE MONSENHOR MÁRIO ARAÚJO GUIMARÃES (CARMO DO RIO CLARO) - INEP: 115088
UPDATE schools 
SET inep_code = '115088' 
WHERE UPPER(TRIM(name)) = 'EE MONSENHOR MÁRIO ARAÚJO GUIMARÃES' 
  AND UPPER(TRIM(city)) = 'CARMO DO RIO CLARO' 
  AND inep_code IS NULL;

-- EE PADRE JOSÉ SANGALI (CÓRREGO FUNDO) - INEP: 115347
UPDATE schools 
SET inep_code = '115347' 
WHERE UPPER(TRIM(name)) = 'EE PADRE JOSÉ SANGALI' 
  AND UPPER(TRIM(city)) = 'CÓRREGO FUNDO' 
  AND inep_code IS NULL;

-- EE PROFESSORA NEIVA MARIA LEITE (DELFINÓPOLIS) - INEP: 115126
UPDATE schools 
SET inep_code = '115126' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA NEIVA MARIA LEITE' 
  AND UPPER(TRIM(city)) = 'DELFINÓPOLIS' 
  AND inep_code IS NULL;

-- EE STA TEREZINHA (DORESÓPOLIS) - INEP: 115177
UPDATE schools 
SET inep_code = '115177' 
WHERE UPPER(TRIM(name)) = 'EE STA TEREZINHA' 
  AND UPPER(TRIM(city)) = 'DORESÓPOLIS' 
  AND inep_code IS NULL;

-- CESEC ÂNGELA MARIA CASSEMIRO CORRÊA (FORMIGA) - INEP: 313700
UPDATE schools 
SET inep_code = '313700' 
WHERE UPPER(TRIM(name)) = 'CESEC ÂNGELA MARIA CASSEMIRO CORRÊA' 
  AND UPPER(TRIM(city)) = 'FORMIGA' 
  AND inep_code IS NULL;

-- EE AURELIANO RODRIGUES NUNES (FORMIGA) - INEP: 115258
UPDATE schools 
SET inep_code = '115258' 
WHERE UPPER(TRIM(name)) = 'EE AURELIANO RODRIGUES NUNES' 
  AND UPPER(TRIM(city)) = 'FORMIGA' 
  AND inep_code IS NULL;

-- EE DR ABÍLIO MACHADO (FORMIGA) - INEP: 115282
UPDATE schools 
SET inep_code = '115282' 
WHERE UPPER(TRIM(name)) = 'EE DR ABÍLIO MACHADO' 
  AND UPPER(TRIM(city)) = 'FORMIGA' 
  AND inep_code IS NULL;

-- EE JALCIRA SANTOS VALADÃO (FORMIGA) - INEP: 115266
UPDATE schools 
SET inep_code = '115266' 
WHERE UPPER(TRIM(name)) = 'EE JALCIRA SANTOS VALADÃO' 
  AND UPPER(TRIM(city)) = 'FORMIGA' 
  AND inep_code IS NULL;

-- EE JOSÉ BERNARDES DE FARIA (FORMIGA) - INEP: 115304
UPDATE schools 
SET inep_code = '115304' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ BERNARDES DE FARIA' 
  AND UPPER(TRIM(city)) = 'FORMIGA' 
  AND inep_code IS NULL;

-- EE PROFESSOR JOAQUIM RODARTE (FORMIGA) - INEP: 115207
UPDATE schools 
SET inep_code = '115207' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOAQUIM RODARTE' 
  AND UPPER(TRIM(city)) = 'FORMIGA' 
  AND inep_code IS NULL;

-- EE PROFESSOR TONICO LEITE (FORMIGA) - INEP: 115223
UPDATE schools 
SET inep_code = '115223' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR TONICO LEITE' 
  AND UPPER(TRIM(city)) = 'FORMIGA' 
  AND inep_code IS NULL;

-- EE PROFESSORA MARIA APARECIDA COSTA DE RESENDE (FORMIGA) - INEP: 339091
UPDATE schools 
SET inep_code = '339091' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA APARECIDA COSTA DE RESENDE' 
  AND UPPER(TRIM(city)) = 'FORMIGA' 
  AND inep_code IS NULL;

-- EE RODOLFO ALMEIDA (FORMIGA) - INEP: 115240
UPDATE schools 
SET inep_code = '115240' 
WHERE UPPER(TRIM(name)) = 'EE RODOLFO ALMEIDA' 
  AND UPPER(TRIM(city)) = 'FORMIGA' 
  AND inep_code IS NULL;

-- EE DOUTOR NORALDINO DE LIMA (FORTALEZA DE MINAS) - INEP: 115363
UPDATE schools 
SET inep_code = '115363' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR NORALDINO DE LIMA' 
  AND UPPER(TRIM(city)) = 'FORTALEZA DE MINAS' 
  AND inep_code IS NULL;

-- CESEC DONA EMÍLIA LEAL (PASSOS) - INEP: 232653
UPDATE schools 
SET inep_code = '232653' 
WHERE UPPER(TRIM(name)) = 'CESEC DONA EMÍLIA LEAL' 
  AND UPPER(TRIM(city)) = 'PASSOS' 
  AND inep_code IS NULL;

-- COLÉGIO TIRADENTES PMMG (PASSOS) - INEP: 115479
UPDATE schools 
SET inep_code = '115479' 
WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG' 
  AND UPPER(TRIM(city)) = 'PASSOS' 
  AND inep_code IS NULL;

-- EE ABRAÃO LINCOLN (PASSOS) - INEP: 115380
UPDATE schools 
SET inep_code = '115380' 
WHERE UPPER(TRIM(name)) = 'EE ABRAÃO LINCOLN' 
  AND UPPER(TRIM(city)) = 'PASSOS' 
  AND inep_code IS NULL;

-- EE CAETANO MACHADO DA SILVEIRA (PASSOS) - INEP: 115401
UPDATE schools 
SET inep_code = '115401' 
WHERE UPPER(TRIM(name)) = 'EE CAETANO MACHADO DA SILVEIRA' 
  AND UPPER(TRIM(city)) = 'PASSOS' 
  AND inep_code IS NULL;

-- EE DEUS UNIVERSO E VIRTUDE (PASSOS) - INEP: 115428
UPDATE schools 
SET inep_code = '115428' 
WHERE UPPER(TRIM(name)) = 'EE DEUS UNIVERSO E VIRTUDE' 
  AND UPPER(TRIM(city)) = 'PASSOS' 
  AND inep_code IS NULL;

-- EE DOUTOR TANCREDO DE ALMEIDA NEVES (PASSOS) - INEP: 115495
UPDATE schools 
SET inep_code = '115495' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR TANCREDO DE ALMEIDA NEVES' 
  AND UPPER(TRIM(city)) = 'PASSOS' 
  AND inep_code IS NULL;

-- EE DULCE FERREIRA DE SOUZA (PASSOS) - INEP: 115576
UPDATE schools 
SET inep_code = '115576' 
WHERE UPPER(TRIM(name)) = 'EE DULCE FERREIRA DE SOUZA' 
  AND UPPER(TRIM(city)) = 'PASSOS' 
  AND inep_code IS NULL;

-- EE FRANCISCO DA SILVA MAIA (PASSOS) - INEP: 115487
UPDATE schools 
SET inep_code = '115487' 
WHERE UPPER(TRIM(name)) = 'EE FRANCISCO DA SILVA MAIA' 
  AND UPPER(TRIM(city)) = 'PASSOS' 
  AND inep_code IS NULL;

-- EE GERALDO STARLING SOARES (PASSOS) - INEP: 115509
UPDATE schools 
SET inep_code = '115509' 
WHERE UPPER(TRIM(name)) = 'EE GERALDO STARLING SOARES' 
  AND UPPER(TRIM(city)) = 'PASSOS' 
  AND inep_code IS NULL;

-- EE LOURENÇO ANDRADE (PASSOS) - INEP: 115533
UPDATE schools 
SET inep_code = '115533' 
WHERE UPPER(TRIM(name)) = 'EE LOURENÇO ANDRADE' 
  AND UPPER(TRIM(city)) = 'PASSOS' 
  AND inep_code IS NULL;

-- EE LUIZ DE MELLO VIANNA SOBRINHO (PASSOS) - INEP: 115541
UPDATE schools 
SET inep_code = '115541' 
WHERE UPPER(TRIM(name)) = 'EE LUIZ DE MELLO VIANNA SOBRINHO' 
  AND UPPER(TRIM(city)) = 'PASSOS' 
  AND inep_code IS NULL;

-- EE NAZLE JABUR (PASSOS) - INEP: 115517
UPDATE schools 
SET inep_code = '115517' 
WHERE UPPER(TRIM(name)) = 'EE NAZLE JABUR' 
  AND UPPER(TRIM(city)) = 'PASSOS' 
  AND inep_code IS NULL;

-- EE NECA QUIRINO (PASSOS) - INEP: 115550
UPDATE schools 
SET inep_code = '115550' 
WHERE UPPER(TRIM(name)) = 'EE NECA QUIRINO' 
  AND UPPER(TRIM(city)) = 'PASSOS' 
  AND inep_code IS NULL;

-- EE NOSSA SENHORA DA PENHA (PASSOS) - INEP: 115568
UPDATE schools 
SET inep_code = '115568' 
WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DA PENHA' 
  AND UPPER(TRIM(city)) = 'PASSOS' 
  AND inep_code IS NULL;

-- EE PROFESSOR JAIR SANTOS (PASSOS) - INEP: 218154
UPDATE schools 
SET inep_code = '218154' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JAIR SANTOS' 
  AND UPPER(TRIM(city)) = 'PASSOS' 
  AND inep_code IS NULL;

-- EE PROFESSORA JÚLIA KUBITSCHEK (PASSOS) - INEP: 115398
UPDATE schools 
SET inep_code = '115398' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA JÚLIA KUBITSCHEK' 
  AND UPPER(TRIM(city)) = 'PASSOS' 
  AND inep_code IS NULL;

-- EE SÃO JOSÉ (PASSOS) - INEP: 115436
UPDATE schools 
SET inep_code = '115436' 
WHERE UPPER(TRIM(name)) = 'EE SÃO JOSÉ' 
  AND UPPER(TRIM(city)) = 'PASSOS' 
  AND inep_code IS NULL;

-- EE PADRE JOSÉ ESPÍNDOLA (PIMENTA) - INEP: 115606
UPDATE schools 
SET inep_code = '115606' 
WHERE UPPER(TRIM(name)) = 'EE PADRE JOSÉ ESPÍNDOLA' 
  AND UPPER(TRIM(city)) = 'PIMENTA' 
  AND inep_code IS NULL;

-- CESEC SEBASTIÃO GONÇALVES DA SILVA (PIUMHI) - INEP: 115720
UPDATE schools 
SET inep_code = '115720' 
WHERE UPPER(TRIM(name)) = 'CESEC SEBASTIÃO GONÇALVES DA SILVA' 
  AND UPPER(TRIM(city)) = 'PIUMHI' 
  AND inep_code IS NULL;

-- EE PROFESSOR FRANCISCO DE PAULA REBELO HORTA (PIUMHI) - INEP: 115690
UPDATE schools 
SET inep_code = '115690' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR FRANCISCO DE PAULA REBELO HORTA' 
  AND UPPER(TRIM(city)) = 'PIUMHI' 
  AND inep_code IS NULL;

-- EE PROFESSOR JOÃO MENEZES (PIUMHI) - INEP: 115703
UPDATE schools 
SET inep_code = '115703' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOÃO MENEZES' 
  AND UPPER(TRIM(city)) = 'PIUMHI' 
  AND inep_code IS NULL;

-- EE PROFESSOR JOSÉ VICENTE (PIUMHI) - INEP: 115711
UPDATE schools 
SET inep_code = '115711' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOSÉ VICENTE' 
  AND UPPER(TRIM(city)) = 'PIUMHI' 
  AND inep_code IS NULL;

-- EE JOSÉ SEVERIANO FILHO (SÃO JOÃO BATISTA DO GLÓRIA) - INEP: 115762
UPDATE schools 
SET inep_code = '115762' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ SEVERIANO FILHO' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO BATISTA DO GLÓRIA' 
  AND inep_code IS NULL;

-- EE DE FURNAS (SÃO JOSÉ DA BARRA) - INEP: 114901
UPDATE schools 
SET inep_code = '114901' 
WHERE UPPER(TRIM(name)) = 'EE DE FURNAS' 
  AND UPPER(TRIM(city)) = 'SÃO JOSÉ DA BARRA' 
  AND inep_code IS NULL;

-- EE DOUTOR JUSCELINO KUBITSCHEK (SÃO JOSÉ DA BARRA) - INEP: 114910
UPDATE schools 
SET inep_code = '114910' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR JUSCELINO KUBITSCHEK' 
  AND UPPER(TRIM(city)) = 'SÃO JOSÉ DA BARRA' 
  AND inep_code IS NULL;

-- EE GENERAL CARNEIRO (SÃO ROQUE DE MINAS) - INEP: 115789
UPDATE schools 
SET inep_code = '115789' 
WHERE UPPER(TRIM(name)) = 'EE GENERAL CARNEIRO' 
  AND UPPER(TRIM(city)) = 'SÃO ROQUE DE MINAS' 
  AND inep_code IS NULL;

-- EE PROFESSORA IZAURA DE OLIVEIRA VILELA (SÃO ROQUE DE MINAS) - INEP: 346136
UPDATE schools 
SET inep_code = '346136' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA IZAURA DE OLIVEIRA VILELA' 
  AND UPPER(TRIM(city)) = 'SÃO ROQUE DE MINAS' 
  AND inep_code IS NULL;

-- EE SÃO FRANCISCO (VARGEM BONITA) - INEP: 115843
UPDATE schools 
SET inep_code = '115843' 
WHERE UPPER(TRIM(name)) = 'EE SÃO FRANCISCO' 
  AND UPPER(TRIM(city)) = 'VARGEM BONITA' 
  AND inep_code IS NULL;

-- EE MANOEL GONÇALVES BOAVENTURA (ARAPUÁ) - INEP: 118419
UPDATE schools 
SET inep_code = '118419' 
WHERE UPPER(TRIM(name)) = 'EE MANOEL GONÇALVES BOAVENTURA' 
  AND UPPER(TRIM(city)) = 'ARAPUÁ' 
  AND inep_code IS NULL;

-- CESEC PROFESSOR ANTÔNIO DE DEUS VIEIRA NETO (CARMO DO PARANAÍBA) - INEP: 118532
UPDATE schools 
SET inep_code = '118532' 
WHERE UPPER(TRIM(name)) = 'CESEC PROFESSOR ANTÔNIO DE DEUS VIEIRA NETO' 
  AND UPPER(TRIM(city)) = 'CARMO DO PARANAÍBA' 
  AND inep_code IS NULL;

-- EE AMADEU GONÇALVES BOAVENTURA (CARMO DO PARANAÍBA) - INEP: 118443
UPDATE schools 
SET inep_code = '118443' 
WHERE UPPER(TRIM(name)) = 'EE AMADEU GONÇALVES BOAVENTURA' 
  AND UPPER(TRIM(city)) = 'CARMO DO PARANAÍBA' 
  AND inep_code IS NULL;

-- EE ANTÔNIO ATANÁSIO (CARMO DO PARANAÍBA) - INEP: 118559
UPDATE schools 
SET inep_code = '118559' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO ATANÁSIO' 
  AND UPPER(TRIM(city)) = 'CARMO DO PARANAÍBA' 
  AND inep_code IS NULL;

-- EE LEÔNCIO FERREIRA DE MELO (CARMO DO PARANAÍBA) - INEP: 305341
UPDATE schools 
SET inep_code = '305341' 
WHERE UPPER(TRIM(name)) = 'EE LEÔNCIO FERREIRA DE MELO' 
  AND UPPER(TRIM(city)) = 'CARMO DO PARANAÍBA' 
  AND inep_code IS NULL;

-- EE NOSSA SENHORA DO CARMO (CARMO DO PARANAÍBA) - INEP: 326631
UPDATE schools 
SET inep_code = '326631' 
WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DO CARMO' 
  AND UPPER(TRIM(city)) = 'CARMO DO PARANAÍBA' 
  AND inep_code IS NULL;


COMMIT;
