-- Lote 1 de 7
-- Updates 1 a 300

BEGIN;

-- =====================================================
-- ATUALIZAÇÃO AUTOMÁTICA DE INEPs
-- Total de escolas ESTADUAIS: 1832
-- =====================================================

BEGIN;

-- EE CORONEL JOSÉ VENÂNCIO DE SOUSA (ÁGUAS VERMELHAS) - INEP: 184381
UPDATE schools 
SET inep_code = '184381' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL JOSÉ VENÂNCIO DE SOUSA' 
  AND UPPER(TRIM(city)) = 'ÁGUAS VERMELHAS' 
  AND inep_code IS NULL;

-- EE DE ITAMARATI (ÁGUAS VERMELHAS) - INEP: 184462
UPDATE schools 
SET inep_code = '184462' 
WHERE UPPER(TRIM(name)) = 'EE DE ITAMARATI' 
  AND UPPER(TRIM(city)) = 'ÁGUAS VERMELHAS' 
  AND inep_code IS NULL;

-- EE DE MACHADO MINEIRO (ÁGUAS VERMELHAS) - INEP: 184403
UPDATE schools 
SET inep_code = '184403' 
WHERE UPPER(TRIM(name)) = 'EE DE MACHADO MINEIRO' 
  AND UPPER(TRIM(city)) = 'ÁGUAS VERMELHAS' 
  AND inep_code IS NULL;

-- EE JOAQUIM FERNANDES ABADE (ÁGUAS VERMELHAS) - INEP: 184420
UPDATE schools 
SET inep_code = '184420' 
WHERE UPPER(TRIM(name)) = 'EE JOAQUIM FERNANDES ABADE' 
  AND UPPER(TRIM(city)) = 'ÁGUAS VERMELHAS' 
  AND inep_code IS NULL;

-- CESEC QUERUBIM FRÓES OTONI (ALMENARA) - INEP: 184578
UPDATE schools 
SET inep_code = '184578' 
WHERE UPPER(TRIM(name)) = 'CESEC QUERUBIM FRÓES OTONI' 
  AND UPPER(TRIM(city)) = 'ALMENARA' 
  AND inep_code IS NULL;

-- EE CONDE AFONSO CELSO (ALMENARA) - INEP: 184527
UPDATE schools 
SET inep_code = '184527' 
WHERE UPPER(TRIM(name)) = 'EE CONDE AFONSO CELSO' 
  AND UPPER(TRIM(city)) = 'ALMENARA' 
  AND inep_code IS NULL;

-- EE DE PEDRA GRANDE (ALMENARA) - INEP: 184608
UPDATE schools 
SET inep_code = '184608' 
WHERE UPPER(TRIM(name)) = 'EE DE PEDRA GRANDE' 
  AND UPPER(TRIM(city)) = 'ALMENARA' 
  AND inep_code IS NULL;

-- EE JOEL MARES (ALMENARA) - INEP: 246336
UPDATE schools 
SET inep_code = '246336' 
WHERE UPPER(TRIM(name)) = 'EE JOEL MARES' 
  AND UPPER(TRIM(city)) = 'ALMENARA' 
  AND inep_code IS NULL;

-- EE JOVIANO NAVES (ALMENARA) - INEP: 184551
UPDATE schools 
SET inep_code = '184551' 
WHERE UPPER(TRIM(name)) = 'EE JOVIANO NAVES' 
  AND UPPER(TRIM(city)) = 'ALMENARA' 
  AND inep_code IS NULL;

-- EE LAUDELINA DIAS LACERDA (ALMENARA) - INEP: 184543
UPDATE schools 
SET inep_code = '184543' 
WHERE UPPER(TRIM(name)) = 'EE LAUDELINA DIAS LACERDA' 
  AND UPPER(TRIM(city)) = 'ALMENARA' 
  AND inep_code IS NULL;

-- EE TANCREDO NEVES (ALMENARA) - INEP: 184519
UPDATE schools 
SET inep_code = '184519' 
WHERE UPPER(TRIM(name)) = 'EE TANCREDO NEVES' 
  AND UPPER(TRIM(city)) = 'ALMENARA' 
  AND inep_code IS NULL;

-- EE JOÃO DOS SANTOS AMARAL (BANDEIRA) - INEP: 184632
UPDATE schools 
SET inep_code = '184632' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO DOS SANTOS AMARAL' 
  AND UPPER(TRIM(city)) = 'BANDEIRA' 
  AND inep_code IS NULL;

-- EE BARÃO DO RIO BRANCO (CACHOEIRA DE PAJEÚ) - INEP: 184616
UPDATE schools 
SET inep_code = '184616' 
WHERE UPPER(TRIM(name)) = 'EE BARÃO DO RIO BRANCO' 
  AND UPPER(TRIM(city)) = 'CACHOEIRA DE PAJEÚ' 
  AND inep_code IS NULL;

-- EE DO CARIRI (CACHOEIRA DE PAJEÚ) - INEP: 246328
UPDATE schools 
SET inep_code = '246328' 
WHERE UPPER(TRIM(name)) = 'EE DO CARIRI' 
  AND UPPER(TRIM(city)) = 'CACHOEIRA DE PAJEÚ' 
  AND inep_code IS NULL;

-- EE DO POVOADO DE ÁGUAS ALTAS (CACHOEIRA DE PAJEÚ) - INEP: 205613
UPDATE schools 
SET inep_code = '205613' 
WHERE UPPER(TRIM(name)) = 'EE DO POVOADO DE ÁGUAS ALTAS' 
  AND UPPER(TRIM(city)) = 'CACHOEIRA DE PAJEÚ' 
  AND inep_code IS NULL;

-- EE DE MARISTELA (CURRAL DE DENTRO) - INEP: 184411
UPDATE schools 
SET inep_code = '184411' 
WHERE UPPER(TRIM(name)) = 'EE DE MARISTELA' 
  AND UPPER(TRIM(city)) = 'CURRAL DE DENTRO' 
  AND inep_code IS NULL;

-- EE VERÍSSIMO TEIXEIRA COSTA (CURRAL DE DENTRO) - INEP: 184446
UPDATE schools 
SET inep_code = '184446' 
WHERE UPPER(TRIM(name)) = 'EE VERÍSSIMO TEIXEIRA COSTA' 
  AND UPPER(TRIM(city)) = 'CURRAL DE DENTRO' 
  AND inep_code IS NULL;

-- EE DE DIVISA ALEGRE (DIVISA ALEGRE) - INEP: 184454
UPDATE schools 
SET inep_code = '184454' 
WHERE UPPER(TRIM(name)) = 'EE DE DIVISA ALEGRE' 
  AND UPPER(TRIM(city)) = 'DIVISA ALEGRE' 
  AND inep_code IS NULL;

-- EE ALBERTO VICENTE PEREIRA (DIVISÓPOLIS) - INEP: 184586
UPDATE schools 
SET inep_code = '184586' 
WHERE UPPER(TRIM(name)) = 'EE ALBERTO VICENTE PEREIRA' 
  AND UPPER(TRIM(city)) = 'DIVISÓPOLIS' 
  AND inep_code IS NULL;

-- EE DE FELISBURGO (FELISBURGO) - INEP: 184691
UPDATE schools 
SET inep_code = '184691' 
WHERE UPPER(TRIM(name)) = 'EE DE FELISBURGO' 
  AND UPPER(TRIM(city)) = 'FELISBURGO' 
  AND inep_code IS NULL;

-- EE TRANQUILINO PINTO COELHO (FELISBURGO) - INEP: 184705
UPDATE schools 
SET inep_code = '184705' 
WHERE UPPER(TRIM(name)) = 'EE TRANQUILINO PINTO COELHO' 
  AND UPPER(TRIM(city)) = 'FELISBURGO' 
  AND inep_code IS NULL;

-- EE ALÍPIO DE MORAES (JACINTO) - INEP: 184764
UPDATE schools 
SET inep_code = '184764' 
WHERE UPPER(TRIM(name)) = 'EE ALÍPIO DE MORAES' 
  AND UPPER(TRIM(city)) = 'JACINTO' 
  AND inep_code IS NULL;

-- EE DO HAVAÍ (JACINTO) - INEP: 184799
UPDATE schools 
SET inep_code = '184799' 
WHERE UPPER(TRIM(name)) = 'EE DO HAVAÍ' 
  AND UPPER(TRIM(city)) = 'JACINTO' 
  AND inep_code IS NULL;

-- EE PROFESSOR ESTÊVÃO ARAÚJO (JACINTO) - INEP: 184756
UPDATE schools 
SET inep_code = '184756' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ESTÊVÃO ARAÚJO' 
  AND UPPER(TRIM(city)) = 'JACINTO' 
  AND inep_code IS NULL;

-- CESEC ZEMARIA DO NORTE (JEQUITINHONHA) - INEP: 184969
UPDATE schools 
SET inep_code = '184969' 
WHERE UPPER(TRIM(name)) = 'CESEC ZEMARIA DO NORTE' 
  AND UPPER(TRIM(city)) = 'JEQUITINHONHA' 
  AND inep_code IS NULL;

-- EE CORONEL JOÃO DA CUNHA (JEQUITINHONHA) - INEP: 184977
UPDATE schools 
SET inep_code = '184977' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL JOÃO DA CUNHA' 
  AND UPPER(TRIM(city)) = 'JEQUITINHONHA' 
  AND inep_code IS NULL;

-- EE CORONEL RAMIRO PEREIRA (JEQUITINHONHA) - INEP: 184837
UPDATE schools 
SET inep_code = '184837' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL RAMIRO PEREIRA' 
  AND UPPER(TRIM(city)) = 'JEQUITINHONHA' 
  AND inep_code IS NULL;

-- EE DOUTOR HENRIQUE HEITMANN (JEQUITINHONHA) - INEP: 232084
UPDATE schools 
SET inep_code = '232084' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR HENRIQUE HEITMANN' 
  AND UPPER(TRIM(city)) = 'JEQUITINHONHA' 
  AND inep_code IS NULL;

-- EE EPAMINONDAS RAMOS (JEQUITINHONHA) - INEP: 184942
UPDATE schools 
SET inep_code = '184942' 
WHERE UPPER(TRIM(name)) = 'EE EPAMINONDAS RAMOS' 
  AND UPPER(TRIM(city)) = 'JEQUITINHONHA' 
  AND inep_code IS NULL;

-- EE PREFEITO EPAMINONDAS RAMOS (JEQUITINHONHA) - INEP: 185001
UPDATE schools 
SET inep_code = '185001' 
WHERE UPPER(TRIM(name)) = 'EE PREFEITO EPAMINONDAS RAMOS' 
  AND UPPER(TRIM(city)) = 'JEQUITINHONHA' 
  AND inep_code IS NULL;

-- EE PROFESSOR MANUEL DO NORTE (JEQUITINHONHA) - INEP: 184900
UPDATE schools 
SET inep_code = '184900' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR MANUEL DO NORTE' 
  AND UPPER(TRIM(city)) = 'JEQUITINHONHA' 
  AND inep_code IS NULL;

-- EE SÃO MIGUEL (JEQUITINHONHA) - INEP: 184918
UPDATE schools 
SET inep_code = '184918' 
WHERE UPPER(TRIM(name)) = 'EE SÃO MIGUEL' 
  AND UPPER(TRIM(city)) = 'JEQUITINHONHA' 
  AND inep_code IS NULL;

-- CESEC DE JOAÍMA (JOAÍMA) - INEP: 312126
UPDATE schools 
SET inep_code = '312126' 
WHERE UPPER(TRIM(name)) = 'CESEC DE JOAÍMA' 
  AND UPPER(TRIM(city)) = 'JOAÍMA' 
  AND inep_code IS NULL;

-- EE DE GIRU (JOAÍMA) - INEP: 185043
UPDATE schools 
SET inep_code = '185043' 
WHERE UPPER(TRIM(name)) = 'EE DE GIRU' 
  AND UPPER(TRIM(city)) = 'JOAÍMA' 
  AND inep_code IS NULL;

-- EE PROFESSOR ANTÔNIO GOMES MOREIRA (JOAÍMA) - INEP: 185019
UPDATE schools 
SET inep_code = '185019' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ANTÔNIO GOMES MOREIRA' 
  AND UPPER(TRIM(city)) = 'JOAÍMA' 
  AND inep_code IS NULL;

-- EE PROFESSOR MANOEL DO NORTE (JOAÍMA) - INEP: 185051
UPDATE schools 
SET inep_code = '185051' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR MANOEL DO NORTE' 
  AND UPPER(TRIM(city)) = 'JOAÍMA' 
  AND inep_code IS NULL;

-- EE DE JORDÂNIA (JORDÂNIA) - INEP: 185078
UPDATE schools 
SET inep_code = '185078' 
WHERE UPPER(TRIM(name)) = 'EE DE JORDÂNIA' 
  AND UPPER(TRIM(city)) = 'JORDÂNIA' 
  AND inep_code IS NULL;

-- EE DOM JOSÉ (JORDÂNIA) - INEP: 185094
UPDATE schools 
SET inep_code = '185094' 
WHERE UPPER(TRIM(name)) = 'EE DOM JOSÉ' 
  AND UPPER(TRIM(city)) = 'JORDÂNIA' 
  AND inep_code IS NULL;

-- EE FREI HENRIQUE DE COIMBRA (JORDÂNIA) - INEP: 185086
UPDATE schools 
SET inep_code = '185086' 
WHERE UPPER(TRIM(name)) = 'EE FREI HENRIQUE DE COIMBRA' 
  AND UPPER(TRIM(city)) = 'JORDÂNIA' 
  AND inep_code IS NULL;

-- EE PROFESSOR MANOEL DA ROCHA PINTO (JORDÂNIA) - INEP: 185116
UPDATE schools 
SET inep_code = '185116' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR MANOEL DA ROCHA PINTO' 
  AND UPPER(TRIM(city)) = 'JORDÂNIA' 
  AND inep_code IS NULL;

-- EE DE MATA VERDE (MATA VERDE) - INEP: 184594
UPDATE schools 
SET inep_code = '184594' 
WHERE UPPER(TRIM(name)) = 'EE DE MATA VERDE' 
  AND UPPER(TRIM(city)) = 'MATA VERDE' 
  AND inep_code IS NULL;

-- EE JOSÉ FERREIRA DA ROCHA (MATA VERDE) - INEP: 209643
UPDATE schools 
SET inep_code = '209643' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ FERREIRA DA ROCHA' 
  AND UPPER(TRIM(city)) = 'MATA VERDE' 
  AND inep_code IS NULL;

-- EE MANOEL DE SOUZA SANTOS (MONTE FORMOSO) - INEP: 185035
UPDATE schools 
SET inep_code = '185035' 
WHERE UPPER(TRIM(name)) = 'EE MANOEL DE SOUZA SANTOS' 
  AND UPPER(TRIM(city)) = 'MONTE FORMOSO' 
  AND inep_code IS NULL;

-- EE DOIS DE ABRIL (PALMÓPOLIS) - INEP: 185329
UPDATE schools 
SET inep_code = '185329' 
WHERE UPPER(TRIM(name)) = 'EE DOIS DE ABRIL' 
  AND UPPER(TRIM(city)) = 'PALMÓPOLIS' 
  AND inep_code IS NULL;

-- EE GOVERNADOR CLÓVIS SALGADO (PALMÓPOLIS) - INEP: 185353
UPDATE schools 
SET inep_code = '185353' 
WHERE UPPER(TRIM(name)) = 'EE GOVERNADOR CLÓVIS SALGADO' 
  AND UPPER(TRIM(city)) = 'PALMÓPOLIS' 
  AND inep_code IS NULL;

-- CESEC EDIRALVA DE OLIVEIRA ALMEIDA (PEDRA AZUL) - INEP: 311952
UPDATE schools 
SET inep_code = '311952' 
WHERE UPPER(TRIM(name)) = 'CESEC EDIRALVA DE OLIVEIRA ALMEIDA' 
  AND UPPER(TRIM(city)) = 'PEDRA AZUL' 
  AND inep_code IS NULL;

-- EE ANA FARIA (PEDRA AZUL) - INEP: 185213
UPDATE schools 
SET inep_code = '185213' 
WHERE UPPER(TRIM(name)) = 'EE ANA FARIA' 
  AND UPPER(TRIM(city)) = 'PEDRA AZUL' 
  AND inep_code IS NULL;

-- EE CASSIANO MENDES (PEDRA AZUL) - INEP: 185205
UPDATE schools 
SET inep_code = '185205' 
WHERE UPPER(TRIM(name)) = 'EE CASSIANO MENDES' 
  AND UPPER(TRIM(city)) = 'PEDRA AZUL' 
  AND inep_code IS NULL;

-- EE CORONEL PACÍFICO FARIA (PEDRA AZUL) - INEP: 185221
UPDATE schools 
SET inep_code = '185221' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL PACÍFICO FARIA' 
  AND UPPER(TRIM(city)) = 'PEDRA AZUL' 
  AND inep_code IS NULL;

-- EE DEPUTADO JOÃO DE ALMEIDA (PEDRA AZUL) - INEP: 212831
UPDATE schools 
SET inep_code = '212831' 
WHERE UPPER(TRIM(name)) = 'EE DEPUTADO JOÃO DE ALMEIDA' 
  AND UPPER(TRIM(city)) = 'PEDRA AZUL' 
  AND inep_code IS NULL;

-- EE GENI MARIA DE SOUZA (RIO DO PRADO) - INEP: 353558
UPDATE schools 
SET inep_code = '353558' 
WHERE UPPER(TRIM(name)) = 'EE GENI MARIA DE SOUZA' 
  AND UPPER(TRIM(city)) = 'RIO DO PRADO' 
  AND inep_code IS NULL;

-- EE PROFESSOR CLEMENTE TRINDADE (RIO DO PRADO) - INEP: 185302
UPDATE schools 
SET inep_code = '185302' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR CLEMENTE TRINDADE' 
  AND UPPER(TRIM(city)) = 'RIO DO PRADO' 
  AND inep_code IS NULL;

-- EE TEREZINHA PORTO FAGUNDES (RIO DO PRADO) - INEP: 245160
UPDATE schools 
SET inep_code = '245160' 
WHERE UPPER(TRIM(name)) = 'EE TEREZINHA PORTO FAGUNDES' 
  AND UPPER(TRIM(city)) = 'RIO DO PRADO' 
  AND inep_code IS NULL;

-- EE LÍDIO ALMEIDA (RUBIM) - INEP: 185396
UPDATE schools 
SET inep_code = '185396' 
WHERE UPPER(TRIM(name)) = 'EE LÍDIO ALMEIDA' 
  AND UPPER(TRIM(city)) = 'RUBIM' 
  AND inep_code IS NULL;

-- EE WALMIR ALMEIDA COSTA (RUBIM) - INEP: 185388
UPDATE schools 
SET inep_code = '185388' 
WHERE UPPER(TRIM(name)) = 'EE WALMIR ALMEIDA COSTA' 
  AND UPPER(TRIM(city)) = 'RUBIM' 
  AND inep_code IS NULL;

-- EE CORONEL ELPÍDIO ALVES FERREIRA (SALTO DA DIVISA) - INEP: 185400
UPDATE schools 
SET inep_code = '185400' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL ELPÍDIO ALVES FERREIRA' 
  AND UPPER(TRIM(city)) = 'SALTO DA DIVISA' 
  AND inep_code IS NULL;

-- EE CORONEL TINÔ (SALTO DA DIVISA) - INEP: 185418
UPDATE schools 
SET inep_code = '185418' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL TINÔ' 
  AND UPPER(TRIM(city)) = 'SALTO DA DIVISA' 
  AND inep_code IS NULL;

-- EE JOSÉ JOAQUIM CABRAL (SANTA MARIA DO SALTO) - INEP: 185442
UPDATE schools 
SET inep_code = '185442' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ JOAQUIM CABRAL' 
  AND UPPER(TRIM(city)) = 'SANTA MARIA DO SALTO' 
  AND inep_code IS NULL;

-- EE CLEMENTE DA ROCHA BANDEIRA (SANTO ANTÔNIO DO JACINTO) - INEP: 185451
UPDATE schools 
SET inep_code = '185451' 
WHERE UPPER(TRIM(name)) = 'EE CLEMENTE DA ROCHA BANDEIRA' 
  AND UPPER(TRIM(city)) = 'SANTO ANTÔNIO DO JACINTO' 
  AND inep_code IS NULL;

-- EE DE CATAJÁS (SANTO ANTÔNIO DO JACINTO) - INEP: 185469
UPDATE schools 
SET inep_code = '185469' 
WHERE UPPER(TRIM(name)) = 'EE DE CATAJÁS' 
  AND UPPER(TRIM(city)) = 'SANTO ANTÔNIO DO JACINTO' 
  AND inep_code IS NULL;

-- EE DO POVOADO DE CRISTIANÓPOLIS (SANTO ANTÔNIO DO JACINTO) - INEP: 246301
UPDATE schools 
SET inep_code = '246301' 
WHERE UPPER(TRIM(name)) = 'EE DO POVOADO DE CRISTIANÓPOLIS' 
  AND UPPER(TRIM(city)) = 'SANTO ANTÔNIO DO JACINTO' 
  AND inep_code IS NULL;

-- EE JOÃO VIEIRA DE SOUZA (SANTO ANTÔNIO DO JACINTO) - INEP: 218324
UPDATE schools 
SET inep_code = '218324' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO VIEIRA DE SOUZA' 
  AND UPPER(TRIM(city)) = 'SANTO ANTÔNIO DO JACINTO' 
  AND inep_code IS NULL;

-- EE ARTHUR BERGANHOLI (ARAÇUAÍ) - INEP: 146005
UPDATE schools 
SET inep_code = '146005' 
WHERE UPPER(TRIM(name)) = 'EE ARTHUR BERGANHOLI' 
  AND UPPER(TRIM(city)) = 'ARAÇUAÍ' 
  AND inep_code IS NULL;

-- EE BOM JESUS DE AGUADA NOVA (ARAÇUAÍ) - INEP: 146013
UPDATE schools 
SET inep_code = '146013' 
WHERE UPPER(TRIM(name)) = 'EE BOM JESUS DE AGUADA NOVA' 
  AND UPPER(TRIM(city)) = 'ARAÇUAÍ' 
  AND inep_code IS NULL;

-- EE DA FAZENDA DIAMANTINO (ARAÇUAÍ) - INEP: 146048
UPDATE schools 
SET inep_code = '146048' 
WHERE UPPER(TRIM(name)) = 'EE DA FAZENDA DIAMANTINO' 
  AND UPPER(TRIM(city)) = 'ARAÇUAÍ' 
  AND inep_code IS NULL;

-- EE DOM JOSÉ DE HAAS (ARAÇUAÍ) - INEP: 146081
UPDATE schools 
SET inep_code = '146081' 
WHERE UPPER(TRIM(name)) = 'EE DOM JOSÉ DE HAAS' 
  AND UPPER(TRIM(city)) = 'ARAÇUAÍ' 
  AND inep_code IS NULL;

-- EE FREI ROGATO (ARAÇUAÍ) - INEP: 247707
UPDATE schools 
SET inep_code = '247707' 
WHERE UPPER(TRIM(name)) = 'EE FREI ROGATO' 
  AND UPPER(TRIM(city)) = 'ARAÇUAÍ' 
  AND inep_code IS NULL;

-- EE HILÁRIO PINHEIRO JARDIM (ARAÇUAÍ) - INEP: 146161
UPDATE schools 
SET inep_code = '146161' 
WHERE UPPER(TRIM(name)) = 'EE HILÁRIO PINHEIRO JARDIM' 
  AND UPPER(TRIM(city)) = 'ARAÇUAÍ' 
  AND inep_code IS NULL;

-- EE INDUSTRIAL SÃO JOSÉ (ARAÇUAÍ) - INEP: 146099
UPDATE schools 
SET inep_code = '146099' 
WHERE UPPER(TRIM(name)) = 'EE INDUSTRIAL SÃO JOSÉ' 
  AND UPPER(TRIM(city)) = 'ARAÇUAÍ' 
  AND inep_code IS NULL;

-- EE ISALTINA CAJUBI FULGÊNCIO (ARAÇUAÍ) - INEP: 146102
UPDATE schools 
SET inep_code = '146102' 
WHERE UPPER(TRIM(name)) = 'EE ISALTINA CAJUBI FULGÊNCIO' 
  AND UPPER(TRIM(city)) = 'ARAÇUAÍ' 
  AND inep_code IS NULL;

-- EE JOSÉ DOS SANTOS NEIVA (ARAÇUAÍ) - INEP: 146170
UPDATE schools 
SET inep_code = '146170' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ DOS SANTOS NEIVA' 
  AND UPPER(TRIM(city)) = 'ARAÇUAÍ' 
  AND inep_code IS NULL;

-- EE PROFESSOR LEOPOLDO PEREIRA (ARAÇUAÍ) - INEP: 146129
UPDATE schools 
SET inep_code = '146129' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR LEOPOLDO PEREIRA' 
  AND UPPER(TRIM(city)) = 'ARAÇUAÍ' 
  AND inep_code IS NULL;

-- EE PROFESSORA APARECIDA DUTRA (ARAÇUAÍ) - INEP: 145998
UPDATE schools 
SET inep_code = '145998' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA APARECIDA DUTRA' 
  AND UPPER(TRIM(city)) = 'ARAÇUAÍ' 
  AND inep_code IS NULL;

-- EE TEREZINHA GONÇALVES DOS SANTOS (ARAÇUAÍ) - INEP: 330809
UPDATE schools 
SET inep_code = '330809' 
WHERE UPPER(TRIM(name)) = 'EE TEREZINHA GONÇALVES DOS SANTOS' 
  AND UPPER(TRIM(city)) = 'ARAÇUAÍ' 
  AND inep_code IS NULL;

-- EE DE BERILO (BERILO) - INEP: 330655
UPDATE schools 
SET inep_code = '330655' 
WHERE UPPER(TRIM(name)) = 'EE DE BERILO' 
  AND UPPER(TRIM(city)) = 'BERILO' 
  AND inep_code IS NULL;

-- EE ANTÔNIO MARQUES DE ABREU (CHAPADA DO NORTE) - INEP: 338729
UPDATE schools 
SET inep_code = '338729' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO MARQUES DE ABREU' 
  AND UPPER(TRIM(city)) = 'CHAPADA DO NORTE' 
  AND inep_code IS NULL;

-- EE ALPHONSUS DE GUIMARÃES (COMERCINHO) - INEP: 184641
UPDATE schools 
SET inep_code = '184641' 
WHERE UPPER(TRIM(name)) = 'EE ALPHONSUS DE GUIMARÃES' 
  AND UPPER(TRIM(city)) = 'COMERCINHO' 
  AND inep_code IS NULL;

-- EE FERNANDO DA COSTA AMARAL (COMERCINHO) - INEP: 184667
UPDATE schools 
SET inep_code = '184667' 
WHERE UPPER(TRIM(name)) = 'EE FERNANDO DA COSTA AMARAL' 
  AND UPPER(TRIM(city)) = 'COMERCINHO' 
  AND inep_code IS NULL;

-- EE ARTHUR ANTÔNIO FERNANDES (CORONEL MURTA) - INEP: 146676
UPDATE schools 
SET inep_code = '146676' 
WHERE UPPER(TRIM(name)) = 'EE ARTHUR ANTÔNIO FERNANDES' 
  AND UPPER(TRIM(city)) = 'CORONEL MURTA' 
  AND inep_code IS NULL;

-- EE CORONEL MARIANO MURTA (CORONEL MURTA) - INEP: 146650
UPDATE schools 
SET inep_code = '146650' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL MARIANO MURTA' 
  AND UPPER(TRIM(city)) = 'CORONEL MURTA' 
  AND inep_code IS NULL;

-- EE ANTÔNIO MIRANDA (INDAIABIRA) - INEP: 276898
UPDATE schools 
SET inep_code = '276898' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO MIRANDA' 
  AND UPPER(TRIM(city)) = 'INDAIABIRA' 
  AND inep_code IS NULL;

-- EE CHAVES RIBEIRO (ITAOBIM) - INEP: 146889
UPDATE schools 
SET inep_code = '146889' 
WHERE UPPER(TRIM(name)) = 'EE CHAVES RIBEIRO' 
  AND UPPER(TRIM(city)) = 'ITAOBIM' 
  AND inep_code IS NULL;

-- EE DE ITAOBIM (ITAOBIM) - INEP: 146897
UPDATE schools 
SET inep_code = '146897' 
WHERE UPPER(TRIM(name)) = 'EE DE ITAOBIM' 
  AND UPPER(TRIM(city)) = 'ITAOBIM' 
  AND inep_code IS NULL;

-- EE IRMÃOS FERNANDES (ITAOBIM) - INEP: 146901
UPDATE schools 
SET inep_code = '146901' 
WHERE UPPER(TRIM(name)) = 'EE IRMÃOS FERNANDES' 
  AND UPPER(TRIM(city)) = 'ITAOBIM' 
  AND inep_code IS NULL;

-- EE PROFESSORA DEYS LOPES JARDIM (ITAOBIM) - INEP: 310271
UPDATE schools 
SET inep_code = '310271' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA DEYS LOPES JARDIM' 
  AND UPPER(TRIM(city)) = 'ITAOBIM' 
  AND inep_code IS NULL;

-- EE COMENDADOR MURTA (ITINGA) - INEP: 146951
UPDATE schools 
SET inep_code = '146951' 
WHERE UPPER(TRIM(name)) = 'EE COMENDADOR MURTA' 
  AND UPPER(TRIM(city)) = 'ITINGA' 
  AND inep_code IS NULL;

-- EE DE ITINGA (ITINGA) - INEP: 322504
UPDATE schools 
SET inep_code = '322504' 
WHERE UPPER(TRIM(name)) = 'EE DE ITINGA' 
  AND UPPER(TRIM(city)) = 'ITINGA' 
  AND inep_code IS NULL;

-- EE DO POVOADO DE TAQUARAL (ITINGA) - INEP: 146978
UPDATE schools 
SET inep_code = '146978' 
WHERE UPPER(TRIM(name)) = 'EE DO POVOADO DE TAQUARAL' 
  AND UPPER(TRIM(city)) = 'ITINGA' 
  AND inep_code IS NULL;

-- EE MANOEL DA SILVA GUSMÃO (ITINGA) - INEP: 146986
UPDATE schools 
SET inep_code = '146986' 
WHERE UPPER(TRIM(name)) = 'EE MANOEL DA SILVA GUSMÃO' 
  AND UPPER(TRIM(city)) = 'ITINGA' 
  AND inep_code IS NULL;

-- EE ANTÔNIO RAMALHO MOTA (JENIPAPO DE MINAS) - INEP: 330621
UPDATE schools 
SET inep_code = '330621' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO RAMALHO MOTA' 
  AND UPPER(TRIM(city)) = 'JENIPAPO DE MINAS' 
  AND inep_code IS NULL;

-- EE PADRE WILLY (JENIPAPO DE MINAS) - INEP: 330612
UPDATE schools 
SET inep_code = '330612' 
WHERE UPPER(TRIM(name)) = 'EE PADRE WILLY' 
  AND UPPER(TRIM(city)) = 'JENIPAPO DE MINAS' 
  AND inep_code IS NULL;

-- CESEC NANETE ANTUNES GUIMARÃES (MEDINA) - INEP: 311944
UPDATE schools 
SET inep_code = '311944' 
WHERE UPPER(TRIM(name)) = 'CESEC NANETE ANTUNES GUIMARÃES' 
  AND UPPER(TRIM(city)) = 'MEDINA' 
  AND inep_code IS NULL;

-- EE ANÍBAL MELO (MEDINA) - INEP: 185175
UPDATE schools 
SET inep_code = '185175' 
WHERE UPPER(TRIM(name)) = 'EE ANÍBAL MELO' 
  AND UPPER(TRIM(city)) = 'MEDINA' 
  AND inep_code IS NULL;

-- EE DOUTOR MAX MACHADO (MEDINA) - INEP: 185191
UPDATE schools 
SET inep_code = '185191' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR MAX MACHADO' 
  AND UPPER(TRIM(city)) = 'MEDINA' 
  AND inep_code IS NULL;

-- EE JOÃO FRANCISCO COSTA (MEDINA) - INEP: 185183
UPDATE schools 
SET inep_code = '185183' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO FRANCISCO COSTA' 
  AND UPPER(TRIM(city)) = 'MEDINA' 
  AND inep_code IS NULL;

-- EE LUIZ TANURE (MEDINA) - INEP: 185159
UPDATE schools 
SET inep_code = '185159' 
WHERE UPPER(TRIM(name)) = 'EE LUIZ TANURE' 
  AND UPPER(TRIM(city)) = 'MEDINA' 
  AND inep_code IS NULL;

-- EE MONSENHOR MANOEL (MEDINA) - INEP: 185124
UPDATE schools 
SET inep_code = '185124' 
WHERE UPPER(TRIM(name)) = 'EE MONSENHOR MANOEL' 
  AND UPPER(TRIM(city)) = 'MEDINA' 
  AND inep_code IS NULL;

-- EE PROFESSOR QUERUBIM CIRINO DE MATOS (MEDINA) - INEP: 185167
UPDATE schools 
SET inep_code = '185167' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR QUERUBIM CIRINO DE MATOS' 
  AND UPPER(TRIM(city)) = 'MEDINA' 
  AND inep_code IS NULL;

-- EE DAVID FERRAZ DE OLIVEIRA (NINHEIRA) - INEP: 349259
UPDATE schools 
SET inep_code = '349259' 
WHERE UPPER(TRIM(name)) = 'EE DAVID FERRAZ DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'NINHEIRA' 
  AND inep_code IS NULL;

-- EE PROFESSOR MARCIONILO PEREIRA DUTRA (NINHEIRA) - INEP: 338737
UPDATE schools 
SET inep_code = '338737' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR MARCIONILO PEREIRA DUTRA' 
  AND UPPER(TRIM(city)) = 'NINHEIRA' 
  AND inep_code IS NULL;

-- EE DOUTOR OSVALDO PREDILIANO SANT'ANA (SALINAS) - INEP: 218189
UPDATE schools 
SET inep_code = '218189' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR OSVALDO PREDILIANO SANT''ANA' 
  AND UPPER(TRIM(city)) = 'SALINAS' 
  AND inep_code IS NULL;

-- EE VICENTE JOSÉ FERREIRA (SALINAS) - INEP: 342807
UPDATE schools 
SET inep_code = '342807' 
WHERE UPPER(TRIM(name)) = 'EE VICENTE JOSÉ FERREIRA' 
  AND UPPER(TRIM(city)) = 'SALINAS' 
  AND inep_code IS NULL;

-- EE DE ENSINO FUNDAMENTAL E MÉDIO (SANTA CRUZ DE SALINAS) - INEP: 361674
UPDATE schools 
SET inep_code = '361674' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL E MÉDIO' 
  AND UPPER(TRIM(city)) = 'SANTA CRUZ DE SALINAS' 
  AND inep_code IS NULL;

-- EE CATULO CEARENSE (VIRGEM DA LAPA) - INEP: 148474
UPDATE schools 
SET inep_code = '148474' 
WHERE UPPER(TRIM(name)) = 'EE CATULO CEARENSE' 
  AND UPPER(TRIM(city)) = 'VIRGEM DA LAPA' 
  AND inep_code IS NULL;

-- EE NOSSA SENHORA DA LAPA (VIRGEM DA LAPA) - INEP: 148521
UPDATE schools 
SET inep_code = '148521' 
WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DA LAPA' 
  AND UPPER(TRIM(city)) = 'VIRGEM DA LAPA' 
  AND inep_code IS NULL;

-- EE OLEGÁRIO MACIEL (VIRGEM DA LAPA) - INEP: 148482
UPDATE schools 
SET inep_code = '148482' 
WHERE UPPER(TRIM(name)) = 'EE OLEGÁRIO MACIEL' 
  AND UPPER(TRIM(city)) = 'VIRGEM DA LAPA' 
  AND inep_code IS NULL;

-- EE SÃO DOMINGOS (VIRGEM DA LAPA) - INEP: 148491
UPDATE schools 
SET inep_code = '148491' 
WHERE UPPER(TRIM(name)) = 'EE SÃO DOMINGOS' 
  AND UPPER(TRIM(city)) = 'VIRGEM DA LAPA' 
  AND inep_code IS NULL;

-- EE SÃO JOÃO DO VACARIA (VIRGEM DA LAPA) - INEP: 148504
UPDATE schools 
SET inep_code = '148504' 
WHERE UPPER(TRIM(name)) = 'EE SÃO JOÃO DO VACARIA' 
  AND UPPER(TRIM(city)) = 'VIRGEM DA LAPA' 
  AND inep_code IS NULL;

-- EE VALDOMIRO SILVA COSTA (VIRGEM DA LAPA) - INEP: 148512
UPDATE schools 
SET inep_code = '148512' 
WHERE UPPER(TRIM(name)) = 'EE VALDOMIRO SILVA COSTA' 
  AND UPPER(TRIM(city)) = 'VIRGEM DA LAPA' 
  AND inep_code IS NULL;

-- EE LIMA DUARTE (ANTÔNIO CARLOS) - INEP: 239372
UPDATE schools 
SET inep_code = '239372' 
WHERE UPPER(TRIM(name)) = 'EE LIMA DUARTE' 
  AND UPPER(TRIM(city)) = 'ANTÔNIO CARLOS' 
  AND inep_code IS NULL;

-- CENTRO ESTADUAL DE EDUCAÇÃO ESPECIAL MARIA DO ROSÁRIO (BARBACENA) - INEP: 232131
UPDATE schools 
SET inep_code = '232131' 
WHERE UPPER(TRIM(name)) = 'CENTRO ESTADUAL DE EDUCAÇÃO ESPECIAL MARIA DO ROSÁRIO' 
  AND UPPER(TRIM(city)) = 'BARBACENA' 
  AND inep_code IS NULL;

-- EE DE ENSINO FUNDAMENTAL E MÉDIO (BARBACENA) - INEP: 356905
UPDATE schools 
SET inep_code = '356905' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL E MÉDIO' 
  AND UPPER(TRIM(city)) = 'BARBACENA' 
  AND inep_code IS NULL;

-- EE DEPUTADO JOSÉ BONIFÁCIO LAFAYETTE DE ANDRADA (BARBACENA) - INEP: 273376
UPDATE schools 
SET inep_code = '273376' 
WHERE UPPER(TRIM(name)) = 'EE DEPUTADO JOSÉ BONIFÁCIO LAFAYETTE DE ANDRADA' 
  AND UPPER(TRIM(city)) = 'BARBACENA' 
  AND inep_code IS NULL;

-- EE SENHORA DAS DORES (BARBACENA) - INEP: 302627
UPDATE schools 
SET inep_code = '302627' 
WHERE UPPER(TRIM(name)) = 'EE SENHORA DAS DORES' 
  AND UPPER(TRIM(city)) = 'BARBACENA' 
  AND inep_code IS NULL;

-- EE RUBEM ESTEVES RUFFO (OLIVEIRA FORTES) - INEP: 338664
UPDATE schools 
SET inep_code = '338664' 
WHERE UPPER(TRIM(name)) = 'EE RUBEM ESTEVES RUFFO' 
  AND UPPER(TRIM(city)) = 'OLIVEIRA FORTES' 
  AND inep_code IS NULL;

-- EE DOUTOR ANTÔNIO BATISTA DO NASCIMENTO (PIEDADE DO RIO GRANDE) - INEP: 248479
UPDATE schools 
SET inep_code = '248479' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR ANTÔNIO BATISTA DO NASCIMENTO' 
  AND UPPER(TRIM(city)) = 'PIEDADE DO RIO GRANDE' 
  AND inep_code IS NULL;

-- EE PADRE EGYDIO REIS (SENHORA DOS REMÉDIOS) - INEP: 255611
UPDATE schools 
SET inep_code = '255611' 
WHERE UPPER(TRIM(name)) = 'EE PADRE EGYDIO REIS' 
  AND UPPER(TRIM(city)) = 'SENHORA DOS REMÉDIOS' 
  AND inep_code IS NULL;

-- EE PROFESSOR LEONIDES ALVARENGA (AGUANIL) - INEP: 202134
UPDATE schools 
SET inep_code = '202134' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR LEONIDES ALVARENGA' 
  AND UPPER(TRIM(city)) = 'AGUANIL' 
  AND inep_code IS NULL;

-- EE NÉLSON FERNANDES FRIAÇA (CAMACHO) - INEP: 202177
UPDATE schools 
SET inep_code = '202177' 
WHERE UPPER(TRIM(name)) = 'EE NÉLSON FERNANDES FRIAÇA' 
  AND UPPER(TRIM(city)) = 'CAMACHO' 
  AND inep_code IS NULL;

-- CESEC PROFESSOR JOÃO DE OLIVEIRA  BARBOSA (CAMPO BELO) - INEP: 305219
UPDATE schools 
SET inep_code = '305219' 
WHERE UPPER(TRIM(name)) = 'CESEC PROFESSOR JOÃO DE OLIVEIRA BARBOSA' 
  AND UPPER(TRIM(city)) = 'CAMPO BELO' 
  AND inep_code IS NULL;

-- EE ABÍLIO NEVES (CAMPO BELO) - INEP: 202185
UPDATE schools 
SET inep_code = '202185' 
WHERE UPPER(TRIM(name)) = 'EE ABÍLIO NEVES' 
  AND UPPER(TRIM(city)) = 'CAMPO BELO' 
  AND inep_code IS NULL;

-- EE JARBAS GAMBOGI (CAMPO BELO) - INEP: 202304
UPDATE schools 
SET inep_code = '202304' 
WHERE UPPER(TRIM(name)) = 'EE JARBAS GAMBOGI' 
  AND UPPER(TRIM(city)) = 'CAMPO BELO' 
  AND inep_code IS NULL;

-- EE MARIA BAUAB GIBRAM (CAMPO BELO) - INEP: 202355
UPDATE schools 
SET inep_code = '202355' 
WHERE UPPER(TRIM(name)) = 'EE MARIA BAUAB GIBRAM' 
  AND UPPER(TRIM(city)) = 'CAMPO BELO' 
  AND inep_code IS NULL;

-- EE MIGUEL ROGANA (CAMPO BELO) - INEP: 202321
UPDATE schools 
SET inep_code = '202321' 
WHERE UPPER(TRIM(name)) = 'EE MIGUEL ROGANA' 
  AND UPPER(TRIM(city)) = 'CAMPO BELO' 
  AND inep_code IS NULL;

-- EE PADRE ALBERTO FUGER (CAMPO BELO) - INEP: 202193
UPDATE schools 
SET inep_code = '202193' 
WHERE UPPER(TRIM(name)) = 'EE PADRE ALBERTO FUGER' 
  AND UPPER(TRIM(city)) = 'CAMPO BELO' 
  AND inep_code IS NULL;

-- EE PROFESSOR JOSÉ MONTEIRO (CAMPO BELO) - INEP: 202339
UPDATE schools 
SET inep_code = '202339' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOSÉ MONTEIRO' 
  AND UPPER(TRIM(city)) = 'CAMPO BELO' 
  AND inep_code IS NULL;

-- EE DOUTOR JOSÉ ESTEVES DE ANDRADE BOTELHO (CANA VERDE) - INEP: 202401
UPDATE schools 
SET inep_code = '202401' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR JOSÉ ESTEVES DE ANDRADE BOTELHO' 
  AND UPPER(TRIM(city)) = 'CANA VERDE' 
  AND inep_code IS NULL;

-- EE PADRE AMÉRICO (CANDEIAS) - INEP: 202487
UPDATE schools 
SET inep_code = '202487' 
WHERE UPPER(TRIM(name)) = 'EE PADRE AMÉRICO' 
  AND UPPER(TRIM(city)) = 'CANDEIAS' 
  AND inep_code IS NULL;

-- EE PRESIDENTE KENNEDY (CANDEIAS) - INEP: 202495
UPDATE schools 
SET inep_code = '202495' 
WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE KENNEDY' 
  AND UPPER(TRIM(city)) = 'CANDEIAS' 
  AND inep_code IS NULL;

-- EE DOUTOR OSMAR BICALHO (CRISTAIS) - INEP: 202665
UPDATE schools 
SET inep_code = '202665' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR OSMAR BICALHO' 
  AND UPPER(TRIM(city)) = 'CRISTAIS' 
  AND inep_code IS NULL;

-- COLÉGIO TIRADENTES PMMG (LAVRAS) - INEP: 203122
UPDATE schools 
SET inep_code = '203122' 
WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG' 
  AND UPPER(TRIM(city)) = 'LAVRAS' 
  AND inep_code IS NULL;

-- EE AZARIAS RIBEIRO (LAVRAS) - INEP: 202894
UPDATE schools 
SET inep_code = '202894' 
WHERE UPPER(TRIM(name)) = 'EE AZARIAS RIBEIRO' 
  AND UPPER(TRIM(city)) = 'LAVRAS' 
  AND inep_code IS NULL;

-- EE CINIRA CARVALHO (LAVRAS) - INEP: 217743
UPDATE schools 
SET inep_code = '217743' 
WHERE UPPER(TRIM(name)) = 'EE CINIRA CARVALHO' 
  AND UPPER(TRIM(city)) = 'LAVRAS' 
  AND inep_code IS NULL;

-- EE CRISTIANO DE SOUZA (LAVRAS) - INEP: 202908
UPDATE schools 
SET inep_code = '202908' 
WHERE UPPER(TRIM(name)) = 'EE CRISTIANO DE SOUZA' 
  AND UPPER(TRIM(city)) = 'LAVRAS' 
  AND inep_code IS NULL;

-- EE DORA MATARAZZO (LAVRAS) - INEP: 202967
UPDATE schools 
SET inep_code = '202967' 
WHERE UPPER(TRIM(name)) = 'EE DORA MATARAZZO' 
  AND UPPER(TRIM(city)) = 'LAVRAS' 
  AND inep_code IS NULL;

-- EE DOUTOR JOÃO BATISTA HERMETO (LAVRAS) - INEP: 202975
UPDATE schools 
SET inep_code = '202975' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR JOÃO BATISTA HERMETO' 
  AND UPPER(TRIM(city)) = 'LAVRAS' 
  AND inep_code IS NULL;

-- EE FIRMINO COSTA (LAVRAS) - INEP: 203009
UPDATE schools 
SET inep_code = '203009' 
WHERE UPPER(TRIM(name)) = 'EE FIRMINO COSTA' 
  AND UPPER(TRIM(city)) = 'LAVRAS' 
  AND inep_code IS NULL;

-- EE TIRADENTES (LAVRAS) - INEP: 203106
UPDATE schools 
SET inep_code = '203106' 
WHERE UPPER(TRIM(name)) = 'EE TIRADENTES' 
  AND UPPER(TRIM(city)) = 'LAVRAS' 
  AND inep_code IS NULL;

-- EE CARMELITA CARVALHO GARCIA (PERDÕES) - INEP: 203483
UPDATE schools 
SET inep_code = '203483' 
WHERE UPPER(TRIM(name)) = 'EE CARMELITA CARVALHO GARCIA' 
  AND UPPER(TRIM(city)) = 'PERDÕES' 
  AND inep_code IS NULL;

-- EE ELVIRA LOPES RESENDE (PERDÕES) - INEP: 203491
UPDATE schools 
SET inep_code = '203491' 
WHERE UPPER(TRIM(name)) = 'EE ELVIRA LOPES RESENDE' 
  AND UPPER(TRIM(city)) = 'PERDÕES' 
  AND inep_code IS NULL;

-- EE JOÃO MELO GOMIDE (PERDÕES) - INEP: 203441
UPDATE schools 
SET inep_code = '203441' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO MELO GOMIDE' 
  AND UPPER(TRIM(city)) = 'PERDÕES' 
  AND inep_code IS NULL;

-- EE PROFESSOR GETÚLIO JOSÉ SOARES (PERDÕES) - INEP: 203475
UPDATE schools 
SET inep_code = '203475' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR GETÚLIO JOSÉ SOARES' 
  AND UPPER(TRIM(city)) = 'PERDÕES' 
  AND inep_code IS NULL;

-- EE ANTÔNIO NOVAIS (RIBEIRÃO VERMELHO) - INEP: 203521
UPDATE schools 
SET inep_code = '203521' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO NOVAIS' 
  AND UPPER(TRIM(city)) = 'RIBEIRÃO VERMELHO' 
  AND inep_code IS NULL;

-- EE CARMELITA CARVALHO GARCIA (SANTANA DO JACARÉ) - INEP: 203530
UPDATE schools 
SET inep_code = '203530' 
WHERE UPPER(TRIM(name)) = 'EE CARMELITA CARVALHO GARCIA' 
  AND UPPER(TRIM(city)) = 'SANTANA DO JACARÉ' 
  AND inep_code IS NULL;

-- EE ALBERICO FERREIRA NAVES (SANTO ANTÔNIO DO AMPARO) - INEP: 134473
UPDATE schools 
SET inep_code = '134473' 
WHERE UPPER(TRIM(name)) = 'EE ALBERICO FERREIRA NAVES' 
  AND UPPER(TRIM(city)) = 'SANTO ANTÔNIO DO AMPARO' 
  AND inep_code IS NULL;

-- EE DOUTOR CÍCERO FERREIRA (SANTO ANTÔNIO DO AMPARO) - INEP: 134490
UPDATE schools 
SET inep_code = '134490' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR CÍCERO FERREIRA' 
  AND UPPER(TRIM(city)) = 'SANTO ANTÔNIO DO AMPARO' 
  AND inep_code IS NULL;

-- EE NEWTON FERREIRA DE PAIVA (SANTO ANTÔNIO DO AMPARO) - INEP: 134511
UPDATE schools 
SET inep_code = '134511' 
WHERE UPPER(TRIM(name)) = 'EE NEWTON FERREIRA DE PAIVA' 
  AND UPPER(TRIM(city)) = 'SANTO ANTÔNIO DO AMPARO' 
  AND inep_code IS NULL;

-- EE CORONEL MÁRIO CAMPOS (SÃO FRANCISCO DE PAULA) - INEP: 203564
UPDATE schools 
SET inep_code = '203564' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL MÁRIO CAMPOS' 
  AND UPPER(TRIM(city)) = 'SÃO FRANCISCO DE PAULA' 
  AND inep_code IS NULL;

-- EE MARIA ROSA DE FREITAS (FERVEDOURO) - INEP: 351148
UPDATE schools 
SET inep_code = '351148' 
WHERE UPPER(TRIM(name)) = 'EE MARIA ROSA DE FREITAS' 
  AND UPPER(TRIM(city)) = 'FERVEDOURO' 
  AND inep_code IS NULL;

-- EE MARIA CONCEIÇÃO GONÇALVES CARRARA (PEDRA DOURADA) - INEP: 322652
UPDATE schools 
SET inep_code = '322652' 
WHERE UPPER(TRIM(name)) = 'EE MARIA CONCEIÇÃO GONÇALVES CARRARA' 
  AND UPPER(TRIM(city)) = 'PEDRA DOURADA' 
  AND inep_code IS NULL;

-- EE JOÃO PAULO II (BOM JESUS DO GALHO) - INEP: 213314
UPDATE schools 
SET inep_code = '213314' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO PAULO II' 
  AND UPPER(TRIM(city)) = 'BOM JESUS DO GALHO' 
  AND inep_code IS NULL;

-- EE FELICIANO MIGUEL ABDALLA (CARATINGA) - INEP: 353450
UPDATE schools 
SET inep_code = '353450' 
WHERE UPPER(TRIM(name)) = 'EE FELICIANO MIGUEL ABDALLA' 
  AND UPPER(TRIM(city)) = 'CARATINGA' 
  AND inep_code IS NULL;

-- EE MOACYR DE MATTOS (CARATINGA) - INEP: 253855
UPDATE schools 
SET inep_code = '253855' 
WHERE UPPER(TRIM(name)) = 'EE MOACYR DE MATTOS' 
  AND UPPER(TRIM(city)) = 'CARATINGA' 
  AND inep_code IS NULL;

-- EE PROFESSOR JOAQUIM NUNES (CARATINGA) - INEP: 218766
UPDATE schools 
SET inep_code = '218766' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOAQUIM NUNES' 
  AND UPPER(TRIM(city)) = 'CARATINGA' 
  AND inep_code IS NULL;

-- EE DÊNIO MOREIRA DE CARVALHO (IPABA) - INEP: 268879
UPDATE schools 
SET inep_code = '268879' 
WHERE UPPER(TRIM(name)) = 'EE DÊNIO MOREIRA DE CARVALHO' 
  AND UPPER(TRIM(city)) = 'IPABA' 
  AND inep_code IS NULL;

-- CESEC MARIA CECÍLIA DE MOURA (IPANEMA) - INEP: 310581
UPDATE schools 
SET inep_code = '310581' 
WHERE UPPER(TRIM(name)) = 'CESEC MARIA CECÍLIA DE MOURA' 
  AND UPPER(TRIM(city)) = 'IPANEMA' 
  AND inep_code IS NULL;

-- EE PROFESSORA DINALVA MARIA DE SOUZA (PINGO-D'ÁGUA) - INEP: 213306
UPDATE schools 
SET inep_code = '213306' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA DINALVA MARIA DE SOUZA' 
  AND UPPER(TRIM(city)) = 'PINGO-D''ÁGUA' 
  AND inep_code IS NULL;

-- EE CONSELHEIRO FIDÉLIS (AIURUOCA) - INEP: 170682
UPDATE schools 
SET inep_code = '170682' 
WHERE UPPER(TRIM(name)) = 'EE CONSELHEIRO FIDÉLIS' 
  AND UPPER(TRIM(city)) = 'AIURUOCA' 
  AND inep_code IS NULL;

-- EE MARIA DO CARMO LIMA PINTO (ALAGOA) - INEP: 276464
UPDATE schools 
SET inep_code = '276464' 
WHERE UPPER(TRIM(name)) = 'EE MARIA DO CARMO LIMA PINTO' 
  AND UPPER(TRIM(city)) = 'ALAGOA' 
  AND inep_code IS NULL;

-- EE ANÍSIO ESAÚ DOS SANTOS (BAEPENDI) - INEP: 171026
UPDATE schools 
SET inep_code = '171026' 
WHERE UPPER(TRIM(name)) = 'EE ANÍSIO ESAÚ DOS SANTOS' 
  AND UPPER(TRIM(city)) = 'BAEPENDI' 
  AND inep_code IS NULL;

-- EE JOAQUIM ALVARENGA MACIEL (BAEPENDI) - INEP: 170984
UPDATE schools 
SET inep_code = '170984' 
WHERE UPPER(TRIM(name)) = 'EE JOAQUIM ALVARENGA MACIEL' 
  AND UPPER(TRIM(city)) = 'BAEPENDI' 
  AND inep_code IS NULL;

-- EE NOSSA SENHORA DE MONTSERRAT (BAEPENDI) - INEP: 171042
UPDATE schools 
SET inep_code = '171042' 
WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DE MONTSERRAT' 
  AND UPPER(TRIM(city)) = 'BAEPENDI' 
  AND inep_code IS NULL;

-- EE VARGEM DA LAGE (BAEPENDI) - INEP: 171051
UPDATE schools 
SET inep_code = '171051' 
WHERE UPPER(TRIM(name)) = 'EE VARGEM DA LAGE' 
  AND UPPER(TRIM(city)) = 'BAEPENDI' 
  AND inep_code IS NULL;

-- EE CÔNEGO JOÃO SEVERO (BOCAINA DE MINAS) - INEP: 294667
UPDATE schools 
SET inep_code = '294667' 
WHERE UPPER(TRIM(name)) = 'EE CÔNEGO JOÃO SEVERO' 
  AND UPPER(TRIM(city)) = 'BOCAINA DE MINAS' 
  AND inep_code IS NULL;

-- CEP-CENTRO DE EDUCAÇÃO PROFISSIONAL DE CAXAMBU (CAXAMBU) - INEP: 344656
UPDATE schools 
SET inep_code = '344656' 
WHERE UPPER(TRIM(name)) = 'CEP-CENTRO DE EDUCAÇÃO PROFISSIONAL DE CAXAMBU' 
  AND UPPER(TRIM(city)) = 'CAXAMBU' 
  AND inep_code IS NULL;

-- EE CABO LUIZ DE QUEIROZ (CAXAMBU) - INEP: 311880
UPDATE schools 
SET inep_code = '311880' 
WHERE UPPER(TRIM(name)) = 'EE CABO LUIZ DE QUEIROZ' 
  AND UPPER(TRIM(city)) = 'CAXAMBU' 
  AND inep_code IS NULL;

-- EE DOMINGOS GONÇALVES DE MELLO MINGOTE (CAXAMBU) - INEP: 172073
UPDATE schools 
SET inep_code = '172073' 
WHERE UPPER(TRIM(name)) = 'EE DOMINGOS GONÇALVES DE MELLO MINGOTE' 
  AND UPPER(TRIM(city)) = 'CAXAMBU' 
  AND inep_code IS NULL;

-- EE RUTH MARTINS DE ALMEIDA (CAXAMBU) - INEP: 172081
UPDATE schools 
SET inep_code = '172081' 
WHERE UPPER(TRIM(name)) = 'EE RUTH MARTINS DE ALMEIDA' 
  AND UPPER(TRIM(city)) = 'CAXAMBU' 
  AND inep_code IS NULL;

-- EE DOM OTHON MOTTA (CONCEIÇÃO DO RIO VERDE) - INEP: 172146
UPDATE schools 
SET inep_code = '172146' 
WHERE UPPER(TRIM(name)) = 'EE DOM OTHON MOTTA' 
  AND UPPER(TRIM(city)) = 'CONCEIÇÃO DO RIO VERDE' 
  AND inep_code IS NULL;

-- EE PADRE PEDRO RIBEIRO DE CASTRO (CONCEIÇÃO DO RIO VERDE) - INEP: 172120
UPDATE schools 
SET inep_code = '172120' 
WHERE UPPER(TRIM(name)) = 'EE PADRE PEDRO RIBEIRO DE CASTRO' 
  AND UPPER(TRIM(city)) = 'CONCEIÇÃO DO RIO VERDE' 
  AND inep_code IS NULL;

-- EE DONA LEONINA NUNES MACIEL (CRUZÍLIA) - INEP: 172448
UPDATE schools 
SET inep_code = '172448' 
WHERE UPPER(TRIM(name)) = 'EE DONA LEONINA NUNES MACIEL' 
  AND UPPER(TRIM(city)) = 'CRUZÍLIA' 
  AND inep_code IS NULL;

-- EE MONSENHOR JOÃO CÂNCIO (CRUZÍLIA) - INEP: 172456
UPDATE schools 
SET inep_code = '172456' 
WHERE UPPER(TRIM(name)) = 'EE MONSENHOR JOÃO CÂNCIO' 
  AND UPPER(TRIM(city)) = 'CRUZÍLIA' 
  AND inep_code IS NULL;

-- EE SÃO SEBASTIÃO (CRUZÍLIA) - INEP: 172464
UPDATE schools 
SET inep_code = '172464' 
WHERE UPPER(TRIM(name)) = 'EE SÃO SEBASTIÃO' 
  AND UPPER(TRIM(city)) = 'CRUZÍLIA' 
  AND inep_code IS NULL;

-- EE NILO PEÇANHA (ITAMONTE) - INEP: 172847
UPDATE schools 
SET inep_code = '172847' 
WHERE UPPER(TRIM(name)) = 'EE NILO PEÇANHA' 
  AND UPPER(TRIM(city)) = 'ITAMONTE' 
  AND inep_code IS NULL;

-- EE DONA SEMIANA (ITANHANDU) - INEP: 172910
UPDATE schools 
SET inep_code = '172910' 
WHERE UPPER(TRIM(name)) = 'EE DONA SEMIANA' 
  AND UPPER(TRIM(city)) = 'ITANHANDU' 
  AND inep_code IS NULL;

-- EE PROFESSOR SOUZA NILO (ITANHANDU) - INEP: 172936
UPDATE schools 
SET inep_code = '172936' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR SOUZA NILO' 
  AND UPPER(TRIM(city)) = 'ITANHANDU' 
  AND inep_code IS NULL;

-- EE JOÃO DE ALMEIDA LISBOA (JESUÂNIA) - INEP: 172961
UPDATE schools 
SET inep_code = '172961' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO DE ALMEIDA LISBOA' 
  AND UPPER(TRIM(city)) = 'JESUÂNIA' 
  AND inep_code IS NULL;

-- EE PROFESSORA MARIA ANTONIETA ROMANO SALGADO (OLÍMPIO NORONHA) - INEP: 173487
UPDATE schools 
SET inep_code = '173487' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA ANTONIETA ROMANO SALGADO' 
  AND UPPER(TRIM(city)) = 'OLÍMPIO NORONHA' 
  AND inep_code IS NULL;

-- EE CORONEL ARTUR TIBÚRCIO (PASSA QUATRO) - INEP: 173673
UPDATE schools 
SET inep_code = '173673' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL ARTUR TIBÚRCIO' 
  AND UPPER(TRIM(city)) = 'PASSA QUATRO' 
  AND inep_code IS NULL;

-- EE NOSSA SENHORA APARECIDA (PASSA QUATRO) - INEP: 173762
UPDATE schools 
SET inep_code = '173762' 
WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA APARECIDA' 
  AND UPPER(TRIM(city)) = 'PASSA QUATRO' 
  AND inep_code IS NULL;

-- EE PRESIDENTE ROOSEVELT (PASSA QUATRO) - INEP: 173789
UPDATE schools 
SET inep_code = '173789' 
WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE ROOSEVELT' 
  AND UPPER(TRIM(city)) = 'PASSA QUATRO' 
  AND inep_code IS NULL;

-- EE PROFESSORA LOURDES CASTILHO FREITAS (PASSA QUATRO) - INEP: 173665
UPDATE schools 
SET inep_code = '173665' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA LOURDES CASTILHO FREITAS' 
  AND UPPER(TRIM(city)) = 'PASSA QUATRO' 
  AND inep_code IS NULL;

-- EE FELIZARDA RUSSANO (POUSO ALTO) - INEP: 173916
UPDATE schools 
SET inep_code = '173916' 
WHERE UPPER(TRIM(name)) = 'EE FELIZARDA RUSSANO' 
  AND UPPER(TRIM(city)) = 'POUSO ALTO' 
  AND inep_code IS NULL;

-- CESEC PROFESSORA NOÊMIA GOULART FERREIRA (SÃO LOURENÇO) - INEP: 174203
UPDATE schools 
SET inep_code = '174203' 
WHERE UPPER(TRIM(name)) = 'CESEC PROFESSORA NOÊMIA GOULART FERREIRA' 
  AND UPPER(TRIM(city)) = 'SÃO LOURENÇO' 
  AND inep_code IS NULL;

-- EE DOUTOR HUMBERTO SANCHES (SÃO LOURENÇO) - INEP: 174149
UPDATE schools 
SET inep_code = '174149' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR HUMBERTO SANCHES' 
  AND UPPER(TRIM(city)) = 'SÃO LOURENÇO' 
  AND inep_code IS NULL;

-- EE EURÍPEDES PRAZERES (SÃO LOURENÇO) - INEP: 174157
UPDATE schools 
SET inep_code = '174157' 
WHERE UPPER(TRIM(name)) = 'EE EURÍPEDES PRAZERES' 
  AND UPPER(TRIM(city)) = 'SÃO LOURENÇO' 
  AND inep_code IS NULL;

-- EE PROFESSOR ANTÔNIO MAGALHÃES ALVES (SÃO LOURENÇO) - INEP: 174190
UPDATE schools 
SET inep_code = '174190' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ANTÔNIO MAGALHÃES ALVES' 
  AND UPPER(TRIM(city)) = 'SÃO LOURENÇO' 
  AND inep_code IS NULL;

-- EE PROFESSOR MÁRIO JUNQUEIRA FERRAZ (SÃO LOURENÇO) - INEP: 174181
UPDATE schools 
SET inep_code = '174181' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR MÁRIO JUNQUEIRA FERRAZ' 
  AND UPPER(TRIM(city)) = 'SÃO LOURENÇO' 
  AND inep_code IS NULL;

-- EE PROFESSOR TÚLIO BENTO (SÃO LOURENÇO) - INEP: 356832
UPDATE schools 
SET inep_code = '356832' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR TÚLIO BENTO' 
  AND UPPER(TRIM(city)) = 'SÃO LOURENÇO' 
  AND inep_code IS NULL;

-- EE SÃO FRANCISCO DE ASSIS (SÃO LOURENÇO) - INEP: 338710
UPDATE schools 
SET inep_code = '338710' 
WHERE UPPER(TRIM(name)) = 'EE SÃO FRANCISCO DE ASSIS' 
  AND UPPER(TRIM(city)) = 'SÃO LOURENÇO' 
  AND inep_code IS NULL;

-- EE JOSÉ RIBEIRO MIRA (SÃO SEBASTIÃO DO RIO VERDE) - INEP: 330744
UPDATE schools 
SET inep_code = '330744' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ RIBEIRO MIRA' 
  AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO RIO VERDE' 
  AND inep_code IS NULL;

-- EE DO SOBRADINHO (SÃO THOMÉ DAS LETRAS) - INEP: 174220
UPDATE schools 
SET inep_code = '174220' 
WHERE UPPER(TRIM(name)) = 'EE DO SOBRADINHO' 
  AND UPPER(TRIM(city)) = 'SÃO THOMÉ DAS LETRAS' 
  AND inep_code IS NULL;

-- EE JOSÉ CRISTIANO ALVES (SÃO THOMÉ DAS LETRAS) - INEP: 174246
UPDATE schools 
SET inep_code = '174246' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ CRISTIANO ALVES' 
  AND UPPER(TRIM(city)) = 'SÃO THOMÉ DAS LETRAS' 
  AND inep_code IS NULL;

-- EE MINISTRO CLÓVIS SALGADO (SERITINGA) - INEP: 174289
UPDATE schools 
SET inep_code = '174289' 
WHERE UPPER(TRIM(name)) = 'EE MINISTRO CLÓVIS SALGADO' 
  AND UPPER(TRIM(city)) = 'SERITINGA' 
  AND inep_code IS NULL;

-- EE NOSSA SENHORA DO BONSUCESSO (SERRANOS) - INEP: 305260
UPDATE schools 
SET inep_code = '305260' 
WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DO BONSUCESSO' 
  AND UPPER(TRIM(city)) = 'SERRANOS' 
  AND inep_code IS NULL;

-- EE DONA MARIANA CARVALHAL COSTA (SOLEDADE DE MINAS) - INEP: 174319
UPDATE schools 
SET inep_code = '174319' 
WHERE UPPER(TRIM(name)) = 'EE DONA MARIANA CARVALHAL COSTA' 
  AND UPPER(TRIM(city)) = 'SOLEDADE DE MINAS' 
  AND inep_code IS NULL;

-- EE SILVESTRE NUNES (CASA GRANDE) - INEP: 193348
UPDATE schools 
SET inep_code = '193348' 
WHERE UPPER(TRIM(name)) = 'EE SILVESTRE NUNES' 
  AND UPPER(TRIM(city)) = 'CASA GRANDE' 
  AND inep_code IS NULL;

-- EE GUSTAVO AUGUSTO DA SILVA (CATAS ALTAS DA NORUEGA) - INEP: 193356
UPDATE schools 
SET inep_code = '193356' 
WHERE UPPER(TRIM(name)) = 'EE GUSTAVO AUGUSTO DA SILVA' 
  AND UPPER(TRIM(city)) = 'CATAS ALTAS DA NORUEGA' 
  AND inep_code IS NULL;

-- EE BARÃO DE PARAOPEBA (CONGONHAS) - INEP: 193399
UPDATE schools 
SET inep_code = '193399' 
WHERE UPPER(TRIM(name)) = 'EE BARÃO DE PARAOPEBA' 
  AND UPPER(TRIM(city)) = 'CONGONHAS' 
  AND inep_code IS NULL;

-- EE FELICIANO MENDES (CONGONHAS) - INEP: 193429
UPDATE schools 
SET inep_code = '193429' 
WHERE UPPER(TRIM(name)) = 'EE FELICIANO MENDES' 
  AND UPPER(TRIM(city)) = 'CONGONHAS' 
  AND inep_code IS NULL;

-- EE LAMARTINE DE FREITAS (CONGONHAS) - INEP: 193453
UPDATE schools 
SET inep_code = '193453' 
WHERE UPPER(TRIM(name)) = 'EE LAMARTINE DE FREITAS' 
  AND UPPER(TRIM(city)) = 'CONGONHAS' 
  AND inep_code IS NULL;

-- CESEC PROFESSOR JOSÉ MARTINS SOBRINHO (CONSELHEIRO LAFAIETE) - INEP: 193704
UPDATE schools 
SET inep_code = '193704' 
WHERE UPPER(TRIM(name)) = 'CESEC PROFESSOR JOSÉ MARTINS SOBRINHO' 
  AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' 
  AND inep_code IS NULL;

-- EE AUGUSTO JOSÉ VIEIRA (CONSELHEIRO LAFAIETE) - INEP: 193551
UPDATE schools 
SET inep_code = '193551' 
WHERE UPPER(TRIM(name)) = 'EE AUGUSTO JOSÉ VIEIRA' 
  AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' 
  AND inep_code IS NULL;

-- EE DOMINGOS BEBIANO (CONSELHEIRO LAFAIETE) - INEP: 193577
UPDATE schools 
SET inep_code = '193577' 
WHERE UPPER(TRIM(name)) = 'EE DOMINGOS BEBIANO' 
  AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' 
  AND inep_code IS NULL;

-- EE DOUTOR ANTERO CHAVES (CONSELHEIRO LAFAIETE) - INEP: 193593
UPDATE schools 
SET inep_code = '193593' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR ANTERO CHAVES' 
  AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' 
  AND inep_code IS NULL;

-- EE DOUTOR ANTONIO NOGUEIRA DE REZENDE (CONSELHEIRO LAFAIETE) - INEP: 193801
UPDATE schools 
SET inep_code = '193801' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR ANTONIO NOGUEIRA DE REZENDE' 
  AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' 
  AND inep_code IS NULL;

-- EE GENERAL OSWALDO PINTO DA VEIGA (CONSELHEIRO LAFAIETE) - INEP: 193615
UPDATE schools 
SET inep_code = '193615' 
WHERE UPPER(TRIM(name)) = 'EE GENERAL OSWALDO PINTO DA VEIGA' 
  AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' 
  AND inep_code IS NULL;

-- EE GENERAL SYLVIO RAULINO DE OLIVEIRA (CONSELHEIRO LAFAIETE) - INEP: 193631
UPDATE schools 
SET inep_code = '193631' 
WHERE UPPER(TRIM(name)) = 'EE GENERAL SYLVIO RAULINO DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' 
  AND inep_code IS NULL;

-- EE GERALDO BITTENCOURT (CONSELHEIRO LAFAIETE) - INEP: 193658
UPDATE schools 
SET inep_code = '193658' 
WHERE UPPER(TRIM(name)) = 'EE GERALDO BITTENCOURT' 
  AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' 
  AND inep_code IS NULL;

-- EE ISAURA FERREIRA (CONSELHEIRO LAFAIETE) - INEP: 193691
UPDATE schools 
SET inep_code = '193691' 
WHERE UPPER(TRIM(name)) = 'EE ISAURA FERREIRA' 
  AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' 
  AND inep_code IS NULL;

-- EE LOPES FRANCO (CONSELHEIRO LAFAIETE) - INEP: 193747
UPDATE schools 
SET inep_code = '193747' 
WHERE UPPER(TRIM(name)) = 'EE LOPES FRANCO' 
  AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' 
  AND inep_code IS NULL;

-- EE LUIZ DE MELLO VIANNA SOBRINHO (CONSELHEIRO LAFAIETE) - INEP: 193755
UPDATE schools 
SET inep_code = '193755' 
WHERE UPPER(TRIM(name)) = 'EE LUIZ DE MELLO VIANNA SOBRINHO' 
  AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' 
  AND inep_code IS NULL;

-- EE MARECHAL HUMBERTO DE ALENCAR CASTELLO BRANCO (CONSELHEIRO LAFAIETE) - INEP: 193763
UPDATE schools 
SET inep_code = '193763' 
WHERE UPPER(TRIM(name)) = 'EE MARECHAL HUMBERTO DE ALENCAR CASTELLO BRANCO' 
  AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' 
  AND inep_code IS NULL;

-- EE MOACIR DE SOUZA DIAS (CONSELHEIRO LAFAIETE) - INEP: 219037
UPDATE schools 
SET inep_code = '219037' 
WHERE UPPER(TRIM(name)) = 'EE MOACIR DE SOUZA DIAS' 
  AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' 
  AND inep_code IS NULL;

-- EE MONSENHOR ANTÔNIO JOSÉ FERREIRA (CONSELHEIRO LAFAIETE) - INEP: 193682
UPDATE schools 
SET inep_code = '193682' 
WHERE UPPER(TRIM(name)) = 'EE MONSENHOR ANTÔNIO JOSÉ FERREIRA' 
  AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' 
  AND inep_code IS NULL;

-- EE MONSENHOR HORTA (CONSELHEIRO LAFAIETE) - INEP: 193666
UPDATE schools 
SET inep_code = '193666' 
WHERE UPPER(TRIM(name)) = 'EE MONSENHOR HORTA' 
  AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' 
  AND inep_code IS NULL;

-- EE NARCISO DE QUEIRÓS (CONSELHEIRO LAFAIETE) - INEP: 193771
UPDATE schools 
SET inep_code = '193771' 
WHERE UPPER(TRIM(name)) = 'EE NARCISO DE QUEIRÓS' 
  AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' 
  AND inep_code IS NULL;

-- EE PACÍFICO VIEIRA (CONSELHEIRO LAFAIETE) - INEP: 193780
UPDATE schools 
SET inep_code = '193780' 
WHERE UPPER(TRIM(name)) = 'EE PACÍFICO VIEIRA' 
  AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' 
  AND inep_code IS NULL;

-- EE PROFESSOR ASTOR VIANNA (CONSELHEIRO LAFAIETE) - INEP: 193542
UPDATE schools 
SET inep_code = '193542' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ASTOR VIANNA' 
  AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' 
  AND inep_code IS NULL;

-- EE QUEIROZ JÚNIOR (CONSELHEIRO LAFAIETE) - INEP: 193585
UPDATE schools 
SET inep_code = '193585' 
WHERE UPPER(TRIM(name)) = 'EE QUEIROZ JÚNIOR' 
  AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' 
  AND inep_code IS NULL;

-- EE CORONEL ALCIDES DUTRA (CRISTIANO OTONI) - INEP: 193828
UPDATE schools 
SET inep_code = '193828' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL ALCIDES DUTRA' 
  AND UPPER(TRIM(city)) = 'CRISTIANO OTONI' 
  AND inep_code IS NULL;

-- EE CARMELA DUTRA (DESTERRO DE ENTRE RIOS) - INEP: 193879
UPDATE schools 
SET inep_code = '193879' 
WHERE UPPER(TRIM(name)) = 'EE CARMELA DUTRA' 
  AND UPPER(TRIM(city)) = 'DESTERRO DE ENTRE RIOS' 
  AND inep_code IS NULL;

-- EE EVARISTO AUGUSTO DE OLIVEIRA (DESTERRO DE ENTRE RIOS) - INEP: 193895
UPDATE schools 
SET inep_code = '193895' 
WHERE UPPER(TRIM(name)) = 'EE EVARISTO AUGUSTO DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'DESTERRO DE ENTRE RIOS' 
  AND inep_code IS NULL;

-- EE NOSSA SENHORA DE FÁTIMA (DESTERRO DE ENTRE RIOS) - INEP: 193852
UPDATE schools 
SET inep_code = '193852' 
WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DE FÁTIMA' 
  AND UPPER(TRIM(city)) = 'DESTERRO DE ENTRE RIOS' 
  AND inep_code IS NULL;

-- EE DOM RODOLFO (ENTRE RIOS DE MINAS) - INEP: 218383
UPDATE schools 
SET inep_code = '218383' 
WHERE UPPER(TRIM(name)) = 'EE DOM RODOLFO' 
  AND UPPER(TRIM(city)) = 'ENTRE RIOS DE MINAS' 
  AND inep_code IS NULL;

-- EE EXPEDICIONÁRIO GERALDO BAETA (ENTRE RIOS DE MINAS) - INEP: 193925
UPDATE schools 
SET inep_code = '193925' 
WHERE UPPER(TRIM(name)) = 'EE EXPEDICIONÁRIO GERALDO BAETA' 
  AND UPPER(TRIM(city)) = 'ENTRE RIOS DE MINAS' 
  AND inep_code IS NULL;

-- EE PEDRO DOMINGUES (ENTRE RIOS DE MINAS) - INEP: 193950
UPDATE schools 
SET inep_code = '193950' 
WHERE UPPER(TRIM(name)) = 'EE PEDRO DOMINGUES' 
  AND UPPER(TRIM(city)) = 'ENTRE RIOS DE MINAS' 
  AND inep_code IS NULL;

-- EE RIBEIRO DE OLIVEIRA (ENTRE RIOS DE MINAS) - INEP: 193968
UPDATE schools 
SET inep_code = '193968' 
WHERE UPPER(TRIM(name)) = 'EE RIBEIRO DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'ENTRE RIOS DE MINAS' 
  AND inep_code IS NULL;

-- EE CONSELHEIRO ANTÃO (ITAVERAVA) - INEP: 193992
UPDATE schools 
SET inep_code = '193992' 
WHERE UPPER(TRIM(name)) = 'EE CONSELHEIRO ANTÃO' 
  AND UPPER(TRIM(city)) = 'ITAVERAVA' 
  AND inep_code IS NULL;

-- EE PROFESSORA NOEMI NOGUEIRA (ITAVERAVA) - INEP: 194000
UPDATE schools 
SET inep_code = '194000' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA NOEMI NOGUEIRA' 
  AND UPPER(TRIM(city)) = 'ITAVERAVA' 
  AND inep_code IS NULL;

-- EE SANTOS REIS (JECEABA) - INEP: 194042
UPDATE schools 
SET inep_code = '194042' 
WHERE UPPER(TRIM(name)) = 'EE SANTOS REIS' 
  AND UPPER(TRIM(city)) = 'JECEABA' 
  AND inep_code IS NULL;

-- EE NAPOLEÃO REIS (LAMIM) - INEP: 194107
UPDATE schools 
SET inep_code = '194107' 
WHERE UPPER(TRIM(name)) = 'EE NAPOLEÃO REIS' 
  AND UPPER(TRIM(city)) = 'LAMIM' 
  AND inep_code IS NULL;

-- CESEC JOSÉ BRÁS DOS REIS (OURO BRANCO) - INEP: 194131
UPDATE schools 
SET inep_code = '194131' 
WHERE UPPER(TRIM(name)) = 'CESEC JOSÉ BRÁS DOS REIS' 
  AND UPPER(TRIM(city)) = 'OURO BRANCO' 
  AND inep_code IS NULL;

-- EE CÔNEGO LUIZ VIEIRA DA SILVA (OURO BRANCO) - INEP: 194123
UPDATE schools 
SET inep_code = '194123' 
WHERE UPPER(TRIM(name)) = 'EE CÔNEGO LUIZ VIEIRA DA SILVA' 
  AND UPPER(TRIM(city)) = 'OURO BRANCO' 
  AND inep_code IS NULL;

-- EE DE EDUCAÇÃO ESPECIAL PROFESSORA MARIA CORRÊA COUTINHO (OURO BRANCO) - INEP: 222208
UPDATE schools 
SET inep_code = '222208' 
WHERE UPPER(TRIM(name)) = 'EE DE EDUCAÇÃO ESPECIAL PROFESSORA MARIA CORRÊA COUTINHO' 
  AND UPPER(TRIM(city)) = 'OURO BRANCO' 
  AND inep_code IS NULL;

-- EE IRACEMA DE ALMEIDA (OURO BRANCO) - INEP: 194158
UPDATE schools 
SET inep_code = '194158' 
WHERE UPPER(TRIM(name)) = 'EE IRACEMA DE ALMEIDA' 
  AND UPPER(TRIM(city)) = 'OURO BRANCO' 
  AND inep_code IS NULL;

-- EE LEVINDO COSTA CARVALHO (OURO BRANCO) - INEP: 194182
UPDATE schools 
SET inep_code = '194182' 
WHERE UPPER(TRIM(name)) = 'EE LEVINDO COSTA CARVALHO' 
  AND UPPER(TRIM(city)) = 'OURO BRANCO' 
  AND inep_code IS NULL;

-- EE ANTÔNIO DE PAULA DIAS (PIRANGA) - INEP: 194298
UPDATE schools 
SET inep_code = '194298' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO DE PAULA DIAS' 
  AND UPPER(TRIM(city)) = 'PIRANGA' 
  AND inep_code IS NULL;

-- EE CORONEL AMANTINO MACIEL (PIRANGA) - INEP: 194191
UPDATE schools 
SET inep_code = '194191' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL AMANTINO MACIEL' 
  AND UPPER(TRIM(city)) = 'PIRANGA' 
  AND inep_code IS NULL;

-- EE CORONEL JOSÉ ILDEFONSO (PIRANGA) - INEP: 194204
UPDATE schools 
SET inep_code = '194204' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL JOSÉ ILDEFONSO' 
  AND UPPER(TRIM(city)) = 'PIRANGA' 
  AND inep_code IS NULL;

-- EE FRANCISCO FERREIRA MACIEL (PIRANGA) - INEP: 194263
UPDATE schools 
SET inep_code = '194263' 
WHERE UPPER(TRIM(name)) = 'EE FRANCISCO FERREIRA MACIEL' 
  AND UPPER(TRIM(city)) = 'PIRANGA' 
  AND inep_code IS NULL;

-- EE FRANCISCO SALES FERREIRA (PIRANGA) - INEP: 194255
UPDATE schools 
SET inep_code = '194255' 
WHERE UPPER(TRIM(name)) = 'EE FRANCISCO SALES FERREIRA' 
  AND UPPER(TRIM(city)) = 'PIRANGA' 
  AND inep_code IS NULL;

-- EE SANTO AMARO (QUELUZITO) - INEP: 194328
UPDATE schools 
SET inep_code = '194328' 
WHERE UPPER(TRIM(name)) = 'EE SANTO AMARO' 
  AND UPPER(TRIM(city)) = 'QUELUZITO' 
  AND inep_code IS NULL;

-- EE MAJOR MIRANDA (RIO ESPERA) - INEP: 194336
UPDATE schools 
SET inep_code = '194336' 
WHERE UPPER(TRIM(name)) = 'EE MAJOR MIRANDA' 
  AND UPPER(TRIM(city)) = 'RIO ESPERA' 
  AND inep_code IS NULL;

-- EE MONSENHOR FRANCISCO MIGUEL FERNANDES (RIO ESPERA) - INEP: 196347
UPDATE schools 
SET inep_code = '196347' 
WHERE UPPER(TRIM(name)) = 'EE MONSENHOR FRANCISCO MIGUEL FERNANDES' 
  AND UPPER(TRIM(city)) = 'RIO ESPERA' 
  AND inep_code IS NULL;

-- EE DR JOÃO NOGUEIRA DE ALMEIDA (SANTANA DOS MONTES) - INEP: 194395
UPDATE schools 
SET inep_code = '194395' 
WHERE UPPER(TRIM(name)) = 'EE DR JOÃO NOGUEIRA DE ALMEIDA' 
  AND UPPER(TRIM(city)) = 'SANTANA DOS MONTES' 
  AND inep_code IS NULL;

-- EE DESEMBARGADOR APRÍGIO RIBEIRO DE OLIVEIRA (SÃO BRÁS DO SUAÇUÍ) - INEP: 194425
UPDATE schools 
SET inep_code = '194425' 
WHERE UPPER(TRIM(name)) = 'EE DESEMBARGADOR APRÍGIO RIBEIRO DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'SÃO BRÁS DO SUAÇUÍ' 
  AND inep_code IS NULL;

-- EE QUINZINHO INÁCIO (SENHORA DE OLIVEIRA) - INEP: 194468
UPDATE schools 
SET inep_code = '194468' 
WHERE UPPER(TRIM(name)) = 'EE QUINZINHO INÁCIO' 
  AND UPPER(TRIM(city)) = 'SENHORA DE OLIVEIRA' 
  AND inep_code IS NULL;

-- EE CORONEL FABRICIANO FELISBERTO DE BRITO (ANTÔNIO DIAS) - INEP: 190641
UPDATE schools 
SET inep_code = '190641' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL FABRICIANO FELISBERTO DE BRITO' 
  AND UPPER(TRIM(city)) = 'ANTÔNIO DIAS' 
  AND inep_code IS NULL;

-- EE GERMANO PEDRO DE SOUZA (ANTÔNIO DIAS) - INEP: 190705
UPDATE schools 
SET inep_code = '190705' 
WHERE UPPER(TRIM(name)) = 'EE GERMANO PEDRO DE SOUZA' 
  AND UPPER(TRIM(city)) = 'ANTÔNIO DIAS' 
  AND inep_code IS NULL;

-- EE PROFESSOR LETRO (ANTÔNIO DIAS) - INEP: 190683
UPDATE schools 
SET inep_code = '190683' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR LETRO' 
  AND UPPER(TRIM(city)) = 'ANTÔNIO DIAS' 
  AND inep_code IS NULL;

-- EE VICENTE INÁCIO BISPO (ANTÔNIO DIAS) - INEP: 190659
UPDATE schools 
SET inep_code = '190659' 
WHERE UPPER(TRIM(name)) = 'EE VICENTE INÁCIO BISPO' 
  AND UPPER(TRIM(city)) = 'ANTÔNIO DIAS' 
  AND inep_code IS NULL;

-- EE JOÃO HEMÉTRIO DE MENEZES (BELO ORIENTE) - INEP: 273368
UPDATE schools 
SET inep_code = '273368' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO HEMÉTRIO DE MENEZES' 
  AND UPPER(TRIM(city)) = 'BELO ORIENTE' 
  AND inep_code IS NULL;

-- EE PRESIDENTE TANCREDO NEVES (BELO ORIENTE) - INEP: 190756
UPDATE schools 
SET inep_code = '190756' 
WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE TANCREDO NEVES' 
  AND UPPER(TRIM(city)) = 'BELO ORIENTE' 
  AND inep_code IS NULL;

-- EE FAGUNDES VARELA (BRAÚNAS) - INEP: 190772
UPDATE schools 
SET inep_code = '190772' 
WHERE UPPER(TRIM(name)) = 'EE FAGUNDES VARELA' 
  AND UPPER(TRIM(city)) = 'BRAÚNAS' 
  AND inep_code IS NULL;

-- EE MARIA IZABEL MOREIRA PINTO (BRAÚNAS) - INEP: 190799
UPDATE schools 
SET inep_code = '190799' 
WHERE UPPER(TRIM(name)) = 'EE MARIA IZABEL MOREIRA PINTO' 
  AND UPPER(TRIM(city)) = 'BRAÚNAS' 
  AND inep_code IS NULL;

-- EE ALBERTO GIOVANNINI (CORONEL FABRICIANO) - INEP: 190802
UPDATE schools 
SET inep_code = '190802' 
WHERE UPPER(TRIM(name)) = 'EE ALBERTO GIOVANNINI' 
  AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' 
  AND inep_code IS NULL;

-- EE CORONEL SILVINO PEREIRA (CORONEL FABRICIANO) - INEP: 190926
UPDATE schools 
SET inep_code = '190926' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL SILVINO PEREIRA' 
  AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' 
  AND inep_code IS NULL;

-- EE DOUTOR GERALDO PERLINGEIRO DE ABREU (CORONEL FABRICIANO) - INEP: 221449
UPDATE schools 
SET inep_code = '221449' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR GERALDO PERLINGEIRO DE ABREU' 
  AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' 
  AND inep_code IS NULL;

-- EE DOUTOR JOAQUIM GOMES DA SILVEIRA NETO (CORONEL FABRICIANO) - INEP: 190829
UPDATE schools 
SET inep_code = '190829' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR JOAQUIM GOMES DA SILVEIRA NETO' 
  AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' 
  AND inep_code IS NULL;

-- EE INTENDENTE CÂMARA (CORONEL FABRICIANO) - INEP: 190870
UPDATE schools 
SET inep_code = '190870' 
WHERE UPPER(TRIM(name)) = 'EE INTENDENTE CÂMARA' 
  AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' 
  AND inep_code IS NULL;

-- EE PADRE DEOLINDO COELHO (CORONEL FABRICIANO) - INEP: 190934
UPDATE schools 
SET inep_code = '190934' 
WHERE UPPER(TRIM(name)) = 'EE PADRE DEOLINDO COELHO' 
  AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' 
  AND inep_code IS NULL;

-- EE PADRE JOSÉ MARIA DE MAN (CORONEL FABRICIANO) - INEP: 190942
UPDATE schools 
SET inep_code = '190942' 
WHERE UPPER(TRIM(name)) = 'EE PADRE JOSÉ MARIA DE MAN' 
  AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' 
  AND inep_code IS NULL;

-- EE PROFESSOR FRANCISCO LETRO (CORONEL FABRICIANO) - INEP: 190951
UPDATE schools 
SET inep_code = '190951' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR FRANCISCO LETRO' 
  AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' 
  AND inep_code IS NULL;

-- EE PROFESSOR PEDRO CALMON (CORONEL FABRICIANO) - INEP: 190888
UPDATE schools 
SET inep_code = '190888' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR PEDRO CALMON' 
  AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' 
  AND inep_code IS NULL;

-- EE PROFESSORA CELINA MACHADO (CORONEL FABRICIANO) - INEP: 190900
UPDATE schools 
SET inep_code = '190900' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA CELINA MACHADO' 
  AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' 
  AND inep_code IS NULL;

-- EE RAULINO COTTA PACHECO (CORONEL FABRICIANO) - INEP: 190918
UPDATE schools 
SET inep_code = '190918' 
WHERE UPPER(TRIM(name)) = 'EE RAULINO COTTA PACHECO' 
  AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' 
  AND inep_code IS NULL;

-- EE ROTILDINO AVELINO (CORONEL FABRICIANO) - INEP: 190969
UPDATE schools 
SET inep_code = '190969' 
WHERE UPPER(TRIM(name)) = 'EE ROTILDINO AVELINO' 
  AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' 
  AND inep_code IS NULL;

-- EE TANCREDO DE ALMEIDA NEVES (CORONEL FABRICIANO) - INEP: 190985
UPDATE schools 
SET inep_code = '190985' 
WHERE UPPER(TRIM(name)) = 'EE TANCREDO DE ALMEIDA NEVES' 
  AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' 
  AND inep_code IS NULL;

-- EE ZACARIAS ROQUE (CORONEL FABRICIANO) - INEP: 190977
UPDATE schools 
SET inep_code = '190977' 
WHERE UPPER(TRIM(name)) = 'EE ZACARIAS ROQUE' 
  AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' 
  AND inep_code IS NULL;

-- CESEC JOÃO GUIMARÃES ROSA (IPATINGA) - INEP: 313726
UPDATE schools 
SET inep_code = '313726' 
WHERE UPPER(TRIM(name)) = 'CESEC JOÃO GUIMARÃES ROSA' 
  AND UPPER(TRIM(city)) = 'IPATINGA' 
  AND inep_code IS NULL;

-- COLÉGIO TIRADENTES PMMG (IPATINGA) - INEP: 191132
UPDATE schools 
SET inep_code = '191132' 
WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG' 
  AND UPPER(TRIM(city)) = 'IPATINGA' 
  AND inep_code IS NULL;

-- EE ALMIRANTE TOYODA (IPATINGA) - INEP: 190993
UPDATE schools 
SET inep_code = '190993' 
WHERE UPPER(TRIM(name)) = 'EE ALMIRANTE TOYODA' 
  AND UPPER(TRIM(city)) = 'IPATINGA' 
  AND inep_code IS NULL;

-- EE CHICO MENDES (IPATINGA) - INEP: 191281
UPDATE schools 
SET inep_code = '191281' 
WHERE UPPER(TRIM(name)) = 'EE CHICO MENDES' 
  AND UPPER(TRIM(city)) = 'IPATINGA' 
  AND inep_code IS NULL;

-- EE DOM HELVÉCIO (IPATINGA) - INEP: 191027
UPDATE schools 
SET inep_code = '191027' 
WHERE UPPER(TRIM(name)) = 'EE DOM HELVÉCIO' 
  AND UPPER(TRIM(city)) = 'IPATINGA' 
  AND inep_code IS NULL;

-- EE DONA CAETANA AMÉRICA MENEZES (IPATINGA) - INEP: 191191
UPDATE schools 
SET inep_code = '191191' 
WHERE UPPER(TRIM(name)) = 'EE DONA CAETANA AMÉRICA MENEZES' 
  AND UPPER(TRIM(city)) = 'IPATINGA' 
  AND inep_code IS NULL;

-- EE DONA CANUTA ROSA OLIVEIRA BARBOSA (IPATINGA) - INEP: 191221
UPDATE schools 
SET inep_code = '191221' 
WHERE UPPER(TRIM(name)) = 'EE DONA CANUTA ROSA OLIVEIRA BARBOSA' 
  AND UPPER(TRIM(city)) = 'IPATINGA' 
  AND inep_code IS NULL;

-- EE DOUTOR OVÍDIO DE ANDRADE (IPATINGA) - INEP: 191035
UPDATE schools 
SET inep_code = '191035' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR OVÍDIO DE ANDRADE' 
  AND UPPER(TRIM(city)) = 'IPATINGA' 
  AND inep_code IS NULL;

-- EE ENGENHEIRO AMARO LANARI JÚNIOR (IPATINGA) - INEP: 191183
UPDATE schools 
SET inep_code = '191183' 
WHERE UPPER(TRIM(name)) = 'EE ENGENHEIRO AMARO LANARI JÚNIOR' 
  AND UPPER(TRIM(city)) = 'IPATINGA' 
  AND inep_code IS NULL;

-- EE ENGENHEIRO MÁRCIO AGUIAR DA CUNHA (IPATINGA) - INEP: 191043
UPDATE schools 
SET inep_code = '191043' 
WHERE UPPER(TRIM(name)) = 'EE ENGENHEIRO MÁRCIO AGUIAR DA CUNHA' 
  AND UPPER(TRIM(city)) = 'IPATINGA' 
  AND inep_code IS NULL;

-- EE GERALDO GOMES RIBEIRO (IPATINGA) - INEP: 191205
UPDATE schools 
SET inep_code = '191205' 
WHERE UPPER(TRIM(name)) = 'EE GERALDO GOMES RIBEIRO' 
  AND UPPER(TRIM(city)) = 'IPATINGA' 
  AND inep_code IS NULL;

-- EE HAYDÉE MARIA IMACULADA SCHITTINI (IPATINGA) - INEP: 191159
UPDATE schools 
SET inep_code = '191159' 
WHERE UPPER(TRIM(name)) = 'EE HAYDÉE MARIA IMACULADA SCHITTINI' 
  AND UPPER(TRIM(city)) = 'IPATINGA' 
  AND inep_code IS NULL;

-- EE JOÃO WALMICK (IPATINGA) - INEP: 191078
UPDATE schools 
SET inep_code = '191078' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO WALMICK' 
  AND UPPER(TRIM(city)) = 'IPATINGA' 
  AND inep_code IS NULL;

-- EE JOÃO XXIII (IPATINGA) - INEP: 191060
UPDATE schools 
SET inep_code = '191060' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO XXIII' 
  AND UPPER(TRIM(city)) = 'IPATINGA' 
  AND inep_code IS NULL;

-- EE LAURA XAVIER SANTANA (IPATINGA) - INEP: 191001
UPDATE schools 
SET inep_code = '191001' 
WHERE UPPER(TRIM(name)) = 'EE LAURA XAVIER SANTANA' 
  AND UPPER(TRIM(city)) = 'IPATINGA' 
  AND inep_code IS NULL;

-- EE MANOEL IZÍDIO (IPATINGA) - INEP: 191086
UPDATE schools 
SET inep_code = '191086' 
WHERE UPPER(TRIM(name)) = 'EE MANOEL IZÍDIO' 
  AND UPPER(TRIM(city)) = 'IPATINGA' 
  AND inep_code IS NULL;

-- EE MANOELA SOARES BICALHO (IPATINGA) - INEP: 191264
UPDATE schools 
SET inep_code = '191264' 
WHERE UPPER(TRIM(name)) = 'EE MANOELA SOARES BICALHO' 
  AND UPPER(TRIM(city)) = 'IPATINGA' 
  AND inep_code IS NULL;

-- EE MAURÍLIO ALBANESE NOVAES (IPATINGA) - INEP: 191124
UPDATE schools 
SET inep_code = '191124' 
WHERE UPPER(TRIM(name)) = 'EE MAURÍLIO ALBANESE NOVAES' 
  AND UPPER(TRIM(city)) = 'IPATINGA' 
  AND inep_code IS NULL;

-- EE NACIF SELIM DE SALES (IPATINGA) - INEP: 191213
UPDATE schools 
SET inep_code = '191213' 
WHERE UPPER(TRIM(name)) = 'EE NACIF SELIM DE SALES' 
  AND UPPER(TRIM(city)) = 'IPATINGA' 
  AND inep_code IS NULL;

-- EE NILZA LUZIA DE SOUZA BUTTA (IPATINGA) - INEP: 217310
UPDATE schools 
SET inep_code = '217310' 
WHERE UPPER(TRIM(name)) = 'EE NILZA LUZIA DE SOUZA BUTTA' 
  AND UPPER(TRIM(city)) = 'IPATINGA' 
  AND inep_code IS NULL;

-- EE PROFESSORA ELZA DE OLIVEIRA LAGE (IPATINGA) - INEP: 191299
UPDATE schools 
SET inep_code = '191299' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ELZA DE OLIVEIRA LAGE' 
  AND UPPER(TRIM(city)) = 'IPATINGA' 
  AND inep_code IS NULL;

-- EE PROFESSORA MARIA ANTONIETA (IPATINGA) - INEP: 191116
UPDATE schools 
SET inep_code = '191116' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA ANTONIETA' 
  AND UPPER(TRIM(city)) = 'IPATINGA' 
  AND inep_code IS NULL;

-- EE SELIM JOSÉ DE SALLES (IPATINGA) - INEP: 191256
UPDATE schools 
SET inep_code = '191256' 
WHERE UPPER(TRIM(name)) = 'EE SELIM JOSÉ DE SALLES' 
  AND UPPER(TRIM(city)) = 'IPATINGA' 
  AND inep_code IS NULL;

-- EE SÔNIA MARIA SILVA GOMES (IPATINGA) - INEP: 191302
UPDATE schools 
SET inep_code = '191302' 
WHERE UPPER(TRIM(name)) = 'EE SÔNIA MARIA SILVA GOMES' 
  AND UPPER(TRIM(city)) = 'IPATINGA' 
  AND inep_code IS NULL;

-- EE WILSON ALVARENGA (IPATINGA) - INEP: 191248
UPDATE schools 
SET inep_code = '191248' 
WHERE UPPER(TRIM(name)) = 'EE WILSON ALVARENGA' 
  AND UPPER(TRIM(city)) = 'IPATINGA' 
  AND inep_code IS NULL;

-- EE PROFESSORA SEBASTIANA DE ALMEIDA E SILVA (JAGUARAÇU) - INEP: 361453
UPDATE schools 
SET inep_code = '361453' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA SEBASTIANA DE ALMEIDA E SILVA' 
  AND UPPER(TRIM(city)) = 'JAGUARAÇU' 
  AND inep_code IS NULL;


COMMIT;
