-- Lote 5 de 7
-- Updates 1201 a 1500

BEGIN;

-- EE PARAISENSE (SÃO SEBASTIÃO DO PARAÍSO) - INEP: 137944
UPDATE schools 
SET inep_code = '137944' 
WHERE UPPER(TRIM(name)) = 'EE PARAISENSE' 
  AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' 
  AND inep_code IS NULL;

-- EE PAULA FRASSINETTI (SÃO SEBASTIÃO DO PARAÍSO) - INEP: 137928
UPDATE schools 
SET inep_code = '137928' 
WHERE UPPER(TRIM(name)) = 'EE PAULA FRASSINETTI' 
  AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' 
  AND inep_code IS NULL;

-- EE PROFESSORA INÊS MIRANDA ALMEIDA (SÃO SEBASTIÃO DO PARAÍSO) - INEP: 212431
UPDATE schools 
SET inep_code = '212431' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA INÊS MIRANDA ALMEIDA' 
  AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' 
  AND inep_code IS NULL;

-- EE SÃO JOÃO DA ESCÓCIA (SÃO SEBASTIÃO DO PARAÍSO) - INEP: 137961
UPDATE schools 
SET inep_code = '137961' 
WHERE UPPER(TRIM(name)) = 'EE SÃO JOÃO DA ESCÓCIA' 
  AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' 
  AND inep_code IS NULL;

-- EE DOUTOR TANCREDO DE ALMEIDA NEVES (SÃO TOMÁS DE AQUINO) - INEP: 138053
UPDATE schools 
SET inep_code = '138053' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR TANCREDO DE ALMEIDA NEVES' 
  AND UPPER(TRIM(city)) = 'SÃO TOMÁS DE AQUINO' 
  AND inep_code IS NULL;

-- EE PROFESSORA MARIA DA CONCEIÇÃO SILVA (ARAÇAÍ) - INEP: 311189
UPDATE schools 
SET inep_code = '311189' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA DA CONCEIÇÃO SILVA' 
  AND UPPER(TRIM(city)) = 'ARAÇAÍ' 
  AND inep_code IS NULL;

-- EE JOSÉ RIBEIRO DA SILVA (BALDIM) - INEP: 140325
UPDATE schools 
SET inep_code = '140325' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ RIBEIRO DA SILVA' 
  AND UPPER(TRIM(city)) = 'BALDIM' 
  AND inep_code IS NULL;

-- EE OSCAR ARTUR GUIMARÃES (BALDIM) - INEP: 140376
UPDATE schools 
SET inep_code = '140376' 
WHERE UPPER(TRIM(name)) = 'EE OSCAR ARTUR GUIMARÃES' 
  AND UPPER(TRIM(city)) = 'BALDIM' 
  AND inep_code IS NULL;

-- EE MARIA ANÁLIA MENDES FERREIRA (CACHOEIRA DA PRATA) - INEP: 267805
UPDATE schools 
SET inep_code = '267805' 
WHERE UPPER(TRIM(name)) = 'EE MARIA ANÁLIA MENDES FERREIRA' 
  AND UPPER(TRIM(city)) = 'CACHOEIRA DA PRATA' 
  AND inep_code IS NULL;

-- EE PROFESSORA DORA SILVA (CAETANÓPOLIS) - INEP: 140465
UPDATE schools 
SET inep_code = '140465' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA DORA SILVA' 
  AND UPPER(TRIM(city)) = 'CAETANÓPOLIS' 
  AND inep_code IS NULL;

-- EE FRANCISCO SALES (CAPIM BRANCO) - INEP: 140481
UPDATE schools 
SET inep_code = '140481' 
WHERE UPPER(TRIM(name)) = 'EE FRANCISCO SALES' 
  AND UPPER(TRIM(city)) = 'CAPIM BRANCO' 
  AND inep_code IS NULL;

-- EE MESTRE CORNÉLIO (CAPIM BRANCO) - INEP: 310611
UPDATE schools 
SET inep_code = '310611' 
WHERE UPPER(TRIM(name)) = 'EE MESTRE CORNÉLIO' 
  AND UPPER(TRIM(city)) = 'CAPIM BRANCO' 
  AND inep_code IS NULL;

-- EE CLÁUDIO PINHEIRO DE LIMA (CORDISBURGO) - INEP: 140538
UPDATE schools 
SET inep_code = '140538' 
WHERE UPPER(TRIM(name)) = 'EE CLÁUDIO PINHEIRO DE LIMA' 
  AND UPPER(TRIM(city)) = 'CORDISBURGO' 
  AND inep_code IS NULL;

-- EE MESTRE CANDINHO (CORDISBURGO) - INEP: 140554
UPDATE schools 
SET inep_code = '140554' 
WHERE UPPER(TRIM(name)) = 'EE MESTRE CANDINHO' 
  AND UPPER(TRIM(city)) = 'CORDISBURGO' 
  AND inep_code IS NULL;

-- EE PROFESSOR ANÍSIO TEIXEIRA (CORDISBURGO) - INEP: 140589
UPDATE schools 
SET inep_code = '140589' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ANÍSIO TEIXEIRA' 
  AND UPPER(TRIM(city)) = 'CORDISBURGO' 
  AND inep_code IS NULL;

-- EE CORONEL AMÉRICO TEIXEIRA GUIMARÃES (FORTUNA DE MINAS) - INEP: 141003
UPDATE schools 
SET inep_code = '141003' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL AMÉRICO TEIXEIRA GUIMARÃES' 
  AND UPPER(TRIM(city)) = 'FORTUNA DE MINAS' 
  AND inep_code IS NULL;

-- EE ALUÍSIO FERREIRA DE SOUZA (FUNILÂNDIA) - INEP: 141038
UPDATE schools 
SET inep_code = '141038' 
WHERE UPPER(TRIM(name)) = 'EE ALUÍSIO FERREIRA DE SOUZA' 
  AND UPPER(TRIM(city)) = 'FUNILÂNDIA' 
  AND inep_code IS NULL;

-- EE DIOLINO MOREIRA (FUNILÂNDIA) - INEP: 141054
UPDATE schools 
SET inep_code = '141054' 
WHERE UPPER(TRIM(name)) = 'EE DIOLINO MOREIRA' 
  AND UPPER(TRIM(city)) = 'FUNILÂNDIA' 
  AND inep_code IS NULL;

-- EE MESSIAS ANTÔNIO GUIMARÃES (INHAÚMA) - INEP: 141101
UPDATE schools 
SET inep_code = '141101' 
WHERE UPPER(TRIM(name)) = 'EE MESSIAS ANTÔNIO GUIMARÃES' 
  AND UPPER(TRIM(city)) = 'INHAÚMA' 
  AND inep_code IS NULL;

-- EE PROFESSOR VÍTOR PINTO (JEQUITIBÁ) - INEP: 141135
UPDATE schools 
SET inep_code = '141135' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR VÍTOR PINTO' 
  AND UPPER(TRIM(city)) = 'JEQUITIBÁ' 
  AND inep_code IS NULL;

-- EE BENTO GONÇALVES (MATOZINHOS) - INEP: 141194
UPDATE schools 
SET inep_code = '141194' 
WHERE UPPER(TRIM(name)) = 'EE BENTO GONÇALVES' 
  AND UPPER(TRIM(city)) = 'MATOZINHOS' 
  AND inep_code IS NULL;

-- EE FELÍCIA FERNANDES CAMPOS (MATOZINHOS) - INEP: 141275
UPDATE schools 
SET inep_code = '141275' 
WHERE UPPER(TRIM(name)) = 'EE FELÍCIA FERNANDES CAMPOS' 
  AND UPPER(TRIM(city)) = 'MATOZINHOS' 
  AND inep_code IS NULL;

-- EE HERMELITA SOARES HORTA (MATOZINHOS) - INEP: 141259
UPDATE schools 
SET inep_code = '141259' 
WHERE UPPER(TRIM(name)) = 'EE HERMELITA SOARES HORTA' 
  AND UPPER(TRIM(city)) = 'MATOZINHOS' 
  AND inep_code IS NULL;

-- EE PROFESSORA VITIZA OCTAVIANO VIANA (MATOZINHOS) - INEP: 141186
UPDATE schools 
SET inep_code = '141186' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA VITIZA OCTAVIANO VIANA' 
  AND UPPER(TRIM(city)) = 'MATOZINHOS' 
  AND inep_code IS NULL;

-- EE VISCONDE DO RIO DAS VELHAS (MATOZINHOS) - INEP: 141216
UPDATE schools 
SET inep_code = '141216' 
WHERE UPPER(TRIM(name)) = 'EE VISCONDE DO RIO DAS VELHAS' 
  AND UPPER(TRIM(city)) = 'MATOZINHOS' 
  AND inep_code IS NULL;

-- EE WALDEMAR PEZZINI (MATOZINHOS) - INEP: 310646
UPDATE schools 
SET inep_code = '310646' 
WHERE UPPER(TRIM(name)) = 'EE WALDEMAR PEZZINI' 
  AND UPPER(TRIM(city)) = 'MATOZINHOS' 
  AND inep_code IS NULL;

-- EE AGNALDO EDMUNDO SILVA (PARAOPEBA) - INEP: 230995
UPDATE schools 
SET inep_code = '230995' 
WHERE UPPER(TRIM(name)) = 'EE AGNALDO EDMUNDO SILVA' 
  AND UPPER(TRIM(city)) = 'PARAOPEBA' 
  AND inep_code IS NULL;

-- EE CONSELHEIRO AFONSO PENA (PARAOPEBA) - INEP: 141321
UPDATE schools 
SET inep_code = '141321' 
WHERE UPPER(TRIM(name)) = 'EE CONSELHEIRO AFONSO PENA' 
  AND UPPER(TRIM(city)) = 'PARAOPEBA' 
  AND inep_code IS NULL;

-- EE JOAQUINA CÂNDIDA MOREIRA (PARAOPEBA) - INEP: 310654
UPDATE schools 
SET inep_code = '310654' 
WHERE UPPER(TRIM(name)) = 'EE JOAQUINA CÂNDIDA MOREIRA' 
  AND UPPER(TRIM(city)) = 'PARAOPEBA' 
  AND inep_code IS NULL;

-- EE PADRE AUGUSTO HORTA (PARAOPEBA) - INEP: 141356
UPDATE schools 
SET inep_code = '141356' 
WHERE UPPER(TRIM(name)) = 'EE PADRE AUGUSTO HORTA' 
  AND UPPER(TRIM(city)) = 'PARAOPEBA' 
  AND inep_code IS NULL;

-- EE DONA FRANCISCA DE OLIVEIRA (POMPÉU) - INEP: 141437
UPDATE schools 
SET inep_code = '141437' 
WHERE UPPER(TRIM(name)) = 'EE DONA FRANCISCA DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'POMPÉU' 
  AND inep_code IS NULL;

-- EE DR JACINTO CAMPOS (POMPÉU) - INEP: 141445
UPDATE schools 
SET inep_code = '141445' 
WHERE UPPER(TRIM(name)) = 'EE DR JACINTO CAMPOS' 
  AND UPPER(TRIM(city)) = 'POMPÉU' 
  AND inep_code IS NULL;

-- EE MINISTRO FRANCISCO CAMPOS (POMPÉU) - INEP: 141399
UPDATE schools 
SET inep_code = '141399' 
WHERE UPPER(TRIM(name)) = 'EE MINISTRO FRANCISCO CAMPOS' 
  AND UPPER(TRIM(city)) = 'POMPÉU' 
  AND inep_code IS NULL;

-- EE PAULO CAMPOS GUIMARÃES (POMPÉU) - INEP: 231762
UPDATE schools 
SET inep_code = '231762' 
WHERE UPPER(TRIM(name)) = 'EE PAULO CAMPOS GUIMARÃES' 
  AND UPPER(TRIM(city)) = 'POMPÉU' 
  AND inep_code IS NULL;

-- EE PEDRO ROBERTO DE MENEZES (POMPÉU) - INEP: 141470
UPDATE schools 
SET inep_code = '141470' 
WHERE UPPER(TRIM(name)) = 'EE PEDRO ROBERTO DE MENEZES' 
  AND UPPER(TRIM(city)) = 'POMPÉU' 
  AND inep_code IS NULL;

-- EE ANTÔNIO DELPHINO DOS SANTOS (PRUDENTE DE MORAIS) - INEP: 231550
UPDATE schools 
SET inep_code = '231550' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO DELPHINO DOS SANTOS' 
  AND UPPER(TRIM(city)) = 'PRUDENTE DE MORAIS' 
  AND inep_code IS NULL;

-- EE JOÃO RODRIGUES DA SILVA (PRUDENTE DE MORAIS) - INEP: 141488
UPDATE schools 
SET inep_code = '141488' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO RODRIGUES DA SILVA' 
  AND UPPER(TRIM(city)) = 'PRUDENTE DE MORAIS' 
  AND inep_code IS NULL;

-- EE VIRGÍLIO DE MELO FRANCO (PRUDENTE DE MORAIS) - INEP: 310662
UPDATE schools 
SET inep_code = '310662' 
WHERE UPPER(TRIM(name)) = 'EE VIRGÍLIO DE MELO FRANCO' 
  AND UPPER(TRIM(city)) = 'PRUDENTE DE MORAIS' 
  AND inep_code IS NULL;

-- EE CORONEL DOMINGOS DINIZ COUTO (SANTANA DE PIRAPAMA) - INEP: 141526
UPDATE schools 
SET inep_code = '141526' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL DOMINGOS DINIZ COUTO' 
  AND UPPER(TRIM(city)) = 'SANTANA DE PIRAPAMA' 
  AND inep_code IS NULL;

-- EE JOÃO MARTINS GUIMARÃES (SANTANA DE PIRAPAMA) - INEP: 141585
UPDATE schools 
SET inep_code = '141585' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO MARTINS GUIMARÃES' 
  AND UPPER(TRIM(city)) = 'SANTANA DE PIRAPAMA' 
  AND inep_code IS NULL;

-- EE JUVELINO VIEIRA DE ÁVILA (SANTANA DE PIRAPAMA) - INEP: 141542
UPDATE schools 
SET inep_code = '141542' 
WHERE UPPER(TRIM(name)) = 'EE JUVELINO VIEIRA DE ÁVILA' 
  AND UPPER(TRIM(city)) = 'SANTANA DE PIRAPAMA' 
  AND inep_code IS NULL;

-- CESEC DE SETE LAGOAS (SETE LAGOAS) - INEP: 141615
UPDATE schools 
SET inep_code = '141615' 
WHERE UPPER(TRIM(name)) = 'CESEC DE SETE LAGOAS' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- COLÉGIO TIRADENTES PMMG (SETE LAGOAS) - INEP: 368237
UPDATE schools 
SET inep_code = '368237' 
WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE ANTÔNIO FRANCISCO DE OLIVEIRA (SETE LAGOAS) - INEP: 205591
UPDATE schools 
SET inep_code = '205591' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO FRANCISCO DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE ÁPIO SÓLON CARDOSO (SETE LAGOAS) - INEP: 229288
UPDATE schools 
SET inep_code = '229288' 
WHERE UPPER(TRIM(name)) = 'EE ÁPIO SÓLON CARDOSO' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE BERNARDO VALADARES DE VASCONCELLOS (SETE LAGOAS) - INEP: 141925
UPDATE schools 
SET inep_code = '141925' 
WHERE UPPER(TRIM(name)) = 'EE BERNARDO VALADARES DE VASCONCELLOS' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE CAPITÃO JOÃO LÚCIO DO CARMO (SETE LAGOAS) - INEP: 339296
UPDATE schools 
SET inep_code = '339296' 
WHERE UPPER(TRIM(name)) = 'EE CAPITÃO JOÃO LÚCIO DO CARMO' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE DE ENSINO  MÉDIO (SETE LAGOAS) - INEP: 372110
UPDATE schools 
SET inep_code = '372110' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE DEPUTADO RENATO AZEREDO (SETE LAGOAS) - INEP: 141801
UPDATE schools 
SET inep_code = '141801' 
WHERE UPPER(TRIM(name)) = 'EE DEPUTADO RENATO AZEREDO' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE DOUTOR AFONSO VIANA (SETE LAGOAS) - INEP: 141593
UPDATE schools 
SET inep_code = '141593' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR AFONSO VIANA' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE DOUTOR ALONSO MARQUES FERREIRA (SETE LAGOAS) - INEP: 141887
UPDATE schools 
SET inep_code = '141887' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR ALONSO MARQUES FERREIRA' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE DOUTOR ARTHUR BERNARDES (SETE LAGOAS) - INEP: 141631
UPDATE schools 
SET inep_code = '141631' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR ARTHUR BERNARDES' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE DOUTOR AVELAR (SETE LAGOAS) - INEP: 141674
UPDATE schools 
SET inep_code = '141674' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR AVELAR' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE DOUTOR OLINTO SÁTYRO ALVIM (SETE LAGOAS) - INEP: 141704
UPDATE schools 
SET inep_code = '141704' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR OLINTO SÁTYRO ALVIM' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE DOUTOR ULISSES VASCONCELOS (SETE LAGOAS) - INEP: 141721
UPDATE schools 
SET inep_code = '141721' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR ULISSES VASCONCELOS' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE EDITE FURST (SETE LAGOAS) - INEP: 141640
UPDATE schools 
SET inep_code = '141640' 
WHERE UPPER(TRIM(name)) = 'EE EDITE FURST' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE EMÍLIO DE VASCONCELOS COSTA (SETE LAGOAS) - INEP: 141682
UPDATE schools 
SET inep_code = '141682' 
WHERE UPPER(TRIM(name)) = 'EE EMÍLIO DE VASCONCELOS COSTA' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE EPONINA SOARES DOS SANTOS (SETE LAGOAS) - INEP: 141658
UPDATE schools 
SET inep_code = '141658' 
WHERE UPPER(TRIM(name)) = 'EE EPONINA SOARES DOS SANTOS' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE GOVERNADOR JUSCELINO (SETE LAGOAS) - INEP: 310689
UPDATE schools 
SET inep_code = '310689' 
WHERE UPPER(TRIM(name)) = 'EE GOVERNADOR JUSCELINO' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE JOSÉ EVANGELISTA FRANÇA (SETE LAGOAS) - INEP: 141763
UPDATE schools 
SET inep_code = '141763' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ EVANGELISTA FRANÇA' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE JÚLIO CÉSAR REIS OLIVEIRA (SETE LAGOAS) - INEP: 213675
UPDATE schools 
SET inep_code = '213675' 
WHERE UPPER(TRIM(name)) = 'EE JÚLIO CÉSAR REIS OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE MARIA AMÂNCIO (SETE LAGOAS) - INEP: 310671
UPDATE schools 
SET inep_code = '310671' 
WHERE UPPER(TRIM(name)) = 'EE MARIA AMÂNCIO' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE MAURILO DE JESUS PEIXOTO (SETE LAGOAS) - INEP: 141798
UPDATE schools 
SET inep_code = '141798' 
WHERE UPPER(TRIM(name)) = 'EE MAURILO DE JESUS PEIXOTO' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE MAURO FACCIO GONÇALVES (SETE LAGOAS) - INEP: 353469
UPDATE schools 
SET inep_code = '353469' 
WHERE UPPER(TRIM(name)) = 'EE MAURO FACCIO GONÇALVES' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE MODESTINO ANDRADE SOBRINHO (SETE LAGOAS) - INEP: 141810
UPDATE schools 
SET inep_code = '141810' 
WHERE UPPER(TRIM(name)) = 'EE MODESTINO ANDRADE SOBRINHO' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE PREFEITO ZICO PAIVA (SETE LAGOAS) - INEP: 218944
UPDATE schools 
SET inep_code = '218944' 
WHERE UPPER(TRIM(name)) = 'EE PREFEITO ZICO PAIVA' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE PROFESSOR CÂNDIDO AZEREDO (SETE LAGOAS) - INEP: 141844
UPDATE schools 
SET inep_code = '141844' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR CÂNDIDO AZEREDO' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE PROFESSOR JOÃO FERNANDINO JÚNIOR (SETE LAGOAS) - INEP: 141852
UPDATE schools 
SET inep_code = '141852' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOÃO FERNANDINO JÚNIOR' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE PROFESSOR ROUSSET (SETE LAGOAS) - INEP: 141861
UPDATE schools 
SET inep_code = '141861' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ROUSSET' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE PROFESSORA ELZA MOREIRA LOPES (SETE LAGOAS) - INEP: 141933
UPDATE schools 
SET inep_code = '141933' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ELZA MOREIRA LOPES' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE RUTH BRANDÃO DE AZEREDO (SETE LAGOAS) - INEP: 349305
UPDATE schools 
SET inep_code = '349305' 
WHERE UPPER(TRIM(name)) = 'EE RUTH BRANDÃO DE AZEREDO' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE SANTOS AZEREDO (SETE LAGOAS) - INEP: 141909
UPDATE schools 
SET inep_code = '141909' 
WHERE UPPER(TRIM(name)) = 'EE SANTOS AZEREDO' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE SINHÁ ANDRADE (SETE LAGOAS) - INEP: 141895
UPDATE schools 
SET inep_code = '141895' 
WHERE UPPER(TRIM(name)) = 'EE SINHÁ ANDRADE' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE VENCESLAU BRÁS (SETE LAGOAS) - INEP: 342572
UPDATE schools 
SET inep_code = '342572' 
WHERE UPPER(TRIM(name)) = 'EE VENCESLAU BRÁS' 
  AND UPPER(TRIM(city)) = 'SETE LAGOAS' 
  AND inep_code IS NULL;

-- EE CAPITÃO INÁCIO SOARES (ÁGUAS FORMOSAS) - INEP: 145912
UPDATE schools 
SET inep_code = '145912' 
WHERE UPPER(TRIM(name)) = 'EE CAPITÃO INÁCIO SOARES' 
  AND UPPER(TRIM(city)) = 'ÁGUAS FORMOSAS' 
  AND inep_code IS NULL;

-- EE CARLOS MAGNO REBOUÇAS (ÁGUAS FORMOSAS) - INEP: 145904
UPDATE schools 
SET inep_code = '145904' 
WHERE UPPER(TRIM(name)) = 'EE CARLOS MAGNO REBOUÇAS' 
  AND UPPER(TRIM(city)) = 'ÁGUAS FORMOSAS' 
  AND inep_code IS NULL;

-- EE CESÁRIO MATIAS DE ALMEIDA (ÁGUAS FORMOSAS) - INEP: 145921
UPDATE schools 
SET inep_code = '145921' 
WHERE UPPER(TRIM(name)) = 'EE CESÁRIO MATIAS DE ALMEIDA' 
  AND UPPER(TRIM(city)) = 'ÁGUAS FORMOSAS' 
  AND inep_code IS NULL;

-- EE DE ÁGUA QUENTE (ÁGUAS FORMOSAS) - INEP: 145947
UPDATE schools 
SET inep_code = '145947' 
WHERE UPPER(TRIM(name)) = 'EE DE ÁGUA QUENTE' 
  AND UPPER(TRIM(city)) = 'ÁGUAS FORMOSAS' 
  AND inep_code IS NULL;

-- EE JOSÉ QUARESMA DA COSTA (ÁGUAS FORMOSAS) - INEP: 145955
UPDATE schools 
SET inep_code = '145955' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ QUARESMA DA COSTA' 
  AND UPPER(TRIM(city)) = 'ÁGUAS FORMOSAS' 
  AND inep_code IS NULL;

-- EE MAJOR RAIMUNDO FELICÍSSIMO (ÁGUAS FORMOSAS) - INEP: 145963
UPDATE schools 
SET inep_code = '145963' 
WHERE UPPER(TRIM(name)) = 'EE MAJOR RAIMUNDO FELICÍSSIMO' 
  AND UPPER(TRIM(city)) = 'ÁGUAS FORMOSAS' 
  AND inep_code IS NULL;

-- EE DANIEL PEREIRA OTTONI (ATALÉIA) - INEP: 338818
UPDATE schools 
SET inep_code = '338818' 
WHERE UPPER(TRIM(name)) = 'EE DANIEL PEREIRA OTTONI' 
  AND UPPER(TRIM(city)) = 'ATALÉIA' 
  AND inep_code IS NULL;

-- EE DE NOVO HORIZONTE (ATALÉIA) - INEP: 146412
UPDATE schools 
SET inep_code = '146412' 
WHERE UPPER(TRIM(name)) = 'EE DE NOVO HORIZONTE' 
  AND UPPER(TRIM(city)) = 'ATALÉIA' 
  AND inep_code IS NULL;

-- EE DE SÃO MIGUEL (ATALÉIA) - INEP: 146391
UPDATE schools 
SET inep_code = '146391' 
WHERE UPPER(TRIM(name)) = 'EE DE SÃO MIGUEL' 
  AND UPPER(TRIM(city)) = 'ATALÉIA' 
  AND inep_code IS NULL;

-- EE DOUTOR ANTÔNIO OLINTO (ATALÉIA) - INEP: 146315
UPDATE schools 
SET inep_code = '146315' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR ANTÔNIO OLINTO' 
  AND UPPER(TRIM(city)) = 'ATALÉIA' 
  AND inep_code IS NULL;

-- EE PREFEITO CLEMENTE ESTEVES FERRAZ (ATALÉIA) - INEP: 146285
UPDATE schools 
SET inep_code = '146285' 
WHERE UPPER(TRIM(name)) = 'EE PREFEITO CLEMENTE ESTEVES FERRAZ' 
  AND UPPER(TRIM(city)) = 'ATALÉIA' 
  AND inep_code IS NULL;

-- EE PROFESSORA ALNEDA DE MATOS MACHADO (ATALÉIA) - INEP: 146331
UPDATE schools 
SET inep_code = '146331' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ALNEDA DE MATOS MACHADO' 
  AND UPPER(TRIM(city)) = 'ATALÉIA' 
  AND inep_code IS NULL;

-- EE PROFESSORA HERMÍNIA P DE ALMEIDA (ATALÉIA) - INEP: 146323
UPDATE schools 
SET inep_code = '146323' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA HERMÍNIA P DE ALMEIDA' 
  AND UPPER(TRIM(city)) = 'ATALÉIA' 
  AND inep_code IS NULL;

-- EE DE BERTÓPOLIS (BERTÓPOLIS) - INEP: 146421
UPDATE schools 
SET inep_code = '146421' 
WHERE UPPER(TRIM(name)) = 'EE DE BERTÓPOLIS' 
  AND UPPER(TRIM(city)) = 'BERTÓPOLIS' 
  AND inep_code IS NULL;

-- EE DE UMBURANINHA (BERTÓPOLIS) - INEP: 146439
UPDATE schools 
SET inep_code = '146439' 
WHERE UPPER(TRIM(name)) = 'EE DE UMBURANINHA' 
  AND UPPER(TRIM(city)) = 'BERTÓPOLIS' 
  AND inep_code IS NULL;

-- EE INDÍGENA CAPITÃOZINHO MAXAKALI (BERTÓPOLIS) - INEP: 269867
UPDATE schools 
SET inep_code = '269867' 
WHERE UPPER(TRIM(name)) = 'EE INDÍGENA CAPITÃOZINHO MAXAKALI' 
  AND UPPER(TRIM(city)) = 'BERTÓPOLIS' 
  AND inep_code IS NULL;

-- EE ANTÔNIO DUARTE SOBRINHO (CAMPANÁRIO) - INEP: 146471
UPDATE schools 
SET inep_code = '146471' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO DUARTE SOBRINHO' 
  AND UPPER(TRIM(city)) = 'CAMPANÁRIO' 
  AND inep_code IS NULL;

-- EE DE CARAÍ (CARAÍ) - INEP: 146510
UPDATE schools 
SET inep_code = '146510' 
WHERE UPPER(TRIM(name)) = 'EE DE CARAÍ' 
  AND UPPER(TRIM(city)) = 'CARAÍ' 
  AND inep_code IS NULL;

-- EE DE ENSINO MÉDIO (CARAÍ) - INEP: 372072
UPDATE schools 
SET inep_code = '372072' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' 
  AND UPPER(TRIM(city)) = 'CARAÍ' 
  AND inep_code IS NULL;

-- EE DOM JOSÉ DE HAAS (CARAÍ) - INEP: 146536
UPDATE schools 
SET inep_code = '146536' 
WHERE UPPER(TRIM(name)) = 'EE DOM JOSÉ DE HAAS' 
  AND UPPER(TRIM(city)) = 'CARAÍ' 
  AND inep_code IS NULL;

-- EE ORLANDO TAVARES (CARAÍ) - INEP: 146544
UPDATE schools 
SET inep_code = '146544' 
WHERE UPPER(TRIM(name)) = 'EE ORLANDO TAVARES' 
  AND UPPER(TRIM(city)) = 'CARAÍ' 
  AND inep_code IS NULL;

-- EE PROFESSOR ABGAR RENAULT (CARAÍ) - INEP: 146528
UPDATE schools 
SET inep_code = '146528' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ABGAR RENAULT' 
  AND UPPER(TRIM(city)) = 'CARAÍ' 
  AND inep_code IS NULL;

-- EE DOUTOR JOÃO BERALDO (CARLOS CHAGAS) - INEP: 146579
UPDATE schools 
SET inep_code = '146579' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR JOÃO BERALDO' 
  AND UPPER(TRIM(city)) = 'CARLOS CHAGAS' 
  AND inep_code IS NULL;

-- EE EPAMINONDAS OTONI (CARLOS CHAGAS) - INEP: 146625
UPDATE schools 
SET inep_code = '146625' 
WHERE UPPER(TRIM(name)) = 'EE EPAMINONDAS OTONI' 
  AND UPPER(TRIM(city)) = 'CARLOS CHAGAS' 
  AND inep_code IS NULL;

-- EE GERALDO DE SOUZA NORTE (CARLOS CHAGAS) - INEP: 146561
UPDATE schools 
SET inep_code = '146561' 
WHERE UPPER(TRIM(name)) = 'EE GERALDO DE SOUZA NORTE' 
  AND UPPER(TRIM(city)) = 'CARLOS CHAGAS' 
  AND inep_code IS NULL;

-- EE OLGA PRATES (CARLOS CHAGAS) - INEP: 146633
UPDATE schools 
SET inep_code = '146633' 
WHERE UPPER(TRIM(name)) = 'EE OLGA PRATES' 
  AND UPPER(TRIM(city)) = 'CARLOS CHAGAS' 
  AND inep_code IS NULL;

-- EE PROFESSORA ANTÔNIA BERNARDO RODRIGUES (CARLOS CHAGAS) - INEP: 346179
UPDATE schools 
SET inep_code = '346179' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ANTÔNIA BERNARDO RODRIGUES' 
  AND UPPER(TRIM(city)) = 'CARLOS CHAGAS' 
  AND inep_code IS NULL;

-- EE DOUTOR CIRO MACIEL (CATUJI) - INEP: 146749
UPDATE schools 
SET inep_code = '146749' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR CIRO MACIEL' 
  AND UPPER(TRIM(city)) = 'CATUJI' 
  AND inep_code IS NULL;

-- EE GEORGINA FERREIRA BATISTA (CATUJI) - INEP: 330591
UPDATE schools 
SET inep_code = '330591' 
WHERE UPPER(TRIM(name)) = 'EE GEORGINA FERREIRA BATISTA' 
  AND UPPER(TRIM(city)) = 'CATUJI' 
  AND inep_code IS NULL;

-- EE RAUL FERREIRA SOUTO (CRISÓLITA) - INEP: 145980
UPDATE schools 
SET inep_code = '145980' 
WHERE UPPER(TRIM(name)) = 'EE RAUL FERREIRA SOUTO' 
  AND UPPER(TRIM(city)) = 'CRISÓLITA' 
  AND inep_code IS NULL;

-- EE DE ANTÔNIO FERREIRA (FRANCISCÓPOLIS) - INEP: 147222
UPDATE schools 
SET inep_code = '147222' 
WHERE UPPER(TRIM(name)) = 'EE DE ANTÔNIO FERREIRA' 
  AND UPPER(TRIM(city)) = 'FRANCISCÓPOLIS' 
  AND inep_code IS NULL;

-- EE MARIA DA SILVA ROCHA (FRANCISCÓPOLIS) - INEP: 147249
UPDATE schools 
SET inep_code = '147249' 
WHERE UPPER(TRIM(name)) = 'EE MARIA DA SILVA ROCHA' 
  AND UPPER(TRIM(city)) = 'FRANCISCÓPOLIS' 
  AND inep_code IS NULL;

-- EE SALMEN BUKZEM (FREI GASPAR) - INEP: 146706
UPDATE schools 
SET inep_code = '146706' 
WHERE UPPER(TRIM(name)) = 'EE SALMEN BUKZEM' 
  AND UPPER(TRIM(city)) = 'FREI GASPAR' 
  AND inep_code IS NULL;

-- EE DE PAMPÃ (FRONTEIRA DOS VALES) - INEP: 146714
UPDATE schools 
SET inep_code = '146714' 
WHERE UPPER(TRIM(name)) = 'EE DE PAMPÃ' 
  AND UPPER(TRIM(city)) = 'FRONTEIRA DOS VALES' 
  AND inep_code IS NULL;

-- EE CORONEL CLEMENTE LUIZ (ITAIPÉ) - INEP: 146731
UPDATE schools 
SET inep_code = '146731' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL CLEMENTE LUIZ' 
  AND UPPER(TRIM(city)) = 'ITAIPÉ' 
  AND inep_code IS NULL;

-- EE PROFESSORA FRANCISCA MATOS (ITAIPÉ) - INEP: 319082
UPDATE schools 
SET inep_code = '319082' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA FRANCISCA MATOS' 
  AND UPPER(TRIM(city)) = 'ITAIPÉ' 
  AND inep_code IS NULL;

-- EE CARLOS PRATES (ITAMBACURI) - INEP: 146811
UPDATE schools 
SET inep_code = '146811' 
WHERE UPPER(TRIM(name)) = 'EE CARLOS PRATES' 
  AND UPPER(TRIM(city)) = 'ITAMBACURI' 
  AND inep_code IS NULL;

-- EE DOUTOR TRISTÃO DA CUNHA (ITAMBACURI) - INEP: 146757
UPDATE schools 
SET inep_code = '146757' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR TRISTÃO DA CUNHA' 
  AND UPPER(TRIM(city)) = 'ITAMBACURI' 
  AND inep_code IS NULL;

-- EE FREI GASPAR DE MÓDICA (ITAMBACURI) - INEP: 146803
UPDATE schools 
SET inep_code = '146803' 
WHERE UPPER(TRIM(name)) = 'EE FREI GASPAR DE MÓDICA' 
  AND UPPER(TRIM(city)) = 'ITAMBACURI' 
  AND inep_code IS NULL;

-- EE MADRE SERAFINA DE JESUS (ITAMBACURI) - INEP: 146820
UPDATE schools 
SET inep_code = '146820' 
WHERE UPPER(TRIM(name)) = 'EE MADRE SERAFINA DE JESUS' 
  AND UPPER(TRIM(city)) = 'ITAMBACURI' 
  AND inep_code IS NULL;

-- EE PROFESSORA MÍLCIA DE OLIVEIRA ABRANTES (ITAMBACURI) - INEP: 146781
UPDATE schools 
SET inep_code = '146781' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MÍLCIA DE OLIVEIRA ABRANTES' 
  AND UPPER(TRIM(city)) = 'ITAMBACURI' 
  AND inep_code IS NULL;

-- EE RAMIRO SOUZA E SILVA (ITAMBACURI) - INEP: 146871
UPDATE schools 
SET inep_code = '146871' 
WHERE UPPER(TRIM(name)) = 'EE RAMIRO SOUZA E SILVA' 
  AND UPPER(TRIM(city)) = 'ITAMBACURI' 
  AND inep_code IS NULL;

-- EE VEREADOR JÚLIO LAGES (ITAMBACURI) - INEP: 146862
UPDATE schools 
SET inep_code = '146862' 
WHERE UPPER(TRIM(name)) = 'EE VEREADOR JÚLIO LAGES' 
  AND UPPER(TRIM(city)) = 'ITAMBACURI' 
  AND inep_code IS NULL;

-- EE CASSIMIRO DE ABREU (JAMPRUCA) - INEP: 146501
UPDATE schools 
SET inep_code = '146501' 
WHERE UPPER(TRIM(name)) = 'EE CASSIMIRO DE ABREU' 
  AND UPPER(TRIM(city)) = 'JAMPRUCA' 
  AND inep_code IS NULL;

-- EE CORONEL ANTÔNIO LOPES (JAMPRUCA) - INEP: 146480
UPDATE schools 
SET inep_code = '146480' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL ANTÔNIO LOPES' 
  AND UPPER(TRIM(city)) = 'JAMPRUCA' 
  AND inep_code IS NULL;

-- EE DE ENSINO FUNDAMENTAL (JAMPRUCA) - INEP: 369870
UPDATE schools 
SET inep_code = '369870' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL' 
  AND UPPER(TRIM(city)) = 'JAMPRUCA' 
  AND inep_code IS NULL;

-- EE DE CONCÓRDIA DO MUCURI (LADAINHA) - INEP: 147109
UPDATE schools 
SET inep_code = '147109' 
WHERE UPPER(TRIM(name)) = 'EE DE CONCÓRDIA DO MUCURI' 
  AND UPPER(TRIM(city)) = 'LADAINHA' 
  AND inep_code IS NULL;

-- EE DE LADAINHA (LADAINHA) - INEP: 147052
UPDATE schools 
SET inep_code = '147052' 
WHERE UPPER(TRIM(name)) = 'EE DE LADAINHA' 
  AND UPPER(TRIM(city)) = 'LADAINHA' 
  AND inep_code IS NULL;

-- EE ENGENHEIRO WENEFREDO PORTELLA (LADAINHA) - INEP: 147087
UPDATE schools 
SET inep_code = '147087' 
WHERE UPPER(TRIM(name)) = 'EE ENGENHEIRO WENEFREDO PORTELLA' 
  AND UPPER(TRIM(city)) = 'LADAINHA' 
  AND inep_code IS NULL;

-- EE INDÍGENA IZABEL DA SILVA MAXAKALI (LADAINHA) - INEP: 338826
UPDATE schools 
SET inep_code = '338826' 
WHERE UPPER(TRIM(name)) = 'EE INDÍGENA IZABEL DA SILVA MAXAKALI' 
  AND UPPER(TRIM(city)) = 'LADAINHA' 
  AND inep_code IS NULL;

-- EE NOSSA SENHORA DO ROSÁRIO (LADAINHA) - INEP: 147095
UPDATE schools 
SET inep_code = '147095' 
WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DO ROSÁRIO' 
  AND UPPER(TRIM(city)) = 'LADAINHA' 
  AND inep_code IS NULL;

-- EE ANTÔNIO DIAS DOS SANTOS (MACHACALIS) - INEP: 253839
UPDATE schools 
SET inep_code = '253839' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO DIAS DOS SANTOS' 
  AND UPPER(TRIM(city)) = 'MACHACALIS' 
  AND inep_code IS NULL;

-- EE JOSÉ DE ALENCAR (MACHACALIS) - INEP: 147133
UPDATE schools 
SET inep_code = '147133' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ DE ALENCAR' 
  AND UPPER(TRIM(city)) = 'MACHACALIS' 
  AND inep_code IS NULL;

-- EE DE JAGUARITIRA (MALACACHETA) - INEP: 147281
UPDATE schools 
SET inep_code = '147281' 
WHERE UPPER(TRIM(name)) = 'EE DE JAGUARITIRA' 
  AND UPPER(TRIM(city)) = 'MALACACHETA' 
  AND inep_code IS NULL;

-- EE DE SANTO ANTÔNIO DO MUCURI (MALACACHETA) - INEP: 147311
UPDATE schools 
SET inep_code = '147311' 
WHERE UPPER(TRIM(name)) = 'EE DE SANTO ANTÔNIO DO MUCURI' 
  AND UPPER(TRIM(city)) = 'MALACACHETA' 
  AND inep_code IS NULL;

-- EE DEPUTADO CASTRO PIRES (MALACACHETA) - INEP: 147168
UPDATE schools 
SET inep_code = '147168' 
WHERE UPPER(TRIM(name)) = 'EE DEPUTADO CASTRO PIRES' 
  AND UPPER(TRIM(city)) = 'MALACACHETA' 
  AND inep_code IS NULL;

-- EE GERALDO DOS SANTOS COIMBRA (MALACACHETA) - INEP: 147290
UPDATE schools 
SET inep_code = '147290' 
WHERE UPPER(TRIM(name)) = 'EE GERALDO DOS SANTOS COIMBRA' 
  AND UPPER(TRIM(city)) = 'MALACACHETA' 
  AND inep_code IS NULL;

-- EE MESTRA ZULMIRA (MALACACHETA) - INEP: 147206
UPDATE schools 
SET inep_code = '147206' 
WHERE UPPER(TRIM(name)) = 'EE MESTRA ZULMIRA' 
  AND UPPER(TRIM(city)) = 'MALACACHETA' 
  AND inep_code IS NULL;

-- EE MONSENHOR CLÓVIS VIEIRA DA FONSECA (MALACACHETA) - INEP: 147141
UPDATE schools 
SET inep_code = '147141' 
WHERE UPPER(TRIM(name)) = 'EE MONSENHOR CLÓVIS VIEIRA DA FONSECA' 
  AND UPPER(TRIM(city)) = 'MALACACHETA' 
  AND inep_code IS NULL;

-- EE STELLA ABRANTES (MALACACHETA) - INEP: 147192
UPDATE schools 
SET inep_code = '147192' 
WHERE UPPER(TRIM(name)) = 'EE STELLA ABRANTES' 
  AND UPPER(TRIM(city)) = 'MALACACHETA' 
  AND inep_code IS NULL;

-- EE ÁLVARO AMORIM (NANUQUE) - INEP: 147397
UPDATE schools 
SET inep_code = '147397' 
WHERE UPPER(TRIM(name)) = 'EE ÁLVARO AMORIM' 
  AND UPPER(TRIM(city)) = 'NANUQUE' 
  AND inep_code IS NULL;

-- EE ÁLVARO ROMANO (NANUQUE) - INEP: 147419
UPDATE schools 
SET inep_code = '147419' 
WHERE UPPER(TRIM(name)) = 'EE ÁLVARO ROMANO' 
  AND UPPER(TRIM(city)) = 'NANUQUE' 
  AND inep_code IS NULL;

-- EE ANTÔNIO BATISTA DA MOTA (NANUQUE) - INEP: 147451
UPDATE schools 
SET inep_code = '147451' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO BATISTA DA MOTA' 
  AND UPPER(TRIM(city)) = 'NANUQUE' 
  AND inep_code IS NULL;

-- EE GOVERNADOR BIAS FORTES (NANUQUE) - INEP: 147401
UPDATE schools 
SET inep_code = '147401' 
WHERE UPPER(TRIM(name)) = 'EE GOVERNADOR BIAS FORTES' 
  AND UPPER(TRIM(city)) = 'NANUQUE' 
  AND inep_code IS NULL;

-- EE JOSEPH STALIM ROMANO (NANUQUE) - INEP: 147486
UPDATE schools 
SET inep_code = '147486' 
WHERE UPPER(TRIM(name)) = 'EE JOSEPH STALIM ROMANO' 
  AND UPPER(TRIM(city)) = 'NANUQUE' 
  AND inep_code IS NULL;

-- EE PASTOR PAULO NOBRE NASCIMENTO (NANUQUE) - INEP: 147494
UPDATE schools 
SET inep_code = '147494' 
WHERE UPPER(TRIM(name)) = 'EE PASTOR PAULO NOBRE NASCIMENTO' 
  AND UPPER(TRIM(city)) = 'NANUQUE' 
  AND inep_code IS NULL;

-- EE PÉRICLES COELHO (NANUQUE) - INEP: 147508
UPDATE schools 
SET inep_code = '147508' 
WHERE UPPER(TRIM(name)) = 'EE PÉRICLES COELHO' 
  AND UPPER(TRIM(city)) = 'NANUQUE' 
  AND inep_code IS NULL;

-- EE STELLA MATUTINA (NANUQUE) - INEP: 147460
UPDATE schools 
SET inep_code = '147460' 
WHERE UPPER(TRIM(name)) = 'EE STELLA MATUTINA' 
  AND UPPER(TRIM(city)) = 'NANUQUE' 
  AND inep_code IS NULL;

-- EE UNIÃO BENEFICENTE OPERÁRIA (NANUQUE) - INEP: 147478
UPDATE schools 
SET inep_code = '147478' 
WHERE UPPER(TRIM(name)) = 'EE UNIÃO BENEFICENTE OPERÁRIA' 
  AND UPPER(TRIM(city)) = 'NANUQUE' 
  AND inep_code IS NULL;

-- EE VALE DO MUCURI (NANUQUE) - INEP: 147389
UPDATE schools 
SET inep_code = '147389' 
WHERE UPPER(TRIM(name)) = 'EE VALE DO MUCURI' 
  AND UPPER(TRIM(city)) = 'NANUQUE' 
  AND inep_code IS NULL;

-- EE ANTÔNIO RAMOS DE SOUZA (NOVO CRUZEIRO) - INEP: 147575
UPDATE schools 
SET inep_code = '147575' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO RAMOS DE SOUZA' 
  AND UPPER(TRIM(city)) = 'NOVO CRUZEIRO' 
  AND inep_code IS NULL;

-- EE AUGUSTO SOARES (NOVO CRUZEIRO) - INEP: 326119
UPDATE schools 
SET inep_code = '326119' 
WHERE UPPER(TRIM(name)) = 'EE AUGUSTO SOARES' 
  AND UPPER(TRIM(city)) = 'NOVO CRUZEIRO' 
  AND inep_code IS NULL;

-- EE DA FAZENDA ARUEGA (NOVO CRUZEIRO) - INEP: 218430
UPDATE schools 
SET inep_code = '218430' 
WHERE UPPER(TRIM(name)) = 'EE DA FAZENDA ARUEGA' 
  AND UPPER(TRIM(city)) = 'NOVO CRUZEIRO' 
  AND inep_code IS NULL;

-- EE DE LAMBARI (NOVO CRUZEIRO) - INEP: 147583
UPDATE schools 
SET inep_code = '147583' 
WHERE UPPER(TRIM(name)) = 'EE DE LAMBARI' 
  AND UPPER(TRIM(city)) = 'NOVO CRUZEIRO' 
  AND inep_code IS NULL;

-- EE DE SANTA BÁRBARA (NOVO CRUZEIRO) - INEP: 147648
UPDATE schools 
SET inep_code = '147648' 
WHERE UPPER(TRIM(name)) = 'EE DE SANTA BÁRBARA' 
  AND UPPER(TRIM(city)) = 'NOVO CRUZEIRO' 
  AND inep_code IS NULL;

-- EE DO LUFA (NOVO CRUZEIRO) - INEP: 147621
UPDATE schools 
SET inep_code = '147621' 
WHERE UPPER(TRIM(name)) = 'EE DO LUFA' 
  AND UPPER(TRIM(city)) = 'NOVO CRUZEIRO' 
  AND inep_code IS NULL;

-- EE DOM JOSÉ DE HAAS (NOVO CRUZEIRO) - INEP: 147559
UPDATE schools 
SET inep_code = '147559' 
WHERE UPPER(TRIM(name)) = 'EE DOM JOSÉ DE HAAS' 
  AND UPPER(TRIM(city)) = 'NOVO CRUZEIRO' 
  AND inep_code IS NULL;

-- EE EDUARDO MILTON DA SILVA (NOVO CRUZEIRO) - INEP: 147541
UPDATE schools 
SET inep_code = '147541' 
WHERE UPPER(TRIM(name)) = 'EE EDUARDO MILTON DA SILVA' 
  AND UPPER(TRIM(city)) = 'NOVO CRUZEIRO' 
  AND inep_code IS NULL;

-- EE INÁCIO MURTA (NOVO CRUZEIRO) - INEP: 147567
UPDATE schools 
SET inep_code = '147567' 
WHERE UPPER(TRIM(name)) = 'EE INÁCIO MURTA' 
  AND UPPER(TRIM(city)) = 'NOVO CRUZEIRO' 
  AND inep_code IS NULL;

-- EE JOSÉ MENDES BARBOSA (NOVO CRUZEIRO) - INEP: 147656
UPDATE schools 
SET inep_code = '147656' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ MENDES BARBOSA' 
  AND UPPER(TRIM(city)) = 'NOVO CRUZEIRO' 
  AND inep_code IS NULL;

-- EE MARIA CÂNDIDA REIS (NOVO CRUZEIRO) - INEP: 147664
UPDATE schools 
SET inep_code = '147664' 
WHERE UPPER(TRIM(name)) = 'EE MARIA CÂNDIDA REIS' 
  AND UPPER(TRIM(city)) = 'NOVO CRUZEIRO' 
  AND inep_code IS NULL;

-- EE SUL AMÉRICA (NOVO CRUZEIRO) - INEP: 147613
UPDATE schools 
SET inep_code = '147613' 
WHERE UPPER(TRIM(name)) = 'EE SUL AMÉRICA' 
  AND UPPER(TRIM(city)) = 'NOVO CRUZEIRO' 
  AND inep_code IS NULL;

-- EE ADOLFO TEIXEIRA DE SOUZA (NOVO ORIENTE DE MINAS) - INEP: 346144
UPDATE schools 
SET inep_code = '346144' 
WHERE UPPER(TRIM(name)) = 'EE ADOLFO TEIXEIRA DE SOUZA' 
  AND UPPER(TRIM(city)) = 'NOVO ORIENTE DE MINAS' 
  AND inep_code IS NULL;

-- EE DE FREI GONZAGA (NOVO ORIENTE DE MINAS) - INEP: 148393
UPDATE schools 
SET inep_code = '148393' 
WHERE UPPER(TRIM(name)) = 'EE DE FREI GONZAGA' 
  AND UPPER(TRIM(city)) = 'NOVO ORIENTE DE MINAS' 
  AND inep_code IS NULL;

-- EE PAULO PINHEIRO CHAGAS (NOVO ORIENTE DE MINAS) - INEP: 148385
UPDATE schools 
SET inep_code = '148385' 
WHERE UPPER(TRIM(name)) = 'EE PAULO PINHEIRO CHAGAS' 
  AND UPPER(TRIM(city)) = 'NOVO ORIENTE DE MINAS' 
  AND inep_code IS NULL;

-- EE ELISA LEAL (OURO VERDE DE MINAS) - INEP: 254487
UPDATE schools 
SET inep_code = '254487' 
WHERE UPPER(TRIM(name)) = 'EE ELISA LEAL' 
  AND UPPER(TRIM(city)) = 'OURO VERDE DE MINAS' 
  AND inep_code IS NULL;

-- EE VEREADOR LUZO FREITAS DE ARAÚJO (OURO VERDE DE MINAS) - INEP: 147672
UPDATE schools 
SET inep_code = '147672' 
WHERE UPPER(TRIM(name)) = 'EE VEREADOR LUZO FREITAS DE ARAÚJO' 
  AND UPPER(TRIM(city)) = 'OURO VERDE DE MINAS' 
  AND inep_code IS NULL;

-- EE DA VILA SÃO JOÃO (PADRE PARAÍSO) - INEP: 147681
UPDATE schools 
SET inep_code = '147681' 
WHERE UPPER(TRIM(name)) = 'EE DA VILA SÃO JOÃO' 
  AND UPPER(TRIM(city)) = 'PADRE PARAÍSO' 
  AND inep_code IS NULL;

-- EE DE ENSINO MÉDIO (PADRE PARAÍSO) - INEP: 330574
UPDATE schools 
SET inep_code = '330574' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' 
  AND UPPER(TRIM(city)) = 'PADRE PARAÍSO' 
  AND inep_code IS NULL;

-- EE DOUTOR CÂNDIDO ULHOA (PADRE PARAÍSO) - INEP: 147699
UPDATE schools 
SET inep_code = '147699' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR CÂNDIDO ULHOA' 
  AND UPPER(TRIM(city)) = 'PADRE PARAÍSO' 
  AND inep_code IS NULL;

-- EE PRESIDENTE JOÃO PINHEIRO (PADRE PARAÍSO) - INEP: 147702
UPDATE schools 
SET inep_code = '147702' 
WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE JOÃO PINHEIRO' 
  AND UPPER(TRIM(city)) = 'PADRE PARAÍSO' 
  AND inep_code IS NULL;

-- EE PROFESSOR JOSÉ MONTEIRO FONSECA (PADRE PARAÍSO) - INEP: 147711
UPDATE schools 
SET inep_code = '147711' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOSÉ MONTEIRO FONSECA' 
  AND UPPER(TRIM(city)) = 'PADRE PARAÍSO' 
  AND inep_code IS NULL;

-- EE BENJAMIM DA CUNHA (PAVÃO) - INEP: 147729
UPDATE schools 
SET inep_code = '147729' 
WHERE UPPER(TRIM(name)) = 'EE BENJAMIM DA CUNHA' 
  AND UPPER(TRIM(city)) = 'PAVÃO' 
  AND inep_code IS NULL;

-- EE CAIO NÉLSON DE SENA (PAVÃO) - INEP: 147737
UPDATE schools 
SET inep_code = '147737' 
WHERE UPPER(TRIM(name)) = 'EE CAIO NÉLSON DE SENA' 
  AND UPPER(TRIM(city)) = 'PAVÃO' 
  AND inep_code IS NULL;

-- EE DO POVOADO DE LIMEIRA (PAVÃO) - INEP: 147753
UPDATE schools 
SET inep_code = '147753' 
WHERE UPPER(TRIM(name)) = 'EE DO POVOADO DE LIMEIRA' 
  AND UPPER(TRIM(city)) = 'PAVÃO' 
  AND inep_code IS NULL;

-- EE DOUTOR TRISTÃO DA CUNHA (PESCADOR) - INEP: 147788
UPDATE schools 
SET inep_code = '147788' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR TRISTÃO DA CUNHA' 
  AND UPPER(TRIM(city)) = 'PESCADOR' 
  AND inep_code IS NULL;

-- EE ALONZO BARBUDA (PONTO DOS VOLANTES) - INEP: 147010
UPDATE schools 
SET inep_code = '147010' 
WHERE UPPER(TRIM(name)) = 'EE ALONZO BARBUDA' 
  AND UPPER(TRIM(city)) = 'PONTO DOS VOLANTES' 
  AND inep_code IS NULL;

-- EE DE ENSINO MÉDIO (PONTO DOS VOLANTES) - INEP: 372080
UPDATE schools 
SET inep_code = '372080' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' 
  AND UPPER(TRIM(city)) = 'PONTO DOS VOLANTES' 
  AND inep_code IS NULL;

-- EE SANTANA DO ARAÇUAÍ (PONTO DOS VOLANTES) - INEP: 147028
UPDATE schools 
SET inep_code = '147028' 
WHERE UPPER(TRIM(name)) = 'EE SANTANA DO ARAÇUAÍ' 
  AND UPPER(TRIM(city)) = 'PONTO DOS VOLANTES' 
  AND inep_code IS NULL;

-- EE CLÁUDIO MANOEL (POTÉ) - INEP: 147796
UPDATE schools 
SET inep_code = '147796' 
WHERE UPPER(TRIM(name)) = 'EE CLÁUDIO MANOEL' 
  AND UPPER(TRIM(city)) = 'POTÉ' 
  AND inep_code IS NULL;

-- EE JOÃO FERREIRA DE OLIVEIRA (POTÉ) - INEP: 147818
UPDATE schools 
SET inep_code = '147818' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO FERREIRA DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'POTÉ' 
  AND inep_code IS NULL;

-- EE JOSÉ ARAUJO FONSECA (POTÉ) - INEP: 147834
UPDATE schools 
SET inep_code = '147834' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ ARAUJO FONSECA' 
  AND UPPER(TRIM(city)) = 'POTÉ' 
  AND inep_code IS NULL;

-- EE RIBEIRÃO DE SANTA CRUZ (POTÉ) - INEP: 147826
UPDATE schools 
SET inep_code = '147826' 
WHERE UPPER(TRIM(name)) = 'EE RIBEIRÃO DE SANTA CRUZ' 
  AND UPPER(TRIM(city)) = 'POTÉ' 
  AND inep_code IS NULL;

-- EE VEREADOR SEBASTIÃO MAGALHÃES (POTÉ) - INEP: 147869
UPDATE schools 
SET inep_code = '147869' 
WHERE UPPER(TRIM(name)) = 'EE VEREADOR SEBASTIÃO MAGALHÃES' 
  AND UPPER(TRIM(city)) = 'POTÉ' 
  AND inep_code IS NULL;

-- EE EUCLIDES SILVEIRA TOLENTINO (SANTA HELENA DE MINAS) - INEP: 146455
UPDATE schools 
SET inep_code = '146455' 
WHERE UPPER(TRIM(name)) = 'EE EUCLIDES SILVEIRA TOLENTINO' 
  AND UPPER(TRIM(city)) = 'SANTA HELENA DE MINAS' 
  AND inep_code IS NULL;

-- EE INDÍGENA MAXAKALI (SANTA HELENA DE MINAS) - INEP: 269859
UPDATE schools 
SET inep_code = '269859' 
WHERE UPPER(TRIM(name)) = 'EE INDÍGENA MAXAKALI' 
  AND UPPER(TRIM(city)) = 'SANTA HELENA DE MINAS' 
  AND inep_code IS NULL;

-- EE RAUL RODRIGUES SALOMÃO (SANTA HELENA DE MINAS) - INEP: 146447
UPDATE schools 
SET inep_code = '146447' 
WHERE UPPER(TRIM(name)) = 'EE RAUL RODRIGUES SALOMÃO' 
  AND UPPER(TRIM(city)) = 'SANTA HELENA DE MINAS' 
  AND inep_code IS NULL;

-- EE DE SERRA DOS AIMORÉS (SERRA DOS AIMORÉS) - INEP: 147893
UPDATE schools 
SET inep_code = '147893' 
WHERE UPPER(TRIM(name)) = 'EE DE SERRA DOS AIMORÉS' 
  AND UPPER(TRIM(city)) = 'SERRA DOS AIMORÉS' 
  AND inep_code IS NULL;

-- EE PEDRO GONZAGA (SERRA DOS AIMORÉS) - INEP: 147923
UPDATE schools 
SET inep_code = '147923' 
WHERE UPPER(TRIM(name)) = 'EE PEDRO GONZAGA' 
  AND UPPER(TRIM(city)) = 'SERRA DOS AIMORÉS' 
  AND inep_code IS NULL;

-- EE VANDA REUTER (SERRA DOS AIMORÉS) - INEP: 147931
UPDATE schools 
SET inep_code = '147931' 
WHERE UPPER(TRIM(name)) = 'EE VANDA REUTER' 
  AND UPPER(TRIM(city)) = 'SERRA DOS AIMORÉS' 
  AND inep_code IS NULL;

-- EE DE SETÚBAL (SETUBINHA) - INEP: 147354
UPDATE schools 
SET inep_code = '147354' 
WHERE UPPER(TRIM(name)) = 'EE DE SETÚBAL' 
  AND UPPER(TRIM(city)) = 'SETUBINHA' 
  AND inep_code IS NULL;

-- EE GENTIL BARBOSA SENA (SETUBINHA) - INEP: 147320
UPDATE schools 
SET inep_code = '147320' 
WHERE UPPER(TRIM(name)) = 'EE GENTIL BARBOSA SENA' 
  AND UPPER(TRIM(city)) = 'SETUBINHA' 
  AND inep_code IS NULL;

-- EE MADALENA PEREIRA JORGE (SETUBINHA) - INEP: 326101
UPDATE schools 
SET inep_code = '326101' 
WHERE UPPER(TRIM(name)) = 'EE MADALENA PEREIRA JORGE' 
  AND UPPER(TRIM(city)) = 'SETUBINHA' 
  AND inep_code IS NULL;

-- EE NAGIB MAHMUD NÉDIR (SETUBINHA) - INEP: 147362
UPDATE schools 
SET inep_code = '147362' 
WHERE UPPER(TRIM(name)) = 'EE NAGIB MAHMUD NÉDIR' 
  AND UPPER(TRIM(city)) = 'SETUBINHA' 
  AND inep_code IS NULL;

-- EE PROFESSORA LEONOR ESTEVES LIMA (SETUBINHA) - INEP: 147338
UPDATE schools 
SET inep_code = '147338' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA LEONOR ESTEVES LIMA' 
  AND UPPER(TRIM(city)) = 'SETUBINHA' 
  AND inep_code IS NULL;

-- EE SOTURNO DA MATA (SETUBINHA) - INEP: 240818
UPDATE schools 
SET inep_code = '240818' 
WHERE UPPER(TRIM(name)) = 'EE SOTURNO DA MATA' 
  AND UPPER(TRIM(city)) = 'SETUBINHA' 
  AND inep_code IS NULL;

-- CEP - CENTRO DE EDUCAÇÃO PROFISSIONAL PAULO VIANA (TEÓFILO OTONI) - INEP: 298913
UPDATE schools 
SET inep_code = '298913' 
WHERE UPPER(TRIM(name)) = 'CEP - CENTRO DE EDUCAÇÃO PROFISSIONAL PAULO VIANA' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- CESEC  DE TEÓFILO OTONI (TEÓFILO OTONI) - INEP: 148199
UPDATE schools 
SET inep_code = '148199' 
WHERE UPPER(TRIM(name)) = 'CESEC DE TEÓFILO OTONI' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- COLÉGIO TIRADENTES PMMG (TEÓFILO OTONI) - INEP: 281204
UPDATE schools 
SET inep_code = '281204' 
WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE ALBERTO BARREIROS (TEÓFILO OTONI) - INEP: 147940
UPDATE schools 
SET inep_code = '147940' 
WHERE UPPER(TRIM(name)) = 'EE ALBERTO BARREIROS' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE ALFREDO SÁ (TEÓFILO OTONI) - INEP: 147966
UPDATE schools 
SET inep_code = '147966' 
WHERE UPPER(TRIM(name)) = 'EE ALFREDO SÁ' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE ALTINO BARBOSA (TEÓFILO OTONI) - INEP: 147982
UPDATE schools 
SET inep_code = '147982' 
WHERE UPPER(TRIM(name)) = 'EE ALTINO BARBOSA' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE ARTUR BERNARDES (TEÓFILO OTONI) - INEP: 148415
UPDATE schools 
SET inep_code = '148415' 
WHERE UPPER(TRIM(name)) = 'EE ARTUR BERNARDES' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE CLOTILDE ONOFRI DE CAMPOS (TEÓFILO OTONI) - INEP: 148059
UPDATE schools 
SET inep_code = '148059' 
WHERE UPPER(TRIM(name)) = 'EE CLOTILDE ONOFRI DE CAMPOS' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE DA CABECEIRA DE SÃO PEDRO (TEÓFILO OTONI) - INEP: 148164
UPDATE schools 
SET inep_code = '148164' 
WHERE UPPER(TRIM(name)) = 'EE DA CABECEIRA DE SÃO PEDRO' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE DE BARRA DO CEDRO (TEÓFILO OTONI) - INEP: 148121
UPDATE schools 
SET inep_code = '148121' 
WHERE UPPER(TRIM(name)) = 'EE DE BARRA DO CEDRO' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE DE ENSINO FUNDAMENTAL E MÉDIO (TEÓFILO OTONI) - INEP: 326828
UPDATE schools 
SET inep_code = '326828' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL E MÉDIO' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE DE LIBERDADE (TEÓFILO OTONI) - INEP: 148229
UPDATE schools 
SET inep_code = '148229' 
WHERE UPPER(TRIM(name)) = 'EE DE LIBERDADE' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE DE MUCURI (TEÓFILO OTONI) - INEP: 148431
UPDATE schools 
SET inep_code = '148431' 
WHERE UPPER(TRIM(name)) = 'EE DE MUCURI' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE DE PEDRO VERSIANI (TEÓFILO OTONI) - INEP: 148407
UPDATE schools 
SET inep_code = '148407' 
WHERE UPPER(TRIM(name)) = 'EE DE PEDRO VERSIANI' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE DEPUTADO GERALDO LANDI (TEÓFILO OTONI) - INEP: 148288
UPDATE schools 
SET inep_code = '148288' 
WHERE UPPER(TRIM(name)) = 'EE DEPUTADO GERALDO LANDI' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE DOUTOR ANTÔNIO JACINTO PIMENTA (TEÓFILO OTONI) - INEP: 148300
UPDATE schools 
SET inep_code = '148300' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR ANTÔNIO JACINTO PIMENTA' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE DOUTOR FELIPE MOREIRA CALDAS (TEÓFILO OTONI) - INEP: 148318
UPDATE schools 
SET inep_code = '148318' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR FELIPE MOREIRA CALDAS' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE DOUTOR MANOEL ESTEVES OTONI (TEÓFILO OTONI) - INEP: 148334
UPDATE schools 
SET inep_code = '148334' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR MANOEL ESTEVES OTONI' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE DOUTOR WALDEMAR NEVES DA ROCHA (TEÓFILO OTONI) - INEP: 148113
UPDATE schools 
SET inep_code = '148113' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR WALDEMAR NEVES DA ROCHA' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE FREI ANTELMO KROPMAN (TEÓFILO OTONI) - INEP: 148156
UPDATE schools 
SET inep_code = '148156' 
WHERE UPPER(TRIM(name)) = 'EE FREI ANTELMO KROPMAN' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE FREI BRÁS BERTEN (TEÓFILO OTONI) - INEP: 148008
UPDATE schools 
SET inep_code = '148008' 
WHERE UPPER(TRIM(name)) = 'EE FREI BRÁS BERTEN' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE GLÓRIA PENCHEL (TEÓFILO OTONI) - INEP: 148041
UPDATE schools 
SET inep_code = '148041' 
WHERE UPPER(TRIM(name)) = 'EE GLÓRIA PENCHEL' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE IONE LEWICK CUNHA MELO (TEÓFILO OTONI) - INEP: 148075
UPDATE schools 
SET inep_code = '148075' 
WHERE UPPER(TRIM(name)) = 'EE IONE LEWICK CUNHA MELO' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE IRMÃ ARCÂNGELA (TEÓFILO OTONI) - INEP: 148130
UPDATE schools 
SET inep_code = '148130' 
WHERE UPPER(TRIM(name)) = 'EE IRMÃ ARCÂNGELA' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE JOSÉ EXPEDITO SOUZA CAMPOS (TEÓFILO OTONI) - INEP: 148440
UPDATE schools 
SET inep_code = '148440' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ EXPEDITO SOUZA CAMPOS' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE MAGID LAUAR (TEÓFILO OTONI) - INEP: 148261
UPDATE schools 
SET inep_code = '148261' 
WHERE UPPER(TRIM(name)) = 'EE MAGID LAUAR' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE NOSSA SENHORA DE FÁTIMA (TEÓFILO OTONI) - INEP: 148342
UPDATE schools 
SET inep_code = '148342' 
WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DE FÁTIMA' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE PASTOR HOLLERBACH (TEÓFILO OTONI) - INEP: 148024
UPDATE schools 
SET inep_code = '148024' 
WHERE UPPER(TRIM(name)) = 'EE PASTOR HOLLERBACH' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE PREFEITO GERMANO AUGUSTO DE SOUZA (TEÓFILO OTONI) - INEP: 148369
UPDATE schools 
SET inep_code = '148369' 
WHERE UPPER(TRIM(name)) = 'EE PREFEITO GERMANO AUGUSTO DE SOUZA' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE PRESIDENTE TANCREDO NEVES (TEÓFILO OTONI) - INEP: 148351
UPDATE schools 
SET inep_code = '148351' 
WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE TANCREDO NEVES' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE PROFESSOR PATRÍCIO FERREIRA GOMES (TEÓFILO OTONI) - INEP: 147958
UPDATE schools 
SET inep_code = '147958' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR PATRÍCIO FERREIRA GOMES' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE PROFESSORA MARIA LÚCIA GOMES RIBEIRO (TEÓFILO OTONI) - INEP: 338834
UPDATE schools 
SET inep_code = '338834' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA LÚCIA GOMES RIBEIRO' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE RUBEM TOMICH (TEÓFILO OTONI) - INEP: 330582
UPDATE schools 
SET inep_code = '330582' 
WHERE UPPER(TRIM(name)) = 'EE RUBEM TOMICH' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE SÃO SEBASTIÃO (TEÓFILO OTONI) - INEP: 148016
UPDATE schools 
SET inep_code = '148016' 
WHERE UPPER(TRIM(name)) = 'EE SÃO SEBASTIÃO' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE SEBASTIÃO ALVES DA CRUZ (TEÓFILO OTONI) - INEP: 349330
UPDATE schools 
SET inep_code = '349330' 
WHERE UPPER(TRIM(name)) = 'EE SEBASTIÃO ALVES DA CRUZ' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE SEBASTIÃO RAMOS (TEÓFILO OTONI) - INEP: 148032
UPDATE schools 
SET inep_code = '148032' 
WHERE UPPER(TRIM(name)) = 'EE SEBASTIÃO RAMOS' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE TRISTÃO DA CUNHA (TEÓFILO OTONI) - INEP: 148091
UPDATE schools 
SET inep_code = '148091' 
WHERE UPPER(TRIM(name)) = 'EE TRISTÃO DA CUNHA' 
  AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' 
  AND inep_code IS NULL;

-- EE APARÍCIO ALVES MURTA (UMBURATIBA) - INEP: 148458
UPDATE schools 
SET inep_code = '148458' 
WHERE UPPER(TRIM(name)) = 'EE APARÍCIO ALVES MURTA' 
  AND UPPER(TRIM(city)) = 'UMBURATIBA' 
  AND inep_code IS NULL;

-- EE DEPUTADO EDSON RESENDE (ASTOLFO DUTRA) - INEP: 180769
UPDATE schools 
SET inep_code = '180769' 
WHERE UPPER(TRIM(name)) = 'EE DEPUTADO EDSON RESENDE' 
  AND UPPER(TRIM(city)) = 'ASTOLFO DUTRA' 
  AND inep_code IS NULL;

-- EE OLINTO ALMADA (ASTOLFO DUTRA) - INEP: 180751
UPDATE schools 
SET inep_code = '180751' 
WHERE UPPER(TRIM(name)) = 'EE OLINTO ALMADA' 
  AND UPPER(TRIM(city)) = 'ASTOLFO DUTRA' 
  AND inep_code IS NULL;

-- EE PROFESSOR SOUZA PRIMO (ASTOLFO DUTRA) - INEP: 180742
UPDATE schools 
SET inep_code = '180742' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR SOUZA PRIMO' 
  AND UPPER(TRIM(city)) = 'ASTOLFO DUTRA' 
  AND inep_code IS NULL;

-- EE JOSÉ ALVES DE MAGALHÃES (BRÁS PIRES) - INEP: 180785
UPDATE schools 
SET inep_code = '180785' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ ALVES DE MAGALHÃES' 
  AND UPPER(TRIM(city)) = 'BRÁS PIRES' 
  AND inep_code IS NULL;

-- EE SÃO LUÍS (BRÁS PIRES) - INEP: 180793
UPDATE schools 
SET inep_code = '180793' 
WHERE UPPER(TRIM(name)) = 'EE SÃO LUÍS' 
  AND UPPER(TRIM(city)) = 'BRÁS PIRES' 
  AND inep_code IS NULL;

-- EE EMÍLIO JARDIM (COIMBRA) - INEP: 128635
UPDATE schools 
SET inep_code = '128635' 
WHERE UPPER(TRIM(name)) = 'EE EMÍLIO JARDIM' 
  AND UPPER(TRIM(city)) = 'COIMBRA' 
  AND inep_code IS NULL;

-- EE PROFESSOR BIOLKINO DE ANDRADE (DIVINÉSIA) - INEP: 180807
UPDATE schools 
SET inep_code = '180807' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR BIOLKINO DE ANDRADE' 
  AND UPPER(TRIM(city)) = 'DIVINÉSIA' 
  AND inep_code IS NULL;

-- EE CORINA VIEIRA HENRIQUES (DONA EUSÉBIA) - INEP: 180831
UPDATE schools 
SET inep_code = '180831' 
WHERE UPPER(TRIM(name)) = 'EE CORINA VIEIRA HENRIQUES' 
  AND UPPER(TRIM(city)) = 'DONA EUSÉBIA' 
  AND inep_code IS NULL;

-- EE DOMICIANO ESTEVES (DONA EUSÉBIA) - INEP: 180815
UPDATE schools 
SET inep_code = '180815' 
WHERE UPPER(TRIM(name)) = 'EE DOMICIANO ESTEVES' 
  AND UPPER(TRIM(city)) = 'DONA EUSÉBIA' 
  AND inep_code IS NULL;

-- EE TEREZINHA PEREIRA (DORES DO TURVO) - INEP: 180858
UPDATE schools 
SET inep_code = '180858' 
WHERE UPPER(TRIM(name)) = 'EE TEREZINHA PEREIRA' 
  AND UPPER(TRIM(city)) = 'DORES DO TURVO' 
  AND inep_code IS NULL;

-- EE DOM FRANCISCO DAS CHAGAS (ERVÁLIA) - INEP: 180904
UPDATE schools 
SET inep_code = '180904' 
WHERE UPPER(TRIM(name)) = 'EE DOM FRANCISCO DAS CHAGAS' 
  AND UPPER(TRIM(city)) = 'ERVÁLIA' 
  AND inep_code IS NULL;

-- EE MONSENHOR RODOLFO (ERVÁLIA) - INEP: 180912
UPDATE schools 
SET inep_code = '180912' 
WHERE UPPER(TRIM(name)) = 'EE MONSENHOR RODOLFO' 
  AND UPPER(TRIM(city)) = 'ERVÁLIA' 
  AND inep_code IS NULL;

-- EE PROFESSOR DAVID PROCÓPIO (ERVÁLIA) - INEP: 180891
UPDATE schools 
SET inep_code = '180891' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR DAVID PROCÓPIO' 
  AND UPPER(TRIM(city)) = 'ERVÁLIA' 
  AND inep_code IS NULL;

-- EE JOSÉ ALVAREZ FILHO (GUARANI) - INEP: 215384
UPDATE schools 
SET inep_code = '215384' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ ALVAREZ FILHO' 
  AND UPPER(TRIM(city)) = 'GUARANI' 
  AND inep_code IS NULL;

-- EE PROFESSOR ALBERTO PACHECO (GUARANI) - INEP: 181030
UPDATE schools 
SET inep_code = '181030' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ALBERTO PACHECO' 
  AND UPPER(TRIM(city)) = 'GUARANI' 
  AND inep_code IS NULL;

-- EE CORONEL JOAQUIM MARTINS (GUIDOVAL) - INEP: 181102
UPDATE schools 
SET inep_code = '181102' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL JOAQUIM MARTINS' 
  AND UPPER(TRIM(city)) = 'GUIDOVAL' 
  AND inep_code IS NULL;

-- EE MARIANA DE PAIVA (GUIDOVAL) - INEP: 181137
UPDATE schools 
SET inep_code = '181137' 
WHERE UPPER(TRIM(name)) = 'EE MARIANA DE PAIVA' 
  AND UPPER(TRIM(city)) = 'GUIDOVAL' 
  AND inep_code IS NULL;

-- EE CASTORINA GOMES SOARES (GUIRICEMA) - INEP: 181200
UPDATE schools 
SET inep_code = '181200' 
WHERE UPPER(TRIM(name)) = 'EE CASTORINA GOMES SOARES' 
  AND UPPER(TRIM(city)) = 'GUIRICEMA' 
  AND inep_code IS NULL;

-- EE GALDINO LEOCÁDIO (GUIRICEMA) - INEP: 181234
UPDATE schools 
SET inep_code = '181234' 
WHERE UPPER(TRIM(name)) = 'EE GALDINO LEOCÁDIO' 
  AND UPPER(TRIM(city)) = 'GUIRICEMA' 
  AND inep_code IS NULL;

-- EE PREFEITO ANTÔNIO ARRUDA (GUIRICEMA) - INEP: 181188
UPDATE schools 
SET inep_code = '181188' 
WHERE UPPER(TRIM(name)) = 'EE PREFEITO ANTÔNIO ARRUDA' 
  AND UPPER(TRIM(city)) = 'GUIRICEMA' 
  AND inep_code IS NULL;

-- EE JOSÉ MAURÍLIO VALENTE (PAULA CÂNDIDO) - INEP: 181251
UPDATE schools 
SET inep_code = '181251' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ MAURÍLIO VALENTE' 
  AND UPPER(TRIM(city)) = 'PAULA CÂNDIDO' 
  AND inep_code IS NULL;

-- EE PROFESSOR SAMUEL JOÃO DE DEUS (PAULA CÂNDIDO) - INEP: 181277
UPDATE schools 
SET inep_code = '181277' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR SAMUEL JOÃO DE DEUS' 
  AND UPPER(TRIM(city)) = 'PAULA CÂNDIDO' 
  AND inep_code IS NULL;

-- EE AURÉLIO BENTO SALGADO (PIRAÚBA) - INEP: 181307
UPDATE schools 
SET inep_code = '181307' 
WHERE UPPER(TRIM(name)) = 'EE AURÉLIO BENTO SALGADO' 
  AND UPPER(TRIM(city)) = 'PIRAÚBA' 
  AND inep_code IS NULL;

-- EE LAFAYETE MAURÍCIO LOPES (PIRAÚBA) - INEP: 181366
UPDATE schools 
SET inep_code = '181366' 
WHERE UPPER(TRIM(name)) = 'EE LAFAYETE MAURÍCIO LOPES' 
  AND UPPER(TRIM(city)) = 'PIRAÚBA' 
  AND inep_code IS NULL;

-- EE PROFESSORA FRANCISCA PEREIRA RODRIGUES (PIRAÚBA) - INEP: 181382
UPDATE schools 
SET inep_code = '181382' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA FRANCISCA PEREIRA RODRIGUES' 
  AND UPPER(TRIM(city)) = 'PIRAÚBA' 
  AND inep_code IS NULL;

-- EE ANTÔNIO LUCAS MARTINS (PRESIDENTE BERNARDES) - INEP: 181404
UPDATE schools 
SET inep_code = '181404' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO LUCAS MARTINS' 
  AND UPPER(TRIM(city)) = 'PRESIDENTE BERNARDES' 
  AND inep_code IS NULL;

-- EE GOVERNADOR CLÓVIS SALGADO (PRESIDENTE BERNARDES) - INEP: 181421
UPDATE schools 
SET inep_code = '181421' 
WHERE UPPER(TRIM(name)) = 'EE GOVERNADOR CLÓVIS SALGADO' 
  AND UPPER(TRIM(city)) = 'PRESIDENTE BERNARDES' 
  AND inep_code IS NULL;

-- EE PADRE VICENTE CARVALHO (PRESIDENTE BERNARDES) - INEP: 181412
UPDATE schools 
SET inep_code = '181412' 
WHERE UPPER(TRIM(name)) = 'EE PADRE VICENTE CARVALHO' 
  AND UPPER(TRIM(city)) = 'PRESIDENTE BERNARDES' 
  AND inep_code IS NULL;

-- EE PROFESSOR JOSÉ BORGES DE MORAIS (RIO POMBA) - INEP: 181498
UPDATE schools 
SET inep_code = '181498' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOSÉ BORGES DE MORAIS' 
  AND UPPER(TRIM(city)) = 'RIO POMBA' 
  AND inep_code IS NULL;

-- EE MÁRCIO NICOLATO (RODEIRO) - INEP: 181528
UPDATE schools 
SET inep_code = '181528' 
WHERE UPPER(TRIM(name)) = 'EE MÁRCIO NICOLATO' 
  AND UPPER(TRIM(city)) = 'RODEIRO' 
  AND inep_code IS NULL;

-- EE ÁLVARO GIESTA (SÃO GERALDO) - INEP: 181536
UPDATE schools 
SET inep_code = '181536' 
WHERE UPPER(TRIM(name)) = 'EE ÁLVARO GIESTA' 
  AND UPPER(TRIM(city)) = 'SÃO GERALDO' 
  AND inep_code IS NULL;

-- EE MINISTRO ALOÍSIO COSTA (SÃO GERALDO) - INEP: 181579
UPDATE schools 
SET inep_code = '181579' 
WHERE UPPER(TRIM(name)) = 'EE MINISTRO ALOÍSIO COSTA' 
  AND UPPER(TRIM(city)) = 'SÃO GERALDO' 
  AND inep_code IS NULL;

-- EE PROFESSOR ORMINDO DE SOUZA LIMA (SÃO GERALDO) - INEP: 181544
UPDATE schools 
SET inep_code = '181544' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ORMINDO DE SOUZA LIMA' 
  AND UPPER(TRIM(city)) = 'SÃO GERALDO' 
  AND inep_code IS NULL;

-- EE PROFESSOR CÍCERO TORRES GALINDO (SENADOR FIRMINO) - INEP: 181609
UPDATE schools 
SET inep_code = '181609' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR CÍCERO TORRES GALINDO' 
  AND UPPER(TRIM(city)) = 'SENADOR FIRMINO' 
  AND inep_code IS NULL;

-- EE SANTO ANTÔNIO (SILVEIRÂNIA) - INEP: 181641
UPDATE schools 
SET inep_code = '181641' 
WHERE UPPER(TRIM(name)) = 'EE SANTO ANTÔNIO' 
  AND UPPER(TRIM(city)) = 'SILVEIRÂNIA' 
  AND inep_code IS NULL;

-- EE MENELICK DE CARVALHO (TABULEIRO) - INEP: 181692
UPDATE schools 
SET inep_code = '181692' 
WHERE UPPER(TRIM(name)) = 'EE MENELICK DE CARVALHO' 
  AND UPPER(TRIM(city)) = 'TABULEIRO' 
  AND inep_code IS NULL;

-- EE CAPITAO ANTONIO PINTO DE MIRANDA (TOCANTINS) - INEP: 181731
UPDATE schools 
SET inep_code = '181731' 
WHERE UPPER(TRIM(name)) = 'EE CAPITAO ANTONIO PINTO DE MIRANDA' 
  AND UPPER(TRIM(city)) = 'TOCANTINS' 
  AND inep_code IS NULL;

-- EE DR JOÃO PINTO (TOCANTINS) - INEP: 181854
UPDATE schools 
SET inep_code = '181854' 
WHERE UPPER(TRIM(name)) = 'EE DR JOÃO PINTO' 
  AND UPPER(TRIM(city)) = 'TOCANTINS' 
  AND inep_code IS NULL;

-- EE PROFESSOR JOÃO LOYOLA (TOCANTINS) - INEP: 181757
UPDATE schools 
SET inep_code = '181757' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOÃO LOYOLA' 
  AND UPPER(TRIM(city)) = 'TOCANTINS' 
  AND inep_code IS NULL;

-- CESEC PROFESSOR JOSÉ CARNEIRO DE CASTRO (UBÁ) - INEP: 182028
UPDATE schools 
SET inep_code = '182028' 
WHERE UPPER(TRIM(name)) = 'CESEC PROFESSOR JOSÉ CARNEIRO DE CASTRO' 
  AND UPPER(TRIM(city)) = 'UBÁ' 
  AND inep_code IS NULL;

-- COLÉGIO TIRADENTES DA PMMG - CTPM - UNIDADE CÂNDIDO MARTINS DE OLIVEIRA (UBÁ) - INEP: 369985
UPDATE schools 
SET inep_code = '369985' 
WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES DA PMMG - CTPM - UNIDADE CÂNDIDO MARTINS DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'UBÁ' 
  AND inep_code IS NULL;

-- EE BARÃO DO RIO BRANCO (UBÁ) - INEP: 182109
UPDATE schools 
SET inep_code = '182109' 
WHERE UPPER(TRIM(name)) = 'EE BARÃO DO RIO BRANCO' 
  AND UPPER(TRIM(city)) = 'UBÁ' 
  AND inep_code IS NULL;

-- EE CESÁRIO ALVIM (UBÁ) - INEP: 181919
UPDATE schools 
SET inep_code = '181919' 
WHERE UPPER(TRIM(name)) = 'EE CESÁRIO ALVIM' 
  AND UPPER(TRIM(city)) = 'UBÁ' 
  AND inep_code IS NULL;

-- EE CORONEL CAMILO SOARES (UBÁ) - INEP: 181935
UPDATE schools 
SET inep_code = '181935' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL CAMILO SOARES' 
  AND UPPER(TRIM(city)) = 'UBÁ' 
  AND inep_code IS NULL;

-- EE CORONEL JOÃO FERREIRA DE ANDRADE (UBÁ) - INEP: 182095
UPDATE schools 
SET inep_code = '182095' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL JOÃO FERREIRA DE ANDRADE' 
  AND UPPER(TRIM(city)) = 'UBÁ' 
  AND inep_code IS NULL;

-- EE CORONEL TEIXEIRA ERVILHA (UBÁ) - INEP: 182087
UPDATE schools 
SET inep_code = '182087' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL TEIXEIRA ERVILHA' 
  AND UPPER(TRIM(city)) = 'UBÁ' 
  AND inep_code IS NULL;

-- EE DEPUTADO CARLOS PEIXOTO FILHO (UBÁ) - INEP: 181951
UPDATE schools 
SET inep_code = '181951' 
WHERE UPPER(TRIM(name)) = 'EE DEPUTADO CARLOS PEIXOTO FILHO' 
  AND UPPER(TRIM(city)) = 'UBÁ' 
  AND inep_code IS NULL;

-- EE DOUTOR JOSÉ JANUÁRIO CARNEIRO (UBÁ) - INEP: 181978
UPDATE schools 
SET inep_code = '181978' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR JOSÉ JANUÁRIO CARNEIRO' 
  AND UPPER(TRIM(city)) = 'UBÁ' 
  AND inep_code IS NULL;

-- EE DOUTOR LEVINDO COELHO (UBÁ) - INEP: 181994
UPDATE schools 
SET inep_code = '181994' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR LEVINDO COELHO' 
  AND UPPER(TRIM(city)) = 'UBÁ' 
  AND inep_code IS NULL;

-- EE EUNICE WEAVER (UBÁ) - INEP: 181820
UPDATE schools 
SET inep_code = '181820' 
WHERE UPPER(TRIM(name)) = 'EE EUNICE WEAVER' 
  AND UPPER(TRIM(city)) = 'UBÁ' 
  AND inep_code IS NULL;

-- EE GOVERNADOR VALADARES (UBÁ) - INEP: 182036
UPDATE schools 
SET inep_code = '182036' 
WHERE UPPER(TRIM(name)) = 'EE GOVERNADOR VALADARES' 
  AND UPPER(TRIM(city)) = 'UBÁ' 
  AND inep_code IS NULL;

-- EE PADRE JOÃOZINHO (UBÁ) - INEP: 182001
UPDATE schools 
SET inep_code = '182001' 
WHERE UPPER(TRIM(name)) = 'EE PADRE JOÃOZINHO' 
  AND UPPER(TRIM(city)) = 'UBÁ' 
  AND inep_code IS NULL;

-- EE PROFESSOR LÍVIO DE CASTRO CARNEIRO (UBÁ) - INEP: 181943
UPDATE schools 
SET inep_code = '181943' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR LÍVIO DE CASTRO CARNEIRO' 
  AND UPPER(TRIM(city)) = 'UBÁ' 
  AND inep_code IS NULL;

-- EE RAUL SOARES (UBÁ) - INEP: 182052
UPDATE schools 
SET inep_code = '182052' 
WHERE UPPER(TRIM(name)) = 'EE RAUL SOARES' 
  AND UPPER(TRIM(city)) = 'UBÁ' 
  AND inep_code IS NULL;

-- EE SÃO JOSÉ (UBÁ) - INEP: 182079
UPDATE schools 
SET inep_code = '182079' 
WHERE UPPER(TRIM(name)) = 'EE SÃO JOSÉ' 
  AND UPPER(TRIM(city)) = 'UBÁ' 
  AND inep_code IS NULL;

-- EE SENADOR LEVINDO COELHO (UBÁ) - INEP: 181862
UPDATE schools 
SET inep_code = '181862' 
WHERE UPPER(TRIM(name)) = 'EE SENADOR LEVINDO COELHO' 
  AND UPPER(TRIM(city)) = 'UBÁ' 
  AND inep_code IS NULL;

-- CESEC PROFESSOR PAULO ROBERTO REIS DE ALMEIDA (VISCONDE DO RIO BRANCO) - INEP: 182214
UPDATE schools 
SET inep_code = '182214' 
WHERE UPPER(TRIM(name)) = 'CESEC PROFESSOR PAULO ROBERTO REIS DE ALMEIDA' 
  AND UPPER(TRIM(city)) = 'VISCONDE DO RIO BRANCO' 
  AND inep_code IS NULL;

-- CONSERVATÓRIO EST MÚSICA PROF THEODOLINDO JOSÉ SOARES (VISCONDE DO RIO BRANCO) - INEP: 182311
UPDATE schools 
SET inep_code = '182311' 
WHERE UPPER(TRIM(name)) = 'CONSERVATÓRIO EST MÚSICA PROF THEODOLINDO JOSÉ SOARES' 
  AND UPPER(TRIM(city)) = 'VISCONDE DO RIO BRANCO' 
  AND inep_code IS NULL;

-- EE CORONEL AVELINO CARDOSO (VISCONDE DO RIO BRANCO) - INEP: 182184
UPDATE schools 
SET inep_code = '182184' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL AVELINO CARDOSO' 
  AND UPPER(TRIM(city)) = 'VISCONDE DO RIO BRANCO' 
  AND inep_code IS NULL;

-- EE DE EDUCAÇÃO ESPECIAL ANTONIO DE GOUVÊA LIMA (VISCONDE DO RIO BRANCO) - INEP: 182176
UPDATE schools 
SET inep_code = '182176' 
WHERE UPPER(TRIM(name)) = 'EE DE EDUCAÇÃO ESPECIAL ANTONIO DE GOUVÊA LIMA' 
  AND UPPER(TRIM(city)) = 'VISCONDE DO RIO BRANCO' 
  AND inep_code IS NULL;

-- EE DOUTOR CELSO MACHADO (VISCONDE DO RIO BRANCO) - INEP: 182222
UPDATE schools 
SET inep_code = '182222' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR CELSO MACHADO' 
  AND UPPER(TRIM(city)) = 'VISCONDE DO RIO BRANCO' 
  AND inep_code IS NULL;

-- EE DR JOÃO BATISTA DE ALMEIDA (VISCONDE DO RIO BRANCO) - INEP: 182249
UPDATE schools 
SET inep_code = '182249' 
WHERE UPPER(TRIM(name)) = 'EE DR JOÃO BATISTA DE ALMEIDA' 
  AND UPPER(TRIM(city)) = 'VISCONDE DO RIO BRANCO' 
  AND inep_code IS NULL;

-- EE LAUDELINA BARANDIER ESMERALDO (VISCONDE DO RIO BRANCO) - INEP: 182290
UPDATE schools 
SET inep_code = '182290' 
WHERE UPPER(TRIM(name)) = 'EE LAUDELINA BARANDIER ESMERALDO' 
  AND UPPER(TRIM(city)) = 'VISCONDE DO RIO BRANCO' 
  AND inep_code IS NULL;

-- EE PADRE ANTÔNIO CORREA (VISCONDE DO RIO BRANCO) - INEP: 182320
UPDATE schools 
SET inep_code = '182320' 
WHERE UPPER(TRIM(name)) = 'EE PADRE ANTÔNIO CORREA' 
  AND UPPER(TRIM(city)) = 'VISCONDE DO RIO BRANCO' 
  AND inep_code IS NULL;

-- EE PREFEITO RUY BOUCHARDET (VISCONDE DO RIO BRANCO) - INEP: 182338
UPDATE schools 
SET inep_code = '182338' 
WHERE UPPER(TRIM(name)) = 'EE PREFEITO RUY BOUCHARDET' 
  AND UPPER(TRIM(city)) = 'VISCONDE DO RIO BRANCO' 
  AND inep_code IS NULL;

-- EE TENENTE ROBERTO SOARES DE SOUZA LIMA (VISCONDE DO RIO BRANCO) - INEP: 182150
UPDATE schools 
SET inep_code = '182150' 
WHERE UPPER(TRIM(name)) = 'EE TENENTE ROBERTO SOARES DE SOUZA LIMA' 
  AND UPPER(TRIM(city)) = 'VISCONDE DO RIO BRANCO' 
  AND inep_code IS NULL;

-- EE JOSÉ ACÁCIO DA SILVA (ÁGUA COMPRIDA) - INEP: 311863
UPDATE schools 
SET inep_code = '311863' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ ACÁCIO DA SILVA' 
  AND UPPER(TRIM(city)) = 'ÁGUA COMPRIDA' 
  AND inep_code IS NULL;

-- EE ARMANDO SANTOS (ARAXÁ) - INEP: 158178
UPDATE schools 
SET inep_code = '158178' 
WHERE UPPER(TRIM(name)) = 'EE ARMANDO SANTOS' 
  AND UPPER(TRIM(city)) = 'ARAXÁ' 
  AND inep_code IS NULL;

-- EE CORONEL JOSÉ ADOLFO AGUIAR (ARAXÁ) - INEP: 158186
UPDATE schools 
SET inep_code = '158186' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL JOSÉ ADOLFO AGUIAR' 
  AND UPPER(TRIM(city)) = 'ARAXÁ' 
  AND inep_code IS NULL;

-- EE DOM JOSÉ GASPAR (ARAXÁ) - INEP: 158224
UPDATE schools 
SET inep_code = '158224' 
WHERE UPPER(TRIM(name)) = 'EE DOM JOSÉ GASPAR' 
  AND UPPER(TRIM(city)) = 'ARAXÁ' 
  AND inep_code IS NULL;

-- EE LOREN RIOS FERES (ARAXÁ) - INEP: 158330
UPDATE schools 
SET inep_code = '158330' 
WHERE UPPER(TRIM(name)) = 'EE LOREN RIOS FERES' 
  AND UPPER(TRIM(city)) = 'ARAXÁ' 
  AND inep_code IS NULL;

-- EE LUIZA DE OLIVEIRA FARIA (ARAXÁ) - INEP: 158267
UPDATE schools 
SET inep_code = '158267' 
WHERE UPPER(TRIM(name)) = 'EE LUIZA DE OLIVEIRA FARIA' 
  AND UPPER(TRIM(city)) = 'ARAXÁ' 
  AND inep_code IS NULL;


COMMIT;
