-- Lote 2 de 7
-- Updates 301 a 600

BEGIN;

-- EE PROFESSOR ANTÔNIO MARCIANO (JOANÉSIA) - INEP: 205621
UPDATE schools 
SET inep_code = '205621' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ANTÔNIO MARCIANO' 
  AND UPPER(TRIM(city)) = 'JOANÉSIA' 
  AND inep_code IS NULL;

-- EE PROFESSOR MANOEL GONÇALVES FERREIRA (JOANÉSIA) - INEP: 191353
UPDATE schools 
SET inep_code = '191353' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR MANOEL GONÇALVES FERREIRA' 
  AND UPPER(TRIM(city)) = 'JOANÉSIA' 
  AND inep_code IS NULL;

-- EE PROFESSORA EUNICE DOS SANTOS COSTA (JOANÉSIA) - INEP: 191345
UPDATE schools 
SET inep_code = '191345' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA EUNICE DOS SANTOS COSTA' 
  AND UPPER(TRIM(city)) = 'JOANÉSIA' 
  AND inep_code IS NULL;

-- EE HORTO BELÉM (MARLIÉRIA) - INEP: 191396
UPDATE schools 
SET inep_code = '191396' 
WHERE UPPER(TRIM(name)) = 'EE HORTO BELÉM' 
  AND UPPER(TRIM(city)) = 'MARLIÉRIA' 
  AND inep_code IS NULL;

-- EE LIBERATO DE CASTRO (MARLIÉRIA) - INEP: 191361
UPDATE schools 
SET inep_code = '191361' 
WHERE UPPER(TRIM(name)) = 'EE LIBERATO DE CASTRO' 
  AND UPPER(TRIM(city)) = 'MARLIÉRIA' 
  AND inep_code IS NULL;

-- EE CAETANO DIAS (MESQUITA) - INEP: 191434
UPDATE schools 
SET inep_code = '191434' 
WHERE UPPER(TRIM(name)) = 'EE CAETANO DIAS' 
  AND UPPER(TRIM(city)) = 'MESQUITA' 
  AND inep_code IS NULL;

-- EE PRUDENTE DE MORAIS (MESQUITA) - INEP: 191418
UPDATE schools 
SET inep_code = '191418' 
WHERE UPPER(TRIM(name)) = 'EE PRUDENTE DE MORAIS' 
  AND UPPER(TRIM(city)) = 'MESQUITA' 
  AND inep_code IS NULL;

-- EE ALBERTINO FERREIRA DRUMOND (SANTANA DO PARAÍSO) - INEP: 191442
UPDATE schools 
SET inep_code = '191442' 
WHERE UPPER(TRIM(name)) = 'EE ALBERTINO FERREIRA DRUMOND' 
  AND UPPER(TRIM(city)) = 'SANTANA DO PARAÍSO' 
  AND inep_code IS NULL;

-- EE ANTÔNIO LUIZ (SANTANA DO PARAÍSO) - INEP: 191451
UPDATE schools 
SET inep_code = '191451' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO LUIZ' 
  AND UPPER(TRIM(city)) = 'SANTANA DO PARAÍSO' 
  AND inep_code IS NULL;

-- EE HERBERT JOSÉ DE SOUZA BETINHO (SANTANA DO PARAÍSO) - INEP: 330540
UPDATE schools 
SET inep_code = '330540' 
WHERE UPPER(TRIM(name)) = 'EE HERBERT JOSÉ DE SOUZA BETINHO' 
  AND UPPER(TRIM(city)) = 'SANTANA DO PARAÍSO' 
  AND inep_code IS NULL;

-- EE JOAQUIM ELIZIÁRIO DA SILVA (SANTANA DO PARAÍSO) - INEP: 191469
UPDATE schools 
SET inep_code = '191469' 
WHERE UPPER(TRIM(name)) = 'EE JOAQUIM ELIZIÁRIO DA SILVA' 
  AND UPPER(TRIM(city)) = 'SANTANA DO PARAÍSO' 
  AND inep_code IS NULL;

-- EE JOSÉ ROSA DAMASCENO (SANTANA DO PARAÍSO) - INEP: 191426
UPDATE schools 
SET inep_code = '191426' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ ROSA DAMASCENO' 
  AND UPPER(TRIM(city)) = 'SANTANA DO PARAÍSO' 
  AND inep_code IS NULL;

-- EE SALVELINO FERNANDES MADEIRA (SANTANA DO PARAÍSO) - INEP: 191477
UPDATE schools 
SET inep_code = '191477' 
WHERE UPPER(TRIM(name)) = 'EE SALVELINO FERNANDES MADEIRA' 
  AND UPPER(TRIM(city)) = 'SANTANA DO PARAÍSO' 
  AND inep_code IS NULL;

-- EE ANTÔNIO SILVA (TIMÓTEO) - INEP: 191540
UPDATE schools 
SET inep_code = '191540' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO SILVA' 
  AND UPPER(TRIM(city)) = 'TIMÓTEO' 
  AND inep_code IS NULL;

-- EE CAPITÃO EGÍDIO LIMA (TIMÓTEO) - INEP: 191558
UPDATE schools 
SET inep_code = '191558' 
WHERE UPPER(TRIM(name)) = 'EE CAPITÃO EGÍDIO LIMA' 
  AND UPPER(TRIM(city)) = 'TIMÓTEO' 
  AND inep_code IS NULL;

-- EE GETÚLIO VARGAS (TIMÓTEO) - INEP: 191574
UPDATE schools 
SET inep_code = '191574' 
WHERE UPPER(TRIM(name)) = 'EE GETÚLIO VARGAS' 
  AND UPPER(TRIM(city)) = 'TIMÓTEO' 
  AND inep_code IS NULL;

-- EE JOÃO COTTA DE FIGUEIREDO BARCELOS (TIMÓTEO) - INEP: 191663
UPDATE schools 
SET inep_code = '191663' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO COTTA DE FIGUEIREDO BARCELOS' 
  AND UPPER(TRIM(city)) = 'TIMÓTEO' 
  AND inep_code IS NULL;

-- EE JOSÉ FERREIRA MAIA (TIMÓTEO) - INEP: 191655
UPDATE schools 
SET inep_code = '191655' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ FERREIRA MAIA' 
  AND UPPER(TRIM(city)) = 'TIMÓTEO' 
  AND inep_code IS NULL;

-- EE LEÔNCIO DE ARAÚJO (TIMÓTEO) - INEP: 191639
UPDATE schools 
SET inep_code = '191639' 
WHERE UPPER(TRIM(name)) = 'EE LEÔNCIO DE ARAÚJO' 
  AND UPPER(TRIM(city)) = 'TIMÓTEO' 
  AND inep_code IS NULL;

-- EE PROFESSORA ANA LETRO STAACKS (TIMÓTEO) - INEP: 191531
UPDATE schools 
SET inep_code = '191531' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ANA LETRO STAACKS' 
  AND UPPER(TRIM(city)) = 'TIMÓTEO' 
  AND inep_code IS NULL;

-- EE PROFESSORA HAYDÉE DE SOUZA ABREU (TIMÓTEO) - INEP: 326445
UPDATE schools 
SET inep_code = '326445' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA HAYDÉE DE SOUZA ABREU' 
  AND UPPER(TRIM(city)) = 'TIMÓTEO' 
  AND inep_code IS NULL;

-- EE PROFESSORA HILDA DE ARAÚJO OSÓRIO ZAUZA (TIMÓTEO) - INEP: 191566
UPDATE schools 
SET inep_code = '191566' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA HILDA DE ARAÚJO OSÓRIO ZAUZA' 
  AND UPPER(TRIM(city)) = 'TIMÓTEO' 
  AND inep_code IS NULL;

-- EE SÃO SEBASTIÃO (TIMÓTEO) - INEP: 191507
UPDATE schools 
SET inep_code = '191507' 
WHERE UPPER(TRIM(name)) = 'EE SÃO SEBASTIÃO' 
  AND UPPER(TRIM(city)) = 'TIMÓTEO' 
  AND inep_code IS NULL;

-- EE TENENTE JOSÉ LUCIANO (TIMÓTEO) - INEP: 191523
UPDATE schools 
SET inep_code = '191523' 
WHERE UPPER(TRIM(name)) = 'EE TENENTE JOSÉ LUCIANO' 
  AND UPPER(TRIM(city)) = 'TIMÓTEO' 
  AND inep_code IS NULL;

-- EE AFONSO SOARES DE FREITAS (AUGUSTO DE LIMA) - INEP: 140309
UPDATE schools 
SET inep_code = '140309' 
WHERE UPPER(TRIM(name)) = 'EE AFONSO SOARES DE FREITAS' 
  AND UPPER(TRIM(city)) = 'AUGUSTO DE LIMA' 
  AND inep_code IS NULL;

-- EE NOSSA SENHORA DO CARMO (BUENÓPOLIS) - INEP: 140384
UPDATE schools 
SET inep_code = '140384' 
WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DO CARMO' 
  AND UPPER(TRIM(city)) = 'BUENÓPOLIS' 
  AND inep_code IS NULL;

-- EE PADRE LAERTE ESPERANÇA OLIVEIRA (BUENÓPOLIS) - INEP: 140392
UPDATE schools 
SET inep_code = '140392' 
WHERE UPPER(TRIM(name)) = 'EE PADRE LAERTE ESPERANÇA OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'BUENÓPOLIS' 
  AND inep_code IS NULL;

-- EE ALENCASTRO GUIMARÃES (CORINTO) - INEP: 140597
UPDATE schools 
SET inep_code = '140597' 
WHERE UPPER(TRIM(name)) = 'EE ALENCASTRO GUIMARÃES' 
  AND UPPER(TRIM(city)) = 'CORINTO' 
  AND inep_code IS NULL;

-- EE ANTÔNIO VIEIRA MACHADO (CORINTO) - INEP: 140601
UPDATE schools 
SET inep_code = '140601' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO VIEIRA MACHADO' 
  AND UPPER(TRIM(city)) = 'CORINTO' 
  AND inep_code IS NULL;

-- EE DESEMBARGADOR CANEDO (CORINTO) - INEP: 140627
UPDATE schools 
SET inep_code = '140627' 
WHERE UPPER(TRIM(name)) = 'EE DESEMBARGADOR CANEDO' 
  AND UPPER(TRIM(city)) = 'CORINTO' 
  AND inep_code IS NULL;

-- EE JOSÉ BRÍGIDO PEREIRA PEDRA (CORINTO) - INEP: 140619
UPDATE schools 
SET inep_code = '140619' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ BRÍGIDO PEREIRA PEDRA' 
  AND UPPER(TRIM(city)) = 'CORINTO' 
  AND inep_code IS NULL;

-- EE MAJOR CLARINDO DE PAIVA (CORINTO) - INEP: 140651
UPDATE schools 
SET inep_code = '140651' 
WHERE UPPER(TRIM(name)) = 'EE MAJOR CLARINDO DE PAIVA' 
  AND UPPER(TRIM(city)) = 'CORINTO' 
  AND inep_code IS NULL;

-- EE PROFESSORA MARIA AMÁLIA CAMPOS (CORINTO) - INEP: 140686
UPDATE schools 
SET inep_code = '140686' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA AMÁLIA CAMPOS' 
  AND UPPER(TRIM(city)) = 'CORINTO' 
  AND inep_code IS NULL;

-- EE WALDEMAR ARAÚJO (CORINTO) - INEP: 140694
UPDATE schools 
SET inep_code = '140694' 
WHERE UPPER(TRIM(name)) = 'EE WALDEMAR ARAÚJO' 
  AND UPPER(TRIM(city)) = 'CORINTO' 
  AND inep_code IS NULL;

-- CESEC DE CURVELO (CURVELO) - INEP: 346080
UPDATE schools 
SET inep_code = '346080' 
WHERE UPPER(TRIM(name)) = 'CESEC DE CURVELO' 
  AND UPPER(TRIM(city)) = 'CURVELO' 
  AND inep_code IS NULL;

-- COLÉGIO TIRADENTES PMMG - UNIDADE CURVELO (CURVELO) - INEP: 368288
UPDATE schools 
SET inep_code = '368288' 
WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG - UNIDADE CURVELO' 
  AND UPPER(TRIM(city)) = 'CURVELO' 
  AND inep_code IS NULL;

-- EE ANTONINA MASCARENHAS GONZAGA (CURVELO) - INEP: 140864
UPDATE schools 
SET inep_code = '140864' 
WHERE UPPER(TRIM(name)) = 'EE ANTONINA MASCARENHAS GONZAGA' 
  AND UPPER(TRIM(city)) = 'CURVELO' 
  AND inep_code IS NULL;

-- EE BASÍLIO FRANCISCO XAVIER (CURVELO) - INEP: 140899
UPDATE schools 
SET inep_code = '140899' 
WHERE UPPER(TRIM(name)) = 'EE BASÍLIO FRANCISCO XAVIER' 
  AND UPPER(TRIM(city)) = 'CURVELO' 
  AND inep_code IS NULL;

-- EE BOLÍVAR DE FREITAS (CURVELO) - INEP: 140716
UPDATE schools 
SET inep_code = '140716' 
WHERE UPPER(TRIM(name)) = 'EE BOLÍVAR DE FREITAS' 
  AND UPPER(TRIM(city)) = 'CURVELO' 
  AND inep_code IS NULL;

-- EE EURÍPEDES DE PAULA (CURVELO) - INEP: 140767
UPDATE schools 
SET inep_code = '140767' 
WHERE UPPER(TRIM(name)) = 'EE EURÍPEDES DE PAULA' 
  AND UPPER(TRIM(city)) = 'CURVELO' 
  AND inep_code IS NULL;

-- EE INTERVENTOR ALCIDES LINS (CURVELO) - INEP: 140775
UPDATE schools 
SET inep_code = '140775' 
WHERE UPPER(TRIM(name)) = 'EE INTERVENTOR ALCIDES LINS' 
  AND UPPER(TRIM(city)) = 'CURVELO' 
  AND inep_code IS NULL;

-- EE IRMÃ CLARENTINA (CURVELO) - INEP: 140856
UPDATE schools 
SET inep_code = '140856' 
WHERE UPPER(TRIM(name)) = 'EE IRMÃ CLARENTINA' 
  AND UPPER(TRIM(city)) = 'CURVELO' 
  AND inep_code IS NULL;

-- EE IRMÃ RAIMUNDA MARQUES (CURVELO) - INEP: 140848
UPDATE schools 
SET inep_code = '140848' 
WHERE UPPER(TRIM(name)) = 'EE IRMÃ RAIMUNDA MARQUES' 
  AND UPPER(TRIM(city)) = 'CURVELO' 
  AND inep_code IS NULL;

-- EE MAJOR ANTÔNIO SALVO (CURVELO) - INEP: 140791
UPDATE schools 
SET inep_code = '140791' 
WHERE UPPER(TRIM(name)) = 'EE MAJOR ANTÔNIO SALVO' 
  AND UPPER(TRIM(city)) = 'CURVELO' 
  AND inep_code IS NULL;

-- EE MINISTRO ADAUTO LÚCIO CARDOSO (CURVELO) - INEP: 140708
UPDATE schools 
SET inep_code = '140708' 
WHERE UPPER(TRIM(name)) = 'EE MINISTRO ADAUTO LÚCIO CARDOSO' 
  AND UPPER(TRIM(city)) = 'CURVELO' 
  AND inep_code IS NULL;

-- EE PADRE AUGUSTO HORTA (CURVELO) - INEP: 140872
UPDATE schools 
SET inep_code = '140872' 
WHERE UPPER(TRIM(name)) = 'EE PADRE AUGUSTO HORTA' 
  AND UPPER(TRIM(city)) = 'CURVELO' 
  AND inep_code IS NULL;

-- EE SÃO GERALDO (CURVELO) - INEP: 140821
UPDATE schools 
SET inep_code = '140821' 
WHERE UPPER(TRIM(name)) = 'EE SÃO GERALDO' 
  AND UPPER(TRIM(city)) = 'CURVELO' 
  AND inep_code IS NULL;

-- EE SÃO VICENTE DE PAULO (CURVELO) - INEP: 140830
UPDATE schools 
SET inep_code = '140830' 
WHERE UPPER(TRIM(name)) = 'EE SÃO VICENTE DE PAULO' 
  AND UPPER(TRIM(city)) = 'CURVELO' 
  AND inep_code IS NULL;

-- EE SÉRGIO EUGÊNIO DA SILVA (CURVELO) - INEP: 253421
UPDATE schools 
SET inep_code = '253421' 
WHERE UPPER(TRIM(name)) = 'EE SÉRGIO EUGÊNIO DA SILVA' 
  AND UPPER(TRIM(city)) = 'CURVELO' 
  AND inep_code IS NULL;

-- CESEC HUMBERTO JOSÉ ELIAS (FELIXLÂNDIA) - INEP: 218685
UPDATE schools 
SET inep_code = '218685' 
WHERE UPPER(TRIM(name)) = 'CESEC HUMBERTO JOSÉ ELIAS' 
  AND UPPER(TRIM(city)) = 'FELIXLÂNDIA' 
  AND inep_code IS NULL;

-- EE PADRE JOSÉ GONÇALVES DE SOUZA (FELIXLÂNDIA) - INEP: 140953
UPDATE schools 
SET inep_code = '140953' 
WHERE UPPER(TRIM(name)) = 'EE PADRE JOSÉ GONÇALVES DE SOUZA' 
  AND UPPER(TRIM(city)) = 'FELIXLÂNDIA' 
  AND inep_code IS NULL;

-- EE SÃO JOSÉ DO BURITI (FELIXLÂNDIA) - INEP: 140988
UPDATE schools 
SET inep_code = '140988' 
WHERE UPPER(TRIM(name)) = 'EE SÃO JOSÉ DO BURITI' 
  AND UPPER(TRIM(city)) = 'FELIXLÂNDIA' 
  AND inep_code IS NULL;

-- EE DOUTOR PACÍFICO MASCARENHAS (INIMUTABA) - INEP: 141119
UPDATE schools 
SET inep_code = '141119' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR PACÍFICO MASCARENHAS' 
  AND UPPER(TRIM(city)) = 'INIMUTABA' 
  AND inep_code IS NULL;

-- EE NOSSA SENHORA DAS DORES (JOAQUIM FELÍCIO) - INEP: 141178
UPDATE schools 
SET inep_code = '141178' 
WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DAS DORES' 
  AND UPPER(TRIM(city)) = 'JOAQUIM FELÍCIO' 
  AND inep_code IS NULL;

-- EE PREFEITO WALTER COELHO DA ROCHA (MORRO DA GARÇA) - INEP: 312070
UPDATE schools 
SET inep_code = '312070' 
WHERE UPPER(TRIM(name)) = 'EE PREFEITO WALTER COELHO DA ROCHA' 
  AND UPPER(TRIM(city)) = 'MORRO DA GARÇA' 
  AND inep_code IS NULL;

-- EE CARLOS ALEXANDRE DE OLIVEIRA (TRÊS MARIAS) - INEP: 142042
UPDATE schools 
SET inep_code = '142042' 
WHERE UPPER(TRIM(name)) = 'EE CARLOS ALEXANDRE DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'TRÊS MARIAS' 
  AND inep_code IS NULL;

-- EE JOÃO GUIMARÃES ROSA (TRÊS MARIAS) - INEP: 246417
UPDATE schools 
SET inep_code = '246417' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO GUIMARÃES ROSA' 
  AND UPPER(TRIM(city)) = 'TRÊS MARIAS' 
  AND inep_code IS NULL;

-- EE JOSÉ ERMÍRIO DE MORAIS (TRÊS MARIAS) - INEP: 141976
UPDATE schools 
SET inep_code = '141976' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ ERMÍRIO DE MORAIS' 
  AND UPPER(TRIM(city)) = 'TRÊS MARIAS' 
  AND inep_code IS NULL;

-- EE MANOEL PEREIRA DE FREITAS (TRÊS MARIAS) - INEP: 142026
UPDATE schools 
SET inep_code = '142026' 
WHERE UPPER(TRIM(name)) = 'EE MANOEL PEREIRA DE FREITAS' 
  AND UPPER(TRIM(city)) = 'TRÊS MARIAS' 
  AND inep_code IS NULL;

-- EE PRESIDENTE JUSCELINO KUBITSCHEK DE OLIVEIRA (TRÊS MARIAS) - INEP: 141984
UPDATE schools 
SET inep_code = '141984' 
WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE JUSCELINO KUBITSCHEK DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'TRÊS MARIAS' 
  AND inep_code IS NULL;

-- EE IVETA GOMES SANTANA (ANGELÂNDIA) - INEP: 330604
UPDATE schools 
SET inep_code = '330604' 
WHERE UPPER(TRIM(name)) = 'EE IVETA GOMES SANTANA' 
  AND UPPER(TRIM(city)) = 'ANGELÂNDIA' 
  AND inep_code IS NULL;

-- CESEC DE CAPELINHA (CAPELINHA) - INEP: 351032
UPDATE schools 
SET inep_code = '351032' 
WHERE UPPER(TRIM(name)) = 'CESEC DE CAPELINHA' 
  AND UPPER(TRIM(city)) = 'CAPELINHA' 
  AND inep_code IS NULL;

-- EE BENTO ROCHA DE JESUS (CAPELINHA) - INEP: 319376
UPDATE schools 
SET inep_code = '319376' 
WHERE UPPER(TRIM(name)) = 'EE BENTO ROCHA DE JESUS' 
  AND UPPER(TRIM(city)) = 'CAPELINHA' 
  AND inep_code IS NULL;

-- EE DOMINGOS PIMENTA DE FIGUEIREDO (CAPELINHA) - INEP: 205893
UPDATE schools 
SET inep_code = '205893' 
WHERE UPPER(TRIM(name)) = 'EE DOMINGOS PIMENTA DE FIGUEIREDO' 
  AND UPPER(TRIM(city)) = 'CAPELINHA' 
  AND inep_code IS NULL;

-- EE ROSARINHA PIMENTINHA (CAPELINHA) - INEP: 217646
UPDATE schools 
SET inep_code = '217646' 
WHERE UPPER(TRIM(name)) = 'EE ROSARINHA PIMENTINHA' 
  AND UPPER(TRIM(city)) = 'CAPELINHA' 
  AND inep_code IS NULL;

-- EE SEBASTIÃO PEÇANHA DE OLIVEIRA (CAPELINHA) - INEP: 342718
UPDATE schools 
SET inep_code = '342718' 
WHERE UPPER(TRIM(name)) = 'EE SEBASTIÃO PEÇANHA DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'CAPELINHA' 
  AND inep_code IS NULL;

-- EE JULIANA CATARINA DA SILVEIRA (DATAS) - INEP: 254355
UPDATE schools 
SET inep_code = '254355' 
WHERE UPPER(TRIM(name)) = 'EE JULIANA CATARINA DA SILVEIRA' 
  AND UPPER(TRIM(city)) = 'DATAS' 
  AND inep_code IS NULL;

-- EE MESTRA BEZINHA GANDRA (ITAMARANDIBA) - INEP: 217611
UPDATE schools 
SET inep_code = '217611' 
WHERE UPPER(TRIM(name)) = 'EE MESTRA BEZINHA GANDRA' 
  AND UPPER(TRIM(city)) = 'ITAMARANDIBA' 
  AND inep_code IS NULL;

-- EE ERNESTO ALVES DE MENDONÇA (MINAS NOVAS) - INEP: 218448
UPDATE schools 
SET inep_code = '218448' 
WHERE UPPER(TRIM(name)) = 'EE ERNESTO ALVES DE MENDONÇA' 
  AND UPPER(TRIM(city)) = 'MINAS NOVAS' 
  AND inep_code IS NULL;

-- EE JOÃO FERNANDES DE AZEVEDO (MINAS NOVAS) - INEP: 218421
UPDATE schools 
SET inep_code = '218421' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO FERNANDES DE AZEVEDO' 
  AND UPPER(TRIM(city)) = 'MINAS NOVAS' 
  AND inep_code IS NULL;

-- EE SEBASTIÃO GOMES DE ALMEIDA (MINAS NOVAS) - INEP: 217638
UPDATE schools 
SET inep_code = '217638' 
WHERE UPPER(TRIM(name)) = 'EE SEBASTIÃO GOMES DE ALMEIDA' 
  AND UPPER(TRIM(city)) = 'MINAS NOVAS' 
  AND inep_code IS NULL;

-- CESEC SENHORA DA PIEDADE (TURMALINA) - INEP: 218367
UPDATE schools 
SET inep_code = '218367' 
WHERE UPPER(TRIM(name)) = 'CESEC SENHORA DA PIEDADE' 
  AND UPPER(TRIM(city)) = 'TURMALINA' 
  AND inep_code IS NULL;

-- EE PROFESSORA EDITE GOMES (TURMALINA) - INEP: 246344
UPDATE schools 
SET inep_code = '246344' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA EDITE GOMES' 
  AND UPPER(TRIM(city)) = 'TURMALINA' 
  AND inep_code IS NULL;

-- EE SÃO FRANCISCO DE ASSIS (CARMO DO CAJURU) - INEP: 307335
UPDATE schools 
SET inep_code = '307335' 
WHERE UPPER(TRIM(name)) = 'EE SÃO FRANCISCO DE ASSIS' 
  AND UPPER(TRIM(city)) = 'CARMO DO CAJURU' 
  AND inep_code IS NULL;

-- COLÉGIO TIRADENTES PMMG (DIVINÓPOLIS) - INEP: 364592
UPDATE schools 
SET inep_code = '364592' 
WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG' 
  AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' 
  AND inep_code IS NULL;

-- EE ALBERTO SANTOS DUMONT (DIVINÓPOLIS) - INEP: 326992
UPDATE schools 
SET inep_code = '326992' 
WHERE UPPER(TRIM(name)) = 'EE ALBERTO SANTOS DUMONT' 
  AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' 
  AND inep_code IS NULL;

-- EE CARMELO MESQUITA (ITAPECERICA) - INEP: 202851
UPDATE schools 
SET inep_code = '202851' 
WHERE UPPER(TRIM(name)) = 'EE CARMELO MESQUITA' 
  AND UPPER(TRIM(city)) = 'ITAPECERICA' 
  AND inep_code IS NULL;

-- EE IMACULADA CONCEIÇÃO (ITAPECERICA) - INEP: 202762
UPDATE schools 
SET inep_code = '202762' 
WHERE UPPER(TRIM(name)) = 'EE IMACULADA CONCEIÇÃO' 
  AND UPPER(TRIM(city)) = 'ITAPECERICA' 
  AND inep_code IS NULL;

-- EE INDÍGENA PATAXÓ MUÃ MIMATXI (ITAPECERICA) - INEP: 342521
UPDATE schools 
SET inep_code = '342521' 
WHERE UPPER(TRIM(name)) = 'EE INDÍGENA PATAXÓ MUÃ MIMATXI' 
  AND UPPER(TRIM(city)) = 'ITAPECERICA' 
  AND inep_code IS NULL;

-- EE LAMOUNIER GODOFREDO (ITAPECERICA) - INEP: 202843
UPDATE schools 
SET inep_code = '202843' 
WHERE UPPER(TRIM(name)) = 'EE LAMOUNIER GODOFREDO' 
  AND UPPER(TRIM(city)) = 'ITAPECERICA' 
  AND inep_code IS NULL;

-- EE PADRE HERCULANO PAZ (ITAPECERICA) - INEP: 202797
UPDATE schools 
SET inep_code = '202797' 
WHERE UPPER(TRIM(name)) = 'EE PADRE HERCULANO PAZ' 
  AND UPPER(TRIM(city)) = 'ITAPECERICA' 
  AND inep_code IS NULL;

-- EE PEDRO LUIZ (ITAPECERICA) - INEP: 202860
UPDATE schools 
SET inep_code = '202860' 
WHERE UPPER(TRIM(name)) = 'EE PEDRO LUIZ' 
  AND UPPER(TRIM(city)) = 'ITAPECERICA' 
  AND inep_code IS NULL;

-- EE PROFESSOR ALBERTO CORDEIRO DO COUTO (ITAPECERICA) - INEP: 202819
UPDATE schools 
SET inep_code = '202819' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ALBERTO CORDEIRO DO COUTO' 
  AND UPPER(TRIM(city)) = 'ITAPECERICA' 
  AND inep_code IS NULL;

-- EE PROFESSORA MARIA MAGALHÃES PINTO (ITAPECERICA) - INEP: 202801
UPDATE schools 
SET inep_code = '202801' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA MAGALHÃES PINTO' 
  AND UPPER(TRIM(city)) = 'ITAPECERICA' 
  AND inep_code IS NULL;

-- EE PROFESSORA GERALDA MAGELA LEÃO DE MELO (ITAÚNA) - INEP: 330841
UPDATE schools 
SET inep_code = '330841' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA GERALDA MAGELA LEÃO DE MELO' 
  AND UPPER(TRIM(city)) = 'ITAÚNA' 
  AND inep_code IS NULL;

-- EE PROFESSORA GILKA DRUMOND DE FARIA (ITAÚNA) - INEP: 305642
UPDATE schools 
SET inep_code = '305642' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA GILKA DRUMOND DE FARIA' 
  AND UPPER(TRIM(city)) = 'ITAÚNA' 
  AND inep_code IS NULL;

-- EE DONA TILOSA (LAGOA DA PRATA) - INEP: 310506
UPDATE schools 
SET inep_code = '310506' 
WHERE UPPER(TRIM(name)) = 'EE DONA TILOSA' 
  AND UPPER(TRIM(city)) = 'LAGOA DA PRATA' 
  AND inep_code IS NULL;

-- EE JOSÉ TEOTÔNIO DE CASTRO (LAGOA DA PRATA) - INEP: 231746
UPDATE schools 
SET inep_code = '231746' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ TEOTÔNIO DE CASTRO' 
  AND UPPER(TRIM(city)) = 'LAGOA DA PRATA' 
  AND inep_code IS NULL;

-- EE DONA LICA RAPOSO (LUZ) - INEP: 218405
UPDATE schools 
SET inep_code = '218405' 
WHERE UPPER(TRIM(name)) = 'EE DONA LICA RAPOSO' 
  AND UPPER(TRIM(city)) = 'LUZ' 
  AND inep_code IS NULL;

-- EE SANDOVAL DE AZEVEDO (LUZ) - INEP: 310514
UPDATE schools 
SET inep_code = '310514' 
WHERE UPPER(TRIM(name)) = 'EE SANDOVAL DE AZEVEDO' 
  AND UPPER(TRIM(city)) = 'LUZ' 
  AND inep_code IS NULL;

-- CESEC DE NOVA SERRANA (NOVA SERRANA) - INEP: 346195
UPDATE schools 
SET inep_code = '346195' 
WHERE UPPER(TRIM(name)) = 'CESEC DE NOVA SERRANA' 
  AND UPPER(TRIM(city)) = 'NOVA SERRANA' 
  AND inep_code IS NULL;

-- EE MARIA ZELI DINIZ FONSECA (NOVA SERRANA) - INEP: 342530
UPDATE schools 
SET inep_code = '342530' 
WHERE UPPER(TRIM(name)) = 'EE MARIA ZELI DINIZ FONSECA' 
  AND UPPER(TRIM(city)) = 'NOVA SERRANA' 
  AND inep_code IS NULL;

-- EE PADRE LAURO (NOVA SERRANA) - INEP: 326135
UPDATE schools 
SET inep_code = '326135' 
WHERE UPPER(TRIM(name)) = 'EE PADRE LAURO' 
  AND UPPER(TRIM(city)) = 'NOVA SERRANA' 
  AND inep_code IS NULL;

-- EE DESEMBARGADOR CONTINENTINO (OLIVEIRA) - INEP: 203289
UPDATE schools 
SET inep_code = '203289' 
WHERE UPPER(TRIM(name)) = 'EE DESEMBARGADOR CONTINENTINO' 
  AND UPPER(TRIM(city)) = 'OLIVEIRA' 
  AND inep_code IS NULL;

-- EE DOUTOR JOSÉ MARIA LOBATO (OLIVEIRA) - INEP: 203301
UPDATE schools 
SET inep_code = '203301' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR JOSÉ MARIA LOBATO' 
  AND UPPER(TRIM(city)) = 'OLIVEIRA' 
  AND inep_code IS NULL;

-- EE FRANCISCO FERNANDES (OLIVEIRA) - INEP: 203327
UPDATE schools 
SET inep_code = '203327' 
WHERE UPPER(TRIM(name)) = 'EE FRANCISCO FERNANDES' 
  AND UPPER(TRIM(city)) = 'OLIVEIRA' 
  AND inep_code IS NULL;

-- EE MÁRIO CAMPOS E SILVA (OLIVEIRA) - INEP: 203343
UPDATE schools 
SET inep_code = '203343' 
WHERE UPPER(TRIM(name)) = 'EE MÁRIO CAMPOS E SILVA' 
  AND UPPER(TRIM(city)) = 'OLIVEIRA' 
  AND inep_code IS NULL;

-- EE PROFESSOR PINHEIRO CAMPOS (OLIVEIRA) - INEP: 203360
UPDATE schools 
SET inep_code = '203360' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR PINHEIRO CAMPOS' 
  AND UPPER(TRIM(city)) = 'OLIVEIRA' 
  AND inep_code IS NULL;

-- EE SÃO JOÃO BATISTA (OLIVEIRA) - INEP: 203408
UPDATE schools 
SET inep_code = '203408' 
WHERE UPPER(TRIM(name)) = 'EE SÃO JOÃO BATISTA' 
  AND UPPER(TRIM(city)) = 'OLIVEIRA' 
  AND inep_code IS NULL;

-- EE PADRE PAULO (SANTO ANTÔNIO DO MONTE) - INEP: 224014
UPDATE schools 
SET inep_code = '224014' 
WHERE UPPER(TRIM(name)) = 'EE PADRE PAULO' 
  AND UPPER(TRIM(city)) = 'SANTO ANTÔNIO DO MONTE' 
  AND inep_code IS NULL;

-- CESEC MAESTRO CARLOS RIBEIRO DA SILVA (SÃO GONÇALO DO PARÁ) - INEP: 311871
UPDATE schools 
SET inep_code = '311871' 
WHERE UPPER(TRIM(name)) = 'CESEC MAESTRO CARLOS RIBEIRO DA SILVA' 
  AND UPPER(TRIM(city)) = 'SÃO GONÇALO DO PARÁ' 
  AND inep_code IS NULL;

-- EE DE TAPIRAÍ (TAPIRAÍ) - INEP: 307416
UPDATE schools 
SET inep_code = '307416' 
WHERE UPPER(TRIM(name)) = 'EE DE TAPIRAÍ' 
  AND UPPER(TRIM(city)) = 'TAPIRAÍ' 
  AND inep_code IS NULL;

-- EE PROFESSORA ELGE RENAN BRAGA (COROACI) - INEP: 267228
UPDATE schools 
SET inep_code = '267228' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ELGE RENAN BRAGA' 
  AND UPPER(TRIM(city)) = 'COROACI' 
  AND inep_code IS NULL;

-- EE CECÍLIA MEIRELES (GOVERNADOR VALADARES) - INEP: 354716
UPDATE schools 
SET inep_code = '354716' 
WHERE UPPER(TRIM(name)) = 'EE CECÍLIA MEIRELES' 
  AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' 
  AND inep_code IS NULL;

-- EE DO BAIRRO JARDIM DO IPÊ (GOVERNADOR VALADARES) - INEP: 205371
UPDATE schools 
SET inep_code = '205371' 
WHERE UPPER(TRIM(name)) = 'EE DO BAIRRO JARDIM DO IPÊ' 
  AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' 
  AND inep_code IS NULL;

-- EE PROFESSOR DARCY RIBEIRO (GOVERNADOR VALADARES) - INEP: 271241
UPDATE schools 
SET inep_code = '271241' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR DARCY RIBEIRO' 
  AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' 
  AND inep_code IS NULL;

-- EE PROFESSORA MARIA DAMÁZIO DE BARROS MENEZES (GOVERNADOR VALADARES) - INEP: 354724
UPDATE schools 
SET inep_code = '354724' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA DAMÁZIO DE BARROS MENEZES' 
  AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' 
  AND inep_code IS NULL;

-- EE SÃO FRANCISCO DE ASSIS (GOVERNADOR VALADARES) - INEP: 326861
UPDATE schools 
SET inep_code = '326861' 
WHERE UPPER(TRIM(name)) = 'EE SÃO FRANCISCO DE ASSIS' 
  AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' 
  AND inep_code IS NULL;

-- EE SÃO JUDAS TADEU (GOVERNADOR VALADARES) - INEP: 326852
UPDATE schools 
SET inep_code = '326852' 
WHERE UPPER(TRIM(name)) = 'EE SÃO JUDAS TADEU' 
  AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' 
  AND inep_code IS NULL;

-- CESEC DE ITABIRINHA (ITABIRINHA) - INEP: 351423
UPDATE schools 
SET inep_code = '351423' 
WHERE UPPER(TRIM(name)) = 'CESEC DE ITABIRINHA' 
  AND UPPER(TRIM(city)) = 'ITABIRINHA' 
  AND inep_code IS NULL;

-- EE DOUTOR ALAIR ALVES COSTA (NOVA MÓDICA) - INEP: 147532
UPDATE schools 
SET inep_code = '147532' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR ALAIR ALVES COSTA' 
  AND UPPER(TRIM(city)) = 'NOVA MÓDICA' 
  AND inep_code IS NULL;

-- EE NA RESERVA INDÍGENA DE KRENAK (RESPLENDOR) - INEP: 246387
UPDATE schools 
SET inep_code = '246387' 
WHERE UPPER(TRIM(name)) = 'EE NA RESERVA INDÍGENA DE KRENAK' 
  AND UPPER(TRIM(city)) = 'RESPLENDOR' 
  AND inep_code IS NULL;

-- EE TRANQUILINO DIAS BRITO (SÃO JOSÉ DO DIVINO) - INEP: 147885
UPDATE schools 
SET inep_code = '147885' 
WHERE UPPER(TRIM(name)) = 'EE TRANQUILINO DIAS BRITO' 
  AND UPPER(TRIM(city)) = 'SÃO JOSÉ DO DIVINO' 
  AND inep_code IS NULL;

-- EE PRIMEIRO DE JUNHO (TUMIRITINGA) - INEP: 246379
UPDATE schools 
SET inep_code = '246379' 
WHERE UPPER(TRIM(name)) = 'EE PRIMEIRO DE JUNHO' 
  AND UPPER(TRIM(city)) = 'TUMIRITINGA' 
  AND inep_code IS NULL;

-- EE JOSÉ BONIFÁCIO SANTANA (ÁGUA BOA) - INEP: 254045
UPDATE schools 
SET inep_code = '254045' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ BONIFÁCIO SANTANA' 
  AND UPPER(TRIM(city)) = 'ÁGUA BOA' 
  AND inep_code IS NULL;

-- EE INDÍGENA ÃGOHÓ KUÂP PATAXÓ (CARMÉSIA) - INEP: 369802
UPDATE schools 
SET inep_code = '369802' 
WHERE UPPER(TRIM(name)) = 'EE INDÍGENA ÃGOHÓ KUÂP PATAXÓ' 
  AND UPPER(TRIM(city)) = 'CARMÉSIA' 
  AND inep_code IS NULL;

-- EE INDÍGENA PATAXÓ BACUMUXÁ (CARMÉSIA) - INEP: 277657
UPDATE schools 
SET inep_code = '277657' 
WHERE UPPER(TRIM(name)) = 'EE INDÍGENA PATAXÓ BACUMUXÁ' 
  AND UPPER(TRIM(city)) = 'CARMÉSIA' 
  AND inep_code IS NULL;

-- EE PROFESSORA ALMERINDA AGUIAR (COLUNA) - INEP: 213969
UPDATE schools 
SET inep_code = '213969' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ALMERINDA AGUIAR' 
  AND UPPER(TRIM(city)) = 'COLUNA' 
  AND inep_code IS NULL;

-- EE NADIM NOMAN (DORES DE GUANHÃES) - INEP: 322857
UPDATE schools 
SET inep_code = '322857' 
WHERE UPPER(TRIM(name)) = 'EE NADIM NOMAN' 
  AND UPPER(TRIM(city)) = 'DORES DE GUANHÃES' 
  AND inep_code IS NULL;

-- EE PROFESSORA MARGARET BARROSO PINTO (SABINÓPOLIS) - INEP: 330680
UPDATE schools 
SET inep_code = '330680' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARGARET BARROSO PINTO' 
  AND UPPER(TRIM(city)) = 'SABINÓPOLIS' 
  AND inep_code IS NULL;

-- EE ALTAIR ANDRADE GUIMARÃES (SÃO SEBASTIÃO DO MARANHÃO) - INEP: 253316
UPDATE schools 
SET inep_code = '253316' 
WHERE UPPER(TRIM(name)) = 'EE ALTAIR ANDRADE GUIMARÃES' 
  AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO MARANHÃO' 
  AND inep_code IS NULL;

-- EE PROFESSORA CIVA SIMÕES FONSECA (SENHORA DO PORTO) - INEP: 342548
UPDATE schools 
SET inep_code = '342548' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA CIVA SIMÕES FONSECA' 
  AND UPPER(TRIM(city)) = 'SENHORA DO PORTO' 
  AND inep_code IS NULL;

-- EE DO POVOADO DE BOM JESUS DA BOA VISTA (VIRGINÓPOLIS) - INEP: 218146
UPDATE schools 
SET inep_code = '218146' 
WHERE UPPER(TRIM(name)) = 'EE DO POVOADO DE BOM JESUS DA BOA VISTA' 
  AND UPPER(TRIM(city)) = 'VIRGINÓPOLIS' 
  AND inep_code IS NULL;

-- EE GABRIEL RIBEIRO (CARMO DE MINAS) - INEP: 171956
UPDATE schools 
SET inep_code = '171956' 
WHERE UPPER(TRIM(name)) = 'EE GABRIEL RIBEIRO' 
  AND UPPER(TRIM(city)) = 'CARMO DE MINAS' 
  AND inep_code IS NULL;

-- EE PROFESSOR GUEDES FERNANDES (CARMO DE MINAS) - INEP: 171964
UPDATE schools 
SET inep_code = '171964' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR GUEDES FERNANDES' 
  AND UPPER(TRIM(city)) = 'CARMO DE MINAS' 
  AND inep_code IS NULL;

-- EE CÔNEGO JOSÉ DIVINO (DOM VIÇOSO) - INEP: 305375
UPDATE schools 
SET inep_code = '305375' 
WHERE UPPER(TRIM(name)) = 'EE CÔNEGO JOSÉ DIVINO' 
  AND UPPER(TRIM(city)) = 'DOM VIÇOSO' 
  AND inep_code IS NULL;

-- CEP - CENTRO DE EDUCAÇÃO PROFISSIONAL DE ITAJUBÁ (ITAJUBÁ) - INEP: 310778
UPDATE schools 
SET inep_code = '310778' 
WHERE UPPER(TRIM(name)) = 'CEP - CENTRO DE EDUCAÇÃO PROFISSIONAL DE ITAJUBÁ' 
  AND UPPER(TRIM(city)) = 'ITAJUBÁ' 
  AND inep_code IS NULL;

-- EE EULÁLIA GOMES DE OLIVEIRA (PARAISÓPOLIS) - INEP: 305383
UPDATE schools 
SET inep_code = '305383' 
WHERE UPPER(TRIM(name)) = 'EE EULÁLIA GOMES DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'PARAISÓPOLIS' 
  AND inep_code IS NULL;

-- EE DELFIM MOREIRA (VIRGÍNIA) - INEP: 175137
UPDATE schools 
SET inep_code = '175137' 
WHERE UPPER(TRIM(name)) = 'EE DELFIM MOREIRA' 
  AND UPPER(TRIM(city)) = 'VIRGÍNIA' 
  AND inep_code IS NULL;

-- EE PROFESSOR MANOEL MACHADO (VIRGÍNIA) - INEP: 175153
UPDATE schools 
SET inep_code = '175153' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR MANOEL MACHADO' 
  AND UPPER(TRIM(city)) = 'VIRGÍNIA' 
  AND inep_code IS NULL;

-- EE JOÃO GONÇALVES DE OLIVEIRA (CACHOEIRA DOURADA) - INEP: 322814
UPDATE schools 
SET inep_code = '322814' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO GONÇALVES DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'CACHOEIRA DOURADA' 
  AND inep_code IS NULL;

-- EE JOSÉ EZEQUIEL DE QUEIRÓS (CANÁPOLIS) - INEP: 312045
UPDATE schools 
SET inep_code = '312045' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ EZEQUIEL DE QUEIRÓS' 
  AND UPPER(TRIM(city)) = 'CANÁPOLIS' 
  AND inep_code IS NULL;

-- EE SÃO FRANCISCO DE ASSIS (CANÁPOLIS) - INEP: 196380
UPDATE schools 
SET inep_code = '196380' 
WHERE UPPER(TRIM(name)) = 'EE SÃO FRANCISCO DE ASSIS' 
  AND UPPER(TRIM(city)) = 'CANÁPOLIS' 
  AND inep_code IS NULL;

-- EE GOVERNADOR JUSCELINO (CAPINÓPOLIS) - INEP: 196401
UPDATE schools 
SET inep_code = '196401' 
WHERE UPPER(TRIM(name)) = 'EE GOVERNADOR JUSCELINO' 
  AND UPPER(TRIM(city)) = 'CAPINÓPOLIS' 
  AND inep_code IS NULL;

-- EE SÉRGIO DE FREITAS PACHECO (CAPINÓPOLIS) - INEP: 196398
UPDATE schools 
SET inep_code = '196398' 
WHERE UPPER(TRIM(name)) = 'EE SÉRGIO DE FREITAS PACHECO' 
  AND UPPER(TRIM(city)) = 'CAPINÓPOLIS' 
  AND inep_code IS NULL;

-- EE BELCHIOR DE FARIA (CENTRALINA) - INEP: 196436
UPDATE schools 
SET inep_code = '196436' 
WHERE UPPER(TRIM(name)) = 'EE BELCHIOR DE FARIA' 
  AND UPPER(TRIM(city)) = 'CENTRALINA' 
  AND inep_code IS NULL;

-- EE WILSON DE MELO (CENTRALINA) - INEP: 196452
UPDATE schools 
SET inep_code = '196452' 
WHERE UPPER(TRIM(name)) = 'EE WILSON DE MELO' 
  AND UPPER(TRIM(city)) = 'CENTRALINA' 
  AND inep_code IS NULL;

-- EE DE GURINHATÃ (GURINHATÃ) - INEP: 196461
UPDATE schools 
SET inep_code = '196461' 
WHERE UPPER(TRIM(name)) = 'EE DE GURINHATÃ' 
  AND UPPER(TRIM(city)) = 'GURINHATÃ' 
  AND inep_code IS NULL;

-- EE HEITOR JOSÉ DE CASTRO (GURINHATÃ) - INEP: 196487
UPDATE schools 
SET inep_code = '196487' 
WHERE UPPER(TRIM(name)) = 'EE HEITOR JOSÉ DE CASTRO' 
  AND UPPER(TRIM(city)) = 'GURINHATÃ' 
  AND inep_code IS NULL;

-- EE BENEDITO WALDEMAR DA SILVA (IPIAÇU) - INEP: 196517
UPDATE schools 
SET inep_code = '196517' 
WHERE UPPER(TRIM(name)) = 'EE BENEDITO WALDEMAR DA SILVA' 
  AND UPPER(TRIM(city)) = 'IPIAÇU' 
  AND inep_code IS NULL;

-- CESEC CLORINDA MARTINS TAVARES (ITUIUTABA) - INEP: 196703
UPDATE schools 
SET inep_code = '196703' 
WHERE UPPER(TRIM(name)) = 'CESEC CLORINDA MARTINS TAVARES' 
  AND UPPER(TRIM(city)) = 'ITUIUTABA' 
  AND inep_code IS NULL;

-- CONSERVATÓRIO ESTADUAL DE MÚSICA DOUTOR JOSÉ ZÓCCOLI DE ANDRADE (ITUIUTABA) - INEP: 196622
UPDATE schools 
SET inep_code = '196622' 
WHERE UPPER(TRIM(name)) = 'CONSERVATÓRIO ESTADUAL DE MÚSICA DOUTOR JOSÉ ZÓCCOLI DE ANDRADE' 
  AND UPPER(TRIM(city)) = 'ITUIUTABA' 
  AND inep_code IS NULL;

-- EE ANTÔNIO SOUZA MARTINS (ITUIUTABA) - INEP: 196631
UPDATE schools 
SET inep_code = '196631' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO SOUZA MARTINS' 
  AND UPPER(TRIM(city)) = 'ITUIUTABA' 
  AND inep_code IS NULL;

-- EE ARTHUR JUNQUEIRA DE ALMEIDA (ITUIUTABA) - INEP: 196576
UPDATE schools 
SET inep_code = '196576' 
WHERE UPPER(TRIM(name)) = 'EE ARTHUR JUNQUEIRA DE ALMEIDA' 
  AND UPPER(TRIM(city)) = 'ITUIUTABA' 
  AND inep_code IS NULL;

-- EE CÔNEGO ÂNGELO (ITUIUTABA) - INEP: 196541
UPDATE schools 
SET inep_code = '196541' 
WHERE UPPER(TRIM(name)) = 'EE CÔNEGO ÂNGELO' 
  AND UPPER(TRIM(city)) = 'ITUIUTABA' 
  AND inep_code IS NULL;

-- EE CORONEL JOÃO MARTINS (ITUIUTABA) - INEP: 196525
UPDATE schools 
SET inep_code = '196525' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL JOÃO MARTINS' 
  AND UPPER(TRIM(city)) = 'ITUIUTABA' 
  AND inep_code IS NULL;

-- EE CORONEL TONICO FRANCO (ITUIUTABA) - INEP: 196533
UPDATE schools 
SET inep_code = '196533' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL TONICO FRANCO' 
  AND UPPER(TRIM(city)) = 'ITUIUTABA' 
  AND inep_code IS NULL;

-- EE DE EDUCAÇÃO ESPECIAL RISOLETA NEVES (ITUIUTABA) - INEP: 196711
UPDATE schools 
SET inep_code = '196711' 
WHERE UPPER(TRIM(name)) = 'EE DE EDUCAÇÃO ESPECIAL RISOLETA NEVES' 
  AND UPPER(TRIM(city)) = 'ITUIUTABA' 
  AND inep_code IS NULL;

-- EE DOUTOR FERNANDO ALEXANDRE (ITUIUTABA) - INEP: 196550
UPDATE schools 
SET inep_code = '196550' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR FERNANDO ALEXANDRE' 
  AND UPPER(TRIM(city)) = 'ITUIUTABA' 
  AND inep_code IS NULL;

-- EE GOVERNADOR BIAS FORTES (ITUIUTABA) - INEP: 196568
UPDATE schools 
SET inep_code = '196568' 
WHERE UPPER(TRIM(name)) = 'EE GOVERNADOR BIAS FORTES' 
  AND UPPER(TRIM(city)) = 'ITUIUTABA' 
  AND inep_code IS NULL;

-- EE GOVERNADOR CLÓVIS SALGADO (ITUIUTABA) - INEP: 196681
UPDATE schools 
SET inep_code = '196681' 
WHERE UPPER(TRIM(name)) = 'EE GOVERNADOR CLÓVIS SALGADO' 
  AND UPPER(TRIM(city)) = 'ITUIUTABA' 
  AND inep_code IS NULL;

-- EE GOVERNADOR ISRAEL PINHEIRO (ITUIUTABA) - INEP: 196584
UPDATE schools 
SET inep_code = '196584' 
WHERE UPPER(TRIM(name)) = 'EE GOVERNADOR ISRAEL PINHEIRO' 
  AND UPPER(TRIM(city)) = 'ITUIUTABA' 
  AND inep_code IS NULL;

-- EE JOÃO PINHEIRO (ITUIUTABA) - INEP: 196606
UPDATE schools 
SET inep_code = '196606' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO PINHEIRO' 
  AND UPPER(TRIM(city)) = 'ITUIUTABA' 
  AND inep_code IS NULL;

-- EE PROFESSOR ÁLVARO BRANDÃO DE ANDRADE (ITUIUTABA) - INEP: 196657
UPDATE schools 
SET inep_code = '196657' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ÁLVARO BRANDÃO DE ANDRADE' 
  AND UPPER(TRIM(city)) = 'ITUIUTABA' 
  AND inep_code IS NULL;

-- EE PROFESSORA MARIA DE BARROS (ITUIUTABA) - INEP: 196592
UPDATE schools 
SET inep_code = '196592' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA DE BARROS' 
  AND UPPER(TRIM(city)) = 'ITUIUTABA' 
  AND inep_code IS NULL;

-- EE ROTARY (ITUIUTABA) - INEP: 196665
UPDATE schools 
SET inep_code = '196665' 
WHERE UPPER(TRIM(name)) = 'EE ROTARY' 
  AND UPPER(TRIM(city)) = 'ITUIUTABA' 
  AND inep_code IS NULL;

-- EE SENADOR CAMILO CHAVES (ITUIUTABA) - INEP: 196673
UPDATE schools 
SET inep_code = '196673' 
WHERE UPPER(TRIM(name)) = 'EE SENADOR CAMILO CHAVES' 
  AND UPPER(TRIM(city)) = 'ITUIUTABA' 
  AND inep_code IS NULL;

-- EE JOSÉ PARANAÍBA (SANTA VITÓRIA) - INEP: 196738
UPDATE schools 
SET inep_code = '196738' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ PARANAÍBA' 
  AND UPPER(TRIM(city)) = 'SANTA VITÓRIA' 
  AND inep_code IS NULL;

-- EE PREFEITO JOSÉ FRANCO DE GOUVEIA (SANTA VITÓRIA) - INEP: 196720
UPDATE schools 
SET inep_code = '196720' 
WHERE UPPER(TRIM(name)) = 'EE PREFEITO JOSÉ FRANCO DE GOUVEIA' 
  AND UPPER(TRIM(city)) = 'SANTA VITÓRIA' 
  AND inep_code IS NULL;

-- EE PROFESSORA DIRCE MARIA DE OLIVEIRA (SANTA VITÓRIA) - INEP: 338672
UPDATE schools 
SET inep_code = '338672' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA DIRCE MARIA DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'SANTA VITÓRIA' 
  AND inep_code IS NULL;

-- EE JOAQUIM TEIXEIRA DE BRITO (CATUTI) - INEP: 239194
UPDATE schools 
SET inep_code = '239194' 
WHERE UPPER(TRIM(name)) = 'EE JOAQUIM TEIXEIRA DE BRITO' 
  AND UPPER(TRIM(city)) = 'CATUTI' 
  AND inep_code IS NULL;

-- EE ALVACY DE FREITAS (ESPINOSA) - INEP: 362484
UPDATE schools 
SET inep_code = '362484' 
WHERE UPPER(TRIM(name)) = 'EE ALVACY DE FREITAS' 
  AND UPPER(TRIM(city)) = 'ESPINOSA' 
  AND inep_code IS NULL;

-- EE BETÂNIA TOLENTINO SILVEIRA (ESPINOSA) - INEP: 212261
UPDATE schools 
SET inep_code = '212261' 
WHERE UPPER(TRIM(name)) = 'EE BETÂNIA TOLENTINO SILVEIRA' 
  AND UPPER(TRIM(city)) = 'ESPINOSA' 
  AND inep_code IS NULL;

-- EE SANTOS DUMONT (ESPINOSA) - INEP: 218286
UPDATE schools 
SET inep_code = '218286' 
WHERE UPPER(TRIM(name)) = 'EE SANTOS DUMONT' 
  AND UPPER(TRIM(city)) = 'ESPINOSA' 
  AND inep_code IS NULL;

-- EE STA TEREZINHA (ESPINOSA) - INEP: 218294
UPDATE schools 
SET inep_code = '218294' 
WHERE UPPER(TRIM(name)) = 'EE STA TEREZINHA' 
  AND UPPER(TRIM(city)) = 'ESPINOSA' 
  AND inep_code IS NULL;

-- EE DO NÚCLEO HABITACIONAL I (JAÍBA) - INEP: 231843
UPDATE schools 
SET inep_code = '231843' 
WHERE UPPER(TRIM(name)) = 'EE DO NÚCLEO HABITACIONAL I' 
  AND UPPER(TRIM(city)) = 'JAÍBA' 
  AND inep_code IS NULL;

-- EE GUIMARÃES ROSA (JAÍBA) - INEP: 295086
UPDATE schools 
SET inep_code = '295086' 
WHERE UPPER(TRIM(name)) = 'EE GUIMARÃES ROSA' 
  AND UPPER(TRIM(city)) = 'JAÍBA' 
  AND inep_code IS NULL;

-- EE PEQUENOS IRRIGANTES (JAÍBA) - INEP: 231835
UPDATE schools 
SET inep_code = '231835' 
WHERE UPPER(TRIM(name)) = 'EE PEQUENOS IRRIGANTES' 
  AND UPPER(TRIM(city)) = 'JAÍBA' 
  AND inep_code IS NULL;

-- EE TIMÓTEO LISBOA GUERRA (JAÍBA) - INEP: 239208
UPDATE schools 
SET inep_code = '239208' 
WHERE UPPER(TRIM(name)) = 'EE TIMÓTEO LISBOA GUERRA' 
  AND UPPER(TRIM(city)) = 'JAÍBA' 
  AND inep_code IS NULL;

-- EE CECÍLIA MARIA DE JESUS (JANAÚBA) - INEP: 218251
UPDATE schools 
SET inep_code = '218251' 
WHERE UPPER(TRIM(name)) = 'EE CECÍLIA MARIA DE JESUS' 
  AND UPPER(TRIM(city)) = 'JANAÚBA' 
  AND inep_code IS NULL;

-- EE DOUTOR JOSÉ ESTEVES RODRIGUES (JANAÚBA) - INEP: 338680
UPDATE schools 
SET inep_code = '338680' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR JOSÉ ESTEVES RODRIGUES' 
  AND UPPER(TRIM(city)) = 'JANAÚBA' 
  AND inep_code IS NULL;

-- EE JOAQUIM MAURÍCIO DE AZEVEDO (JANAÚBA) - INEP: 233374
UPDATE schools 
SET inep_code = '233374' 
WHERE UPPER(TRIM(name)) = 'EE JOAQUIM MAURÍCIO DE AZEVEDO' 
  AND UPPER(TRIM(city)) = 'JANAÚBA' 
  AND inep_code IS NULL;

-- EE JULIÃO MENDES FERREIRA (JANAÚBA) - INEP: 338699
UPDATE schools 
SET inep_code = '338699' 
WHERE UPPER(TRIM(name)) = 'EE JULIÃO MENDES FERREIRA' 
  AND UPPER(TRIM(city)) = 'JANAÚBA' 
  AND inep_code IS NULL;

-- EE PROFESSORA DIVA PINTO (JANAÚBA) - INEP: 218260
UPDATE schools 
SET inep_code = '218260' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA DIVA PINTO' 
  AND UPPER(TRIM(city)) = 'JANAÚBA' 
  AND inep_code IS NULL;

-- EE IRÊNIO PINHEIRO (MATO VERDE) - INEP: 239186
UPDATE schools 
SET inep_code = '239186' 
WHERE UPPER(TRIM(name)) = 'EE IRÊNIO PINHEIRO' 
  AND UPPER(TRIM(city)) = 'MATO VERDE' 
  AND inep_code IS NULL;

-- EE EREZINHA ANTUNES MARTINS (NOVA PORTEIRINHA) - INEP: 205648
UPDATE schools 
SET inep_code = '205648' 
WHERE UPPER(TRIM(name)) = 'EE EREZINHA ANTUNES MARTINS' 
  AND UPPER(TRIM(city)) = 'NOVA PORTEIRINHA' 
  AND inep_code IS NULL;

-- EE MESTRE TOMAZ VALERIANO DE ARAÚJO (PORTEIRINHA) - INEP: 338702
UPDATE schools 
SET inep_code = '338702' 
WHERE UPPER(TRIM(name)) = 'EE MESTRE TOMAZ VALERIANO DE ARAÚJO' 
  AND UPPER(TRIM(city)) = 'PORTEIRINHA' 
  AND inep_code IS NULL;

-- EE DE ENSINO MÉDIO (RIO PARDO DE MINAS) - INEP: 349267
UPDATE schools 
SET inep_code = '349267' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' 
  AND UPPER(TRIM(city)) = 'RIO PARDO DE MINAS' 
  AND inep_code IS NULL;

-- EE PROFESSORA MARLENE CARMO (RIO PARDO DE MINAS) - INEP: 212253
UPDATE schools 
SET inep_code = '212253' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARLENE CARMO' 
  AND UPPER(TRIM(city)) = 'RIO PARDO DE MINAS' 
  AND inep_code IS NULL;

-- EE ALICE DE JESUS RODRIGUES (VERDELÂNDIA) - INEP: 351091
UPDATE schools 
SET inep_code = '351091' 
WHERE UPPER(TRIM(name)) = 'EE ALICE DE JESUS RODRIGUES' 
  AND UPPER(TRIM(city)) = 'VERDELÂNDIA' 
  AND inep_code IS NULL;

-- EE ANTONINA FERNANDES SAMPAIO (VERDELÂNDIA) - INEP: 351083
UPDATE schools 
SET inep_code = '351083' 
WHERE UPPER(TRIM(name)) = 'EE ANTONINA FERNANDES SAMPAIO' 
  AND UPPER(TRIM(city)) = 'VERDELÂNDIA' 
  AND inep_code IS NULL;

-- EE CESÁRIO NUNES DOS SANTOS (BONITO DE MINAS) - INEP: 205532
UPDATE schools 
SET inep_code = '205532' 
WHERE UPPER(TRIM(name)) = 'EE CESÁRIO NUNES DOS SANTOS' 
  AND UPPER(TRIM(city)) = 'BONITO DE MINAS' 
  AND inep_code IS NULL;

-- EE DE BONFIM (BONITO DE MINAS) - INEP: 205516
UPDATE schools 
SET inep_code = '205516' 
WHERE UPPER(TRIM(name)) = 'EE DE BONFIM' 
  AND UPPER(TRIM(city)) = 'BONITO DE MINAS' 
  AND inep_code IS NULL;

-- EE DE ENSINO FUNDAMENTAL ANOS FINAIS E ENSINO MÉDIO (BONITO DE MINAS) - INEP: 369810
UPDATE schools 
SET inep_code = '369810' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL ANOS FINAIS E ENSINO MÉDIO' 
  AND UPPER(TRIM(city)) = 'BONITO DE MINAS' 
  AND inep_code IS NULL;

-- EE MANOEL PEREIRA MAGALHÃES (BONITO DE MINAS) - INEP: 205451
UPDATE schools 
SET inep_code = '205451' 
WHERE UPPER(TRIM(name)) = 'EE MANOEL PEREIRA MAGALHÃES' 
  AND UPPER(TRIM(city)) = 'BONITO DE MINAS' 
  AND inep_code IS NULL;

-- EE SÃO JOSÉ DO GIBÃO (BONITO DE MINAS) - INEP: 205508
UPDATE schools 
SET inep_code = '205508' 
WHERE UPPER(TRIM(name)) = 'EE SÃO JOSÉ DO GIBÃO' 
  AND UPPER(TRIM(city)) = 'BONITO DE MINAS' 
  AND inep_code IS NULL;

-- EE MOACIR CÂNDIDO (CHAPADA GAÚCHA) - INEP: 205460
UPDATE schools 
SET inep_code = '205460' 
WHERE UPPER(TRIM(name)) = 'EE MOACIR CÂNDIDO' 
  AND UPPER(TRIM(city)) = 'CHAPADA GAÚCHA' 
  AND inep_code IS NULL;

-- EE DE ENSINO FUNDAMENTAL ANOS FINAIS E ENSINO MÉDIO (CÔNEGO MARINHO) - INEP: 369829
UPDATE schools 
SET inep_code = '369829' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL ANOS FINAIS E ENSINO MÉDIO' 
  AND UPPER(TRIM(city)) = 'CÔNEGO MARINHO' 
  AND inep_code IS NULL;

-- EE ANTÔNIO FERNANDES VIANA (JANUÁRIA) - INEP: 246271
UPDATE schools 
SET inep_code = '246271' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO FERNANDES VIANA' 
  AND UPPER(TRIM(city)) = 'JANUÁRIA' 
  AND inep_code IS NULL;

-- EE DE BOA VISTA (JANUÁRIA) - INEP: 212822
UPDATE schools 
SET inep_code = '212822' 
WHERE UPPER(TRIM(name)) = 'EE DE BOA VISTA' 
  AND UPPER(TRIM(city)) = 'JANUÁRIA' 
  AND inep_code IS NULL;

-- EE DE ENSINO MÉDIO (JANUÁRIA) - INEP: 356778
UPDATE schools 
SET inep_code = '356778' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' 
  AND UPPER(TRIM(city)) = 'JANUÁRIA' 
  AND inep_code IS NULL;

-- EE EULER TUPINÁ BASTOS (JANUÁRIA) - INEP: 253685
UPDATE schools 
SET inep_code = '253685' 
WHERE UPPER(TRIM(name)) = 'EE EULER TUPINÁ BASTOS' 
  AND UPPER(TRIM(city)) = 'JANUÁRIA' 
  AND inep_code IS NULL;

-- EE FELIPE DIAS CORRÊA (JANUÁRIA) - INEP: 253677
UPDATE schools 
SET inep_code = '253677' 
WHERE UPPER(TRIM(name)) = 'EE FELIPE DIAS CORRÊA' 
  AND UPPER(TRIM(city)) = 'JANUÁRIA' 
  AND inep_code IS NULL;

-- EE MARIA ROSA NUNES (JANUÁRIA) - INEP: 246280
UPDATE schools 
SET inep_code = '246280' 
WHERE UPPER(TRIM(name)) = 'EE MARIA ROSA NUNES' 
  AND UPPER(TRIM(city)) = 'JANUÁRIA' 
  AND inep_code IS NULL;

-- EE NOVA ESPERANÇA (JANUÁRIA) - INEP: 253651
UPDATE schools 
SET inep_code = '253651' 
WHERE UPPER(TRIM(name)) = 'EE NOVA ESPERANÇA' 
  AND UPPER(TRIM(city)) = 'JANUÁRIA' 
  AND inep_code IS NULL;

-- EE MANOEL FERNANDES DA SILVA (JUVENÍLIA) - INEP: 342726
UPDATE schools 
SET inep_code = '342726' 
WHERE UPPER(TRIM(name)) = 'EE MANOEL FERNANDES DA SILVA' 
  AND UPPER(TRIM(city)) = 'JUVENÍLIA' 
  AND inep_code IS NULL;

-- EE DE ENSINO MÉDIO (MATIAS CARDOSO) - INEP: 342734
UPDATE schools 
SET inep_code = '342734' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' 
  AND UPPER(TRIM(city)) = 'MATIAS CARDOSO' 
  AND inep_code IS NULL;

-- EE DA VILA NOVO HORIZONTE (MONTALVÂNIA) - INEP: 217913
UPDATE schools 
SET inep_code = '217913' 
WHERE UPPER(TRIM(name)) = 'EE DA VILA NOVO HORIZONTE' 
  AND UPPER(TRIM(city)) = 'MONTALVÂNIA' 
  AND inep_code IS NULL;

-- EE DE POÇÃOZINHO (PEDRAS DE MARIA DA CRUZ) - INEP: 239429
UPDATE schools 
SET inep_code = '239429' 
WHERE UPPER(TRIM(name)) = 'EE DE POÇÃOZINHO' 
  AND UPPER(TRIM(city)) = 'PEDRAS DE MARIA DA CRUZ' 
  AND inep_code IS NULL;

-- EE DONA CILA (PEDRAS DE MARIA DA CRUZ) - INEP: 239330
UPDATE schools 
SET inep_code = '239330' 
WHERE UPPER(TRIM(name)) = 'EE DONA CILA' 
  AND UPPER(TRIM(city)) = 'PEDRAS DE MARIA DA CRUZ' 
  AND inep_code IS NULL;

-- EE PRIMAVERA (PINTÓPOLIS) - INEP: 253847
UPDATE schools 
SET inep_code = '253847' 
WHERE UPPER(TRIM(name)) = 'EE PRIMAVERA' 
  AND UPPER(TRIM(city)) = 'PINTÓPOLIS' 
  AND inep_code IS NULL;

-- EE BRASILIANO BRAZ (SÃO FRANCISCO) - INEP: 240222
UPDATE schools 
SET inep_code = '240222' 
WHERE UPPER(TRIM(name)) = 'EE BRASILIANO BRAZ' 
  AND UPPER(TRIM(city)) = 'SÃO FRANCISCO' 
  AND inep_code IS NULL;

-- EE DA FAZENDA PASSAGEM FUNDA (SÃO FRANCISCO) - INEP: 239411
UPDATE schools 
SET inep_code = '239411' 
WHERE UPPER(TRIM(name)) = 'EE DA FAZENDA PASSAGEM FUNDA' 
  AND UPPER(TRIM(city)) = 'SÃO FRANCISCO' 
  AND inep_code IS NULL;

-- EE EPAMINONDAS LEITE (SÃO FRANCISCO) - INEP: 253588
UPDATE schools 
SET inep_code = '253588' 
WHERE UPPER(TRIM(name)) = 'EE EPAMINONDAS LEITE' 
  AND UPPER(TRIM(city)) = 'SÃO FRANCISCO' 
  AND inep_code IS NULL;

-- EE EVERARDO GONÇALVES BOTELHO (SÃO FRANCISCO) - INEP: 239313
UPDATE schools 
SET inep_code = '239313' 
WHERE UPPER(TRIM(name)) = 'EE EVERARDO GONÇALVES BOTELHO' 
  AND UPPER(TRIM(city)) = 'SÃO FRANCISCO' 
  AND inep_code IS NULL;

-- EE ALINE DIAS NEVES (SÃO JOÃO DAS MISSÕES) - INEP: 338761
UPDATE schools 
SET inep_code = '338761' 
WHERE UPPER(TRIM(name)) = 'EE ALINE DIAS NEVES' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DAS MISSÕES' 
  AND inep_code IS NULL;

-- EE INDÍGENA BUKIMUJU (SÃO JOÃO DAS MISSÕES) - INEP: 269875
UPDATE schools 
SET inep_code = '269875' 
WHERE UPPER(TRIM(name)) = 'EE INDÍGENA BUKIMUJU' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DAS MISSÕES' 
  AND inep_code IS NULL;

-- EE INDÍGENA BUKINUK (SÃO JOÃO DAS MISSÕES) - INEP: 322571
UPDATE schools 
SET inep_code = '322571' 
WHERE UPPER(TRIM(name)) = 'EE INDÍGENA BUKINUK' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DAS MISSÕES' 
  AND inep_code IS NULL;

-- EE INDÍGENA DE EDUCAÇÃO INFANTIL E ENSINO FUNDAMENTAL (SÃO JOÃO DAS MISSÕES) - INEP: 369837
UPDATE schools 
SET inep_code = '369837' 
WHERE UPPER(TRIM(name)) = 'EE INDÍGENA DE EDUCAÇÃO INFANTIL E ENSINO FUNDAMENTAL' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DAS MISSÕES' 
  AND inep_code IS NULL;

-- EE INDÍGENA DE EDUCAÇÃO INFANTIL ENSINO FUNDAMENTAL E ENSINO MÉDIO (SÃO JOÃO DAS MISSÕES) - INEP: 356786
UPDATE schools 
SET inep_code = '356786' 
WHERE UPPER(TRIM(name)) = 'EE INDÍGENA DE EDUCAÇÃO INFANTIL ENSINO FUNDAMENTAL E ENSINO MÉDIO' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DAS MISSÕES' 
  AND inep_code IS NULL;

-- EE INDÍGENA DE EDUCAÇÃO INFANTIL ENSINO FUNDAMENTAL E ENSINO MÉDIO (SÃO JOÃO DAS MISSÕES) - INEP: 361461
UPDATE schools 
SET inep_code = '361461' 
WHERE UPPER(TRIM(name)) = 'EE INDÍGENA DE EDUCAÇÃO INFANTIL ENSINO FUNDAMENTAL E ENSINO MÉDIO' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DAS MISSÕES' 
  AND inep_code IS NULL;

-- EE INDÍGENA KUHINAN XACRIABÁ (SÃO JOÃO DAS MISSÕES) - INEP: 319058
UPDATE schools 
SET inep_code = '319058' 
WHERE UPPER(TRIM(name)) = 'EE INDÍGENA KUHINAN XACRIABÁ' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DAS MISSÕES' 
  AND inep_code IS NULL;

-- EE INDÍGENA MAMBUKA (SÃO JOÃO DAS MISSÕES) - INEP: 338753
UPDATE schools 
SET inep_code = '338753' 
WHERE UPPER(TRIM(name)) = 'EE INDÍGENA MAMBUKA' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DAS MISSÕES' 
  AND inep_code IS NULL;

-- EE INDÍGENA OAYTOMORIM (SÃO JOÃO DAS MISSÕES) - INEP: 338770
UPDATE schools 
SET inep_code = '338770' 
WHERE UPPER(TRIM(name)) = 'EE INDÍGENA OAYTOMORIM' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DAS MISSÕES' 
  AND inep_code IS NULL;

-- EE INDÍGENA UIKITU KUHINÃ (SÃO JOÃO DAS MISSÕES) - INEP: 338745
UPDATE schools 
SET inep_code = '338745' 
WHERE UPPER(TRIM(name)) = 'EE INDÍGENA UIKITU KUHINÃ' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DAS MISSÕES' 
  AND inep_code IS NULL;

-- EE INDÍGENA XUKURANK (SÃO JOÃO DAS MISSÕES) - INEP: 297518
UPDATE schools 
SET inep_code = '297518' 
WHERE UPPER(TRIM(name)) = 'EE INDÍGENA XUKURANK' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DAS MISSÕES' 
  AND inep_code IS NULL;

-- EE DA FAZENDA CAMPO LINDO (UBAÍ) - INEP: 213543
UPDATE schools 
SET inep_code = '213543' 
WHERE UPPER(TRIM(name)) = 'EE DA FAZENDA CAMPO LINDO' 
  AND UPPER(TRIM(city)) = 'UBAÍ' 
  AND inep_code IS NULL;

-- EE AMÉLIA CAVALCANTE PIMENTA (VARZELÂNDIA) - INEP: 253499
UPDATE schools 
SET inep_code = '253499' 
WHERE UPPER(TRIM(name)) = 'EE AMÉLIA CAVALCANTE PIMENTA' 
  AND UPPER(TRIM(city)) = 'VARZELÂNDIA' 
  AND inep_code IS NULL;

-- EE DEUSÂNIA DE BRITO SALES (VARZELÂNDIA) - INEP: 253481
UPDATE schools 
SET inep_code = '253481' 
WHERE UPPER(TRIM(name)) = 'EE DEUSÂNIA DE BRITO SALES' 
  AND UPPER(TRIM(city)) = 'VARZELÂNDIA' 
  AND inep_code IS NULL;

-- EE GILBERTO ALVES COUTINHO (VARZELÂNDIA) - INEP: 253511
UPDATE schools 
SET inep_code = '253511' 
WHERE UPPER(TRIM(name)) = 'EE GILBERTO ALVES COUTINHO' 
  AND UPPER(TRIM(city)) = 'VARZELÂNDIA' 
  AND inep_code IS NULL;

-- EE ISABEL SOARES DE JESUS (VARZELÂNDIA) - INEP: 217344
UPDATE schools 
SET inep_code = '217344' 
WHERE UPPER(TRIM(name)) = 'EE ISABEL SOARES DE JESUS' 
  AND UPPER(TRIM(city)) = 'VARZELÂNDIA' 
  AND inep_code IS NULL;

-- EE JOSÉ FERNANDES DE SOUZA (VARZELÂNDIA) - INEP: 213527
UPDATE schools 
SET inep_code = '213527' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ FERNANDES DE SOUZA' 
  AND UPPER(TRIM(city)) = 'VARZELÂNDIA' 
  AND inep_code IS NULL;

-- EE JUCA VELOSO (VARZELÂNDIA) - INEP: 223999
UPDATE schools 
SET inep_code = '223999' 
WHERE UPPER(TRIM(name)) = 'EE JUCA VELOSO' 
  AND UPPER(TRIM(city)) = 'VARZELÂNDIA' 
  AND inep_code IS NULL;

-- EE MANOEL ALVES DE ALMEIDA (VARZELÂNDIA) - INEP: 217352
UPDATE schools 
SET inep_code = '217352' 
WHERE UPPER(TRIM(name)) = 'EE MANOEL ALVES DE ALMEIDA' 
  AND UPPER(TRIM(city)) = 'VARZELÂNDIA' 
  AND inep_code IS NULL;

-- EE NILZA MARIA DOS SANTOS (VARZELÂNDIA) - INEP: 253472
UPDATE schools 
SET inep_code = '253472' 
WHERE UPPER(TRIM(name)) = 'EE NILZA MARIA DOS SANTOS' 
  AND UPPER(TRIM(city)) = 'VARZELÂNDIA' 
  AND inep_code IS NULL;

-- EE SANTO ANTÔNIO (CHIADOR) - INEP: 346217
UPDATE schools 
SET inep_code = '346217' 
WHERE UPPER(TRIM(name)) = 'EE SANTO ANTÔNIO' 
  AND UPPER(TRIM(city)) = 'CHIADOR' 
  AND inep_code IS NULL;

-- EE PROFESSOR MILTON SANTOS (CORONEL PACHECO) - INEP: 322512
UPDATE schools 
SET inep_code = '322512' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR MILTON SANTOS' 
  AND UPPER(TRIM(city)) = 'CORONEL PACHECO' 
  AND inep_code IS NULL;

-- EE CARLOS HENRIQUE RIBEIRO DOS SANTOS (GOIANÁ) - INEP: 369845
UPDATE schools 
SET inep_code = '369845' 
WHERE UPPER(TRIM(name)) = 'EE CARLOS HENRIQUE RIBEIRO DOS SANTOS' 
  AND UPPER(TRIM(city)) = 'GOIANÁ' 
  AND inep_code IS NULL;

-- EE PROFESSOR IRINEU GUIMARÃES (GUARARÁ) - INEP: 330558
UPDATE schools 
SET inep_code = '330558' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR IRINEU GUIMARÃES' 
  AND UPPER(TRIM(city)) = 'GUARARÁ' 
  AND inep_code IS NULL;

-- EE DE ENSINO FUNDAMENTAL E MÉDIO (JUIZ DE FORA) - INEP: 326801
UPDATE schools 
SET inep_code = '326801' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL E MÉDIO' 
  AND UPPER(TRIM(city)) = 'JUIZ DE FORA' 
  AND inep_code IS NULL;

-- EE DE ENSINO FUNDAMENTAL E MÉDIO (JUIZ DE FORA) - INEP: 326810
UPDATE schools 
SET inep_code = '326810' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL E MÉDIO' 
  AND UPPER(TRIM(city)) = 'JUIZ DE FORA' 
  AND inep_code IS NULL;

-- EE NYRCE VILLA VERDE COELHO DE MAGALHÃES (JUIZ DE FORA) - INEP: 342637
UPDATE schools 
SET inep_code = '342637' 
WHERE UPPER(TRIM(name)) = 'EE NYRCE VILLA VERDE COELHO DE MAGALHÃES' 
  AND UPPER(TRIM(city)) = 'JUIZ DE FORA' 
  AND inep_code IS NULL;

-- EE PREFEITO WALTER TREZZA (MARIPÁ DE MINAS) - INEP: 322539
UPDATE schools 
SET inep_code = '322539' 
WHERE UPPER(TRIM(name)) = 'EE PREFEITO WALTER TREZZA' 
  AND UPPER(TRIM(city)) = 'MARIPÁ DE MINAS' 
  AND inep_code IS NULL;

-- EE JOAQUIM ALVES DE CARVALHO (OLARIA) - INEP: 330566
UPDATE schools 
SET inep_code = '330566' 
WHERE UPPER(TRIM(name)) = 'EE JOAQUIM ALVES DE CARVALHO' 
  AND UPPER(TRIM(city)) = 'OLARIA' 
  AND inep_code IS NULL;

-- EE DE ENSINO MÉDIO (PEDRO TEIXEIRA) - INEP: 338788
UPDATE schools 
SET inep_code = '338788' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' 
  AND UPPER(TRIM(city)) = 'PEDRO TEIXEIRA' 
  AND inep_code IS NULL;

-- EE PADRE JOÃO BATISTA DE OLIVEIRA (PEQUERI) - INEP: 322547
UPDATE schools 
SET inep_code = '322547' 
WHERE UPPER(TRIM(name)) = 'EE PADRE JOÃO BATISTA DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'PEQUERI' 
  AND inep_code IS NULL;

-- EE DE ENSINO MÉDIO (ROCHEDO DE MINAS) - INEP: 342645
UPDATE schools 
SET inep_code = '342645' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' 
  AND UPPER(TRIM(city)) = 'ROCHEDO DE MINAS' 
  AND inep_code IS NULL;

-- EE JOÃO AUGUSTO DA SILVA BARRETO (SANTA BÁRBARA DO MONTE VERDE) - INEP: 342653
UPDATE schools 
SET inep_code = '342653' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO AUGUSTO DA SILVA BARRETO' 
  AND UPPER(TRIM(city)) = 'SANTA BÁRBARA DO MONTE VERDE' 
  AND inep_code IS NULL;

-- EE DYRCE JOSÉ  DA SILVA E SOUZA (SANTANA DO DESERTO) - INEP: 338796
UPDATE schools 
SET inep_code = '338796' 
WHERE UPPER(TRIM(name)) = 'EE DYRCE JOSÉ DA SILVA E SOUZA' 
  AND UPPER(TRIM(city)) = 'SANTANA DO DESERTO' 
  AND inep_code IS NULL;

-- EE PROFESSORA ROMILDA BARBOSA (SENADOR CORTES) - INEP: 342661
UPDATE schools 
SET inep_code = '342661' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ROMILDA BARBOSA' 
  AND UPPER(TRIM(city)) = 'SENADOR CORTES' 
  AND inep_code IS NULL;

-- EE DE ENSINO MÉDIO (SIMÃO PEREIRA) - INEP: 338800
UPDATE schools 
SET inep_code = '338800' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' 
  AND UPPER(TRIM(city)) = 'SIMÃO PEREIRA' 
  AND inep_code IS NULL;

-- EE PROFESSOR LUIZ ANTÔNIO PIRES DE SOUZA (ARGIRITA) - INEP: 305316
UPDATE schools 
SET inep_code = '305316' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR LUIZ ANTÔNIO PIRES DE SOUZA' 
  AND UPPER(TRIM(city)) = 'ARGIRITA' 
  AND inep_code IS NULL;

-- EE ISA MORAES FREITAS (ITAMARATI DE MINAS) - INEP: 305324
UPDATE schools 
SET inep_code = '305324' 
WHERE UPPER(TRIM(name)) = 'EE ISA MORAES FREITAS' 
  AND UPPER(TRIM(city)) = 'ITAMARATI DE MINAS' 
  AND inep_code IS NULL;

-- EE EMÍLIA MARIA DINIZ (DURANDÉ) - INEP: 319066
UPDATE schools 
SET inep_code = '319066' 
WHERE UPPER(TRIM(name)) = 'EE EMÍLIA MARIA DINIZ' 
  AND UPPER(TRIM(city)) = 'DURANDÉ' 
  AND inep_code IS NULL;

-- EE ANTÔNIO SILVA ROCHA (MANHUAÇU) - INEP: 364940
UPDATE schools 
SET inep_code = '364940' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO SILVA ROCHA' 
  AND UPPER(TRIM(city)) = 'MANHUAÇU' 
  AND inep_code IS NULL;

-- EE DO BAIRRO BOA VISTA (MATIPÓ) - INEP: 205541
UPDATE schools 
SET inep_code = '205541' 
WHERE UPPER(TRIM(name)) = 'EE DO BAIRRO BOA VISTA' 
  AND UPPER(TRIM(city)) = 'MATIPÓ' 
  AND inep_code IS NULL;

-- CESEC VALDIR PINHEIRO DE LACERDA (MUTUM) - INEP: 312479
UPDATE schools 
SET inep_code = '312479' 
WHERE UPPER(TRIM(name)) = 'CESEC VALDIR PINHEIRO DE LACERDA' 
  AND UPPER(TRIM(city)) = 'MUTUM' 
  AND inep_code IS NULL;

-- EE DALILA CERQUEIRA PESSOA (SANTA MARGARIDA) - INEP: 346381
UPDATE schools 
SET inep_code = '346381' 
WHERE UPPER(TRIM(name)) = 'EE DALILA CERQUEIRA PESSOA' 
  AND UPPER(TRIM(city)) = 'SANTA MARGARIDA' 
  AND inep_code IS NULL;

-- EE VIOLETA MAGESTE PEREIRA (SANTA MARGARIDA) - INEP: 346187
UPDATE schools 
SET inep_code = '346187' 
WHERE UPPER(TRIM(name)) = 'EE VIOLETA MAGESTE PEREIRA' 
  AND UPPER(TRIM(city)) = 'SANTA MARGARIDA' 
  AND inep_code IS NULL;

-- EE EFIGÊNIA DE BARROS OLIVEIRA (BARÃO DE COCAIS) - INEP: 218723
UPDATE schools 
SET inep_code = '218723' 
WHERE UPPER(TRIM(name)) = 'EE EFIGÊNIA DE BARROS OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'BARÃO DE COCAIS' 
  AND inep_code IS NULL;

-- CENTRO INTERESCOLAR DE CULTURA ARTE LINGUAGENS E TECNOLOGIAS (BELO HORIZONTE) - INEP: 364932
UPDATE schools 
SET inep_code = '364932' 
WHERE UPPER(TRIM(name)) = 'CENTRO INTERESCOLAR DE CULTURA ARTE LINGUAGENS E TECNOLOGIAS' 
  AND UPPER(TRIM(city)) = 'BELO HORIZONTE' 
  AND inep_code IS NULL;

-- CESEC POETA MURILO MENDES (BELO HORIZONTE) - INEP: 307068
UPDATE schools 
SET inep_code = '307068' 
WHERE UPPER(TRIM(name)) = 'CESEC POETA MURILO MENDES' 
  AND UPPER(TRIM(city)) = 'BELO HORIZONTE' 
  AND inep_code IS NULL;

-- EE JOVEM PROTAGONISTA (BELO HORIZONTE) - INEP: 322563
UPDATE schools 
SET inep_code = '322563' 
WHERE UPPER(TRIM(name)) = 'EE JOVEM PROTAGONISTA' 
  AND UPPER(TRIM(city)) = 'BELO HORIZONTE' 
  AND inep_code IS NULL;

-- EE LAR DOS MENINOS (BELO HORIZONTE) - INEP: 322555
UPDATE schools 
SET inep_code = '322555' 
WHERE UPPER(TRIM(name)) = 'EE LAR DOS MENINOS' 
  AND UPPER(TRIM(city)) = 'BELO HORIZONTE' 
  AND inep_code IS NULL;

-- EE PROFESSOR NEIDSON RODRIGUES (BELO HORIZONTE) - INEP: 342432
UPDATE schools 
SET inep_code = '342432' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR NEIDSON RODRIGUES' 
  AND UPPER(TRIM(city)) = 'BELO HORIZONTE' 
  AND inep_code IS NULL;

-- EE PROFESSORA ALAÍDE LISBOA DE OLIVEIRA (BELO HORIZONTE) - INEP: 342459
UPDATE schools 
SET inep_code = '342459' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ALAÍDE LISBOA DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'BELO HORIZONTE' 
  AND inep_code IS NULL;

-- EE PROFESSORA HENRIQUETA LISBOA (BELO HORIZONTE) - INEP: 342424
UPDATE schools 
SET inep_code = '342424' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA HENRIQUETA LISBOA' 
  AND UPPER(TRIM(city)) = 'BELO HORIZONTE' 
  AND inep_code IS NULL;

-- EE ZILDA ARNS NEUMANN (BELO HORIZONTE) - INEP: 342440
UPDATE schools 
SET inep_code = '342440' 
WHERE UPPER(TRIM(name)) = 'EE ZILDA ARNS NEUMANN' 
  AND UPPER(TRIM(city)) = 'BELO HORIZONTE' 
  AND inep_code IS NULL;

-- EE DOUTOR GAMA CERQUEIRA (BELO VALE) - INEP: 106020
UPDATE schools 
SET inep_code = '106020' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR GAMA CERQUEIRA' 
  AND UPPER(TRIM(city)) = 'BELO VALE' 
  AND inep_code IS NULL;

-- EE DE FELIPE (BOM JESUS DO AMPARO) - INEP: 102806
UPDATE schools 
SET inep_code = '102806' 
WHERE UPPER(TRIM(name)) = 'EE DE FELIPE' 
  AND UPPER(TRIM(city)) = 'BOM JESUS DO AMPARO' 
  AND inep_code IS NULL;

-- EE EDMUNDO PENA (BOM JESUS DO AMPARO) - INEP: 102792
UPDATE schools 
SET inep_code = '102792' 
WHERE UPPER(TRIM(name)) = 'EE EDMUNDO PENA' 
  AND UPPER(TRIM(city)) = 'BOM JESUS DO AMPARO' 
  AND inep_code IS NULL;

-- EE ABELARDO DUARTE PASSOS (BRUMADINHO) - INEP: 351075
UPDATE schools 
SET inep_code = '351075' 
WHERE UPPER(TRIM(name)) = 'EE ABELARDO DUARTE PASSOS' 
  AND UPPER(TRIM(city)) = 'BRUMADINHO' 
  AND inep_code IS NULL;

-- EE SENADOR MELO VIANA (MOEDA) - INEP: 106437
UPDATE schools 
SET inep_code = '106437' 
WHERE UPPER(TRIM(name)) = 'EE SENADOR MELO VIANA' 
  AND UPPER(TRIM(city)) = 'MOEDA' 
  AND inep_code IS NULL;

-- EE MARIA JOSEFINA SALES WARDI (NOVA LIMA) - INEP: 305014
UPDATE schools 
SET inep_code = '305014' 
WHERE UPPER(TRIM(name)) = 'EE MARIA JOSEFINA SALES WARDI' 
  AND UPPER(TRIM(city)) = 'NOVA LIMA' 
  AND inep_code IS NULL;

-- EE JUQUINHA DE ALMEIDA (SABARÁ) - INEP: 222470
UPDATE schools 
SET inep_code = '222470' 
WHERE UPPER(TRIM(name)) = 'EE JUQUINHA DE ALMEIDA' 
  AND UPPER(TRIM(city)) = 'SABARÁ' 
  AND inep_code IS NULL;

-- EE PRESIDENTE JUSCELINO KUBITSCHEK DE OLIVEIRA (SABARÁ) - INEP: 318418
UPDATE schools 
SET inep_code = '318418' 
WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE JUSCELINO KUBITSCHEK DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'SABARÁ' 
  AND inep_code IS NULL;

-- EE PROFESSOR JOÃO DE ARRUDA PINTO (SABARÁ) - INEP: 291102
UPDATE schools 
SET inep_code = '291102' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOÃO DE ARRUDA PINTO' 
  AND UPPER(TRIM(city)) = 'SABARÁ' 
  AND inep_code IS NULL;

-- EE PROFESSORA NHANITA (SANTA BÁRBARA) - INEP: 346284
UPDATE schools 
SET inep_code = '346284' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA NHANITA' 
  AND UPPER(TRIM(city)) = 'SANTA BÁRBARA' 
  AND inep_code IS NULL;

-- COLÉGIO TIRADENTES PMMG - UNIDADE GAMELEIRA (BELO HORIZONTE) - INEP: 307696
UPDATE schools 
SET inep_code = '307696' 
WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG - UNIDADE GAMELEIRA' 
  AND UPPER(TRIM(city)) = 'BELO HORIZONTE' 
  AND inep_code IS NULL;

-- COLÉGIO TIRADENTES PMMG- UNIDADE NOSSA SENHORA DAS VITÓRIAS (BELO HORIZONTE) - INEP: 307718
UPDATE schools 
SET inep_code = '307718' 
WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG- UNIDADE NOSSA SENHORA DAS VITÓRIAS' 
  AND UPPER(TRIM(city)) = 'BELO HORIZONTE' 
  AND inep_code IS NULL;

-- EE EMÍLIA CERDEIRA (BELO HORIZONTE) - INEP: 246433
UPDATE schools 
SET inep_code = '246433' 
WHERE UPPER(TRIM(name)) = 'EE EMÍLIA CERDEIRA' 
  AND UPPER(TRIM(city)) = 'BELO HORIZONTE' 
  AND inep_code IS NULL;

-- COLÉGIO TIRADENTES PMMG (BETIM) - INEP: 321061
UPDATE schools 
SET inep_code = '321061' 
WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG' 
  AND UPPER(TRIM(city)) = 'BETIM' 
  AND inep_code IS NULL;

-- EE ANTÔNIO AUGUSTO RIBEIRO (BETIM) - INEP: 212598
UPDATE schools 
SET inep_code = '212598' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO AUGUSTO RIBEIRO' 
  AND UPPER(TRIM(city)) = 'BETIM' 
  AND inep_code IS NULL;

-- EE DO BAIRRO AMAZONAS (BETIM) - INEP: 215082
UPDATE schools 
SET inep_code = '215082' 
WHERE UPPER(TRIM(name)) = 'EE DO BAIRRO AMAZONAS' 
  AND UPPER(TRIM(city)) = 'BETIM' 
  AND inep_code IS NULL;

-- EE GABRIEL PASSOS (BETIM) - INEP: 361445
UPDATE schools 
SET inep_code = '361445' 
WHERE UPPER(TRIM(name)) = 'EE GABRIEL PASSOS' 
  AND UPPER(TRIM(city)) = 'BETIM' 
  AND inep_code IS NULL;

-- EE PROFESSOR OSVALDO FRANCO (BETIM) - INEP: 212601
UPDATE schools 
SET inep_code = '212601' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR OSVALDO FRANCO' 
  AND UPPER(TRIM(city)) = 'BETIM' 
  AND inep_code IS NULL;

-- EE VINÍCIUS DE MORAES (BETIM) - INEP: 353787
UPDATE schools 
SET inep_code = '353787' 
WHERE UPPER(TRIM(name)) = 'EE VINÍCIUS DE MORAES' 
  AND UPPER(TRIM(city)) = 'BETIM' 
  AND inep_code IS NULL;

-- COLÉGIO TIRADENTES PMMG (CONTAGEM) - INEP: 307726
UPDATE schools 
SET inep_code = '307726' 
WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG' 
  AND UPPER(TRIM(city)) = 'CONTAGEM' 
  AND inep_code IS NULL;

-- COLÉGIO TIRADENTES PMMG - UNIDADE AVELINO CAMARGOS (CONTAGEM) - INEP: 368903
UPDATE schools 
SET inep_code = '368903' 
WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG - UNIDADE AVELINO CAMARGOS' 
  AND UPPER(TRIM(city)) = 'CONTAGEM' 
  AND inep_code IS NULL;

-- EE DE ENSINO MÉDIO (CONTAGEM) - INEP: 349283
UPDATE schools 
SET inep_code = '349283' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' 
  AND UPPER(TRIM(city)) = 'CONTAGEM' 
  AND inep_code IS NULL;

-- EE MARIA DE SALLES FERREIRA (CONTAGEM) - INEP: 212644
UPDATE schools 
SET inep_code = '212644' 
WHERE UPPER(TRIM(name)) = 'EE MARIA DE SALLES FERREIRA' 
  AND UPPER(TRIM(city)) = 'CONTAGEM' 
  AND inep_code IS NULL;

-- EE PROFESSOR PAULO FREIRE (CONTAGEM) - INEP: 326780
UPDATE schools 
SET inep_code = '326780' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR PAULO FREIRE' 
  AND UPPER(TRIM(city)) = 'CONTAGEM' 
  AND inep_code IS NULL;

-- EE ROBERTO FERNANDES (CONTAGEM) - INEP: 349275
UPDATE schools 
SET inep_code = '349275' 
WHERE UPPER(TRIM(name)) = 'EE ROBERTO FERNANDES' 
  AND UPPER(TRIM(city)) = 'CONTAGEM' 
  AND inep_code IS NULL;

-- EE VINÍCIUS DE MORAES (CONTAGEM) - INEP: 212652
UPDATE schools 
SET inep_code = '212652' 
WHERE UPPER(TRIM(name)) = 'EE VINÍCIUS DE MORAES' 
  AND UPPER(TRIM(city)) = 'CONTAGEM' 
  AND inep_code IS NULL;

-- EE MONTE SINAI (ESMERALDAS) - INEP: 353868
UPDATE schools 
SET inep_code = '353868' 
WHERE UPPER(TRIM(name)) = 'EE MONTE SINAI' 
  AND UPPER(TRIM(city)) = 'ESMERALDAS' 
  AND inep_code IS NULL;

-- EE PROFESSOR RAYMUNDO CÂNDIDO (ESMERALDAS) - INEP: 330647
UPDATE schools 
SET inep_code = '330647' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR RAYMUNDO CÂNDIDO' 
  AND UPPER(TRIM(city)) = 'ESMERALDAS' 
  AND inep_code IS NULL;

-- EE ANTÔNIO MARINHO CAMPOS (IBIRITÉ) - INEP: 231665
UPDATE schools 
SET inep_code = '231665' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO MARINHO CAMPOS' 
  AND UPPER(TRIM(city)) = 'IBIRITÉ' 
  AND inep_code IS NULL;

-- EE ANTÔNIO PINHEIRO DINIZ (IBIRITÉ) - INEP: 322989
UPDATE schools 
SET inep_code = '322989' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO PINHEIRO DINIZ' 
  AND UPPER(TRIM(city)) = 'IBIRITÉ' 
  AND inep_code IS NULL;

-- EE CORA CORALINA (IBIRITÉ) - INEP: 270407
UPDATE schools 
SET inep_code = '270407' 
WHERE UPPER(TRIM(name)) = 'EE CORA CORALINA' 
  AND UPPER(TRIM(city)) = 'IBIRITÉ' 
  AND inep_code IS NULL;

-- EE DE ENSINO FUNDAMENTAL E MÉDIO (IBIRITÉ) - INEP: 353507
UPDATE schools 
SET inep_code = '353507' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL E MÉDIO' 
  AND UPPER(TRIM(city)) = 'IBIRITÉ' 
  AND inep_code IS NULL;

-- EE IMPERATRIZ PIMENTA (IBIRITÉ) - INEP: 232483
UPDATE schools 
SET inep_code = '232483' 
WHERE UPPER(TRIM(name)) = 'EE IMPERATRIZ PIMENTA' 
  AND UPPER(TRIM(city)) = 'IBIRITÉ' 
  AND inep_code IS NULL;

-- EE JOÃO FERREIRA DE FREITAS (IBIRITÉ) - INEP: 223590
UPDATE schools 
SET inep_code = '223590' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO FERREIRA DE FREITAS' 
  AND UPPER(TRIM(city)) = 'IBIRITÉ' 
  AND inep_code IS NULL;

-- EE MARIA ALVES NAGY VARGA (IBIRITÉ) - INEP: 231657
UPDATE schools 
SET inep_code = '231657' 
WHERE UPPER(TRIM(name)) = 'EE MARIA ALVES NAGY VARGA' 
  AND UPPER(TRIM(city)) = 'IBIRITÉ' 
  AND inep_code IS NULL;

-- EE PROFESSORA ELZA CARDOSO RANGEL (IBIRITÉ) - INEP: 231673
UPDATE schools 
SET inep_code = '231673' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ELZA CARDOSO RANGEL' 
  AND UPPER(TRIM(city)) = 'IBIRITÉ' 
  AND inep_code IS NULL;

-- EE CRISTIANO CHAVES DE OLIVEIRA (IGARAPÉ) - INEP: 254720
UPDATE schools 
SET inep_code = '254720' 
WHERE UPPER(TRIM(name)) = 'EE CRISTIANO CHAVES DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'IGARAPÉ' 
  AND inep_code IS NULL;

-- EE JOELMA ALVES DE OLIVEIRA (IGARAPÉ) - INEP: 212466
UPDATE schools 
SET inep_code = '212466' 
WHERE UPPER(TRIM(name)) = 'EE JOELMA ALVES DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'IGARAPÉ' 
  AND inep_code IS NULL;

-- EE ANTÔNIO RIBEIRO DA SILVA (SÃO JOAQUIM DE BICAS) - INEP: 326798
UPDATE schools 
SET inep_code = '326798' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO RIBEIRO DA SILVA' 
  AND UPPER(TRIM(city)) = 'SÃO JOAQUIM DE BICAS' 
  AND inep_code IS NULL;

-- EE PADRE CARLOS ROBERTO MARQUES (SÃO JOAQUIM DE BICAS) - INEP: 309842
UPDATE schools 
SET inep_code = '309842' 
WHERE UPPER(TRIM(name)) = 'EE PADRE CARLOS ROBERTO MARQUES' 
  AND UPPER(TRIM(city)) = 'SÃO JOAQUIM DE BICAS' 
  AND inep_code IS NULL;

-- EE PATROCÍNIA CÂNDIDA DE OLIVEIRA (SÃO JOAQUIM DE BICAS) - INEP: 231291
UPDATE schools 
SET inep_code = '231291' 
WHERE UPPER(TRIM(name)) = 'EE PATROCÍNIA CÂNDIDA DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'SÃO JOAQUIM DE BICAS' 
  AND inep_code IS NULL;

-- EE JOSÉ PEREIRA DOS SANTOS (SARZEDO) - INEP: 266094
UPDATE schools 
SET inep_code = '266094' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ PEREIRA DOS SANTOS' 
  AND UPPER(TRIM(city)) = 'SARZEDO' 
  AND inep_code IS NULL;


COMMIT;
