-- Lote 4 de 7
-- Updates 901 a 1200

BEGIN;

-- EE PROFESSOR JOSÉ HUGO GUIMARÃES (CARMO DO PARANAÍBA) - INEP: 118494
UPDATE schools 
SET inep_code = '118494' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOSÉ HUGO GUIMARÃES' 
  AND UPPER(TRIM(city)) = 'CARMO DO PARANAÍBA' 
  AND inep_code IS NULL;

-- EE SIZENANDO AMARAL DE EDUCAÇÃO ESPECIAL (CARMO DO PARANAÍBA) - INEP: 118541
UPDATE schools 
SET inep_code = '118541' 
WHERE UPPER(TRIM(name)) = 'EE SIZENANDO AMARAL DE EDUCAÇÃO ESPECIAL' 
  AND UPPER(TRIM(city)) = 'CARMO DO PARANAÍBA' 
  AND inep_code IS NULL;

-- CESEC AUGUSTA RAQUEL DA SILVEIRA (LAGAMAR) - INEP: 118648
UPDATE schools 
SET inep_code = '118648' 
WHERE UPPER(TRIM(name)) = 'CESEC AUGUSTA RAQUEL DA SILVEIRA' 
  AND UPPER(TRIM(city)) = 'LAGAMAR' 
  AND inep_code IS NULL;

-- EE AFONSO CORRÊA (LAGAMAR) - INEP: 118575
UPDATE schools 
SET inep_code = '118575' 
WHERE UPPER(TRIM(name)) = 'EE AFONSO CORRÊA' 
  AND UPPER(TRIM(city)) = 'LAGAMAR' 
  AND inep_code IS NULL;

-- EE AMÉRICO ALVES (LAGAMAR) - INEP: 118583
UPDATE schools 
SET inep_code = '118583' 
WHERE UPPER(TRIM(name)) = 'EE AMÉRICO ALVES' 
  AND UPPER(TRIM(city)) = 'LAGAMAR' 
  AND inep_code IS NULL;

-- EE DOM BOSCO (LAGAMAR) - INEP: 118605
UPDATE schools 
SET inep_code = '118605' 
WHERE UPPER(TRIM(name)) = 'EE DOM BOSCO' 
  AND UPPER(TRIM(city)) = 'LAGAMAR' 
  AND inep_code IS NULL;

-- EE CORONEL CRISTIANO (LAGOA FORMOSA) - INEP: 118656
UPDATE schools 
SET inep_code = '118656' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL CRISTIANO' 
  AND UPPER(TRIM(city)) = 'LAGOA FORMOSA' 
  AND inep_code IS NULL;

-- EE JOSÉ MARCIANO BRANDÃO (LAGOA FORMOSA) - INEP: 118672
UPDATE schools 
SET inep_code = '118672' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ MARCIANO BRANDÃO' 
  AND UPPER(TRIM(city)) = 'LAGOA FORMOSA' 
  AND inep_code IS NULL;

-- EE NOSSA SENHORA DA PIEDADE (LAGOA FORMOSA) - INEP: 118664
UPDATE schools 
SET inep_code = '118664' 
WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DA PIEDADE' 
  AND UPPER(TRIM(city)) = 'LAGOA FORMOSA' 
  AND inep_code IS NULL;

-- EE SANTA TEREZINHA (LAGOA GRANDE) - INEP: 119172
UPDATE schools 
SET inep_code = '119172' 
WHERE UPPER(TRIM(name)) = 'EE SANTA TEREZINHA' 
  AND UPPER(TRIM(city)) = 'LAGOA GRANDE' 
  AND inep_code IS NULL;

-- EE ANA ROCHA (MATUTINA) - INEP: 118737
UPDATE schools 
SET inep_code = '118737' 
WHERE UPPER(TRIM(name)) = 'EE ANA ROCHA' 
  AND UPPER(TRIM(city)) = 'MATUTINA' 
  AND inep_code IS NULL;

-- CESEC ORDALINA VIEIRA RORIZ DA COSTA (PATOS DE MINAS) - INEP: 118851
UPDATE schools 
SET inep_code = '118851' 
WHERE UPPER(TRIM(name)) = 'CESEC ORDALINA VIEIRA RORIZ DA COSTA' 
  AND UPPER(TRIM(city)) = 'PATOS DE MINAS' 
  AND inep_code IS NULL;

-- COLÉGIO TIRADENTES PMMG (PATOS DE MINAS) - INEP: 118770
UPDATE schools 
SET inep_code = '118770' 
WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG' 
  AND UPPER(TRIM(city)) = 'PATOS DE MINAS' 
  AND inep_code IS NULL;

-- EE ABÍLIO CAIXETA DE QUEIROZ (PATOS DE MINAS) - INEP: 118818
UPDATE schools 
SET inep_code = '118818' 
WHERE UPPER(TRIM(name)) = 'EE ABÍLIO CAIXETA DE QUEIROZ' 
  AND UPPER(TRIM(city)) = 'PATOS DE MINAS' 
  AND inep_code IS NULL;

-- EE ABNER AFONSO (PATOS DE MINAS) - INEP: 118761
UPDATE schools 
SET inep_code = '118761' 
WHERE UPPER(TRIM(name)) = 'EE ABNER AFONSO' 
  AND UPPER(TRIM(city)) = 'PATOS DE MINAS' 
  AND inep_code IS NULL;

-- EE ADELAIDE MACIEL (PATOS DE MINAS) - INEP: 118788
UPDATE schools 
SET inep_code = '118788' 
WHERE UPPER(TRIM(name)) = 'EE ADELAIDE MACIEL' 
  AND UPPER(TRIM(city)) = 'PATOS DE MINAS' 
  AND inep_code IS NULL;

-- EE AGROTÉCNICA AFONSO QUEIROZ (PATOS DE MINAS) - INEP: 212229
UPDATE schools 
SET inep_code = '212229' 
WHERE UPPER(TRIM(name)) = 'EE AGROTÉCNICA AFONSO QUEIROZ' 
  AND UPPER(TRIM(city)) = 'PATOS DE MINAS' 
  AND inep_code IS NULL;

-- EE ARLINDO PORTO (PATOS DE MINAS) - INEP: 305367
UPDATE schools 
SET inep_code = '305367' 
WHERE UPPER(TRIM(name)) = 'EE ARLINDO PORTO' 
  AND UPPER(TRIM(city)) = 'PATOS DE MINAS' 
  AND inep_code IS NULL;

-- EE CÔNEGO GETÚLIO (PATOS DE MINAS) - INEP: 118842
UPDATE schools 
SET inep_code = '118842' 
WHERE UPPER(TRIM(name)) = 'EE CÔNEGO GETÚLIO' 
  AND UPPER(TRIM(city)) = 'PATOS DE MINAS' 
  AND inep_code IS NULL;

-- EE DEIRÓ EUNÁPIO BORGES (PATOS DE MINAS) - INEP: 118800
UPDATE schools 
SET inep_code = '118800' 
WHERE UPPER(TRIM(name)) = 'EE DEIRÓ EUNÁPIO BORGES' 
  AND UPPER(TRIM(city)) = 'PATOS DE MINAS' 
  AND inep_code IS NULL;

-- EE DONA GUIOMAR DE MELO (PATOS DE MINAS) - INEP: 118923
UPDATE schools 
SET inep_code = '118923' 
WHERE UPPER(TRIM(name)) = 'EE DONA GUIOMAR DE MELO' 
  AND UPPER(TRIM(city)) = 'PATOS DE MINAS' 
  AND inep_code IS NULL;

-- EE DOUTOR PAULO BORGES (PATOS DE MINAS) - INEP: 118796
UPDATE schools 
SET inep_code = '118796' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR PAULO BORGES' 
  AND UPPER(TRIM(city)) = 'PATOS DE MINAS' 
  AND inep_code IS NULL;

-- EE DOUTOR SEBASTIÃO SILVÉRIO DE FARIA (PATOS DE MINAS) - INEP: 326640
UPDATE schools 
SET inep_code = '326640' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR SEBASTIÃO SILVÉRIO DE FARIA' 
  AND UPPER(TRIM(city)) = 'PATOS DE MINAS' 
  AND inep_code IS NULL;

-- EE EUSTÁQUIO JOSÉ DA SILVA (PATOS DE MINAS) - INEP: 342483
UPDATE schools 
SET inep_code = '342483' 
WHERE UPPER(TRIM(name)) = 'EE EUSTÁQUIO JOSÉ DA SILVA' 
  AND UPPER(TRIM(city)) = 'PATOS DE MINAS' 
  AND inep_code IS NULL;

-- EE ILÍDIO CAIXETA DE MELO (PATOS DE MINAS) - INEP: 118834
UPDATE schools 
SET inep_code = '118834' 
WHERE UPPER(TRIM(name)) = 'EE ILÍDIO CAIXETA DE MELO' 
  AND UPPER(TRIM(city)) = 'PATOS DE MINAS' 
  AND inep_code IS NULL;

-- EE JOÃO BARBOSA PORTO (PATOS DE MINAS) - INEP: 119032
UPDATE schools 
SET inep_code = '119032' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO BARBOSA PORTO' 
  AND UPPER(TRIM(city)) = 'PATOS DE MINAS' 
  AND inep_code IS NULL;

-- EE JUCA MANDU (PATOS DE MINAS) - INEP: 119083
UPDATE schools 
SET inep_code = '119083' 
WHERE UPPER(TRIM(name)) = 'EE JUCA MANDU' 
  AND UPPER(TRIM(city)) = 'PATOS DE MINAS' 
  AND inep_code IS NULL;

-- EE MAJOR MOTA (PATOS DE MINAS) - INEP: 119067
UPDATE schools 
SET inep_code = '119067' 
WHERE UPPER(TRIM(name)) = 'EE MAJOR MOTA' 
  AND UPPER(TRIM(city)) = 'PATOS DE MINAS' 
  AND inep_code IS NULL;

-- EE MARCOLINO DE BARROS (PATOS DE MINAS) - INEP: 118958
UPDATE schools 
SET inep_code = '118958' 
WHERE UPPER(TRIM(name)) = 'EE MARCOLINO DE BARROS' 
  AND UPPER(TRIM(city)) = 'PATOS DE MINAS' 
  AND inep_code IS NULL;

-- EE MONSENHOR FLEURY (PATOS DE MINAS) - INEP: 118966
UPDATE schools 
SET inep_code = '118966' 
WHERE UPPER(TRIM(name)) = 'EE MONSENHOR FLEURY' 
  AND UPPER(TRIM(city)) = 'PATOS DE MINAS' 
  AND inep_code IS NULL;

-- EE PADRE ALMIR NEVES DE MEDEIROS (PATOS DE MINAS) - INEP: 212237
UPDATE schools 
SET inep_code = '212237' 
WHERE UPPER(TRIM(name)) = 'EE PADRE ALMIR NEVES DE MEDEIROS' 
  AND UPPER(TRIM(city)) = 'PATOS DE MINAS' 
  AND inep_code IS NULL;

-- EE PROFESSOR ANTÔNIO DIAS MACIEL (PATOS DE MINAS) - INEP: 118982
UPDATE schools 
SET inep_code = '118982' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ANTÔNIO DIAS MACIEL' 
  AND UPPER(TRIM(city)) = 'PATOS DE MINAS' 
  AND inep_code IS NULL;

-- EE PROFESSOR MANOEL LOPES NOGUEIRA (PATOS DE MINAS) - INEP: 305359
UPDATE schools 
SET inep_code = '305359' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR MANOEL LOPES NOGUEIRA' 
  AND UPPER(TRIM(city)) = 'PATOS DE MINAS' 
  AND inep_code IS NULL;

-- EE PROFESSOR MODESTO (PATOS DE MINAS) - INEP: 118991
UPDATE schools 
SET inep_code = '118991' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR MODESTO' 
  AND UPPER(TRIM(city)) = 'PATOS DE MINAS' 
  AND inep_code IS NULL;

-- EE PROFESSOR RENÉ DE DEUS VIEIRA (PATOS DE MINAS) - INEP: 360813
UPDATE schools 
SET inep_code = '360813' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR RENÉ DE DEUS VIEIRA' 
  AND UPPER(TRIM(city)) = 'PATOS DE MINAS' 
  AND inep_code IS NULL;

-- EE PROFESSOR ZAMA MACIEL (PATOS DE MINAS) - INEP: 119024
UPDATE schools 
SET inep_code = '119024' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ZAMA MACIEL' 
  AND UPPER(TRIM(city)) = 'PATOS DE MINAS' 
  AND inep_code IS NULL;

-- EE PROFESSORA PAULINA DE MELO PORTO (PATOS DE MINAS) - INEP: 353485
UPDATE schools 
SET inep_code = '353485' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA PAULINA DE MELO PORTO' 
  AND UPPER(TRIM(city)) = 'PATOS DE MINAS' 
  AND inep_code IS NULL;

-- EE SANTA TEREZINHA (PATOS DE MINAS) - INEP: 119016
UPDATE schools 
SET inep_code = '119016' 
WHERE UPPER(TRIM(name)) = 'EE SANTA TEREZINHA' 
  AND UPPER(TRIM(city)) = 'PATOS DE MINAS' 
  AND inep_code IS NULL;

-- CESEC TANCREDO NEVES (PRESIDENTE OLEGÁRIO) - INEP: 232645
UPDATE schools 
SET inep_code = '232645' 
WHERE UPPER(TRIM(name)) = 'CESEC TANCREDO NEVES' 
  AND UPPER(TRIM(city)) = 'PRESIDENTE OLEGÁRIO' 
  AND inep_code IS NULL;

-- EE DE ENSINO FUNDAMENTAL - ANOS INICIAIS E FINAIS (PRESIDENTE OLEGÁRIO) - INEP: 375853
UPDATE schools 
SET inep_code = '375853' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL - ANOS INICIAIS E FINAIS' 
  AND UPPER(TRIM(city)) = 'PRESIDENTE OLEGÁRIO' 
  AND inep_code IS NULL;

-- EE DE PONTE FIRME (PRESIDENTE OLEGÁRIO) - INEP: 119199
UPDATE schools 
SET inep_code = '119199' 
WHERE UPPER(TRIM(name)) = 'EE DE PONTE FIRME' 
  AND UPPER(TRIM(city)) = 'PRESIDENTE OLEGÁRIO' 
  AND inep_code IS NULL;

-- EE PADRE JOSÉ ANDRÉ CALDEIRA COIMBRA (PRESIDENTE OLEGÁRIO) - INEP: 119121
UPDATE schools 
SET inep_code = '119121' 
WHERE UPPER(TRIM(name)) = 'EE PADRE JOSÉ ANDRÉ CALDEIRA COIMBRA' 
  AND UPPER(TRIM(city)) = 'PRESIDENTE OLEGÁRIO' 
  AND inep_code IS NULL;

-- EE PRESIDENTE VARGAS (PRESIDENTE OLEGÁRIO) - INEP: 119164
UPDATE schools 
SET inep_code = '119164' 
WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE VARGAS' 
  AND UPPER(TRIM(city)) = 'PRESIDENTE OLEGÁRIO' 
  AND inep_code IS NULL;

-- EE DOUTOR ADIRON GONÇALVES BOAVENTURA (RIO PARANAÍBA) - INEP: 122629
UPDATE schools 
SET inep_code = '122629' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR ADIRON GONÇALVES BOAVENTURA' 
  AND UPPER(TRIM(city)) = 'RIO PARANAÍBA' 
  AND inep_code IS NULL;

-- EE ANTERO MAGALHÃES DE AGUIAR (SANTA ROSA DA SERRA) - INEP: 119458
UPDATE schools 
SET inep_code = '119458' 
WHERE UPPER(TRIM(name)) = 'EE ANTERO MAGALHÃES DE AGUIAR' 
  AND UPPER(TRIM(city)) = 'SANTA ROSA DA SERRA' 
  AND inep_code IS NULL;

-- EE ZICO MENDONÇA (SÃO GONÇALO DO ABAETÉ) - INEP: 119504
UPDATE schools 
SET inep_code = '119504' 
WHERE UPPER(TRIM(name)) = 'EE ZICO MENDONÇA' 
  AND UPPER(TRIM(city)) = 'SÃO GONÇALO DO ABAETÉ' 
  AND inep_code IS NULL;

-- CESEC MARIA COELI FRANCO (SÃO GOTARDO) - INEP: 119601
UPDATE schools 
SET inep_code = '119601' 
WHERE UPPER(TRIM(name)) = 'CESEC MARIA COELI FRANCO' 
  AND UPPER(TRIM(city)) = 'SÃO GOTARDO' 
  AND inep_code IS NULL;

-- EE CONSELHEIRO AFONSO PENA (SÃO GOTARDO) - INEP: 318531
UPDATE schools 
SET inep_code = '318531' 
WHERE UPPER(TRIM(name)) = 'EE CONSELHEIRO AFONSO PENA' 
  AND UPPER(TRIM(city)) = 'SÃO GOTARDO' 
  AND inep_code IS NULL;

-- EE CORONEL HERMENEGILDO LADEIRA (SÃO GOTARDO) - INEP: 119628
UPDATE schools 
SET inep_code = '119628' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL HERMENEGILDO LADEIRA' 
  AND UPPER(TRIM(city)) = 'SÃO GOTARDO' 
  AND inep_code IS NULL;

-- EE CORONEL OSCAR PRADOS (SÃO GOTARDO) - INEP: 119539
UPDATE schools 
SET inep_code = '119539' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL OSCAR PRADOS' 
  AND UPPER(TRIM(city)) = 'SÃO GOTARDO' 
  AND inep_code IS NULL;

-- EE JOSÉ CAETANO RIBEIRO (SÃO GOTARDO) - INEP: 119598
UPDATE schools 
SET inep_code = '119598' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ CAETANO RIBEIRO' 
  AND UPPER(TRIM(city)) = 'SÃO GOTARDO' 
  AND inep_code IS NULL;

-- EE PADRE SINFRÔNIO BAHIA (SÃO GOTARDO) - INEP: 119571
UPDATE schools 
SET inep_code = '119571' 
WHERE UPPER(TRIM(name)) = 'EE PADRE SINFRÔNIO BAHIA' 
  AND UPPER(TRIM(city)) = 'SÃO GOTARDO' 
  AND inep_code IS NULL;

-- EE SÃO PIO X (SÃO GOTARDO) - INEP: 119563
UPDATE schools 
SET inep_code = '119563' 
WHERE UPPER(TRIM(name)) = 'EE SÃO PIO X' 
  AND UPPER(TRIM(city)) = 'SÃO GOTARDO' 
  AND inep_code IS NULL;

-- EE PADRE JOSÉ COELHO (TIROS) - INEP: 119679
UPDATE schools 
SET inep_code = '119679' 
WHERE UPPER(TRIM(name)) = 'EE PADRE JOSÉ COELHO' 
  AND UPPER(TRIM(city)) = 'TIROS' 
  AND inep_code IS NULL;

-- EE JOÃO PEREIRA BRANDÃO (VARJÃO DE MINAS) - INEP: 119521
UPDATE schools 
SET inep_code = '119521' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO PEREIRA BRANDÃO' 
  AND UPPER(TRIM(city)) = 'VARJÃO DE MINAS' 
  AND inep_code IS NULL;

-- EE CÂNDIDA CORTES CORRÊA (CRUZEIRO DA FORTALEZA) - INEP: 278718
UPDATE schools 
SET inep_code = '278718' 
WHERE UPPER(TRIM(name)) = 'EE CÂNDIDA CORTES CORRÊA' 
  AND UPPER(TRIM(city)) = 'CRUZEIRO DA FORTALEZA' 
  AND inep_code IS NULL;

-- EE IRMÃOS GUIMARÃES (GUIMARÂNIA) - INEP: 198943
UPDATE schools 
SET inep_code = '198943' 
WHERE UPPER(TRIM(name)) = 'EE IRMÃOS GUIMARÃES' 
  AND UPPER(TRIM(city)) = 'GUIMARÂNIA' 
  AND inep_code IS NULL;

-- EE DOUTOR PEDRO DIAS DOS REIS (IBIÁ) - INEP: 159026
UPDATE schools 
SET inep_code = '159026' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR PEDRO DIAS DOS REIS' 
  AND UPPER(TRIM(city)) = 'IBIÁ' 
  AND inep_code IS NULL;

-- EE SÃO JOSÉ (IBIÁ) - INEP: 159069
UPDATE schools 
SET inep_code = '159069' 
WHERE UPPER(TRIM(name)) = 'EE SÃO JOSÉ' 
  AND UPPER(TRIM(city)) = 'IBIÁ' 
  AND inep_code IS NULL;

-- EE PADRE EUSTÁQUIO (IRAÍ DE MINAS) - INEP: 198960
UPDATE schools 
SET inep_code = '198960' 
WHERE UPPER(TRIM(name)) = 'EE PADRE EUSTÁQUIO' 
  AND UPPER(TRIM(city)) = 'IRAÍ DE MINAS' 
  AND inep_code IS NULL;

-- EE SÃO JOSÉ DO BARREIRO (IRAÍ DE MINAS) - INEP: 198986
UPDATE schools 
SET inep_code = '198986' 
WHERE UPPER(TRIM(name)) = 'EE SÃO JOSÉ DO BARREIRO' 
  AND UPPER(TRIM(city)) = 'IRAÍ DE MINAS' 
  AND inep_code IS NULL;

-- CESEC DORALICE ALVES RODRIGUES (PATROCÍNIO) - INEP: 199150
UPDATE schools 
SET inep_code = '199150' 
WHERE UPPER(TRIM(name)) = 'CESEC DORALICE ALVES RODRIGUES' 
  AND UPPER(TRIM(city)) = 'PATROCÍNIO' 
  AND inep_code IS NULL;

-- EE AMIR AMARAL (PATROCÍNIO) - INEP: 198994
UPDATE schools 
SET inep_code = '198994' 
WHERE UPPER(TRIM(name)) = 'EE AMIR AMARAL' 
  AND UPPER(TRIM(city)) = 'PATROCÍNIO' 
  AND inep_code IS NULL;

-- EE CORONEL ELMIRO ALVES DO NASCIMENTO (PATROCÍNIO) - INEP: 199214
UPDATE schools 
SET inep_code = '199214' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL ELMIRO ALVES DO NASCIMENTO' 
  AND UPPER(TRIM(city)) = 'PATROCÍNIO' 
  AND inep_code IS NULL;

-- EE CORONEL JOÃO CÂNDIDO DE AGUIAR (PATROCÍNIO) - INEP: 199087
UPDATE schools 
SET inep_code = '199087' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL JOÃO CÂNDIDO DE AGUIAR' 
  AND UPPER(TRIM(city)) = 'PATROCÍNIO' 
  AND inep_code IS NULL;

-- EE DALVA STELA DE QUEIROZ (PATROCÍNIO) - INEP: 199141
UPDATE schools 
SET inep_code = '199141' 
WHERE UPPER(TRIM(name)) = 'EE DALVA STELA DE QUEIROZ' 
  AND UPPER(TRIM(city)) = 'PATROCÍNIO' 
  AND inep_code IS NULL;

-- EE DE ENSINO FUNDAMENTAL E MÉDIO (PATROCÍNIO) - INEP: 327590
UPDATE schools 
SET inep_code = '327590' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL E MÉDIO' 
  AND UPPER(TRIM(city)) = 'PATROCÍNIO' 
  AND inep_code IS NULL;

-- EE DOM LUSTOSA (PATROCÍNIO) - INEP: 199010
UPDATE schools 
SET inep_code = '199010' 
WHERE UPPER(TRIM(name)) = 'EE DOM LUSTOSA' 
  AND UPPER(TRIM(city)) = 'PATROCÍNIO' 
  AND inep_code IS NULL;

-- EE DONA COTINHA (PATROCÍNIO) - INEP: 199036
UPDATE schools 
SET inep_code = '199036' 
WHERE UPPER(TRIM(name)) = 'EE DONA COTINHA' 
  AND UPPER(TRIM(city)) = 'PATROCÍNIO' 
  AND inep_code IS NULL;

-- EE IRMÃ GISLENE (PATROCÍNIO) - INEP: 199061
UPDATE schools 
SET inep_code = '199061' 
WHERE UPPER(TRIM(name)) = 'EE IRMÃ GISLENE' 
  AND UPPER(TRIM(city)) = 'PATROCÍNIO' 
  AND inep_code IS NULL;

-- EE JOAQUIM DIAS (PATROCÍNIO) - INEP: 199095
UPDATE schools 
SET inep_code = '199095' 
WHERE UPPER(TRIM(name)) = 'EE JOAQUIM DIAS' 
  AND UPPER(TRIM(city)) = 'PATROCÍNIO' 
  AND inep_code IS NULL;

-- EE JOSÉ EDUARDO AQUINO (PATROCÍNIO) - INEP: 199133
UPDATE schools 
SET inep_code = '199133' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ EDUARDO AQUINO' 
  AND UPPER(TRIM(city)) = 'PATROCÍNIO' 
  AND inep_code IS NULL;

-- EE LÍBIA LASSI LOPES (PATROCÍNIO) - INEP: 218090
UPDATE schools 
SET inep_code = '218090' 
WHERE UPPER(TRIM(name)) = 'EE LÍBIA LASSI LOPES' 
  AND UPPER(TRIM(city)) = 'PATROCÍNIO' 
  AND inep_code IS NULL;

-- EE MARIANA TAVARES (PATROCÍNIO) - INEP: 199109
UPDATE schools 
SET inep_code = '199109' 
WHERE UPPER(TRIM(name)) = 'EE MARIANA TAVARES' 
  AND UPPER(TRIM(city)) = 'PATROCÍNIO' 
  AND inep_code IS NULL;

-- EE NELY AMARAL (PATROCÍNIO) - INEP: 199117
UPDATE schools 
SET inep_code = '199117' 
WHERE UPPER(TRIM(name)) = 'EE NELY AMARAL' 
  AND UPPER(TRIM(city)) = 'PATROCÍNIO' 
  AND inep_code IS NULL;

-- EE ODILON BEHRENS (PATROCÍNIO) - INEP: 199184
UPDATE schools 
SET inep_code = '199184' 
WHERE UPPER(TRIM(name)) = 'EE ODILON BEHRENS' 
  AND UPPER(TRIM(city)) = 'PATROCÍNIO' 
  AND inep_code IS NULL;

-- EE PROFESSORA CÉLIA LEMOS (PATROCÍNIO) - INEP: 218103
UPDATE schools 
SET inep_code = '218103' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA CÉLIA LEMOS' 
  AND UPPER(TRIM(city)) = 'PATROCÍNIO' 
  AND inep_code IS NULL;

-- EE PROFESSORA IRMA CARVALHO (PATROCÍNIO) - INEP: 238538
UPDATE schools 
SET inep_code = '238538' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA IRMA CARVALHO' 
  AND UPPER(TRIM(city)) = 'PATROCÍNIO' 
  AND inep_code IS NULL;

-- EE PROFESSORA ORMY ARAÚJO AMARAL (PATROCÍNIO) - INEP: 310603
UPDATE schools 
SET inep_code = '310603' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ORMY ARAÚJO AMARAL' 
  AND UPPER(TRIM(city)) = 'PATROCÍNIO' 
  AND inep_code IS NULL;

-- EE TEREZINHA MOREIRA MARRA (PATROCÍNIO) - INEP: 356794
UPDATE schools 
SET inep_code = '356794' 
WHERE UPPER(TRIM(name)) = 'EE TEREZINHA MOREIRA MARRA' 
  AND UPPER(TRIM(city)) = 'PATROCÍNIO' 
  AND inep_code IS NULL;

-- EE VENINA TAVARES AMARAL (PATROCÍNIO) - INEP: 199168
UPDATE schools 
SET inep_code = '199168' 
WHERE UPPER(TRIM(name)) = 'EE VENINA TAVARES AMARAL' 
  AND UPPER(TRIM(city)) = 'PATROCÍNIO' 
  AND inep_code IS NULL;

-- EE HORÁCIO AFONSO (PERDIZES) - INEP: 159344
UPDATE schools 
SET inep_code = '159344' 
WHERE UPPER(TRIM(name)) = 'EE HORÁCIO AFONSO' 
  AND UPPER(TRIM(city)) = 'PERDIZES' 
  AND inep_code IS NULL;

-- EE JOSEFA MARGARIDA TRINDADE (PERDIZES) - INEP: 159352
UPDATE schools 
SET inep_code = '159352' 
WHERE UPPER(TRIM(name)) = 'EE JOSEFA MARGARIDA TRINDADE' 
  AND UPPER(TRIM(city)) = 'PERDIZES' 
  AND inep_code IS NULL;

-- EE PADRE JOÃO BALKER (PERDIZES) - INEP: 159387
UPDATE schools 
SET inep_code = '159387' 
WHERE UPPER(TRIM(name)) = 'EE PADRE JOÃO BALKER' 
  AND UPPER(TRIM(city)) = 'PERDIZES' 
  AND inep_code IS NULL;

-- EE PREFEITO VIRMONDES AFONSO (PERDIZES) - INEP: 326704
UPDATE schools 
SET inep_code = '326704' 
WHERE UPPER(TRIM(name)) = 'EE PREFEITO VIRMONDES AFONSO' 
  AND UPPER(TRIM(city)) = 'PERDIZES' 
  AND inep_code IS NULL;

-- EE CORNÉLIA REGINA (SERRA DO SALITRE) - INEP: 199303
UPDATE schools 
SET inep_code = '199303' 
WHERE UPPER(TRIM(name)) = 'EE CORNÉLIA REGINA' 
  AND UPPER(TRIM(city)) = 'SERRA DO SALITRE' 
  AND inep_code IS NULL;

-- EE SERRA DO SALITRE (SERRA DO SALITRE) - INEP: 199265
UPDATE schools 
SET inep_code = '199265' 
WHERE UPPER(TRIM(name)) = 'EE SERRA DO SALITRE' 
  AND UPPER(TRIM(city)) = 'SERRA DO SALITRE' 
  AND inep_code IS NULL;

-- EE TEREZA DE CASTRO MARIANO (SERRA DO SALITRE) - INEP: 361607
UPDATE schools 
SET inep_code = '361607' 
WHERE UPPER(TRIM(name)) = 'EE TEREZA DE CASTRO MARIANO' 
  AND UPPER(TRIM(city)) = 'SERRA DO SALITRE' 
  AND inep_code IS NULL;

-- CESEC DE BURITIZEIRO (BURITIZEIRO) - INEP: 346322
UPDATE schools 
SET inep_code = '346322' 
WHERE UPPER(TRIM(name)) = 'CESEC DE BURITIZEIRO' 
  AND UPPER(TRIM(city)) = 'BURITIZEIRO' 
  AND inep_code IS NULL;

-- EE DE ENSINO FUNDAMENTAL E MÉDIO (BURITIZEIRO) - INEP: 346233
UPDATE schools 
SET inep_code = '346233' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL E MÉDIO' 
  AND UPPER(TRIM(city)) = 'BURITIZEIRO' 
  AND inep_code IS NULL;

-- EE PREFEITO JOSÉ MARIA PEREIRA (BURITIZEIRO) - INEP: 246131
UPDATE schools 
SET inep_code = '246131' 
WHERE UPPER(TRIM(name)) = 'EE PREFEITO JOSÉ MARIA PEREIRA' 
  AND UPPER(TRIM(city)) = 'BURITIZEIRO' 
  AND inep_code IS NULL;

-- EE PROFESSORA SÍLVIA ALENCAR ZSCHABER (BURITIZEIRO) - INEP: 246140
UPDATE schools 
SET inep_code = '246140' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA SÍLVIA ALENCAR ZSCHABER' 
  AND UPPER(TRIM(city)) = 'BURITIZEIRO' 
  AND inep_code IS NULL;

-- EE PROFESSOR PAULO FREIRE (PIRAPORA) - INEP: 365270
UPDATE schools 
SET inep_code = '365270' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR PAULO FREIRE' 
  AND UPPER(TRIM(city)) = 'PIRAPORA' 
  AND inep_code IS NULL;

-- EE PROFESSORA GEOVANINA FERREIRA DIAS (SÃO ROMÃO) - INEP: 346225
UPDATE schools 
SET inep_code = '346225' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA GEOVANINA FERREIRA DIAS' 
  AND UPPER(TRIM(city)) = 'SÃO ROMÃO' 
  AND inep_code IS NULL;

-- EE GERALDO SANGUINETTE (VÁRZEA DA PALMA) - INEP: 223671
UPDATE schools 
SET inep_code = '223671' 
WHERE UPPER(TRIM(name)) = 'EE GERALDO SANGUINETTE' 
  AND UPPER(TRIM(city)) = 'VÁRZEA DA PALMA' 
  AND inep_code IS NULL;

-- EE BOLÍVAR BOANERGES DA SILVEIRA (ALTEROSA) - INEP: 123668
UPDATE schools 
SET inep_code = '123668' 
WHERE UPPER(TRIM(name)) = 'EE BOLÍVAR BOANERGES DA SILVEIRA' 
  AND UPPER(TRIM(city)) = 'ALTEROSA' 
  AND inep_code IS NULL;

-- EE DEPUTADO JALES MACHADO (ALTEROSA) - INEP: 123684
UPDATE schools 
SET inep_code = '123684' 
WHERE UPPER(TRIM(name)) = 'EE DEPUTADO JALES MACHADO' 
  AND UPPER(TRIM(city)) = 'ALTEROSA' 
  AND inep_code IS NULL;

-- EE ADOLFO FIRMINO SOUZA MARQUES (ANDRADAS) - INEP: 123773
UPDATE schools 
SET inep_code = '123773' 
WHERE UPPER(TRIM(name)) = 'EE ADOLFO FIRMINO SOUZA MARQUES' 
  AND UPPER(TRIM(city)) = 'ANDRADAS' 
  AND inep_code IS NULL;

-- EE CORONEL JOÃO MOSCONI (ANDRADAS) - INEP: 123706
UPDATE schools 
SET inep_code = '123706' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL JOÃO MOSCONI' 
  AND UPPER(TRIM(city)) = 'ANDRADAS' 
  AND inep_code IS NULL;

-- EE DANIEL RIBEIRO MOGGI (ANDRADAS) - INEP: 123757
UPDATE schools 
SET inep_code = '123757' 
WHERE UPPER(TRIM(name)) = 'EE DANIEL RIBEIRO MOGGI' 
  AND UPPER(TRIM(city)) = 'ANDRADAS' 
  AND inep_code IS NULL;

-- EE DOUTOR ALCIDES MOSCONI (ANDRADAS) - INEP: 123714
UPDATE schools 
SET inep_code = '123714' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR ALCIDES MOSCONI' 
  AND UPPER(TRIM(city)) = 'ANDRADAS' 
  AND inep_code IS NULL;

-- EE PROFESSOR EDMUNDO VIEIRA (ANDRADAS) - INEP: 123731
UPDATE schools 
SET inep_code = '123731' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR EDMUNDO VIEIRA' 
  AND UPPER(TRIM(city)) = 'ANDRADAS' 
  AND inep_code IS NULL;

-- EE JOÃO LOURENÇO (AREADO) - INEP: 123846
UPDATE schools 
SET inep_code = '123846' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO LOURENÇO' 
  AND UPPER(TRIM(city)) = 'AREADO' 
  AND inep_code IS NULL;

-- EE JOSÉ BANDEIRA DE CARVALHO (BANDEIRA DO SUL) - INEP: 123897
UPDATE schools 
SET inep_code = '123897' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ BANDEIRA DE CARVALHO' 
  AND UPPER(TRIM(city)) = 'BANDEIRA DO SUL' 
  AND inep_code IS NULL;

-- EE AFONSO ROMÃO DE SIQUEIRA (BOTELHOS) - INEP: 124010
UPDATE schools 
SET inep_code = '124010' 
WHERE UPPER(TRIM(name)) = 'EE AFONSO ROMÃO DE SIQUEIRA' 
  AND UPPER(TRIM(city)) = 'BOTELHOS' 
  AND inep_code IS NULL;

-- EE JOÃO DE SOUZA GONÇALVES (BOTELHOS) - INEP: 123951
UPDATE schools 
SET inep_code = '123951' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO DE SOUZA GONÇALVES' 
  AND UPPER(TRIM(city)) = 'BOTELHOS' 
  AND inep_code IS NULL;

-- EE SÃO JOSÉ (BOTELHOS) - INEP: 123978
UPDATE schools 
SET inep_code = '123978' 
WHERE UPPER(TRIM(name)) = 'EE SÃO JOSÉ' 
  AND UPPER(TRIM(city)) = 'BOTELHOS' 
  AND inep_code IS NULL;

-- EE MAJOR LEONEL (CABO VERDE) - INEP: 124095
UPDATE schools 
SET inep_code = '124095' 
WHERE UPPER(TRIM(name)) = 'EE MAJOR LEONEL' 
  AND UPPER(TRIM(city)) = 'CABO VERDE' 
  AND inep_code IS NULL;

-- EE PROFESSOR PEDRO SATURNINO DE MAGALHÃES (CABO VERDE) - INEP: 124079
UPDATE schools 
SET inep_code = '124079' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR PEDRO SATURNINO DE MAGALHÃES' 
  AND UPPER(TRIM(city)) = 'CABO VERDE' 
  AND inep_code IS NULL;

-- CESEC PROFESSORA ELVIRA RODRIGUES PEREIRA (CALDAS) - INEP: 124214
UPDATE schools 
SET inep_code = '124214' 
WHERE UPPER(TRIM(name)) = 'CESEC PROFESSORA ELVIRA RODRIGUES PEREIRA' 
  AND UPPER(TRIM(city)) = 'CALDAS' 
  AND inep_code IS NULL;

-- EE INDÍGENA DE EDUCAÇÃO INFANTIL ENSINO FUNDAMENTAL - ANOS INICIAIS E FINAIS E ENSINO MÉDIO (CALDAS) - INEP: 377929
UPDATE schools 
SET inep_code = '377929' 
WHERE UPPER(TRIM(name)) = 'EE INDÍGENA DE EDUCAÇÃO INFANTIL ENSINO FUNDAMENTAL - ANOS INICIAIS E FINAIS E ENSINO MÉDIO' 
  AND UPPER(TRIM(city)) = 'CALDAS' 
  AND inep_code IS NULL;

-- EE INDÍGENA XUCURU KARIRI - WARKANÃ DE ARUANÃ (CALDAS) - INEP: 322610
UPDATE schools 
SET inep_code = '322610' 
WHERE UPPER(TRIM(name)) = 'EE INDÍGENA XUCURU KARIRI - WARKANÃ DE ARUANÃ' 
  AND UPPER(TRIM(city)) = 'CALDAS' 
  AND inep_code IS NULL;

-- EE JOSÉ FRANCO (CALDAS) - INEP: 124231
UPDATE schools 
SET inep_code = '124231' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ FRANCO' 
  AND UPPER(TRIM(city)) = 'CALDAS' 
  AND inep_code IS NULL;

-- EE SOUZA NOVAIS (CALDAS) - INEP: 124184
UPDATE schools 
SET inep_code = '124184' 
WHERE UPPER(TRIM(name)) = 'EE SOUZA NOVAIS' 
  AND UPPER(TRIM(city)) = 'CALDAS' 
  AND inep_code IS NULL;

-- EE VICENTE LANDI JÚNIOR (CALDAS) - INEP: 124192
UPDATE schools 
SET inep_code = '124192' 
WHERE UPPER(TRIM(name)) = 'EE VICENTE LANDI JÚNIOR' 
  AND UPPER(TRIM(city)) = 'CALDAS' 
  AND inep_code IS NULL;

-- EE ELIAS JORGE ZENUN (CAMPESTRE) - INEP: 124290
UPDATE schools 
SET inep_code = '124290' 
WHERE UPPER(TRIM(name)) = 'EE ELIAS JORGE ZENUN' 
  AND UPPER(TRIM(city)) = 'CAMPESTRE' 
  AND inep_code IS NULL;

-- EE RUI BARBOSA (CAMPESTRE) - INEP: 124303
UPDATE schools 
SET inep_code = '124303' 
WHERE UPPER(TRIM(name)) = 'EE RUI BARBOSA' 
  AND UPPER(TRIM(city)) = 'CAMPESTRE' 
  AND inep_code IS NULL;

-- EE DONA COTINHA (CONCEIÇÃO DA APARECIDA) - INEP: 124346
UPDATE schools 
SET inep_code = '124346' 
WHERE UPPER(TRIM(name)) = 'EE DONA COTINHA' 
  AND UPPER(TRIM(city)) = 'CONCEIÇÃO DA APARECIDA' 
  AND inep_code IS NULL;

-- EE PADRE JOSÉ ANTÔNIO PANUCCI (CONCEIÇÃO DA APARECIDA) - INEP: 124311
UPDATE schools 
SET inep_code = '124311' 
WHERE UPPER(TRIM(name)) = 'EE PADRE JOSÉ ANTÔNIO PANUCCI' 
  AND UPPER(TRIM(city)) = 'CONCEIÇÃO DA APARECIDA' 
  AND inep_code IS NULL;

-- EE SECRETÁRIO TRISTÃO DA CUNHA (DIVISA NOVA) - INEP: 124419
UPDATE schools 
SET inep_code = '124419' 
WHERE UPPER(TRIM(name)) = 'EE SECRETÁRIO TRISTÃO DA CUNHA' 
  AND UPPER(TRIM(city)) = 'DIVISA NOVA' 
  AND inep_code IS NULL;

-- EE CALIMÉRIA SILVEIRA (IBITIÚRA DE MINAS) - INEP: 279293
UPDATE schools 
SET inep_code = '279293' 
WHERE UPPER(TRIM(name)) = 'EE CALIMÉRIA SILVEIRA' 
  AND UPPER(TRIM(city)) = 'IBITIÚRA DE MINAS' 
  AND inep_code IS NULL;

-- EE FREI LEVINO (MONTE BELO) - INEP: 124516
UPDATE schools 
SET inep_code = '124516' 
WHERE UPPER(TRIM(name)) = 'EE FREI LEVINO' 
  AND UPPER(TRIM(city)) = 'MONTE BELO' 
  AND inep_code IS NULL;

-- EE PRESIDENTE TANCREDO DE ALMEIDA NEVES (MONTE BELO) - INEP: 124524
UPDATE schools 
SET inep_code = '124524' 
WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE TANCREDO DE ALMEIDA NEVES' 
  AND UPPER(TRIM(city)) = 'MONTE BELO' 
  AND inep_code IS NULL;

-- EE CESÁRIO COIMBRA (MUZAMBINHO) - INEP: 124575
UPDATE schools 
SET inep_code = '124575' 
WHERE UPPER(TRIM(name)) = 'EE CESÁRIO COIMBRA' 
  AND UPPER(TRIM(city)) = 'MUZAMBINHO' 
  AND inep_code IS NULL;

-- EE PROFESSOR SALATIEL DE ALMEIDA (MUZAMBINHO) - INEP: 124656
UPDATE schools 
SET inep_code = '124656' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR SALATIEL DE ALMEIDA' 
  AND UPPER(TRIM(city)) = 'MUZAMBINHO' 
  AND inep_code IS NULL;

-- EE PADRE LUIZ MORENO (NOVA RESENDE) - INEP: 312061
UPDATE schools 
SET inep_code = '312061' 
WHERE UPPER(TRIM(name)) = 'EE PADRE LUIZ MORENO' 
  AND UPPER(TRIM(city)) = 'NOVA RESENDE' 
  AND inep_code IS NULL;

-- EE PROFESSOR CAIO ALBUQUERQUE (NOVA RESENDE) - INEP: 124664
UPDATE schools 
SET inep_code = '124664' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR CAIO ALBUQUERQUE' 
  AND UPPER(TRIM(city)) = 'NOVA RESENDE' 
  AND inep_code IS NULL;

-- CESEC PROFESSORA HELOÍSA LACERDA (POÇOS DE CALDAS) - INEP: 124931
UPDATE schools 
SET inep_code = '124931' 
WHERE UPPER(TRIM(name)) = 'CESEC PROFESSORA HELOÍSA LACERDA' 
  AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' 
  AND inep_code IS NULL;

-- EE DAVID CAMPISTA (POÇOS DE CALDAS) - INEP: 124737
UPDATE schools 
SET inep_code = '124737' 
WHERE UPPER(TRIM(name)) = 'EE DAVID CAMPISTA' 
  AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' 
  AND inep_code IS NULL;

-- EE DE ENSINO FUNDAMENTAL E MÉDIO (POÇOS DE CALDAS) - INEP: 338869
UPDATE schools 
SET inep_code = '338869' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL E MÉDIO' 
  AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' 
  AND inep_code IS NULL;

-- EE DONA FRANCISCA TAMM BIAS FORTES (POÇOS DE CALDAS) - INEP: 124745
UPDATE schools 
SET inep_code = '124745' 
WHERE UPPER(TRIM(name)) = 'EE DONA FRANCISCA TAMM BIAS FORTES' 
  AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' 
  AND inep_code IS NULL;

-- EE DOUTOR EDMUNDO GOUVEA CARDILLO (POÇOS DE CALDAS) - INEP: 124877
UPDATE schools 
SET inep_code = '124877' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR EDMUNDO GOUVEA CARDILLO' 
  AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' 
  AND inep_code IS NULL;

-- EE DOUTOR JOÃO EUGÊNIO DE ALMEIDA (POÇOS DE CALDAS) - INEP: 124729
UPDATE schools 
SET inep_code = '124729' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR JOÃO EUGÊNIO DE ALMEIDA' 
  AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' 
  AND inep_code IS NULL;

-- EE FRANCISCO ESCOBAR (POÇOS DE CALDAS) - INEP: 124761
UPDATE schools 
SET inep_code = '124761' 
WHERE UPPER(TRIM(name)) = 'EE FRANCISCO ESCOBAR' 
  AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' 
  AND inep_code IS NULL;

-- EE PROFESSOR ARLINDO PEREIRA - CENTRO DE EDUCAÇÃO POLITÉCNICA (POÇOS DE CALDAS) - INEP: 124818
UPDATE schools 
SET inep_code = '124818' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ARLINDO PEREIRA - CENTRO DE EDUCAÇÃO POLITÉCNICA' 
  AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' 
  AND inep_code IS NULL;

-- EE PROFESSOR JOSÉ CASTRO DE ARAÚJO (POÇOS DE CALDAS) - INEP: 124923
UPDATE schools 
SET inep_code = '124923' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOSÉ CASTRO DE ARAÚJO' 
  AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' 
  AND inep_code IS NULL;

-- EE PROFESSORA CLEUSA LOVATO CALIARI (POÇOS DE CALDAS) - INEP: 124826
UPDATE schools 
SET inep_code = '124826' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA CLEUSA LOVATO CALIARI' 
  AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' 
  AND inep_code IS NULL;

-- EE CARLOS MAGNO DE CARVALHO (SANTA RITA DE CALDAS) - INEP: 124974
UPDATE schools 
SET inep_code = '124974' 
WHERE UPPER(TRIM(name)) = 'EE CARLOS MAGNO DE CARVALHO' 
  AND UPPER(TRIM(city)) = 'SANTA RITA DE CALDAS' 
  AND inep_code IS NULL;

-- EE DONA RITA AMÉLIA DE CARVALHO (SANTA RITA DE CALDAS) - INEP: 124940
UPDATE schools 
SET inep_code = '124940' 
WHERE UPPER(TRIM(name)) = 'EE DONA RITA AMÉLIA DE CARVALHO' 
  AND UPPER(TRIM(city)) = 'SANTA RITA DE CALDAS' 
  AND inep_code IS NULL;

-- EE DIRETOR NELSON RODRIGUES (SERRANIA) - INEP: 125024
UPDATE schools 
SET inep_code = '125024' 
WHERE UPPER(TRIM(name)) = 'EE DIRETOR NELSON RODRIGUES' 
  AND UPPER(TRIM(city)) = 'SERRANIA' 
  AND inep_code IS NULL;

-- EE ABRE CAMPO (ABRE CAMPO) - INEP: 258971
UPDATE schools 
SET inep_code = '258971' 
WHERE UPPER(TRIM(name)) = 'EE ABRE CAMPO' 
  AND UPPER(TRIM(city)) = 'ABRE CAMPO' 
  AND inep_code IS NULL;

-- EE DOM JOÃO BOSCO (ABRE CAMPO) - INEP: 128104
UPDATE schools 
SET inep_code = '128104' 
WHERE UPPER(TRIM(name)) = 'EE DOM JOÃO BOSCO' 
  AND UPPER(TRIM(city)) = 'ABRE CAMPO' 
  AND inep_code IS NULL;

-- EE DOUTOR JOSÉ GROSSI (ABRE CAMPO) - INEP: 128121
UPDATE schools 
SET inep_code = '128121' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR JOSÉ GROSSI' 
  AND UPPER(TRIM(city)) = 'ABRE CAMPO' 
  AND inep_code IS NULL;

-- EE PROFESSOR ERNESTO DE MELO BRANDÃO (ABRE CAMPO) - INEP: 128139
UPDATE schools 
SET inep_code = '128139' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ERNESTO DE MELO BRANDÃO' 
  AND UPPER(TRIM(city)) = 'ABRE CAMPO' 
  AND inep_code IS NULL;

-- EE ANTÔNIO CARLOS (ALVINÓPOLIS) - INEP: 128252
UPDATE schools 
SET inep_code = '128252' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO CARLOS' 
  AND UPPER(TRIM(city)) = 'ALVINÓPOLIS' 
  AND inep_code IS NULL;

-- EE DESEMBARGADOR BARCELOS CORREA (ALVINÓPOLIS) - INEP: 128261
UPDATE schools 
SET inep_code = '128261' 
WHERE UPPER(TRIM(name)) = 'EE DESEMBARGADOR BARCELOS CORREA' 
  AND UPPER(TRIM(city)) = 'ALVINÓPOLIS' 
  AND inep_code IS NULL;

-- EE GOVERNADOR BIAS FORTES (ALVINÓPOLIS) - INEP: 322806
UPDATE schools 
SET inep_code = '322806' 
WHERE UPPER(TRIM(name)) = 'EE GOVERNADOR BIAS FORTES' 
  AND UPPER(TRIM(city)) = 'ALVINÓPOLIS' 
  AND inep_code IS NULL;

-- EE PROFESSOR CÂNDIDO GOMES (ALVINÓPOLIS) - INEP: 128244
UPDATE schools 
SET inep_code = '128244' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR CÂNDIDO GOMES' 
  AND UPPER(TRIM(city)) = 'ALVINÓPOLIS' 
  AND inep_code IS NULL;

-- EE ALFREDO DO CARMO (AMPARO DO SERRA) - INEP: 128279
UPDATE schools 
SET inep_code = '128279' 
WHERE UPPER(TRIM(name)) = 'EE ALFREDO DO CARMO' 
  AND UPPER(TRIM(city)) = 'AMPARO DO SERRA' 
  AND inep_code IS NULL;

-- EE CÔNEGO JOSÉ ERMELINDO DE SOUZA (ARAPONGA) - INEP: 128325
UPDATE schools 
SET inep_code = '128325' 
WHERE UPPER(TRIM(name)) = 'EE CÔNEGO JOSÉ ERMELINDO DE SOUZA' 
  AND UPPER(TRIM(city)) = 'ARAPONGA' 
  AND inep_code IS NULL;

-- EE JOSÉ DIAS DO CARMO (ARAPONGA) - INEP: 128341
UPDATE schools 
SET inep_code = '128341' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ DIAS DO CARMO' 
  AND UPPER(TRIM(city)) = 'ARAPONGA' 
  AND inep_code IS NULL;

-- EE CLAUDIONOR LOPES (BARRA LONGA) - INEP: 128368
UPDATE schools 
SET inep_code = '128368' 
WHERE UPPER(TRIM(name)) = 'EE CLAUDIONOR LOPES' 
  AND UPPER(TRIM(city)) = 'BARRA LONGA' 
  AND inep_code IS NULL;

-- EE PADRE JOSÉ EPIFÂNIO GONÇALVES (BARRA LONGA) - INEP: 128414
UPDATE schools 
SET inep_code = '128414' 
WHERE UPPER(TRIM(name)) = 'EE PADRE JOSÉ EPIFÂNIO GONÇALVES' 
  AND UPPER(TRIM(city)) = 'BARRA LONGA' 
  AND inep_code IS NULL;

-- EE CAPITÃO ARNALDO DIAS ANDRADE (CAJURI) - INEP: 128449
UPDATE schools 
SET inep_code = '128449' 
WHERE UPPER(TRIM(name)) = 'EE CAPITÃO ARNALDO DIAS ANDRADE' 
  AND UPPER(TRIM(city)) = 'CAJURI' 
  AND inep_code IS NULL;

-- EE ANTÔNIO LOPES SOARES (CANAÃ) - INEP: 128490
UPDATE schools 
SET inep_code = '128490' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO LOPES SOARES' 
  AND UPPER(TRIM(city)) = 'CANAÃ' 
  AND inep_code IS NULL;

-- EE MARIA APARECIDA DAVID (CANAÃ) - INEP: 233200
UPDATE schools 
SET inep_code = '233200' 
WHERE UPPER(TRIM(name)) = 'EE MARIA APARECIDA DAVID' 
  AND UPPER(TRIM(city)) = 'CANAÃ' 
  AND inep_code IS NULL;

-- EE PRESIDENTE TANCREDO NEVES (DOM SILVÉRIO) - INEP: 128678
UPDATE schools 
SET inep_code = '128678' 
WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE TANCREDO NEVES' 
  AND UPPER(TRIM(city)) = 'DOM SILVÉRIO' 
  AND inep_code IS NULL;

-- EE AGOSTINHO HIPÓLITO DE F FREIRE (GUARACIABA) - INEP: 128694
UPDATE schools 
SET inep_code = '128694' 
WHERE UPPER(TRIM(name)) = 'EE AGOSTINHO HIPÓLITO DE F FREIRE' 
  AND UPPER(TRIM(city)) = 'GUARACIABA' 
  AND inep_code IS NULL;

-- EE HERMÓGENES FERREIRA DA SILVA (GUARACIABA) - INEP: 128732
UPDATE schools 
SET inep_code = '128732' 
WHERE UPPER(TRIM(name)) = 'EE HERMÓGENES FERREIRA DA SILVA' 
  AND UPPER(TRIM(city)) = 'GUARACIABA' 
  AND inep_code IS NULL;

-- EE JOSÉ MATEUS DE VASCONCELOS (GUARACIABA) - INEP: 128716
UPDATE schools 
SET inep_code = '128716' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ MATEUS DE VASCONCELOS' 
  AND UPPER(TRIM(city)) = 'GUARACIABA' 
  AND inep_code IS NULL;

-- EE PADRE DIMAS (GUARACIABA) - INEP: 128724
UPDATE schools 
SET inep_code = '128724' 
WHERE UPPER(TRIM(name)) = 'EE PADRE DIMAS' 
  AND UPPER(TRIM(city)) = 'GUARACIABA' 
  AND inep_code IS NULL;

-- EE DE PISCAMBA (JEQUERI) - INEP: 128791
UPDATE schools 
SET inep_code = '128791' 
WHERE UPPER(TRIM(name)) = 'EE DE PISCAMBA' 
  AND UPPER(TRIM(city)) = 'JEQUERI' 
  AND inep_code IS NULL;

-- EE DO GROTA (JEQUERI) - INEP: 128775
UPDATE schools 
SET inep_code = '128775' 
WHERE UPPER(TRIM(name)) = 'EE DO GROTA' 
  AND UPPER(TRIM(city)) = 'JEQUERI' 
  AND inep_code IS NULL;

-- EE PADRE BENEVENUTO (JEQUERI) - INEP: 128741
UPDATE schools 
SET inep_code = '128741' 
WHERE UPPER(TRIM(name)) = 'EE PADRE BENEVENUTO' 
  AND UPPER(TRIM(city)) = 'JEQUERI' 
  AND inep_code IS NULL;

-- EE SÃO VICENTE DO GRAMA (JEQUERI) - INEP: 128821
UPDATE schools 
SET inep_code = '128821' 
WHERE UPPER(TRIM(name)) = 'EE SÃO VICENTE DO GRAMA' 
  AND UPPER(TRIM(city)) = 'JEQUERI' 
  AND inep_code IS NULL;

-- EE TENENTE MOL (JEQUERI) - INEP: 128759
UPDATE schools 
SET inep_code = '128759' 
WHERE UPPER(TRIM(name)) = 'EE TENENTE MOL' 
  AND UPPER(TRIM(city)) = 'JEQUERI' 
  AND inep_code IS NULL;

-- EE DOUTOR FRANCISCO VIEIRA MARTINS (ORATÓRIOS) - INEP: 129135
UPDATE schools 
SET inep_code = '129135' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR FRANCISCO VIEIRA MARTINS' 
  AND UPPER(TRIM(city)) = 'ORATÓRIOS' 
  AND inep_code IS NULL;

-- EE ALFENO FRANCISCO DO CARMO (PEDRA BONITA) - INEP: 353825
UPDATE schools 
SET inep_code = '353825' 
WHERE UPPER(TRIM(name)) = 'EE ALFENO FRANCISCO DO CARMO' 
  AND UPPER(TRIM(city)) = 'PEDRA BONITA' 
  AND inep_code IS NULL;

-- EE DOM OSCAR DE OLIVEIRA (PEDRA BONITA) - INEP: 128147
UPDATE schools 
SET inep_code = '128147' 
WHERE UPPER(TRIM(name)) = 'EE DOM OSCAR DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'PEDRA BONITA' 
  AND inep_code IS NULL;

-- EE JOSÉ ALBINO LEAL (PEDRA DO ANTA) - INEP: 128856
UPDATE schools 
SET inep_code = '128856' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ ALBINO LEAL' 
  AND UPPER(TRIM(city)) = 'PEDRA DO ANTA' 
  AND inep_code IS NULL;

-- EE CORONEL ANTONINHO (PIEDADE DE PONTE NOVA) - INEP: 128881
UPDATE schools 
SET inep_code = '128881' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL ANTONINHO' 
  AND UPPER(TRIM(city)) = 'PIEDADE DE PONTE NOVA' 
  AND inep_code IS NULL;

-- CESEC PROFESSORA VERA PARENTONI (PONTE NOVA) - INEP: 129127
UPDATE schools 
SET inep_code = '129127' 
WHERE UPPER(TRIM(name)) = 'CESEC PROFESSORA VERA PARENTONI' 
  AND UPPER(TRIM(city)) = 'PONTE NOVA' 
  AND inep_code IS NULL;

-- EE ANTÔNIO COELHO (PONTE NOVA) - INEP: 338877
UPDATE schools 
SET inep_code = '338877' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO COELHO' 
  AND UPPER(TRIM(city)) = 'PONTE NOVA' 
  AND inep_code IS NULL;

-- EE CAETANO MARINHO (PONTE NOVA) - INEP: 128902
UPDATE schools 
SET inep_code = '128902' 
WHERE UPPER(TRIM(name)) = 'EE CAETANO MARINHO' 
  AND UPPER(TRIM(city)) = 'PONTE NOVA' 
  AND inep_code IS NULL;

-- EE CARLOS TRIVELLATO (PONTE NOVA) - INEP: 128929
UPDATE schools 
SET inep_code = '128929' 
WHERE UPPER(TRIM(name)) = 'EE CARLOS TRIVELLATO' 
  AND UPPER(TRIM(city)) = 'PONTE NOVA' 
  AND inep_code IS NULL;

-- EE CORONEL CANTÍDIO DRUMOND (PONTE NOVA) - INEP: 128945
UPDATE schools 
SET inep_code = '128945' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL CANTÍDIO DRUMOND' 
  AND UPPER(TRIM(city)) = 'PONTE NOVA' 
  AND inep_code IS NULL;

-- EE PROFESSOR ANTÔNIO GONÇALVES LANNA (PONTE NOVA) - INEP: 129062
UPDATE schools 
SET inep_code = '129062' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ANTÔNIO GONÇALVES LANNA' 
  AND UPPER(TRIM(city)) = 'PONTE NOVA' 
  AND inep_code IS NULL;

-- EE PROFESSOR RAYMUNDO MARTINIANO FERREIRA (PONTE NOVA) - INEP: 129071
UPDATE schools 
SET inep_code = '129071' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR RAYMUNDO MARTINIANO FERREIRA' 
  AND UPPER(TRIM(city)) = 'PONTE NOVA' 
  AND inep_code IS NULL;

-- EE SENADOR ANTÔNIO MARTINS (PONTE NOVA) - INEP: 129101
UPDATE schools 
SET inep_code = '129101' 
WHERE UPPER(TRIM(name)) = 'EE SENADOR ANTÔNIO MARTINS' 
  AND UPPER(TRIM(city)) = 'PONTE NOVA' 
  AND inep_code IS NULL;

-- EE CORONEL AMANTINO (PORTO FIRME) - INEP: 310590
UPDATE schools 
SET inep_code = '310590' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL AMANTINO' 
  AND UPPER(TRIM(city)) = 'PORTO FIRME' 
  AND inep_code IS NULL;

-- EE IMACULADA CONCEIÇÃO (PORTO FIRME) - INEP: 129194
UPDATE schools 
SET inep_code = '129194' 
WHERE UPPER(TRIM(name)) = 'EE IMACULADA CONCEIÇÃO' 
  AND UPPER(TRIM(city)) = 'PORTO FIRME' 
  AND inep_code IS NULL;

-- EE SOLON ILDEFONSO (PORTO FIRME) - INEP: 129208
UPDATE schools 
SET inep_code = '129208' 
WHERE UPPER(TRIM(name)) = 'EE SOLON ILDEFONSO' 
  AND UPPER(TRIM(city)) = 'PORTO FIRME' 
  AND inep_code IS NULL;

-- CESEC RÉCIO DE SOUZA RIBEIRO (RAUL SOARES) - INEP: 129241
UPDATE schools 
SET inep_code = '129241' 
WHERE UPPER(TRIM(name)) = 'CESEC RÉCIO DE SOUZA RIBEIRO' 
  AND UPPER(TRIM(city)) = 'RAUL SOARES' 
  AND inep_code IS NULL;

-- EE ALBANO PIRES (RAUL SOARES) - INEP: 129283
UPDATE schools 
SET inep_code = '129283' 
WHERE UPPER(TRIM(name)) = 'EE ALBANO PIRES' 
  AND UPPER(TRIM(city)) = 'RAUL SOARES' 
  AND inep_code IS NULL;

-- EE BENEDITO VALADARES (RAUL SOARES) - INEP: 129224
UPDATE schools 
SET inep_code = '129224' 
WHERE UPPER(TRIM(name)) = 'EE BENEDITO VALADARES' 
  AND UPPER(TRIM(city)) = 'RAUL SOARES' 
  AND inep_code IS NULL;

-- EE DOM HELVÉCIO GOMES DE OLIVEIRA (RAUL SOARES) - INEP: 129259
UPDATE schools 
SET inep_code = '129259' 
WHERE UPPER(TRIM(name)) = 'EE DOM HELVÉCIO GOMES DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'RAUL SOARES' 
  AND inep_code IS NULL;

-- EE DR LUIZ MARTINS SOARES (RAUL SOARES) - INEP: 129305
UPDATE schools 
SET inep_code = '129305' 
WHERE UPPER(TRIM(name)) = 'EE DR LUIZ MARTINS SOARES' 
  AND UPPER(TRIM(city)) = 'RAUL SOARES' 
  AND inep_code IS NULL;

-- EE JOÃO FELISBERTO DA COSTA (RAUL SOARES) - INEP: 129275
UPDATE schools 
SET inep_code = '129275' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO FELISBERTO DA COSTA' 
  AND UPPER(TRIM(city)) = 'RAUL SOARES' 
  AND inep_code IS NULL;

-- EE PADRE JÚLIO MARIA (RAUL SOARES) - INEP: 129267
UPDATE schools 
SET inep_code = '129267' 
WHERE UPPER(TRIM(name)) = 'EE PADRE JÚLIO MARIA' 
  AND UPPER(TRIM(city)) = 'RAUL SOARES' 
  AND inep_code IS NULL;

-- EE REGINA PACIS (RAUL SOARES) - INEP: 129313
UPDATE schools 
SET inep_code = '129313' 
WHERE UPPER(TRIM(name)) = 'EE REGINA PACIS' 
  AND UPPER(TRIM(city)) = 'RAUL SOARES' 
  AND inep_code IS NULL;

-- EE IMACULADA CONCEIÇÃO (RIO CASCA) - INEP: 129381
UPDATE schools 
SET inep_code = '129381' 
WHERE UPPER(TRIM(name)) = 'EE IMACULADA CONCEIÇÃO' 
  AND UPPER(TRIM(city)) = 'RIO CASCA' 
  AND inep_code IS NULL;

-- EE MARIA AMÉLIA (RIO DOCE) - INEP: 129437
UPDATE schools 
SET inep_code = '129437' 
WHERE UPPER(TRIM(name)) = 'EE MARIA AMÉLIA' 
  AND UPPER(TRIM(city)) = 'RIO DOCE' 
  AND inep_code IS NULL;

-- EE DOUTOR OTÁVIO SOARES (SANTA CRUZ DO ESCALVADO) - INEP: 129461
UPDATE schools 
SET inep_code = '129461' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR OTÁVIO SOARES' 
  AND UPPER(TRIM(city)) = 'SANTA CRUZ DO ESCALVADO' 
  AND inep_code IS NULL;

-- EE MARIANO GOMES (SANTO ANTÔNIO DO GRAMA) - INEP: 129534
UPDATE schools 
SET inep_code = '129534' 
WHERE UPPER(TRIM(name)) = 'EE MARIANO GOMES' 
  AND UPPER(TRIM(city)) = 'SANTO ANTÔNIO DO GRAMA' 
  AND inep_code IS NULL;

-- EE JOSÉ DE ASSIS PINTO (SÃO MIGUEL DO ANTA) - INEP: 129551
UPDATE schools 
SET inep_code = '129551' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ DE ASSIS PINTO' 
  AND UPPER(TRIM(city)) = 'SÃO MIGUEL DO ANTA' 
  AND inep_code IS NULL;

-- EE PEDRO LESSA (SÃO MIGUEL DO ANTA) - INEP: 129585
UPDATE schools 
SET inep_code = '129585' 
WHERE UPPER(TRIM(name)) = 'EE PEDRO LESSA' 
  AND UPPER(TRIM(city)) = 'SÃO MIGUEL DO ANTA' 
  AND inep_code IS NULL;

-- EE DO LAJÃO (SÃO PEDRO DOS FERROS) - INEP: 129593
UPDATE schools 
SET inep_code = '129593' 
WHERE UPPER(TRIM(name)) = 'EE DO LAJÃO' 
  AND UPPER(TRIM(city)) = 'SÃO PEDRO DOS FERROS' 
  AND inep_code IS NULL;

-- EE OMAR REZENDE PEREZ (SÃO PEDRO DOS FERROS) - INEP: 129666
UPDATE schools 
SET inep_code = '129666' 
WHERE UPPER(TRIM(name)) = 'EE OMAR REZENDE PEREZ' 
  AND UPPER(TRIM(city)) = 'SÃO PEDRO DOS FERROS' 
  AND inep_code IS NULL;

-- EE SENADOR LEVINDO COELHO (SÃO PEDRO DOS FERROS) - INEP: 129658
UPDATE schools 
SET inep_code = '129658' 
WHERE UPPER(TRIM(name)) = 'EE SENADOR LEVINDO COELHO' 
  AND UPPER(TRIM(city)) = 'SÃO PEDRO DOS FERROS' 
  AND inep_code IS NULL;

-- EE SÃO SEBASTIÃO (SEM-PEIXE) - INEP: 128686
UPDATE schools 
SET inep_code = '128686' 
WHERE UPPER(TRIM(name)) = 'EE SÃO SEBASTIÃO' 
  AND UPPER(TRIM(city)) = 'SEM-PEIXE' 
  AND inep_code IS NULL;

-- EE CLÉLIA BERNARDES (SERICITA) - INEP: 129674
UPDATE schools 
SET inep_code = '129674' 
WHERE UPPER(TRIM(name)) = 'EE CLÉLIA BERNARDES' 
  AND UPPER(TRIM(city)) = 'SERICITA' 
  AND inep_code IS NULL;

-- EE ANTÔNIO MOREIRA DE QUEIROZ (TEIXEIRAS) - INEP: 317420
UPDATE schools 
SET inep_code = '317420' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO MOREIRA DE QUEIROZ' 
  AND UPPER(TRIM(city)) = 'TEIXEIRAS' 
  AND inep_code IS NULL;

-- EE DOUTOR MARIANO DA ROCHA (TEIXEIRAS) - INEP: 129763
UPDATE schools 
SET inep_code = '129763' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR MARIANO DA ROCHA' 
  AND UPPER(TRIM(city)) = 'TEIXEIRAS' 
  AND inep_code IS NULL;

-- EE CUSTÓDIO MARTINS DA SILVA (URUCÂNIA) - INEP: 129801
UPDATE schools 
SET inep_code = '129801' 
WHERE UPPER(TRIM(name)) = 'EE CUSTÓDIO MARTINS DA SILVA' 
  AND UPPER(TRIM(city)) = 'URUCÂNIA' 
  AND inep_code IS NULL;

-- EE HELDER DE AQUINO (URUCÂNIA) - INEP: 129828
UPDATE schools 
SET inep_code = '129828' 
WHERE UPPER(TRIM(name)) = 'EE HELDER DE AQUINO' 
  AND UPPER(TRIM(city)) = 'URUCÂNIA' 
  AND inep_code IS NULL;

-- EE PROFESSOR MANUEL RUFINO (URUCÂNIA) - INEP: 129836
UPDATE schools 
SET inep_code = '129836' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR MANUEL RUFINO' 
  AND UPPER(TRIM(city)) = 'URUCÂNIA' 
  AND inep_code IS NULL;

-- EE FARMACÊUTICO SOARES (VERMELHO NOVO) - INEP: 129321
UPDATE schools 
SET inep_code = '129321' 
WHERE UPPER(TRIM(name)) = 'EE FARMACÊUTICO SOARES' 
  AND UPPER(TRIM(city)) = 'VERMELHO NOVO' 
  AND inep_code IS NULL;

-- CESEC DOUTOR ALTAMIRO SARAIVA (VIÇOSA) - INEP: 259551
UPDATE schools 
SET inep_code = '259551' 
WHERE UPPER(TRIM(name)) = 'CESEC DOUTOR ALTAMIRO SARAIVA' 
  AND UPPER(TRIM(city)) = 'VIÇOSA' 
  AND inep_code IS NULL;

-- EE ALICE LOUREIRO (VIÇOSA) - INEP: 130036
UPDATE schools 
SET inep_code = '130036' 
WHERE UPPER(TRIM(name)) = 'EE ALICE LOUREIRO' 
  AND UPPER(TRIM(city)) = 'VIÇOSA' 
  AND inep_code IS NULL;

-- EE DR RAIMUNDO ALVES TORRES (VIÇOSA) - INEP: 129992
UPDATE schools 
SET inep_code = '129992' 
WHERE UPPER(TRIM(name)) = 'EE DR RAIMUNDO ALVES TORRES' 
  AND UPPER(TRIM(city)) = 'VIÇOSA' 
  AND inep_code IS NULL;

-- EE EFFIE ROLFS (VIÇOSA) - INEP: 129861
UPDATE schools 
SET inep_code = '129861' 
WHERE UPPER(TRIM(name)) = 'EE EFFIE ROLFS' 
  AND UPPER(TRIM(city)) = 'VIÇOSA' 
  AND inep_code IS NULL;

-- EE JOSÉ LOURENÇO DE FREITAS (VIÇOSA) - INEP: 130044
UPDATE schools 
SET inep_code = '130044' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ LOURENÇO DE FREITAS' 
  AND UPPER(TRIM(city)) = 'VIÇOSA' 
  AND inep_code IS NULL;

-- EE MADRE SANTA FACE (VIÇOSA) - INEP: 129895
UPDATE schools 
SET inep_code = '129895' 
WHERE UPPER(TRIM(name)) = 'EE MADRE SANTA FACE' 
  AND UPPER(TRIM(city)) = 'VIÇOSA' 
  AND inep_code IS NULL;

-- EE PADRE ÁLVARO CORREA BORGES (VIÇOSA) - INEP: 129941
UPDATE schools 
SET inep_code = '129941' 
WHERE UPPER(TRIM(name)) = 'EE PADRE ÁLVARO CORREA BORGES' 
  AND UPPER(TRIM(city)) = 'VIÇOSA' 
  AND inep_code IS NULL;

-- EE PROFESSOR CID BATISTA - EJA (VIÇOSA) - INEP: 339075
UPDATE schools 
SET inep_code = '339075' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR CID BATISTA - EJA' 
  AND UPPER(TRIM(city)) = 'VIÇOSA' 
  AND inep_code IS NULL;

-- EE RAUL DE LEONI (VIÇOSA) - INEP: 217778
UPDATE schools 
SET inep_code = '217778' 
WHERE UPPER(TRIM(name)) = 'EE RAUL DE LEONI' 
  AND UPPER(TRIM(city)) = 'VIÇOSA' 
  AND inep_code IS NULL;

-- EE SANTA RITA DE CÁSSIA (VIÇOSA) - INEP: 130001
UPDATE schools 
SET inep_code = '130001' 
WHERE UPPER(TRIM(name)) = 'EE SANTA RITA DE CÁSSIA' 
  AND UPPER(TRIM(city)) = 'VIÇOSA' 
  AND inep_code IS NULL;

-- EE JOSÉ GOMES DE MORAIS FILHO (ALBERTINA) - INEP: 294705
UPDATE schools 
SET inep_code = '294705' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ GOMES DE MORAIS FILHO' 
  AND UPPER(TRIM(city)) = 'ALBERTINA' 
  AND inep_code IS NULL;

-- EE VERNER GRINBERG (CAMANDUCAIA) - INEP: 342700
UPDATE schools 
SET inep_code = '342700' 
WHERE UPPER(TRIM(name)) = 'EE VERNER GRINBERG' 
  AND UPPER(TRIM(city)) = 'CAMANDUCAIA' 
  AND inep_code IS NULL;

-- EE MENDES DE OLIVEIRA (CONGONHAL) - INEP: 124389
UPDATE schools 
SET inep_code = '124389' 
WHERE UPPER(TRIM(name)) = 'EE MENDES DE OLIVEIRA' 
  AND UPPER(TRIM(city)) = 'CONGONHAL' 
  AND inep_code IS NULL;

-- EE PREFEITO CELSO VIEIRA VILELA (HELIODORA) - INEP: 172766
UPDATE schools 
SET inep_code = '172766' 
WHERE UPPER(TRIM(name)) = 'EE PREFEITO CELSO VIEIRA VILELA' 
  AND UPPER(TRIM(city)) = 'HELIODORA' 
  AND inep_code IS NULL;

-- EE CRISTIANO MACHADO (IPUIÚNA) - INEP: 124460
UPDATE schools 
SET inep_code = '124460' 
WHERE UPPER(TRIM(name)) = 'EE CRISTIANO MACHADO' 
  AND UPPER(TRIM(city)) = 'IPUIÚNA' 
  AND inep_code IS NULL;

-- EE PROFESSORA DELORME DE AVELLAR MUNIZ (OURO FINO) - INEP: 218138
UPDATE schools 
SET inep_code = '218138' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA DELORME DE AVELLAR MUNIZ' 
  AND UPPER(TRIM(city)) = 'OURO FINO' 
  AND inep_code IS NULL;

-- COLÉGIO TIRADENTES PMMG (POUSO ALEGRE) - INEP: 362280
UPDATE schools 
SET inep_code = '362280' 
WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG' 
  AND UPPER(TRIM(city)) = 'POUSO ALEGRE' 
  AND inep_code IS NULL;

-- EE DE ENSINO MÉDIO (POUSO ALEGRE) - INEP: 372099
UPDATE schools 
SET inep_code = '372099' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' 
  AND UPPER(TRIM(city)) = 'POUSO ALEGRE' 
  AND inep_code IS NULL;

-- EE DE ENSINO MÉDIO (POUSO ALEGRE) - INEP: 372102
UPDATE schools 
SET inep_code = '372102' 
WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' 
  AND UPPER(TRIM(city)) = 'POUSO ALEGRE' 
  AND inep_code IS NULL;

-- EE PROFESSOR MENDONÇA (SENADOR JOSÉ BENTO) - INEP: 124982
UPDATE schools 
SET inep_code = '124982' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR MENDONÇA' 
  AND UPPER(TRIM(city)) = 'SENADOR JOSÉ BENTO' 
  AND inep_code IS NULL;

-- EE ANTÔNIO CARLOS DE CARVALHO (BOM SUCESSO) - INEP: 133728
UPDATE schools 
SET inep_code = '133728' 
WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO CARLOS DE CARVALHO' 
  AND UPPER(TRIM(city)) = 'BOM SUCESSO' 
  AND inep_code IS NULL;

-- EE BENJAMIM GUIMARÃES (BOM SUCESSO) - INEP: 133744
UPDATE schools 
SET inep_code = '133744' 
WHERE UPPER(TRIM(name)) = 'EE BENJAMIM GUIMARÃES' 
  AND UPPER(TRIM(city)) = 'BOM SUCESSO' 
  AND inep_code IS NULL;

-- EE SARA KUBITSCHEK (CARRANCAS) - INEP: 133922
UPDATE schools 
SET inep_code = '133922' 
WHERE UPPER(TRIM(name)) = 'EE SARA KUBITSCHEK' 
  AND UPPER(TRIM(city)) = 'CARRANCAS' 
  AND inep_code IS NULL;

-- EE ADÍLIO JOSÉ BORGES (CONCEIÇÃO DA BARRA DE MINAS) - INEP: 133931
UPDATE schools 
SET inep_code = '133931' 
WHERE UPPER(TRIM(name)) = 'EE ADÍLIO JOSÉ BORGES' 
  AND UPPER(TRIM(city)) = 'CONCEIÇÃO DA BARRA DE MINAS' 
  AND inep_code IS NULL;

-- EE CORONEL XAVIER CHAVES (CORONEL XAVIER CHAVES) - INEP: 133949
UPDATE schools 
SET inep_code = '133949' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL XAVIER CHAVES' 
  AND UPPER(TRIM(city)) = 'CORONEL XAVIER CHAVES' 
  AND inep_code IS NULL;

-- EE DUQUE DE CAXIAS (DORES DE CAMPOS) - INEP: 133973
UPDATE schools 
SET inep_code = '133973' 
WHERE UPPER(TRIM(name)) = 'EE DUQUE DE CAXIAS' 
  AND UPPER(TRIM(city)) = 'DORES DE CAMPOS' 
  AND inep_code IS NULL;

-- EE PROFESSOR JÚLIO BUENO (IBITURUNA) - INEP: 134007
UPDATE schools 
SET inep_code = '134007' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JÚLIO BUENO' 
  AND UPPER(TRIM(city)) = 'IBITURUNA' 
  AND inep_code IS NULL;

-- EE MAURÍCIO ZAKHIA (IJACI) - INEP: 134040
UPDATE schools 
SET inep_code = '134040' 
WHERE UPPER(TRIM(name)) = 'EE MAURÍCIO ZAKHIA' 
  AND UPPER(TRIM(city)) = 'IJACI' 
  AND inep_code IS NULL;

-- EE RAMIRO DE SOUZA ANDRADE (INGAÍ) - INEP: 134104
UPDATE schools 
SET inep_code = '134104' 
WHERE UPPER(TRIM(name)) = 'EE RAMIRO DE SOUZA ANDRADE' 
  AND UPPER(TRIM(city)) = 'INGAÍ' 
  AND inep_code IS NULL;

-- EE CERRADO DO ROSÁRIO (ITUMIRIM) - INEP: 134139
UPDATE schools 
SET inep_code = '134139' 
WHERE UPPER(TRIM(name)) = 'EE CERRADO DO ROSÁRIO' 
  AND UPPER(TRIM(city)) = 'ITUMIRIM' 
  AND inep_code IS NULL;

-- EE DE MACUCO DE MINAS (ITUMIRIM) - INEP: 134147
UPDATE schools 
SET inep_code = '134147' 
WHERE UPPER(TRIM(name)) = 'EE DE MACUCO DE MINAS' 
  AND UPPER(TRIM(city)) = 'ITUMIRIM' 
  AND inep_code IS NULL;

-- EE DOM DELFIM (ITUMIRIM) - INEP: 134121
UPDATE schools 
SET inep_code = '134121' 
WHERE UPPER(TRIM(name)) = 'EE DOM DELFIM' 
  AND UPPER(TRIM(city)) = 'ITUMIRIM' 
  AND inep_code IS NULL;

-- EE JAIME FERREIRA LEITE (ITUTINGA) - INEP: 134163
UPDATE schools 
SET inep_code = '134163' 
WHERE UPPER(TRIM(name)) = 'EE JAIME FERREIRA LEITE' 
  AND UPPER(TRIM(city)) = 'ITUTINGA' 
  AND inep_code IS NULL;

-- EE ABEILARD PEREIRA (LAGOA DOURADA) - INEP: 305600
UPDATE schools 
SET inep_code = '305600' 
WHERE UPPER(TRIM(name)) = 'EE ABEILARD PEREIRA' 
  AND UPPER(TRIM(city)) = 'LAGOA DOURADA' 
  AND inep_code IS NULL;

-- EE PROFESSOR BASÍLIO DE MAGALHÃES (NAZARENO) - INEP: 134295
UPDATE schools 
SET inep_code = '134295' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR BASÍLIO DE MAGALHÃES' 
  AND UPPER(TRIM(city)) = 'NAZARENO' 
  AND inep_code IS NULL;

-- EE DOUTOR VIVIANO CALDAS (PRADOS) - INEP: 134333
UPDATE schools 
SET inep_code = '134333' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR VIVIANO CALDAS' 
  AND UPPER(TRIM(city)) = 'PRADOS' 
  AND inep_code IS NULL;

-- EE ASSIS RESENDE (RESENDE COSTA) - INEP: 134368
UPDATE schools 
SET inep_code = '134368' 
WHERE UPPER(TRIM(name)) = 'EE ASSIS RESENDE' 
  AND UPPER(TRIM(city)) = 'RESENDE COSTA' 
  AND inep_code IS NULL;

-- EE PADRE CRISPINIANO (RITÁPOLIS) - INEP: 134414
UPDATE schools 
SET inep_code = '134414' 
WHERE UPPER(TRIM(name)) = 'EE PADRE CRISPINIANO' 
  AND UPPER(TRIM(city)) = 'RITÁPOLIS' 
  AND inep_code IS NULL;

-- EE AMÉLIA PASSOS (SANTA CRUZ DE MINAS) - INEP: 134911
UPDATE schools 
SET inep_code = '134911' 
WHERE UPPER(TRIM(name)) = 'EE AMÉLIA PASSOS' 
  AND UPPER(TRIM(city)) = 'SANTA CRUZ DE MINAS' 
  AND inep_code IS NULL;

-- CESEC PROFESSOR JOSÉ AMÉRICO DA COSTA (SÃO JOÃO DEL REI) - INEP: 134759
UPDATE schools 
SET inep_code = '134759' 
WHERE UPPER(TRIM(name)) = 'CESEC PROFESSOR JOSÉ AMÉRICO DA COSTA' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' 
  AND inep_code IS NULL;

-- COLÉGIO TIRADENTES PMMG - UNIDADE SÃO JOÃO DEL REI (SÃO JOÃO DEL REI) - INEP: 368148
UPDATE schools 
SET inep_code = '368148' 
WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG - UNIDADE SÃO JOÃO DEL REI' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' 
  AND inep_code IS NULL;

-- CONSERVATÓRIO ESTADUAL MÚSICA PADRE JOSÉ MARIA XAVIER (SÃO JOÃO DEL REI) - INEP: 134732
UPDATE schools 
SET inep_code = '134732' 
WHERE UPPER(TRIM(name)) = 'CONSERVATÓRIO ESTADUAL MÚSICA PADRE JOSÉ MARIA XAVIER' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' 
  AND inep_code IS NULL;

-- EE AURELIANO PIMENTEL (SÃO JOÃO DEL REI) - INEP: 134571
UPDATE schools 
SET inep_code = '134571' 
WHERE UPPER(TRIM(name)) = 'EE AURELIANO PIMENTEL' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' 
  AND inep_code IS NULL;

-- EE BRIGHENTI CESARE (SÃO JOÃO DEL REI) - INEP: 134546
UPDATE schools 
SET inep_code = '134546' 
WHERE UPPER(TRIM(name)) = 'EE BRIGHENTI CESARE' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' 
  AND inep_code IS NULL;

-- EE CÔNEGO OSVALDO LUSTOSA (SÃO JOÃO DEL REI) - INEP: 134562
UPDATE schools 
SET inep_code = '134562' 
WHERE UPPER(TRIM(name)) = 'EE CÔNEGO OSVALDO LUSTOSA' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' 
  AND inep_code IS NULL;

-- EE DEPUTADO MATEUS SALOMÉ (SÃO JOÃO DEL REI) - INEP: 134597
UPDATE schools 
SET inep_code = '134597' 
WHERE UPPER(TRIM(name)) = 'EE DEPUTADO MATEUS SALOMÉ' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' 
  AND inep_code IS NULL;

-- EE DETETIVE MARCO ANTONIO DE SOUZA (SÃO JOÃO DEL REI) - INEP: 338885
UPDATE schools 
SET inep_code = '338885' 
WHERE UPPER(TRIM(name)) = 'EE DETETIVE MARCO ANTONIO DE SOUZA' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' 
  AND inep_code IS NULL;

-- EE DOUTOR GARCIA DE LIMA (SÃO JOÃO DEL REI) - INEP: 134619
UPDATE schools 
SET inep_code = '134619' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR GARCIA DE LIMA' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' 
  AND inep_code IS NULL;

-- EE EVANDRO ÁVILA (SÃO JOÃO DEL REI) - INEP: 134791
UPDATE schools 
SET inep_code = '134791' 
WHERE UPPER(TRIM(name)) = 'EE EVANDRO ÁVILA' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' 
  AND inep_code IS NULL;

-- EE GOVERNADOR MILTON CAMPOS (SÃO JOÃO DEL REI) - INEP: 134635
UPDATE schools 
SET inep_code = '134635' 
WHERE UPPER(TRIM(name)) = 'EE GOVERNADOR MILTON CAMPOS' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' 
  AND inep_code IS NULL;

-- EE IDALINA HORTA GALVÃO (SÃO JOÃO DEL REI) - INEP: 134643
UPDATE schools 
SET inep_code = '134643' 
WHERE UPPER(TRIM(name)) = 'EE IDALINA HORTA GALVÃO' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' 
  AND inep_code IS NULL;

-- EE INÁCIO PASSOS (SÃO JOÃO DEL REI) - INEP: 134651
UPDATE schools 
SET inep_code = '134651' 
WHERE UPPER(TRIM(name)) = 'EE INÁCIO PASSOS' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' 
  AND inep_code IS NULL;

-- EE JOÃO DOS SANTOS (SÃO JOÃO DEL REI) - INEP: 134660
UPDATE schools 
SET inep_code = '134660' 
WHERE UPPER(TRIM(name)) = 'EE JOÃO DOS SANTOS' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' 
  AND inep_code IS NULL;

-- EE MINISTRO GABRIEL PASSOS (SÃO JOÃO DEL REI) - INEP: 134694
UPDATE schools 
SET inep_code = '134694' 
WHERE UPPER(TRIM(name)) = 'EE MINISTRO GABRIEL PASSOS' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' 
  AND inep_code IS NULL;

-- EE PADRE LOPES (SÃO JOÃO DEL REI) - INEP: 134805
UPDATE schools 
SET inep_code = '134805' 
WHERE UPPER(TRIM(name)) = 'EE PADRE LOPES' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' 
  AND inep_code IS NULL;

-- EE PROFESSOR IAGO PIMENTEL (SÃO JOÃO DEL REI) - INEP: 134716
UPDATE schools 
SET inep_code = '134716' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSOR IAGO PIMENTEL' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' 
  AND inep_code IS NULL;

-- EE TOMÉ PORTES DEL REI (SÃO JOÃO DEL REI) - INEP: 134724
UPDATE schools 
SET inep_code = '134724' 
WHERE UPPER(TRIM(name)) = 'EE TOMÉ PORTES DEL REI' 
  AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' 
  AND inep_code IS NULL;

-- EE AFONSO PENA JÚNIOR (SÃO TIAGO) - INEP: 134813
UPDATE schools 
SET inep_code = '134813' 
WHERE UPPER(TRIM(name)) = 'EE AFONSO PENA JÚNIOR' 
  AND UPPER(TRIM(city)) = 'SÃO TIAGO' 
  AND inep_code IS NULL;

-- EE DE MERCÊS DE ÁGUA LIMPA (SÃO TIAGO) - INEP: 134872
UPDATE schools 
SET inep_code = '134872' 
WHERE UPPER(TRIM(name)) = 'EE DE MERCÊS DE ÁGUA LIMPA' 
  AND UPPER(TRIM(city)) = 'SÃO TIAGO' 
  AND inep_code IS NULL;

-- EE HENRIQUE PEREIRA SANTIAGO (SÃO TIAGO) - INEP: 310786
UPDATE schools 
SET inep_code = '310786' 
WHERE UPPER(TRIM(name)) = 'EE HENRIQUE PEREIRA SANTIAGO' 
  AND UPPER(TRIM(city)) = 'SÃO TIAGO' 
  AND inep_code IS NULL;

-- EE BASÍLIO DA GAMA (TIRADENTES) - INEP: 134881
UPDATE schools 
SET inep_code = '134881' 
WHERE UPPER(TRIM(name)) = 'EE BASÍLIO DA GAMA' 
  AND UPPER(TRIM(city)) = 'TIRADENTES' 
  AND inep_code IS NULL;

-- EE CORONEL LUCAS MAGALHÃES (ARCEBURGO) - INEP: 136875
UPDATE schools 
SET inep_code = '136875' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL LUCAS MAGALHÃES' 
  AND UPPER(TRIM(city)) = 'ARCEBURGO' 
  AND inep_code IS NULL;

-- EE DOUTOR JOSÉ TEODORO DE SOUZA (CAPETINGA) - INEP: 136891
UPDATE schools 
SET inep_code = '136891' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR JOSÉ TEODORO DE SOUZA' 
  AND UPPER(TRIM(city)) = 'CAPETINGA' 
  AND inep_code IS NULL;

-- EE MELO VIANA (CÁSSIA) - INEP: 137006
UPDATE schools 
SET inep_code = '137006' 
WHERE UPPER(TRIM(name)) = 'EE MELO VIANA' 
  AND UPPER(TRIM(city)) = 'CÁSSIA' 
  AND inep_code IS NULL;

-- EE SÃO GABRIEL (CÁSSIA) - INEP: 136948
UPDATE schools 
SET inep_code = '136948' 
WHERE UPPER(TRIM(name)) = 'EE SÃO GABRIEL' 
  AND UPPER(TRIM(city)) = 'CÁSSIA' 
  AND inep_code IS NULL;

-- EE IARBAS RODRIGUES (CLARAVAL) - INEP: 137065
UPDATE schools 
SET inep_code = '137065' 
WHERE UPPER(TRIM(name)) = 'EE IARBAS RODRIGUES' 
  AND UPPER(TRIM(city)) = 'CLARAVAL' 
  AND inep_code IS NULL;

-- EE ALICE AUTRAN DOURADO (GUARANÉSIA) - INEP: 137073
UPDATE schools 
SET inep_code = '137073' 
WHERE UPPER(TRIM(name)) = 'EE ALICE AUTRAN DOURADO' 
  AND UPPER(TRIM(city)) = 'GUARANÉSIA' 
  AND inep_code IS NULL;

-- EE CARVALHO BRITO (GUARANÉSIA) - INEP: 137090
UPDATE schools 
SET inep_code = '137090' 
WHERE UPPER(TRIM(name)) = 'EE CARVALHO BRITO' 
  AND UPPER(TRIM(city)) = 'GUARANÉSIA' 
  AND inep_code IS NULL;

-- EE GERALDO RIBEIRO DIAS (GUARANÉSIA) - INEP: 137146
UPDATE schools 
SET inep_code = '137146' 
WHERE UPPER(TRIM(name)) = 'EE GERALDO RIBEIRO DIAS' 
  AND UPPER(TRIM(city)) = 'GUARANÉSIA' 
  AND inep_code IS NULL;

-- EE DONA QUERIDINHA BIAS FORTES (GUAXUPÉ) - INEP: 137227
UPDATE schools 
SET inep_code = '137227' 
WHERE UPPER(TRIM(name)) = 'EE DONA QUERIDINHA BIAS FORTES' 
  AND UPPER(TRIM(city)) = 'GUAXUPÉ' 
  AND inep_code IS NULL;

-- EE DOUTOR ANDRÉ CORTEZ GRANERO (GUAXUPÉ) - INEP: 137324
UPDATE schools 
SET inep_code = '137324' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR ANDRÉ CORTEZ GRANERO' 
  AND UPPER(TRIM(city)) = 'GUAXUPÉ' 
  AND inep_code IS NULL;

-- EE DOUTOR BENEDITO LEITE RIBEIRO (GUAXUPÉ) - INEP: 137235
UPDATE schools 
SET inep_code = '137235' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR BENEDITO LEITE RIBEIRO' 
  AND UPPER(TRIM(city)) = 'GUAXUPÉ' 
  AND inep_code IS NULL;

-- EE MAJOR LUIZ ZERBINI (GUAXUPÉ) - INEP: 137251
UPDATE schools 
SET inep_code = '137251' 
WHERE UPPER(TRIM(name)) = 'EE MAJOR LUIZ ZERBINI' 
  AND UPPER(TRIM(city)) = 'GUAXUPÉ' 
  AND inep_code IS NULL;

-- EE NOSSA SENHORA APARECIDA (GUAXUPÉ) - INEP: 137278
UPDATE schools 
SET inep_code = '137278' 
WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA APARECIDA' 
  AND UPPER(TRIM(city)) = 'GUAXUPÉ' 
  AND inep_code IS NULL;

-- EE DE IBIRACI (IBIRACI) - INEP: 137341
UPDATE schools 
SET inep_code = '137341' 
WHERE UPPER(TRIM(name)) = 'EE DE IBIRACI' 
  AND UPPER(TRIM(city)) = 'IBIRACI' 
  AND inep_code IS NULL;

-- EE DOUTOR ANTÔNIO CARLOS (IBIRACI) - INEP: 137359
UPDATE schools 
SET inep_code = '137359' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR ANTÔNIO CARLOS' 
  AND UPPER(TRIM(city)) = 'IBIRACI' 
  AND inep_code IS NULL;

-- EE DE ITAMOGI (ITAMOGI) - INEP: 137413
UPDATE schools 
SET inep_code = '137413' 
WHERE UPPER(TRIM(name)) = 'EE DE ITAMOGI' 
  AND UPPER(TRIM(city)) = 'ITAMOGI' 
  AND inep_code IS NULL;

-- EE JOSÉ SOARES DE ARAÚJO (ITAMOGI) - INEP: 137456
UPDATE schools 
SET inep_code = '137456' 
WHERE UPPER(TRIM(name)) = 'EE JOSÉ SOARES DE ARAÚJO' 
  AND UPPER(TRIM(city)) = 'ITAMOGI' 
  AND inep_code IS NULL;

-- EE ARY PIMENTA BUGELLI (ITAÚ DE MINAS) - INEP: 240800
UPDATE schools 
SET inep_code = '240800' 
WHERE UPPER(TRIM(name)) = 'EE ARY PIMENTA BUGELLI' 
  AND UPPER(TRIM(city)) = 'ITAÚ DE MINAS' 
  AND inep_code IS NULL;

-- EE PROFESSORA MARIA LEONOR NASSER (JACUÍ) - INEP: 137502
UPDATE schools 
SET inep_code = '137502' 
WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA LEONOR NASSER' 
  AND UPPER(TRIM(city)) = 'JACUÍ' 
  AND inep_code IS NULL;

-- EE EDUARDO SENEDESE (JURUAIA) - INEP: 137529
UPDATE schools 
SET inep_code = '137529' 
WHERE UPPER(TRIM(name)) = 'EE EDUARDO SENEDESE' 
  AND UPPER(TRIM(city)) = 'JURUAIA' 
  AND inep_code IS NULL;

-- EE AMÉRICO DE PAIVA (MONTE SANTO DE MINAS) - INEP: 137545
UPDATE schools 
SET inep_code = '137545' 
WHERE UPPER(TRIM(name)) = 'EE AMÉRICO DE PAIVA' 
  AND UPPER(TRIM(city)) = 'MONTE SANTO DE MINAS' 
  AND inep_code IS NULL;

-- EE DE MILAGRE (MONTE SANTO DE MINAS) - INEP: 137669
UPDATE schools 
SET inep_code = '137669' 
WHERE UPPER(TRIM(name)) = 'EE DE MILAGRE' 
  AND UPPER(TRIM(city)) = 'MONTE SANTO DE MINAS' 
  AND inep_code IS NULL;

-- EE DOUTOR WENCESLAU BRAZ (MONTE SANTO DE MINAS) - INEP: 137618
UPDATE schools 
SET inep_code = '137618' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR WENCESLAU BRAZ' 
  AND UPPER(TRIM(city)) = 'MONTE SANTO DE MINAS' 
  AND inep_code IS NULL;

-- EE CORONEL NECA LEMOS (PRATÁPOLIS) - INEP: 137677
UPDATE schools 
SET inep_code = '137677' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL NECA LEMOS' 
  AND UPPER(TRIM(city)) = 'PRATÁPOLIS' 
  AND inep_code IS NULL;

-- EE DOUTOR FARID SILVA (PRATÁPOLIS) - INEP: 137707
UPDATE schools 
SET inep_code = '137707' 
WHERE UPPER(TRIM(name)) = 'EE DOUTOR FARID SILVA' 
  AND UPPER(TRIM(city)) = 'PRATÁPOLIS' 
  AND inep_code IS NULL;

-- EE CORONEL JOÃO FERREIRA BARBOSA (SÃO PEDRO DA UNIÃO) - INEP: 137847
UPDATE schools 
SET inep_code = '137847' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL JOÃO FERREIRA BARBOSA' 
  AND UPPER(TRIM(city)) = 'SÃO PEDRO DA UNIÃO' 
  AND inep_code IS NULL;

-- CESEC ALDA POLASTRE (SÃO SEBASTIÃO DO PARAÍSO) - INEP: 138011
UPDATE schools 
SET inep_code = '138011' 
WHERE UPPER(TRIM(name)) = 'CESEC ALDA POLASTRE' 
  AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' 
  AND inep_code IS NULL;

-- EE BENEDITO FERREIRA CALAFIORI (SÃO SEBASTIÃO DO PARAÍSO) - INEP: 137987
UPDATE schools 
SET inep_code = '137987' 
WHERE UPPER(TRIM(name)) = 'EE BENEDITO FERREIRA CALAFIORI' 
  AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' 
  AND inep_code IS NULL;

-- EE CLÓVIS SALGADO (SÃO SEBASTIÃO DO PARAÍSO) - INEP: 137880
UPDATE schools 
SET inep_code = '137880' 
WHERE UPPER(TRIM(name)) = 'EE CLÓVIS SALGADO' 
  AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' 
  AND inep_code IS NULL;

-- EE COMENDADOR JOÃO ALVES DE FIGUEIREDO (SÃO SEBASTIÃO DO PARAÍSO) - INEP: 137936
UPDATE schools 
SET inep_code = '137936' 
WHERE UPPER(TRIM(name)) = 'EE COMENDADOR JOÃO ALVES DE FIGUEIREDO' 
  AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' 
  AND inep_code IS NULL;

-- EE COMENDADORA ANA CÂNDIDA DE FIGUEIREDO (SÃO SEBASTIÃO DO PARAÍSO) - INEP: 137910
UPDATE schools 
SET inep_code = '137910' 
WHERE UPPER(TRIM(name)) = 'EE COMENDADORA ANA CÂNDIDA DE FIGUEIREDO' 
  AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' 
  AND inep_code IS NULL;

-- EE CORONEL JOSÉ CÂNDIDO (SÃO SEBASTIÃO DO PARAÍSO) - INEP: 137898
UPDATE schools 
SET inep_code = '137898' 
WHERE UPPER(TRIM(name)) = 'EE CORONEL JOSÉ CÂNDIDO' 
  AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' 
  AND inep_code IS NULL;


COMMIT;
