import type { EntityId } from '@profeplan/types';

export const DOMAIN_REASON_CODES = [
  'SOURCE_NOT_APPROVED',
  'SOURCE_USE_NOT_ALLOWED',
  'SOURCE_LICENSE_INCOMPATIBLE',
  'SOURCE_PERMISSION_REVOKED',
  'SOURCE_PERMISSION_BLOCKED',
  'SOURCE_NOT_VALIDATED',
  'SOURCE_REGISTRATION_BLOCKED',
  'SOURCE_PURPOSE_NOT_AUTHORIZED',
  'SOURCE_AUTHORIZATION_NOT_YET_EFFECTIVE',
  'SOURCE_AUTHORIZATION_SUSPENDED',
  'SOURCE_AUTHORIZATION_REVOKED',
  'SOURCE_AUTHORIZATION_EXPIRED',
  'SOURCE_AUTHORIZATION_BLOCKED',
  'SOURCE_AUTHORIZATION_SUPERSEDED',
  'SOURCE_AUTHORIZATION_BASIS_REQUIRED',
  'SOURCE_ACTOR_REQUIRED',
  'SOURCE_ACTOR_ROLE_FORBIDDEN',
  'SOURCE_INVALID_EFFECTIVE_WINDOW',
  'SOURCE_INVALID_QUERY_INSTANT',
  'SOURCE_INVALID_REGISTRATION_TRANSITION',
  'SOURCE_INVALID_AUTHORIZATION_TRANSITION',
  'SOURCE_IDEMPOTENCY_CONFLICT',
  'SOURCE_EXPECTED_VERSION_MISMATCH',
  'SOURCE_EXPECTED_SEQUENCE_MISMATCH',
  'SOURCE_EXPECTED_STATE_MISMATCH',
  'SOURCE_GOVERNANCE_INFORMATION_MISSING',
  'INGESTION_INVALID_TRANSITION',
  'INGESTION_EXPECTED_STATE_MISMATCH',
  'INGESTION_IDEMPOTENCY_CONFLICT',
  'INGESTION_TEMPORARY_STAGING_AUTHORIZATION_REQUIRED',
  'INGESTION_AUTHORIZATION_REQUIRED',
  'INGESTION_EXTRACTION_AUTHORIZATION_REQUIRED',
  'INGESTION_HUMAN_REVIEW_REQUIRED',
  'INGESTION_HUMAN_REVIEW_NOT_APPROVED',
  'STAGING_FILE_TOO_LARGE',
  'STAGING_RUN_FILE_LIMIT_EXCEEDED',
  'STAGING_RUN_BYTE_LIMIT_EXCEEDED',
  'STAGING_MEDIA_TYPE_NOT_ALLOWED',
  'STAGING_EXTENSION_NOT_ALLOWED',
  'STAGING_FILENAME_REJECTED',
  'STAGING_FILE_SIGNATURE_MISMATCH',
  'STAGING_INTAKE_DURATION_EXCEEDED',
  'STAGING_RETENTION_INVALID',
  'STAGING_ARTIFACT_EXPIRED',
  'COMPONENT_INVALID_TRANSITION',
  'COMPONENT_STATUS_NOT_APPROVED',
  'COMPONENT_VERSION_MISSING',
  'COMPONENT_CURRENT_VERSION_MISMATCH',
  'COMPONENT_EVIDENCE_MISSING',
  'COMPONENT_EVIDENCE_UNRESOLVED',
  'COMPONENT_SOURCE_INELIGIBLE',
  'COMPONENT_CURRICULUM_MISSING',
  'COMPONENT_SCOPE_MISMATCH',
  'CURRICULUM_NOT_ACTIVE',
  'CURRICULUM_STATE_BLOCKED',
  'CURRICULUM_STAGE_MISMATCH',
  'CURRICULUM_GRADE_MISMATCH',
  'CURRICULUM_COMPONENT_MISMATCH',
  'CURRICULUM_OUTSIDE_EFFECTIVE_PERIOD',
  'CURRICULUM_NODE_MISMATCH',
  'AGENT_INACTIVE',
  'AGENT_SCOPE_ID_MISMATCH',
  'AGENT_COMPONENT_MISMATCH',
  'AGENT_STAGE_MISMATCH',
  'AGENT_GRADE_MISMATCH',
  'AGENT_STATE_MISMATCH',
  'AGENT_CURRICULUM_PACKAGE_MISMATCH',
  'OPP_INVALID_TRANSITION',
  'OPP_GATE_NOT_MET',
  'OPP_INSUFFICIENT',
  'OPP_BLOCKING_FINDING',
  'OPP_INSUFFICIENCY_NOT_CONFIRMED',
] as const;

export type DomainReasonCode = (typeof DOMAIN_REASON_CODES)[number];
export type DomainMetadataValue = string | number | boolean;

export interface DomainReason {
  code: DomainReasonCode;
  message: string;
  subjectId?: EntityId;
  metadata?: Readonly<Record<string, DomainMetadataValue>>;
}

export function reason(
  code: DomainReasonCode,
  message: string,
  subjectId?: EntityId,
  metadata?: Readonly<Record<string, DomainMetadataValue>>
): DomainReason {
  return { code, message, subjectId, metadata };
}
