-- COLÉGIO SÃO GONÇALO DO SAPUCAÍ (SÃO GONÇALO DO SAPUCAÍ)
UPDATE schools SET inep_code = '375195' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SÃO GONÇALO DO SAPUCAÍ' AND UPPER(TRIM(city)) = 'SÃO GONÇALO DO SAPUCAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '375195');

-- ESCOLA SESI JOSÉ BENTO NOGUEIRA JUNQUEIRA (SÃO GONÇALO DO SAPUCAÍ)
UPDATE schools SET inep_code = '322903' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SESI JOSÉ BENTO NOGUEIRA JUNQUEIRA' AND UPPER(TRIM(city)) = 'SÃO GONÇALO DO SAPUCAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322903');

-- SERVIÇO NACIONAL DE APRENDIZAGEM INDUSTRIAL - DRMG (SÃO GONÇALO DO SAPUCAÍ)
UPDATE schools SET inep_code = '370916' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SERVIÇO NACIONAL DE APRENDIZAGEM INDUSTRIAL - DRMG' AND UPPER(TRIM(city)) = 'SÃO GONÇALO DO SAPUCAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '370916');

-- CENTRO EDUCACIONAL FLOR DO IPÊ (TRÊS CORAÇÕES)
UPDATE schools SET inep_code = '313386' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL FLOR DO IPÊ' AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '313386');

-- COLÉGIO CASTELO (TRÊS CORAÇÕES)
UPDATE schools SET inep_code = '368466' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CASTELO' AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368466');

-- COLÉGIO IMPÉRIO - UNIDADE III (TRÊS CORAÇÕES)
UPDATE schools SET inep_code = '374679' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO IMPÉRIO - UNIDADE III' AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '374679');

-- COLÉGIO NOVA GERAÇÃO (TRÊS CORAÇÕES)
UPDATE schools SET inep_code = '342742' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO NOVA GERAÇÃO' AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342742');

-- COLÉGIO UNIÃO - UNIDADE II (TRÊS CORAÇÕES)
UPDATE schools SET inep_code = '342998' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO UNIÃO - UNIDADE II' AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342998');

-- COLÉGIO UNIVERSITÁRIO APLICAÇÃO DA UNINCOR PROF JOSÉ MARIA FERREIRA MACIEL (TRÊS CORAÇÕES)
UPDATE schools SET inep_code = '180556' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO UNIVERSITÁRIO APLICAÇÃO DA UNINCOR PROF JOSÉ MARIA FERREIRA MACIEL' AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180556');

-- ESCOLA PADRÃO (TRÊS CORAÇÕES)
UPDATE schools SET inep_code = '310174' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA PADRÃO' AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310174');

-- SENAC UNIDADE ENSINO TECNICO - CFP DE TRÊS CORAÇÕES (TRÊS CORAÇÕES)
UPDATE schools SET inep_code = '343510' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAC UNIDADE ENSINO TECNICO - CFP DE TRÊS CORAÇÕES' AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '343510');

-- COLÉGIO NOVO MILÊNIO (TRÊS PONTAS)
UPDATE schools SET inep_code = '296848' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO NOVO MILÊNIO' AND UPPER(TRIM(city)) = 'TRÊS PONTAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '296848');

-- COLEGIO PRÓSPERI (TRÊS PONTAS)
UPDATE schools SET inep_code = '222381' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLEGIO PRÓSPERI' AND UPPER(TRIM(city)) = 'TRÊS PONTAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '222381');

-- COLÉGIO TRAVESSIA (TRÊS PONTAS)
UPDATE schools SET inep_code = '361313' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TRAVESSIA' AND UPPER(TRIM(city)) = 'TRÊS PONTAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '361313');

-- ESCOLA CORAÇÃO DE JESUS (TRÊS PONTAS)
UPDATE schools SET inep_code = '180572' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA CORAÇÃO DE JESUS' AND UPPER(TRIM(city)) = 'TRÊS PONTAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180572');

-- ETEC - ESCOLA TÉCNICA NOVO HORIZONTE (TRÊS PONTAS)
UPDATE schools SET inep_code = '329941' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ETEC - ESCOLA TÉCNICA NOVO HORIZONTE' AND UPPER(TRIM(city)) = 'TRÊS PONTAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '329941');

-- APLICAR - CURSOS DE EXCELÊNCIA (VARGINHA)
UPDATE schools SET inep_code = '373737' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'APLICAR - CURSOS DE EXCELÊNCIA' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '373737');

-- COLÉGIO ADVENTISTA DE VARGINHA - UNIDADE II (VARGINHA)
UPDATE schools SET inep_code = '372480' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ADVENTISTA DE VARGINHA - UNIDADE II' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '372480');

-- COLÉGIO ÁGAPE DOM (VARGINHA)
UPDATE schools SET inep_code = '366269' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ÁGAPE DOM' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '366269');

-- COLÉGIO ALPHA (VARGINHA)
UPDATE schools SET inep_code = '180599' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ALPHA' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180599');

-- COLÉGIO BATISTA DE VARGINHA (VARGINHA)
UPDATE schools SET inep_code = '180602' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO BATISTA DE VARGINHA' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180602');

-- COLÉGIO DOS SANTOS ANJOS (VARGINHA)
UPDATE schools SET inep_code = '180611' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DOS SANTOS ANJOS' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180611');

-- COLÉGIO INOVA CAMINHOS DOURADOS (VARGINHA)
UPDATE schools SET inep_code = '306215' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO INOVA CAMINHOS DOURADOS' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '306215');

-- COLÉGIO MARISTA (VARGINHA)
UPDATE schools SET inep_code = '293687' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MARISTA' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '293687');

-- COLÉGIO MASTER VARGINHA (VARGINHA)
UPDATE schools SET inep_code = '296856' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MASTER VARGINHA' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '296856');

-- ESCOLA MARISTA CHAMPAGNAT DE VARGINHA (VARGINHA)
UPDATE schools SET inep_code = '351407' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA MARISTA CHAMPAGNAT DE VARGINHA' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '351407');

-- IMPACTO ESCOLA DE SAÚDE (VARGINHA)
UPDATE schools SET inep_code = '317497' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'IMPACTO ESCOLA DE SAÚDE' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '317497');

-- LOGOS COLÉGIO E CURSO - FORMACAO INTEGRAL DE ENSINO FUNDAMENTAL E ENSINO MÉDIO (VARGINHA)
UPDATE schools SET inep_code = '316237' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'LOGOS COLÉGIO E CURSO - FORMACAO INTEGRAL DE ENSINO FUNDAMENTAL E ENSINO MÉDIO' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '316237');

-- SENAC UNID ENS TEC - CFP VARGINHA (VARGINHA)
UPDATE schools SET inep_code = '317675' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAC UNID ENS TEC - CFP VARGINHA' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '317675');

-- SENAI CENTRO DE FORMAÇÃO PROFISSIONAL ALOYSIO RIBEIRO DE ALMEIDA (VARGINHA)
UPDATE schools SET inep_code = '267414' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI CENTRO DE FORMAÇÃO PROFISSIONAL ALOYSIO RIBEIRO DE ALMEIDA' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '267414');

-- SESI ALOYSIO RIBEIRO DE ALMEIDA (VARGINHA)
UPDATE schools SET inep_code = '368954' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SESI ALOYSIO RIBEIRO DE ALMEIDA' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368954');