-- EE CORONEL ANTÔNIO DOMINGOS RIBEIRO (BOM JESUS DA PENHA)
UPDATE schools SET inep_code = '123901' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL ANTÔNIO DOMINGOS RIBEIRO' AND UPPER(TRIM(city)) = 'BOM JESUS DA PENHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '123901');

-- EE CORONEL LOURENÇO BELO (CAPITÓLIO)
UPDATE schools SET inep_code = '317462' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL LOURENÇO BELO' AND UPPER(TRIM(city)) = 'CAPITÓLIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '317462');

-- EE MODESTO ANTÔNIO DE OLIVEIRA (CAPITÓLIO)
UPDATE schools SET inep_code = '114961' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MODESTO ANTÔNIO DE OLIVEIRA' AND UPPER(TRIM(city)) = 'CAPITÓLIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '114961');

-- EE GERALDO DE ANDRADE VILELA (CARMO DO RIO CLARO)
UPDATE schools SET inep_code = '115061' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GERALDO DE ANDRADE VILELA' AND UPPER(TRIM(city)) = 'CARMO DO RIO CLARO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115061');

-- EE MONSENHOR MÁRIO ARAÚJO GUIMARÃES (CARMO DO RIO CLARO)
UPDATE schools SET inep_code = '115088' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MONSENHOR MÁRIO ARAÚJO GUIMARÃES' AND UPPER(TRIM(city)) = 'CARMO DO RIO CLARO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115088');

-- EE PADRE JOSÉ SANGALI (CÓRREGO FUNDO)
UPDATE schools SET inep_code = '115347' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE JOSÉ SANGALI' AND UPPER(TRIM(city)) = 'CÓRREGO FUNDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115347');

-- EE PROFESSORA NEIVA MARIA LEITE (DELFINÓPOLIS)
UPDATE schools SET inep_code = '115126' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA NEIVA MARIA LEITE' AND UPPER(TRIM(city)) = 'DELFINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115126');

-- EE STA TEREZINHA (DORESÓPOLIS)
UPDATE schools SET inep_code = '115177' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE STA TEREZINHA' AND UPPER(TRIM(city)) = 'DORESÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115177');

-- CESEC ÂNGELA MARIA CASSEMIRO CORRÊA (FORMIGA)
UPDATE schools SET inep_code = '313700' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC ÂNGELA MARIA CASSEMIRO CORRÊA' AND UPPER(TRIM(city)) = 'FORMIGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '313700');

-- EE AURELIANO RODRIGUES NUNES (FORMIGA)
UPDATE schools SET inep_code = '115258' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE AURELIANO RODRIGUES NUNES' AND UPPER(TRIM(city)) = 'FORMIGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115258');

-- EE DR ABÍLIO MACHADO (FORMIGA)
UPDATE schools SET inep_code = '115282' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DR ABÍLIO MACHADO' AND UPPER(TRIM(city)) = 'FORMIGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115282');

-- EE JALCIRA SANTOS VALADÃO (FORMIGA)
UPDATE schools SET inep_code = '115266' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JALCIRA SANTOS VALADÃO' AND UPPER(TRIM(city)) = 'FORMIGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115266');

-- EE JOSÉ BERNARDES DE FARIA (FORMIGA)
UPDATE schools SET inep_code = '115304' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ BERNARDES DE FARIA' AND UPPER(TRIM(city)) = 'FORMIGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115304');

-- EE PROFESSOR JOAQUIM RODARTE (FORMIGA)
UPDATE schools SET inep_code = '115207' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOAQUIM RODARTE' AND UPPER(TRIM(city)) = 'FORMIGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115207');

-- EE PROFESSOR TONICO LEITE (FORMIGA)
UPDATE schools SET inep_code = '115223' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR TONICO LEITE' AND UPPER(TRIM(city)) = 'FORMIGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115223');

-- EE RODOLFO ALMEIDA (FORMIGA)
UPDATE schools SET inep_code = '115240' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE RODOLFO ALMEIDA' AND UPPER(TRIM(city)) = 'FORMIGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115240');

-- EE DOUTOR NORALDINO DE LIMA (FORTALEZA DE MINAS)
UPDATE schools SET inep_code = '115363' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR NORALDINO DE LIMA' AND UPPER(TRIM(city)) = 'FORTALEZA DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115363');

-- CESEC DONA EMÍLIA LEAL (PASSOS)
UPDATE schools SET inep_code = '232653' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC DONA EMÍLIA LEAL' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '232653');

-- COLÉGIO TIRADENTES PMMG (PASSOS)
UPDATE schools SET inep_code = '115479' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115479');

-- EE ABRAÃO LINCOLN (PASSOS)
UPDATE schools SET inep_code = '115380' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ABRAÃO LINCOLN' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115380');

-- EE CAETANO MACHADO DA SILVEIRA (PASSOS)
UPDATE schools SET inep_code = '115401' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CAETANO MACHADO DA SILVEIRA' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115401');

-- EE DEUS UNIVERSO E VIRTUDE (PASSOS)
UPDATE schools SET inep_code = '115428' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DEUS UNIVERSO E VIRTUDE' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115428');

-- EE DOUTOR TANCREDO DE ALMEIDA NEVES (PASSOS)
UPDATE schools SET inep_code = '115495' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR TANCREDO DE ALMEIDA NEVES' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115495');

-- EE DULCE FERREIRA DE SOUZA (PASSOS)
UPDATE schools SET inep_code = '115576' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DULCE FERREIRA DE SOUZA' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115576');

-- EE FRANCISCO DA SILVA MAIA (PASSOS)
UPDATE schools SET inep_code = '115487' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE FRANCISCO DA SILVA MAIA' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115487');

-- EE LOURENÇO ANDRADE (PASSOS)
UPDATE schools SET inep_code = '115533' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LOURENÇO ANDRADE' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115533');

-- EE LUIZ DE MELLO VIANNA SOBRINHO (PASSOS)
UPDATE schools SET inep_code = '115541' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LUIZ DE MELLO VIANNA SOBRINHO' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115541');

-- EE NAZLE JABUR (PASSOS)
UPDATE schools SET inep_code = '115517' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NAZLE JABUR' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115517');

-- EE NECA QUIRINO (PASSOS)
UPDATE schools SET inep_code = '115550' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NECA QUIRINO' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115550');

-- EE NOSSA SENHORA DA PENHA (PASSOS)
UPDATE schools SET inep_code = '115568' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DA PENHA' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115568');

-- EE PROFESSOR JAIR SANTOS (PASSOS)
UPDATE schools SET inep_code = '218154' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JAIR SANTOS' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218154');

-- EE PROFESSORA JÚLIA KUBITSCHEK (PASSOS)
UPDATE schools SET inep_code = '115398' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA JÚLIA KUBITSCHEK' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115398');

-- EE SÃO JOSÉ (PASSOS)
UPDATE schools SET inep_code = '115436' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO JOSÉ' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115436');

-- EE PADRE JOSÉ ESPÍNDOLA (PIMENTA)
UPDATE schools SET inep_code = '115606' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE JOSÉ ESPÍNDOLA' AND UPPER(TRIM(city)) = 'PIMENTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115606');

-- CESEC SEBASTIÃO GONÇALVES DA SILVA (PIUMHI)
UPDATE schools SET inep_code = '115720' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC SEBASTIÃO GONÇALVES DA SILVA' AND UPPER(TRIM(city)) = 'PIUMHI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115720');

-- EE PROFESSOR FRANCISCO DE PAULA REBELO HORTA (PIUMHI)
UPDATE schools SET inep_code = '115690' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR FRANCISCO DE PAULA REBELO HORTA' AND UPPER(TRIM(city)) = 'PIUMHI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115690');

-- EE PROFESSOR JOÃO MENEZES (PIUMHI)
UPDATE schools SET inep_code = '115703' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOÃO MENEZES' AND UPPER(TRIM(city)) = 'PIUMHI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115703');

-- EE JOSÉ SEVERIANO FILHO (SÃO JOÃO BATISTA DO GLÓRIA)
UPDATE schools SET inep_code = '115762' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ SEVERIANO FILHO' AND UPPER(TRIM(city)) = 'SÃO JOÃO BATISTA DO GLÓRIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115762');

-- EE DE FURNAS (SÃO JOSÉ DA BARRA)
UPDATE schools SET inep_code = '114901' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE FURNAS' AND UPPER(TRIM(city)) = 'SÃO JOSÉ DA BARRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '114901');

-- EE DOUTOR JUSCELINO KUBITSCHEK (SÃO JOSÉ DA BARRA)
UPDATE schools SET inep_code = '114910' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR JUSCELINO KUBITSCHEK' AND UPPER(TRIM(city)) = 'SÃO JOSÉ DA BARRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '114910');

-- EE GENERAL CARNEIRO (SÃO ROQUE DE MINAS)
UPDATE schools SET inep_code = '115789' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GENERAL CARNEIRO' AND UPPER(TRIM(city)) = 'SÃO ROQUE DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115789');

-- EE PROFESSORA IZAURA DE OLIVEIRA VILELA (SÃO ROQUE DE MINAS)
UPDATE schools SET inep_code = '346136' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA IZAURA DE OLIVEIRA VILELA' AND UPPER(TRIM(city)) = 'SÃO ROQUE DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346136');

-- EE SÃO FRANCISCO (VARGEM BONITA)
UPDATE schools SET inep_code = '115843' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO FRANCISCO' AND UPPER(TRIM(city)) = 'VARGEM BONITA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115843');

-- EE MANOEL GONÇALVES BOAVENTURA (ARAPUÁ)
UPDATE schools SET inep_code = '118419' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MANOEL GONÇALVES BOAVENTURA' AND UPPER(TRIM(city)) = 'ARAPUÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '118419');

-- EE AMADEU GONÇALVES BOAVENTURA (CARMO DO PARANAÍBA)
UPDATE schools SET inep_code = '118443' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE AMADEU GONÇALVES BOAVENTURA' AND UPPER(TRIM(city)) = 'CARMO DO PARANAÍBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '118443');

-- EE ANTÔNIO ATANÁSIO (CARMO DO PARANAÍBA)
UPDATE schools SET inep_code = '118559' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO ATANÁSIO' AND UPPER(TRIM(city)) = 'CARMO DO PARANAÍBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '118559');

-- EE LEÔNCIO FERREIRA DE MELO (CARMO DO PARANAÍBA)
UPDATE schools SET inep_code = '305341' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LEÔNCIO FERREIRA DE MELO' AND UPPER(TRIM(city)) = 'CARMO DO PARANAÍBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305341');

-- EE NOSSA SENHORA DO CARMO (CARMO DO PARANAÍBA)
UPDATE schools SET inep_code = '326631' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DO CARMO' AND UPPER(TRIM(city)) = 'CARMO DO PARANAÍBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '326631');

-- EE PROFESSOR JOSÉ HUGO GUIMARÃES (CARMO DO PARANAÍBA)
UPDATE schools SET inep_code = '118494' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOSÉ HUGO GUIMARÃES' AND UPPER(TRIM(city)) = 'CARMO DO PARANAÍBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '118494');

-- CESEC AUGUSTA RAQUEL DA SILVEIRA (LAGAMAR)
UPDATE schools SET inep_code = '118648' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC AUGUSTA RAQUEL DA SILVEIRA' AND UPPER(TRIM(city)) = 'LAGAMAR' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '118648');

-- EE AFONSO CORRÊA (LAGAMAR)
UPDATE schools SET inep_code = '118575' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE AFONSO CORRÊA' AND UPPER(TRIM(city)) = 'LAGAMAR' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '118575');

-- EE AMÉRICO ALVES (LAGAMAR)
UPDATE schools SET inep_code = '118583' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE AMÉRICO ALVES' AND UPPER(TRIM(city)) = 'LAGAMAR' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '118583');

-- EE DOM BOSCO (LAGAMAR)
UPDATE schools SET inep_code = '118605' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOM BOSCO' AND UPPER(TRIM(city)) = 'LAGAMAR' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '118605');

-- EE CORONEL CRISTIANO (LAGOA FORMOSA)
UPDATE schools SET inep_code = '118656' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL CRISTIANO' AND UPPER(TRIM(city)) = 'LAGOA FORMOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '118656');

-- EE JOSÉ MARCIANO BRANDÃO (LAGOA FORMOSA)
UPDATE schools SET inep_code = '118672' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ MARCIANO BRANDÃO' AND UPPER(TRIM(city)) = 'LAGOA FORMOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '118672');

-- EE NOSSA SENHORA DA PIEDADE (LAGOA FORMOSA)
UPDATE schools SET inep_code = '118664' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DA PIEDADE' AND UPPER(TRIM(city)) = 'LAGOA FORMOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '118664');

-- EE SANTA TEREZINHA (LAGOA GRANDE)
UPDATE schools SET inep_code = '119172' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SANTA TEREZINHA' AND UPPER(TRIM(city)) = 'LAGOA GRANDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '119172');

-- EE ANA ROCHA (MATUTINA)
UPDATE schools SET inep_code = '118737' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANA ROCHA' AND UPPER(TRIM(city)) = 'MATUTINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '118737');

-- COLÉGIO TIRADENTES PMMG (PATOS DE MINAS)
UPDATE schools SET inep_code = '118770' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '118770');

-- EE ABÍLIO CAIXETA DE QUEIROZ (PATOS DE MINAS)
UPDATE schools SET inep_code = '118818' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ABÍLIO CAIXETA DE QUEIROZ' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '118818');

-- EE ABNER AFONSO (PATOS DE MINAS)
UPDATE schools SET inep_code = '118761' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ABNER AFONSO' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '118761');

-- EE ADELAIDE MACIEL (PATOS DE MINAS)
UPDATE schools SET inep_code = '118788' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ADELAIDE MACIEL' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '118788');

-- EE AGROTÉCNICA AFONSO QUEIROZ (PATOS DE MINAS)
UPDATE schools SET inep_code = '212229' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE AGROTÉCNICA AFONSO QUEIROZ' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '212229');

-- EE ARLINDO PORTO (PATOS DE MINAS)
UPDATE schools SET inep_code = '305367' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ARLINDO PORTO' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305367');

-- EE DEIRÓ EUNÁPIO BORGES (PATOS DE MINAS)
UPDATE schools SET inep_code = '118800' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DEIRÓ EUNÁPIO BORGES' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '118800');

-- EE DONA GUIOMAR DE MELO (PATOS DE MINAS)
UPDATE schools SET inep_code = '118923' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DONA GUIOMAR DE MELO' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '118923');

-- EE DOUTOR PAULO BORGES (PATOS DE MINAS)
UPDATE schools SET inep_code = '118796' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR PAULO BORGES' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '118796');

-- EE EUSTÁQUIO JOSÉ DA SILVA (PATOS DE MINAS)
UPDATE schools SET inep_code = '342483' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE EUSTÁQUIO JOSÉ DA SILVA' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342483');

-- EE ILÍDIO CAIXETA DE MELO (PATOS DE MINAS)
UPDATE schools SET inep_code = '118834' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ILÍDIO CAIXETA DE MELO' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '118834');

-- EE JOÃO BARBOSA PORTO (PATOS DE MINAS)
UPDATE schools SET inep_code = '119032' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO BARBOSA PORTO' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '119032');

-- EE JUCA MANDU (PATOS DE MINAS)
UPDATE schools SET inep_code = '119083' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JUCA MANDU' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '119083');

-- EE MAJOR MOTA (PATOS DE MINAS)
UPDATE schools SET inep_code = '119067' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MAJOR MOTA' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '119067');

-- EE MARCOLINO DE BARROS (PATOS DE MINAS)
UPDATE schools SET inep_code = '118958' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARCOLINO DE BARROS' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '118958');

-- EE PADRE ALMIR NEVES DE MEDEIROS (PATOS DE MINAS)
UPDATE schools SET inep_code = '212237' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE ALMIR NEVES DE MEDEIROS' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '212237');

-- EE PROFESSOR ANTÔNIO DIAS MACIEL (PATOS DE MINAS)
UPDATE schools SET inep_code = '118982' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ANTÔNIO DIAS MACIEL' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '118982');

-- EE PROFESSOR MANOEL LOPES NOGUEIRA (PATOS DE MINAS)
UPDATE schools SET inep_code = '305359' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR MANOEL LOPES NOGUEIRA' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305359');

-- EE PROFESSOR RENÉ DE DEUS VIEIRA (PATOS DE MINAS)
UPDATE schools SET inep_code = '360813' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR RENÉ DE DEUS VIEIRA' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '360813');

-- EE PROFESSOR ZAMA MACIEL (PATOS DE MINAS)
UPDATE schools SET inep_code = '119024' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ZAMA MACIEL' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '119024');

-- EE PROFESSORA PAULINA DE MELO PORTO (PATOS DE MINAS)
UPDATE schools SET inep_code = '353485' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA PAULINA DE MELO PORTO' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '353485');

-- EE SANTA TEREZINHA (PATOS DE MINAS)
UPDATE schools SET inep_code = '119016' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SANTA TEREZINHA' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '119016');

-- CESEC TANCREDO NEVES (PRESIDENTE OLEGÁRIO)
UPDATE schools SET inep_code = '232645' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC TANCREDO NEVES' AND UPPER(TRIM(city)) = 'PRESIDENTE OLEGÁRIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '232645');

-- EE DE ENSINO FUNDAMENTAL - ANOS INICIAIS E FINAIS (PRESIDENTE OLEGÁRIO)
UPDATE schools SET inep_code = '375853' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL - ANOS INICIAIS E FINAIS' AND UPPER(TRIM(city)) = 'PRESIDENTE OLEGÁRIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '375853');

-- EE DE PONTE FIRME (PRESIDENTE OLEGÁRIO)
UPDATE schools SET inep_code = '119199' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE PONTE FIRME' AND UPPER(TRIM(city)) = 'PRESIDENTE OLEGÁRIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '119199');

-- EE PADRE JOSÉ ANDRÉ CALDEIRA COIMBRA (PRESIDENTE OLEGÁRIO)
UPDATE schools SET inep_code = '119121' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE JOSÉ ANDRÉ CALDEIRA COIMBRA' AND UPPER(TRIM(city)) = 'PRESIDENTE OLEGÁRIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '119121');

-- EE PRESIDENTE VARGAS (PRESIDENTE OLEGÁRIO)
UPDATE schools SET inep_code = '119164' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE VARGAS' AND UPPER(TRIM(city)) = 'PRESIDENTE OLEGÁRIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '119164');

-- EE DOUTOR ADIRON GONÇALVES BOAVENTURA (RIO PARANAÍBA)
UPDATE schools SET inep_code = '122629' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR ADIRON GONÇALVES BOAVENTURA' AND UPPER(TRIM(city)) = 'RIO PARANAÍBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '122629');

-- EE ANTERO MAGALHÃES DE AGUIAR (SANTA ROSA DA SERRA)
UPDATE schools SET inep_code = '119458' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTERO MAGALHÃES DE AGUIAR' AND UPPER(TRIM(city)) = 'SANTA ROSA DA SERRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '119458');

-- EE ZICO MENDONÇA (SÃO GONÇALO DO ABAETÉ)
UPDATE schools SET inep_code = '119504' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ZICO MENDONÇA' AND UPPER(TRIM(city)) = 'SÃO GONÇALO DO ABAETÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '119504');

-- CESEC MARIA COELI FRANCO (SÃO GOTARDO)
UPDATE schools SET inep_code = '119601' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC MARIA COELI FRANCO' AND UPPER(TRIM(city)) = 'SÃO GOTARDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '119601');

-- EE CONSELHEIRO AFONSO PENA (SÃO GOTARDO)
UPDATE schools SET inep_code = '318531' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CONSELHEIRO AFONSO PENA' AND UPPER(TRIM(city)) = 'SÃO GOTARDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '318531');

-- EE CORONEL HERMENEGILDO LADEIRA (SÃO GOTARDO)
UPDATE schools SET inep_code = '119628' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL HERMENEGILDO LADEIRA' AND UPPER(TRIM(city)) = 'SÃO GOTARDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '119628');

-- EE CORONEL OSCAR PRADOS (SÃO GOTARDO)
UPDATE schools SET inep_code = '119539' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL OSCAR PRADOS' AND UPPER(TRIM(city)) = 'SÃO GOTARDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '119539');

-- EE JOSÉ CAETANO RIBEIRO (SÃO GOTARDO)
UPDATE schools SET inep_code = '119598' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ CAETANO RIBEIRO' AND UPPER(TRIM(city)) = 'SÃO GOTARDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '119598');

-- EE PADRE SINFRÔNIO BAHIA (SÃO GOTARDO)
UPDATE schools SET inep_code = '119571' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE SINFRÔNIO BAHIA' AND UPPER(TRIM(city)) = 'SÃO GOTARDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '119571');

-- EE SÃO PIO X (SÃO GOTARDO)
UPDATE schools SET inep_code = '119563' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO PIO X' AND UPPER(TRIM(city)) = 'SÃO GOTARDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '119563');

-- EE PADRE JOSÉ COELHO (TIROS)
UPDATE schools SET inep_code = '119679' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE JOSÉ COELHO' AND UPPER(TRIM(city)) = 'TIROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '119679');

-- EE JOÃO PEREIRA BRANDÃO (VARJÃO DE MINAS)
UPDATE schools SET inep_code = '119521' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO PEREIRA BRANDÃO' AND UPPER(TRIM(city)) = 'VARJÃO DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '119521');

-- EE CÂNDIDA CORTES CORRÊA (CRUZEIRO DA FORTALEZA)
UPDATE schools SET inep_code = '278718' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CÂNDIDA CORTES CORRÊA' AND UPPER(TRIM(city)) = 'CRUZEIRO DA FORTALEZA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '278718');

-- EE IRMÃOS GUIMARÃES (GUIMARÂNIA)
UPDATE schools SET inep_code = '198943' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE IRMÃOS GUIMARÃES' AND UPPER(TRIM(city)) = 'GUIMARÂNIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '198943');

-- EE DOUTOR PEDRO DIAS DOS REIS (IBIÁ)
UPDATE schools SET inep_code = '159026' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR PEDRO DIAS DOS REIS' AND UPPER(TRIM(city)) = 'IBIÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159026');

-- EE SÃO JOSÉ (IBIÁ)
UPDATE schools SET inep_code = '159069' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO JOSÉ' AND UPPER(TRIM(city)) = 'IBIÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159069');

-- EE PADRE EUSTÁQUIO (IRAÍ DE MINAS)
UPDATE schools SET inep_code = '198960' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE EUSTÁQUIO' AND UPPER(TRIM(city)) = 'IRAÍ DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '198960');

-- EE SÃO JOSÉ DO BARREIRO (IRAÍ DE MINAS)
UPDATE schools SET inep_code = '198986' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO JOSÉ DO BARREIRO' AND UPPER(TRIM(city)) = 'IRAÍ DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '198986');

-- EE AMIR AMARAL (PATROCÍNIO)
UPDATE schools SET inep_code = '198994' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE AMIR AMARAL' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '198994');

-- EE CORONEL ELMIRO ALVES DO NASCIMENTO (PATROCÍNIO)
UPDATE schools SET inep_code = '199214' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL ELMIRO ALVES DO NASCIMENTO' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '199214');

-- EE DALVA STELA DE QUEIROZ (PATROCÍNIO)
UPDATE schools SET inep_code = '199141' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DALVA STELA DE QUEIROZ' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '199141');

-- EE DOM LUSTOSA (PATROCÍNIO)
UPDATE schools SET inep_code = '199010' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOM LUSTOSA' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '199010');

-- EE DONA COTINHA (PATROCÍNIO)
UPDATE schools SET inep_code = '199036' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DONA COTINHA' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '199036');

-- EE IRMÃ GISLENE (PATROCÍNIO)
UPDATE schools SET inep_code = '199061' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE IRMÃ GISLENE' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '199061');

-- EE JOAQUIM DIAS (PATROCÍNIO)
UPDATE schools SET inep_code = '199095' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOAQUIM DIAS' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '199095');

-- EE JOSÉ EDUARDO AQUINO (PATROCÍNIO)
UPDATE schools SET inep_code = '199133' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ EDUARDO AQUINO' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '199133');

-- EE NELY AMARAL (PATROCÍNIO)
UPDATE schools SET inep_code = '199117' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NELY AMARAL' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '199117');

-- EE ODILON BEHRENS (PATROCÍNIO)
UPDATE schools SET inep_code = '199184' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ODILON BEHRENS' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '199184');

-- EE PROFESSORA ORMY ARAÚJO AMARAL (PATROCÍNIO)
UPDATE schools SET inep_code = '310603' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ORMY ARAÚJO AMARAL' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310603');

-- EE TEREZINHA MOREIRA MARRA (PATROCÍNIO)
UPDATE schools SET inep_code = '356794' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE TEREZINHA MOREIRA MARRA' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '356794');

-- EE VENINA TAVARES AMARAL (PATROCÍNIO)
UPDATE schools SET inep_code = '199168' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE VENINA TAVARES AMARAL' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '199168');

-- EE HORÁCIO AFONSO (PERDIZES)
UPDATE schools SET inep_code = '159344' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE HORÁCIO AFONSO' AND UPPER(TRIM(city)) = 'PERDIZES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159344');

-- EE JOSEFA MARGARIDA TRINDADE (PERDIZES)
UPDATE schools SET inep_code = '159352' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSEFA MARGARIDA TRINDADE' AND UPPER(TRIM(city)) = 'PERDIZES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159352');

-- EE PADRE JOÃO BALKER (PERDIZES)
UPDATE schools SET inep_code = '159387' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE JOÃO BALKER' AND UPPER(TRIM(city)) = 'PERDIZES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159387');

-- EE PREFEITO VIRMONDES AFONSO (PERDIZES)
UPDATE schools SET inep_code = '326704' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PREFEITO VIRMONDES AFONSO' AND UPPER(TRIM(city)) = 'PERDIZES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '326704');

-- EE CORNÉLIA REGINA (SERRA DO SALITRE)
UPDATE schools SET inep_code = '199303' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORNÉLIA REGINA' AND UPPER(TRIM(city)) = 'SERRA DO SALITRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '199303');

-- EE SERRA DO SALITRE (SERRA DO SALITRE)
UPDATE schools SET inep_code = '199265' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SERRA DO SALITRE' AND UPPER(TRIM(city)) = 'SERRA DO SALITRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '199265');

-- EE TEREZA DE CASTRO MARIANO (SERRA DO SALITRE)
UPDATE schools SET inep_code = '361607' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE TEREZA DE CASTRO MARIANO' AND UPPER(TRIM(city)) = 'SERRA DO SALITRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '361607');

-- EE DE ENSINO FUNDAMENTAL E MÉDIO (BURITIZEIRO)
UPDATE schools SET inep_code = '346233' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL E MÉDIO' AND UPPER(TRIM(city)) = 'BURITIZEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346233');

-- EE PREFEITO JOSÉ MARIA PEREIRA (BURITIZEIRO)
UPDATE schools SET inep_code = '246131' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PREFEITO JOSÉ MARIA PEREIRA' AND UPPER(TRIM(city)) = 'BURITIZEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246131');

-- EE PROFESSORA SÍLVIA ALENCAR ZSCHABER (BURITIZEIRO)
UPDATE schools SET inep_code = '246140' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA SÍLVIA ALENCAR ZSCHABER' AND UPPER(TRIM(city)) = 'BURITIZEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246140');

-- EE PROFESSOR PAULO FREIRE (PIRAPORA)
UPDATE schools SET inep_code = '365270' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR PAULO FREIRE' AND UPPER(TRIM(city)) = 'PIRAPORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '365270');

-- EE PROFESSORA GEOVANINA FERREIRA DIAS (SÃO ROMÃO)
UPDATE schools SET inep_code = '346225' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA GEOVANINA FERREIRA DIAS' AND UPPER(TRIM(city)) = 'SÃO ROMÃO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346225');

-- EE GERALDO SANGUINETTE (VÁRZEA DA PALMA)
UPDATE schools SET inep_code = '223671' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GERALDO SANGUINETTE' AND UPPER(TRIM(city)) = 'VÁRZEA DA PALMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '223671');

-- EE BOLÍVAR BOANERGES DA SILVEIRA (ALTEROSA)
UPDATE schools SET inep_code = '123668' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BOLÍVAR BOANERGES DA SILVEIRA' AND UPPER(TRIM(city)) = 'ALTEROSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '123668');

-- EE DEPUTADO JALES MACHADO (ALTEROSA)
UPDATE schools SET inep_code = '123684' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DEPUTADO JALES MACHADO' AND UPPER(TRIM(city)) = 'ALTEROSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '123684');

-- EE ADOLFO FIRMINO SOUZA MARQUES (ANDRADAS)
UPDATE schools SET inep_code = '123773' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ADOLFO FIRMINO SOUZA MARQUES' AND UPPER(TRIM(city)) = 'ANDRADAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '123773');

-- EE CORONEL JOÃO MOSCONI (ANDRADAS)
UPDATE schools SET inep_code = '123706' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL JOÃO MOSCONI' AND UPPER(TRIM(city)) = 'ANDRADAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '123706');

-- EE DANIEL RIBEIRO MOGGI (ANDRADAS)
UPDATE schools SET inep_code = '123757' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DANIEL RIBEIRO MOGGI' AND UPPER(TRIM(city)) = 'ANDRADAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '123757');

-- EE DOUTOR ALCIDES MOSCONI (ANDRADAS)
UPDATE schools SET inep_code = '123714' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR ALCIDES MOSCONI' AND UPPER(TRIM(city)) = 'ANDRADAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '123714');

-- EE PROFESSOR EDMUNDO VIEIRA (ANDRADAS)
UPDATE schools SET inep_code = '123731' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR EDMUNDO VIEIRA' AND UPPER(TRIM(city)) = 'ANDRADAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '123731');

-- EE JOÃO LOURENÇO (AREADO)
UPDATE schools SET inep_code = '123846' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO LOURENÇO' AND UPPER(TRIM(city)) = 'AREADO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '123846');

-- EE JOSÉ BANDEIRA DE CARVALHO (BANDEIRA DO SUL)
UPDATE schools SET inep_code = '123897' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ BANDEIRA DE CARVALHO' AND UPPER(TRIM(city)) = 'BANDEIRA DO SUL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '123897');

-- EE AFONSO ROMÃO DE SIQUEIRA (BOTELHOS)
UPDATE schools SET inep_code = '124010' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE AFONSO ROMÃO DE SIQUEIRA' AND UPPER(TRIM(city)) = 'BOTELHOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124010');

-- EE JOÃO DE SOUZA GONÇALVES (BOTELHOS)
UPDATE schools SET inep_code = '123951' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO DE SOUZA GONÇALVES' AND UPPER(TRIM(city)) = 'BOTELHOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '123951');

-- EE MAJOR LEONEL (CABO VERDE)
UPDATE schools SET inep_code = '124095' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MAJOR LEONEL' AND UPPER(TRIM(city)) = 'CABO VERDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124095');

-- EE PROFESSOR PEDRO SATURNINO DE MAGALHÃES (CABO VERDE)
UPDATE schools SET inep_code = '124079' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR PEDRO SATURNINO DE MAGALHÃES' AND UPPER(TRIM(city)) = 'CABO VERDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124079');

-- CESEC PROFESSORA ELVIRA RODRIGUES PEREIRA (CALDAS)
UPDATE schools SET inep_code = '124214' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC PROFESSORA ELVIRA RODRIGUES PEREIRA' AND UPPER(TRIM(city)) = 'CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124214');

-- EE INDÍGENA DE EDUCAÇÃO INFANTIL ENSINO FUNDAMENTAL - ANOS INICIAIS E FINAIS E ENSINO MÉDIO (CALDAS)
UPDATE schools SET inep_code = '377929' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE INDÍGENA DE EDUCAÇÃO INFANTIL ENSINO FUNDAMENTAL - ANOS INICIAIS E FINAIS E ENSINO MÉDIO' AND UPPER(TRIM(city)) = 'CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '377929');

-- EE INDÍGENA XUCURU KARIRI - WARKANÃ DE ARUANÃ (CALDAS)
UPDATE schools SET inep_code = '322610' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE INDÍGENA XUCURU KARIRI - WARKANÃ DE ARUANÃ' AND UPPER(TRIM(city)) = 'CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322610');

-- EE JOSÉ FRANCO (CALDAS)
UPDATE schools SET inep_code = '124231' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ FRANCO' AND UPPER(TRIM(city)) = 'CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124231');

-- EE SOUZA NOVAIS (CALDAS)
UPDATE schools SET inep_code = '124184' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SOUZA NOVAIS' AND UPPER(TRIM(city)) = 'CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124184');

-- EE VICENTE LANDI JÚNIOR (CALDAS)
UPDATE schools SET inep_code = '124192' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE VICENTE LANDI JÚNIOR' AND UPPER(TRIM(city)) = 'CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124192');

-- EE ELIAS JORGE ZENUN (CAMPESTRE)
UPDATE schools SET inep_code = '124290' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ELIAS JORGE ZENUN' AND UPPER(TRIM(city)) = 'CAMPESTRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124290');

-- EE RUI BARBOSA (CAMPESTRE)
UPDATE schools SET inep_code = '124303' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE RUI BARBOSA' AND UPPER(TRIM(city)) = 'CAMPESTRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124303');

-- EE DONA COTINHA (CONCEIÇÃO DA APARECIDA)
UPDATE schools SET inep_code = '124346' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DONA COTINHA' AND UPPER(TRIM(city)) = 'CONCEIÇÃO DA APARECIDA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124346');

-- EE PADRE JOSÉ ANTÔNIO PANUCCI (CONCEIÇÃO DA APARECIDA)
UPDATE schools SET inep_code = '124311' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE JOSÉ ANTÔNIO PANUCCI' AND UPPER(TRIM(city)) = 'CONCEIÇÃO DA APARECIDA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124311');

-- EE SECRETÁRIO TRISTÃO DA CUNHA (DIVISA NOVA)
UPDATE schools SET inep_code = '124419' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SECRETÁRIO TRISTÃO DA CUNHA' AND UPPER(TRIM(city)) = 'DIVISA NOVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124419');

-- EE CALIMÉRIA SILVEIRA (IBITIÚRA DE MINAS)
UPDATE schools SET inep_code = '279293' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CALIMÉRIA SILVEIRA' AND UPPER(TRIM(city)) = 'IBITIÚRA DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '279293');

-- EE FREI LEVINO (MONTE BELO)
UPDATE schools SET inep_code = '124516' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE FREI LEVINO' AND UPPER(TRIM(city)) = 'MONTE BELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124516');

-- EE PRESIDENTE TANCREDO DE ALMEIDA NEVES (MONTE BELO)
UPDATE schools SET inep_code = '124524' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE TANCREDO DE ALMEIDA NEVES' AND UPPER(TRIM(city)) = 'MONTE BELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124524');

-- EE CESÁRIO COIMBRA (MUZAMBINHO)
UPDATE schools SET inep_code = '124575' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CESÁRIO COIMBRA' AND UPPER(TRIM(city)) = 'MUZAMBINHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124575');

-- EE PROFESSOR SALATIEL DE ALMEIDA (MUZAMBINHO)
UPDATE schools SET inep_code = '124656' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR SALATIEL DE ALMEIDA' AND UPPER(TRIM(city)) = 'MUZAMBINHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124656');

-- EE PADRE LUIZ MORENO (NOVA RESENDE)
UPDATE schools SET inep_code = '312061' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE LUIZ MORENO' AND UPPER(TRIM(city)) = 'NOVA RESENDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312061');

-- EE PROFESSOR CAIO ALBUQUERQUE (NOVA RESENDE)
UPDATE schools SET inep_code = '124664' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR CAIO ALBUQUERQUE' AND UPPER(TRIM(city)) = 'NOVA RESENDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124664');

-- EE DAVID CAMPISTA (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '124737' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DAVID CAMPISTA' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124737');

-- EE DE ENSINO FUNDAMENTAL E MÉDIO (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '338869' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL E MÉDIO' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338869');

-- EE DONA FRANCISCA TAMM BIAS FORTES (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '124745' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DONA FRANCISCA TAMM BIAS FORTES' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124745');

-- EE DOUTOR EDMUNDO GOUVEA CARDILLO (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '124877' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR EDMUNDO GOUVEA CARDILLO' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124877');

-- EE DOUTOR JOÃO EUGÊNIO DE ALMEIDA (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '124729' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR JOÃO EUGÊNIO DE ALMEIDA' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124729');

-- EE FRANCISCO ESCOBAR (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '124761' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE FRANCISCO ESCOBAR' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124761');

-- EE PROFESSOR ARLINDO PEREIRA - CENTRO DE EDUCAÇÃO POLITÉCNICA (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '124818' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ARLINDO PEREIRA - CENTRO DE EDUCAÇÃO POLITÉCNICA' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124818');

-- EE PROFESSOR JOSÉ CASTRO DE ARAÚJO (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '124923' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOSÉ CASTRO DE ARAÚJO' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124923');

-- EE PROFESSORA CLEUSA LOVATO CALIARI (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '124826' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA CLEUSA LOVATO CALIARI' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124826');

-- EE CARLOS MAGNO DE CARVALHO (SANTA RITA DE CALDAS)
UPDATE schools SET inep_code = '124974' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CARLOS MAGNO DE CARVALHO' AND UPPER(TRIM(city)) = 'SANTA RITA DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124974');

-- EE DONA RITA AMÉLIA DE CARVALHO (SANTA RITA DE CALDAS)
UPDATE schools SET inep_code = '124940' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DONA RITA AMÉLIA DE CARVALHO' AND UPPER(TRIM(city)) = 'SANTA RITA DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124940');

-- EE DIRETOR NELSON RODRIGUES (SERRANIA)
UPDATE schools SET inep_code = '125024' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DIRETOR NELSON RODRIGUES' AND UPPER(TRIM(city)) = 'SERRANIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '125024');

-- EE ABRE CAMPO (ABRE CAMPO)
UPDATE schools SET inep_code = '258971' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ABRE CAMPO' AND UPPER(TRIM(city)) = 'ABRE CAMPO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '258971');

-- EE DOM JOÃO BOSCO (ABRE CAMPO)
UPDATE schools SET inep_code = '128104' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOM JOÃO BOSCO' AND UPPER(TRIM(city)) = 'ABRE CAMPO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128104');

-- EE PROFESSOR ERNESTO DE MELO BRANDÃO (ABRE CAMPO)
UPDATE schools SET inep_code = '128139' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ERNESTO DE MELO BRANDÃO' AND UPPER(TRIM(city)) = 'ABRE CAMPO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128139');

-- EE ANTÔNIO CARLOS (ALVINÓPOLIS)
UPDATE schools SET inep_code = '128252' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO CARLOS' AND UPPER(TRIM(city)) = 'ALVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128252');

-- EE DESEMBARGADOR BARCELOS CORREA (ALVINÓPOLIS)
UPDATE schools SET inep_code = '128261' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DESEMBARGADOR BARCELOS CORREA' AND UPPER(TRIM(city)) = 'ALVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128261');

-- EE PROFESSOR CÂNDIDO GOMES (ALVINÓPOLIS)
UPDATE schools SET inep_code = '128244' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR CÂNDIDO GOMES' AND UPPER(TRIM(city)) = 'ALVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128244');

-- EE ALFREDO DO CARMO (AMPARO DO SERRA)
UPDATE schools SET inep_code = '128279' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALFREDO DO CARMO' AND UPPER(TRIM(city)) = 'AMPARO DO SERRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128279');

-- EE CÔNEGO JOSÉ ERMELINDO DE SOUZA (ARAPONGA)
UPDATE schools SET inep_code = '128325' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CÔNEGO JOSÉ ERMELINDO DE SOUZA' AND UPPER(TRIM(city)) = 'ARAPONGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128325');

-- EE JOSÉ DIAS DO CARMO (ARAPONGA)
UPDATE schools SET inep_code = '128341' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ DIAS DO CARMO' AND UPPER(TRIM(city)) = 'ARAPONGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128341');

-- EE PADRE JOSÉ EPIFÂNIO GONÇALVES (BARRA LONGA)
UPDATE schools SET inep_code = '128414' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE JOSÉ EPIFÂNIO GONÇALVES' AND UPPER(TRIM(city)) = 'BARRA LONGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128414');

-- EE CAPITÃO ARNALDO DIAS ANDRADE (CAJURI)
UPDATE schools SET inep_code = '128449' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CAPITÃO ARNALDO DIAS ANDRADE' AND UPPER(TRIM(city)) = 'CAJURI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128449');

-- EE ANTÔNIO LOPES SOARES (CANAÃ)
UPDATE schools SET inep_code = '128490' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO LOPES SOARES' AND UPPER(TRIM(city)) = 'CANAÃ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128490');

-- EE MARIA APARECIDA DAVID (CANAÃ)
UPDATE schools SET inep_code = '233200' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARIA APARECIDA DAVID' AND UPPER(TRIM(city)) = 'CANAÃ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '233200');

-- EE PRESIDENTE TANCREDO NEVES (DOM SILVÉRIO)
UPDATE schools SET inep_code = '128678' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE TANCREDO NEVES' AND UPPER(TRIM(city)) = 'DOM SILVÉRIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128678');

-- EE AGOSTINHO HIPÓLITO DE F FREIRE (GUARACIABA)
UPDATE schools SET inep_code = '128694' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE AGOSTINHO HIPÓLITO DE F FREIRE' AND UPPER(TRIM(city)) = 'GUARACIABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128694');

-- EE HERMÓGENES FERREIRA DA SILVA (GUARACIABA)
UPDATE schools SET inep_code = '128732' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE HERMÓGENES FERREIRA DA SILVA' AND UPPER(TRIM(city)) = 'GUARACIABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128732');

-- EE JOSÉ MATEUS DE VASCONCELOS (GUARACIABA)
UPDATE schools SET inep_code = '128716' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ MATEUS DE VASCONCELOS' AND UPPER(TRIM(city)) = 'GUARACIABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128716');

-- EE DE PISCAMBA (JEQUERI)
UPDATE schools SET inep_code = '128791' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE PISCAMBA' AND UPPER(TRIM(city)) = 'JEQUERI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128791');

-- EE DO GROTA (JEQUERI)
UPDATE schools SET inep_code = '128775' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DO GROTA' AND UPPER(TRIM(city)) = 'JEQUERI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128775');

-- EE PADRE BENEVENUTO (JEQUERI)
UPDATE schools SET inep_code = '128741' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE BENEVENUTO' AND UPPER(TRIM(city)) = 'JEQUERI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128741');

-- EE SÃO VICENTE DO GRAMA (JEQUERI)
UPDATE schools SET inep_code = '128821' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO VICENTE DO GRAMA' AND UPPER(TRIM(city)) = 'JEQUERI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128821');

-- EE TENENTE MOL (JEQUERI)
UPDATE schools SET inep_code = '128759' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE TENENTE MOL' AND UPPER(TRIM(city)) = 'JEQUERI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128759');

-- EE DOUTOR FRANCISCO VIEIRA MARTINS (ORATÓRIOS)
UPDATE schools SET inep_code = '129135' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR FRANCISCO VIEIRA MARTINS' AND UPPER(TRIM(city)) = 'ORATÓRIOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129135');

-- EE ALFENO FRANCISCO DO CARMO (PEDRA BONITA)
UPDATE schools SET inep_code = '353825' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALFENO FRANCISCO DO CARMO' AND UPPER(TRIM(city)) = 'PEDRA BONITA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '353825');

-- EE DOM OSCAR DE OLIVEIRA (PEDRA BONITA)
UPDATE schools SET inep_code = '128147' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOM OSCAR DE OLIVEIRA' AND UPPER(TRIM(city)) = 'PEDRA BONITA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128147');

-- EE JOSÉ ALBINO LEAL (PEDRA DO ANTA)
UPDATE schools SET inep_code = '128856' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ ALBINO LEAL' AND UPPER(TRIM(city)) = 'PEDRA DO ANTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128856');

-- EE CORONEL ANTONINHO (PIEDADE DE PONTE NOVA)
UPDATE schools SET inep_code = '128881' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL ANTONINHO' AND UPPER(TRIM(city)) = 'PIEDADE DE PONTE NOVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128881');

-- CESEC PROFESSORA VERA PARENTONI (PONTE NOVA)
UPDATE schools SET inep_code = '129127' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC PROFESSORA VERA PARENTONI' AND UPPER(TRIM(city)) = 'PONTE NOVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129127');

-- EE ANTÔNIO COELHO (PONTE NOVA)
UPDATE schools SET inep_code = '338877' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO COELHO' AND UPPER(TRIM(city)) = 'PONTE NOVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338877');

-- EE CAETANO MARINHO (PONTE NOVA)
UPDATE schools SET inep_code = '128902' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CAETANO MARINHO' AND UPPER(TRIM(city)) = 'PONTE NOVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128902');

-- EE CARLOS TRIVELLATO (PONTE NOVA)
UPDATE schools SET inep_code = '128929' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CARLOS TRIVELLATO' AND UPPER(TRIM(city)) = 'PONTE NOVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128929');

-- EE CORONEL CANTÍDIO DRUMOND (PONTE NOVA)
UPDATE schools SET inep_code = '128945' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL CANTÍDIO DRUMOND' AND UPPER(TRIM(city)) = 'PONTE NOVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128945');

-- EE PROFESSOR ANTÔNIO GONÇALVES LANNA (PONTE NOVA)
UPDATE schools SET inep_code = '129062' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ANTÔNIO GONÇALVES LANNA' AND UPPER(TRIM(city)) = 'PONTE NOVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129062');

-- EE PROFESSOR RAYMUNDO MARTINIANO FERREIRA (PONTE NOVA)
UPDATE schools SET inep_code = '129071' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR RAYMUNDO MARTINIANO FERREIRA' AND UPPER(TRIM(city)) = 'PONTE NOVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129071');

-- EE SENADOR ANTÔNIO MARTINS (PONTE NOVA)
UPDATE schools SET inep_code = '129101' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SENADOR ANTÔNIO MARTINS' AND UPPER(TRIM(city)) = 'PONTE NOVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129101');

-- EE CORONEL AMANTINO (PORTO FIRME)
UPDATE schools SET inep_code = '310590' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL AMANTINO' AND UPPER(TRIM(city)) = 'PORTO FIRME' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310590');

-- EE IMACULADA CONCEIÇÃO (PORTO FIRME)
UPDATE schools SET inep_code = '129194' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE IMACULADA CONCEIÇÃO' AND UPPER(TRIM(city)) = 'PORTO FIRME' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129194');

-- CESEC RÉCIO DE SOUZA RIBEIRO (RAUL SOARES)
UPDATE schools SET inep_code = '129241' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC RÉCIO DE SOUZA RIBEIRO' AND UPPER(TRIM(city)) = 'RAUL SOARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129241');

-- EE ALBANO PIRES (RAUL SOARES)
UPDATE schools SET inep_code = '129283' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALBANO PIRES' AND UPPER(TRIM(city)) = 'RAUL SOARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129283');

-- EE BENEDITO VALADARES (RAUL SOARES)
UPDATE schools SET inep_code = '129224' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BENEDITO VALADARES' AND UPPER(TRIM(city)) = 'RAUL SOARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129224');

-- EE DOM HELVÉCIO GOMES DE OLIVEIRA (RAUL SOARES)
UPDATE schools SET inep_code = '129259' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOM HELVÉCIO GOMES DE OLIVEIRA' AND UPPER(TRIM(city)) = 'RAUL SOARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129259');

-- EE DR LUIZ MARTINS SOARES (RAUL SOARES)
UPDATE schools SET inep_code = '129305' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DR LUIZ MARTINS SOARES' AND UPPER(TRIM(city)) = 'RAUL SOARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129305');

-- EE JOÃO FELISBERTO DA COSTA (RAUL SOARES)
UPDATE schools SET inep_code = '129275' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO FELISBERTO DA COSTA' AND UPPER(TRIM(city)) = 'RAUL SOARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129275');

-- EE PADRE JÚLIO MARIA (RAUL SOARES)
UPDATE schools SET inep_code = '129267' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE JÚLIO MARIA' AND UPPER(TRIM(city)) = 'RAUL SOARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129267');

-- EE REGINA PACIS (RAUL SOARES)
UPDATE schools SET inep_code = '129313' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE REGINA PACIS' AND UPPER(TRIM(city)) = 'RAUL SOARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129313');

-- EE IMACULADA CONCEIÇÃO (RIO CASCA)
UPDATE schools SET inep_code = '129381' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE IMACULADA CONCEIÇÃO' AND UPPER(TRIM(city)) = 'RIO CASCA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129381');

-- EE MARIA AMÉLIA (RIO DOCE)
UPDATE schools SET inep_code = '129437' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARIA AMÉLIA' AND UPPER(TRIM(city)) = 'RIO DOCE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129437');

-- EE DOUTOR OTÁVIO SOARES (SANTA CRUZ DO ESCALVADO)
UPDATE schools SET inep_code = '129461' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR OTÁVIO SOARES' AND UPPER(TRIM(city)) = 'SANTA CRUZ DO ESCALVADO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129461');

-- EE MARIANO GOMES (SANTO ANTÔNIO DO GRAMA)
UPDATE schools SET inep_code = '129534' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARIANO GOMES' AND UPPER(TRIM(city)) = 'SANTO ANTÔNIO DO GRAMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129534');

-- EE JOSÉ DE ASSIS PINTO (SÃO MIGUEL DO ANTA)
UPDATE schools SET inep_code = '129551' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ DE ASSIS PINTO' AND UPPER(TRIM(city)) = 'SÃO MIGUEL DO ANTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129551');

-- EE PEDRO LESSA (SÃO MIGUEL DO ANTA)
UPDATE schools SET inep_code = '129585' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PEDRO LESSA' AND UPPER(TRIM(city)) = 'SÃO MIGUEL DO ANTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129585');

-- EE DO LAJÃO (SÃO PEDRO DOS FERROS)
UPDATE schools SET inep_code = '129593' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DO LAJÃO' AND UPPER(TRIM(city)) = 'SÃO PEDRO DOS FERROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129593');

-- EE OMAR REZENDE PEREZ (SÃO PEDRO DOS FERROS)
UPDATE schools SET inep_code = '129666' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE OMAR REZENDE PEREZ' AND UPPER(TRIM(city)) = 'SÃO PEDRO DOS FERROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129666');

-- EE SENADOR LEVINDO COELHO (SÃO PEDRO DOS FERROS)
UPDATE schools SET inep_code = '129658' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SENADOR LEVINDO COELHO' AND UPPER(TRIM(city)) = 'SÃO PEDRO DOS FERROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129658');

-- EE SÃO SEBASTIÃO (SEM-PEIXE)
UPDATE schools SET inep_code = '128686' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO SEBASTIÃO' AND UPPER(TRIM(city)) = 'SEM-PEIXE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128686');

-- EE CLÉLIA BERNARDES (SERICITA)
UPDATE schools SET inep_code = '129674' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CLÉLIA BERNARDES' AND UPPER(TRIM(city)) = 'SERICITA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129674');

-- EE ANTÔNIO MOREIRA DE QUEIROZ (TEIXEIRAS)
UPDATE schools SET inep_code = '317420' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO MOREIRA DE QUEIROZ' AND UPPER(TRIM(city)) = 'TEIXEIRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '317420');

-- EE DOUTOR MARIANO DA ROCHA (TEIXEIRAS)
UPDATE schools SET inep_code = '129763' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR MARIANO DA ROCHA' AND UPPER(TRIM(city)) = 'TEIXEIRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129763');

-- EE CUSTÓDIO MARTINS DA SILVA (URUCÂNIA)
UPDATE schools SET inep_code = '129801' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CUSTÓDIO MARTINS DA SILVA' AND UPPER(TRIM(city)) = 'URUCÂNIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129801');

-- EE HELDER DE AQUINO (URUCÂNIA)
UPDATE schools SET inep_code = '129828' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE HELDER DE AQUINO' AND UPPER(TRIM(city)) = 'URUCÂNIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129828');

-- EE PROFESSOR MANUEL RUFINO (URUCÂNIA)
UPDATE schools SET inep_code = '129836' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR MANUEL RUFINO' AND UPPER(TRIM(city)) = 'URUCÂNIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129836');

-- EE FARMACÊUTICO SOARES (VERMELHO NOVO)
UPDATE schools SET inep_code = '129321' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE FARMACÊUTICO SOARES' AND UPPER(TRIM(city)) = 'VERMELHO NOVO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129321');

-- CESEC DOUTOR ALTAMIRO SARAIVA (VIÇOSA)
UPDATE schools SET inep_code = '259551' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC DOUTOR ALTAMIRO SARAIVA' AND UPPER(TRIM(city)) = 'VIÇOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '259551');

-- EE ALICE LOUREIRO (VIÇOSA)
UPDATE schools SET inep_code = '130036' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALICE LOUREIRO' AND UPPER(TRIM(city)) = 'VIÇOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '130036');

-- EE DR RAIMUNDO ALVES TORRES (VIÇOSA)
UPDATE schools SET inep_code = '129992' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DR RAIMUNDO ALVES TORRES' AND UPPER(TRIM(city)) = 'VIÇOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129992');

-- EE EFFIE ROLFS (VIÇOSA)
UPDATE schools SET inep_code = '129861' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE EFFIE ROLFS' AND UPPER(TRIM(city)) = 'VIÇOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129861');

-- EE JOSÉ LOURENÇO DE FREITAS (VIÇOSA)
UPDATE schools SET inep_code = '130044' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ LOURENÇO DE FREITAS' AND UPPER(TRIM(city)) = 'VIÇOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '130044');

-- EE PADRE ÁLVARO CORREA BORGES (VIÇOSA)
UPDATE schools SET inep_code = '129941' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE ÁLVARO CORREA BORGES' AND UPPER(TRIM(city)) = 'VIÇOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129941');

-- EE RAUL DE LEONI (VIÇOSA)
UPDATE schools SET inep_code = '217778' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE RAUL DE LEONI' AND UPPER(TRIM(city)) = 'VIÇOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217778');

-- EE SANTA RITA DE CÁSSIA (VIÇOSA)
UPDATE schools SET inep_code = '130001' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SANTA RITA DE CÁSSIA' AND UPPER(TRIM(city)) = 'VIÇOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '130001');

-- EE JOSÉ GOMES DE MORAIS FILHO (ALBERTINA)
UPDATE schools SET inep_code = '294705' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ GOMES DE MORAIS FILHO' AND UPPER(TRIM(city)) = 'ALBERTINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '294705');

-- EE VERNER GRINBERG (CAMANDUCAIA)
UPDATE schools SET inep_code = '342700' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE VERNER GRINBERG' AND UPPER(TRIM(city)) = 'CAMANDUCAIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342700');

-- EE MENDES DE OLIVEIRA (CONGONHAL)
UPDATE schools SET inep_code = '124389' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MENDES DE OLIVEIRA' AND UPPER(TRIM(city)) = 'CONGONHAL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124389');

-- EE PREFEITO CELSO VIEIRA VILELA (HELIODORA)
UPDATE schools SET inep_code = '172766' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PREFEITO CELSO VIEIRA VILELA' AND UPPER(TRIM(city)) = 'HELIODORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '172766');

-- EE CRISTIANO MACHADO (IPUIÚNA)
UPDATE schools SET inep_code = '124460' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CRISTIANO MACHADO' AND UPPER(TRIM(city)) = 'IPUIÚNA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124460');

-- COLÉGIO TIRADENTES PMMG (POUSO ALEGRE)
UPDATE schools SET inep_code = '362280' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG' AND UPPER(TRIM(city)) = 'POUSO ALEGRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '362280');

-- EE DE ENSINO MÉDIO (POUSO ALEGRE)
UPDATE schools SET inep_code = '372099' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' AND UPPER(TRIM(city)) = 'POUSO ALEGRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '372099');

-- EE DE ENSINO MÉDIO (POUSO ALEGRE)
UPDATE schools SET inep_code = '372102' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' AND UPPER(TRIM(city)) = 'POUSO ALEGRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '372102');