-- EM DOUTOR EMÍLIO ABDON PÓVOA (SÃO LOURENÇO)
UPDATE schools SET inep_code = '242144' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOUTOR EMÍLIO ABDON PÓVOA' AND UPPER(TRIM(city)) = 'SÃO LOURENÇO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '242144');

-- EM MANOEL MONTEIRO (SÃO LOURENÇO)
UPDATE schools SET inep_code = '179078' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MANOEL MONTEIRO' AND UPPER(TRIM(city)) = 'SÃO LOURENÇO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '179078');

-- EM PADRE FRANCISCO FREITAS CARVALHO (SÃO SEBASTIÃO DO RIO VERDE)
UPDATE schools SET inep_code = '174211' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PADRE FRANCISCO FREITAS CARVALHO' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO RIO VERDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174211');

-- EM PROFESSORA MARY VIEIRA RIBEIRO SOUZA (SERITINGA)
UPDATE schools SET inep_code = '271934' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA MARY VIEIRA RIBEIRO SOUZA' AND UPPER(TRIM(city)) = 'SERITINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '271934');

-- EM RIBEIRO PENA (SERRANOS)
UPDATE schools SET inep_code = '174301' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM RIBEIRO PENA' AND UPPER(TRIM(city)) = 'SERRANOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174301');

-- EM SÍLVIA NUNES (CASA GRANDE)
UPDATE schools SET inep_code = '272043' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SÍLVIA NUNES' AND UPPER(TRIM(city)) = 'CASA GRANDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '272043');

-- EM DOM JOÃO MUNIZ (CONGONHAS)
UPDATE schools SET inep_code = '217107' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOM JOÃO MUNIZ' AND UPPER(TRIM(city)) = 'CONGONHAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217107');

-- EM DONA CAETANA PEREIRA TRINDADE (CONGONHAS)
UPDATE schools SET inep_code = '321036' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DONA CAETANA PEREIRA TRINDADE' AND UPPER(TRIM(city)) = 'CONGONHAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '321036');

-- EM FORTUNATA DE FREITAS JUNQUEIRA (CONGONHAS)
UPDATE schools SET inep_code = '244261' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM FORTUNATA DE FREITAS JUNQUEIRA' AND UPPER(TRIM(city)) = 'CONGONHAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '244261');

-- EM JAIR ELIAS (CONGONHAS)
UPDATE schools SET inep_code = '327760' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JAIR ELIAS' AND UPPER(TRIM(city)) = 'CONGONHAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '327760');

-- EM JOÃO NARCISO (CONGONHAS)
UPDATE schools SET inep_code = '193402' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOÃO NARCISO' AND UPPER(TRIM(city)) = 'CONGONHAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193402');

-- EM JOSÉ MONTEIRO DE CASTRO (CONGONHAS)
UPDATE schools SET inep_code = '249360' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ MONTEIRO DE CASTRO' AND UPPER(TRIM(city)) = 'CONGONHAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '249360');

-- EM JUDITH AUGUSTA FERREIRA (CONGONHAS)
UPDATE schools SET inep_code = '193445' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JUDITH AUGUSTA FERREIRA' AND UPPER(TRIM(city)) = 'CONGONHAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193445');

-- EM MICHAEL PEREIRA DE SOUZA (CONGONHAS)
UPDATE schools SET inep_code = '320994' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MICHAEL PEREIRA DE SOUZA' AND UPPER(TRIM(city)) = 'CONGONHAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '320994');

-- EM ROSÁLIA ANDRADE DA GLÓRIA (CONGONHAS)
UPDATE schools SET inep_code = '216879' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ROSÁLIA ANDRADE DA GLÓRIA' AND UPPER(TRIM(city)) = 'CONGONHAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '216879');

-- EM SENHOR ODORICO MARTINHO DA SILVA (CONGONHAS)
UPDATE schools SET inep_code = '194590' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SENHOR ODORICO MARTINHO DA SILVA' AND UPPER(TRIM(city)) = 'CONGONHAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '194590');

-- CAIC EM DR RUI PENA (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '266493' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CAIC EM DR RUI PENA' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '266493');

-- EM ARNALDO RODRIGUES PEREIRA (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '194689' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ARNALDO RODRIGUES PEREIRA' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '194689');

-- EM JAIR NORONHA (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '194727' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JAIR NORONHA' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '194727');

-- EM MARINHO FERNANDES (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '312762' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARINHO FERNANDES' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312762');

-- EM MERIDIONAL (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '196207' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MERIDIONAL' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196207');

-- EM NAPOLEÃO REIS (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '196215' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM NAPOLEÃO REIS' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196215');

-- EM PROFESSOR DORIOL BEATO (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '221562' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR DORIOL BEATO' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '221562');

-- EM PROFESSOR LUÍS CARLOS GOMES BEATO (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '266485' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR LUÍS CARLOS GOMES BEATO' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '266485');

-- EM PROFESSORA NILCE RAMOS MOREIRA (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '245682' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA NILCE RAMOS MOREIRA' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '245682');

-- EM VEREADOR JOSÉ ALEIXO DE MATOS (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '319457' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM VEREADOR JOSÉ ALEIXO DE MATOS' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '319457');

-- EM MONSENHOR RAUL COUTINHO (CRISTIANO OTONI)
UPDATE schools SET inep_code = '193810' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MONSENHOR RAUL COUTINHO' AND UPPER(TRIM(city)) = 'CRISTIANO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193810');

-- EM ZULEIKA HALFED DE ALBUQUERQUE (JECEABA)
UPDATE schools SET inep_code = '268933' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ZULEIKA HALFED DE ALBUQUERQUE' AND UPPER(TRIM(city)) = 'JECEABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '268933');

-- COLÉGIO MUNICIPAL JOÃO XXIII (OURO BRANCO)
UPDATE schools SET inep_code = '194140' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MUNICIPAL JOÃO XXIII' AND UPPER(TRIM(city)) = 'OURO BRANCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '194140');

-- COLÉGIO MUNICIPAL PIO XII (OURO BRANCO)
UPDATE schools SET inep_code = '196321' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MUNICIPAL PIO XII' AND UPPER(TRIM(city)) = 'OURO BRANCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196321');

-- EM LIVREMENTE (OURO BRANCO)
UPDATE schools SET inep_code = '216925' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM LIVREMENTE' AND UPPER(TRIM(city)) = 'OURO BRANCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '216925');

-- EM NOSSA SENHORA DO CARMO (OURO BRANCO)
UPDATE schools SET inep_code = '195529' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM NOSSA SENHORA DO CARMO' AND UPPER(TRIM(city)) = 'OURO BRANCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '195529');

-- EM OSWALDO CRUZ (OURO BRANCO)
UPDATE schools SET inep_code = '195545' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM OSWALDO CRUZ' AND UPPER(TRIM(city)) = 'OURO BRANCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '195545');

-- EM RAIMUNDO CAMPOS (OURO BRANCO)
UPDATE schools SET inep_code = '195570' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM RAIMUNDO CAMPOS' AND UPPER(TRIM(city)) = 'OURO BRANCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '195570');

-- EM ANÍSIO PINTO (SANTANA DOS MONTES)
UPDATE schools SET inep_code = '194417' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANÍSIO PINTO' AND UPPER(TRIM(city)) = 'SANTANA DOS MONTES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '194417');

-- EM PADRE ARMANDO CESÁRIO (SANTANA DOS MONTES)
UPDATE schools SET inep_code = '331333' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PADRE ARMANDO CESÁRIO' AND UPPER(TRIM(city)) = 'SANTANA DOS MONTES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '331333');

-- EM AMÉLIA D'ANUNCIAÇÃO PYRAMO (SÃO BRÁS DO SUAÇUÍ)
UPDATE schools SET inep_code = '216950' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM AMÉLIA D''ANUNCIAÇÃO PYRAMO' AND UPPER(TRIM(city)) = 'SÃO BRÁS DO SUAÇUÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '216950');

-- EM ANTÔNIO FIRMINO (BELO ORIENTE)
UPDATE schools SET inep_code = '191868' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANTÔNIO FIRMINO' AND UPPER(TRIM(city)) = 'BELO ORIENTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191868');

-- EM BOM JESUS DO BAGRE (BELO ORIENTE)
UPDATE schools SET inep_code = '190730' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM BOM JESUS DO BAGRE' AND UPPER(TRIM(city)) = 'BELO ORIENTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '190730');

-- EM DE ESPERANÇA (BELO ORIENTE)
UPDATE schools SET inep_code = '191892' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DE ESPERANÇA' AND UPPER(TRIM(city)) = 'BELO ORIENTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191892');

-- EM FRANCISCO GONÇALVES BRITTO (BELO ORIENTE)
UPDATE schools SET inep_code = '191922' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM FRANCISCO GONÇALVES BRITTO' AND UPPER(TRIM(city)) = 'BELO ORIENTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191922');

-- EM HILDA MORAIS (BELO ORIENTE)
UPDATE schools SET inep_code = '271187' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM HILDA MORAIS' AND UPPER(TRIM(city)) = 'BELO ORIENTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '271187');

-- EM ARTUR DA COSTA E SILVA (BRAÚNAS)
UPDATE schools SET inep_code = '192007' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ARTUR DA COSTA E SILVA' AND UPPER(TRIM(city)) = 'BRAÚNAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '192007');

-- EM ARGEU BRANDÃO (CORONEL FABRICIANO)
UPDATE schools SET inep_code = '192139' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ARGEU BRANDÃO' AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '192139');

-- EM BOA VISTA (CORONEL FABRICIANO)
UPDATE schools SET inep_code = '358975' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM BOA VISTA' AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '358975');

-- EM MARIA DA CONCEIÇÃO ATAÍDE (CORONEL FABRICIANO)
UPDATE schools SET inep_code = '192147' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA DA CONCEIÇÃO ATAÍDE' AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '192147');

-- EM MARIA DAS GRAÇAS FERREIRA (CORONEL FABRICIANO)
UPDATE schools SET inep_code = '249319' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA DAS GRAÇAS FERREIRA' AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '249319');

-- EM VER  PAULO FRANKLIN (CORONEL FABRICIANO)
UPDATE schools SET inep_code = '192180' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM VER  PAULO FRANKLIN' AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '192180');

-- EM VEREADOR NICANOR ATAÍDE (CORONEL FABRICIANO)
UPDATE schools SET inep_code = '192171' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM VEREADOR NICANOR ATAÍDE' AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '192171');

-- EM ALTINA OLÍVIA GONÇALVES (IPATINGA)
UPDATE schools SET inep_code = '192252' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ALTINA OLÍVIA GONÇALVES' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '192252');

-- EM ARTUR BERNARDES (IPATINGA)
UPDATE schools SET inep_code = '192317' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ARTUR BERNARDES' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '192317');

-- EM CARLOS DRUMOND DE ANDRADE (IPATINGA)
UPDATE schools SET inep_code = '250805' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CARLOS DRUMOND DE ANDRADE' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '250805');

-- EM CHIRLENE CRISTINA PEREIRA (IPATINGA)
UPDATE schools SET inep_code = '229636' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CHIRLENE CRISTINA PEREIRA' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '229636');

-- EM DEOLINDA TAVARES LAMEGO (IPATINGA)
UPDATE schools SET inep_code = '192392' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DEOLINDA TAVARES LAMEGO' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '192392');

-- EM EVERSON MAGALHÃES LAGE (IPATINGA)
UPDATE schools SET inep_code = '231355' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM EVERSON MAGALHÃES LAGE' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '231355');

-- EM HENRIQUE FREITAS BADARÓ (IPATINGA)
UPDATE schools SET inep_code = '229644' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM HENRIQUE FREITAS BADARÓ' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '229644');

-- EM JOÃO REIS DE SOUZA (IPATINGA)
UPDATE schools SET inep_code = '231401' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOÃO REIS DE SOUZA' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '231401');

-- EM LEVINDO MARIANO (IPATINGA)
UPDATE schools SET inep_code = '192295' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM LEVINDO MARIANO' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '192295');

-- EM MÁRCIO ANDRADE GUERRA (IPATINGA)
UPDATE schools SET inep_code = '192325' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MÁRCIO ANDRADE GUERRA' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '192325');

-- EM NELCINA ROSA DE JESUS (IPATINGA)
UPDATE schools SET inep_code = '192384' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM NELCINA ROSA DE JESUS' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '192384');

-- EM PADRE BERTOLLO (IPATINGA)
UPDATE schools SET inep_code = '191230' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PADRE BERTOLLO' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191230');

-- EM PADRE CÍCERO DE CASTRO (IPATINGA)
UPDATE schools SET inep_code = '192406' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PADRE CÍCERO DE CASTRO' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '192406');

-- EM PAULO FREIRE (IPATINGA)
UPDATE schools SET inep_code = '295299' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PAULO FREIRE' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '295299');

-- EM PROFESSOR EVALDO FONTES (IPATINGA)
UPDATE schools SET inep_code = '192457' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR EVALDO FONTES' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '192457');

-- EM PROFESSORA MARIA CONCEIÇÃO PENA ROCHA (IPATINGA)
UPDATE schools SET inep_code = '192333' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA MARIA CONCEIÇÃO PENA ROCHA' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '192333');

-- EM TEREZINHA NIVIA DE OLIVEIRA LOPES (IPATINGA)
UPDATE schools SET inep_code = '332445' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM TEREZINHA NIVIA DE OLIVEIRA LOPES' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '332445');

-- EM VILMA DE FARIA SILVA (IPATINGA)
UPDATE schools SET inep_code = '249301' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM VILMA DE FARIA SILVA' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '249301');

-- EM ZÉLIA DUARTE PASSOS (IPATINGA)
UPDATE schools SET inep_code = '192465' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ZÉLIA DUARTE PASSOS' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '192465');

-- EM CORONEL FELÍCIO MIRANDA (JAGUARAÇU)
UPDATE schools SET inep_code = '191311' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CORONEL FELÍCIO MIRANDA' AND UPPER(TRIM(city)) = 'JAGUARAÇU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191311');

-- EM ANTÔNIO CAMILO DA SILVA (MESQUITA)
UPDATE schools SET inep_code = '192848' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANTÔNIO CAMILO DA SILVA' AND UPPER(TRIM(city)) = 'MESQUITA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '192848');

-- EM DE TIMÓTEO (TIMÓTEO)
UPDATE schools SET inep_code = '192911' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DE TIMÓTEO' AND UPPER(TRIM(city)) = 'TIMÓTEO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '192911');

-- EM LIMOEIRO (TIMÓTEO)
UPDATE schools SET inep_code = '192902' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM LIMOEIRO' AND UPPER(TRIM(city)) = 'TIMÓTEO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '192902');

-- EM NOVO TEMPO (TIMÓTEO)
UPDATE schools SET inep_code = '296350' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM NOVO TEMPO' AND UPPER(TRIM(city)) = 'TIMÓTEO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '296350');

-- EM PROFESSORA MARIA APARECIDA MARTINS PRADO (TIMÓTEO)
UPDATE schools SET inep_code = '254100' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA MARIA APARECIDA MARTINS PRADO' AND UPPER(TRIM(city)) = 'TIMÓTEO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '254100');

-- INSTITUTO MUNICIPAL DE EDUCAÇÃO TÉCNICA DE TIMÓTEO (TIMÓTEO)
UPDATE schools SET inep_code = '215376' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO MUNICIPAL DE EDUCAÇÃO TÉCNICA DE TIMÓTEO' AND UPPER(TRIM(city)) = 'TIMÓTEO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '215376');

-- EM PROFA LAURA MARTINS (AUGUSTO DE LIMA)
UPDATE schools SET inep_code = '251241' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFA LAURA MARTINS' AND UPPER(TRIM(city)) = 'AUGUSTO DE LIMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '251241');

-- EM ANTONIO MALDINE (CORINTO)
UPDATE schools SET inep_code = '143057' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANTONIO MALDINE' AND UPPER(TRIM(city)) = 'CORINTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '143057');

-- EM CRISTO REI (CORINTO)
UPDATE schools SET inep_code = '145556' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CRISTO REI' AND UPPER(TRIM(city)) = 'CORINTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '145556');

-- EM DONA MARIA SOFIA (FELIXLÂNDIA)
UPDATE schools SET inep_code = '140929' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DONA MARIA SOFIA' AND UPPER(TRIM(city)) = 'FELIXLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140929');

-- EM PEDRO EPIFÂNIO (FELIXLÂNDIA)
UPDATE schools SET inep_code = '143642' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PEDRO EPIFÂNIO' AND UPPER(TRIM(city)) = 'FELIXLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '143642');

-- EM TERESA COSTA BRAVO (FELIXLÂNDIA)
UPDATE schools SET inep_code = '143588' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM TERESA COSTA BRAVO' AND UPPER(TRIM(city)) = 'FELIXLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '143588');

-- EM PROFA ODÍLIA COSTA (JOAQUIM FELÍCIO)
UPDATE schools SET inep_code = '271071' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFA ODÍLIA COSTA' AND UPPER(TRIM(city)) = 'JOAQUIM FELÍCIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '271071');

-- EM CARLOS PEREIRA MARIZ (MORRO DA GARÇA)
UPDATE schools SET inep_code = '144347' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CARLOS PEREIRA MARIZ' AND UPPER(TRIM(city)) = 'MORRO DA GARÇA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '144347');

-- EM PE JOAQUIM DA SILVEIRA (MORRO DA GARÇA)
UPDATE schools SET inep_code = '141283' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PE JOAQUIM DA SILVEIRA' AND UPPER(TRIM(city)) = 'MORRO DA GARÇA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141283');

-- EM ANTÔNIO FONSECA LEAL (TRÊS MARIAS)
UPDATE schools SET inep_code = '273295' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANTÔNIO FONSECA LEAL' AND UPPER(TRIM(city)) = 'TRÊS MARIAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '273295');

-- EM GERALDA MÁRCIA PEREIRA GONÇALVES (TRÊS MARIAS)
UPDATE schools SET inep_code = '142018' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM GERALDA MÁRCIA PEREIRA GONÇALVES' AND UPPER(TRIM(city)) = 'TRÊS MARIAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '142018');

-- EM MEMORIAL ZUMBI (TRÊS MARIAS)
UPDATE schools SET inep_code = '318400' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MEMORIAL ZUMBI' AND UPPER(TRIM(city)) = 'TRÊS MARIAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '318400');

-- EM POLICENA ALVES DE AMORIM (TRÊS MARIAS)
UPDATE schools SET inep_code = '145360' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM POLICENA ALVES DE AMORIM' AND UPPER(TRIM(city)) = 'TRÊS MARIAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '145360');

-- EM ROSA PEDROSO DE ALMEIDA (TRÊS MARIAS)
UPDATE schools SET inep_code = '142000' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ROSA PEDROSO DE ALMEIDA' AND UPPER(TRIM(city)) = 'TRÊS MARIAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '142000');

-- EM VEREADOR CARLINDO NASCIMENTO GAIA (TRÊS MARIAS)
UPDATE schools SET inep_code = '271276' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM VEREADOR CARLINDO NASCIMENTO GAIA' AND UPPER(TRIM(city)) = 'TRÊS MARIAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '271276');

-- EM NÚCLEO DA ESTIVA (CARBONITA)
UPDATE schools SET inep_code = '305405' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM NÚCLEO DA ESTIVA' AND UPPER(TRIM(city)) = 'CARBONITA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305405');

-- EM AMADOR AGUIAR (CONCEIÇÃO DO MATO DENTRO)
UPDATE schools SET inep_code = '356689' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM AMADOR AGUIAR' AND UPPER(TRIM(city)) = 'CONCEIÇÃO DO MATO DENTRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '356689');

-- EM DOUTOR JOÃO ANTUNES DE OLIVEIRA (DIAMANTINA)
UPDATE schools SET inep_code = '236217' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOUTOR JOÃO ANTUNES DE OLIVEIRA' AND UPPER(TRIM(city)) = 'DIAMANTINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '236217');

-- EM CRIANÇA FELIZ (ITAMARANDIBA)
UPDATE schools SET inep_code = '265837' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CRIANÇA FELIZ' AND UPPER(TRIM(city)) = 'ITAMARANDIBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '265837');

-- EM PROFESSORA GERALDA FIGUEIREDO (LEME DO PRADO)
UPDATE schools SET inep_code = '312681' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA GERALDA FIGUEIREDO' AND UPPER(TRIM(city)) = 'LEME DO PRADO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312681');

-- EM GABRIELA LEITE ARAÚJO (MINAS NOVAS)
UPDATE schools SET inep_code = '278157' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM GABRIELA LEITE ARAÚJO' AND UPPER(TRIM(city)) = 'MINAS NOVAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '278157');

-- EM PREFEITO GERALDO MOREIRA DA COSTA (MONJOLOS)
UPDATE schools SET inep_code = '271021' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PREFEITO GERALDO MOREIRA DA COSTA' AND UPPER(TRIM(city)) = 'MONJOLOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '271021');

-- EM SANTO ANTÔNIO (ARCOS)
UPDATE schools SET inep_code = '253375' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SANTO ANTÔNIO' AND UPPER(TRIM(city)) = 'ARCOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253375');

-- EM VERA LÚCIA PARAÍSO (ARCOS)
UPDATE schools SET inep_code = '244775' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM VERA LÚCIA PARAÍSO' AND UPPER(TRIM(city)) = 'ARCOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '244775');

-- EM YOLANDA AMORIM DE CARVALHO (ARCOS)
UPDATE schools SET inep_code = '226971' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM YOLANDA AMORIM DE CARVALHO' AND UPPER(TRIM(city)) = 'ARCOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '226971');

-- EM PROFESSORA LYGIA VAZ DE OLIVEIRA (CARMÓPOLIS DE MINAS)
UPDATE schools SET inep_code = '227013' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA LYGIA VAZ DE OLIVEIRA' AND UPPER(TRIM(city)) = 'CARMÓPOLIS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '227013');

-- EM DOUTOR WILSON VEADO (CLÁUDIO)
UPDATE schools SET inep_code = '256200' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOUTOR WILSON VEADO' AND UPPER(TRIM(city)) = 'CLÁUDIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '256200');

-- CAIC EM PADRE JOÃO BRUNO (DIVINÓPOLIS)
UPDATE schools SET inep_code = '223930' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CAIC EM PADRE JOÃO BRUNO' AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '223930');

-- EM ANTONIETA FONSECA (DIVINÓPOLIS)
UPDATE schools SET inep_code = '313653' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANTONIETA FONSECA' AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '313653');

-- EM DIONÍSIO JOAQUIM RODRIGUES (DIVINÓPOLIS)
UPDATE schools SET inep_code = '370347' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DIONÍSIO JOAQUIM RODRIGUES' AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '370347');

-- EM DOUTOR SEBASTIÃO GOMES GUIMARÃES (DIVINÓPOLIS)
UPDATE schools SET inep_code = '220060' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOUTOR SEBASTIÃO GOMES GUIMARÃES' AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '220060');

-- EM JOÃO GONTIJO DA FONSECA (DIVINÓPOLIS)
UPDATE schools SET inep_code = '227102' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOÃO GONTIJO DA FONSECA' AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '227102');

-- EM JOÃO SEVERINO DE AZEVEDO (DIVINÓPOLIS)
UPDATE schools SET inep_code = '223891' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOÃO SEVERINO DE AZEVEDO' AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '223891');

-- EM MARIA FONSECA PEÇANHA (DIVINÓPOLIS)
UPDATE schools SET inep_code = '223913' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA FONSECA PEÇANHA' AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '223913');

-- EM PADRE GUARITA (DIVINÓPOLIS)
UPDATE schools SET inep_code = '212733' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PADRE GUARITA' AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '212733');

-- EM PROFESSOR BAHIA (DIVINÓPOLIS)
UPDATE schools SET inep_code = '223921' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR BAHIA' AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '223921');

-- EM PROFESSOR ODILON SANTIAGO (DIVINÓPOLIS)
UPDATE schools SET inep_code = '220051' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR ODILON SANTIAGO' AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '220051');

-- EM SIDNEY JOSÉ DE OLIVEIRA (DIVINÓPOLIS)
UPDATE schools SET inep_code = '223905' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SIDNEY JOSÉ DE OLIVEIRA' AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '223905');

-- EM DONA DORICA (ITAÚNA)
UPDATE schools SET inep_code = '227048' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DONA DORICA' AND UPPER(TRIM(city)) = 'ITAÚNA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '227048');

-- EM SEBASTIÃO LEMOS TORRES (MEDEIROS)
UPDATE schools SET inep_code = '270377' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SEBASTIÃO LEMOS TORRES' AND UPPER(TRIM(city)) = 'MEDEIROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '270377');

-- EM ANTÔNIO AMARAL DE LACERDA - TÕEZINHO BENTO (NOVA SERRANA)
UPDATE schools SET inep_code = '378208' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANTÔNIO AMARAL DE LACERDA - TÕEZINHO BENTO' AND UPPER(TRIM(city)) = 'NOVA SERRANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '378208');

-- EM DIRETORA MARIA DO CARMO FONSECA (NOVA SERRANA)
UPDATE schools SET inep_code = '330361' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DIRETORA MARIA DO CARMO FONSECA' AND UPPER(TRIM(city)) = 'NOVA SERRANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '330361');

-- EM DONA MARIA ROSA SOARES (NOVA SERRANA)
UPDATE schools SET inep_code = '234737' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DONA MARIA ROSA SOARES' AND UPPER(TRIM(city)) = 'NOVA SERRANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '234737');

-- EM FREI AMBRÓSIO (NOVA SERRANA)
UPDATE schools SET inep_code = '310921' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM FREI AMBRÓSIO' AND UPPER(TRIM(city)) = 'NOVA SERRANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310921');

-- EM GERALDA DE ASSIS FREITAS (NOVA SERRANA)
UPDATE schools SET inep_code = '320021' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM GERALDA DE ASSIS FREITAS' AND UPPER(TRIM(city)) = 'NOVA SERRANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '320021');

-- EM JOSÉ AMÉRICO DE LACERDA (NOVA SERRANA)
UPDATE schools SET inep_code = '249564' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ AMÉRICO DE LACERDA' AND UPPER(TRIM(city)) = 'NOVA SERRANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '249564');

-- EM MARIA ALVES DE BRITO LEITE (NOVA SERRANA)
UPDATE schools SET inep_code = '339474' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA ALVES DE BRITO LEITE' AND UPPER(TRIM(city)) = 'NOVA SERRANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '339474');

-- EM PROFESSORA ELIANA FRANCISCA DE FREITAS (NOVA SERRANA)
UPDATE schools SET inep_code = '343765' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA ELIANA FRANCISCA DE FREITAS' AND UPPER(TRIM(city)) = 'NOVA SERRANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '343765');

-- EM WALFRIDO SILVINO DOS MARES GUIA (OLIVEIRA)
UPDATE schools SET inep_code = '327174' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM WALFRIDO SILVINO DOS MARES GUIA' AND UPPER(TRIM(city)) = 'OLIVEIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '327174');

-- EM SILAS SILVA (PEDRA DO INDAIÁ)
UPDATE schools SET inep_code = '271691' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SILAS SILVA' AND UPPER(TRIM(city)) = 'PEDRA DO INDAIÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '271691');

-- EM DEPUTADO JAIME MARTINS (SÃO SEBASTIÃO DO OESTE)
UPDATE schools SET inep_code = '271675' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DEPUTADO JAIME MARTINS' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO OESTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '271675');

-- EM HENRIQUE RODRIGUES DE BARROS (AIMORÉS)
UPDATE schools SET inep_code = '273449' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM HENRIQUE RODRIGUES DE BARROS' AND UPPER(TRIM(city)) = 'AIMORÉS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '273449');

-- EM HONÓRIO VICENTE DE OLIVEIRA (AIMORÉS)
UPDATE schools SET inep_code = '273431' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM HONÓRIO VICENTE DE OLIVEIRA' AND UPPER(TRIM(city)) = 'AIMORÉS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '273431');

-- EM ALIETE RODRIGUES DO CARMO (CONSELHEIRO PENA)
UPDATE schools SET inep_code = '256251' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ALIETE RODRIGUES DO CARMO' AND UPPER(TRIM(city)) = 'CONSELHEIRO PENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '256251');

-- EM CHICO MENDES (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '319287' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CHICO MENDES' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '319287');

-- EM IVO TASSIS (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '302813' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM IVO TASSIS' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '302813');

-- EM OTÁCVIO SOARES FERREIRA (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '360082' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM OTÁCVIO SOARES FERREIRA' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '360082');

-- EM REALINA ADELINA COSTA (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '323616' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM REALINA ADELINA COSTA' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '323616');

-- EM VEREADOR HAMÍLTON TEODORO (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '227153' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM VEREADOR HAMÍLTON TEODORO' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '227153');

-- EM VEREADOR JOÃO DORNELLAS (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '235075' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM VEREADOR JOÃO DORNELLAS' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '235075');

-- EMEIEF DONA LINA MARTELLI (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '363669' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EMEIEF DONA LINA MARTELLI' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '363669');

-- EMEIEF PADRE PEDRO CRISÓLOGO ROSA (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '363545' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EMEIEF PADRE PEDRO CRISÓLOGO ROSA' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '363545');

-- EMEIEF PASTOR FABIANO ALVES (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '363588' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EMEIEF PASTOR FABIANO ALVES' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '363588');

-- EMEIEF PASTOR MARTIN LUTHER KING JR (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '363596' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EMEIEF PASTOR MARTIN LUTHER KING JR' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '363596');

-- EMEIEF PROFESSOR DAMON DE LIMA (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '363600' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EMEIEF PROFESSOR DAMON DE LIMA' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '363600');

-- EMEIEF PROFESSOR DANIEL ALVES AJUDARTE (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '363618' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EMEIEF PROFESSOR DANIEL ALVES AJUDARTE' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '363618');

-- EMEIEF PROFESSORA VIOLETA DIAS ANDRADE (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '363626' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EMEIEF PROFESSORA VIOLETA DIAS ANDRADE' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '363626');

-- EMEIEF WALDEMAR NADIL KRENAK (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '363642' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EMEIEF WALDEMAR NADIL KRENAK' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '363642');

-- EMEIEF ZUMBI DE PALMARES (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '363634' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EMEIEF ZUMBI DE PALMARES' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '363634');

-- ESCOLA MUNICIPAL DE EDUCAÇÃO INFANTIL E ENSINO FUNDAMENTAL PROFESSOR VICTOR VARGAS GLÓRIA (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '363650' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA MUNICIPAL DE EDUCAÇÃO INFANTIL E ENSINO FUNDAMENTAL PROFESSOR VICTOR VARGAS GLÓRIA' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '363650');

-- EM WALDEMIRO BARREL (PERIQUITO)
UPDATE schools SET inep_code = '294063' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM WALDEMIRO BARREL' AND UPPER(TRIM(city)) = 'PERIQUITO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '294063');

-- EM OLÍMPIO ALVES MACHADO (RESPLENDOR)
UPDATE schools SET inep_code = '273414' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM OLÍMPIO ALVES MACHADO' AND UPPER(TRIM(city)) = 'RESPLENDOR' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '273414');

-- EM PREFEITO ANTÔNIO RABELO LEITE (SÃO GERALDO DA PIEDADE)
UPDATE schools SET inep_code = '349674' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PREFEITO ANTÔNIO RABELO LEITE' AND UPPER(TRIM(city)) = 'SÃO GERALDO DA PIEDADE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349674');

-- EM JOÃO INÁCIO DA SILVA (SÃO JOSÉ DA SAFIRA)
UPDATE schools SET inep_code = '316563' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOÃO INÁCIO DA SILVA' AND UPPER(TRIM(city)) = 'SÃO JOSÉ DA SAFIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '316563');

-- EM MUNICIPAL ITELVINA FERREIRA DE SOUZA (FREI LAGONEGRO)
UPDATE schools SET inep_code = '269557' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MUNICIPAL ITELVINA FERREIRA DE SOUZA' AND UPPER(TRIM(city)) = 'FREI LAGONEGRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '269557');

-- EM DONA OTÍLIA VITALINA DE QUEIROZ (PAULISTAS)
UPDATE schools SET inep_code = '263931' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DONA OTÍLIA VITALINA DE QUEIROZ' AND UPPER(TRIM(city)) = 'PAULISTAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '263931');

-- EM JOSÉ PIMENTA DA SILVA (PAULISTAS)
UPDATE schools SET inep_code = '205389' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ PIMENTA DA SILVA' AND UPPER(TRIM(city)) = 'PAULISTAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '205389');

-- EM CÔNEGO JOSÉ COELHO (SENHORA DO PORTO)
UPDATE schools SET inep_code = '265977' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CÔNEGO JOSÉ COELHO' AND UPPER(TRIM(city)) = 'SENHORA DO PORTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '265977');

-- EM MONSENHOR JOSÉ CARLOS DE FARIA (MARIA DA FÉ)
UPDATE schools SET inep_code = '269930' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MONSENHOR JOSÉ CARLOS DE FARIA' AND UPPER(TRIM(city)) = 'MARIA DA FÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '269930');

-- EM PROFESSORA LAÍS PERALTA CARNEIRO (MARIA DA FÉ)
UPDATE schools SET inep_code = '369535' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA LAÍS PERALTA CARNEIRO' AND UPPER(TRIM(city)) = 'MARIA DA FÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369535');

-- EM MARECHAL RONDON (CACHOEIRA DOURADA)
UPDATE schools SET inep_code = '196355' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARECHAL RONDON' AND UPPER(TRIM(city)) = 'CACHOEIRA DOURADA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196355');

-- EM CARLOS PRATES (CENTRALINA)
UPDATE schools SET inep_code = '269409' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CARLOS PRATES' AND UPPER(TRIM(city)) = 'CENTRALINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '269409');

-- EM JOSÉ OLYNTHO FERREIRA (IPIAÇU)
UPDATE schools SET inep_code = '197661' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ OLYNTHO FERREIRA' AND UPPER(TRIM(city)) = 'IPIAÇU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '197661');

-- CIME MUNICIPAL TANCREDO PAULA ALMEIDA (ITUIUTABA)
UPDATE schools SET inep_code = '198269' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CIME MUNICIPAL TANCREDO PAULA ALMEIDA' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '198269');

-- EM ARCHIDAMIRO PARREIRA DE SOUZA (ITUIUTABA)
UPDATE schools SET inep_code = '197742' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ARCHIDAMIRO PARREIRA DE SOUZA' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '197742');

-- EM AURELIANO JOAQUIM DA SILVA (ITUIUTABA)
UPDATE schools SET inep_code = '260011' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM AURELIANO JOAQUIM DA SILVA' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '260011');

-- EM BERNARDO JOSÉ FRANCO (ITUIUTABA)
UPDATE schools SET inep_code = '197971' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM BERNARDO JOSÉ FRANCO' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '197971');

-- EM MACHADO DE ASSIS (ITUIUTABA)
UPDATE schools SET inep_code = '197980' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MACHADO DE ASSIS' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '197980');

-- EM MANOEL ALVES VILELA (ITUIUTABA)
UPDATE schools SET inep_code = '198021' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MANOEL ALVES VILELA' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '198021');

-- EM QUIRINO DE MORAIS (ITUIUTABA)
UPDATE schools SET inep_code = '198161' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM QUIRINO DE MORAIS' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '198161');

-- EM NOSSA SENHORA DAS GRAÇAS (SANTA VITÓRIA)
UPDATE schools SET inep_code = '198714' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM NOSSA SENHORA DAS GRAÇAS' AND UPPER(TRIM(city)) = 'SANTA VITÓRIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '198714');

-- EM SÃO JOSÉ (SANTA VITÓRIA)
UPDATE schools SET inep_code = '196746' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SÃO JOSÉ' AND UPPER(TRIM(city)) = 'SANTA VITÓRIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196746');

-- EM TANCREDO NEVES (SANTA VITÓRIA)
UPDATE schools SET inep_code = '198633' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM TANCREDO NEVES' AND UPPER(TRIM(city)) = 'SANTA VITÓRIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '198633');

-- EM JOSÉ BARBOSA DE OLIVEIRA (CATUTI)
UPDATE schools SET inep_code = '315141' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ BARBOSA DE OLIVEIRA' AND UPPER(TRIM(city)) = 'CATUTI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '315141');

-- EM TACIANO ANTUNES DE SOUZA (GAMELEIRAS)
UPDATE schools SET inep_code = '316601' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM TACIANO ANTUNES DE SOUZA' AND UPPER(TRIM(city)) = 'GAMELEIRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '316601');

-- EM NOVA ESPERANÇA (JAÍBA)
UPDATE schools SET inep_code = '248517' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM NOVA ESPERANÇA' AND UPPER(TRIM(city)) = 'JAÍBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '248517');

-- EM MADRE CÂNDIDA MARIA DE JESUS (JANAÚBA)
UPDATE schools SET inep_code = '347418' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MADRE CÂNDIDA MARIA DE JESUS' AND UPPER(TRIM(city)) = 'JANAÚBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '347418');

-- EM CLEMENTE MENDES DE SOUZA (PORTEIRINHA)
UPDATE schools SET inep_code = '313491' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CLEMENTE MENDES DE SOUZA' AND UPPER(TRIM(city)) = 'PORTEIRINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '313491');

-- EM EDMUNDO DE ALMEIDA ROCHA (RIO PARDO DE MINAS)
UPDATE schools SET inep_code = '218201' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM EDMUNDO DE ALMEIDA ROCHA' AND UPPER(TRIM(city)) = 'RIO PARDO DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218201');

-- EM PROFESSOR GUMERCINDO COSTA (RIO PARDO DE MINAS)
UPDATE schools SET inep_code = '218197' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR GUMERCINDO COSTA' AND UPPER(TRIM(city)) = 'RIO PARDO DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218197');

-- EM SÃO JOAQUIM (SANTO ANTÔNIO DO RETIRO)
UPDATE schools SET inep_code = '259080' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SÃO JOAQUIM' AND UPPER(TRIM(city)) = 'SANTO ANTÔNIO DO RETIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '259080');

-- EM MOACIR FERNANDES CANGUSSU (SERRANÓPOLIS DE MINAS)
UPDATE schools SET inep_code = '317616' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MOACIR FERNANDES CANGUSSU' AND UPPER(TRIM(city)) = 'SERRANÓPOLIS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '317616');

-- EM ANTÔNIO LUIZ DE MORAIS (VERDELÂNDIA)
UPDATE schools SET inep_code = '251291' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANTÔNIO LUIZ DE MORAIS' AND UPPER(TRIM(city)) = 'VERDELÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '251291');

-- EM ONOFRE DE OLIVEIRA NETO (VERDELÂNDIA)
UPDATE schools SET inep_code = '312703' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ONOFRE DE OLIVEIRA NETO' AND UPPER(TRIM(city)) = 'VERDELÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312703');

-- EM DE SUMIDOURO (BONITO DE MINAS)
UPDATE schools SET inep_code = '307793' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DE SUMIDOURO' AND UPPER(TRIM(city)) = 'BONITO DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '307793');

-- EM FRANCISCO BORGES MONTEIRO (BONITO DE MINAS)
UPDATE schools SET inep_code = '207179' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM FRANCISCO BORGES MONTEIRO' AND UPPER(TRIM(city)) = 'BONITO DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '207179');

-- EM DARIO CARNEIRO (CHAPADA GAÚCHA)
UPDATE schools SET inep_code = '248584' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DARIO CARNEIRO' AND UPPER(TRIM(city)) = 'CHAPADA GAÚCHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '248584');

-- EM GETÚLIO INÁCIO DE FARIA (CHAPADA GAÚCHA)
UPDATE schools SET inep_code = '272841' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM GETÚLIO INÁCIO DE FARIA' AND UPPER(TRIM(city)) = 'CHAPADA GAÚCHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '272841');

-- EM SANTO AGOSTINHO (CHAPADA GAÚCHA)
UPDATE schools SET inep_code = '263206' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SANTO AGOSTINHO' AND UPPER(TRIM(city)) = 'CHAPADA GAÚCHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '263206');

-- EM BARREIRO DO BORRACHUDO (CÔNEGO MARINHO)
UPDATE schools SET inep_code = '294829' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM BARREIRO DO BORRACHUDO' AND UPPER(TRIM(city)) = 'CÔNEGO MARINHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '294829');

-- EM JOÃO LOPES CORREA (CÔNEGO MARINHO)
UPDATE schools SET inep_code = '273741' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOÃO LOPES CORREA' AND UPPER(TRIM(city)) = 'CÔNEGO MARINHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '273741');

-- EM SÃO JOSÉ DE MACAÚBAS (CÔNEGO MARINHO)
UPDATE schools SET inep_code = '279447' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SÃO JOSÉ DE MACAÚBAS' AND UPPER(TRIM(city)) = 'CÔNEGO MARINHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '279447');

-- EM VACA PRETA (CÔNEGO MARINHO)
UPDATE schools SET inep_code = '217433' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM VACA PRETA' AND UPPER(TRIM(city)) = 'CÔNEGO MARINHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217433');

-- ESCOLA MUNICIPAL JOSEFINA FRANCISCA DA MOTA (CÔNEGO MARINHO)
UPDATE schools SET inep_code = '370410' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA MUNICIPAL JOSEFINA FRANCISCA DA MOTA' AND UPPER(TRIM(city)) = 'CÔNEGO MARINHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '370410');

-- EM ADÉLIA ANTÔNIA ALMEIDA SEIXAS (ITACARAMBI)
UPDATE schools SET inep_code = '295311' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ADÉLIA ANTÔNIA ALMEIDA SEIXAS' AND UPPER(TRIM(city)) = 'ITACARAMBI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '295311');

-- EM CARMEM MARIA ANDRADE NOGUEIRA (ITACARAMBI)
UPDATE schools SET inep_code = '274585' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CARMEM MARIA ANDRADE NOGUEIRA' AND UPPER(TRIM(city)) = 'ITACARAMBI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '274585');

-- EM OSÓRIO EVANGELISTA DOS SANTOS (ITACARAMBI)
UPDATE schools SET inep_code = '253723' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM OSÓRIO EVANGELISTA DOS SANTOS' AND UPPER(TRIM(city)) = 'ITACARAMBI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253723');

-- CAIC EM JOANA PORTO (JANUÁRIA)
UPDATE schools SET inep_code = '239356' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CAIC EM JOANA PORTO' AND UPPER(TRIM(city)) = 'JANUÁRIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '239356');

-- EM DE ARAÇÁ (JANUÁRIA)
UPDATE schools SET inep_code = '293016' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DE ARAÇÁ' AND UPPER(TRIM(city)) = 'JANUÁRIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '293016');

-- EM DE BARREIRAS (JANUÁRIA)
UPDATE schools SET inep_code = '298646' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DE BARREIRAS' AND UPPER(TRIM(city)) = 'JANUÁRIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '298646');

-- EM DE QUILOMBO (JANUÁRIA)
UPDATE schools SET inep_code = '298662' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DE QUILOMBO' AND UPPER(TRIM(city)) = 'JANUÁRIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '298662');

-- EM DE SÍTIO NOVO (JANUÁRIA)
UPDATE schools SET inep_code = '297917' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DE SÍTIO NOVO' AND UPPER(TRIM(city)) = 'JANUÁRIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '297917');

-- EM QUILOMBOLA GERÔNIMO BORGES DOS SANTOS (JANUÁRIA)
UPDATE schools SET inep_code = '355623' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM QUILOMBOLA GERÔNIMO BORGES DOS SANTOS' AND UPPER(TRIM(city)) = 'JANUÁRIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '355623');

-- EM SANTA RITA (JANUÁRIA)
UPDATE schools SET inep_code = '268615' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SANTA RITA' AND UPPER(TRIM(city)) = 'JANUÁRIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '268615');

-- EM VERÍSSIMO FERNANDES (JANUÁRIA)
UPDATE schools SET inep_code = '217409' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM VERÍSSIMO FERNANDES' AND UPPER(TRIM(city)) = 'JANUÁRIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217409');

-- EM PE RICARDO TRITSCHIER (MANGA)
UPDATE schools SET inep_code = '272370' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PE RICARDO TRITSCHIER' AND UPPER(TRIM(city)) = 'MANGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '272370');

-- EM DE PITARANA (MONTALVÂNIA)
UPDATE schools SET inep_code = '371947' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DE PITARANA' AND UPPER(TRIM(city)) = 'MONTALVÂNIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '371947');

-- EM JOSÉ OLÍMPIO DE SOUZA (MONTALVÂNIA)
UPDATE schools SET inep_code = '234320' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ OLÍMPIO DE SOUZA' AND UPPER(TRIM(city)) = 'MONTALVÂNIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '234320');

-- EM MANOEL FERREIRA DE FARIAS (MONTALVÂNIA)
UPDATE schools SET inep_code = '278840' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MANOEL FERREIRA DE FARIAS' AND UPPER(TRIM(city)) = 'MONTALVÂNIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '278840');

-- EM DO BOM MENINO (SÃO FRANCISCO)
UPDATE schools SET inep_code = '207161' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DO BOM MENINO' AND UPPER(TRIM(city)) = 'SÃO FRANCISCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '207161');

-- EM JOSÉ D'ÁVILA PINTO (SÃO FRANCISCO)
UPDATE schools SET inep_code = '234508' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ D''ÁVILA PINTO' AND UPPER(TRIM(city)) = 'SÃO FRANCISCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '234508');

-- EM PAULO FREIRE (SÃO FRANCISCO)
UPDATE schools SET inep_code = '293113' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PAULO FREIRE' AND UPPER(TRIM(city)) = 'SÃO FRANCISCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '293113');

-- EM SANTA MARTA (SÃO FRANCISCO)
UPDATE schools SET inep_code = '248789' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SANTA MARTA' AND UPPER(TRIM(city)) = 'SÃO FRANCISCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '248789');

-- EM SÃO JUDAS TADEU (SÃO FRANCISCO)
UPDATE schools SET inep_code = '318396' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SÃO JUDAS TADEU' AND UPPER(TRIM(city)) = 'SÃO FRANCISCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '318396');

-- EM ELÓI FERREIRA DA SILVA (URUCUIA)
UPDATE schools SET inep_code = '351156' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ELÓI FERREIRA DA SILVA' AND UPPER(TRIM(city)) = 'URUCUIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '351156');

-- EM IRACY LOPO LISBOA (URUCUIA)
UPDATE schools SET inep_code = '351121' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM IRACY LOPO LISBOA' AND UPPER(TRIM(city)) = 'URUCUIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '351121');

-- EM LUIZ RIBEIRO MENDES (URUCUIA)
UPDATE schools SET inep_code = '261611' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM LUIZ RIBEIRO MENDES' AND UPPER(TRIM(city)) = 'URUCUIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '261611');

-- ESCOLA CÍVICO MILITAR MUNICIPAL PROFESSORA ANA AMÉLIA MACEDO MONTE ALTO (URUCUIA)
UPDATE schools SET inep_code = '377848' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA CÍVICO MILITAR MUNICIPAL PROFESSORA ANA AMÉLIA MACEDO MONTE ALTO' AND UPPER(TRIM(city)) = 'URUCUIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '377848');

-- EM BERTOLINO FERREIRA DE QUEIROZ (VARZELÂNDIA)
UPDATE schools SET inep_code = '322938' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM BERTOLINO FERREIRA DE QUEIROZ' AND UPPER(TRIM(city)) = 'VARZELÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322938');

-- EM DOUTOR DILSON DE QUADROS GODINHO (VARZELÂNDIA)
UPDATE schools SET inep_code = '278203' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOUTOR DILSON DE QUADROS GODINHO' AND UPPER(TRIM(city)) = 'VARZELÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '278203');

-- EM ZARA DE PAULA (ARANTINA)
UPDATE schools SET inep_code = '273082' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ZARA DE PAULA' AND UPPER(TRIM(city)) = 'ARANTINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '273082');

-- EM CORONEL JOAQUIM JOSÉ DE SOUZA (BICAS)
UPDATE schools SET inep_code = '269883' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CORONEL JOAQUIM JOSÉ DE SOUZA' AND UPPER(TRIM(city)) = 'BICAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '269883');

-- EM SÃO SEBASTIÃO (BOM JARDIM DE MINAS)
UPDATE schools SET inep_code = '223948' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SÃO SEBASTIÃO' AND UPPER(TRIM(city)) = 'BOM JARDIM DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '223948');

-- EM PREFEITO NILTON BRETAS (CHÁCARA)
UPDATE schools SET inep_code = '270628' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PREFEITO NILTON BRETAS' AND UPPER(TRIM(city)) = 'CHÁCARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '270628');

-- EM ANTÔNIO FAUSTINO DA SILVA (JUIZ DE FORA)
UPDATE schools SET inep_code = '235261' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANTÔNIO FAUSTINO DA SILVA' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '235261');

-- EM ARLETE BASTOS MAGALHÃES (JUIZ DE FORA)
UPDATE schools SET inep_code = '235270' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ARLETE BASTOS MAGALHÃES' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '235270');

-- EM BELA AURORA (JUIZ DE FORA)
UPDATE schools SET inep_code = '227498' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM BELA AURORA' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '227498');

-- EM BELMIRA DUARTE DIAS (JUIZ DE FORA)
UPDATE schools SET inep_code = '235288' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM BELMIRA DUARTE DIAS' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '235288');

-- EM CARLOS DRUMOND DE ANDRADE (JUIZ DE FORA)
UPDATE schools SET inep_code = '218006' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CARLOS DRUMOND DE ANDRADE' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218006');

-- EM CORONEL EMÍLIO ESTEVES DOS REIS (JUIZ DE FORA)
UPDATE schools SET inep_code = '352110' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CORONEL EMÍLIO ESTEVES DOS REIS' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '352110');

-- EM DE SANTA CÂNDIDA (JUIZ DE FORA)
UPDATE schools SET inep_code = '218014' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DE SANTA CÂNDIDA' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218014');

-- EM DOUTOR CÁSSIO VIEIRA MARQUES (JUIZ DE FORA)
UPDATE schools SET inep_code = '235253' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOUTOR CÁSSIO VIEIRA MARQUES' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '235253');

-- EM ENGENHEIRO DOUTOR ANDRÉ REBOUÇAS (JUIZ DE FORA)
UPDATE schools SET inep_code = '217981' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ENGENHEIRO DOUTOR ANDRÉ REBOUÇAS' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217981');

-- EM GABRIEL GONÇALVES DA SILVA (JUIZ DE FORA)
UPDATE schools SET inep_code = '227480' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM GABRIEL GONÇALVES DA SILVA' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '227480');

-- EM GEORGE RODENBACH (JUIZ DE FORA)
UPDATE schools SET inep_code = '233099' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM GEORGE RODENBACH' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '233099');

-- EM HENRIQUE JOSÉ DE SOUZA (JUIZ DE FORA)
UPDATE schools SET inep_code = '217999' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM HENRIQUE JOSÉ DE SOUZA' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217999');

-- EM JARDIM DE ALÁ (JUIZ DE FORA)
UPDATE schools SET inep_code = '275204' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JARDIM DE ALÁ' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '275204');

-- EM JOÃO EVANGELISTA DE ASSIS (JUIZ DE FORA)
UPDATE schools SET inep_code = '227501' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOÃO EVANGELISTA DE ASSIS' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '227501');

-- EM JOVITA MONTREUIL BRANDÃO (JUIZ DE FORA)
UPDATE schools SET inep_code = '362387' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOVITA MONTREUIL BRANDÃO' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '362387');

-- EM MARIA CATARINA BARBOSA (JUIZ DE FORA)
UPDATE schools SET inep_code = '220698' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA CATARINA BARBOSA' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '220698');

-- EM PROFESORA EUNICE ALVES VIEIRA (JUIZ DE FORA)
UPDATE schools SET inep_code = '296406' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESORA EUNICE ALVES VIEIRA' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '296406');

-- EM PROFESSOR AUGUSTO GOTARDELO (JUIZ DE FORA)
UPDATE schools SET inep_code = '327352' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR AUGUSTO GOTARDELO' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '327352');

-- EM PROFESSOR HELYON DE OLIVEIRA (JUIZ DE FORA)
UPDATE schools SET inep_code = '260134' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR HELYON DE OLIVEIRA' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '260134');

-- EM PROFESSOR OSWALDO VELLOSO (JUIZ DE FORA)
UPDATE schools SET inep_code = '295442' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR OSWALDO VELLOSO' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '295442');

-- EM PROFESSORA ÁUREA NARDELLI (JUIZ DE FORA)
UPDATE schools SET inep_code = '307564' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA ÁUREA NARDELLI' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '307564');

-- EM PROFESSORA MARLENE BARROS (JUIZ DE FORA)
UPDATE schools SET inep_code = '235296' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA MARLENE BARROS' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '235296');

-- EM PROFESSORA NÚBIA PEREIRA DE MAGALHÃES GOMES - CAIC (JUIZ DE FORA)
UPDATE schools SET inep_code = '260126' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA NÚBIA PEREIRA DE MAGALHÃES GOMES - CAIC' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '260126');

-- EM PROFESSORA THEREZA FALCI (JUIZ DE FORA)
UPDATE schools SET inep_code = '307556' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA THEREZA FALCI' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '307556');

-- EM QUILOMBO DOS PALMARES (JUIZ DE FORA)
UPDATE schools SET inep_code = '218031' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM QUILOMBO DOS PALMARES' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218031');

-- EM ROCHA POMBO (JUIZ DE FORA)
UPDATE schools SET inep_code = '267317' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ROCHA POMBO' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '267317');

-- EM SANTA CECÍLIA (JUIZ DE FORA)
UPDATE schools SET inep_code = '227510' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SANTA CECÍLIA' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '227510');

-- EM SANTOS DUMONT (JUIZ DE FORA)
UPDATE schools SET inep_code = '223972' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SANTOS DUMONT' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '223972');

-- EM SÃO GERALDO (JUIZ DE FORA)
UPDATE schools SET inep_code = '266434' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SÃO GERALDO' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '266434');

-- EM VEREADOR RAYMUNDO HARGREAVES (JUIZ DE FORA)
UPDATE schools SET inep_code = '218022' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM VEREADOR RAYMUNDO HARGREAVES' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218022');

-- EM ELVIRA MAGDALENA MANNARINO (MAR DE ESPANHA)
UPDATE schools SET inep_code = '272833' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ELVIRA MAGDALENA MANNARINO' AND UPPER(TRIM(city)) = 'MAR DE ESPANHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '272833');