-- EM EÇA DE QUEIROZ (BURITIS)
UPDATE schools SET inep_code = '110353' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM EÇA DE QUEIROZ' AND UPPER(TRIM(city)) = 'BURITIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '110353');

-- EM FRANCISCO FERNANDES PITANGUI (BURITIS)
UPDATE schools SET inep_code = '110418' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM FRANCISCO FERNANDES PITANGUI' AND UPPER(TRIM(city)) = 'BURITIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '110418');

-- EM JOÃO FARIAS PINHO (BURITIS)
UPDATE schools SET inep_code = '110744' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOÃO FARIAS PINHO' AND UPPER(TRIM(city)) = 'BURITIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '110744');

-- EM JOSÉ MARIA DE ALKIMIN (BURITIS)
UPDATE schools SET inep_code = '110493' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ MARIA DE ALKIMIN' AND UPPER(TRIM(city)) = 'BURITIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '110493');

-- EM OLEGÁRIO BATISTA DA SILVA (BURITIS)
UPDATE schools SET inep_code = '110710' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM OLEGÁRIO BATISTA DA SILVA' AND UPPER(TRIM(city)) = 'BURITIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '110710');

-- EM PHILOMENA CAMPOS LOPES (BURITIS)
UPDATE schools SET inep_code = '366790' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PHILOMENA CAMPOS LOPES' AND UPPER(TRIM(city)) = 'BURITIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '366790');

-- EM PROFESSOR ANATÓLIO (BURITIS)
UPDATE schools SET inep_code = '110396' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR ANATÓLIO' AND UPPER(TRIM(city)) = 'BURITIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '110396');

-- EM SANTA LUZIA (BURITIS)
UPDATE schools SET inep_code = '108448' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SANTA LUZIA' AND UPPER(TRIM(city)) = 'BURITIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108448');

-- EM SANTA MARTA (BURITIS)
UPDATE schools SET inep_code = '110914' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SANTA MARTA' AND UPPER(TRIM(city)) = 'BURITIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '110914');

-- EM SANTA TEÓFILA (BURITIS)
UPDATE schools SET inep_code = '110931' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SANTA TEÓFILA' AND UPPER(TRIM(city)) = 'BURITIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '110931');

-- EM JOAQUIM DE MENDONÇA (CABECEIRA GRANDE)
UPDATE schools SET inep_code = '113875' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOAQUIM DE MENDONÇA' AND UPPER(TRIM(city)) = 'CABECEIRA GRANDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '113875');

-- EM MARGARIDA GOMES FERREIRA (CABECEIRA GRANDE)
UPDATE schools SET inep_code = '367044' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARGARIDA GOMES FERREIRA' AND UPPER(TRIM(city)) = 'CABECEIRA GRANDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '367044');

-- EM PROFA HOZANA (CABECEIRA GRANDE)
UPDATE schools SET inep_code = '312185' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFA HOZANA' AND UPPER(TRIM(city)) = 'CABECEIRA GRANDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312185');

-- EM STO ANTÔNIO (DOM BOSCO)
UPDATE schools SET inep_code = '108324' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM STO ANTÔNIO' AND UPPER(TRIM(city)) = 'DOM BOSCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108324');

-- EM LÁZARO XAVIER PIRES (FORMOSO)
UPDATE schools SET inep_code = '111112' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM LÁZARO XAVIER PIRES' AND UPPER(TRIM(city)) = 'FORMOSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '111112');

-- EM STO ANTÔNIO (FORMOSO)
UPDATE schools SET inep_code = '108472' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM STO ANTÔNIO' AND UPPER(TRIM(city)) = 'FORMOSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108472');

-- EM ADÉLIA RODRIGUES MARQUES (UNAÍ)
UPDATE schools SET inep_code = '112909' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ADÉLIA RODRIGUES MARQUES' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '112909');

-- EM DR ISRAEL PINHEIRO (UNAÍ)
UPDATE schools SET inep_code = '224006' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DR ISRAEL PINHEIRO' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '224006');

-- EM EUCLIDES DA CUNHA (UNAÍ)
UPDATE schools SET inep_code = '113557' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM EUCLIDES DA CUNHA' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '113557');

-- EM EVA MARIA VIEIRA (UNAÍ)
UPDATE schools SET inep_code = '113964' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM EVA MARIA VIEIRA' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '113964');

-- EM N SRA DE FÁTIMA (UNAÍ)
UPDATE schools SET inep_code = '113689' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM N SRA DE FÁTIMA' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '113689');

-- EM PE JOSÉ DE ANCHIETA (UNAÍ)
UPDATE schools SET inep_code = '324531' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PE JOSÉ DE ANCHIETA' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '324531');

-- EM PROFA GLÓRIA MOREIRA (UNAÍ)
UPDATE schools SET inep_code = '292141' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFA GLÓRIA MOREIRA' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '292141');

-- EM PROFA JOVELMIRA J VASCONCELOS (UNAÍ)
UPDATE schools SET inep_code = '312274' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFA JOVELMIRA J VASCONCELOS' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312274');

-- EM STO ANTÔNIO (UNAÍ)
UPDATE schools SET inep_code = '114367' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM STO ANTÔNIO' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '114367');

-- EM TEODORO CAMPOS (UNAÍ)
UPDATE schools SET inep_code = '109126' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM TEODORO CAMPOS' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '109126');

-- EM TEREZINHA REZENDE (UNAÍ)
UPDATE schools SET inep_code = '114235' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM TEREZINHA REZENDE' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '114235');

-- EM TOMAZ PINTO DA SILVA (UNAÍ)
UPDATE schools SET inep_code = '113441' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM TOMAZ PINTO DA SILVA' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '113441');

-- EM FLORIANO PEIXOTO (URUANA DE MINAS)
UPDATE schools SET inep_code = '114111' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM FLORIANO PEIXOTO' AND UPPER(TRIM(city)) = 'URUANA DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '114111');

-- EM GUSTAVO CAPANEMA (URUANA DE MINAS)
UPDATE schools SET inep_code = '114197' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM GUSTAVO CAPANEMA' AND UPPER(TRIM(city)) = 'URUANA DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '114197');

-- EM ABRÃO ADOLPHO ENGEL (ALFENAS)
UPDATE schools SET inep_code = '170917' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ABRÃO ADOLPHO ENGEL' AND UPPER(TRIM(city)) = 'ALFENAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170917');

-- EM ANTÔNIO JOAQUIM VIEIRA (ALFENAS)
UPDATE schools SET inep_code = '170747' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANTÔNIO JOAQUIM VIEIRA' AND UPPER(TRIM(city)) = 'ALFENAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170747');

-- EM DOUTOR FAUSTO MONTEIRO (ALFENAS)
UPDATE schools SET inep_code = '170801' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOUTOR FAUSTO MONTEIRO' AND UPPER(TRIM(city)) = 'ALFENAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170801');

-- EM ORLANDO PAULINO DA COSTA (ALFENAS)
UPDATE schools SET inep_code = '175323' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ORLANDO PAULINO DA COSTA' AND UPPER(TRIM(city)) = 'ALFENAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '175323');

-- EM PRESIDENTE TANCREDO NEVES (ALFENAS)
UPDATE schools SET inep_code = '170909' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PRESIDENTE TANCREDO NEVES' AND UPPER(TRIM(city)) = 'ALFENAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170909');

-- EM DA FAZENDA ÁGUAS VERDES (BOA ESPERANÇA)
UPDATE schools SET inep_code = '171166' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DA FAZENDA ÁGUAS VERDES' AND UPPER(TRIM(city)) = 'BOA ESPERANÇA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '171166');

-- EM DE BARRO PRETO (BOA ESPERANÇA)
UPDATE schools SET inep_code = '171131' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DE BARRO PRETO' AND UPPER(TRIM(city)) = 'BOA ESPERANÇA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '171131');

-- EM JOÃO BARBALHO (CAMPOS GERAIS)
UPDATE schools SET inep_code = '171654' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOÃO BARBALHO' AND UPPER(TRIM(city)) = 'CAMPOS GERAIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '171654');

-- EM RURAL JOÃO CÂNDIDO DE FARIA (CAMPOS GERAIS)
UPDATE schools SET inep_code = '176354' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM RURAL JOÃO CÂNDIDO DE FARIA' AND UPPER(TRIM(city)) = 'CAMPOS GERAIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '176354');

-- EM MARIA CAPRONI DE OLIVEIRA (CARVALHÓPOLIS)
UPDATE schools SET inep_code = '269719' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA CAPRONI DE OLIVEIRA' AND UPPER(TRIM(city)) = 'CARVALHÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '269719');

-- EM ASTOLFO MOREIRA DE CARVALHO (ELÓI MENDES)
UPDATE schools SET inep_code = '249408' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ASTOLFO MOREIRA DE CARVALHO' AND UPPER(TRIM(city)) = 'ELÓI MENDES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '249408');

-- EM DA FAZENDA SANTA CRUZ (ELÓI MENDES)
UPDATE schools SET inep_code = '172545' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DA FAZENDA SANTA CRUZ' AND UPPER(TRIM(city)) = 'ELÓI MENDES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '172545');

-- EM MARIA DO CARMO MENDES (ELÓI MENDES)
UPDATE schools SET inep_code = '224685' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA DO CARMO MENDES' AND UPPER(TRIM(city)) = 'ELÓI MENDES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '224685');

-- EM MARTA MARTINS MACHADO (ELÓI MENDES)
UPDATE schools SET inep_code = '224693' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARTA MARTINS MACHADO' AND UPPER(TRIM(city)) = 'ELÓI MENDES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '224693');

-- EM OSCAR ARAÚJO (ELÓI MENDES)
UPDATE schools SET inep_code = '176940' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM OSCAR ARAÚJO' AND UPPER(TRIM(city)) = 'ELÓI MENDES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '176940');

-- EM PROFA JÚLIA CAMÕES VIEITO (ELÓI MENDES)
UPDATE schools SET inep_code = '172596' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFA JÚLIA CAMÕES VIEITO' AND UPPER(TRIM(city)) = 'ELÓI MENDES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '172596');

-- EM DE APARECIDA DO SUL (GUAPÉ)
UPDATE schools SET inep_code = '172685' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DE APARECIDA DO SUL' AND UPPER(TRIM(city)) = 'GUAPÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '172685');

-- EM DEPUTADO JOAQUIM DE MELO FREIRE (GUAPÉ)
UPDATE schools SET inep_code = '177083' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DEPUTADO JOAQUIM DE MELO FREIRE' AND UPPER(TRIM(city)) = 'GUAPÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '177083');

-- EM PROF ISMAEL SILVA (ILICÍNEA)
UPDATE schools SET inep_code = '172839' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROF ISMAEL SILVA' AND UPPER(TRIM(city)) = 'ILICÍNEA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '172839');

-- EM PAULO SINÉSIO BELATO (MONSENHOR PAULO)
UPDATE schools SET inep_code = '217735' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PAULO SINÉSIO BELATO' AND UPPER(TRIM(city)) = 'MONSENHOR PAULO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217735');

-- EM DE GUAIPAVA (PARAGUAÇU)
UPDATE schools SET inep_code = '173657' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DE GUAIPAVA' AND UPPER(TRIM(city)) = 'PARAGUAÇU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '173657');

-- EM MARIA ANTONIETA ALVARENGA (PARAGUAÇU)
UPDATE schools SET inep_code = '234630' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA ANTONIETA ALVARENGA' AND UPPER(TRIM(city)) = 'PARAGUAÇU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '234630');

-- EM BENTO GONÇALVES FILHO (SÃO GONÇALO DO SAPUCAÍ)
UPDATE schools SET inep_code = '178845' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM BENTO GONÇALVES FILHO' AND UPPER(TRIM(city)) = 'SÃO GONÇALO DO SAPUCAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '178845');

-- EM DE FERREIRAS (SÃO GONÇALO DO SAPUCAÍ)
UPDATE schools SET inep_code = '377473' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DE FERREIRAS' AND UPPER(TRIM(city)) = 'SÃO GONÇALO DO SAPUCAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '377473');

-- CAIC EM PROFA CÂNDIDA JUNQUEIRA (TRÊS CORAÇÕES)
UPDATE schools SET inep_code = '254746' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CAIC EM PROFA CÂNDIDA JUNQUEIRA' AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '254746');

-- EM CAPITÃO MORBELLO VENDRAMINI (TRÊS CORAÇÕES)
UPDATE schools SET inep_code = '346888' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CAPITÃO MORBELLO VENDRAMINI' AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346888');

-- EM DONA MARIA LAURA (TRÊS CORAÇÕES)
UPDATE schools SET inep_code = '262099' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DONA MARIA LAURA' AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '262099');

-- EM JOSÉ JOAQUIM ALVES PEREIRA (TRÊS CORAÇÕES)
UPDATE schools SET inep_code = '179485' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ JOAQUIM ALVES PEREIRA' AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '179485');

-- EM PREF CELSO BANDA (TRÊS CORAÇÕES)
UPDATE schools SET inep_code = '234958' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PREF CELSO BANDA' AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '234958');

-- EM PROFA MARIA EVANI GOMES TELES (TRÊS CORAÇÕES)
UPDATE schools SET inep_code = '346950' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFA MARIA EVANI GOMES TELES' AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346950');

-- EM PROFESSORA HENRIQUETA GOMES (TRÊS CORAÇÕES)
UPDATE schools SET inep_code = '254738' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA HENRIQUETA GOMES' AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '254738');

-- EM PROFESSORA ONEIDA JUNQUEIRA (TRÊS CORAÇÕES)
UPDATE schools SET inep_code = '179353' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA ONEIDA JUNQUEIRA' AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '179353');

-- EM RIO DO PEIXE II (TRÊS CORAÇÕES)
UPDATE schools SET inep_code = '179434' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM RIO DO PEIXE II' AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '179434');

-- EM ROTARY (TRÊS CORAÇÕES)
UPDATE schools SET inep_code = '179451' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ROTARY' AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '179451');

-- EM SAGRADO CORAÇÃO DE JESUS (TRÊS CORAÇÕES)
UPDATE schools SET inep_code = '179515' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SAGRADO CORAÇÃO DE JESUS' AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '179515');

-- EM ZILAH REZENDE PINTO (TRÊS CORAÇÕES)
UPDATE schools SET inep_code = '174505' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ZILAH REZENDE PINTO' AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174505');

-- EM JOSÉ VIEIRA MENDONÇA (TRÊS PONTAS)
UPDATE schools SET inep_code = '222445' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ VIEIRA MENDONÇA' AND UPPER(TRIM(city)) = 'TRÊS PONTAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '222445');

-- EM PROFESSOR JOÃO DE ABREU SALGADO (TRÊS PONTAS)
UPDATE schools SET inep_code = '174807' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR JOÃO DE ABREU SALGADO' AND UPPER(TRIM(city)) = 'TRÊS PONTAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174807');

-- EM CLAUDIO FIGUEIREDO NOGUEIRA (VARGINHA)
UPDATE schools SET inep_code = '348457' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CLAUDIO FIGUEIREDO NOGUEIRA' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '348457');

-- EM DOMINGOS RIBEIRO DE REZENDE (VARGINHA)
UPDATE schools SET inep_code = '175021' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOMINGOS RIBEIRO DE REZENDE' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '175021');

-- EM DR JACY DE FIGUEIREDO (VARGINHA)
UPDATE schools SET inep_code = '234672' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DR JACY DE FIGUEIREDO' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '234672');

-- EM JOSÉ AUGUSTO PAIVA (VARGINHA)
UPDATE schools SET inep_code = '179914' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ AUGUSTO PAIVA' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '179914');

-- EM JOSÉ CAMILO TAVARES (VARGINHA)
UPDATE schools SET inep_code = '179931' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ CAMILO TAVARES' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '179931');

-- EM MATHEUS TAVARES (VARGINHA)
UPDATE schools SET inep_code = '180017' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MATHEUS TAVARES' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180017');

-- EM PROFESSORA HELENA REIS (VARGINHA)
UPDATE schools SET inep_code = '251160' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA HELENA REIS' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '251160');

-- EM PROFESSORA MARIA APARECIDA ABREU (VARGINHA)
UPDATE schools SET inep_code = '306975' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA MARIA APARECIDA ABREU' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '306975');

-- EM SÃO JOSÉ (VARGINHA)
UPDATE schools SET inep_code = '180092' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SÃO JOSÉ' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180092');

-- CENTRO EDUCACIONAL JOÃO E MARIA (ALMENARA)
UPDATE schools SET inep_code = '353965' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL JOÃO E MARIA' AND UPPER(TRIM(city)) = 'ALMENARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '353965');

-- COLÉGIO COMUNITÁRIO DOUTOR FERNANDO MAGALHÃES (ALMENARA)
UPDATE schools SET inep_code = '247731' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO COMUNITÁRIO DOUTOR FERNANDO MAGALHÃES' AND UPPER(TRIM(city)) = 'ALMENARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '247731');

-- COLÉGIO PIAGET ALMENARA (ALMENARA)
UPDATE schools SET inep_code = '299146' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PIAGET ALMENARA' AND UPPER(TRIM(city)) = 'ALMENARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '299146');

-- INSTITUTO EDUCACIONAL JOÃO E MARIA (JACINTO)
UPDATE schools SET inep_code = '351555' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL JOÃO E MARIA' AND UPPER(TRIM(city)) = 'JACINTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '351555');

-- CENTRO EDUCACIONAL MEU CAMINHO (JEQUITINHONHA)
UPDATE schools SET inep_code = '297747' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL MEU CAMINHO' AND UPPER(TRIM(city)) = 'JEQUITINHONHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '297747');

-- COLÉGIO PIRÂMIDE (JEQUITINHONHA)
UPDATE schools SET inep_code = '278751' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PIRÂMIDE' AND UPPER(TRIM(city)) = 'JEQUITINHONHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '278751');

-- ESCOLA FAMÍLIA AGRÍCOLA RENASCER (JEQUITINHONHA)
UPDATE schools SET inep_code = '366200' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA FAMÍLIA AGRÍCOLA RENASCER' AND UPPER(TRIM(city)) = 'JEQUITINHONHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '366200');

-- INSTITUTO EDUCACIONAL CONHECER CONSTRUIR E VIVER (JOAÍMA)
UPDATE schools SET inep_code = '279412' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL CONHECER CONSTRUIR E VIVER' AND UPPER(TRIM(city)) = 'JOAÍMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '279412');

-- CENTRO EDUCACIONAL UNIVERSO - CEU (PEDRA AZUL)
UPDATE schools SET inep_code = '340405' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL UNIVERSO - CEU' AND UPPER(TRIM(city)) = 'PEDRA AZUL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '340405');

-- INSTITUTO TÉCNICO EDUCACIONAL POLIVALENTE DE PEDRA AZUL-ITEP (PEDRA AZUL)
UPDATE schools SET inep_code = '329096' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO TÉCNICO EDUCACIONAL POLIVALENTE DE PEDRA AZUL-ITEP' AND UPPER(TRIM(city)) = 'PEDRA AZUL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '329096');

-- COLÉGIO NAZARETH (ARAÇUAÍ)
UPDATE schools SET inep_code = '157864' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO NAZARETH' AND UPPER(TRIM(city)) = 'ARAÇUAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '157864');

-- ESCOLA FAMÍLIA AGROECOLÓGICA DE ARAÇUAÍ (ARAÇUAÍ)
UPDATE schools SET inep_code = '343323' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA FAMÍLIA AGROECOLÓGICA DE ARAÇUAÍ' AND UPPER(TRIM(city)) = 'ARAÇUAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '343323');

-- INSTITUTO EDUCACIONAL ANTÔNIO COSENZA LEITE (ARAÇUAÍ)
UPDATE schools SET inep_code = '279943' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL ANTÔNIO COSENZA LEITE' AND UPPER(TRIM(city)) = 'ARAÇUAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '279943');

-- ITEP - INSTITUTO TÉCNICO EDUCACIONAL POLIVALENTE DE ARAÇUAÍ (ARAÇUAÍ)
UPDATE schools SET inep_code = '342106' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ITEP - INSTITUTO TÉCNICO EDUCACIONAL POLIVALENTE DE ARAÇUAÍ' AND UPPER(TRIM(city)) = 'ARAÇUAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342106');

-- ESCOLA FAMÍLIA AGRÍCOLA VIDA COMUNITÁRIA (COMERCINHO)
UPDATE schools SET inep_code = '321265' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA FAMÍLIA AGRÍCOLA VIDA COMUNITÁRIA' AND UPPER(TRIM(city)) = 'COMERCINHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '321265');

-- CENTRO EDUCACIONAL CRESCER FELIZ LTDA - ME (ITAOBIM)
UPDATE schools SET inep_code = '361240' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL CRESCER FELIZ LTDA - ME' AND UPPER(TRIM(city)) = 'ITAOBIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '361240');

-- ESCOLA FAMÍLIA AGRÍCOLA BONTEMPO (ITAOBIM)
UPDATE schools SET inep_code = '313793' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA FAMÍLIA AGRÍCOLA BONTEMPO' AND UPPER(TRIM(city)) = 'ITAOBIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '313793');

-- ITEP - INSTITUTO TÉCNICO EDUCACIONAL POLIVALENTE DE ITAOBIM (ITAOBIM)
UPDATE schools SET inep_code = '363120' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ITEP - INSTITUTO TÉCNICO EDUCACIONAL POLIVALENTE DE ITAOBIM' AND UPPER(TRIM(city)) = 'ITAOBIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '363120');

-- ESCOLA COMUNITÁRIA DA FAMÍLIA AGRÍCOLA JACARÉ (ITINGA)
UPDATE schools SET inep_code = '260401' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA COMUNITÁRIA DA FAMÍLIA AGRÍCOLA JACARÉ' AND UPPER(TRIM(city)) = 'ITINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '260401');

-- ITEP - INSTITUTO TÉCNICO EDUCACIONAL POLIVALENTE (MEDINA)
UPDATE schools SET inep_code = '379972' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ITEP - INSTITUTO TÉCNICO EDUCACIONAL POLIVALENTE' AND UPPER(TRIM(city)) = 'MEDINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '379972');

-- CENTRO EDUCACIONAL EQUILÍBRIO SALINAS (SALINAS)
UPDATE schools SET inep_code = '357073' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL EQUILÍBRIO SALINAS' AND UPPER(TRIM(city)) = 'SALINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '357073');

-- COLÉGIO PRESBITERIANO DE SALINAS (SALINAS)
UPDATE schools SET inep_code = '230456' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PRESBITERIANO DE SALINAS' AND UPPER(TRIM(city)) = 'SALINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '230456');

-- INSTITUTO EDUCACIONAL NOSSA SENHORA APARECIDA-IENSA (SALINAS)
UPDATE schools SET inep_code = '277509' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL NOSSA SENHORA APARECIDA-IENSA' AND UPPER(TRIM(city)) = 'SALINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '277509');

-- CENTRO EDUCACIONAL BELIZA CORRÊA (TAIOBEIRAS)
UPDATE schools SET inep_code = '280879' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL BELIZA CORRÊA' AND UPPER(TRIM(city)) = 'TAIOBEIRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '280879');

-- CESP - CENTRO EDUCACIONAL SILVEIRA E PINHEIRO (TAIOBEIRAS)
UPDATE schools SET inep_code = '356158' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESP - CENTRO EDUCACIONAL SILVEIRA E PINHEIRO' AND UPPER(TRIM(city)) = 'TAIOBEIRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '356158');

-- COLÉGIO PRESBITERIANO DE TAIOBEIRAS (TAIOBEIRAS)
UPDATE schools SET inep_code = '325309' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PRESBITERIANO DE TAIOBEIRAS' AND UPPER(TRIM(city)) = 'TAIOBEIRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '325309');

-- ESCOLA FAMÍLIA AGRÍCOLA NOVA ESPERANÇA (TAIOBEIRAS)
UPDATE schools SET inep_code = '352829' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA FAMÍLIA AGRÍCOLA NOVA ESPERANÇA' AND UPPER(TRIM(city)) = 'TAIOBEIRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '352829');

-- ESCOLA FAMÍLIA AGRÍCOLA (VIRGEM DA LAPA)
UPDATE schools SET inep_code = '237850' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA FAMÍLIA AGRÍCOLA' AND UPPER(TRIM(city)) = 'VIRGEM DA LAPA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '237850');

-- CENTRO TÉCNICO PROFISSIONAL UNIPAC (ANTÔNIO CARLOS)
UPDATE schools SET inep_code = '379840' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO TÉCNICO PROFISSIONAL UNIPAC' AND UPPER(TRIM(city)) = 'ANTÔNIO CARLOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '379840');

-- APRENDIZ COLÉGIO E CURSOS TÉCNICOS (BARBACENA)
UPDATE schools SET inep_code = '324850' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'APRENDIZ COLÉGIO E CURSOS TÉCNICOS' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '324850');

-- CECON BARBACENA (BARBACENA)
UPDATE schools SET inep_code = '350230' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CECON BARBACENA' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '350230');

-- CENTRO EDUCACIONAL APRENDIZ UNIDADE II (BARBACENA)
UPDATE schools SET inep_code = '337331' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL APRENDIZ UNIDADE II' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '337331');

-- CENTRO EDUCACIONAL DESAFIO (BARBACENA)
UPDATE schools SET inep_code = '376850' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL DESAFIO' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '376850');

-- CENTRO FORMAÇÃO PROFISSIONAL DE BARBACENA - SENAI (BARBACENA)
UPDATE schools SET inep_code = '280003' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO FORMAÇÃO PROFISSIONAL DE BARBACENA - SENAI' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '280003');

-- CENTRO TÉCNICO PROFISSIONAL DE BARBACENA (BARBACENA)
UPDATE schools SET inep_code = '367281' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO TÉCNICO PROFISSIONAL DE BARBACENA' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '367281');

-- COLÉGIO APLICAÇÃO (BARBACENA)
UPDATE schools SET inep_code = '371769' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO APLICAÇÃO' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '371769');

-- COLÉGIO ARCA (BARBACENA)
UPDATE schools SET inep_code = '293172' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ARCA' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '293172');

-- COLÉGIO DESAFIO DE BARBACENA (BARBACENA)
UPDATE schools SET inep_code = '344834' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DESAFIO DE BARBACENA' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '344834');

-- COLÉGIO POLITÉCNICO (BARBACENA)
UPDATE schools SET inep_code = '364142' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO POLITÉCNICO' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '364142');

-- COLÉGIO POLITÉCNICO BARBACENA (BARBACENA)
UPDATE schools SET inep_code = '358487' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO POLITÉCNICO BARBACENA' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '358487');

-- COLÉGIO SÃO FRANCISCO DE ASSIS (BARBACENA)
UPDATE schools SET inep_code = '368032' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SÃO FRANCISCO DE ASSIS' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368032');

-- COLÉGIO SOBERANA (BARBACENA)
UPDATE schools SET inep_code = '377600' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SOBERANA' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '377600');

-- DESAFIO PRIMEIRO PASSO (BARBACENA)
UPDATE schools SET inep_code = '361410' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'DESAFIO PRIMEIRO PASSO' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '361410');

-- ESCOLA NETWARE (BARBACENA)
UPDATE schools SET inep_code = '363731' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA NETWARE' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '363731');

-- ESCOLA SESI OSCAR MAGALHÃES FERREIRA (BARBACENA)
UPDATE schools SET inep_code = '304875' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SESI OSCAR MAGALHÃES FERREIRA' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '304875');

-- ESCOLA SESI OSCAR MAGALHÃES FERREIRA - UNIDADE II (BARBACENA)
UPDATE schools SET inep_code = '379794' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SESI OSCAR MAGALHÃES FERREIRA - UNIDADE II' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '379794');

-- IMPPACTO CURSOS PROFISSIONALIZANTES (BARBACENA)
UPDATE schools SET inep_code = '339580' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'IMPPACTO CURSOS PROFISSIONALIZANTES' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '339580');

-- INSTITUTO APRENDIZ SOLIDÁRIO (BARBACENA)
UPDATE schools SET inep_code = '305120' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO APRENDIZ SOLIDÁRIO' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305120');

-- INSTITUTO PREMIUM (BARBACENA)
UPDATE schools SET inep_code = '367176' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO PREMIUM' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '367176');

-- SENAC UNIDIDADE ENSINO XI- CENTRO DE FORMAÇÃO PROFISSIONAL DE BARBACENA (BARBACENA)
UPDATE schools SET inep_code = '313734' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAC UNIDIDADE ENSINO XI- CENTRO DE FORMAÇÃO PROFISSIONAL DE BARBACENA' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '313734');

-- ESCOLA SOL NASCENTE (BARROSO)
UPDATE schools SET inep_code = '294381' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SOL NASCENTE' AND UPPER(TRIM(city)) = 'BARROSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '294381');

-- INVICTUS CENTRO DE ENSINO (BARROSO)
UPDATE schools SET inep_code = '280691' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INVICTUS CENTRO DE ENSINO' AND UPPER(TRIM(city)) = 'BARROSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '280691');

-- INSTITUTO EDUCACIONAL LISBOA (CARANDAÍ)
UPDATE schools SET inep_code = '277860' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL LISBOA' AND UPPER(TRIM(city)) = 'CARANDAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '277860');

-- INSTITUTO DE EDUCAÇÃO SABER (MERCÊS)
UPDATE schools SET inep_code = '361194' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO DE EDUCAÇÃO SABER' AND UPPER(TRIM(city)) = 'MERCÊS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '361194');

-- CENTRO MINEIRO TÉCNICO PROFISSIONAL DE CAMPO BELO (CAMPO BELO)
UPDATE schools SET inep_code = '370606' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO MINEIRO TÉCNICO PROFISSIONAL DE CAMPO BELO' AND UPPER(TRIM(city)) = 'CAMPO BELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '370606');

-- COLÉGIO AQUARELA (CAMPO BELO)
UPDATE schools SET inep_code = '356930' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO AQUARELA' AND UPPER(TRIM(city)) = 'CAMPO BELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '356930');

-- COLÉGIO DOM CABRAL (CAMPO BELO)
UPDATE schools SET inep_code = '205150' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DOM CABRAL' AND UPPER(TRIM(city)) = 'CAMPO BELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '205150');

-- COLÉGIO LOSANGO DE CAMPO BELO (CAMPO BELO)
UPDATE schools SET inep_code = '329576' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO LOSANGO DE CAMPO BELO' AND UPPER(TRIM(city)) = 'CAMPO BELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '329576');

-- CENTRO EDUCACIONAL CAMBALHOTA (CANDEIAS)
UPDATE schools SET inep_code = '288209' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL CAMBALHOTA' AND UPPER(TRIM(city)) = 'CANDEIAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '288209');

-- CENTRO DE ENSINO ADMISSÃO (LAVRAS)
UPDATE schools SET inep_code = '374628' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE ENSINO ADMISSÃO' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '374628');

-- CENTRO TECNOLÓGICO DE LAVRAS - CETEC (LAVRAS)
UPDATE schools SET inep_code = '341371' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO TECNOLÓGICO DE LAVRAS - CETEC' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '341371');

-- COLÉGIO ADVENTISTA -  FADMINAS (LAVRAS)
UPDATE schools SET inep_code = '246018' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ADVENTISTA -  FADMINAS' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246018');

-- COLÉGIO CENECISTA JUVENTINO DIAS (LAVRAS)
UPDATE schools SET inep_code = '205249' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CENECISTA JUVENTINO DIAS' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '205249');

-- COLÉGIO EDUCA (LAVRAS)
UPDATE schools SET inep_code = '310573' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO EDUCA' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310573');

-- COLÉGIO IMP (LAVRAS)
UPDATE schools SET inep_code = '346314' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO IMP' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346314');

-- COLÉGIO LOSANGO DE LAVRAS (LAVRAS)
UPDATE schools SET inep_code = '354848' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO LOSANGO DE LAVRAS' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '354848');

-- COLÉGIO NOSSA SENHORA DE LOURDES (LAVRAS)
UPDATE schools SET inep_code = '205231' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO NOSSA SENHORA DE LOURDES' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '205231');

-- COLÉGIO UNIVERSITÁRIO PROFESSOR CANÍSIO IGNÁCIO LUNKES (LAVRAS)
UPDATE schools SET inep_code = '328294' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO UNIVERSITÁRIO PROFESSOR CANÍSIO IGNÁCIO LUNKES' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '328294');

-- ECEI ESCOLA COOPERATIVA DE ENSINO E INTEGRAÇÃO (LAVRAS)
UPDATE schools SET inep_code = '292451' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ECEI ESCOLA COOPERATIVA DE ENSINO E INTEGRAÇÃO' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '292451');

-- ESCOLA COOPERATIVA GRALHA AZUL (LAVRAS)
UPDATE schools SET inep_code = '210609' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA COOPERATIVA GRALHA AZUL' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '210609');

-- IMPACTO ESCOLA DE SAÚDE (LAVRAS)
UPDATE schools SET inep_code = '326160' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'IMPACTO ESCOLA DE SAÚDE' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '326160');

-- INSTITUTO PRESBITERIANO GAMMON (LAVRAS)
UPDATE schools SET inep_code = '205265' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO PRESBITERIANO GAMMON' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '205265');

-- ESCOLA CENECISTA DULCE OLIVEIRA (PERDÕES)
UPDATE schools SET inep_code = '205281' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA CENECISTA DULCE OLIVEIRA' AND UPPER(TRIM(city)) = 'PERDÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '205281');

-- NÚCLEO DE APRENDIZAGEM INTEGRAL (PERDÕES)
UPDATE schools SET inep_code = '278602' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'NÚCLEO DE APRENDIZAGEM INTEGRAL' AND UPPER(TRIM(city)) = 'PERDÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '278602');

-- CENTRO  EDUCACIONAL FAUSTO AVELLAR-CEFA (SANTO ANTÔNIO DO AMPARO)
UPDATE schools SET inep_code = '322253' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO  EDUCACIONAL FAUSTO AVELLAR-CEFA' AND UPPER(TRIM(city)) = 'SANTO ANTÔNIO DO AMPARO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322253');

-- INSTITUTO EDUCACIONAL ARCO (SANTO ANTÔNIO DO AMPARO)
UPDATE schools SET inep_code = '278793' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL ARCO' AND UPPER(TRIM(city)) = 'SANTO ANTÔNIO DO AMPARO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '278793');

-- COLÉGIO CONCEITO (CARANGOLA)
UPDATE schools SET inep_code = '326143' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CONCEITO' AND UPPER(TRIM(city)) = 'CARANGOLA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '326143');

-- ESCOLA ENF-CIÊNCIA (CARANGOLA)
UPDATE schools SET inep_code = '309800' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA ENF-CIÊNCIA' AND UPPER(TRIM(city)) = 'CARANGOLA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '309800');

-- ESCOLA OFFICINA DO SABER (CARANGOLA)
UPDATE schools SET inep_code = '276006' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA OFFICINA DO SABER' AND UPPER(TRIM(city)) = 'CARANGOLA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '276006');

-- ESCOLA SERVITA REGINA PACIS (CARANGOLA)
UPDATE schools SET inep_code = '102385' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SERVITA REGINA PACIS' AND UPPER(TRIM(city)) = 'CARANGOLA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '102385');

-- IMEC DE CARANGOLA (CARANGOLA)
UPDATE schools SET inep_code = '329886' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'IMEC DE CARANGOLA' AND UPPER(TRIM(city)) = 'CARANGOLA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '329886');

-- INSTITUTO EDUCAR (DIVINO)
UPDATE schools SET inep_code = '380989' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCAR' AND UPPER(TRIM(city)) = 'DIVINO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '380989');

-- COLÉGIO BATISTA REOBOTE (ESPERA FELIZ)
UPDATE schools SET inep_code = '281808' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO BATISTA REOBOTE' AND UPPER(TRIM(city)) = 'ESPERA FELIZ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '281808');

-- COLÉGIO PORTAL DO SABER (ESPERA FELIZ)
UPDATE schools SET inep_code = '299880' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PORTAL DO SABER' AND UPPER(TRIM(city)) = 'ESPERA FELIZ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '299880');

-- INSTITUTO DE EDUCAÇÃO MORIÁ (ESPERA FELIZ)
UPDATE schools SET inep_code = '351849' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO DE EDUCAÇÃO MORIÁ' AND UPPER(TRIM(city)) = 'ESPERA FELIZ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '351849');

-- CENTRO DE EXTENSÃO E FORMAÇÃO OFICINA DO CORPO - CEFOC (TOMBOS)
UPDATE schools SET inep_code = '369896' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE EXTENSÃO E FORMAÇÃO OFICINA DO CORPO - CEFOC' AND UPPER(TRIM(city)) = 'TOMBOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369896');

-- COLÉGIO DOCTUM (CARATINGA)
UPDATE schools SET inep_code = '345865' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DOCTUM' AND UPPER(TRIM(city)) = 'CARATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '345865');

-- COLÉGIO GENOMA (CARATINGA)
UPDATE schools SET inep_code = '360147' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO GENOMA' AND UPPER(TRIM(city)) = 'CARATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '360147');

-- ESCOLA PROFESSOR JAIRO GROSSI (CARATINGA)
UPDATE schools SET inep_code = '219126' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA PROFESSOR JAIRO GROSSI' AND UPPER(TRIM(city)) = 'CARATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '219126');

-- ESCOLA LÁPIS DE COR (INHAPIM)
UPDATE schools SET inep_code = '281107' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA LÁPIS DE COR' AND UPPER(TRIM(city)) = 'INHAPIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '281107');

-- INSTITUTO PRESBITERIANO DE EDUCAÇÃO LOGOS (IPANEMA)
UPDATE schools SET inep_code = '374407' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO PRESBITERIANO DE EDUCAÇÃO LOGOS' AND UPPER(TRIM(city)) = 'IPANEMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '374407');

-- CENTRO TÉCNICO PROFISSIONAL DE BAEPENDI (BAEPENDI)
UPDATE schools SET inep_code = '381012' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO TÉCNICO PROFISSIONAL DE BAEPENDI' AND UPPER(TRIM(city)) = 'BAEPENDI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '381012');

-- COLÉGIO FRANCISCANO SANTO INÁCIO (BAEPENDI)
UPDATE schools SET inep_code = '180262' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO FRANCISCANO SANTO INÁCIO' AND UPPER(TRIM(city)) = 'BAEPENDI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180262');

-- EDUCANDÁRIO FRANCISCANO NHÁ CHICA (BAEPENDI)
UPDATE schools SET inep_code = '364460' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EDUCANDÁRIO FRANCISCANO NHÁ CHICA' AND UPPER(TRIM(city)) = 'BAEPENDI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '364460');

-- CENTRO EDUCACIONAL GENNY GOMES (CAXAMBU)
UPDATE schools SET inep_code = '274691' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL GENNY GOMES' AND UPPER(TRIM(city)) = 'CAXAMBU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '274691');

-- COLÉGIO DOM FERRAZ (CAXAMBU)
UPDATE schools SET inep_code = '248401' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DOM FERRAZ' AND UPPER(TRIM(city)) = 'CAXAMBU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '248401');

-- COLÉGIO ÊXITO (CAXAMBU)
UPDATE schools SET inep_code = '372030' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ÊXITO' AND UPPER(TRIM(city)) = 'CAXAMBU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '372030');

-- INSTITUTO SÃO JOSÉ (CONCEIÇÃO DO RIO VERDE)
UPDATE schools SET inep_code = '324507' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO SÃO JOSÉ' AND UPPER(TRIM(city)) = 'CONCEIÇÃO DO RIO VERDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '324507');

-- COLÉGIO JOÃO PAULO II (CRUZÍLIA)
UPDATE schools SET inep_code = '349127' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO JOÃO PAULO II' AND UPPER(TRIM(city)) = 'CRUZÍLIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349127');

-- CENTRO CULTURAL CLOTILDE FRAMIL (ITAMONTE)
UPDATE schools SET inep_code = '273091' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO CULTURAL CLOTILDE FRAMIL' AND UPPER(TRIM(city)) = 'ITAMONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '273091');

-- EDUCANDÁRIO SÃO FRANCISCO DE ASSIS (ITAMONTE)
UPDATE schools SET inep_code = '278815' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EDUCANDÁRIO SÃO FRANCISCO DE ASSIS' AND UPPER(TRIM(city)) = 'ITAMONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '278815');

-- CENTRO EDUCACIONAL AQUARELA (ITANHANDU)
UPDATE schools SET inep_code = '273848' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL AQUARELA' AND UPPER(TRIM(city)) = 'ITANHANDU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '273848');

-- COLÉGIO MINAS AUSTRAL (ITANHANDU)
UPDATE schools SET inep_code = '223778' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MINAS AUSTRAL' AND UPPER(TRIM(city)) = 'ITANHANDU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '223778');

-- COLÉGIO PRIMAR (ITANHANDU)
UPDATE schools SET inep_code = '345571' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PRIMAR' AND UPPER(TRIM(city)) = 'ITANHANDU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '345571');

-- COLÉGIO BALBINA RIBEIRO SOARES (PASSA QUATRO)
UPDATE schools SET inep_code = '180475' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO BALBINA RIBEIRO SOARES' AND UPPER(TRIM(city)) = 'PASSA QUATRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180475');

-- COLÉGIO SÃO MIGUEL (PASSA QUATRO)
UPDATE schools SET inep_code = '180483' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SÃO MIGUEL' AND UPPER(TRIM(city)) = 'PASSA QUATRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180483');

-- COLÉGIO ALERE (SÃO LOURENÇO)
UPDATE schools SET inep_code = '377481' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ALERE' AND UPPER(TRIM(city)) = 'SÃO LOURENÇO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '377481');

-- COLÉGIO DOM BOSCO (SÃO LOURENÇO)
UPDATE schools SET inep_code = '323071' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DOM BOSCO' AND UPPER(TRIM(city)) = 'SÃO LOURENÇO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '323071');

-- COLÉGIO DOM FERRAZ SOLAR (SÃO LOURENÇO)
UPDATE schools SET inep_code = '274852' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DOM FERRAZ SOLAR' AND UPPER(TRIM(city)) = 'SÃO LOURENÇO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '274852');

-- COLÉGIO IMACULADO CORAÇÃO DE MARIA (SÃO LOURENÇO)
UPDATE schools SET inep_code = '180521' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO IMACULADO CORAÇÃO DE MARIA' AND UPPER(TRIM(city)) = 'SÃO LOURENÇO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180521');

-- COLÉGIO INTEGRADO DE SÃO LOURENÇO (SÃO LOURENÇO)
UPDATE schools SET inep_code = '246182' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO INTEGRADO DE SÃO LOURENÇO' AND UPPER(TRIM(city)) = 'SÃO LOURENÇO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246182');

-- COLÉGIO LASER (SÃO LOURENÇO)
UPDATE schools SET inep_code = '180530' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO LASER' AND UPPER(TRIM(city)) = 'SÃO LOURENÇO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180530');

-- INSTITUTO GÊNESIS DE EDUCAÇÃO E CULTURA (SÃO LOURENÇO)
UPDATE schools SET inep_code = '293881' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO GÊNESIS DE EDUCAÇÃO E CULTURA' AND UPPER(TRIM(city)) = 'SÃO LOURENÇO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '293881');

-- CET - CENTRO DE EDUCACÃO TECNOLÓGICA GENERAL EDMUNDO DE MACEDO SOARES E SILVA (CONGONHAS)
UPDATE schools SET inep_code = '196142' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CET - CENTRO DE EDUCACÃO TECNOLÓGICA GENERAL EDMUNDO DE MACEDO SOARES E SILVA' AND UPPER(TRIM(city)) = 'CONGONHAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196142');

-- COLÉGIO ARCEBISPO DOM OSCAR DE OLIVEIRA (CONGONHAS)
UPDATE schools SET inep_code = '292826' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ARCEBISPO DOM OSCAR DE OLIVEIRA' AND UPPER(TRIM(city)) = 'CONGONHAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '292826');

-- COLÉGIO NOSSA SENHORA DA PIEDADE (CONGONHAS)
UPDATE schools SET inep_code = '196134' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO NOSSA SENHORA DA PIEDADE' AND UPPER(TRIM(city)) = 'CONGONHAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196134');

-- COLÉGIO SAGRADO CORAÇÃO DE JESUS (CONGONHAS)
UPDATE schools SET inep_code = '344249' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SAGRADO CORAÇÃO DE JESUS' AND UPPER(TRIM(city)) = 'CONGONHAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '344249');

-- CENTRO TÉCNICO PROFISSIONAL DE CONSELHEIRO LAFAIETE (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '381330' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO TÉCNICO PROFISSIONAL DE CONSELHEIRO LAFAIETE' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '381330');

-- COLÉGIO EDUCAR (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '351997' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO EDUCAR' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '351997');

-- COLÉGIO MONTEIRO LOBATO (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '256919' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MONTEIRO LOBATO' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '256919');

-- COLÉGIO NOSSA SENHORA DE NAZARÉ (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '196177' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO NOSSA SENHORA DE NAZARÉ' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196177');

-- COLÉGIO POTÊNCIA (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '305235' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO POTÊNCIA' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305235');

-- COLÉGIO PROFESSORA ELI MARQUES (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '196185' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PROFESSORA ELI MARQUES' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196185');

-- COLÉGIO QUELUZ DE MINAS (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '210595' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO QUELUZ DE MINAS' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '210595');

-- COLÉGIO SANTA RITA-FASAR (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '321745' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SANTA RITA-FASAR' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '321745');

-- ESCOLA TÉCNICA DE SAÚDE (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '318035' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA DE SAÚDE' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '318035');

-- INSTITUTO EDUCACIONAL MARGARIDA REZENDE (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '339989' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL MARGARIDA REZENDE' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '339989');

-- SENAC - UNIDADE DE ENSINO TÉCNICO DO CEP DE CONSELHEIRO LAFAIETE (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '359823' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAC - UNIDADE DE ENSINO TÉCNICO DO CEP DE CONSELHEIRO LAFAIETE' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '359823');

-- UNIDADE DE ENSINO MORAIS (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '365483' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'UNIDADE DE ENSINO MORAIS' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '365483');

-- CENTRO TÉCNICO PROFISSIONAL DE ENTRE RIOS DE MINAS (ENTRE RIOS DE MINAS)
UPDATE schools SET inep_code = '372404' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO TÉCNICO PROFISSIONAL DE ENTRE RIOS DE MINAS' AND UPPER(TRIM(city)) = 'ENTRE RIOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '372404');

-- COLÉGIO ARQUIDIOCESANO (OURO BRANCO)
UPDATE schools SET inep_code = '230871' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ARQUIDIOCESANO' AND UPPER(TRIM(city)) = 'OURO BRANCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '230871');

-- COLÉGIO BATISTA MINEIRO (OURO BRANCO)
UPDATE schools SET inep_code = '196312' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO BATISTA MINEIRO' AND UPPER(TRIM(city)) = 'OURO BRANCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196312');

-- COLÉGIO PIO XII COOPPED UNIDADE I (OURO BRANCO)
UPDATE schools SET inep_code = '305987' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PIO XII COOPPED UNIDADE I' AND UPPER(TRIM(city)) = 'OURO BRANCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305987');

-- SENAI OURO BRANCO CENTRO DE FORMAÇÃO PROFISSIONAL (OURO BRANCO)
UPDATE schools SET inep_code = '358118' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI OURO BRANCO CENTRO DE FORMAÇÃO PROFISSIONAL' AND UPPER(TRIM(city)) = 'OURO BRANCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '358118');

-- AMPLIAR INSTITUTO DE EDUCAÇÃO (CORONEL FABRICIANO)
UPDATE schools SET inep_code = '326305' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'AMPLIAR INSTITUTO DE EDUCAÇÃO' AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '326305');

-- C EDUC ANJO DA GUARDA (CORONEL FABRICIANO)
UPDATE schools SET inep_code = '266701' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'C EDUC ANJO DA GUARDA' AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '266701');

-- C EDUC SOUZA RIBEIRO (CORONEL FABRICIANO)
UPDATE schools SET inep_code = '240320' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'C EDUC SOUZA RIBEIRO' AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '240320');

-- CEPSMA- COLÉGIO E CENTRO DE PESQUISA SOUZA MARTINS (CORONEL FABRICIANO)
UPDATE schools SET inep_code = '238180' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CEPSMA- COLÉGIO E CENTRO DE PESQUISA SOUZA MARTINS' AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '238180');

-- COLÉGIO ANGÉLICA (CORONEL FABRICIANO)
UPDATE schools SET inep_code = '192996' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ANGÉLICA' AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '192996');

-- COLÉGIO CATÓLICA PADRE DE MAN (CORONEL FABRICIANO)
UPDATE schools SET inep_code = '193038' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CATÓLICA PADRE DE MAN' AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193038');

-- COLÉGIO JOÃO CALVINO (CORONEL FABRICIANO)
UPDATE schools SET inep_code = '193020' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO JOÃO CALVINO' AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193020');

-- COLMINAS - COLÉGIO TÉCNICO DO LESTE MINEIRO (CORONEL FABRICIANO)
UPDATE schools SET inep_code = '339415' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLMINAS - COLÉGIO TÉCNICO DO LESTE MINEIRO' AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '339415');

-- ETHOS INSTITUTO DE EDUCAÇAO (CORONEL FABRICIANO)
UPDATE schools SET inep_code = '254096' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ETHOS INSTITUTO DE EDUCAÇAO' AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '254096');

-- SENAC- UNIDADE DE ENSINO TÉCNICO - CFP VALE DO AÇO (CORONEL FABRICIANO)
UPDATE schools SET inep_code = '325279' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAC- UNIDADE DE ENSINO TÉCNICO - CFP VALE DO AÇO' AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '325279');

--  FIBONACCI COLÉGIO (IPATINGA)
UPDATE schools SET inep_code = '349720' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'FIBONACCI COLÉGIO' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349720');

-- CEST - COLÉGIO EDUCACIONAL DE SUPLÊNCIA E TÉCNICO (IPATINGA)
UPDATE schools SET inep_code = '261581' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CEST - COLÉGIO EDUCACIONAL DE SUPLÊNCIA E TÉCNICO' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '261581');

-- COLÉGIO ADVENTISTA DE IPATINGA (IPATINGA)
UPDATE schools SET inep_code = '261564' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ADVENTISTA DE IPATINGA' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '261564');

-- COLÉGIO BATISTA DE IPATINGA (IPATINGA)
UPDATE schools SET inep_code = '251763' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO BATISTA DE IPATINGA' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '251763');

-- COLÉGIO JOHN WESLEY (IPATINGA)
UPDATE schools SET inep_code = '193071' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO JOHN WESLEY' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193071');

-- COLÉGIO SÃO FRANCISCO XAVIER (IPATINGA)
UPDATE schools SET inep_code = '193097' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SÃO FRANCISCO XAVIER' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193097');

-- COLÉGIO SÃO FRANCISCO XAVIER - UNIDADE II (IPATINGA)
UPDATE schools SET inep_code = '220159' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SÃO FRANCISCO XAVIER - UNIDADE II' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '220159');

-- COLÉGIO SEMEAR (IPATINGA)
UPDATE schools SET inep_code = '310018' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SEMEAR' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310018');

-- EICA ESCOLA CANTINHO DA ALEGRIA (IPATINGA)
UPDATE schools SET inep_code = '344125' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EICA ESCOLA CANTINHO DA ALEGRIA' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '344125');

-- ESCOLA CRIAR E APRENDER (IPATINGA)
UPDATE schools SET inep_code = '303381' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA CRIAR E APRENDER' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '303381');

-- ESCOLA EDUCAÇÃO CRIATIVA (IPATINGA)
UPDATE schools SET inep_code = '193216' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA EDUCAÇÃO CRIATIVA' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193216');

-- ESCOLA ÉRICO VERÍSSIMO (IPATINGA)
UPDATE schools SET inep_code = '193151' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA ÉRICO VERÍSSIMO' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193151');

-- ESCOLA PRÓ IMAGEM EDUCAÇÃO PROFISSIONAL (IPATINGA)
UPDATE schools SET inep_code = '310034' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA PRÓ IMAGEM EDUCAÇÃO PROFISSIONAL' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310034');

-- ESCOLA SESI RINALDO CAMPOS SOARES (IPATINGA)
UPDATE schools SET inep_code = '357081' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SESI RINALDO CAMPOS SOARES' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '357081');

-- ESCOLA SESI SANTA RITA DE CÁSSIA (IPATINGA)
UPDATE schools SET inep_code = '230839' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SESI SANTA RITA DE CÁSSIA' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '230839');

-- ESCOLA TÉCNICA JUSCELINO KUBITSCHEK (IPATINGA)
UPDATE schools SET inep_code = '193089' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA JUSCELINO KUBITSCHEK' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193089');

-- INSTITUTO EDUCACIONAL MAYRINK VIEIRA (IPATINGA)
UPDATE schools SET inep_code = '193160' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL MAYRINK VIEIRA' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193160');

-- INSTITUTO EDUCACIONAL PEQUENOS GIGANTES (IPATINGA)
UPDATE schools SET inep_code = '343145' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL PEQUENOS GIGANTES' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '343145');

-- INSTITUTO EDUCACIONAL PILAR (IPATINGA)
UPDATE schools SET inep_code = '269549' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL PILAR' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '269549');

-- MONTESSORI SCHOOL (IPATINGA)
UPDATE schools SET inep_code = '374636' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'MONTESSORI SCHOOL' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '374636');

-- READ - REDE DE ENSINO ASSEMBLEIA DE DEUS (IPATINGA)
UPDATE schools SET inep_code = '363316' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'READ - REDE DE ENSINO ASSEMBLEIA DE DEUS' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '363316');

-- SENAC UNIDADE DE ENSINO TÉCNICO- CFP IPATINGA (IPATINGA)
UPDATE schools SET inep_code = '341304' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAC UNIDADE DE ENSINO TÉCNICO- CFP IPATINGA' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '341304');

-- SENAI - CENTRO DE FORMAÇÃO PROFISSIONAL RINALDO CAMPOS SOARES (IPATINGA)
UPDATE schools SET inep_code = '340332' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI - CENTRO DE FORMAÇÃO PROFISSIONAL RINALDO CAMPOS SOARES' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '340332');

-- CENTRO EDUCACIONAL CATÓLICA DO LESTE DE MINAS GERAIS - CECMG (TIMÓTEO)
UPDATE schools SET inep_code = '193313' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL CATÓLICA DO LESTE DE MINAS GERAIS - CECMG' AND UPPER(TRIM(city)) = 'TIMÓTEO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193313');

-- COLÉGIO GENOMA (TIMÓTEO)
UPDATE schools SET inep_code = '364517' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO GENOMA' AND UPPER(TRIM(city)) = 'TIMÓTEO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '364517');

-- COLÉGIO GENOMA I (TIMÓTEO)
UPDATE schools SET inep_code = '372277' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO GENOMA I' AND UPPER(TRIM(city)) = 'TIMÓTEO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '372277');

-- EBA - ESCOLA BATISTA DE ACESITA - UNIDADE I (TIMÓTEO)
UPDATE schools SET inep_code = '254363' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EBA - ESCOLA BATISTA DE ACESITA - UNIDADE I' AND UPPER(TRIM(city)) = 'TIMÓTEO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '254363');

-- ESCOLA BATISTA DE ACESITA - EBA - UNIDADE II (TIMÓTEO)
UPDATE schools SET inep_code = '373796' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA BATISTA DE ACESITA - EBA - UNIDADE II' AND UPPER(TRIM(city)) = 'TIMÓTEO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '373796');

-- INSTITUTO DE EDUCAÇÃO PAULO ANTÔNIO SILVA - IEPAS (TIMÓTEO)
UPDATE schools SET inep_code = '316008' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO DE EDUCAÇÃO PAULO ANTÔNIO SILVA - IEPAS' AND UPPER(TRIM(city)) = 'TIMÓTEO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '316008');