-- INSTITUTO NOSSA SENHORA DO CARMO (CATAGUASES)
UPDATE schools SET inep_code = '102415' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO NOSSA SENHORA DO CARMO' AND UPPER(TRIM(city)) = 'CATAGUASES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '102415');

-- SENAI- CENTRO DE FORMAÇÃO PROFISSIONAL JOSÉ IGNÁCIO PEIXOTO (CATAGUASES)
UPDATE schools SET inep_code = '248959' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI- CENTRO DE FORMAÇÃO PROFISSIONAL JOSÉ IGNÁCIO PEIXOTO' AND UPPER(TRIM(city)) = 'CATAGUASES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '248959');

-- CENTRO EDUCACIONAL NOVO HORIZONTE (LEOPOLDINA)
UPDATE schools SET inep_code = '254819' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL NOVO HORIZONTE' AND UPPER(TRIM(city)) = 'LEOPOLDINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '254819');

-- CENTRO TÉCNICO PROFISSIONAL DE LEOPOLDINA (LEOPOLDINA)
UPDATE schools SET inep_code = '381039' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO TÉCNICO PROFISSIONAL DE LEOPOLDINA' AND UPPER(TRIM(city)) = 'LEOPOLDINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '381039');

-- COLÉGIO CIDADE DE LEOPOLDINA (LEOPOLDINA)
UPDATE schools SET inep_code = '250449' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CIDADE DE LEOPOLDINA' AND UPPER(TRIM(city)) = 'LEOPOLDINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '250449');

-- COLÉGIO IMACULADA CONCEIÇÃO (LEOPOLDINA)
UPDATE schools SET inep_code = '102482' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO IMACULADA CONCEIÇÃO' AND UPPER(TRIM(city)) = 'LEOPOLDINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '102482');

-- EPEL ESCOLA POLITÉCNICA EQUIPE DE LEOPOLDINA (LEOPOLDINA)
UPDATE schools SET inep_code = '354627' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EPEL ESCOLA POLITÉCNICA EQUIPE DE LEOPOLDINA' AND UPPER(TRIM(city)) = 'LEOPOLDINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '354627');

-- CENTRO EDUCACIONAL MARTINS E COSTA - CEMEC (PIRAPETINGA)
UPDATE schools SET inep_code = '352462' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL MARTINS E COSTA - CEMEC' AND UPPER(TRIM(city)) = 'PIRAPETINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '352462');

-- CENTRO EDUCACIONAL NORMA AMÉLIA PIRES-CENAP (PIRAPETINGA)
UPDATE schools SET inep_code = '279463' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL NORMA AMÉLIA PIRES-CENAP' AND UPPER(TRIM(city)) = 'PIRAPETINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '279463');

-- ESCOLA TÉCNICA EVOLUÇÃO (CHALÉ)
UPDATE schools SET inep_code = '369144' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA EVOLUÇÃO' AND UPPER(TRIM(city)) = 'CHALÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369144');

-- ESCOLA FAMÍLIA AGRÍCOLA MARGARIDA ALVES - EFAMA (CONCEIÇÃO DE IPANEMA)
UPDATE schools SET inep_code = '344397' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA FAMÍLIA AGRÍCOLA MARGARIDA ALVES - EFAMA' AND UPPER(TRIM(city)) = 'CONCEIÇÃO DE IPANEMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '344397');

-- CENTRO EDUCACIONAL COOPCEL (LAJINHA)
UPDATE schools SET inep_code = '279056' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL COOPCEL' AND UPPER(TRIM(city)) = 'LAJINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '279056');

-- ESCOLA TÉCNICA VÉRTIX - UNIDADE DE LAJINHA (LAJINHA)
UPDATE schools SET inep_code = '381098' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA VÉRTIX - UNIDADE DE LAJINHA' AND UPPER(TRIM(city)) = 'LAJINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '381098');

-- CEM- CENTRO EDUCACIONAL DE MANHUAÇU (MANHUAÇU)
UPDATE schools SET inep_code = '293971' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CEM- CENTRO EDUCACIONAL DE MANHUAÇU' AND UPPER(TRIM(city)) = 'MANHUAÇU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '293971');

-- COLÉGIO AMÉRICA DO NORTE (MANHUAÇU)
UPDATE schools SET inep_code = '321770' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO AMÉRICA DO NORTE' AND UPPER(TRIM(city)) = 'MANHUAÇU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '321770');

-- COLÉGIO AMÉRICA DO SUL (MANHUAÇU)
UPDATE schools SET inep_code = '321761' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO AMÉRICA DO SUL' AND UPPER(TRIM(city)) = 'MANHUAÇU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '321761');

-- COLÉGIO CIDADE DE MANHUAÇU (MANHUAÇU)
UPDATE schools SET inep_code = '325163' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CIDADE DE MANHUAÇU' AND UPPER(TRIM(city)) = 'MANHUAÇU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '325163');

-- COLÉGIO DE ESTUDOS INTEGRADOS - CESI (MANHUAÇU)
UPDATE schools SET inep_code = '299367' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DE ESTUDOS INTEGRADOS - CESI' AND UPPER(TRIM(city)) = 'MANHUAÇU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '299367');

-- ESCOLA DO FUTURO (MANHUAÇU)
UPDATE schools SET inep_code = '294357' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DO FUTURO' AND UPPER(TRIM(city)) = 'MANHUAÇU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '294357');

-- ORBIS EDUCAÇÃO (MANHUAÇU)
UPDATE schools SET inep_code = '342874' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ORBIS EDUCAÇÃO' AND UPPER(TRIM(city)) = 'MANHUAÇU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342874');

-- SENAC- UNIDADE ENSINO TÉCNICO- CFP DE MANHUAÇU (MANHUAÇU)
UPDATE schools SET inep_code = '339903' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAC- UNIDADE ENSINO TÉCNICO- CFP DE MANHUAÇU' AND UPPER(TRIM(city)) = 'MANHUAÇU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '339903');

-- COLÉGIO PIO XI DE MANHUMIRIM (MANHUMIRIM)
UPDATE schools SET inep_code = '369527' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PIO XI DE MANHUMIRIM' AND UPPER(TRIM(city)) = 'MANHUMIRIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369527');

-- ESCOLA VERTENTE DO CAPARAÓ DE MANHUMIRIM - EVEC MANHUMIRIM (MANHUMIRIM)
UPDATE schools SET inep_code = '338605' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA VERTENTE DO CAPARAÓ DE MANHUMIRIM - EVEC MANHUMIRIM' AND UPPER(TRIM(city)) = 'MANHUMIRIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338605');

-- CENTRO EDUCACIONAL DE MATIPÓ (MATIPÓ)
UPDATE schools SET inep_code = '313483' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL DE MATIPÓ' AND UPPER(TRIM(city)) = 'MATIPÓ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '313483');

-- ESCOLA TÉCNICA VÉRTIX (MATIPÓ)
UPDATE schools SET inep_code = '352578' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA VÉRTIX' AND UPPER(TRIM(city)) = 'MATIPÓ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '352578');

-- COLÉGIO MUTUM (MUTUM)
UPDATE schools SET inep_code = '316377' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MUTUM' AND UPPER(TRIM(city)) = 'MUTUM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '316377');

-- CENTRO EDUCACIONAL DE SIMONÉSIA (SIMONÉSIA)
UPDATE schools SET inep_code = '313408' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL DE SIMONÉSIA' AND UPPER(TRIM(city)) = 'SIMONÉSIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '313408');

-- CENTRO EDUCACIONAL BELDANI (BARÃO DE COCAIS)
UPDATE schools SET inep_code = '253065' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL BELDANI' AND UPPER(TRIM(city)) = 'BARÃO DE COCAIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253065');

-- CENTRO PROFISSIONAL GUILHERME CALDAS EMRICH-SENAI (BARÃO DE COCAIS)
UPDATE schools SET inep_code = '327816' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO PROFISSIONAL GUILHERME CALDAS EMRICH-SENAI' AND UPPER(TRIM(city)) = 'BARÃO DE COCAIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '327816');

-- COLÉGIO EDUCARE (BARÃO DE COCAIS)
UPDATE schools SET inep_code = '229946' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO EDUCARE' AND UPPER(TRIM(city)) = 'BARÃO DE COCAIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '229946');

-- VEREDAS EDUCAÇÃO (BARÃO DE COCAIS)
UPDATE schools SET inep_code = '376809' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'VEREDAS EDUCAÇÃO' AND UPPER(TRIM(city)) = 'BARÃO DE COCAIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '376809');

-- ABV ETEC MG - ESCOLA TÉCNICA DE MINAS GERAIS (BELO HORIZONTE)
UPDATE schools SET inep_code = '381470' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ABV ETEC MG - ESCOLA TÉCNICA DE MINAS GERAIS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '381470');

-- CASA DOS QUADRINHOS ESCOLA DE ARTES (BELO HORIZONTE)
UPDATE schools SET inep_code = '340740' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CASA DOS QUADRINHOS ESCOLA DE ARTES' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '340740');

-- CASA VIVA EDUCAÇÃO E CULTURA (BELO HORIZONTE)
UPDATE schools SET inep_code = '365424' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CASA VIVA EDUCAÇÃO E CULTURA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '365424');

-- CEFEMG- CENTRO DE FORMAÇÃO EM ENFERMAGEM DE MINAS GERAIS (BELO HORIZONTE)
UPDATE schools SET inep_code = '306690' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CEFEMG- CENTRO DE FORMAÇÃO EM ENFERMAGEM DE MINAS GERAIS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '306690');

-- CENTRO DE EDUCAÇÃO PROFISSIONAL SENAC - PLUGMINAS (BELO HORIZONTE)
UPDATE schools SET inep_code = '364282' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE EDUCAÇÃO PROFISSIONAL SENAC - PLUGMINAS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '364282');

-- CENTRO DE EDUCAÇÃO TECNOLÓGICA NOVO RUMO (BELO HORIZONTE)
UPDATE schools SET inep_code = '292567' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE EDUCAÇÃO TECNOLÓGICA NOVO RUMO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '292567');

-- CENTRO DE ENSINO GRAU TÉCNICO - UNIDADE BELO HORIZONTE (BELO HORIZONTE)
UPDATE schools SET inep_code = '363790' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE ENSINO GRAU TÉCNICO - UNIDADE BELO HORIZONTE' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '363790');

-- CENTRO DE ENSINO GRAU TÉCNICO BH - UNIDADE III (BELO HORIZONTE)
UPDATE schools SET inep_code = '371041' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE ENSINO GRAU TÉCNICO BH - UNIDADE III' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '371041');

-- CENTRO DE FORMAÇÃO ARTÍSTICA E TECNOLÓGICA - CEFART- FUNDAÇÃO CLÓVIS SALGADO (BELO HORIZONTE)
UPDATE schools SET inep_code = '280526' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE FORMAÇÃO ARTÍSTICA E TECNOLÓGICA - CEFART- FUNDAÇÃO CLÓVIS SALGADO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '280526');

-- CENTRO DE FORMAÇÃO PROFISSIONAL PAULO CÉSAR DIAS DE SOUZA (BELO HORIZONTE)
UPDATE schools SET inep_code = '342769' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE FORMAÇÃO PROFISSIONAL PAULO CÉSAR DIAS DE SOUZA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342769');

-- CENTRO DE FORMAÇÃO TECNOLÓGICA DE MINAS GERAIS - CENTROMIG (BELO HORIZONTE)
UPDATE schools SET inep_code = '353132' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE FORMAÇÃO TECNOLÓGICA DE MINAS GERAIS - CENTROMIG' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '353132');

-- CENTRO EDUCACIONAL ARCA DE NOÉ (BELO HORIZONTE)
UPDATE schools SET inep_code = '331864' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL ARCA DE NOÉ' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '331864');

-- CENTRO EDUCACIONAL SANGI (BELO HORIZONTE)
UPDATE schools SET inep_code = '315389' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL SANGI' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '315389');

-- COLÉGIO ALUMNUS (BELO HORIZONTE)
UPDATE schools SET inep_code = '314749' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ALUMNUS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '314749');

-- COLÉGIO BERNOULLI - UNIDADE GONÇALVES DIAS (BELO HORIZONTE)
UPDATE schools SET inep_code = '311723' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO BERNOULLI - UNIDADE GONÇALVES DIAS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '311723');

-- COLÉGIO BERNOULLI - UNIDADE LOURDES (BELO HORIZONTE)
UPDATE schools SET inep_code = '350664' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO BERNOULLI - UNIDADE LOURDES' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '350664');

-- COLÉGIO CHROMOS CENTRO (BELO HORIZONTE)
UPDATE schools SET inep_code = '363294' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CHROMOS CENTRO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '363294');

-- COLÉGIO CONVIVER (BELO HORIZONTE)
UPDATE schools SET inep_code = '344621' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CONVIVER' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '344621');

-- COLÉGIO COTEMIG- FLORESTA (BELO HORIZONTE)
UPDATE schools SET inep_code = '210048' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO COTEMIG- FLORESTA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '210048');

-- COLÉGIO CRESCER (BELO HORIZONTE)
UPDATE schools SET inep_code = '305456' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CRESCER' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305456');

-- COLÉGIO CRISTÃO VER (BELO HORIZONTE)
UPDATE schools SET inep_code = '315567' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CRISTÃO VER' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '315567');

-- COLÉGIO ECCELLENTE - UNIDADE PALMARES (BELO HORIZONTE)
UPDATE schools SET inep_code = '365904' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ECCELLENTE - UNIDADE PALMARES' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '365904');

-- COLÉGIO EDNA RORIZ (BELO HORIZONTE)
UPDATE schools SET inep_code = '260631' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO EDNA RORIZ' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '260631');

-- COLÉGIO ILÚMINA (BELO HORIZONTE)
UPDATE schools SET inep_code = '300454' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ILÚMINA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '300454');

-- COLÉGIO LOGOSÓFICO GONZÁLEZ PECOTCHE CIDADE NOVA (BELO HORIZONTE)
UPDATE schools SET inep_code = '244058' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO LOGOSÓFICO GONZÁLEZ PECOTCHE CIDADE NOVA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '244058');

-- COLÉGIO MANGABEIRAS (BELO HORIZONTE)
UPDATE schools SET inep_code = '347329' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MANGABEIRAS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '347329');

-- COLÉGIO MAXIMUS UNIDADE PALMARES (BELO HORIZONTE)
UPDATE schools SET inep_code = '258644' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MAXIMUS UNIDADE PALMARES' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '258644');

-- COLÉGIO MÉTODO (BELO HORIZONTE)
UPDATE schools SET inep_code = '210251' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MÉTODO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '210251');

-- COLÉGIO OLIMPO BH (BELO HORIZONTE)
UPDATE schools SET inep_code = '369772' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO OLIMPO BH' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369772');

-- COLÉGIO ORLEANS E BRAGANÇA (BELO HORIZONTE)
UPDATE schools SET inep_code = '370258' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ORLEANS E BRAGANÇA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '370258');

-- COLÉGIO OURO MINAS (BELO HORIZONTE)
UPDATE schools SET inep_code = '344001' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO OURO MINAS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '344001');

-- COLÉGIO REDE DECISÃO - UNIDADE LOURDES (BELO HORIZONTE)
UPDATE schools SET inep_code = '378313' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO REDE DECISÃO - UNIDADE LOURDES' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '378313');

-- COLÉGIO SANTA MARIA MINAS - UNIDADE SÃO GABRIEL (BELO HORIZONTE)
UPDATE schools SET inep_code = '381144' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SANTA MARIA MINAS - UNIDADE SÃO GABRIEL' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '381144');

-- COLÉGIO SAVASSI (BELO HORIZONTE)
UPDATE schools SET inep_code = '307742' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SAVASSI' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '307742');

-- COLÉGIO SISTEMA (BELO HORIZONTE)
UPDATE schools SET inep_code = '257583' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SISTEMA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '257583');

-- COLEGUIUM INTERNACIONAL - CIDADE NOVA (BELO HORIZONTE)
UPDATE schools SET inep_code = '374555' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLEGUIUM INTERNACIONAL - CIDADE NOVA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '374555');

-- CONHECER ESCOLA TÉCNICA - UNIDADE II (BELO HORIZONTE)
UPDATE schools SET inep_code = '303461' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CONHECER ESCOLA TÉCNICA - UNIDADE II' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '303461');

-- ELITE FLORESTA - BH (BELO HORIZONTE)
UPDATE schools SET inep_code = '374180' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ELITE FLORESTA - BH' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '374180');

-- ENFERMIG- ESCOLA DE ENFERMAGEM DE MINAS GERAIS (BELO HORIZONTE)
UPDATE schools SET inep_code = '279391' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ENFERMIG- ESCOLA DE ENFERMAGEM DE MINAS GERAIS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '279391');

-- ESCOLA CRISTÃ IBF (BELO HORIZONTE)
UPDATE schools SET inep_code = '244481' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA CRISTÃ IBF' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '244481');

-- ESCOLA DA SERRA (BELO HORIZONTE)
UPDATE schools SET inep_code = '320404' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DA SERRA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '320404');

-- ESCOLA DE PRÓTESE ODONTOLÓGICA EXPERT M MARTINS (BELO HORIZONTE)
UPDATE schools SET inep_code = '283274' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DE PRÓTESE ODONTOLÓGICA EXPERT M MARTINS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '283274');

-- ESCOLA DO SEBRAE DE FORMAÇÃO GERENCIAL BH - NÚCLEO DE EMPREENDEDORISMO JUVENIL - EFG SEBRAE BH - NEJ (BELO HORIZONTE)
UPDATE schools SET inep_code = '348953' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DO SEBRAE DE FORMAÇÃO GERENCIAL BH - NÚCLEO DE EMPREENDEDORISMO JUVENIL - EFG SEBRAE BH - NEJ' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '348953');

-- ESCOLA SESI NEWTON ANTÔNIO DA SILVA PEREIRA - UNIDADE II (BELO HORIZONTE)
UPDATE schools SET inep_code = '379816' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SESI NEWTON ANTÔNIO DA SILVA PEREIRA - UNIDADE II' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '379816');

-- ESCOLA TÉCNICA DA FUNDAÇÃO UNIMED (BELO HORIZONTE)
UPDATE schools SET inep_code = '376833' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA DA FUNDAÇÃO UNIMED' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '376833');

-- ESCOLA TÉCNICA DA SANTA CASA (BELO HORIZONTE)
UPDATE schools SET inep_code = '267082' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA DA SANTA CASA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '267082');

-- ESCOLA TÉCNICA PRÓ INFORMÁTICA (BELO HORIZONTE)
UPDATE schools SET inep_code = '342947' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA PRÓ INFORMÁTICA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342947');

-- ESCOLA TÉCNICA SAÚDE E VIDA (BELO HORIZONTE)
UPDATE schools SET inep_code = '260649' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA SAÚDE E VIDA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '260649');

-- ESTAÇÃO ENSINO (BELO HORIZONTE)
UPDATE schools SET inep_code = '354139' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESTAÇÃO ENSINO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '354139');

-- FACULDADE DE TECNOLOGIA SENAI (BELO HORIZONTE)
UPDATE schools SET inep_code = '367222' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'FACULDADE DE TECNOLOGIA SENAI' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '367222');

-- IMAM INSTITUTO MINEIRO DE ACUPUNTURA E MASSAGENS (BELO HORIZONTE)
UPDATE schools SET inep_code = '306703' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'IMAM INSTITUTO MINEIRO DE ACUPUNTURA E MASSAGENS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '306703');

-- INAP- INSTITUTO DE ARTE E PROJETO (BELO HORIZONTE)
UPDATE schools SET inep_code = '274666' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INAP- INSTITUTO DE ARTE E PROJETO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '274666');

-- INSTITUTO ARCANJO GABRIEL (BELO HORIZONTE)
UPDATE schools SET inep_code = '345814' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO ARCANJO GABRIEL' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '345814');

-- INSTITUTO EDUCACIONAL SÃO CAMILO (BELO HORIZONTE)
UPDATE schools SET inep_code = '354511' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL SÃO CAMILO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '354511');

-- MAPLE BEAR CANADIAN SCHOOL BELO HORIZONTE (BELO HORIZONTE)
UPDATE schools SET inep_code = '345644' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'MAPLE BEAR CANADIAN SCHOOL BELO HORIZONTE' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '345644');

-- POLITEC MG - ESCOLA POLITÉCNICA MG (BELO HORIZONTE)
UPDATE schools SET inep_code = '312371' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'POLITEC MG - ESCOLA POLITÉCNICA MG' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312371');

-- PROZ - UNIDADE BELO HORIZONTE (BELO HORIZONTE)
UPDATE schools SET inep_code = '353329' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'PROZ - UNIDADE BELO HORIZONTE' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '353329');

-- REDE M2 - JOÃO PINHEIRO (BELO HORIZONTE)
UPDATE schools SET inep_code = '377686' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'REDE M2 - JOÃO PINHEIRO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '377686');

-- SENAC UNIDADE DE ENSINO TECNICO - CFP BELO HORIZONTE (BELO HORIZONTE)
UPDATE schools SET inep_code = '262641' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAC UNIDADE DE ENSINO TECNICO - CFP BELO HORIZONTE' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '262641');

-- SENAI BELO HORIZONTE CFP NANSEN ARAÚJO (BELO HORIZONTE)
UPDATE schools SET inep_code = '380644' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI BELO HORIZONTE CFP NANSEN ARAÚJO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '380644');

-- SENAI C AUTOMOT FORM PROFISSIONAL (BELO HORIZONTE)
UPDATE schools SET inep_code = '267678' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI C AUTOMOT FORM PROFISSIONAL' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '267678');

-- SENAI C DE DESEN TECNOLÓGICO PARA O VESTUÁRIO (BELO HORIZONTE)
UPDATE schools SET inep_code = '329614' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI C DE DESEN TECNOLÓGICO PARA O VESTUÁRIO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '329614');

-- SENAI CENTRO DE FORMAÇÃO PROFISSIONAL SÉRGIO FREITAS PACHECO CECOTEG (BELO HORIZONTE)
UPDATE schools SET inep_code = '274682' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI CENTRO DE FORMAÇÃO PROFISSIONAL SÉRGIO FREITAS PACHECO CECOTEG' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '274682');

-- SENAI- CENTRO TECNOLÓGICO CÉSAR RODRIGUES (BELO HORIZONTE)
UPDATE schools SET inep_code = '267589' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI- CENTRO TECNOLÓGICO CÉSAR RODRIGUES' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '267589');

-- ESCOLA MARIA SENHORINHA DE LIMA (BELO VALE)
UPDATE schools SET inep_code = '365475' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA MARIA SENHORINHA DE LIMA' AND UPPER(TRIM(city)) = 'BELO VALE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '365475');

-- CENTRO EDUCACIONAL CECÍLIA MARIA DE MELO BARCELOS (BRUMADINHO)
UPDATE schools SET inep_code = '329606' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL CECÍLIA MARIA DE MELO BARCELOS' AND UPPER(TRIM(city)) = 'BRUMADINHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '329606');

-- CENTRO EDUCACIONAL MARIA MADALENA FRICHE PASSOS - CEMMA (BRUMADINHO)
UPDATE schools SET inep_code = '223131' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL MARIA MADALENA FRICHE PASSOS - CEMMA' AND UPPER(TRIM(city)) = 'BRUMADINHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '223131');

-- ESCOLA SISTEMA PEDAGÓGICO SEMEAR (BRUMADINHO)
UPDATE schools SET inep_code = '279277' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SISTEMA PEDAGÓGICO SEMEAR' AND UPPER(TRIM(city)) = 'BRUMADINHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '279277');

-- CENTRO DE FORMAÇÃO PROFISSIONAL DA FEC (CAETÉ)
UPDATE schools SET inep_code = '319996' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE FORMAÇÃO PROFISSIONAL DA FEC' AND UPPER(TRIM(city)) = 'CAETÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '319996');

-- ESCOLA DE ENFERMAGEM FLORENCE NIGHTINGALE (CAETÉ)
UPDATE schools SET inep_code = '293954' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DE ENFERMAGEM FLORENCE NIGHTINGALE' AND UPPER(TRIM(city)) = 'CAETÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '293954');

-- INSTITUTO EDUCACIONAL E PSICOPEDAGÓGICO SENA FIGUEIREDO (CAETÉ)
UPDATE schools SET inep_code = '278530' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL E PSICOPEDAGÓGICO SENA FIGUEIREDO' AND UPPER(TRIM(city)) = 'CAETÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '278530');

-- NÚCLEO COMUNITÁRIO EDUCACIONAL DE CAETÉ (CAETÉ)
UPDATE schools SET inep_code = '279552' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'NÚCLEO COMUNITÁRIO EDUCACIONAL DE CAETÉ' AND UPPER(TRIM(city)) = 'CAETÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '279552');

-- ARACÊ ESCOLA (NOVA LIMA)
UPDATE schools SET inep_code = '369357' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ARACÊ ESCOLA' AND UPPER(TRIM(city)) = 'NOVA LIMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369357');

-- CENTRO DE FORMAÇÃO PROFISSIONAL AFONSO GRECO-SENAI (NOVA LIMA)
UPDATE schools SET inep_code = '315931' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE FORMAÇÃO PROFISSIONAL AFONSO GRECO-SENAI' AND UPPER(TRIM(city)) = 'NOVA LIMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '315931');

-- CENTRO EDUCACIONAL SÃO TOMÁS DE AQUINO (NOVA LIMA)
UPDATE schools SET inep_code = '229865' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL SÃO TOMÁS DE AQUINO' AND UPPER(TRIM(city)) = 'NOVA LIMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '229865');

-- COLÉGIO BATISTA MINEIRO - UNIDADE ALPHAVILLE NOVA LIMA (NOVA LIMA)
UPDATE schools SET inep_code = '354600' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO BATISTA MINEIRO - UNIDADE ALPHAVILLE NOVA LIMA' AND UPPER(TRIM(city)) = 'NOVA LIMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '354600');

-- COLÉGIO SANTO AGOSTINHO - UNIDADE NOVA LIMA (NOVA LIMA)
UPDATE schools SET inep_code = '333921' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SANTO AGOSTINHO - UNIDADE NOVA LIMA' AND UPPER(TRIM(city)) = 'NOVA LIMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '333921');

-- COLEGUIUM - UNIDADE JARDIM CANADÁ (NOVA LIMA)
UPDATE schools SET inep_code = '341550' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLEGUIUM - UNIDADE JARDIM CANADÁ' AND UPPER(TRIM(city)) = 'NOVA LIMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '341550');

-- ESCOLA DE FORMAÇÃO GERENCIAL NOVA LIMA - METODOLOGIA SEBRAE (NOVA LIMA)
UPDATE schools SET inep_code = '276413' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DE FORMAÇÃO GERENCIAL NOVA LIMA - METODOLOGIA SEBRAE' AND UPPER(TRIM(city)) = 'NOVA LIMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '276413');

-- ESCOLA INTERNACIONAL DE FORMAÇÃO GERENCIAL (NOVA LIMA)
UPDATE schools SET inep_code = '249548' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA INTERNACIONAL DE FORMAÇÃO GERENCIAL' AND UPPER(TRIM(city)) = 'NOVA LIMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '249548');

-- ESCOLA MAPLE BEAR ALPHAVILLE LAGOA DOS INGLESES (NOVA LIMA)
UPDATE schools SET inep_code = '354473' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA MAPLE BEAR ALPHAVILLE LAGOA DOS INGLESES' AND UPPER(TRIM(city)) = 'NOVA LIMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '354473');

-- FUNDAÇÃO DE EDUCAÇÃO PARA O TRABALHO DE MINAS GERAIS-UTRAMIG (NOVA LIMA)
UPDATE schools SET inep_code = '345024' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'FUNDAÇÃO DE EDUCAÇÃO PARA O TRABALHO DE MINAS GERAIS-UTRAMIG' AND UPPER(TRIM(city)) = 'NOVA LIMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '345024');

-- INSTITUTO CÁSSIO MAGNANI (NOVA LIMA)
UPDATE schools SET inep_code = '266655' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO CÁSSIO MAGNANI' AND UPPER(TRIM(city)) = 'NOVA LIMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '266655');

-- INSTITUTO CÁSSIO MAGNANI - UNIDADE II (NOVA LIMA)
UPDATE schools SET inep_code = '378453' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO CÁSSIO MAGNANI - UNIDADE II' AND UPPER(TRIM(city)) = 'NOVA LIMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '378453');

-- INSTITUTO ÍTALO BRASILEIRO BICULTURAL (NOVA LIMA)
UPDATE schools SET inep_code = '249483' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO ÍTALO BRASILEIRO BICULTURAL' AND UPPER(TRIM(city)) = 'NOVA LIMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '249483');

-- INSTITUTO OURO VERDE (NOVA LIMA)
UPDATE schools SET inep_code = '356700' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO OURO VERDE' AND UPPER(TRIM(city)) = 'NOVA LIMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '356700');

-- PÓLEN ESCOLA WALDORF (NOVA LIMA)
UPDATE schools SET inep_code = '255190' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'PÓLEN ESCOLA WALDORF' AND UPPER(TRIM(city)) = 'NOVA LIMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '255190');

-- COLÉGIO VILLA REAL (SABARÁ)
UPDATE schools SET inep_code = '293423' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO VILLA REAL' AND UPPER(TRIM(city)) = 'SABARÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '293423');

-- ESCOLA SESI HANS SCHLACHER (SABARÁ)
UPDATE schools SET inep_code = '259730' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SESI HANS SCHLACHER' AND UPPER(TRIM(city)) = 'SABARÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '259730');

-- INSTITUTO CLUBE DO MICKEY (SABARÁ)
UPDATE schools SET inep_code = '229784' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO CLUBE DO MICKEY' AND UPPER(TRIM(city)) = 'SABARÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '229784');

-- SENAI -  CENTRO DE FORMAÇÃO PROFISSIONAL MICHEL MICHELS (SABARÁ)
UPDATE schools SET inep_code = '298999' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI -  CENTRO DE FORMAÇÃO PROFISSIONAL MICHEL MICHELS' AND UPPER(TRIM(city)) = 'SABARÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '298999');

-- CENTRO PEDAGÓGICO CECÍLIA MEIRELES (SANTA BÁRBARA)
UPDATE schools SET inep_code = '261394' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO PEDAGÓGICO CECÍLIA MEIRELES' AND UPPER(TRIM(city)) = 'SANTA BÁRBARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '261394');

-- SEPRO- SISTEMA DE EDUCAÇÃO PROFISSIONAL DE ITABIRA (SANTA BÁRBARA)
UPDATE schools SET inep_code = '348970' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SEPRO- SISTEMA DE EDUCAÇÃO PROFISSIONAL DE ITABIRA' AND UPPER(TRIM(city)) = 'SANTA BÁRBARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '348970');

-- ATOS SCHOOL EDUCACIONAL (BELO HORIZONTE)
UPDATE schools SET inep_code = '368105' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ATOS SCHOOL EDUCACIONAL' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368105');

-- CECON-TI-CENTRO EDUCACIONAL DE TECNOLOGIA DA INFORMAÇÃO (BELO HORIZONTE)
UPDATE schools SET inep_code = '348732' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CECON-TI-CENTRO EDUCACIONAL DE TECNOLOGIA DA INFORMAÇÃO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '348732');

-- CEMA - CENTRO EDUCACIONAL MARIA APARECIDA (BELO HORIZONTE)
UPDATE schools SET inep_code = '332429' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CEMA - CENTRO EDUCACIONAL MARIA APARECIDA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '332429');

-- CEMAR -CENTRO EDUCACIONAL MÁRIO RABELO - UNIDADE I (BELO HORIZONTE)
UPDATE schools SET inep_code = '257427' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CEMAR -CENTRO EDUCACIONAL MÁRIO RABELO - UNIDADE I' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '257427');

-- CENTRO DE ENSINO TÉCNICO DE MINAS GERAIS - TECMIG (BELO HORIZONTE)
UPDATE schools SET inep_code = '373567' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE ENSINO TÉCNICO DE MINAS GERAIS - TECMIG' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '373567');

-- CENTRO DE FORMAÇÃO PROFISSIONAL EM SECRETARIADO DE MINAS GERAIS - CEFPROSEMG (BELO HORIZONTE)
UPDATE schools SET inep_code = '350893' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE FORMAÇÃO PROFISSIONAL EM SECRETARIADO DE MINAS GERAIS - CEFPROSEMG' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '350893');

-- CENTRO EDUCACIONAL PIAGET I (BELO HORIZONTE)
UPDATE schools SET inep_code = '297453' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL PIAGET I' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '297453');

-- COL CHROMOS BURITIS (BELO HORIZONTE)
UPDATE schools SET inep_code = '373990' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COL CHROMOS BURITIS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '373990');

-- COL CHROMOS SERRANO (BELO HORIZONTE)
UPDATE schools SET inep_code = '257397' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COL CHROMOS SERRANO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '257397');

-- COLÉGIO ABGAR RENAULT - UNIDADE GLÓRIA (BELO HORIZONTE)
UPDATE schools SET inep_code = '253995' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ABGAR RENAULT - UNIDADE GLÓRIA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253995');

-- COLÉGIO ADVENTISTA DO BURITIS (BELO HORIZONTE)
UPDATE schools SET inep_code = '377503' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ADVENTISTA DO BURITIS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '377503');

-- COLÉGIO BATISTA MINEIRO -  UNIDADE BURITIS II (BELO HORIZONTE)
UPDATE schools SET inep_code = '329282' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO BATISTA MINEIRO -  UNIDADE BURITIS II' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '329282');

-- COLÉGIO BATISTA MINEIRO-UNIDADE BURITIS (BELO HORIZONTE)
UPDATE schools SET inep_code = '354007' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO BATISTA MINEIRO-UNIDADE BURITIS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '354007');

-- COLÉGIO BURITIS AGOSTINIANO (BELO HORIZONTE)
UPDATE schools SET inep_code = '294110' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO BURITIS AGOSTINIANO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '294110');

-- COLÉGIO CAMINHAR BH (BELO HORIZONTE)
UPDATE schools SET inep_code = '308943' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CAMINHAR BH' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '308943');

-- COLÉGIO CEAPS (BELO HORIZONTE)
UPDATE schools SET inep_code = '321621' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CEAPS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '321621');

-- COLÉGIO CHROMOS BARREIRO (BELO HORIZONTE)
UPDATE schools SET inep_code = '369977' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CHROMOS BARREIRO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369977');

-- COLÉGIO CORAÇÃO DE ESTUDANTE (BELO HORIZONTE)
UPDATE schools SET inep_code = '267511' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CORAÇÃO DE ESTUDANTE' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '267511');

-- COLÉGIO CORAÇÃO DE ESTUDANTE - UNIDADE SANTA CRUZ (BELO HORIZONTE)
UPDATE schools SET inep_code = '294047' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CORAÇÃO DE ESTUDANTE - UNIDADE SANTA CRUZ' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '294047');

-- COLÉGIO CRISTÃO ATOS (BELO HORIZONTE)
UPDATE schools SET inep_code = '319341' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CRISTÃO ATOS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '319341');

-- COLÉGIO CRISTO REDENTOR (BELO HORIZONTE)
UPDATE schools SET inep_code = '329908' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CRISTO REDENTOR' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '329908');

-- COLÉGIO DIMENSÃO (BELO HORIZONTE)
UPDATE schools SET inep_code = '220329' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DIMENSÃO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '220329');

-- COLÉGIO DIVERSITAS (BELO HORIZONTE)
UPDATE schools SET inep_code = '292982' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DIVERSITAS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '292982');

-- COLÉGIO EMAÚS (BELO HORIZONTE)
UPDATE schools SET inep_code = '354813' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO EMAÚS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '354813');

-- COLÉGIO JEAN PIAGET (BELO HORIZONTE)
UPDATE schools SET inep_code = '305057' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO JEAN PIAGET' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305057');

-- COLÉGIO JOÃO DE BARRO (BELO HORIZONTE)
UPDATE schools SET inep_code = '257656' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO JOÃO DE BARRO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '257656');

-- COLÉGIO LE PETIT (BELO HORIZONTE)
UPDATE schools SET inep_code = '327638' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO LE PETIT' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '327638');

-- COLÉGIO LOS ANGELOS - IPLAS (BELO HORIZONTE)
UPDATE schools SET inep_code = '321613' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO LOS ANGELOS - IPLAS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '321613');

-- COLÉGIO MASTER PIMENTINHA (BELO HORIZONTE)
UPDATE schools SET inep_code = '257877' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MASTER PIMENTINHA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '257877');

-- COLÉGIO METRÓPOLE (BELO HORIZONTE)
UPDATE schools SET inep_code = '320889' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO METRÓPOLE' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '320889');

-- COLÉGIO PENTÁGONO (BELO HORIZONTE)
UPDATE schools SET inep_code = '297879' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PENTÁGONO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '297879');

-- COLÉGIO SABIRACEMA (BELO HORIZONTE)
UPDATE schools SET inep_code = '315052' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SABIRACEMA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '315052');

-- COLÉGIO SANTA MARIA MINAS - UNIDADE NOVA SUIÇA (BELO HORIZONTE)
UPDATE schools SET inep_code = '244457' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SANTA MARIA MINAS - UNIDADE NOVA SUIÇA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '244457');

-- COLÉGIO SANTO AGOSTINHO - UNIDADE GUTIERREZ (BELO HORIZONTE)
UPDATE schools SET inep_code = '370711' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SANTO AGOSTINHO - UNIDADE GUTIERREZ' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '370711');

-- COLÉGIO SES (BELO HORIZONTE)
UPDATE schools SET inep_code = '346420' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SES' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346420');

-- COLEGUIUM - UNIDADE ALÍPIO DE MELO (BELO HORIZONTE)
UPDATE schools SET inep_code = '358428' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLEGUIUM - UNIDADE ALÍPIO DE MELO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '358428');

-- COLEGUIUM - UNIDADE BURITIS (BELO HORIZONTE)
UPDATE schools SET inep_code = '368342' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLEGUIUM - UNIDADE BURITIS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368342');

-- COLEGUIUM - UNIDADE CARLOS PRATES (BELO HORIZONTE)
UPDATE schools SET inep_code = '358541' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLEGUIUM - UNIDADE CARLOS PRATES' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '358541');

-- COLEGUIUM - UNIDADE GUTIERREZ III (BELO HORIZONTE)
UPDATE schools SET inep_code = '364860' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLEGUIUM - UNIDADE GUTIERREZ III' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '364860');

-- COLEGUIUM - UNIDADE NOVA SUÍÇA (BELO HORIZONTE)
UPDATE schools SET inep_code = '377759' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLEGUIUM - UNIDADE NOVA SUÍÇA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '377759');

-- EDUCANDÁRIO ESTRELAS DO FUTURO (BELO HORIZONTE)
UPDATE schools SET inep_code = '273244' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EDUCANDÁRIO ESTRELAS DO FUTURO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '273244');

-- ESCOLA AMERICANA DE BELO HORIZONTE (BELO HORIZONTE)
UPDATE schools SET inep_code = '244074' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA AMERICANA DE BELO HORIZONTE' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '244074');

-- ESCOLA CANTO VERDE (BELO HORIZONTE)
UPDATE schools SET inep_code = '298069' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA CANTO VERDE' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '298069');

-- ESCOLA DE ENFERMAGEM SOUZA CASTRO (BELO HORIZONTE)
UPDATE schools SET inep_code = '299138' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DE ENFERMAGEM SOUZA CASTRO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '299138');

-- ESCOLA DO SEBRAE (BELO HORIZONTE)
UPDATE schools SET inep_code = '244023' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DO SEBRAE' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '244023');

-- ESCOLA GRAÇA MAIOR (BELO HORIZONTE)
UPDATE schools SET inep_code = '297887' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA GRAÇA MAIOR' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '297887');

-- ESCOLA POLITÉCNICA DE MINAS GERAIS - POLIMIG - UNIDADE III (BELO HORIZONTE)
UPDATE schools SET inep_code = '245925' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA POLITÉCNICA DE MINAS GERAIS - POLIMIG - UNIDADE III' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '245925');

-- ESCOLA POLITÉCNICA DE MINAS GERIAS - POLIMIG - UNIDADE VI (BELO HORIZONTE)
UPDATE schools SET inep_code = '372374' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA POLITÉCNICA DE MINAS GERIAS - POLIMIG - UNIDADE VI' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '372374');

-- ESCOLA SEB UINIMASTER (BELO HORIZONTE)
UPDATE schools SET inep_code = '309711' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SEB UINIMASTER' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '309711');

-- ESCOLA SESI  GENERAL ONÉSIMO BECKER DE  ARAÚJO (BELO HORIZONTE)
UPDATE schools SET inep_code = '246450' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SESI  GENERAL ONÉSIMO BECKER DE  ARAÚJO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246450');

-- GRAU TÉCNICO ALÍPIO DE MELO (BELO HORIZONTE)
UPDATE schools SET inep_code = '377856' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'GRAU TÉCNICO ALÍPIO DE MELO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '377856');

-- GRAU TÉCNICO BARREIRO (BELO HORIZONTE)
UPDATE schools SET inep_code = '373230' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'GRAU TÉCNICO BARREIRO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '373230');

-- IEB INSTITUTO EDUCACIONAL BELO HORIZONTE (BELO HORIZONTE)
UPDATE schools SET inep_code = '337765' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'IEB INSTITUTO EDUCACIONAL BELO HORIZONTE' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '337765');

-- INSTITUTO DE EDUCAÇÃO TEMPO DE DESCOBRIR (BELO HORIZONTE)
UPDATE schools SET inep_code = '357235' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO DE EDUCAÇÃO TEMPO DE DESCOBRIR' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '357235');

-- INSTITUTO EDUCACIONAL BAIÃO SANTOS (BELO HORIZONTE)
UPDATE schools SET inep_code = '210102' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL BAIÃO SANTOS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '210102');

-- INSTITUTO EDUCACIONAL GABRIELA LEOPOLDINA (BELO HORIZONTE)
UPDATE schools SET inep_code = '217166' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL GABRIELA LEOPOLDINA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217166');

-- INSTITUTO EDUCACIONAL MARIA MORATO (BELO HORIZONTE)
UPDATE schools SET inep_code = '303682' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL MARIA MORATO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '303682');

-- INSTITUTO MODAL (BELO HORIZONTE)
UPDATE schools SET inep_code = '292753' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO MODAL' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '292753');

-- INSTITUTO SANTA PAULA (BELO HORIZONTE)
UPDATE schools SET inep_code = '262251' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO SANTA PAULA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '262251');

-- INSTITUTO TÉCNICO INOVAR (BELO HORIZONTE)
UPDATE schools SET inep_code = '261696' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO TÉCNICO INOVAR' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '261696');

-- META - ESCOLA TÉCNICA DE FORMAÇÃO PROFISSIONAL (BELO HORIZONTE)
UPDATE schools SET inep_code = '324027' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'META - ESCOLA TÉCNICA DE FORMAÇÃO PROFISSIONAL' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '324027');

-- REDE M2 - PRADO (BELO HORIZONTE)
UPDATE schools SET inep_code = '374865' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'REDE M2 - PRADO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '374865');

-- SENAI- CENTRO DE FORMAÇÃO PROFISSIONAL AMÉRICO RENÉ GIANNETTI (BELO HORIZONTE)
UPDATE schools SET inep_code = '267571' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI- CENTRO DE FORMAÇÃO PROFISSIONAL AMÉRICO RENÉ GIANNETTI' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '267571');

-- SENAI CENTRO DE FORMAÇÃO PROFISSIONAL PAULO TARSO (BELO HORIZONTE)
UPDATE schools SET inep_code = '309648' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI CENTRO DE FORMAÇÃO PROFISSIONAL PAULO TARSO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '309648');

-- SIC - ESCOLA  PROFISSIONALIZANTE SANTO AGOSTINHO (BELO HORIZONTE)
UPDATE schools SET inep_code = '324663' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SIC - ESCOLA  PROFISSIONALIZANTE SANTO AGOSTINHO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '324663');

-- SISTEMA ÁPICE DE ENSINO (BELO HORIZONTE)
UPDATE schools SET inep_code = '256889' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SISTEMA ÁPICE DE ENSINO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '256889');

-- SISTEMA EDUCACIONAL ATHENA - UNIDADE MUNDO DA CRIANÇA (BELO HORIZONTE)
UPDATE schools SET inep_code = '309184' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SISTEMA EDUCACIONAL ATHENA - UNIDADE MUNDO DA CRIANÇA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '309184');

-- CEB- CENTRO EDUCACIONAL DE BETIM (BETIM)
UPDATE schools SET inep_code = '334502' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CEB- CENTRO EDUCACIONAL DE BETIM' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '334502');

-- CENTRO TECNOLÓGICO DE MECATRÔNICA MARIA MADALENA NOGUEIRA- SENAI (BETIM)
UPDATE schools SET inep_code = '267775' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO TECNOLÓGICO DE MECATRÔNICA MARIA MADALENA NOGUEIRA- SENAI' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '267775');

-- COLÉGIO EDUCARE DE BETIM (BETIM)
UPDATE schools SET inep_code = '235555' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO EDUCARE DE BETIM' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '235555');

-- COLÉGIO NEUZA DUTRA (BETIM)
UPDATE schools SET inep_code = '276651' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO NEUZA DUTRA' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '276651');

-- COLÉGIO SANTA MARIA MINAS - UNIDADE BETIM (BETIM)
UPDATE schools SET inep_code = '353906' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SANTA MARIA MINAS - UNIDADE BETIM' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '353906');

-- COLÉGIO SANTIAGO (BETIM)
UPDATE schools SET inep_code = '320510' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SANTIAGO' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '320510');

-- COLÉGIO SONHO MEU (BETIM)
UPDATE schools SET inep_code = '267465' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SONHO MEU' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '267465');

-- COLÉGIO TÉCNICO GENOMA (BETIM)
UPDATE schools SET inep_code = '321893' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TÉCNICO GENOMA' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '321893');

-- COLÉGIO TÉCNICO IMEC (BETIM)
UPDATE schools SET inep_code = '354643' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TÉCNICO IMEC' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '354643');

-- ECOTEC (BETIM)
UPDATE schools SET inep_code = '344893' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ECOTEC' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '344893');

-- ESCOLA SESI MARIA MADALENA NOGUEIRA (BETIM)
UPDATE schools SET inep_code = '365114' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SESI MARIA MADALENA NOGUEIRA' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '365114');

-- GRAU TÉCNICO BETIM (BETIM)
UPDATE schools SET inep_code = '381136' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'GRAU TÉCNICO BETIM' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '381136');

-- IMEC BETIM (BETIM)
UPDATE schools SET inep_code = '370215' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'IMEC BETIM' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '370215');

-- INSTITUTO EDUCACIONAL DÉBORA ROCHA (BETIM)
UPDATE schools SET inep_code = '324761' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL DÉBORA ROCHA' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '324761');

-- INSTITUTO EDUCACIONAL GESTALD (BETIM)
UPDATE schools SET inep_code = '323764' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL GESTALD' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '323764');

-- INSTITUTO EDUCACIONAL MARRIAN (BETIM)
UPDATE schools SET inep_code = '223123' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL MARRIAN' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '223123');

-- INSTITUTO OLIVEIRA LARA - UNIDADE CRESCER DE ENSINO (BETIM)
UPDATE schools SET inep_code = '328014' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO OLIVEIRA LARA - UNIDADE CRESCER DE ENSINO' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '328014');

-- INSTITUTO RAIO DE SOL (BETIM)
UPDATE schools SET inep_code = '324396' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO RAIO DE SOL' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '324396');

-- IPAC- INSTITUTO PATRÍCIA CARVALHO (BETIM)
UPDATE schools SET inep_code = '294241' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'IPAC- INSTITUTO PATRÍCIA CARVALHO' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '294241');

-- SENAC - UNIDADE DE ENSINO TÉCNICO DO CEP BETIM (BETIM)
UPDATE schools SET inep_code = '358207' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAC - UNIDADE DE ENSINO TÉCNICO DO CEP BETIM' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '358207');

-- CCV - COLÉGIO CRISTÃO VITÓRIA (CONTAGEM)
UPDATE schools SET inep_code = '321818' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CCV - COLÉGIO CRISTÃO VITÓRIA' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '321818');

-- CEMAR CENTRO EDUCACIONAL MÁRIO RABELO - UNIDADE II (CONTAGEM)
UPDATE schools SET inep_code = '310891' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CEMAR CENTRO EDUCACIONAL MÁRIO RABELO - UNIDADE II' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310891');

-- CENAD - CENTRO DE APRENDIZAGEM E DESENVOLVIMENTO PROFISSIONAL (CONTAGEM)
UPDATE schools SET inep_code = '375683' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENAD - CENTRO DE APRENDIZAGEM E DESENVOLVIMENTO PROFISSIONAL' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '375683');

-- CENTRO DE EDUCAÇÃO INFANTIL MÉRITO (CONTAGEM)
UPDATE schools SET inep_code = '279803' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE EDUCAÇÃO INFANTIL MÉRITO' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '279803');

-- CENTRO DE EXCELÊNCIA INTEGRADO AVANÇAR - CEIAV - UNIDADE II (CONTAGEM)
UPDATE schools SET inep_code = '380008' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE EXCELÊNCIA INTEGRADO AVANÇAR - CEIAV - UNIDADE II' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '380008');

-- CENTRO EDUCACIONAL VASCONCELOS (CONTAGEM)
UPDATE schools SET inep_code = '329240' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL VASCONCELOS' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '329240');

-- CENTRO EXCELÊNCIA INTEGRADO AVANÇAR - CEIAV (CONTAGEM)
UPDATE schools SET inep_code = '319767' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EXCELÊNCIA INTEGRADO AVANÇAR - CEIAV' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '319767');

-- CENTRO INTEGRADO SESI/SENAI DONA NENÉM  SCARIOLLI (CONTAGEM)
UPDATE schools SET inep_code = '349429' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO INTEGRADO SESI/SENAI DONA NENÉM  SCARIOLLI' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349429');

-- CESBOC CENTRO EDUCACIONAL PROFISSIONALIZANTE (CONTAGEM)
UPDATE schools SET inep_code = '343897' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESBOC CENTRO EDUCACIONAL PROFISSIONALIZANTE' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '343897');

-- CESIR- CENTRO EDUCACIONAL SILVEIRA ROCHA (CONTAGEM)
UPDATE schools SET inep_code = '313777' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESIR- CENTRO EDUCACIONAL SILVEIRA ROCHA' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '313777');

-- COLÉGIO AGOSTINIANO FREI CARLOS VICUÑA (CONTAGEM)
UPDATE schools SET inep_code = '354090' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO AGOSTINIANO FREI CARLOS VICUÑA' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '354090');

-- COLÉGIO BATISTA REMANESCENTES (CONTAGEM)
UPDATE schools SET inep_code = '330205' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO BATISTA REMANESCENTES' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '330205');

-- COLÉGIO CEC (CONTAGEM)
UPDATE schools SET inep_code = '277673' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CEC' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '277673');

-- COLÉGIO CEIAS (CONTAGEM)
UPDATE schools SET inep_code = '319741' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CEIAS' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '319741');

-- COLÉGIO CHROMOS ELDORADO (CONTAGEM)
UPDATE schools SET inep_code = '357120' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CHROMOS ELDORADO' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '357120');

-- COLÉGIO CONSTRUIR (CONTAGEM)
UPDATE schools SET inep_code = '329819' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CONSTRUIR' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '329819');

-- COLÉGIO CRESCER (CONTAGEM)
UPDATE schools SET inep_code = '277177' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CRESCER' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '277177');

-- COLÉGIO ESPÍRITA PROFESSOR RUBENS COSTA ROMANELLI (CONTAGEM)
UPDATE schools SET inep_code = '236926' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ESPÍRITA PROFESSOR RUBENS COSTA ROMANELLI' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '236926');

-- COLÉGIO GLÓRIA ANDRADE (CONTAGEM)
UPDATE schools SET inep_code = '260916' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO GLÓRIA ANDRADE' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '260916');

-- COLÉGIO KELLY MIRANDA (CONTAGEM)
UPDATE schools SET inep_code = '262676' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO KELLY MIRANDA' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '262676');

-- COLÉGIO NIÉDE GUIDON (CONTAGEM)
UPDATE schools SET inep_code = '376310' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO NIÉDE GUIDON' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '376310');

-- COLÉGIO PAULO FREIRE - UNIDADE NOVO PROGRESSO (CONTAGEM)
UPDATE schools SET inep_code = '279099' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PAULO FREIRE - UNIDADE NOVO PROGRESSO' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '279099');

-- COLÉGIO RAFAEL BRITO (CONTAGEM)
UPDATE schools SET inep_code = '261297' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO RAFAEL BRITO' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '261297');

-- COLÉGIO SAGRADO CORAÇÃO DE JESUS (CONTAGEM)
UPDATE schools SET inep_code = '265578' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SAGRADO CORAÇÃO DE JESUS' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '265578');

-- COLÉGIO SÃO GERALDO (CONTAGEM)
UPDATE schools SET inep_code = '279102' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SÃO GERALDO' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '279102');

-- COLÉGIO SÃO PEDRO DO VATICANO (CONTAGEM)
UPDATE schools SET inep_code = '323730' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SÃO PEDRO DO VATICANO' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '323730');

-- COLÉGIO SÓCRATES (CONTAGEM)
UPDATE schools SET inep_code = '269395' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SÓCRATES' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '269395');

-- COLÉGIO SUPREMO (CONTAGEM)
UPDATE schools SET inep_code = '329258' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SUPREMO' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '329258');

-- COLÉGIO TÉCNICO JK (CONTAGEM)
UPDATE schools SET inep_code = '354066' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TÉCNICO JK' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '354066');

-- ESCOLA PROFISSIONALIZANTE SANTA RITA DE CÁSSIA (CONTAGEM)
UPDATE schools SET inep_code = '276952' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA PROFISSIONALIZANTE SANTA RITA DE CÁSSIA' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '276952');

-- FACULDADE SENAC MINAS CONTAGEM (CONTAGEM)
UPDATE schools SET inep_code = '359998' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'FACULDADE SENAC MINAS CONTAGEM' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '359998');

-- FOCUS ESCOLA TÉCNICA (CONTAGEM)
UPDATE schools SET inep_code = '323080' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'FOCUS ESCOLA TÉCNICA' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '323080');

-- GAMA ESCOLA TÉCNICA E PROFISSIONALIZANTE (CONTAGEM)
UPDATE schools SET inep_code = '340570' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'GAMA ESCOLA TÉCNICA E PROFISSIONALIZANTE' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '340570');

-- GRAU TÉCNICO CONTAGEM (CONTAGEM)
UPDATE schools SET inep_code = '373257' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'GRAU TÉCNICO CONTAGEM' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '373257');

-- GRAU TÉCNICO CONTAGEM - UNIDADE II (CONTAGEM)
UPDATE schools SET inep_code = '376876' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'GRAU TÉCNICO CONTAGEM - UNIDADE II' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '376876');

-- INSTITUTO EDUCACIOANL UMBERTO CORRÊA (CONTAGEM)
UPDATE schools SET inep_code = '274208' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIOANL UMBERTO CORRÊA' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '274208');

-- INSTITUTO EDUCACIONAL EBENEZER (CONTAGEM)
UPDATE schools SET inep_code = '223204' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL EBENEZER' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '223204');

-- INSTITUTO EDUCACIONAL LIBERTAS (CONTAGEM)
UPDATE schools SET inep_code = '327077' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL LIBERTAS' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '327077');

-- INSTITUTO EDUCACIONAL MONTEIRO LOBATO (CONTAGEM)
UPDATE schools SET inep_code = '291811' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL MONTEIRO LOBATO' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '291811');