-- INSTITUTO EDUCACIONAL NÍDIA ZENHA (CONTAGEM)
UPDATE schools SET inep_code = '269913' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL NÍDIA ZENHA' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '269913');

-- INSTITUTO EROS GUSTAVO (CONTAGEM)
UPDATE schools SET inep_code = '236934' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EROS GUSTAVO' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '236934');

-- INSTITUTO HELENA FERNANDES (CONTAGEM)
UPDATE schools SET inep_code = '329452' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO HELENA FERNANDES' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '329452');

-- INSTITUTO PEDAGÓGICO TEREZA CRISTINA (CONTAGEM)
UPDATE schools SET inep_code = '229857' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO PEDAGÓGICO TEREZA CRISTINA' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '229857');

-- INSTITUTO PETILANDIA (CONTAGEM)
UPDATE schools SET inep_code = '365637' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO PETILANDIA' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '365637');

-- INSTUTO EDUCACIONAL NOVOS TEMPOS (CONTAGEM)
UPDATE schools SET inep_code = '267007' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTUTO EDUCACIONAL NOVOS TEMPOS' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '267007');

-- NEFC - NÚCLEO EDUCACIONAL FRANCISCA CAMPOS (CONTAGEM)
UPDATE schools SET inep_code = '278572' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'NEFC - NÚCLEO EDUCACIONAL FRANCISCA CAMPOS' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '278572');

-- NÚCLEO EDUCACIONAL BRAZ NETTO (CONTAGEM)
UPDATE schools SET inep_code = '277185' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'NÚCLEO EDUCACIONAL BRAZ NETTO' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '277185');

-- PROZ - UNIDADE CONTAGEM (CONTAGEM)
UPDATE schools SET inep_code = '377155' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'PROZ - UNIDADE CONTAGEM' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '377155');

-- QUATRO ELEMENTOS/ SÍTIO ESCOLA (CONTAGEM)
UPDATE schools SET inep_code = '347612' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'QUATRO ELEMENTOS/ SÍTIO ESCOLA' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '347612');

-- SEBRAE- ESCOLA DE FORMAÇÃO GERENCIAL - CONTAGEM (CONTAGEM)
UPDATE schools SET inep_code = '262382' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SEBRAE- ESCOLA DE FORMAÇÃO GERENCIAL - CONTAGEM' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '262382');

-- SEMEAR SCHOLL (CONTAGEM)
UPDATE schools SET inep_code = '333700' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SEMEAR SCHOLL' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '333700');

-- SENAI CENTRO DE FORMAÇÃO PROFISSIONAL EUVALDO LODI (CONTAGEM)
UPDATE schools SET inep_code = '267767' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI CENTRO DE FORMAÇÃO PROFISSIONAL EUVALDO LODI' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '267767');

-- SENAI CENTRO DE TREINAMENTO E DESENVOLVIMENTO DA INDÚSTRIA 4.0 (CONTAGEM)
UPDATE schools SET inep_code = '380610' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI CENTRO DE TREINAMENTO E DESENVOLVIMENTO DA INDÚSTRIA 4.0' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '380610');

-- SENAI CONTAGEM CENTRO DE FORMAÇÃO PROFISSIONAL ALVIMAR CARNEIRO DE REZENDE (CONTAGEM)
UPDATE schools SET inep_code = '357189' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI CONTAGEM CENTRO DE FORMAÇÃO PROFISSIONAL ALVIMAR CARNEIRO DE REZENDE' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '357189');

-- COLÉGIO AVANCE (ESMERALDAS)
UPDATE schools SET inep_code = '342505' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO AVANCE' AND UPPER(TRIM(city)) = 'ESMERALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342505');

-- COLÉGIO BANDEIRAS (IBIRITÉ)
UPDATE schools SET inep_code = '340855' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO BANDEIRAS' AND UPPER(TRIM(city)) = 'IBIRITÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '340855');

-- COLÉGIO CRESCER BUSCAR E MULTIPLICAR - CCBM (IBIRITÉ)
UPDATE schools SET inep_code = '349380' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CRESCER BUSCAR E MULTIPLICAR - CCBM' AND UPPER(TRIM(city)) = 'IBIRITÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349380');

-- COLÉGIO CRISTÃO PREPARANDO PARA O FUTURO (IBIRITÉ)
UPDATE schools SET inep_code = '362670' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CRISTÃO PREPARANDO PARA O FUTURO' AND UPPER(TRIM(city)) = 'IBIRITÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '362670');

-- COLÉGIO ORDEM E PROGRESSO (IBIRITÉ)
UPDATE schools SET inep_code = '313521' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ORDEM E PROGRESSO' AND UPPER(TRIM(city)) = 'IBIRITÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '313521');

-- INSTITUTO CULTURAL SEMPRE JATOBÁ (IBIRITÉ)
UPDATE schools SET inep_code = '293202' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO CULTURAL SEMPRE JATOBÁ' AND UPPER(TRIM(city)) = 'IBIRITÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '293202');

-- INSTITUTO EDUCACIONAL ANA CATARINA (IBIRITÉ)
UPDATE schools SET inep_code = '340847' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL ANA CATARINA' AND UPPER(TRIM(city)) = 'IBIRITÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '340847');

-- INSTITUTO EDUCACIONAL CASTRO ALVES (IBIRITÉ)
UPDATE schools SET inep_code = '237043' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL CASTRO ALVES' AND UPPER(TRIM(city)) = 'IBIRITÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '237043');

-- SENAI IBIRITÉ CENTRO DE FORMAÇÃO PROFISSIONAL PROFESSORA IRENE DE MELO PINHEIRO (IBIRITÉ)
UPDATE schools SET inep_code = '358851' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI IBIRITÉ CENTRO DE FORMAÇÃO PROFISSIONAL PROFESSORA IRENE DE MELO PINHEIRO' AND UPPER(TRIM(city)) = 'IBIRITÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '358851');

-- COLÉGIO TEIXEIRA NETO (IGARAPÉ)
UPDATE schools SET inep_code = '343790' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TEIXEIRA NETO' AND UPPER(TRIM(city)) = 'IGARAPÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '343790');

-- ESCOLA CRESCER (IGARAPÉ)
UPDATE schools SET inep_code = '310107' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA CRESCER' AND UPPER(TRIM(city)) = 'IGARAPÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310107');

-- ESCOLA CRISTÃ VERBO VIVO (SÃO JOAQUIM DE BICAS)
UPDATE schools SET inep_code = '322202' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA CRISTÃ VERBO VIVO' AND UPPER(TRIM(city)) = 'SÃO JOAQUIM DE BICAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322202');

-- SISTEMA DE ENSINO LUCAS NUNES (SÃO JOAQUIM DE BICAS)
UPDATE schools SET inep_code = '323845' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SISTEMA DE ENSINO LUCAS NUNES' AND UPPER(TRIM(city)) = 'SÃO JOAQUIM DE BICAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '323845');

-- COLÉGIO MATTER (SARZEDO)
UPDATE schools SET inep_code = '327263' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MATTER' AND UPPER(TRIM(city)) = 'SARZEDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '327263');

--  CENTRO EDUCACIONAL NOVO PROGRESSO (BELO HORIZONTE)
UPDATE schools SET inep_code = '325317' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL NOVO PROGRESSO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '325317');

-- AQUARELA CENTRO DE EDUCAÇÃO (BELO HORIZONTE)
UPDATE schools SET inep_code = '329541' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'AQUARELA CENTRO DE EDUCAÇÃO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '329541');

-- CENTRO DE EDUCAÇÃO ELO (BELO HORIZONTE)
UPDATE schools SET inep_code = '332020' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE EDUCAÇÃO ELO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '332020');

-- CENTRO DE EDUCAÇÃO MÚLTIPLA (BELO HORIZONTE)
UPDATE schools SET inep_code = '350184' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE EDUCAÇÃO MÚLTIPLA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '350184');

-- CENTRO DE EDUCAÇÃO PROFISSIONAL FILADÉLFIA (BELO HORIZONTE)
UPDATE schools SET inep_code = '319961' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE EDUCAÇÃO PROFISSIONAL FILADÉLFIA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '319961');

-- CENTRO EDUCACIONAL ICM (BELO HORIZONTE)
UPDATE schools SET inep_code = '297798' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL ICM' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '297798');

-- CENTRO EDUCACIONAL SÃO BENTO (BELO HORIZONTE)
UPDATE schools SET inep_code = '378321' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL SÃO BENTO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '378321');

-- COL CHROMOS PAMPULHA (BELO HORIZONTE)
UPDATE schools SET inep_code = '290157' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COL CHROMOS PAMPULHA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '290157');

-- COL CHROMOS PAMPULHA - UNIDADE II (BELO HORIZONTE)
UPDATE schools SET inep_code = '377775' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COL CHROMOS PAMPULHA - UNIDADE II' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '377775');

-- COL CHROMOS VENDA NOVA (BELO HORIZONTE)
UPDATE schools SET inep_code = '246468' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COL CHROMOS VENDA NOVA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246468');

-- COLÉGIO ALCEU COTTA - UNIDADE JARDIM ATLÂNTICO (BELO HORIZONTE)
UPDATE schools SET inep_code = '380342' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ALCEU COTTA - UNIDADE JARDIM ATLÂNTICO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '380342');

-- COLÉGIO ALCEU COTTA - UNIDADE SANTA BRANCA (BELO HORIZONTE)
UPDATE schools SET inep_code = '325554' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ALCEU COTTA - UNIDADE SANTA BRANCA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '325554');

-- COLÉGIO ÂNGULO (BELO HORIZONTE)
UPDATE schools SET inep_code = '370266' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ÂNGULO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '370266');

-- COLÉGIO APRIMORAR (BELO HORIZONTE)
UPDATE schools SET inep_code = '341002' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO APRIMORAR' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '341002');

-- COLÉGIO BATISTA GETSÊMANI (BELO HORIZONTE)
UPDATE schools SET inep_code = '218529' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO BATISTA GETSÊMANI' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218529');

-- COLÉGIO BATISTA MINEIRO - UNIDADE CASTELO (BELO HORIZONTE)
UPDATE schools SET inep_code = '370231' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO BATISTA MINEIRO - UNIDADE CASTELO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '370231');

-- COLÉGIO CAVALIERI (BELO HORIZONTE)
UPDATE schools SET inep_code = '316580' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CAVALIERI' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '316580');

-- COLÉGIO COPBH - UNIDADE II (BELO HORIZONTE)
UPDATE schools SET inep_code = '362417' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO COPBH - UNIDADE II' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '362417');

-- COLÉGIO CRISTÃO EFIGÊNIA TOBIAS (BELO HORIZONTE)
UPDATE schools SET inep_code = '309753' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CRISTÃO EFIGÊNIA TOBIAS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '309753');

-- COLÉGIO DONA CLARA (BELO HORIZONTE)
UPDATE schools SET inep_code = '246051' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DONA CLARA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246051');

-- COLÉGIO DONA CLARA - UNIDADE 2 (BELO HORIZONTE)
UPDATE schools SET inep_code = '379832' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DONA CLARA - UNIDADE 2' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '379832');

-- COLÉGIO ECCELLENTE  - UNIDADE PAMPULHA (BELO HORIZONTE)
UPDATE schools SET inep_code = '355143' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ECCELLENTE  - UNIDADE PAMPULHA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '355143');

-- COLÉGIO HELENA BICALHO (BELO HORIZONTE)
UPDATE schools SET inep_code = '220353' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO HELENA BICALHO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '220353');

-- COLÉGIO INTER AÇÃO (BELO HORIZONTE)
UPDATE schools SET inep_code = '220345' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO INTER AÇÃO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '220345');

-- COLÉGIO INTER AÇÃO UNID II (BELO HORIZONTE)
UPDATE schools SET inep_code = '332780' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO INTER AÇÃO UNID II' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '332780');

-- COLÉGIO M2 - BH (BELO HORIZONTE)
UPDATE schools SET inep_code = '368300' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO M2 - BH' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368300');

-- COLÉGIO MAXIMUS UNIDADE OURO PRETO/CASTELO (BELO HORIZONTE)
UPDATE schools SET inep_code = '361089' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MAXIMUS UNIDADE OURO PRETO/CASTELO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '361089');

-- COLÉGIO PAULO FREIRE (BELO HORIZONTE)
UPDATE schools SET inep_code = '297712' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PAULO FREIRE' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '297712');

-- COLÉGIO REFERÊNCIA (BELO HORIZONTE)
UPDATE schools SET inep_code = '339636' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO REFERÊNCIA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '339636');

-- COLEGIO RUI BARBOSA - UNIDADE II (BELO HORIZONTE)
UPDATE schools SET inep_code = '350648' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLEGIO RUI BARBOSA - UNIDADE II' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '350648');

-- COLÉGIO SANTA AMÉLIA - UNIDADE II (BELO HORIZONTE)
UPDATE schools SET inep_code = '361658' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SANTA AMÉLIA - UNIDADE II' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '361658');

-- COLÉGIO SANTA AMÉLIA-UNIDADE I (BELO HORIZONTE)
UPDATE schools SET inep_code = '333670' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SANTA AMÉLIA-UNIDADE I' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '333670');

-- COLEGUIUM -  UNIDADE OURO PRETO I (BELO HORIZONTE)
UPDATE schools SET inep_code = '217123' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLEGUIUM -  UNIDADE OURO PRETO I' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217123');

-- COLEGUIUM- UNIDADE OURO PRETO II (BELO HORIZONTE)
UPDATE schools SET inep_code = '351725' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLEGUIUM- UNIDADE OURO PRETO II' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '351725');

-- COLEGUIUM UNIDADE SANTA AMÉLIA (BELO HORIZONTE)
UPDATE schools SET inep_code = '322873' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLEGUIUM UNIDADE SANTA AMÉLIA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322873');

-- EDUCAR CENTRO EDUCACIONAL PEDAGÓGICO (BELO HORIZONTE)
UPDATE schools SET inep_code = '298158' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EDUCAR CENTRO EDUCACIONAL PEDAGÓGICO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '298158');

-- ESCOLA ADVENTISTA DA PAMPULHA (BELO HORIZONTE)
UPDATE schools SET inep_code = '376043' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA ADVENTISTA DA PAMPULHA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '376043');

-- ESCOLA CASA FUNDAMENTAL (BELO HORIZONTE)
UPDATE schools SET inep_code = '369780' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA CASA FUNDAMENTAL' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369780');

-- ESCOLA DE ENFERMAGEM DO HOSPITAL EVANGÉLICO (BELO HORIZONTE)
UPDATE schools SET inep_code = '274861' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DE ENFERMAGEM DO HOSPITAL EVANGÉLICO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '274861');

-- ESCOLA EDUCAR - UNIDADE II (BELO HORIZONTE)
UPDATE schools SET inep_code = '365874' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA EDUCAR - UNIDADE II' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '365874');

-- ESCOLA EDUCAR -UNIDADE I (BELO HORIZONTE)
UPDATE schools SET inep_code = '210200' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA EDUCAR -UNIDADE I' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '210200');

-- ESCOLA ENSINANDO - PÓLO PAMPULHA (BELO HORIZONTE)
UPDATE schools SET inep_code = '363235' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA ENSINANDO - PÓLO PAMPULHA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '363235');

-- ESCOLA HUB SÃO LUIZ (BELO HORIZONTE)
UPDATE schools SET inep_code = '378992' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA HUB SÃO LUIZ' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '378992');

-- ESCOLA MIGUEL ARCANJO WALDORF (BELO HORIZONTE)
UPDATE schools SET inep_code = '353582' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA MIGUEL ARCANJO WALDORF' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '353582');

-- ESCOLA TÉCNICA TECNOTÓRIOS (BELO HORIZONTE)
UPDATE schools SET inep_code = '372340' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA TECNOTÓRIOS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '372340');

-- ESCOTEC - ESCOLA TÉCNICA FAMINAS - BH (BELO HORIZONTE)
UPDATE schools SET inep_code = '353540' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOTEC - ESCOLA TÉCNICA FAMINAS - BH' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '353540');

-- GRAU TÉCNICO VENDA NOVA (BELO HORIZONTE)
UPDATE schools SET inep_code = '375373' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'GRAU TÉCNICO VENDA NOVA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '375373');

-- INSTITUTO CECÍLIA MEIRELES - UNIDADE CASTELO (BELO HORIZONTE)
UPDATE schools SET inep_code = '372455' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO CECÍLIA MEIRELES - UNIDADE CASTELO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '372455');

-- INSTITUTO EDUCACIONAL ARCO ÍRIS (BELO HORIZONTE)
UPDATE schools SET inep_code = '344796' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL ARCO ÍRIS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '344796');

-- INSTITUTO EDUCACIONAL EVANGÉLICO MONTE SIÃO (BELO HORIZONTE)
UPDATE schools SET inep_code = '246077' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL EVANGÉLICO MONTE SIÃO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246077');

-- INSTITUTO EDUCACIONAL MANOEL PINHEIRO (BELO HORIZONTE)
UPDATE schools SET inep_code = '217263' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL MANOEL PINHEIRO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217263');

-- INSTITUTO EDUCACIONAL MISSÃO PAZ (BELO HORIZONTE)
UPDATE schools SET inep_code = '340391' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL MISSÃO PAZ' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '340391');

-- INSTITUTO EDUCACIONAL RIO BRANCO (BELO HORIZONTE)
UPDATE schools SET inep_code = '270024' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL RIO BRANCO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '270024');

-- INSTITUTO EDUCACIONAL SARAMENHA IESA (BELO HORIZONTE)
UPDATE schools SET inep_code = '327581' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL SARAMENHA IESA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '327581');

-- INSTITUTO EMÍLIA FERREIRO (BELO HORIZONTE)
UPDATE schools SET inep_code = '294039' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EMÍLIA FERREIRO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '294039');

-- INSTITUTO NACIONAL DE EDUCAÇÃO TECNOLÓGICA HEILER ALVES DA ROCHA-INET-HAR (BELO HORIZONTE)
UPDATE schools SET inep_code = '358444' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO NACIONAL DE EDUCAÇÃO TECNOLÓGICA HEILER ALVES DA ROCHA-INET-HAR' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '358444');

-- INSTITUTO PE ANGÉLICO LIPÁNI (BELO HORIZONTE)
UPDATE schools SET inep_code = '210285' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO PE ANGÉLICO LIPÁNI' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '210285');

-- INSTITUTO PEDAGÓGICO GÊNESIS (BELO HORIZONTE)
UPDATE schools SET inep_code = '329151' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO PEDAGÓGICO GÊNESIS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '329151');

-- REDE M2 - VENDA NOVA (BELO HORIZONTE)
UPDATE schools SET inep_code = '375233' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'REDE M2 - VENDA NOVA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '375233');

-- SENAC - CENTRO DE EDUCAÇÃO PROFISSIONAL VENDA NOVA (BELO HORIZONTE)
UPDATE schools SET inep_code = '366781' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAC - CENTRO DE EDUCAÇÃO PROFISSIONAL VENDA NOVA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '366781');

-- SENAT SERVIÇO NACIONAL DE APRENDIZAGEM DO TRANSPORTE - ESCOLA DE AVIAÇÃO CIVIL (BELO HORIZONTE)
UPDATE schools SET inep_code = '337323' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAT SERVIÇO NACIONAL DE APRENDIZAGEM DO TRANSPORTE - ESCOLA DE AVIAÇÃO CIVIL' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '337323');

-- SISTEMA DE ENSINO VOVÔ GRILO (BELO HORIZONTE)
UPDATE schools SET inep_code = '261840' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SISTEMA DE ENSINO VOVÔ GRILO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '261840');

-- SISTEMA MASTER DE ENSINO (BELO HORIZONTE)
UPDATE schools SET inep_code = '279901' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SISTEMA MASTER DE ENSINO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '279901');

-- STELLA ESCOLA INFANTIL (BELO HORIZONTE)
UPDATE schools SET inep_code = '309141' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'STELLA ESCOLA INFANTIL' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '309141');

-- C DE DESENV EDUC VEM SER (JABOTICATUBAS)
UPDATE schools SET inep_code = '322440' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'C DE DESENV EDUC VEM SER' AND UPPER(TRIM(city)) = 'JABOTICATUBAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322440');

-- COL CHROMOS LAGOA SANTA (LAGOA SANTA)
UPDATE schools SET inep_code = '216003' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COL CHROMOS LAGOA SANTA' AND UPPER(TRIM(city)) = 'LAGOA SANTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '216003');

-- COLÉGIO EBENÉZER (LAGOA SANTA)
UPDATE schools SET inep_code = '279251' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO EBENÉZER' AND UPPER(TRIM(city)) = 'LAGOA SANTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '279251');

-- COLÉGIO M2 (LAGOA SANTA)
UPDATE schools SET inep_code = '344176' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO M2' AND UPPER(TRIM(city)) = 'LAGOA SANTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '344176');

-- COLÉGIO YUGEN (LAGOA SANTA)
UPDATE schools SET inep_code = '371688' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO YUGEN' AND UPPER(TRIM(city)) = 'LAGOA SANTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '371688');

-- COLEGUIUM - UNIDADE LAGOA SANTA (LAGOA SANTA)
UPDATE schools SET inep_code = '254886' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLEGUIUM - UNIDADE LAGOA SANTA' AND UPPER(TRIM(city)) = 'LAGOA SANTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '254886');

-- ESCOLA IPÊ AMARELO (LAGOA SANTA)
UPDATE schools SET inep_code = '353612' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA IPÊ AMARELO' AND UPPER(TRIM(city)) = 'LAGOA SANTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '353612');

-- ESCOLA NINHO (LAGOA SANTA)
UPDATE schools SET inep_code = '379999' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA NINHO' AND UPPER(TRIM(city)) = 'LAGOA SANTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '379999');

-- ESCOLA PALOMAR DE LAGOA SANTA (LAGOA SANTA)
UPDATE schools SET inep_code = '331511' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA PALOMAR DE LAGOA SANTA' AND UPPER(TRIM(city)) = 'LAGOA SANTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '331511');

-- ALVO ESCOLA DE SAÚDE (PEDRO LEOPOLDO)
UPDATE schools SET inep_code = '378968' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ALVO ESCOLA DE SAÚDE' AND UPPER(TRIM(city)) = 'PEDRO LEOPOLDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '378968');

-- COLÉGIO CLITA BATISTA (PEDRO LEOPOLDO)
UPDATE schools SET inep_code = '211974' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CLITA BATISTA' AND UPPER(TRIM(city)) = 'PEDRO LEOPOLDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '211974');

-- COLÉGIO M2 - PEDRO LEOPOLDO (PEDRO LEOPOLDO)
UPDATE schools SET inep_code = '376191' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO M2 - PEDRO LEOPOLDO' AND UPPER(TRIM(city)) = 'PEDRO LEOPOLDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '376191');

-- ESCOLA DE FORMAÇÃO GERENCIAL - FPL -THEOTÔNIO BAPTISTA DE FREITAS (PEDRO LEOPOLDO)
UPDATE schools SET inep_code = '253901' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DE FORMAÇÃO GERENCIAL - FPL -THEOTÔNIO BAPTISTA DE FREITAS' AND UPPER(TRIM(city)) = 'PEDRO LEOPOLDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253901');

-- ESCOLA SESI  MARIA JOSÉ D'ALMEIDA MELLO (PEDRO LEOPOLDO)
UPDATE schools SET inep_code = '279129' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SESI  MARIA JOSÉ D''ALMEIDA MELLO' AND UPPER(TRIM(city)) = 'PEDRO LEOPOLDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '279129');

-- SENAI CENTRO DE FORMAÇÃO PROFISSIONAL GÉRSON DIAS (PEDRO LEOPOLDO)
UPDATE schools SET inep_code = '259403' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI CENTRO DE FORMAÇÃO PROFISSIONAL GÉRSON DIAS' AND UPPER(TRIM(city)) = 'PEDRO LEOPOLDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '259403');

-- CENTRO EDUCACIONAL GETSÊMANI (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '349160' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL GETSÊMANI' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349160');

-- CENTRO EDUCACIONAL IMACULADA CONCEIÇÃO (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '362441' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL IMACULADA CONCEIÇÃO' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '362441');

-- COLÉGIO UNIVERSO (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '351717' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO UNIVERSO' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '351717');

-- ESCOLA MARIA CLARA MACHADO (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '321591' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA MARIA CLARA MACHADO' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '321591');

-- ESCOLA TÉCNICA DIVINA PROVIDÊNCIA (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '334111' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA DIVINA PROVIDÊNCIA' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '334111');

-- GPA-GESTORES PRISIONAIS ASSOCIADOS (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '355364' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'GPA-GESTORES PRISIONAIS ASSOCIADOS' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '355364');

-- INSTITUTO EDUCACIONAL DOM BOSCO (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '215813' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL DOM BOSCO' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '215813');

-- INSTITUTO EDUCACIONAL EL SHADAI (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '326194' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL EL SHADAI' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '326194');

-- INSTITUTO METHA (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '323021' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO METHA' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '323021');

-- NOVA VISÃO (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '334022' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'NOVA VISÃO' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '334022');

-- REDE DE ENSINO GÊNESIS (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '253936' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'REDE DE ENSINO GÊNESIS' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253936');

-- SISTEMA NOVO ENSINO (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '313513' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SISTEMA NOVO ENSINO' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '313513');

-- COLÉGIO BATISTA BETESDA (SANTA LUZIA)
UPDATE schools SET inep_code = '262528' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO BATISTA BETESDA' AND UPPER(TRIM(city)) = 'SANTA LUZIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '262528');

-- COLÉGIO CRAMER (SANTA LUZIA)
UPDATE schools SET inep_code = '260487' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CRAMER' AND UPPER(TRIM(city)) = 'SANTA LUZIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '260487');

-- COLÉGIO MAXIMUS (SANTA LUZIA)
UPDATE schools SET inep_code = '316059' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MAXIMUS' AND UPPER(TRIM(city)) = 'SANTA LUZIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '316059');

-- COLÉGIO MONSENHOR  D'AMATO (SANTA LUZIA)
UPDATE schools SET inep_code = '316067' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MONSENHOR  D''AMATO' AND UPPER(TRIM(city)) = 'SANTA LUZIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '316067');

-- COLÉGIO SÃO BENEDITO- UNIDADE I (SANTA LUZIA)
UPDATE schools SET inep_code = '212067' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SÃO BENEDITO- UNIDADE I' AND UPPER(TRIM(city)) = 'SANTA LUZIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '212067');

-- COLÉGIO SÃO BENEDITO- UNIDADE II (SANTA LUZIA)
UPDATE schools SET inep_code = '349399' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SÃO BENEDITO- UNIDADE II' AND UPPER(TRIM(city)) = 'SANTA LUZIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349399');

-- CONHECER ESCOLA TÉCNICA - UNIDADE III (SANTA LUZIA)
UPDATE schools SET inep_code = '371106' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CONHECER ESCOLA TÉCNICA - UNIDADE III' AND UPPER(TRIM(city)) = 'SANTA LUZIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '371106');

-- ESCOLA SESI JOÃO CARLOS GIOVANNINI (SANTA LUZIA)
UPDATE schools SET inep_code = '309796' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SESI JOÃO CARLOS GIOVANNINI' AND UPPER(TRIM(city)) = 'SANTA LUZIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '309796');

-- INSTITUTO EDUCACIONAL LONDRINA (SANTA LUZIA)
UPDATE schools SET inep_code = '261327' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL LONDRINA' AND UPPER(TRIM(city)) = 'SANTA LUZIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '261327');

-- INSTITUTO EDUCACIONAL RACIONAL (SANTA LUZIA)
UPDATE schools SET inep_code = '211958' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL RACIONAL' AND UPPER(TRIM(city)) = 'SANTA LUZIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '211958');

-- INSTITUTO EDUCACIONAL SANTA AMÉLIA (SANTA LUZIA)
UPDATE schools SET inep_code = '215830' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL SANTA AMÉLIA' AND UPPER(TRIM(city)) = 'SANTA LUZIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '215830');

-- SENAI SANTA LUZIA CFP JOÃO CARLOS GIOVANNINI (SANTA LUZIA)
UPDATE schools SET inep_code = '360317' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI SANTA LUZIA CFP JOÃO CARLOS GIOVANNINI' AND UPPER(TRIM(city)) = 'SANTA LUZIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '360317');

-- CENTEP -  CENTRO TECNOLÓGICO E FORMAÇÃO PROFISSIONAL (VESPASIANO)
UPDATE schools SET inep_code = '331414' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTEP -  CENTRO TECNOLÓGICO E FORMAÇÃO PROFISSIONAL' AND UPPER(TRIM(city)) = 'VESPASIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '331414');

-- CENTRO DE ATIVIDADES DO TRABALHADOR ANTONIO QUIRINO DA COSTA (VESPASIANO)
UPDATE schools SET inep_code = '345857' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE ATIVIDADES DO TRABALHADOR ANTONIO QUIRINO DA COSTA' AND UPPER(TRIM(city)) = 'VESPASIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '345857');

-- CENTRO DE FORMAÇÃO PROFISSIONAL DE VESPASIANO (VESPASIANO)
UPDATE schools SET inep_code = '345938' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE FORMAÇÃO PROFISSIONAL DE VESPASIANO' AND UPPER(TRIM(city)) = 'VESPASIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '345938');

-- COLÉGIO M2 - VESPASIANO (VESPASIANO)
UPDATE schools SET inep_code = '371742' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO M2 - VESPASIANO' AND UPPER(TRIM(city)) = 'VESPASIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '371742');

-- ESCOLA DE ENFERMAGEM SANTA CLARA (VESPASIANO)
UPDATE schools SET inep_code = '312240' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DE ENFERMAGEM SANTA CLARA' AND UPPER(TRIM(city)) = 'VESPASIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312240');

-- ESCOLA SESI ANTÔNIO QUIRINO DA COSTA (VESPASIANO)
UPDATE schools SET inep_code = '274089' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SESI ANTÔNIO QUIRINO DA COSTA' AND UPPER(TRIM(city)) = 'VESPASIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '274089');

-- COLÉGIO ÔMEGA (COROMANDEL)
UPDATE schools SET inep_code = '346934' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ÔMEGA' AND UPPER(TRIM(city)) = 'COROMANDEL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346934');

-- INSTITUTO EDUCACIONAL DE COROMANDEL INEC (COROMANDEL)
UPDATE schools SET inep_code = '317764' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL DE COROMANDEL INEC' AND UPPER(TRIM(city)) = 'COROMANDEL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '317764');

-- SENAC UNIDADE  ENSINO TECNICO - CFP COROMANDEL (COROMANDEL)
UPDATE schools SET inep_code = '329894' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAC UNIDADE  ENSINO TECNICO - CFP COROMANDEL' AND UPPER(TRIM(city)) = 'COROMANDEL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '329894');

-- CENTRO DE EDUCAÇÃO PROFISSIONAL ALPHA (MONTE CARMELO)
UPDATE schools SET inep_code = '326917' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE EDUCAÇÃO PROFISSIONAL ALPHA' AND UPPER(TRIM(city)) = 'MONTE CARMELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '326917');

-- COL N SRA DO AMPARO (MONTE CARMELO)
UPDATE schools SET inep_code = '202100' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COL N SRA DO AMPARO' AND UPPER(TRIM(city)) = 'MONTE CARMELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '202100');

-- COLÉGIO EXCELÊNCIA (BOCAIÚVA)
UPDATE schools SET inep_code = '314854' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO EXCELÊNCIA' AND UPPER(TRIM(city)) = 'BOCAIÚVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '314854');

-- INSTITUTO DE EDUCAÇÃO E CULTURA DE BOCAIÚVA (BOCAIÚVA)
UPDATE schools SET inep_code = '344761' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO DE EDUCAÇÃO E CULTURA DE BOCAIÚVA' AND UPPER(TRIM(city)) = 'BOCAIÚVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '344761');

-- CEDULC CENTRO EDUCACIONAL E LABORATORIO DE CULTURA (BRASÍLIA DE MINAS)
UPDATE schools SET inep_code = '247341' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CEDULC CENTRO EDUCACIONAL E LABORATORIO DE CULTURA' AND UPPER(TRIM(city)) = 'BRASÍLIA DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '247341');

-- COLÉGIO SÓLIDO - UNIDADE BRASÍLIA DE MINAS (BRASÍLIA DE MINAS)
UPDATE schools SET inep_code = '368318' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SÓLIDO - UNIDADE BRASÍLIA DE MINAS' AND UPPER(TRIM(city)) = 'BRASÍLIA DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368318');

-- INSTITUTO GÊNESIS (BRASÍLIA DE MINAS)
UPDATE schools SET inep_code = '347604' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO GÊNESIS' AND UPPER(TRIM(city)) = 'BRASÍLIA DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '347604');

-- CENTRO EDUCACIONAL OSVALDO VICINTIN (CAPITÃO ENÉAS)
UPDATE schools SET inep_code = '316989' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL OSVALDO VICINTIN' AND UPPER(TRIM(city)) = 'CAPITÃO ENÉAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '316989');

-- CENTRO EDUCACIONAL CORJESUS (CORAÇÃO DE JESUS)
UPDATE schools SET inep_code = '339679' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL CORJESUS' AND UPPER(TRIM(city)) = 'CORAÇÃO DE JESUS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '339679');

-- COLÉGIO PIRÂMIDE (FRANCISCO SÁ)
UPDATE schools SET inep_code = '321966' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PIRÂMIDE' AND UPPER(TRIM(city)) = 'FRANCISCO SÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '321966');

-- C EDUC COTEMINAS (MONTES CLAROS)
UPDATE schools SET inep_code = '274291' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'C EDUC COTEMINAS' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '274291');

-- C PEDAG ALEGRIA DE VIVER (MONTES CLAROS)
UPDATE schools SET inep_code = '293474' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'C PEDAG ALEGRIA DE VIVER' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '293474');

-- CENTRO DE ENSINO GRAU TÉCNICO MONTES CLAROS (MONTES CLAROS)
UPDATE schools SET inep_code = '376477' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE ENSINO GRAU TÉCNICO MONTES CLAROS' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '376477');

-- CENTRO EDUCACIONAL ÍMPAR (MONTES CLAROS)
UPDATE schools SET inep_code = '213845' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL ÍMPAR' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '213845');

-- CENTRO EDUCACIONAL MENDES E SANTOS (MONTES CLAROS)
UPDATE schools SET inep_code = '222259' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL MENDES E SANTOS' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '222259');

-- CENTRO EDUCACIONAL PIONEIRO (MONTES CLAROS)
UPDATE schools SET inep_code = '322326' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL PIONEIRO' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322326');

-- COL BATISTA NOVA CANAÃ (MONTES CLAROS)
UPDATE schools SET inep_code = '249696' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COL BATISTA NOVA CANAÃ' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '249696');

-- COL SÃO MATEUS (MONTES CLAROS)
UPDATE schools SET inep_code = '248975' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COL SÃO MATEUS' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '248975');

-- COLÉGIO BIOMÁXIMO - UNIDADE II (MONTES CLAROS)
UPDATE schools SET inep_code = '365920' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO BIOMÁXIMO - UNIDADE II' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '365920');

-- COLÉGIO CRISTÃO (MONTES CLAROS)
UPDATE schools SET inep_code = '322822' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CRISTÃO' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322822');

-- COLÉGIO HG6 (MONTES CLAROS)
UPDATE schools SET inep_code = '371750' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO HG6' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '371750');

-- COLÉGIO ÍCONE (MONTES CLAROS)
UPDATE schools SET inep_code = '299693' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ÍCONE' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '299693');

-- COLÉGIO MÁXIMMUS (MONTES CLAROS)
UPDATE schools SET inep_code = '378151' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MÁXIMMUS' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '378151');

-- COLÉGIO PODIUM MONTES CLAROS (MONTES CLAROS)
UPDATE schools SET inep_code = '364223' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PODIUM MONTES CLAROS' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '364223');

-- COLÉGIO SÓLIDO - UNIDADE SÃO JOSÉ (MONTES CLAROS)
UPDATE schools SET inep_code = '367710' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SÓLIDO - UNIDADE SÃO JOSÉ' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '367710');

-- COLÉGIO SÓLIDO MÉDIO (MONTES CLAROS)
UPDATE schools SET inep_code = '346209' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SÓLIDO MÉDIO' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346209');

-- COLÉGIO SÓLIDO TEENS (MONTES CLAROS)
UPDATE schools SET inep_code = '369934' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SÓLIDO TEENS' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369934');

-- COLÉGIO VITÓRIA (MONTES CLAROS)
UPDATE schools SET inep_code = '312932' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO VITÓRIA' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312932');

-- COLLEGIUM PRISMA (MONTES CLAROS)
UPDATE schools SET inep_code = '260541' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLLEGIUM PRISMA' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '260541');

-- ESCOLA DE EDUCAÇÃO PROFISSIONAL IBITURUNA - EEPI (MONTES CLAROS)
UPDATE schools SET inep_code = '348350' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DE EDUCAÇÃO PROFISSIONAL IBITURUNA - EEPI' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '348350');

-- ESCOLA ÍMPETO DO SABER (MONTES CLAROS)
UPDATE schools SET inep_code = '356263' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA ÍMPETO DO SABER' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '356263');

-- EXCELÊNCIA TÉCNICOS (MONTES CLAROS)
UPDATE schools SET inep_code = '348465' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EXCELÊNCIA TÉCNICOS' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '348465');

-- EXCELÊNCIA TÉCNICOS - UNIDADE II (MONTES CLAROS)
UPDATE schools SET inep_code = '366641' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EXCELÊNCIA TÉCNICOS - UNIDADE II' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '366641');

-- IESC INSTITUTO EDUCACIONAL SANTA CRUZ (MONTES CLAROS)
UPDATE schools SET inep_code = '348473' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'IESC INSTITUTO EDUCACIONAL SANTA CRUZ' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '348473');

-- INSTITUTO DE EDUCAÇÃO QUALIFICAR (MONTES CLAROS)
UPDATE schools SET inep_code = '358070' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO DE EDUCAÇÃO QUALIFICAR' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '358070');

-- INSTITUTO MONTESCLARENSE DE EDUCAÇÃO E DESENVOLVIMENTO (MONTES CLAROS)
UPDATE schools SET inep_code = '372331' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO MONTESCLARENSE DE EDUCAÇÃO E DESENVOLVIMENTO' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '372331');

-- PROZ EDUCAÇÃO PROFISSIONAL - UNIDADE MONTES CLAROS (MONTES CLAROS)
UPDATE schools SET inep_code = '380997' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'PROZ EDUCAÇÃO PROFISSIONAL - UNIDADE MONTES CLAROS' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '380997');

-- SENAC- CENTRO DE FORMAÇÃO PROFISSIONAL (MONTES CLAROS)
UPDATE schools SET inep_code = '316130' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAC- CENTRO DE FORMAÇÃO PROFISSIONAL' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '316130');

-- SENAI- CENTRO DE FORMAÇÃO PROFISSIONAL LUIZ DE PAULA (MONTES CLAROS)
UPDATE schools SET inep_code = '317691' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI- CENTRO DE FORMAÇÃO PROFISSIONAL LUIZ DE PAULA' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '317691');

-- SISTEMA DE ENSINO FOCO (MONTES CLAROS)
UPDATE schools SET inep_code = '370100' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SISTEMA DE ENSINO FOCO' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '370100');

-- COLÉGIO RENASCER (MIRAÍ)
UPDATE schools SET inep_code = '352071' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO RENASCER' AND UPPER(TRIM(city)) = 'MIRAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '352071');

-- CECAP- CENTRO DE CAPACITAÇÃO PROFISSIONAL (MURIAÉ)
UPDATE schools SET inep_code = '278866' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CECAP- CENTRO DE CAPACITAÇÃO PROFISSIONAL' AND UPPER(TRIM(city)) = 'MURIAÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '278866');

-- COLÉGIO EQUIPE DE MURIAÉ (MURIAÉ)
UPDATE schools SET inep_code = '305847' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO EQUIPE DE MURIAÉ' AND UPPER(TRIM(city)) = 'MURIAÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305847');

-- COLÉGIO ÔMEGA (MURIAÉ)
UPDATE schools SET inep_code = '377899' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ÔMEGA' AND UPPER(TRIM(city)) = 'MURIAÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '377899');

-- COLÉGIO SANTA MARCELINA (MURIAÉ)
UPDATE schools SET inep_code = '102539' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SANTA MARCELINA' AND UPPER(TRIM(city)) = 'MURIAÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '102539');

-- EDUCANDARIO BATISTA DE MURIAÉ (MURIAÉ)
UPDATE schools SET inep_code = '288225' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EDUCANDARIO BATISTA DE MURIAÉ' AND UPPER(TRIM(city)) = 'MURIAÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '288225');

-- ESCOLA SÃO PAULO (MURIAÉ)
UPDATE schools SET inep_code = '102563' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SÃO PAULO' AND UPPER(TRIM(city)) = 'MURIAÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '102563');

-- CENTRO EDUCACIONAL LUZ SUBLIME (BELA VISTA DE MINAS)
UPDATE schools SET inep_code = '321800' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL LUZ SUBLIME' AND UPPER(TRIM(city)) = 'BELA VISTA DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '321800');

-- BIOTEC – CENTRO DE EDUCAÇÃO (ITABIRA)
UPDATE schools SET inep_code = '326879' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'BIOTEC – CENTRO DE EDUCAÇÃO' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '326879');

-- CENTRO EDUCACIONAL AMIGUINHOS DA MÔNICA (ITABIRA)
UPDATE schools SET inep_code = '301311' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL AMIGUINHOS DA MÔNICA' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '301311');

-- CENTRO EDUCACIONAL CAMPOS (ITABIRA)
UPDATE schools SET inep_code = '352365' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL CAMPOS' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '352365');

-- CENTRO EDUCACIONAL ROBERTO PORTO - UNID VII (ITABIRA)
UPDATE schools SET inep_code = '339300' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL ROBERTO PORTO - UNID VII' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '339300');

-- COLÉGIO AUGE (ITABIRA)
UPDATE schools SET inep_code = '361496' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO AUGE' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '361496');

-- COLÉGIO CESE  - UNIDADE II (ITABIRA)
UPDATE schools SET inep_code = '377767' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CESE  - UNIDADE II' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '377767');

-- COLÉGIO COMERCIAL ITABIRANO (ITABIRA)
UPDATE schools SET inep_code = '105899' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO COMERCIAL ITABIRANO' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '105899');

-- COLÉGIO DE ENSINO TÉCNICO BRASILEIRO EDUCACIONAL (ITABIRA)
UPDATE schools SET inep_code = '375764' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DE ENSINO TÉCNICO BRASILEIRO EDUCACIONAL' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '375764');

-- COLÉGIO NOSSA SENHORA DAS DORES (ITABIRA)
UPDATE schools SET inep_code = '105902' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO NOSSA SENHORA DAS DORES' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '105902');

-- COLÉGIO SUPER MAIS (ITABIRA)
UPDATE schools SET inep_code = '368113' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SUPER MAIS' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368113');

-- ESCOLA TÉCNICA CURSO NOBRE - ITABIRA (ITABIRA)
UPDATE schools SET inep_code = '363766' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA CURSO NOBRE - ITABIRA' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '363766');

-- ESCOLA TÉCNICA DE FORMAÇÃO GERENCIAL - ITABIRA (ITABIRA)
UPDATE schools SET inep_code = '246000' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA DE FORMAÇÃO GERENCIAL - ITABIRA' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246000');

-- ESCOLA TÉCNICA FIDE (ITABIRA)
UPDATE schools SET inep_code = '317730' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA FIDE' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '317730');

-- INSTITUTO BRASILEIRO DE INOVAÇÃO E SUSTENTABILIDADE - IBIS (ITABIRA)
UPDATE schools SET inep_code = '349240' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO BRASILEIRO DE INOVAÇÃO E SUSTENTABILIDADE - IBIS' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349240');

-- SENAC- INIDADE DE ENSINO TÉCNICO - CFP DE ITABIRA (ITABIRA)
UPDATE schools SET inep_code = '342939' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAC- INIDADE DE ENSINO TÉCNICO - CFP DE ITABIRA' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342939');

-- SENAI CENTRO DE FORMAÇÃO PROFISSIONAL PEDRO MARTINS GUERRA (ITABIRA)
UPDATE schools SET inep_code = '322041' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI CENTRO DE FORMAÇÃO PROFISSIONAL PEDRO MARTINS GUERRA' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322041');

-- SEPRO- SISTEMA DE EDUCAÇÃO PROFISSIONAL DE ITABIRA (ITABIRA)
UPDATE schools SET inep_code = '293181' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SEPRO- SISTEMA DE EDUCAÇÃO PROFISSIONAL DE ITABIRA' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '293181');

-- ASSOCIAÇÃO MONLEVADENSE DE ENSINO COOPER (JOÃO MONLEVADE)
UPDATE schools SET inep_code = '105961' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ASSOCIAÇÃO MONLEVADENSE DE ENSINO COOPER' AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '105961');

-- CEBRAC CENTRO DE ENSINO BRASILEIRO E FORMAÇÃO PROFISSIONAL (JOÃO MONLEVADE)
UPDATE schools SET inep_code = '345504' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CEBRAC CENTRO DE ENSINO BRASILEIRO E FORMAÇÃO PROFISSIONAL' AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '345504');

-- CENTRO EDUCACIONAL ROBERTO PORTO (JOÃO MONLEVADE)
UPDATE schools SET inep_code = '317853' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL ROBERTO PORTO' AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '317853');

-- CENTRO EDUCACIONAL ROBERTO PORTO - UNIDADE V (JOÃO MONLEVADE)
UPDATE schools SET inep_code = '333212' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL ROBERTO PORTO - UNIDADE V' AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '333212');

-- CENTRO EDUCACIONAL ROBERTO PORTO UNIDADE II (JOÃO MONLEVADE)
UPDATE schools SET inep_code = '325546' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL ROBERTO PORTO UNIDADE II' AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '325546');

-- COLÉGIO CESP (JOÃO MONLEVADE)
UPDATE schools SET inep_code = '281298' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CESP' AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '281298');

-- COLÉGIO KENNEDY (JOÃO MONLEVADE)
UPDATE schools SET inep_code = '105953' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO KENNEDY' AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '105953');

-- CTM - CENTRO TÉCNICO MUNDIAL (JOÃO MONLEVADE)
UPDATE schools SET inep_code = '373265' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CTM - CENTRO TÉCNICO MUNDIAL' AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '373265');

-- SENAI CENTRO DE FORMAÇÃO PROFISSIONAL NANSEN ARAÚJO (JOÃO MONLEVADE)
UPDATE schools SET inep_code = '317322' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI CENTRO DE FORMAÇÃO PROFISSIONAL NANSEN ARAÚJO' AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '317322');

-- ESCOLA NOVAERENSE (NOVA ERA)
UPDATE schools SET inep_code = '105970' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA NOVAERENSE' AND UPPER(TRIM(city)) = 'NOVA ERA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '105970');

-- SENAI CENTRO DE FORMAÇÃO PROFISSIONAL JOSÉ FERNANDO COURA (SÃO GONÇALO DO RIO ABAIXO)
UPDATE schools SET inep_code = '347108' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI CENTRO DE FORMAÇÃO PROFISSIONAL JOSÉ FERNANDO COURA' AND UPPER(TRIM(city)) = 'SÃO GONÇALO DO RIO ABAIXO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '347108');

-- ESCOLA FAMÍLIA AGRÍCOLA PAULO FREIRE (ACAIACA)
UPDATE schools SET inep_code = '328031' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA FAMÍLIA AGRÍCOLA PAULO FREIRE' AND UPPER(TRIM(city)) = 'ACAIACA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '328031');

-- CENTRO DE ENSINO TÉCNICO SÃO CARLOS (ITABIRITO)
UPDATE schools SET inep_code = '325945' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE ENSINO TÉCNICO SÃO CARLOS' AND UPPER(TRIM(city)) = 'ITABIRITO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '325945');

-- COLÉGIO UNIPAC (ITABIRITO)
UPDATE schools SET inep_code = '372293' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO UNIPAC' AND UPPER(TRIM(city)) = 'ITABIRITO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '372293');

-- ESCOLA EPHIGÊNIA DE OLIVEIRA BATISTA (ITABIRITO)
UPDATE schools SET inep_code = '299979' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA EPHIGÊNIA DE OLIVEIRA BATISTA' AND UPPER(TRIM(city)) = 'ITABIRITO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '299979');

-- ESCOLA PROFESSOR JAYME DE SOUZA MARTINS (ITABIRITO)
UPDATE schools SET inep_code = '108014' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA PROFESSOR JAYME DE SOUZA MARTINS' AND UPPER(TRIM(city)) = 'ITABIRITO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108014');

-- ESCOLA PROFESSOR JAYME DE SOUZA MARTINS - UNIDADE II (ITABIRITO)
UPDATE schools SET inep_code = '378097' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA PROFESSOR JAYME DE SOUZA MARTINS - UNIDADE II' AND UPPER(TRIM(city)) = 'ITABIRITO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '378097');

-- INSTITUTO SANTO ANTÔNIO DE PÁDUA (ITABIRITO)
UPDATE schools SET inep_code = '107981' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO SANTO ANTÔNIO DE PÁDUA' AND UPPER(TRIM(city)) = 'ITABIRITO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '107981');

-- SENAI CENTRO DE FORMAÇÃO PROFISSIONAL LAÉRCIO GARCIA NOGUEIRA (ITABIRITO)
UPDATE schools SET inep_code = '358940' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI CENTRO DE FORMAÇÃO PROFISSIONAL LAÉRCIO GARCIA NOGUEIRA' AND UPPER(TRIM(city)) = 'ITABIRITO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '358940');

-- ADJETIVO - CETEP- CENTRO TÉCNICO DE ENSINO PROFISSIONAL (MARIANA)
UPDATE schools SET inep_code = '323772' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ADJETIVO - CETEP- CENTRO TÉCNICO DE ENSINO PROFISSIONAL' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '323772');

-- CENTRO DE ENSINO TÉCNICO E PROFISSIONALIZANTE MORAIS (MARIANA)
UPDATE schools SET inep_code = '373494' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE ENSINO TÉCNICO E PROFISSIONALIZANTE MORAIS' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '373494');

-- CENTRO DE FORMAÇÃO PROFISSIONAL DOUTOR JOSÉ LUCIANO DUARTE PENIDO (MARIANA)
UPDATE schools SET inep_code = '340960' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE FORMAÇÃO PROFISSIONAL DOUTOR JOSÉ LUCIANO DUARTE PENIDO' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '340960');

-- CENTRO EDUCACIONAL GETSÊMANI (MARIANA)
UPDATE schools SET inep_code = '356336' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL GETSÊMANI' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '356336');

-- COLÉGIO DOM VIÇOSO (MARIANA)
UPDATE schools SET inep_code = '274127' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DOM VIÇOSO' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '274127');

-- COLÉGIO FLECHA (MARIANA)
UPDATE schools SET inep_code = '237167' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO FLECHA' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '237167');

-- COLÉGIO PROVIDÊNCIA (MARIANA)
UPDATE schools SET inep_code = '108031' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PROVIDÊNCIA' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108031');

-- ESCOLA TEIXEIRA DIAS (MARIANA)
UPDATE schools SET inep_code = '300063' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TEIXEIRA DIAS' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '300063');

-- CENTRO DE EDUCAÇÃO CECÍLIA MEIRELES (OURO PRETO)
UPDATE schools SET inep_code = '361259' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE EDUCAÇÃO CECÍLIA MEIRELES' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '361259');

-- CENTRO EDUCACIONAL MUNDO MÁGICO (OURO PRETO)
UPDATE schools SET inep_code = '300012' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL MUNDO MÁGICO' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '300012');

-- CENTRO EDUCACIONAL OURO PRETO (OURO PRETO)
UPDATE schools SET inep_code = '261041' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL OURO PRETO' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '261041');

-- COLÉGIO ARQUIDIOCESANO (OURO PRETO)
UPDATE schools SET inep_code = '108103' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ARQUIDIOCESANO' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108103');

-- COLÉGIO RENASCER (OURO PRETO)
UPDATE schools SET inep_code = '368296' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO RENASCER' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368296');

-- COLÉGIO SINAPSE (OURO PRETO)
UPDATE schools SET inep_code = '321532' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SINAPSE' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '321532');

-- COLÉGIO TÉCNICO INCONFIDENTE ÁLVARES MACIEL (OURO PRETO)
UPDATE schools SET inep_code = '339202' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TÉCNICO INCONFIDENTE ÁLVARES MACIEL' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '339202');

-- ESCOLA DE ARTE RODRIGO MELO FRANCO DE ANDRADE (OURO PRETO)
UPDATE schools SET inep_code = '314722' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DE ARTE RODRIGO MELO FRANCO DE ANDRADE' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '314722');

-- ESCOLA DE ENSINO TÉCNICO EURÍPEDES BARSANULFO (OURO PRETO)
UPDATE schools SET inep_code = '311006' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DE ENSINO TÉCNICO EURÍPEDES BARSANULFO' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '311006');

-- CTA - COLÉGIO TÉCNICO AVANÇAR (ABAETÉ)
UPDATE schools SET inep_code = '340766' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CTA - COLÉGIO TÉCNICO AVANÇAR' AND UPPER(TRIM(city)) = 'ABAETÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '340766');

-- COLÉGIO CIDADE DE BOM DESPACHO (BOM DESPACHO)
UPDATE schools SET inep_code = '343668' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CIDADE DE BOM DESPACHO' AND UPPER(TRIM(city)) = 'BOM DESPACHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '343668');

-- COLÉGIO LEONARDO DA VINCI (BOM DESPACHO)
UPDATE schools SET inep_code = '322849' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO LEONARDO DA VINCI' AND UPPER(TRIM(city)) = 'BOM DESPACHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322849');

-- COLÉGIO TIPURA (BOM DESPACHO)
UPDATE schools SET inep_code = '375675' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TIPURA' AND UPPER(TRIM(city)) = 'BOM DESPACHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '375675');

-- COLÉGIO UNIVERSO (BOM DESPACHO)
UPDATE schools SET inep_code = '362514' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO UNIVERSO' AND UPPER(TRIM(city)) = 'BOM DESPACHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '362514');

-- ESCOLA TÉCNICA SANTA CLARA-BOM DESPACHO (BOM DESPACHO)
UPDATE schools SET inep_code = '354937' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA SANTA CLARA-BOM DESPACHO' AND UPPER(TRIM(city)) = 'BOM DESPACHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '354937');

-- COLÉGIO ELYSIUM (DORES DO INDAIÁ)
UPDATE schools SET inep_code = '274151' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ELYSIUM' AND UPPER(TRIM(city)) = 'DORES DO INDAIÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '274151');

-- ESCOLA MAANAIM (DORES DO INDAIÁ)
UPDATE schools SET inep_code = '280801' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA MAANAIM' AND UPPER(TRIM(city)) = 'DORES DO INDAIÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '280801');