-- EM SÃO JUDAS TADEU (CASCALHO RICO)
UPDATE schools SET inep_code = '272337' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SÃO JUDAS TADEU' AND UPPER(TRIM(city)) = 'CASCALHO RICO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '272337');

-- EM ANTÔNIO MATIAS PEREIRA (COROMANDEL)
UPDATE schools SET inep_code = '266396' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANTÔNIO MATIAS PEREIRA' AND UPPER(TRIM(city)) = 'COROMANDEL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '266396');

-- EM LAÉRCIO MENDES DE SAIRRE (COROMANDEL)
UPDATE schools SET inep_code = '310964' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM LAÉRCIO MENDES DE SAIRRE' AND UPPER(TRIM(city)) = 'COROMANDEL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310964');

-- EM MONS FLEURY CURADO (COROMANDEL)
UPDATE schools SET inep_code = '200417' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MONS FLEURY CURADO' AND UPPER(TRIM(city)) = 'COROMANDEL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '200417');

-- EM CELSO BUENO (MONTE CARMELO)
UPDATE schools SET inep_code = '200565' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CELSO BUENO' AND UPPER(TRIM(city)) = 'MONTE CARMELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '200565');

-- EM FRANCISCO CAMPOS (MONTE CARMELO)
UPDATE schools SET inep_code = '201910' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM FRANCISCO CAMPOS' AND UPPER(TRIM(city)) = 'MONTE CARMELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '201910');

-- EM DINAH SILVA AZEVEDO CALDEIRA (BOCAIÚVA)
UPDATE schools SET inep_code = '237400' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DINAH SILVA AZEVEDO CALDEIRA' AND UPPER(TRIM(city)) = 'BOCAIÚVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '237400');

-- EM JOSÉ SEIXAS (BOCAIÚVA)
UPDATE schools SET inep_code = '237396' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ SEIXAS' AND UPPER(TRIM(city)) = 'BOCAIÚVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '237396');

-- EM PROFESSORA ZECA CALIXTO (BOCAIÚVA)
UPDATE schools SET inep_code = '276723' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA ZECA CALIXTO' AND UPPER(TRIM(city)) = 'BOCAIÚVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '276723');

-- EM JOÃO HENRIQUE (BOTUMIRIM)
UPDATE schools SET inep_code = '207675' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOÃO HENRIQUE' AND UPPER(TRIM(city)) = 'BOTUMIRIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '207675');

-- EM GERALDO GOMES DOS SANTOS (CORAÇÃO DE JESUS)
UPDATE schools SET inep_code = '216399' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM GERALDO GOMES DOS SANTOS' AND UPPER(TRIM(city)) = 'CORAÇÃO DE JESUS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '216399');

-- EM JOSÉ EVANGELISTA PEREIRA (CORAÇÃO DE JESUS)
UPDATE schools SET inep_code = '207764' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ EVANGELISTA PEREIRA' AND UPPER(TRIM(city)) = 'CORAÇÃO DE JESUS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '207764');

-- EM QUIRINO JOSÉ DA SILVA (CORAÇÃO DE JESUS)
UPDATE schools SET inep_code = '216356' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM QUIRINO JOSÉ DA SILVA' AND UPPER(TRIM(city)) = 'CORAÇÃO DE JESUS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '216356');

-- EM DE SÃO GERALDO (FRANCISCO SÁ)
UPDATE schools SET inep_code = '298221' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DE SÃO GERALDO' AND UPPER(TRIM(city)) = 'FRANCISCO SÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '298221');

-- EM PROF CÂNDIDO NEVES (ITACAMBIRA)
UPDATE schools SET inep_code = '207985' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROF CÂNDIDO NEVES' AND UPPER(TRIM(city)) = 'ITACAMBIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '207985');

--  EM DOMINGUINHOS PEREIRA - CAIC (MONTES CLAROS)
UPDATE schools SET inep_code = '242527' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOMINGUINHOS PEREIRA - CAIC' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '242527');

-- EM DONA VIDINHA PIRES (MONTES CLAROS)
UPDATE schools SET inep_code = '305936' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DONA VIDINHA PIRES' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305936');

-- EM DR CRISANTINO BORÉM (MONTES CLAROS)
UPDATE schools SET inep_code = '227595' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DR CRISANTINO BORÉM' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '227595');

-- EM GERALDO PEREIRA DE SOUZA (MONTES CLAROS)
UPDATE schools SET inep_code = '223549' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM GERALDO PEREIRA DE SOUZA' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '223549');

-- EM JOÃO VALLE MAURÍCIO (MONTES CLAROS)
UPDATE schools SET inep_code = '223557' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOÃO VALLE MAURÍCIO' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '223557');

-- EM MESTRA FININHA (MONTES CLAROS)
UPDATE schools SET inep_code = '227692' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MESTRA FININHA' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '227692');

-- EM PROFA EUNICE CARNEIRO (MONTES CLAROS)
UPDATE schools SET inep_code = '344060' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFA EUNICE CARNEIRO' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '344060');

-- EM PROFA NEIDE MELO FRANCO (MONTES CLAROS)
UPDATE schools SET inep_code = '227579' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFA NEIDE MELO FRANCO' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '227579');

-- EM PROFESSORA MARIA DE LOURDES PINHEIRO (MONTES CLAROS)
UPDATE schools SET inep_code = '240168' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA MARIA DE LOURDES PINHEIRO' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '240168');

-- EM ROTARY SÃO LUIZ (MONTES CLAROS)
UPDATE schools SET inep_code = '274305' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ROTARY SÃO LUIZ' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '274305');

-- EM ROZENDA ZANE MORAES (MONTES CLAROS)
UPDATE schools SET inep_code = '368628' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ROZENDA ZANE MORAES' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368628');

-- EM RUY LAGE (MONTES CLAROS)
UPDATE schools SET inep_code = '230359' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM RUY LAGE' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '230359');

-- EM JOANA FERREIRA DE BARROS (PATIS)
UPDATE schools SET inep_code = '315770' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOANA FERREIRA DE BARROS' AND UPPER(TRIM(city)) = 'PATIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '315770');

-- EM DENIZAR VELOSO SANTOS (SÃO JOÃO DA PONTE)
UPDATE schools SET inep_code = '316709' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DENIZAR VELOSO SANTOS' AND UPPER(TRIM(city)) = 'SÃO JOÃO DA PONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '316709');

-- EM JOÃO FERNANDES DOS SANTOS (SÃO JOÃO DA PONTE)
UPDATE schools SET inep_code = '297607' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOÃO FERNANDES DOS SANTOS' AND UPPER(TRIM(city)) = 'SÃO JOÃO DA PONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '297607');

-- EM PROFESSORA MARIA LOURDES RODRIGUES (BARÃO DE MONTE ALTO)
UPDATE schools SET inep_code = '269760' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA MARIA LOURDES RODRIGUES' AND UPPER(TRIM(city)) = 'BARÃO DE MONTE ALTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '269760');

-- EM PROFESSORA OLÍVIA MARIA COELHO (BARÃO DE MONTE ALTO)
UPDATE schools SET inep_code = '269751' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA OLÍVIA MARIA COELHO' AND UPPER(TRIM(city)) = 'BARÃO DE MONTE ALTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '269751');

-- EM QUEIROZES (EUGENÓPOLIS)
UPDATE schools SET inep_code = '244503' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM QUEIROZES' AND UPPER(TRIM(city)) = 'EUGENÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '244503');

-- CENTRO DE EDUCAÇÃO MUNICIPAL NORBERTO BERNO (LARANJAL)
UPDATE schools SET inep_code = '259641' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE EDUCAÇÃO MUNICIPAL NORBERTO BERNO' AND UPPER(TRIM(city)) = 'LARANJAL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '259641');

-- CAIC EM JOAQUIM RIBEIRO CARVALHO (MURIAÉ)
UPDATE schools SET inep_code = '245941' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CAIC EM JOAQUIM RIBEIRO CARVALHO' AND UPPER(TRIM(city)) = 'MURIAÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '245941');

-- EM CÂNDIDO PORTINARI (MURIAÉ)
UPDATE schools SET inep_code = '250970' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CÂNDIDO PORTINARI' AND UPPER(TRIM(city)) = 'MURIAÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '250970');

-- EM PROFA STELA FIDÉLIS (MURIAÉ)
UPDATE schools SET inep_code = '235172' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFA STELA FIDÉLIS' AND UPPER(TRIM(city)) = 'MURIAÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '235172');

-- EM PROFESSORA ELZA ROGÉRIO (MURIAÉ)
UPDATE schools SET inep_code = '227838' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA ELZA ROGÉRIO' AND UPPER(TRIM(city)) = 'MURIAÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '227838');

-- EM PROFESSORA ESMERALDA VIANNA (MURIAÉ)
UPDATE schools SET inep_code = '227846' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA ESMERALDA VIANNA' AND UPPER(TRIM(city)) = 'MURIAÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '227846');

-- EM MARIA AUXILIADORA G B BONATO (ROSÁRIO DA LIMEIRA)
UPDATE schools SET inep_code = '271039' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA AUXILIADORA G B BONATO' AND UPPER(TRIM(city)) = 'ROSÁRIO DA LIMEIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '271039');

-- EM DOUTOR JOÃO BATISTA DE RESENDE (SANTANA DE CATAGUASES)
UPDATE schools SET inep_code = '262978' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOUTOR JOÃO BATISTA DE RESENDE' AND UPPER(TRIM(city)) = 'SANTANA DE CATAGUASES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '262978');

-- EM JOSÉ SOARES DE SOUZA FILHO (VIEIRAS)
UPDATE schools SET inep_code = '269824' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ SOARES DE SOUZA FILHO' AND UPPER(TRIM(city)) = 'VIEIRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '269824');

-- COLÉGIO MUNICIPAL PROFESSORA DIDI ANDRADE (ITABIRA)
UPDATE schools SET inep_code = '232190' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MUNICIPAL PROFESSORA DIDI ANDRADE' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '232190');

-- EM ANTÔNIO CAMILO ALVIM (ITABIRA)
UPDATE schools SET inep_code = '293849' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANTÔNIO CAMILO ALVIM' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '293849');

-- EM JOSÉ GOMES VIEIRA (ITABIRA)
UPDATE schools SET inep_code = '103268' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ GOMES VIEIRA' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103268');

-- EM MARINA BRAGANÇA DE MENDONÇA (ITABIRA)
UPDATE schools SET inep_code = '354481' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARINA BRAGANÇA DE MENDONÇA' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '354481');

-- EM PROFESSORA ANTONINA MOREIRA (ITABIRA)
UPDATE schools SET inep_code = '103217' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA ANTONINA MOREIRA' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103217');

-- CENTRO EDUCACIONAL DE JOÃO MONLEVADE (JOÃO MONLEVADE)
UPDATE schools SET inep_code = '105091' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL DE JOÃO MONLEVADE' AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '105091');

-- EM CÔNEGO JOSÉ HIGINO DE FREITAS (JOÃO MONLEVADE)
UPDATE schools SET inep_code = '103454' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CÔNEGO JOSÉ HIGINO DE FREITAS' AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103454');

-- EM GERMIN LOUREIRO (JOÃO MONLEVADE)
UPDATE schools SET inep_code = '343110' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM GERMIN LOUREIRO' AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '343110');

-- EM GOV ISRAEL PINHEIRO (JOÃO MONLEVADE)
UPDATE schools SET inep_code = '105104' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM GOV ISRAEL PINHEIRO' AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '105104');

-- EM MONTEIRO LOBATO (JOÃO MONLEVADE)
UPDATE schools SET inep_code = '227889' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MONTEIRO LOBATO' AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '227889');

-- EM PROMORAR (JOÃO MONLEVADE)
UPDATE schools SET inep_code = '227897' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROMORAR' AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '227897');

-- EM BERNARDO FERREIRA GUIMARÃES (RIO PIRACICABA)
UPDATE schools SET inep_code = '103748' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM BERNARDO FERREIRA GUIMARÃES' AND UPPER(TRIM(city)) = 'RIO PIRACICABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103748');

-- EM CÓRREGO SÃO MIGUEL (RIO PIRACICABA)
UPDATE schools SET inep_code = '339490' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CÓRREGO SÃO MIGUEL' AND UPPER(TRIM(city)) = 'RIO PIRACICABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '339490');

-- EM MURILLO GARCIA MOREIRA (RIO PIRACICABA)
UPDATE schools SET inep_code = '103705' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MURILLO GARCIA MOREIRA' AND UPPER(TRIM(city)) = 'RIO PIRACICABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103705');

-- CENTRO EDUCACIONAL MUNICIPAL DE SÃO GONÇALO DO RIO ABAIXO (SÃO GONÇALO DO RIO ABAIXO)
UPDATE schools SET inep_code = '347221' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL MUNICIPAL DE SÃO GONÇALO DO RIO ABAIXO' AND UPPER(TRIM(city)) = 'SÃO GONÇALO DO RIO ABAIXO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '347221');

-- EM MARIA DE LOURDES DUARTE MOREIRA DOS SANTOS (SÃO GONÇALO DO RIO ABAIXO)
UPDATE schools SET inep_code = '345032' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA DE LOURDES DUARTE MOREIRA DOS SANTOS' AND UPPER(TRIM(city)) = 'SÃO GONÇALO DO RIO ABAIXO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '345032');

-- EM EUCLIDES FERREIRA DE SÁ (TRÊS PONTAS)
UPDATE schools SET inep_code = '105201' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM EUCLIDES FERREIRA DE SÁ' AND UPPER(TRIM(city)) = 'TRÊS PONTAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '105201');

-- CENTRO EDUCACIONAL MUNICIPAL PROFESSOR ALCIDES R PEREIRA (ITABIRITO)
UPDATE schools SET inep_code = '107972' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL MUNICIPAL PROFESSOR ALCIDES R PEREIRA' AND UPPER(TRIM(city)) = 'ITABIRITO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '107972');

-- EM ANA AMÉLIA QUEIROZ (ITABIRITO)
UPDATE schools SET inep_code = '332976' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANA AMÉLIA QUEIROZ' AND UPPER(TRIM(city)) = 'ITABIRITO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '332976');

-- EM JOSÉ FERREIRA BASTOS (ITABIRITO)
UPDATE schools SET inep_code = '215406' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ FERREIRA BASTOS' AND UPPER(TRIM(city)) = 'ITABIRITO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '215406');

-- EM MANOEL SALVADOR DE OLIVEIRA (ITABIRITO)
UPDATE schools SET inep_code = '106194' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MANOEL SALVADOR DE OLIVEIRA' AND UPPER(TRIM(city)) = 'ITABIRITO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106194');

-- CEMPA - CENTRO DE  EDUCAÇÃO MUNICIPAL PADRE AVELAR (MARIANA)
UPDATE schools SET inep_code = '227960' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CEMPA - CENTRO DE  EDUCAÇÃO MUNICIPAL PADRE AVELAR' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '227960');

-- EM BENTO RODRIGUES (MARIANA)
UPDATE schools SET inep_code = '106241' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM BENTO RODRIGUES' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106241');

-- EM CÔNEGO PAULO DILÁSCIO (MARIANA)
UPDATE schools SET inep_code = '107158' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CÔNEGO PAULO DILÁSCIO' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '107158');

-- EM DANTE LUIZ DOS SANTOS (MARIANA)
UPDATE schools SET inep_code = '107174' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DANTE LUIZ DOS SANTOS' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '107174');

-- EM DE BARRO  BRANCO (MARIANA)
UPDATE schools SET inep_code = '107301' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DE BARRO  BRANCO' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '107301');

-- EM DE MAINART (MARIANA)
UPDATE schools SET inep_code = '107336' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DE MAINART' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '107336');

-- EM DOM LUCIANO PEDRO MENDES DE ALMEIDA (MARIANA)
UPDATE schools SET inep_code = '343021' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOM LUCIANO PEDRO MENDES DE ALMEIDA' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '343021');

-- EM DOM OSCAR DE OLIVEIRA (MARIANA)
UPDATE schools SET inep_code = '321524' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOM OSCAR DE OLIVEIRA' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '321524');

-- EM JOAQUIM EMÍLIO BAPTISTA (MARIANA)
UPDATE schools SET inep_code = '107247' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOAQUIM EMÍLIO BAPTISTA' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '107247');

-- EM PADRE ANTÔNIO GABRIEL DE CARVALHO (MARIANA)
UPDATE schools SET inep_code = '106356' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PADRE ANTÔNIO GABRIEL DE CARVALHO' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106356');

-- EM PARACATU DE BAIXO (MARIANA)
UPDATE schools SET inep_code = '107280' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PARACATU DE BAIXO' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '107280');

-- EM PROFA CELINA CÉLIA GOMES (MARIANA)
UPDATE schools SET inep_code = '107204' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFA CELINA CÉLIA GOMES' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '107204');

-- EM SERRA DO CARMO (MARIANA)
UPDATE schools SET inep_code = '107352' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SERRA DO CARMO' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '107352');

-- EM SINHÔ MACHADO (MARIANA)
UPDATE schools SET inep_code = '106402' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SINHÔ MACHADO' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106402');

-- EM WILSON PIMENTA FERREIRA (MARIANA)
UPDATE schools SET inep_code = '243957' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM WILSON PIMENTA FERREIRA' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '243957');

-- EM ALEIJADINHO (OURO PRETO)
UPDATE schools SET inep_code = '106712' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ALEIJADINHO' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106712');

-- EM BENEDITO XAVIER (OURO PRETO)
UPDATE schools SET inep_code = '106682' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM BENEDITO XAVIER' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106682');

-- EM DE LAVRAS NOVAS (OURO PRETO)
UPDATE schools SET inep_code = '106615' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DE LAVRAS NOVAS' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106615');

-- EM DOUTOR ALVES DE BRITO (OURO PRETO)
UPDATE schools SET inep_code = '106704' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOUTOR ALVES DE BRITO' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106704');

-- EM DOUTOR PEDROSA (OURO PRETO)
UPDATE schools SET inep_code = '106739' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOUTOR PEDROSA' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106739');

-- EM IZAURA MENDES (OURO PRETO)
UPDATE schools SET inep_code = '107441' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM IZAURA MENDES' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '107441');

-- EM MAJOR RAIMUNDO FELICÍSSIMO (OURO PRETO)
UPDATE schools SET inep_code = '106623' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MAJOR RAIMUNDO FELICÍSSIMO' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106623');

-- EM MONSENHOR JOÃO CASTILHO BARBOSA (OURO PRETO)
UPDATE schools SET inep_code = '106534' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MONSENHOR JOÃO CASTILHO BARBOSA' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106534');

-- EM MONSENHOR RAFAEL (OURO PRETO)
UPDATE schools SET inep_code = '106691' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MONSENHOR RAFAEL' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106691');

-- EM PADRE CARMÉLIO AUGUSTO TEIXEIRA (OURO PRETO)
UPDATE schools SET inep_code = '106518' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PADRE CARMÉLIO AUGUSTO TEIXEIRA' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106518');

-- EM PROFESSORA HAYDÉE ANTUNES (OURO PRETO)
UPDATE schools SET inep_code = '107573' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA HAYDÉE ANTUNES' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '107573');

-- EM PROFESSORA JUVENTINA DRUMOND (OURO PRETO)
UPDATE schools SET inep_code = '107468' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA JUVENTINA DRUMOND' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '107468');

-- EM TOMÁS ANTÔNIO GONZAGA (OURO PRETO)
UPDATE schools SET inep_code = '106593' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM TOMÁS ANTÔNIO GONZAGA' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106593');

-- EM SENADOR SOUZA VIANA (ABAETÉ)
UPDATE schools SET inep_code = '316962' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SENADOR SOUZA VIANA' AND UPPER(TRIM(city)) = 'ABAETÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '316962');

-- EM GERALDO DE ASSIS (MARTINHO CAMPOS)
UPDATE schools SET inep_code = '256226' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM GERALDO DE ASSIS' AND UPPER(TRIM(city)) = 'MARTINHO CAMPOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '256226');

-- EM DONA MARIA DO CARMO ÁLVARES SILVA (MORADA NOVA DE MINAS)
UPDATE schools SET inep_code = '268755' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DONA MARIA DO CARMO ÁLVARES SILVA' AND UPPER(TRIM(city)) = 'MORADA NOVA DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '268755');

-- CAIC  EM PROFESSORA AMÉLIA GUIMARÃES (PARÁ DE MINAS)
UPDATE schools SET inep_code = '251020' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CAIC  EM PROFESSORA AMÉLIA GUIMARÃES' AND UPPER(TRIM(city)) = 'PARÁ DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '251020');

-- EM DONA COTINHA (PARÁ DE MINAS)
UPDATE schools SET inep_code = '226947' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DONA COTINHA' AND UPPER(TRIM(city)) = 'PARÁ DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '226947');

-- EM PROFESSORA IZALTINA M MEIRELES (PARÁ DE MINAS)
UPDATE schools SET inep_code = '251046' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA IZALTINA M MEIRELES' AND UPPER(TRIM(city)) = 'PARÁ DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '251046');

-- EM SÃO JUDAS TADEU (PARÁ DE MINAS)
UPDATE schools SET inep_code = '352233' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SÃO JUDAS TADEU' AND UPPER(TRIM(city)) = 'PARÁ DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '352233');

-- EM LUÍS MACHADO FILHO (SERRA DA SAUDADE)
UPDATE schools SET inep_code = '274224' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM LUÍS MACHADO FILHO' AND UPPER(TRIM(city)) = 'SERRA DA SAUDADE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '274224');

-- CAIC EM ISRAEL PINHEIRO (JOÃO PINHEIRO)
UPDATE schools SET inep_code = '111660' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CAIC EM ISRAEL PINHEIRO' AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '111660');

-- EM DE VEREDAS (JOÃO PINHEIRO)
UPDATE schools SET inep_code = '108791' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DE VEREDAS' AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108791');

-- EM EDMUNDO LOURENÇO (JOÃO PINHEIRO)
UPDATE schools SET inep_code = '112178' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM EDMUNDO LOURENÇO' AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '112178');

-- EM FREI PATRÍCIO (JOÃO PINHEIRO)
UPDATE schools SET inep_code = '108774' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM FREI PATRÍCIO' AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108774');

-- EM PROFESSORA CLEUSA TEREZA ANDRADE (JOÃO PINHEIRO)
UPDATE schools SET inep_code = '111988' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA CLEUSA TEREZA ANDRADE' AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '111988');

-- EM AFONSO NOVAIS PINTO (PARACATU)
UPDATE schools SET inep_code = '112275' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM AFONSO NOVAIS PINTO' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '112275');

-- EM ALTINA DE PAULA SOUZA (PARACATU)
UPDATE schools SET inep_code = '112496' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ALTINA DE PAULA SOUZA' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '112496');

-- EM ARQUIMEDES CÂNDIDO MEIRELES (PARACATU)
UPDATE schools SET inep_code = '112615' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ARQUIMEDES CÂNDIDO MEIRELES' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '112615');

-- EM BERNARDINO DE FARIA PEREIRA (PARACATU)
UPDATE schools SET inep_code = '112631' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM BERNARDINO DE FARIA PEREIRA' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '112631');

-- EM CACILDA CAETANO DE SOUZA (PARACATU)
UPDATE schools SET inep_code = '208329' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CACILDA CAETANO DE SOUZA' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '208329');

-- EM CORACI MEIRELES OLIVEIRA (PARACATU)
UPDATE schools SET inep_code = '236381' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CORACI MEIRELES OLIVEIRA' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '236381');

-- EM GIDALTE MARIA DOS SANTOS (PARACATU)
UPDATE schools SET inep_code = '220833' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM GIDALTE MARIA DOS SANTOS' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '220833');

-- EM JOSÉ PALMA (PARACATU)
UPDATE schools SET inep_code = '112623' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ PALMA' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '112623');

-- EM PEDRO SILVA NEIVA (PARACATU)
UPDATE schools SET inep_code = '327549' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PEDRO SILVA NEIVA' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '327549');

-- EM PROFESSORA ADA SANTANA RIBEIRO (PARACATU)
UPDATE schools SET inep_code = '108944' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA ADA SANTANA RIBEIRO' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108944');

-- EM PROFESSORA MARCIA MACEDO MEIRELES - CAIC (PARACATU)
UPDATE schools SET inep_code = '249246' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA MARCIA MACEDO MEIRELES - CAIC' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '249246');

-- EM PROFESSORA MARIA TRINDADE RODRIGUES (PARACATU)
UPDATE schools SET inep_code = '108936' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA MARIA TRINDADE RODRIGUES' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108936');

-- EM RAIMUNDO JOSÉ DE SANTANA (PARACATU)
UPDATE schools SET inep_code = '112861' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM RAIMUNDO JOSÉ DE SANTANA' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '112861');

-- EM CALDEIRA BRANT (VAZANTE)
UPDATE schools SET inep_code = '109207' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CALDEIRA BRANT' AND UPPER(TRIM(city)) = 'VAZANTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '109207');

-- EM DR MARTINHO CAMPOS (VAZANTE)
UPDATE schools SET inep_code = '114588' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DR MARTINHO CAMPOS' AND UPPER(TRIM(city)) = 'VAZANTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '114588');

-- EM EMÍLIO ALVES RIOS (VAZANTE)
UPDATE schools SET inep_code = '236390' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM EMÍLIO ALVES RIOS' AND UPPER(TRIM(city)) = 'VAZANTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '236390');

-- EM NAIR DE MELO FRANCO RIBEIRO (VAZANTE)
UPDATE schools SET inep_code = '109142' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM NAIR DE MELO FRANCO RIBEIRO' AND UPPER(TRIM(city)) = 'VAZANTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '109142');

-- EM DO TAQUARAL (CARMO DO RIO CLARO)
UPDATE schools SET inep_code = '116386' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DO TAQUARAL' AND UPPER(TRIM(city)) = 'CARMO DO RIO CLARO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '116386');

-- EM LÍDIO JOSÉ MARQUES (CARMO DO RIO CLARO)
UPDATE schools SET inep_code = '115045' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM LÍDIO JOSÉ MARQUES' AND UPPER(TRIM(city)) = 'CARMO DO RIO CLARO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115045');

-- EM SANTA LUZIA (CARMO DO RIO CLARO)
UPDATE schools SET inep_code = '116432' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SANTA LUZIA' AND UPPER(TRIM(city)) = 'CARMO DO RIO CLARO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '116432');

-- EM SÃO JOSÉ (CARMO DO RIO CLARO)
UPDATE schools SET inep_code = '116351' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SÃO JOSÉ' AND UPPER(TRIM(city)) = 'CARMO DO RIO CLARO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '116351');

-- EM RAFAEL JOSÉ ALVES (CÓRREGO FUNDO)
UPDATE schools SET inep_code = '116815' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM RAFAEL JOSÉ ALVES' AND UPPER(TRIM(city)) = 'CÓRREGO FUNDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '116815');

-- EM LOURDES APARECIDA DA SILVA (DELFINÓPOLIS)
UPDATE schools SET inep_code = '115169' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM LOURDES APARECIDA DA SILVA' AND UPPER(TRIM(city)) = 'DELFINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115169');

-- EM PROFESSORA MARIA DIAS MACHADO (DELFINÓPOLIS)
UPDATE schools SET inep_code = '115134' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA MARIA DIAS MACHADO' AND UPPER(TRIM(city)) = 'DELFINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115134');

-- EM MARIA EULÁLIA DE JESUS (DORESÓPOLIS)
UPDATE schools SET inep_code = '267201' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA EULÁLIA DE JESUS' AND UPPER(TRIM(city)) = 'DORESÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '267201');

-- EM ARLINDO DE MELLO (FORMIGA)
UPDATE schools SET inep_code = '222747' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ARLINDO DE MELLO' AND UPPER(TRIM(city)) = 'FORMIGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '222747');

-- EM CENTRO DE ATENÇÃO INTEGRAL A CRIANÇA - CAIC (FORMIGA)
UPDATE schools SET inep_code = '242357' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CENTRO DE ATENÇÃO INTEGRAL A CRIANÇA - CAIC' AND UPPER(TRIM(city)) = 'FORMIGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '242357');

-- EM FLORÊNCIO RODRIGUES NUNES (FORMIGA)
UPDATE schools SET inep_code = '115355' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM FLORÊNCIO RODRIGUES NUNES' AND UPPER(TRIM(city)) = 'FORMIGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '115355');

-- EM JOSÉ ANTÔNIO DO COUTO (FORMIGA)
UPDATE schools SET inep_code = '342971' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ ANTÔNIO DO COUTO' AND UPPER(TRIM(city)) = 'FORMIGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342971');

-- EM JOSÉ JOÃO DE MELO (FORMIGA)
UPDATE schools SET inep_code = '116874' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ JOÃO DE MELO' AND UPPER(TRIM(city)) = 'FORMIGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '116874');

-- EM MIRALDA DA SILVA CARVALHO (FORMIGA)
UPDATE schools SET inep_code = '215040' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MIRALDA DA SILVA CARVALHO' AND UPPER(TRIM(city)) = 'FORMIGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '215040');

-- EM  DR MANOEL PATTI (PASSOS)
UPDATE schools SET inep_code = '117498' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM  DR MANOEL PATTI' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '117498');

-- EM CEL AZARIAS DE MELO (PASSOS)
UPDATE schools SET inep_code = '117218' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CEL AZARIAS DE MELO' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '117218');

-- EM GERALDA CÂNDIDA DE OLIVEIRA (PASSOS)
UPDATE schools SET inep_code = '117561' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM GERALDA CÂNDIDA DE OLIVEIRA' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '117561');

-- EM OILDA VALÉRIA SILVEIRA COELHO (PASSOS)
UPDATE schools SET inep_code = '117447' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM OILDA VALÉRIA SILVEIRA COELHO' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '117447');

-- EM PROF HILARINO MORAES (PASSOS)
UPDATE schools SET inep_code = '117471' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROF HILARINO MORAES' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '117471');

-- EM PROFESSORA JALILE BARBOSA CALIXTO (PASSOS)
UPDATE schools SET inep_code = '243655' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA JALILE BARBOSA CALIXTO' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '243655');

-- EM JOSÉ BALDOÍNO BORGES (MATUTINA)
UPDATE schools SET inep_code = '269131' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ BALDOÍNO BORGES' AND UPPER(TRIM(city)) = 'MATUTINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '269131');

-- EM ABDIAS CALDEIRA BRANT (PATOS DE MINAS)
UPDATE schools SET inep_code = '118907' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ABDIAS CALDEIRA BRANT' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '118907');

-- EM CÔNEGO GETÚLIO (PATOS DE MINAS)
UPDATE schools SET inep_code = '121347' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CÔNEGO GETÚLIO' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '121347');

-- EM DELFIM MOREIRA (PATOS DE MINAS)
UPDATE schools SET inep_code = '121380' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DELFIM MOREIRA' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '121380');

-- EM FREI LEOPOLDO (PATOS DE MINAS)
UPDATE schools SET inep_code = '118931' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM FREI LEOPOLDO' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '118931');

-- EM GINO ANDRÉ BARBOSA (PATOS DE MINAS)
UPDATE schools SET inep_code = '121746' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM GINO ANDRÉ BARBOSA' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '121746');

-- EM JEREMIAS F DE PAULA (PATOS DE MINAS)
UPDATE schools SET inep_code = '121525' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JEREMIAS F DE PAULA' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '121525');

-- EM JOÃO GUALBERTO AMORIM JÚNIOR (PATOS DE MINAS)
UPDATE schools SET inep_code = '121193' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOÃO GUALBERTO AMORIM JÚNIOR' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '121193');

-- EM JOSÉ PAULO DE AMORIM (PATOS DE MINAS)
UPDATE schools SET inep_code = '119075' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ PAULO DE AMORIM' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '119075');

-- EM MAJOR AUGUSTO PORTO (PATOS DE MINAS)
UPDATE schools SET inep_code = '119041' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MAJOR AUGUSTO PORTO' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '119041');

-- EM MARIA INÊS RUBINGER DE QUEIROZ RODRIGUES (PATOS DE MINAS)
UPDATE schools SET inep_code = '265331' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA INÊS RUBINGER DE QUEIROZ RODRIGUES' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '265331');

-- EM NORMA BORGES BELUCO (PATOS DE MINAS)
UPDATE schools SET inep_code = '265349' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM NORMA BORGES BELUCO' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '265349');

-- EM PREF JAQUES CORREA DA COSTA (PATOS DE MINAS)
UPDATE schools SET inep_code = '249084' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PREF JAQUES CORREA DA COSTA' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '249084');

-- EM PROF ARISTIDES MEMÓRIA (PATOS DE MINAS)
UPDATE schools SET inep_code = '245381' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROF ARISTIDES MEMÓRIA' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '245381');

-- EM PROFA MARLUCE M OLIVEIRA SCHER (PATOS DE MINAS)
UPDATE schools SET inep_code = '323560' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFA MARLUCE M OLIVEIRA SCHER' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '323560');

-- EM OSVALDO CRUZ (PRESIDENTE OLEGÁRIO)
UPDATE schools SET inep_code = '122190' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM OSVALDO CRUZ' AND UPPER(TRIM(city)) = 'PRESIDENTE OLEGÁRIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '122190');

-- EM PROFESSORA CARMEM CELINA NOGUEIRA DE CASTILHO (PRESIDENTE OLEGÁRIO)
UPDATE schools SET inep_code = '119156' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA CARMEM CELINA NOGUEIRA DE CASTILHO' AND UPPER(TRIM(city)) = 'PRESIDENTE OLEGÁRIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '119156');

-- EM SÃO GERALDO (PRESIDENTE OLEGÁRIO)
UPDATE schools SET inep_code = '122581' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SÃO GERALDO' AND UPPER(TRIM(city)) = 'PRESIDENTE OLEGÁRIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '122581');

-- EM PADRE GOULART II (RIO PARANAÍBA)
UPDATE schools SET inep_code = '119296' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PADRE GOULART II' AND UPPER(TRIM(city)) = 'RIO PARANAÍBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '119296');

-- EM CORONEL SEBASTIÃO FONTE BOA (SANTA ROSA DA SERRA)
UPDATE schools SET inep_code = '122653' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CORONEL SEBASTIÃO FONTE BOA' AND UPPER(TRIM(city)) = 'SANTA ROSA DA SERRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '122653');

-- EM OLINTO GONÇALVES DE MELO (SÃO GONÇALO DO ABAETÉ)
UPDATE schools SET inep_code = '122955' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM OLINTO GONÇALVES DE MELO' AND UPPER(TRIM(city)) = 'SÃO GONÇALO DO ABAETÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '122955');

-- EM PROFESSORA MARIA JOSÉ DUTRA (SÃO GONÇALO DO ABAETÉ)
UPDATE schools SET inep_code = '119482' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA MARIA JOSÉ DUTRA' AND UPPER(TRIM(city)) = 'SÃO GONÇALO DO ABAETÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '119482');

-- EM LUCIANO BORGES DE QUEIROZ (VARJÃO DE MINAS)
UPDATE schools SET inep_code = '265365' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM LUCIANO BORGES DE QUEIROZ' AND UPPER(TRIM(city)) = 'VARJÃO DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '265365');

-- EM MOISÉS BASÍLIO DE CAMARGOS (CRUZEIRO DA FORTALEZA)
UPDATE schools SET inep_code = '198919' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MOISÉS BASÍLIO DE CAMARGOS' AND UPPER(TRIM(city)) = 'CRUZEIRO DA FORTALEZA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '198919');

-- EM NOSSA SENHORA DE FÁTIMA (CRUZEIRO DA FORTALEZA)
UPDATE schools SET inep_code = '198901' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM NOSSA SENHORA DE FÁTIMA' AND UPPER(TRIM(city)) = 'CRUZEIRO DA FORTALEZA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '198901');

-- EM PEDRO ALVES DE PAIVA (IBIÁ)
UPDATE schools SET inep_code = '159107' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PEDRO ALVES DE PAIVA' AND UPPER(TRIM(city)) = 'IBIÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159107');

-- EM QUILOMBO DO AMBRÓSIO (IBIÁ)
UPDATE schools SET inep_code = '253596' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM QUILOMBO DO AMBRÓSIO' AND UPPER(TRIM(city)) = 'IBIÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253596');

-- EM STA BÁRBARA (IBIÁ)
UPDATE schools SET inep_code = '162442' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM STA BÁRBARA' AND UPPER(TRIM(city)) = 'IBIÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '162442');

-- EM STA TEREZINHA (IBIÁ)
UPDATE schools SET inep_code = '162591' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM STA TEREZINHA' AND UPPER(TRIM(city)) = 'IBIÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '162591');

-- EM TATÃO ANACLETO (IBIÁ)
UPDATE schools SET inep_code = '159123' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM TATÃO ANACLETO' AND UPPER(TRIM(city)) = 'IBIÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159123');

-- COL MUN PROF OLÍMPIO DOS SANTOS (PATROCÍNIO)
UPDATE schools SET inep_code = '200221' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COL MUN PROF OLÍMPIO DOS SANTOS' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '200221');

-- CONSERVATÓRIO MUNICIPAL DE MÚSICA DR JOSÉ FIGUEIREDO (PATROCÍNIO)
UPDATE schools SET inep_code = '343196' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CONSERVATÓRIO MUNICIPAL DE MÚSICA DR JOSÉ FIGUEIREDO' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '343196');

-- EM ELISA VIANA BOTELHO (PATROCÍNIO)
UPDATE schools SET inep_code = '199818' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ELISA VIANA BOTELHO' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '199818');

-- EM JOÃO BATISTA ROMÃO (PATROCÍNIO)
UPDATE schools SET inep_code = '199630' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOÃO BATISTA ROMÃO' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '199630');

-- EM JOAQUIM MARTINS (PATROCÍNIO)
UPDATE schools SET inep_code = '199737' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOAQUIM MARTINS' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '199737');

-- EM MARIA ISABEL QUEIROZ ALVES - CAIC (PATROCÍNIO)
UPDATE schools SET inep_code = '248291' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA ISABEL QUEIROZ ALVES - CAIC' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '248291');

-- EM PROF AFRÂNIO AMARAL (PATROCÍNIO)
UPDATE schools SET inep_code = '261726' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROF AFRÂNIO AMARAL' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '261726');

-- EM DONA RITA SANTOS BRAGA (PIRAPORA)
UPDATE schools SET inep_code = '221686' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DONA RITA SANTOS BRAGA' AND UPPER(TRIM(city)) = 'PIRAPORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '221686');

-- EM GABRIEL NUNES DE AZEVEDO (VÁRZEA DA PALMA)
UPDATE schools SET inep_code = '304417' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM GABRIEL NUNES DE AZEVEDO' AND UPPER(TRIM(city)) = 'VÁRZEA DA PALMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '304417');

-- EM PROFESSORA YOLANDA DIAS RIBEIRO (ALTEROSA)
UPDATE schools SET inep_code = '123692' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA YOLANDA DIAS RIBEIRO' AND UPPER(TRIM(city)) = 'ALTEROSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '123692');

-- EM ISAURA VILELA BRASILEIRO (BOTELHOS)
UPDATE schools SET inep_code = '123994' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ISAURA VILELA BRASILEIRO' AND UPPER(TRIM(city)) = 'BOTELHOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '123994');

-- COLÉGIO MUNICIPAL URIEL ALVIM (CALDAS)
UPDATE schools SET inep_code = '125741' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MUNICIPAL URIEL ALVIM' AND UPPER(TRIM(city)) = 'CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '125741');

-- COLÉGIO COMERCIAL PROFESSORA ILMA AMBROGI PRADO (CAMPESTRE)
UPDATE schools SET inep_code = '127884' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO COMERCIAL PROFESSORA ILMA AMBROGI PRADO' AND UPPER(TRIM(city)) = 'CAMPESTRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '127884');

-- EM CÔNEGO ARTUR (CAMPESTRE)
UPDATE schools SET inep_code = '277886' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CÔNEGO ARTUR' AND UPPER(TRIM(city)) = 'CAMPESTRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '277886');

-- EM NO BAIRRO POSSES (CAMPESTRE)
UPDATE schools SET inep_code = '124281' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM NO BAIRRO POSSES' AND UPPER(TRIM(city)) = 'CAMPESTRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124281');

-- EM PEDRA GRANDE (CAMPESTRE)
UPDATE schools SET inep_code = '126039' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PEDRA GRANDE' AND UPPER(TRIM(city)) = 'CAMPESTRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '126039');

-- EM TIRADENTES (CONCEIÇÃO DA APARECIDA)
UPDATE schools SET inep_code = '124362' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM TIRADENTES' AND UPPER(TRIM(city)) = 'CONCEIÇÃO DA APARECIDA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124362');

-- EM MARIA JOSÉ GODOY (NOVA RESENDE)
UPDATE schools SET inep_code = '124699' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA JOSÉ GODOY' AND UPPER(TRIM(city)) = 'NOVA RESENDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124699');

-- CAIC EM PROF ARINO FERREIRA PINTO (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '249157' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CAIC EM PROF ARINO FERREIRA PINTO' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '249157');

-- CONSERVATÓRIO MÚSICA ANTÔNIO FERRUCIO VIVIANI (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '245054' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CONSERVATÓRIO MÚSICA ANTÔNIO FERRUCIO VIVIANI' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '245054');

-- EM ALVINO HOSKEN DE OLIVEIRA (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '124711' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ALVINO HOSKEN DE OLIVEIRA' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124711');

-- EM DONA LÚCIA SACOMANN JUNQUEIRA (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '127469' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DONA LÚCIA SACOMANN JUNQUEIRA' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '127469');

-- EM DONA MARIQUINHAS BROCHADO (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '124907' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DONA MARIQUINHAS BROCHADO' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124907');

-- EM DR HAROLDO AFFONSO JUNQUEIRA (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '124702' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DR HAROLDO AFFONSO JUNQUEIRA' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124702');

-- EM DR JOSÉ VARGAS DE SOUZA (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '127329' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DR JOSÉ VARGAS DE SOUZA' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '127329');

-- EM DR PEDRO AFONSO JUNQUEIRA (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '124753' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DR PEDRO AFONSO JUNQUEIRA' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124753');

-- EM IRMÃO JOSÉ GREGÓRIO (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '127337' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM IRMÃO JOSÉ GREGÓRIO' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '127337');

-- EM JOSÉ AVELINO DE MELO (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '127353' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ AVELINO DE MELO' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '127353');

-- EM JOSÉ MAMUD ASSAN (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '351199' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ MAMUD ASSAN' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '351199');

-- EM JOSÉ RAPHAEL DOS SANTOS NETTO (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '347485' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ RAPHAEL DOS SANTOS NETTO' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '347485');

-- EM MARIA OVÍDIA JUNQUEIRA (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '124869' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA OVÍDIA JUNQUEIRA' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124869');

-- EM PRESIDENTE WASHINGTON LUÍS (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '124842' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PRESIDENTE WASHINGTON LUÍS' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124842');

-- EM PROF ANTÔNIO SÉRGIO TEIXEIRA (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '124885' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROF ANTÔNIO SÉRGIO TEIXEIRA' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124885');

-- EM PROFA CARMÉLIA DE CASTRO (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '124796' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFA CARMÉLIA DE CASTRO' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124796');

-- EM PROFA NICOLINA BERNARDO (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '127396' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFA NICOLINA BERNARDO' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '127396');

-- EM PROFESSORA EDIR FRAYHA (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '232491' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA EDIR FRAYHA' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '232491');

-- EM RAPHAEL SANCHES (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '127361' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM RAPHAEL SANCHES' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '127361');

-- EM SÉRGIO DE FREITAS PACHECO (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '127451' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SÉRGIO DE FREITAS PACHECO' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '127451');

-- EM VITALINA ROSSI (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '310182' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM VITALINA ROSSI' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310182');

-- EM WILSON HEDY MOLINARI (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '124834' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM WILSON HEDY MOLINARI' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124834');

-- EM DOUTOR CUSTÓDIO DE PAULA RODRIGUES (ABRE CAMPO)
UPDATE schools SET inep_code = '305855' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOUTOR CUSTÓDIO DE PAULA RODRIGUES' AND UPPER(TRIM(city)) = 'ABRE CAMPO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305855');

-- EM ANTÔNIO FIRMINO BITENCOURT (AMPARO DO SERRA)
UPDATE schools SET inep_code = '256242' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANTÔNIO FIRMINO BITENCOURT' AND UPPER(TRIM(city)) = 'AMPARO DO SERRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '256242');

-- EM OLÍMPIO LOPES BAIÃO (AMPARO DO SERRA)
UPDATE schools SET inep_code = '128295' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM OLÍMPIO LOPES BAIÃO' AND UPPER(TRIM(city)) = 'AMPARO DO SERRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128295');

-- EM ARNALDO DIAS DE ANDRADE FILHO (CAJURI)
UPDATE schools SET inep_code = '270563' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ARNALDO DIAS DE ANDRADE FILHO' AND UPPER(TRIM(city)) = 'CAJURI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '270563');

-- EM DR JUAREZ DE SOUZA CARMO (CAJURI)
UPDATE schools SET inep_code = '128473' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DR JUAREZ DE SOUZA CARMO' AND UPPER(TRIM(city)) = 'CAJURI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128473');

-- EM CAMILO MARTINS DE MOURA (GUARACIABA)
UPDATE schools SET inep_code = '131237' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CAMILO MARTINS DE MOURA' AND UPPER(TRIM(city)) = 'GUARACIABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '131237');

-- EM VILMA HELENA SACRAMENTO BAIÃO (JEQUERI)
UPDATE schools SET inep_code = '324795' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM VILMA HELENA SACRAMENTO BAIÃO' AND UPPER(TRIM(city)) = 'JEQUERI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '324795');

-- EM PE ALÍPIO MARTINS PINHEIRO (ORATÓRIOS)
UPDATE schools SET inep_code = '271926' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PE ALÍPIO MARTINS PINHEIRO' AND UPPER(TRIM(city)) = 'ORATÓRIOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '271926');

-- EM AGENOR BIBIANO DO CARMO (PEDRA BONITA)
UPDATE schools SET inep_code = '130311' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM AGENOR BIBIANO DO CARMO' AND UPPER(TRIM(city)) = 'PEDRA BONITA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '130311');

-- EM JOÃO VIEIRA DE QUEIROZ (PEDRA BONITA)
UPDATE schools SET inep_code = '130354' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOÃO VIEIRA DE QUEIROZ' AND UPPER(TRIM(city)) = 'PEDRA BONITA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '130354');

-- EM PEDRO VÍTOR DE OLIVEIRA (PEDRA BONITA)
UPDATE schools SET inep_code = '130419' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PEDRO VÍTOR DE OLIVEIRA' AND UPPER(TRIM(city)) = 'PEDRA BONITA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '130419');

-- EM JOSÉ MARIA DA FONSECA (PONTE NOVA)
UPDATE schools SET inep_code = '131954' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ MARIA DA FONSECA' AND UPPER(TRIM(city)) = 'PONTE NOVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '131954');

-- EM LUIZ MARTINS SOARES SOBRINHO (PONTE NOVA)
UPDATE schools SET inep_code = '129020' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM LUIZ MARTINS SOARES SOBRINHO' AND UPPER(TRIM(city)) = 'PONTE NOVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129020');

-- EM N SRA DO ROSÁRIO (PONTE NOVA)
UPDATE schools SET inep_code = '321559' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM N SRA DO ROSÁRIO' AND UPPER(TRIM(city)) = 'PONTE NOVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '321559');

-- EM PE RAFAEL FARACI (PONTE NOVA)
UPDATE schools SET inep_code = '129178' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PE RAFAEL FARACI' AND UPPER(TRIM(city)) = 'PONTE NOVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129178');

-- EM REINALDO ALVES COSTA (PONTE NOVA)
UPDATE schools SET inep_code = '129089' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM REINALDO ALVES COSTA' AND UPPER(TRIM(city)) = 'PONTE NOVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129089');

-- EM SENADOR MIGUEL LANA (PONTE NOVA)
UPDATE schools SET inep_code = '129119' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SENADOR MIGUEL LANA' AND UPPER(TRIM(city)) = 'PONTE NOVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129119');

-- EM CEL JOÃO DOMINGOS (RAUL SOARES)
UPDATE schools SET inep_code = '129232' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CEL JOÃO DOMINGOS' AND UPPER(TRIM(city)) = 'RAUL SOARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129232');

-- EM DR JOSÉ MIRANDA CHAVES (RIO CASCA)
UPDATE schools SET inep_code = '129372' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DR JOSÉ MIRANDA CHAVES' AND UPPER(TRIM(city)) = 'RIO CASCA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129372');

-- EM ITAGIBA MARTINS CHAVES (RIO CASCA)
UPDATE schools SET inep_code = '129411' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ITAGIBA MARTINS CHAVES' AND UPPER(TRIM(city)) = 'RIO CASCA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129411');

-- EM LOURDES FONSECA ZAIDAN (RIO CASCA)
UPDATE schools SET inep_code = '132667' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM LOURDES FONSECA ZAIDAN' AND UPPER(TRIM(city)) = 'RIO CASCA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '132667');

-- EM SENADOR CUPERTINO (RIO CASCA)
UPDATE schools SET inep_code = '129402' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SENADOR CUPERTINO' AND UPPER(TRIM(city)) = 'RIO CASCA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129402');

-- EM AMARO RIBEIRO GOMES (SANTA CRUZ DO ESCALVADO)
UPDATE schools SET inep_code = '129453' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM AMARO RIBEIRO GOMES' AND UPPER(TRIM(city)) = 'SANTA CRUZ DO ESCALVADO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129453');

-- EM ANTÔNIO LEÔNCIO CARNEIRO (SANTA CRUZ DO ESCALVADO)
UPDATE schools SET inep_code = '129500' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANTÔNIO LEÔNCIO CARNEIRO' AND UPPER(TRIM(city)) = 'SANTA CRUZ DO ESCALVADO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129500');

-- EM JOSÉ GOMES DE SOUZA (SANTA CRUZ DO ESCALVADO)
UPDATE schools SET inep_code = '129496' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ GOMES DE SOUZA' AND UPPER(TRIM(city)) = 'SANTA CRUZ DO ESCALVADO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129496');

-- EM ANTÔNIO CARLOS (TEIXEIRAS)
UPDATE schools SET inep_code = '129682' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANTÔNIO CARLOS' AND UPPER(TRIM(city)) = 'TEIXEIRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129682');

-- CENTRO MUNICIPAL DE EDUCAÇÃO DOUTOR JANUÁRIO DE ANDRADE FONTES (VIÇOSA)
UPDATE schools SET inep_code = '361208' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO MUNICIPAL DE EDUCAÇÃO DOUTOR JANUÁRIO DE ANDRADE FONTES' AND UPPER(TRIM(city)) = 'VIÇOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '361208');

-- EM CORONEL ANTÔNIO DA SILVA BERNARDES (VIÇOSA)
UPDATE schools SET inep_code = '129933' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CORONEL ANTÔNIO DA SILVA BERNARDES' AND UPPER(TRIM(city)) = 'VIÇOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129933');

-- EM DOUTOR ARTHUR BERNARDES (VIÇOSA)
UPDATE schools SET inep_code = '133388' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOUTOR ARTHUR BERNARDES' AND UPPER(TRIM(city)) = 'VIÇOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '133388');

-- EM JOÃO FRANCISCO DA SILVA (VIÇOSA)
UPDATE schools SET inep_code = '129909' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOÃO FRANCISCO DA SILVA' AND UPPER(TRIM(city)) = 'VIÇOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129909');

-- EM MINISTRO EDMUNDO LINS (VIÇOSA)
UPDATE schools SET inep_code = '129925' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MINISTRO EDMUNDO LINS' AND UPPER(TRIM(city)) = 'VIÇOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '129925');

-- EM NOSSA SENHORA DE FÁTIMA (VIÇOSA)
UPDATE schools SET inep_code = '133426' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM NOSSA SENHORA DE FÁTIMA' AND UPPER(TRIM(city)) = 'VIÇOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '133426');

-- EM PADRE FRANCISCO JOSÉ DA SILVA (VIÇOSA)
UPDATE schools SET inep_code = '133434' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PADRE FRANCISCO JOSÉ DA SILVA' AND UPPER(TRIM(city)) = 'VIÇOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '133434');

-- EM ANTÔNIO FERREIRA (ALBERTINA)
UPDATE schools SET inep_code = '123617' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANTÔNIO FERREIRA' AND UPPER(TRIM(city)) = 'ALBERTINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '123617');

-- EM PROFESSOR DOUTOR ONOFRE VARGAS (CAMANDUCAIA)
UPDATE schools SET inep_code = '323179' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR DOUTOR ONOFRE VARGAS' AND UPPER(TRIM(city)) = 'CAMANDUCAIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '323179');

-- EM EVANDRO BRITO DA CUNHA (EXTREMA)
UPDATE schools SET inep_code = '273121' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM EVANDRO BRITO DA CUNHA' AND UPPER(TRIM(city)) = 'EXTREMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '273121');

-- EM JOSÉ SEBASTIÃO MORBIDELLI (EXTREMA)
UPDATE schools SET inep_code = '368377' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ SEBASTIÃO MORBIDELLI' AND UPPER(TRIM(city)) = 'EXTREMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368377');

-- EM MARISTELA CARNIEL ONISTO (EXTREMA)
UPDATE schools SET inep_code = '377643' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARISTELA CARNIEL ONISTO' AND UPPER(TRIM(city)) = 'EXTREMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '377643');

-- EM OSVALDO DE OLIVEIRA (EXTREMA)
UPDATE schools SET inep_code = '311413' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM OSVALDO DE OLIVEIRA' AND UPPER(TRIM(city)) = 'EXTREMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '311413');