-- COLÉGIO SANTA MARIA MINAS - UNIDADE SETE LAGOAS (SETE LAGOAS)
UPDATE schools SET inep_code = '145726' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SANTA MARIA MINAS - UNIDADE SETE LAGOAS' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '145726');

-- COLEGUIUM - UNIDADE DE SETE LAGOAS (SETE LAGOAS)
UPDATE schools SET inep_code = '368679' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLEGUIUM - UNIDADE DE SETE LAGOAS' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368679');

-- ESCOLA TECNICA DE FORMAÇÃO GERENCIAL - UNIFEMM (SETE LAGOAS)
UPDATE schools SET inep_code = '350885' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TECNICA DE FORMAÇÃO GERENCIAL - UNIFEMM' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '350885');

-- ESCOLA TÉCNICA SETE LAGOAS - TECSETE (SETE LAGOAS)
UPDATE schools SET inep_code = '377805' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA SETE LAGOAS - TECSETE' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '377805');

-- GRAU TÉCNICO - UNIDADE SETE LAGOAS (SETE LAGOAS)
UPDATE schools SET inep_code = '376825' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'GRAU TÉCNICO - UNIDADE SETE LAGOAS' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '376825');

-- INSTITUTO ALICE MACIEL (SETE LAGOAS)
UPDATE schools SET inep_code = '145700' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO ALICE MACIEL' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '145700');

-- SENAC UNIDADE DE ENSINO TÉCNICO - CFP SETE LAGOAS (SETE LAGOAS)
UPDATE schools SET inep_code = '312975' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAC UNIDADE DE ENSINO TÉCNICO - CFP SETE LAGOAS' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312975');

-- SENAI SETE LAGOAS FUNDAÇÃO ZERRENNER (SETE LAGOAS)
UPDATE schools SET inep_code = '367079' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI SETE LAGOAS FUNDAÇÃO ZERRENNER' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '367079');

-- SESI OTONI ALVES DA COSTA UNIDADE II (SETE LAGOAS)
UPDATE schools SET inep_code = '268259' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SESI OTONI ALVES DA COSTA UNIDADE II' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '268259');

-- ESCOLA PARTICULAR INTERAÇÃO (ÁGUAS FORMOSAS)
UPDATE schools SET inep_code = '274348' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA PARTICULAR INTERAÇÃO' AND UPPER(TRIM(city)) = 'ÁGUAS FORMOSAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '274348');

-- COOP EDUC CARLOS CHAGAS COOEDUCAR (CARLOS CHAGAS)
UPDATE schools SET inep_code = '279684' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COOP EDUC CARLOS CHAGAS COOEDUCAR' AND UPPER(TRIM(city)) = 'CARLOS CHAGAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '279684');

-- EFACIL ESCOLA FAMÍLIA AGRÍCOLA DE CARAÍ,CATUJI,ITAIPÉ E LADAINHA (ITAIPÉ)
UPDATE schools SET inep_code = '356409' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EFACIL ESCOLA FAMÍLIA AGRÍCOLA DE CARAÍ,CATUJI,ITAIPÉ E LADAINHA' AND UPPER(TRIM(city)) = 'ITAIPÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '356409');

-- ESC COOPERATIVA CEPI (ITAMBACURI)
UPDATE schools SET inep_code = '277240' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESC COOPERATIVA CEPI' AND UPPER(TRIM(city)) = 'ITAMBACURI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '277240');

-- INSTITUTO EDUCACIONAL SÃO FRANCISCO DE ASSIS - IESFA (ITAMBACURI)
UPDATE schools SET inep_code = '266060' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL SÃO FRANCISCO DE ASSIS - IESFA' AND UPPER(TRIM(city)) = 'ITAMBACURI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '266060');

-- INSTITUTO TÉCNICO PROFISSIONAL DE ITAMBACURI (ITAMBACURI)
UPDATE schools SET inep_code = '375390' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO TÉCNICO PROFISSIONAL DE ITAMBACURI' AND UPPER(TRIM(city)) = 'ITAMBACURI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '375390');

-- EFASET - ESCOLA FAMÍLIA AGRÍCOLA DO SETÚBAL (MALACACHETA)
UPDATE schools SET inep_code = '354899' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EFASET - ESCOLA FAMÍLIA AGRÍCOLA DO SETÚBAL' AND UPPER(TRIM(city)) = 'MALACACHETA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '354899');

-- ESCOLA PARTICULAR REINO ENCANTADO (MALACACHETA)
UPDATE schools SET inep_code = '302571' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA PARTICULAR REINO ENCANTADO' AND UPPER(TRIM(city)) = 'MALACACHETA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '302571');

-- MESTEP MALACACHETA ESCOLA TÉCNICA PROFISSIONALIZANTE (MALACACHETA)
UPDATE schools SET inep_code = '356204' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'MESTEP MALACACHETA ESCOLA TÉCNICA PROFISSIONALIZANTE' AND UPPER(TRIM(city)) = 'MALACACHETA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '356204');

-- COLÉGIO SANTO ANTÔNIO (NANUQUE)
UPDATE schools SET inep_code = '157902' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SANTO ANTÔNIO' AND UPPER(TRIM(city)) = 'NANUQUE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '157902');

-- EDUCANDÁRIO CARLOS DRUMOND DE ANDRADE (NANUQUE)
UPDATE schools SET inep_code = '157953' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EDUCANDÁRIO CARLOS DRUMOND DE ANDRADE' AND UPPER(TRIM(city)) = 'NANUQUE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '157953');

-- ESCOLA ADVENTISTA DE NANUQUE (NANUQUE)
UPDATE schools SET inep_code = '157911' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA ADVENTISTA DE NANUQUE' AND UPPER(TRIM(city)) = 'NANUQUE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '157911');

-- ESCOLA AGRÍCOLA TERRA MÃE (NOVO ORIENTE DE MINAS)
UPDATE schools SET inep_code = '299235' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA AGRÍCOLA TERRA MÃE' AND UPPER(TRIM(city)) = 'NOVO ORIENTE DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '299235');

-- ESCOLA ORLANDO TAVARES (PADRE PARAÍSO)
UPDATE schools SET inep_code = '263800' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA ORLANDO TAVARES' AND UPPER(TRIM(city)) = 'PADRE PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '263800');

-- CENTRO EDUCACIONAL CRISTÃO ALPHA BRASIL (TEÓFILO OTONI)
UPDATE schools SET inep_code = '274658' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL CRISTÃO ALPHA BRASIL' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '274658');

-- CETEC- CENTRO DE EDUCAÇÃO TECNOLÓGICA TOP LINE (TEÓFILO OTONI)
UPDATE schools SET inep_code = '339628' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CETEC- CENTRO DE EDUCAÇÃO TECNOLÓGICA TOP LINE' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '339628');

-- COLÉGIO ADVENTISTA DE TEÓFILO OTONI (TEÓFILO OTONI)
UPDATE schools SET inep_code = '347230' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ADVENTISTA DE TEÓFILO OTONI' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '347230');

-- COLÉGIO GENOMA (TEÓFILO OTONI)
UPDATE schools SET inep_code = '356190' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO GENOMA' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '356190');

-- COLÉGIO GENOMA  II (TEÓFILO OTONI)
UPDATE schools SET inep_code = '378496' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO GENOMA  II' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '378496');

-- ESCOLA COOPERATIVA EDUCACIONAL DE TEÓFILO OTONI - COOPED (TEÓFILO OTONI)
UPDATE schools SET inep_code = '242918' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA COOPERATIVA EDUCACIONAL DE TEÓFILO OTONI - COOPED' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '242918');

-- ESCOLA PARTICULAR PEQUENO PRÍNCIPE (TEÓFILO OTONI)
UPDATE schools SET inep_code = '158101' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA PARTICULAR PEQUENO PRÍNCIPE' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158101');

-- ESCOLA SANTO AGOSTINHO (TEÓFILO OTONI)
UPDATE schools SET inep_code = '158143' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SANTO AGOSTINHO' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158143');

-- ESCOLA TÉCNICA EGÍDIO JOSÉ DA SILVA (TEÓFILO OTONI)
UPDATE schools SET inep_code = '306916' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA EGÍDIO JOSÉ DA SILVA' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '306916');

-- INSTITUTO EDUCACIONAL PEQUENO POLEGAR (TEÓFILO OTONI)
UPDATE schools SET inep_code = '365157' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL PEQUENO POLEGAR' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '365157');

-- INSTITUTO SEMEAR (TEÓFILO OTONI)
UPDATE schools SET inep_code = '347426' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO SEMEAR' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '347426');

-- CENTRO EDUCACIONAL DE ERVÁLIA - COLÉGIO CENER (ERVÁLIA)
UPDATE schools SET inep_code = '312096' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL DE ERVÁLIA - COLÉGIO CENER' AND UPPER(TRIM(city)) = 'ERVÁLIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312096');

-- CENTRO REFERENCIAL DE ENSINO EM SAÚDE - UNIDADE ERVÁLIA (ERVÁLIA)
UPDATE schools SET inep_code = '373508' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO REFERENCIAL DE ENSINO EM SAÚDE - UNIDADE ERVÁLIA' AND UPPER(TRIM(city)) = 'ERVÁLIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '373508');

-- COLÉGIO EDUCAR (ERVÁLIA)
UPDATE schools SET inep_code = '364410' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO EDUCAR' AND UPPER(TRIM(city)) = 'ERVÁLIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '364410');

-- ESCOLA FAMÍLIA AGRÍCOLA SERRA DO BRIGADEIRO (ERVÁLIA)
UPDATE schools SET inep_code = '338346' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA FAMÍLIA AGRÍCOLA SERRA DO BRIGADEIRO' AND UPPER(TRIM(city)) = 'ERVÁLIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338346');

-- COLÉGIO REGINA COELI (RIO POMBA)
UPDATE schools SET inep_code = '184292' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO REGINA COELI' AND UPPER(TRIM(city)) = 'RIO POMBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184292');

-- MASTER ÊXITUS (RIO POMBA)
UPDATE schools SET inep_code = '365530' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'MASTER ÊXITUS' AND UPPER(TRIM(city)) = 'RIO POMBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '365530');

-- COLÉGIO EQUIPE DE TOCANTINS (TOCANTINS)
UPDATE schools SET inep_code = '320218' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO EQUIPE DE TOCANTINS' AND UPPER(TRIM(city)) = 'TOCANTINS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '320218');

-- CENTRO EDUCACIONAL JEAN PIAGET (UBÁ)
UPDATE schools SET inep_code = '240338' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL JEAN PIAGET' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '240338');

-- COLÉGIO APOGEU UBÁ (UBÁ)
UPDATE schools SET inep_code = '377783' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO APOGEU UBÁ' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '377783');

-- COLÉGIO LOSANGO DE UBÁ (UBÁ)
UPDATE schools SET inep_code = '184349' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO LOSANGO DE UBÁ' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184349');

-- COLÉGIO LUNOS EDUCACIONAL (UBÁ)
UPDATE schools SET inep_code = '372013' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO LUNOS EDUCACIONAL' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '372013');

-- COLÉGIO PILAR (UBÁ)
UPDATE schools SET inep_code = '276057' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PILAR' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '276057');

-- COLÉGIO SAGRADO CORAÇÃO DE MARIA (UBÁ)
UPDATE schools SET inep_code = '184331' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SAGRADO CORAÇÃO DE MARIA' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184331');

-- ETTAL - ESCOLA TECNICA TERESA ALMEIDA (UBÁ)
UPDATE schools SET inep_code = '350079' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ETTAL - ESCOLA TECNICA TERESA ALMEIDA' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '350079');

-- IEB - INSTITUTO EDUCACIONAL BETHEL (UBÁ)
UPDATE schools SET inep_code = '356492' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'IEB - INSTITUTO EDUCACIONAL BETHEL' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '356492');

-- INSTITUTO DE APLICAÇÃO EDUCACIONAL (UBÁ)
UPDATE schools SET inep_code = '238082' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO DE APLICAÇÃO EDUCACIONAL' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '238082');

-- SENAI CENTRO DE FORMAÇÃO PROFISSIONAL JOSÉ ALENCAR GOMES DA SILVA (UBÁ)
UPDATE schools SET inep_code = '310832' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI CENTRO DE FORMAÇÃO PROFISSIONAL JOSÉ ALENCAR GOMES DA SILVA' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310832');

-- SESI ESCOLA JOSÉ ALENCAR GOMES DA SILVA (UBÁ)
UPDATE schools SET inep_code = '278726' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SESI ESCOLA JOSÉ ALENCAR GOMES DA SILVA' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '278726');

-- COLÉGIO LOSANGO (VISCONDE DO RIO BRANCO)
UPDATE schools SET inep_code = '213942' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO LOSANGO' AND UPPER(TRIM(city)) = 'VISCONDE DO RIO BRANCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '213942');

-- COLÉGIO SUPREMO (VISCONDE DO RIO BRANCO)
UPDATE schools SET inep_code = '374660' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SUPREMO' AND UPPER(TRIM(city)) = 'VISCONDE DO RIO BRANCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '374660');

-- COLÉGIO VERDY (VISCONDE DO RIO BRANCO)
UPDATE schools SET inep_code = '257320' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO VERDY' AND UPPER(TRIM(city)) = 'VISCONDE DO RIO BRANCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '257320');

-- ESCOLA RAFAELA MENICUCCI (VISCONDE DO RIO BRANCO)
UPDATE schools SET inep_code = '184365' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA RAFAELA MENICUCCI' AND UPPER(TRIM(city)) = 'VISCONDE DO RIO BRANCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184365');

-- SENAI VISCONDE DO RIO BRANCO CFP SILVIO BENATTI (VISCONDE DO RIO BRANCO)
UPDATE schools SET inep_code = '352586' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI VISCONDE DO RIO BRANCO CFP SILVIO BENATTI' AND UPPER(TRIM(city)) = 'VISCONDE DO RIO BRANCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '352586');

-- CENTRO DE EDUCAÇÃO PROFISSIONAL- BIT COMPANY ARAXÁ (ARAXÁ)
UPDATE schools SET inep_code = '339709' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE EDUCAÇÃO PROFISSIONAL- BIT COMPANY ARAXÁ' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '339709');

-- COLÉGIO ATENA (ARAXÁ)
UPDATE schools SET inep_code = '218553' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ATENA' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218553');

-- COLÉGIO DOM BOSCO (ARAXÁ)
UPDATE schools SET inep_code = '166090' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DOM BOSCO' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166090');

-- COLÉGIO GABARITO (ARAXÁ)
UPDATE schools SET inep_code = '371777' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO GABARITO' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '371777');

-- COLÉGIO MÚLTIPLA ESCOLHA (ARAXÁ)
UPDATE schools SET inep_code = '361534' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MÚLTIPLA ESCOLHA' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '361534');

-- COLÉGIO SÃO DOMINGOS (ARAXÁ)
UPDATE schools SET inep_code = '166103' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SÃO DOMINGOS' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166103');

-- ESCOLA POLITÉCNICA DO PLANALTO DE ARAXÁ (ARAXÁ)
UPDATE schools SET inep_code = '377864' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA POLITÉCNICA DO PLANALTO DE ARAXÁ' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '377864');

-- ESCOLA TÉCNICA SANTA EDWIGES (ARAXÁ)
UPDATE schools SET inep_code = '325911' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA SANTA EDWIGES' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '325911');

-- SENAC UNIDADE DE ENSINO TÉCNICO - CENTRO DE FORMAÇÃO PROFISSIONAL DE ARAXÁ (ARAXÁ)
UPDATE schools SET inep_code = '317888' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAC UNIDADE DE ENSINO TÉCNICO - CENTRO DE FORMAÇÃO PROFISSIONAL DE ARAXÁ' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '317888');

-- SENAI CENTRO DE FORMAÇÃO PROFISSIONAL DJALMA GUIMARÃES (ARAXÁ)
UPDATE schools SET inep_code = '298719' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI CENTRO DE FORMAÇÃO PROFISSIONAL DJALMA GUIMARÃES' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '298719');

-- COLÉGIO PODIUM (CAMPOS ALTOS)
UPDATE schools SET inep_code = '373540' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PODIUM' AND UPPER(TRIM(city)) = 'CAMPOS ALTOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '373540');

-- COLÉGIO SÃO MIGUEL (CAMPOS ALTOS)
UPDATE schools SET inep_code = '365971' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SÃO MIGUEL' AND UPPER(TRIM(city)) = 'CAMPOS ALTOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '365971');

-- COLEGIO ARAOLISS (CONCEIÇÃO DAS ALAGOAS)
UPDATE schools SET inep_code = '367974' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLEGIO ARAOLISS' AND UPPER(TRIM(city)) = 'CONCEIÇÃO DAS ALAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '367974');

-- COLÉGIO UNIÃO - CÉU (CONCEIÇÃO DAS ALAGOAS)
UPDATE schools SET inep_code = '237060' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO UNIÃO - CÉU' AND UPPER(TRIM(city)) = 'CONCEIÇÃO DAS ALAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '237060');

-- COLÉGIO DESTAQUE (FRONTEIRA)
UPDATE schools SET inep_code = '349950' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DESTAQUE' AND UPPER(TRIM(city)) = 'FRONTEIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349950');

-- COLÉGIO EQUILÍBRIO (FRONTEIRA)
UPDATE schools SET inep_code = '360490' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO EQUILÍBRIO' AND UPPER(TRIM(city)) = 'FRONTEIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '360490');

-- COLÉGIO OBJETIVO (FRUTAL)
UPDATE schools SET inep_code = '246905' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO OBJETIVO' AND UPPER(TRIM(city)) = 'FRUTAL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246905');

-- COLÉGIO VICENTE DE PAULO (FRUTAL)
UPDATE schools SET inep_code = '166219' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO VICENTE DE PAULO' AND UPPER(TRIM(city)) = 'FRUTAL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166219');

-- ESCOLA PRESIDENTE VARGAS (FRUTAL)
UPDATE schools SET inep_code = '166201' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA PRESIDENTE VARGAS' AND UPPER(TRIM(city)) = 'FRUTAL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166201');

-- GALILEU PRÉ - VESTIBULAR (FRUTAL)
UPDATE schools SET inep_code = '347671' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'GALILEU PRÉ - VESTIBULAR' AND UPPER(TRIM(city)) = 'FRUTAL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '347671');

-- COLÉGIO FAMA (ITURAMA)
UPDATE schools SET inep_code = '368920' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO FAMA' AND UPPER(TRIM(city)) = 'ITURAMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368920');

-- ESCOLA DINÂMICA (ITURAMA)
UPDATE schools SET inep_code = '261980' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DINÂMICA' AND UPPER(TRIM(city)) = 'ITURAMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '261980');

-- ESCOLA SISTEMA INTELIGENTE DE APRENDIZAGEM (ITURAMA)
UPDATE schools SET inep_code = '247359' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SISTEMA INTELIGENTE DE APRENDIZAGEM' AND UPPER(TRIM(city)) = 'ITURAMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '247359');

-- INSTITUTO EDUCACIONAL PROFISSIONALIZANTE DE ITURAMA (ITURAMA)
UPDATE schools SET inep_code = '320871' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL PROFISSIONALIZANTE DE ITURAMA' AND UPPER(TRIM(city)) = 'ITURAMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '320871');

-- COLÉGIO BOM JESUS (PIRAJUBA)
UPDATE schools SET inep_code = '370290' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO BOM JESUS' AND UPPER(TRIM(city)) = 'PIRAJUBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '370290');

-- COLÉGIO ROUSSEAU (SACRAMENTO)
UPDATE schools SET inep_code = '304468' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ROUSSEAU' AND UPPER(TRIM(city)) = 'SACRAMENTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '304468');

-- ESCOLA EURÍPEDES BARSANULFO (SACRAMENTO)
UPDATE schools SET inep_code = '166260' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA EURÍPEDES BARSANULFO' AND UPPER(TRIM(city)) = 'SACRAMENTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166260');

-- CENTRO EDUCACIONAL NOVO MUNDO (SANTA JULIANA)
UPDATE schools SET inep_code = '352039' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL NOVO MUNDO' AND UPPER(TRIM(city)) = 'SANTA JULIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '352039');

-- CENTRO DE ENSINO GRAU TÉCNICO UBERABA (UBERABA)
UPDATE schools SET inep_code = '376663' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE ENSINO GRAU TÉCNICO UBERABA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '376663');

-- CENTRO EDUCACIONAL BIT MAIS UBERABA (UBERABA)
UPDATE schools SET inep_code = '315966' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL BIT MAIS UBERABA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '315966');

-- CENTRO EDUCACIONAL FUTURA (UBERABA)
UPDATE schools SET inep_code = '299651' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL FUTURA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '299651');

-- CENTRO EDUCACIONAL MONTEIRO LOBATO (UBERABA)
UPDATE schools SET inep_code = '370355' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL MONTEIRO LOBATO' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '370355');

-- CENTRO EDUCACIONAL OPÇÃO (UBERABA)
UPDATE schools SET inep_code = '243418' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL OPÇÃO' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '243418');

-- CENTRO EDUCACIONAL SÃO FRANCISCO ASSIS (UBERABA)
UPDATE schools SET inep_code = '247367' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL SÃO FRANCISCO ASSIS' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '247367');

-- CENTRO TÉCNICO PROFISSIONAL DE UBERABA (UBERABA)
UPDATE schools SET inep_code = '381489' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO TÉCNICO PROFISSIONAL DE UBERABA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '381489');

-- COL CENECISTA DR JOSÉ FERREIRA (UBERABA)
UPDATE schools SET inep_code = '166481' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COL CENECISTA DR JOSÉ FERREIRA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166481');

-- COLÉGIO ANTARES (UBERABA)
UPDATE schools SET inep_code = '166448' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ANTARES' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166448');

-- COLÉGIO APOIO (UBERABA)
UPDATE schools SET inep_code = '320536' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO APOIO' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '320536');

-- COLÉGIO DOM BOSCO (UBERABA)
UPDATE schools SET inep_code = '278076' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DOM BOSCO' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '278076');

-- COLÉGIO F.A.S (UBERABA)
UPDATE schools SET inep_code = '342041' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO F.A.S' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342041');

-- COLÉGIO GABARITO (UBERABA)
UPDATE schools SET inep_code = '354562' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO GABARITO' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '354562');

-- COLÉGIO INTEGRADO UBERABA (UBERABA)
UPDATE schools SET inep_code = '377953' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO INTEGRADO UBERABA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '377953');

-- COLÉGIO JEAN CHRISTOPHE (UBERABA)
UPDATE schools SET inep_code = '166383' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO JEAN CHRISTOPHE' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166383');

-- COLÉGIO LICEU ALBERT EINSTEIN (UBERABA)
UPDATE schools SET inep_code = '260762' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO LICEU ALBERT EINSTEIN' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '260762');

-- COLÉGIO LIVRE APRENDER (UBERABA)
UPDATE schools SET inep_code = '376442' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO LIVRE APRENDER' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '376442');

-- COLÉGIO MACHADO DE ASSIS (UBERABA)
UPDATE schools SET inep_code = '297071' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MACHADO DE ASSIS' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '297071');

-- COLÉGIO MARISTA DIOCESANO (UBERABA)
UPDATE schools SET inep_code = '166332' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MARISTA DIOCESANO' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166332');

-- COLÉGIO MASTER MED (UBERABA)
UPDATE schools SET inep_code = '370614' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MASTER MED' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '370614');

-- COLÉGIO NOSSA SENHORA DAS DORES (UBERABA)
UPDATE schools SET inep_code = '166359' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO NOSSA SENHORA DAS DORES' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166359');

-- COLÉGIO NOSSA SENHORA DAS GRAÇAS (UBERABA)
UPDATE schools SET inep_code = '166375' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO NOSSA SENHORA DAS GRAÇAS' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166375');

-- COLÉGIO PRESBITERIANO COMENIUS (UBERABA)
UPDATE schools SET inep_code = '347248' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PRESBITERIANO COMENIUS' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '347248');

-- COLÉGIO PROJETO (UBERABA)
UPDATE schools SET inep_code = '166367' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PROJETO' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166367');

-- COLÉGIO ROUSSEAU - UNIDADE UBERABA (UBERABA)
UPDATE schools SET inep_code = '378240' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ROUSSEAU - UNIDADE UBERABA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '378240');

-- COLÉGIO RUBEM ALVES (UBERABA)
UPDATE schools SET inep_code = '166456' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO RUBEM ALVES' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166456');

-- ESCOLA ADVENTISTA DE UBERABA (UBERABA)
UPDATE schools SET inep_code = '368539' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA ADVENTISTA DE UBERABA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368539');

-- ESCOLA CRIATIVA DE UBERABA (UBERABA)
UPDATE schools SET inep_code = '213365' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA CRIATIVA DE UBERABA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '213365');

-- ESCOLA CRISTÃ DE UBERABA - ESCRIBA (UBERABA)
UPDATE schools SET inep_code = '366609' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA CRISTÃ DE UBERABA - ESCRIBA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '366609');

-- ESCOLA POLITÉCNICA DO ALTO PARANAÍBA (UBERABA)
UPDATE schools SET inep_code = '368180' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA POLITÉCNICA DO ALTO PARANAÍBA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368180');

-- ESCOLA SESI ALBERTO MARTINS FONTOURA BORGES - UNIDADE II (UBERABA)
UPDATE schools SET inep_code = '379735' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SESI ALBERTO MARTINS FONTOURA BORGES - UNIDADE II' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '379735');

-- ESCOLA TÉCNICA DE FORMAÇÃO PROFISSIONAL MG - EFOP (UBERABA)
UPDATE schools SET inep_code = '316105' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA DE FORMAÇÃO PROFISSIONAL MG - EFOP' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '316105');

-- ESCOLA TÉCNICA DE UBERABA (UBERABA)
UPDATE schools SET inep_code = '323098' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA DE UBERABA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '323098');

-- ESCOLA VITÓRIA FORMAÇÃO PROFISSIONAL (UBERABA)
UPDATE schools SET inep_code = '325902' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA VITÓRIA FORMAÇÃO PROFISSIONAL' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '325902');

-- INSTITUTO EDUCACIONAL FERREIRA GOMES (UBERABA)
UPDATE schools SET inep_code = '310395' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL FERREIRA GOMES' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310395');

-- SENAC UNIDADE DE ENSINO TÉCNICO - CFP DE UBERABA (UBERABA)
UPDATE schools SET inep_code = '317446' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAC UNIDADE DE ENSINO TÉCNICO - CFP DE UBERABA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '317446');

-- SENAI C DE FORM PROFIS FIDÉLIS REIS (UBERABA)
UPDATE schools SET inep_code = '311529' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI C DE FORM PROFIS FIDÉLIS REIS' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '311529');

-- SESI ESC ALBERTO MARTINS FONTOURA BORGES (UBERABA)
UPDATE schools SET inep_code = '278084' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SESI ESC ALBERTO MARTINS FONTOURA BORGES' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '278084');

-- CENTRO EDUCACIONAL BEIJA FLOR (ARAGUARI)
UPDATE schools SET inep_code = '311570' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL BEIJA FLOR' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '311570');

-- CENTRO EDUCACIONAL NOSSO LAR (ARAGUARI)
UPDATE schools SET inep_code = '278912' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL NOSSO LAR' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '278912');

-- COLÉGIO ALFA (ARAGUARI)
UPDATE schools SET inep_code = '340367' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ALFA' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '340367');

-- COLÉGIO BERLAAR SAGRADO CORAÇÃO JESUS (ARAGUARI)
UPDATE schools SET inep_code = '170216' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO BERLAAR SAGRADO CORAÇÃO JESUS' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170216');

-- COLÉGIO NACIONAL (ARAGUARI)
UPDATE schools SET inep_code = '239666' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO NACIONAL' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '239666');

-- COLÉGIO NACIONAL DE ARAGUARI (ARAGUARI)
UPDATE schools SET inep_code = '259349' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO NACIONAL DE ARAGUARI' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '259349');

-- ESCOLA EDUCARE - UNIDADE II (ARAGUARI)
UPDATE schools SET inep_code = '370924' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA EDUCARE - UNIDADE II' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '370924');

-- ESCOLA MACHADO DE ASSIS (ARAGUARI)
UPDATE schools SET inep_code = '170208' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA MACHADO DE ASSIS' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170208');

-- INSTITUTO FRANCISCO SAVÉRIO PETANHA (ARAGUARI)
UPDATE schools SET inep_code = '170232' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO FRANCISCO SAVÉRIO PETANHA' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170232');

-- SENAI CENTRO DE FORMAÇÃO PROFISSIONAL MÁRIO ABDALLA (ARAGUARI)
UPDATE schools SET inep_code = '330931' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI CENTRO DE FORMAÇÃO PROFISSIONAL MÁRIO ABDALLA' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '330931');

-- SESI JOSE ALENCAR GOMES DA SILVA (ARAGUARI)
UPDATE schools SET inep_code = '268283' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SESI JOSE ALENCAR GOMES DA SILVA' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '268283');

-- CENTRO EDUCACIONAL GALILEU GALILEI (CAMPINA VERDE)
UPDATE schools SET inep_code = '247481' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL GALILEU GALILEI' AND UPPER(TRIM(city)) = 'CAMPINA VERDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '247481');

-- ESCOLA SANTA TEREZINHA (CAMPINA VERDE)
UPDATE schools SET inep_code = '166162' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SANTA TEREZINHA' AND UPPER(TRIM(city)) = 'CAMPINA VERDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166162');

-- PRÓTON ESCOLA TÉCNICA E PROFISSIONALIZANTE - UNIDADE CAMPINA VERDE (CAMPINA VERDE)
UPDATE schools SET inep_code = '326241' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'PRÓTON ESCOLA TÉCNICA E PROFISSIONALIZANTE - UNIDADE CAMPINA VERDE' AND UPPER(TRIM(city)) = 'CAMPINA VERDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '326241');

-- CASA ESCOLA PRIMEIROS PASSOS (MONTE ALEGRE DE MINAS)
UPDATE schools SET inep_code = '349224' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CASA ESCOLA PRIMEIROS PASSOS' AND UPPER(TRIM(city)) = 'MONTE ALEGRE DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349224');

-- CENTRO DE EDUCAÇÃO MONTEALEGRENSE (MONTE ALEGRE DE MINAS)
UPDATE schools SET inep_code = '273911' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE EDUCAÇÃO MONTEALEGRENSE' AND UPPER(TRIM(city)) = 'MONTE ALEGRE DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '273911');

-- ESA ESCOLA SOUZA ALVES (PRATA)
UPDATE schools SET inep_code = '324485' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESA ESCOLA SOUZA ALVES' AND UPPER(TRIM(city)) = 'PRATA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '324485');

-- ESCOLA NOSSA SENHORA APARECIDA (PRATA)
UPDATE schools SET inep_code = '232637' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA NOSSA SENHORA APARECIDA' AND UPPER(TRIM(city)) = 'PRATA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '232637');

-- PRÓTON- ESCOLA TÉCNICA PROFISSIONALIZANTE (PRATA)
UPDATE schools SET inep_code = '324477' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'PRÓTON- ESCOLA TÉCNICA PROFISSIONALIZANTE' AND UPPER(TRIM(city)) = 'PRATA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '324477');

-- CENTRO EDUCACIONAL NOSSA ESCOLA (TUPACIGUARA)
UPDATE schools SET inep_code = '351377' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL NOSSA ESCOLA' AND UPPER(TRIM(city)) = 'TUPACIGUARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '351377');

-- ESCOLA ABELHINHA C EDUCACIONAL (TUPACIGUARA)
UPDATE schools SET inep_code = '170291' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA ABELHINHA C EDUCACIONAL' AND UPPER(TRIM(city)) = 'TUPACIGUARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170291');

-- AMEDUCA - COMPLEXO EDUCACIONAL (UBERLÂNDIA)
UPDATE schools SET inep_code = '275557' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'AMEDUCA - COMPLEXO EDUCACIONAL' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '275557');

-- ASSOCIAÇÃO EDUCACIONAL JOHANN KEPLER (UBERLÂNDIA)
UPDATE schools SET inep_code = '323942' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ASSOCIAÇÃO EDUCACIONAL JOHANN KEPLER' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '323942');

-- CEIA -  ESCOLA PROFESSOR LUIZMAR ANTÔNIO DOS SANTOS (UBERLÂNDIA)
UPDATE schools SET inep_code = '350702' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CEIA -  ESCOLA PROFESSOR LUIZMAR ANTÔNIO DOS SANTOS' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '350702');

-- CENTRO DE ENSINO GRAU TÉCNICO UBERLÂNDIA (UBERLÂNDIA)
UPDATE schools SET inep_code = '375411' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE ENSINO GRAU TÉCNICO UBERLÂNDIA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '375411');

-- CENTRO EDUCACIONAL ADVENTISTA DE UBERLÂNDIA (UBERLÂNDIA)
UPDATE schools SET inep_code = '170348' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL ADVENTISTA DE UBERLÂNDIA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170348');

-- CENTRO EDUCACIONAL BATISTA BETEL (UBERLÂNDIA)
UPDATE schools SET inep_code = '325325' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL BATISTA BETEL' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '325325');

-- CENTRO EDUCACIONAL CAMINHO SUAVE (UBERLÂNDIA)
UPDATE schools SET inep_code = '323055' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL CAMINHO SUAVE' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '323055');

-- CENTRO EDUCACIONAL COLIBRI (UBERLÂNDIA)
UPDATE schools SET inep_code = '280089' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL COLIBRI' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '280089');

-- CENTRO EDUCACIONAL EURÍPEDES BARSANULFO (UBERLÂNDIA)
UPDATE schools SET inep_code = '310280' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL EURÍPEDES BARSANULFO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310280');

-- CENTRO EDUCACIONAL GATO DE BOTAS - DRUMMOND (UBERLÂNDIA)
UPDATE schools SET inep_code = '275549' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL GATO DE BOTAS - DRUMMOND' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '275549');

-- CENTRO EDUCACIONAL MONTEIRO LOBATO (UBERLÂNDIA)
UPDATE schools SET inep_code = '313301' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL MONTEIRO LOBATO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '313301');

-- CENTRO PEDAGÓGICO METTA (UBERLÂNDIA)
UPDATE schools SET inep_code = '368415' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO PEDAGÓGICO METTA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368415');

-- CETEC - CENTRO EDUCACIONAL E TECNOLÓGICO (UBERLÂNDIA)
UPDATE schools SET inep_code = '348090' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CETEC - CENTRO EDUCACIONAL E TECNOLÓGICO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '348090');

-- COLÉGIO ANN MACKENZIE (UBERLÂNDIA)
UPDATE schools SET inep_code = '375071' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ANN MACKENZIE' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '375071');

-- COLÉGIO ANN MACKENZIE UNIDADE GÁVEA - KARAÍBA (UBERLÂNDIA)
UPDATE schools SET inep_code = '380210' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ANN MACKENZIE UNIDADE GÁVEA - KARAÍBA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '380210');

-- COLÉGIO APOGEU (UBERLÂNDIA)
UPDATE schools SET inep_code = '278939' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO APOGEU' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '278939');

-- COLÉGIO BATISTA MINEIRO (UBERLÂNDIA)
UPDATE schools SET inep_code = '275531' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO BATISTA MINEIRO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '275531');

-- COLEGIO CASA BRANCA (UBERLÂNDIA)
UPDATE schools SET inep_code = '170615' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLEGIO CASA BRANCA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170615');

-- COLEGIO CECON UBERLÂNDIA (UBERLÂNDIA)
UPDATE schools SET inep_code = '349046' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLEGIO CECON UBERLÂNDIA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349046');

-- COLÉGIO COPACABANA (UBERLÂNDIA)
UPDATE schools SET inep_code = '279846' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO COPACABANA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '279846');

-- COLÉGIO DO TRABALHO UNIDADE I (UBERLÂNDIA)
UPDATE schools SET inep_code = '319953' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DO TRABALHO UNIDADE I' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '319953');

-- COLÉGIO DO TRABALHO UNIDADE II (UBERLÂNDIA)
UPDATE schools SET inep_code = '332712' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DO TRABALHO UNIDADE II' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '332712');

-- COLÉGIO DOM BOSCO (UBERLÂNDIA)
UPDATE schools SET inep_code = '343099' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DOM BOSCO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '343099');

-- COLÉGIO ENGETEC (UBERLÂNDIA)
UPDATE schools SET inep_code = '355682' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ENGETEC' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '355682');

-- COLÉGIO ESPAÇO LETRADO (UBERLÂNDIA)
UPDATE schools SET inep_code = '335053' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ESPAÇO LETRADO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '335053');

-- COLÉGIO GABARITO (UBERLÂNDIA)
UPDATE schools SET inep_code = '352195' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO GABARITO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '352195');

-- COLÉGIO INTEGRAÇÃO PEQUENINO MUNDO (UBERLÂNDIA)
UPDATE schools SET inep_code = '170658' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO INTEGRAÇÃO PEQUENINO MUNDO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170658');

-- COLÉGIO MAIS - UNIDADE JOÃO NAVES (UBERLÂNDIA)
UPDATE schools SET inep_code = '373893' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MAIS - UNIDADE JOÃO NAVES' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '373893');

-- COLÉGIO MAIS POSITIVO (UBERLÂNDIA)
UPDATE schools SET inep_code = '342599' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MAIS POSITIVO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342599');

-- COLÉGIO MARIA DE NAZARÉ (UBERLÂNDIA)
UPDATE schools SET inep_code = '318094' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MARIA DE NAZARÉ' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '318094');

-- COLÉGIO MARISTA CHAMPAGNAT (UBERLÂNDIA)
UPDATE schools SET inep_code = '170402' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MARISTA CHAMPAGNAT' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170402');

-- COLÉGIO NACIONAL - UNIDADE I (UBERLÂNDIA)
UPDATE schools SET inep_code = '220094' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO NACIONAL - UNIDADE I' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '220094');

-- COLÉGIO NACIONAL - UNIDADE IV (UBERLÂNDIA)
UPDATE schools SET inep_code = '369969' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO NACIONAL - UNIDADE IV' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369969');

-- COLÉGIO NACIONAL - UNIDADE V (UBERLÂNDIA)
UPDATE schools SET inep_code = '375276' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO NACIONAL - UNIDADE V' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '375276');

-- COLÉGIO OLIMPO (UBERLÂNDIA)
UPDATE schools SET inep_code = '318426' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO OLIMPO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '318426');

-- COLÉGIO PIRLIMPIMPIM - SÃO PASCHOALL – UNIDADE II (UBERLÂNDIA)
UPDATE schools SET inep_code = '236187' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PIRLIMPIMPIM - SÃO PASCHOALL – UNIDADE II' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '236187');

-- COLÉGIO PIRLIMPIMPIM SÃO PASCHOALL - UNIDADE III (UBERLÂNDIA)
UPDATE schools SET inep_code = '375446' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PIRLIMPIMPIM SÃO PASCHOALL - UNIDADE III' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '375446');

-- COLÉGIO PIRLIMPIMPIM-SÃO PASCHOAL (UBERLÂNDIA)
UPDATE schools SET inep_code = '170534' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PIRLIMPIMPIM-SÃO PASCHOAL' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170534');

-- COLÉGIO PROFISSIONAL (UBERLÂNDIA)
UPDATE schools SET inep_code = '310298' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PROFISSIONAL' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310298');

-- COLÉGIO PROFISSIONAL - UNIDADE II (UBERLÂNDIA)
UPDATE schools SET inep_code = '351237' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PROFISSIONAL - UNIDADE II' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '351237');

-- COLÉGIO RESSURREIÇÃO NOSSA SENHORA (UBERLÂNDIA)
UPDATE schools SET inep_code = '170461' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO RESSURREIÇÃO NOSSA SENHORA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170461');

-- ENFERMINAS - ESCOLA DE ENFERMAGEM DE MINAS GERAIS - UNIDADE UBERLÂNDIA (UBERLÂNDIA)
UPDATE schools SET inep_code = '381152' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ENFERMINAS - ESCOLA DE ENFERMAGEM DE MINAS GERAIS - UNIDADE UBERLÂNDIA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '381152');

-- ESCOLA ATHENAS (UBERLÂNDIA)
UPDATE schools SET inep_code = '309966' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA ATHENAS' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '309966');

-- ESCOLA DA CRIANÇA ESPAÇO ADOLESCER (UBERLÂNDIA)
UPDATE schools SET inep_code = '230812' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DA CRIANÇA ESPAÇO ADOLESCER' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '230812');

-- ESCOLA OFICINA DO SABER (UBERLÂNDIA)
UPDATE schools SET inep_code = '297241' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA OFICINA DO SABER' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '297241');

-- FAMATRI-CURSOS TÉCNICOS PROFISSIONALIZANTES (UBERLÂNDIA)
UPDATE schools SET inep_code = '324264' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'FAMATRI-CURSOS TÉCNICOS PROFISSIONALIZANTES' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '324264');

-- FUNDAÇÃO DE EDUCAÇÃO PARA O TRABALHO DE MINAS GERAIS - UTRAMIG (UBERLÂNDIA)
UPDATE schools SET inep_code = '361542' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'FUNDAÇÃO DE EDUCAÇÃO PARA O TRABALHO DE MINAS GERAIS - UTRAMIG' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '361542');

-- GABARITO SISTEMA EDUCACIONAL (UBERLÂNDIA)
UPDATE schools SET inep_code = '357065' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'GABARITO SISTEMA EDUCACIONAL' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '357065');

-- INSTITUTO DE ESTUDOS INTEGRADOS (UBERLÂNDIA)
UPDATE schools SET inep_code = '346845' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO DE ESTUDOS INTEGRADOS' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346845');

-- INSTITUTO EDUCACIONAL SANTA MÔNICA (UBERLÂNDIA)
UPDATE schools SET inep_code = '210510' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL SANTA MÔNICA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '210510');

-- INSTITUTO EDUCACIONAL SHALOM (UBERLÂNDIA)
UPDATE schools SET inep_code = '230758' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL SHALOM' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '230758');

-- INSTITUTO PROPÉ (UBERLÂNDIA)
UPDATE schools SET inep_code = '375268' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO PROPÉ' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '375268');

-- INSTITUTO TERESA VALSÉ (UBERLÂNDIA)
UPDATE schools SET inep_code = '170607' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO TERESA VALSÉ' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170607');

-- MAPLE BEAR UBERLÂNDIA - UNIDADE II (UBERLÂNDIA)
UPDATE schools SET inep_code = '376590' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'MAPLE BEAR UBERLÂNDIA - UNIDADE II' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '376590');

-- SENAC CENTRO DE FORMAÇÃO PROFISSIONAL (UBERLÂNDIA)
UPDATE schools SET inep_code = '318078' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAC CENTRO DE FORMAÇÃO PROFISSIONAL' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '318078');

-- SENAI UBERLÂNDIA CENTRO DE FORMAÇÃO PROFISSIONAL DOUTOR CELSO CHARURI (UBERLÂNDIA)
UPDATE schools SET inep_code = '358843' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI UBERLÂNDIA CENTRO DE FORMAÇÃO PROFISSIONAL DOUTOR CELSO CHARURI' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '358843');

-- SENAI UBERLÂNIA  CENTRO DE FORMAÇÃO PROFISSIONAL FÁBIO ARAÚJO MOTTA (UBERLÂNDIA)
UPDATE schools SET inep_code = '321575' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI UBERLÂNIA  CENTRO DE FORMAÇÃO PROFISSIONAL FÁBIO ARAÚJO MOTTA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '321575');

-- SESI ESCOLA GUIOMAR DE FREITAS COSTA (UBERLÂNDIA)
UPDATE schools SET inep_code = '170321' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SESI ESCOLA GUIOMAR DE FREITAS COSTA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170321');

-- CENTRO EDUCACIONAL GÊNESIS (ARINOS)
UPDATE schools SET inep_code = '363774' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL GÊNESIS' AND UPPER(TRIM(city)) = 'ARINOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '363774');

-- ESCOLA JUSCELINO KUBITSCHEK (ARINOS)
UPDATE schools SET inep_code = '114715' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA JUSCELINO KUBITSCHEK' AND UPPER(TRIM(city)) = 'ARINOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '114715');

-- ESCOLA TÉCNICA DE BONFINÓPOLIS DE MINAS (BONFINÓPOLIS DE MINAS)
UPDATE schools SET inep_code = '378500' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA DE BONFINÓPOLIS DE MINAS' AND UPPER(TRIM(city)) = 'BONFINÓPOLIS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '378500');

-- COLÉGIO AMETISTA (BURITIS)
UPDATE schools SET inep_code = '348384' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO AMETISTA' AND UPPER(TRIM(city)) = 'BURITIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '348384');

-- COLÉGIO NOSSA SENHORA DA PENA (BURITIS)
UPDATE schools SET inep_code = '255262' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO NOSSA SENHORA DA PENA' AND UPPER(TRIM(city)) = 'BURITIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '255262');

-- ESCOLA FAMÍLIA AGRÍCOLA DE NATALÂNDIA - EFAN (NATALÂNDIA)
UPDATE schools SET inep_code = '349372' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA FAMÍLIA AGRÍCOLA DE NATALÂNDIA - EFAN' AND UPPER(TRIM(city)) = 'NATALÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349372');

-- BOM SUCESSO ESCOLA MONTESSORIANA (UNAÍ)
UPDATE schools SET inep_code = '365599' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'BOM SUCESSO ESCOLA MONTESSORIANA' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '365599');

-- COLÉGIO ATHOS - UNIDADE II (UNAÍ)
UPDATE schools SET inep_code = '380229' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ATHOS - UNIDADE II' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '380229');

-- COLÉGIO CENECISTA NOSSA SENHORA DO CARMO (UNAÍ)
UPDATE schools SET inep_code = '114812' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CENECISTA NOSSA SENHORA DO CARMO' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '114812');

-- COLÉGIO NOVO MUNDO (UNAÍ)
UPDATE schools SET inep_code = '322245' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO NOVO MUNDO' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322245');

-- ESCOLA TÉCNICA DE UNAÍ (UNAÍ)
UPDATE schools SET inep_code = '310336' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA DE UNAÍ' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310336');

-- IEL - INSTITUTO EDUCACIONAL LATTES (UNAÍ)
UPDATE schools SET inep_code = '376671' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'IEL - INSTITUTO EDUCACIONAL LATTES' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '376671');

-- INSTITUTO ATHOS (UNAÍ)
UPDATE schools SET inep_code = '114804' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO ATHOS' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '114804');

-- CENTRO EDUCACIONAL PALMARES (ALFENAS)
UPDATE schools SET inep_code = '321991' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL PALMARES' AND UPPER(TRIM(city)) = 'ALFENAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '321991');

-- COLÉGIO ÁGUIA (ALFENAS)
UPDATE schools SET inep_code = '355640' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ÁGUIA' AND UPPER(TRIM(city)) = 'ALFENAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '355640');

-- COLÉGIO ATENAS (ALFENAS)
UPDATE schools SET inep_code = '180211' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ATENAS' AND UPPER(TRIM(city)) = 'ALFENAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180211');

-- COLÉGIO ATENAS UNID II (ALFENAS)
UPDATE schools SET inep_code = '331163' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ATENAS UNID II' AND UPPER(TRIM(city)) = 'ALFENAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '331163');

-- COLÉGIO CRA (ALFENAS)
UPDATE schools SET inep_code = '346799' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CRA' AND UPPER(TRIM(city)) = 'ALFENAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346799');

-- COLÉGIO PONTUAL DE ALFENAS (ALFENAS)
UPDATE schools SET inep_code = '318345' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PONTUAL DE ALFENAS' AND UPPER(TRIM(city)) = 'ALFENAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '318345');

-- COLÉGIO PROFESSOR ROQUE NICOLAU TAMBURINI (ALFENAS)
UPDATE schools SET inep_code = '319945' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PROFESSOR ROQUE NICOLAU TAMBURINI' AND UPPER(TRIM(city)) = 'ALFENAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '319945');

-- COLÉGIO SAGRADO CORAÇÃO DE JESUS (ALFENAS)
UPDATE schools SET inep_code = '180220' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SAGRADO CORAÇÃO DE JESUS' AND UPPER(TRIM(city)) = 'ALFENAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180220');

-- ETAP - ESCOLA TÉCNICA DE APRENDIZADO PROFISSIONAL (ALFENAS)
UPDATE schools SET inep_code = '328901' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ETAP - ESCOLA TÉCNICA DE APRENDIZADO PROFISSIONAL' AND UPPER(TRIM(city)) = 'ALFENAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '328901');

-- SENAC - UNIDADE DE ENSINO TÉCNICO DO CEP DE ALFENAS (ALFENAS)
UPDATE schools SET inep_code = '359491' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAC - UNIDADE DE ENSINO TÉCNICO DO CEP DE ALFENAS' AND UPPER(TRIM(city)) = 'ALFENAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '359491');

-- COLÉGIO PADRE JÚLIO MARIA (BOA ESPERANÇA)
UPDATE schools SET inep_code = '180271' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PADRE JÚLIO MARIA' AND UPPER(TRIM(city)) = 'BOA ESPERANÇA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180271');

-- COLÉGIO SEI (BOA ESPERANÇA)
UPDATE schools SET inep_code = '256501' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SEI' AND UPPER(TRIM(city)) = 'BOA ESPERANÇA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '256501');

-- ESCOLA SÃO JOÃO (CAMPANHA)
UPDATE schools SET inep_code = '268321' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SÃO JOÃO' AND UPPER(TRIM(city)) = 'CAMPANHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '268321');

-- EXTERNATO NOSSA SENHORA DE LOURDES (CAMPANHA)
UPDATE schools SET inep_code = '180319' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EXTERNATO NOSSA SENHORA DE LOURDES' AND UPPER(TRIM(city)) = 'CAMPANHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180319');

-- COLÉGIO COLIBRI (CAMPOS GERAIS)
UPDATE schools SET inep_code = '247189' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO COLIBRI' AND UPPER(TRIM(city)) = 'CAMPOS GERAIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '247189');

-- COLÉGIO SANTA LUZIA (CAMPOS GERAIS)
UPDATE schools SET inep_code = '279081' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SANTA LUZIA' AND UPPER(TRIM(city)) = 'CAMPOS GERAIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '279081');

-- ESCOLA PARQUE TIBETANO (CARMO DA CACHOEIRA)
UPDATE schools SET inep_code = '354546' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA PARQUE TIBETANO' AND UPPER(TRIM(city)) = 'CARMO DA CACHOEIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '354546');

-- ESCOLA PARQUE TIBETANO COMUNIDADE FIGUEIRA (CARMO DA CACHOEIRA)
UPDATE schools SET inep_code = '346870' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA PARQUE TIBETANO COMUNIDADE FIGUEIRA' AND UPPER(TRIM(city)) = 'CARMO DA CACHOEIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346870');

-- CENTRO EDUCACIONAL PADRE NATAL FERLONI (ELÓI MENDES)
UPDATE schools SET inep_code = '372064' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL PADRE NATAL FERLONI' AND UPPER(TRIM(city)) = 'ELÓI MENDES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '372064');

-- COLÉGIO FÊNIX (ELÓI MENDES)
UPDATE schools SET inep_code = '265306' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO FÊNIX' AND UPPER(TRIM(city)) = 'ELÓI MENDES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '265306');

-- CENTRO DE EDUCAÇÃO E LAZER (LAMBARI)
UPDATE schools SET inep_code = '271616' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE EDUCAÇÃO E LAZER' AND UPPER(TRIM(city)) = 'LAMBARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '271616');

-- COLÉGIO OBJETIVO DE LAMBARI (LAMBARI)
UPDATE schools SET inep_code = '310697' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO OBJETIVO DE LAMBARI' AND UPPER(TRIM(city)) = 'LAMBARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310697');

-- ESCOLA AGROECOLÓGICA SÍTIO ESPERANÇA (LAMBARI)
UPDATE schools SET inep_code = '347647' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA AGROECOLÓGICA SÍTIO ESPERANÇA' AND UPPER(TRIM(city)) = 'LAMBARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '347647');

-- CENTRO -  ESPACC ESPAÇO CULTURAL E EDUCACIONAL (MACHADO)
UPDATE schools SET inep_code = '310158' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO -  ESPACC ESPAÇO CULTURAL E EDUCACIONAL' AND UPPER(TRIM(city)) = 'MACHADO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310158');

-- CENTRO DE FORMAÇÃO EDUCACIONAL MACHADENSE (MACHADO)
UPDATE schools SET inep_code = '279986' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE FORMAÇÃO EDUCACIONAL MACHADENSE' AND UPPER(TRIM(city)) = 'MACHADO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '279986');

-- CENTRO EDUCACIONAL UNIMAPE (MACHADO)
UPDATE schools SET inep_code = '260878' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL UNIMAPE' AND UPPER(TRIM(city)) = 'MACHADO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '260878');

-- COLÉGIO ALIANÇA (MACHADO)
UPDATE schools SET inep_code = '369381' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ALIANÇA' AND UPPER(TRIM(city)) = 'MACHADO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369381');

-- COLÉGIO IMACULADA CONCEIÇÃO (MACHADO)
UPDATE schools SET inep_code = '180408' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO IMACULADA CONCEIÇÃO' AND UPPER(TRIM(city)) = 'MACHADO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180408');

-- COLÉGIO UNIVERSITÁRIO - UNICOL (MACHADO)
UPDATE schools SET inep_code = '330833' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO UNIVERSITÁRIO - UNICOL' AND UPPER(TRIM(city)) = 'MACHADO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '330833');

-- CENTRO EDUCACIONAL LOSANGO DONA CORINA (NEPOMUCENO)
UPDATE schools SET inep_code = '213926' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL LOSANGO DONA CORINA' AND UPPER(TRIM(city)) = 'NEPOMUCENO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '213926');

-- CENTRO EDUCACIONAL FAZENDO ACONTECER CEFA (PARAGUAÇU)
UPDATE schools SET inep_code = '343315' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL FAZENDO ACONTECER CEFA' AND UPPER(TRIM(city)) = 'PARAGUAÇU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '343315');

-- COLÉGIO BRILHO DO SABER (PARAGUAÇU)
UPDATE schools SET inep_code = '351393' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO BRILHO DO SABER' AND UPPER(TRIM(city)) = 'PARAGUAÇU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '351393');

-- CENTRO EDUCACIONAL COOPERAR (POÇO FUNDO)
UPDATE schools SET inep_code = '323951' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL COOPERAR' AND UPPER(TRIM(city)) = 'POÇO FUNDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '323951');

-- COLÉGIO DESAFIO (SÃO GONÇALO DO SAPUCAÍ)
UPDATE schools SET inep_code = '316113' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DESAFIO' AND UPPER(TRIM(city)) = 'SÃO GONÇALO DO SAPUCAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '316113');

-- COLEGIO IRMÃO LUCAS (SÃO GONÇALO DO SAPUCAÍ)
UPDATE schools SET inep_code = '258920' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLEGIO IRMÃO LUCAS' AND UPPER(TRIM(city)) = 'SÃO GONÇALO DO SAPUCAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '258920');