-- EE CORONEL JOSÉ VENÂNCIO DE SOUSA (ÁGUAS VERMELHAS)
UPDATE schools SET inep_code = '184381' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL JOSÉ VENÂNCIO DE SOUSA' AND UPPER(TRIM(city)) = 'ÁGUAS VERMELHAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184381');

-- EE DE ITAMARATI (ÁGUAS VERMELHAS)
UPDATE schools SET inep_code = '184462' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ITAMARATI' AND UPPER(TRIM(city)) = 'ÁGUAS VERMELHAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184462');

-- EE DE MACHADO MINEIRO (ÁGUAS VERMELHAS)
UPDATE schools SET inep_code = '184403' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE MACHADO MINEIRO' AND UPPER(TRIM(city)) = 'ÁGUAS VERMELHAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184403');

-- EE JOAQUIM FERNANDES ABADE (ÁGUAS VERMELHAS)
UPDATE schools SET inep_code = '184420' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOAQUIM FERNANDES ABADE' AND UPPER(TRIM(city)) = 'ÁGUAS VERMELHAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184420');

-- CESEC QUERUBIM FRÓES OTONI (ALMENARA)
UPDATE schools SET inep_code = '184578' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC QUERUBIM FRÓES OTONI' AND UPPER(TRIM(city)) = 'ALMENARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184578');

-- EE CONDE AFONSO CELSO (ALMENARA)
UPDATE schools SET inep_code = '184527' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CONDE AFONSO CELSO' AND UPPER(TRIM(city)) = 'ALMENARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184527');

-- EE DE PEDRA GRANDE (ALMENARA)
UPDATE schools SET inep_code = '184608' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE PEDRA GRANDE' AND UPPER(TRIM(city)) = 'ALMENARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184608');

-- EE JOEL MARES (ALMENARA)
UPDATE schools SET inep_code = '246336' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOEL MARES' AND UPPER(TRIM(city)) = 'ALMENARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246336');

-- EE JOVIANO NAVES (ALMENARA)
UPDATE schools SET inep_code = '184551' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOVIANO NAVES' AND UPPER(TRIM(city)) = 'ALMENARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184551');

-- EE LAUDELINA DIAS LACERDA (ALMENARA)
UPDATE schools SET inep_code = '184543' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LAUDELINA DIAS LACERDA' AND UPPER(TRIM(city)) = 'ALMENARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184543');

-- EE TANCREDO NEVES (ALMENARA)
UPDATE schools SET inep_code = '184519' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE TANCREDO NEVES' AND UPPER(TRIM(city)) = 'ALMENARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184519');

-- EE JOÃO DOS SANTOS AMARAL (BANDEIRA)
UPDATE schools SET inep_code = '184632' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO DOS SANTOS AMARAL' AND UPPER(TRIM(city)) = 'BANDEIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184632');

-- EE BARÃO DO RIO BRANCO (CACHOEIRA DE PAJEÚ)
UPDATE schools SET inep_code = '184616' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BARÃO DO RIO BRANCO' AND UPPER(TRIM(city)) = 'CACHOEIRA DE PAJEÚ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184616');

-- EE DO CARIRI (CACHOEIRA DE PAJEÚ)
UPDATE schools SET inep_code = '246328' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DO CARIRI' AND UPPER(TRIM(city)) = 'CACHOEIRA DE PAJEÚ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246328');

-- EE DO POVOADO DE ÁGUAS ALTAS (CACHOEIRA DE PAJEÚ)
UPDATE schools SET inep_code = '205613' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DO POVOADO DE ÁGUAS ALTAS' AND UPPER(TRIM(city)) = 'CACHOEIRA DE PAJEÚ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '205613');

-- EE DE MARISTELA (CURRAL DE DENTRO)
UPDATE schools SET inep_code = '184411' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE MARISTELA' AND UPPER(TRIM(city)) = 'CURRAL DE DENTRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184411');

-- EE VERÍSSIMO TEIXEIRA COSTA (CURRAL DE DENTRO)
UPDATE schools SET inep_code = '184446' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE VERÍSSIMO TEIXEIRA COSTA' AND UPPER(TRIM(city)) = 'CURRAL DE DENTRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184446');

-- EE DE DIVISA ALEGRE (DIVISA ALEGRE)
UPDATE schools SET inep_code = '184454' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE DIVISA ALEGRE' AND UPPER(TRIM(city)) = 'DIVISA ALEGRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184454');

-- EE ALBERTO VICENTE PEREIRA (DIVISÓPOLIS)
UPDATE schools SET inep_code = '184586' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALBERTO VICENTE PEREIRA' AND UPPER(TRIM(city)) = 'DIVISÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184586');

-- EE DE FELISBURGO (FELISBURGO)
UPDATE schools SET inep_code = '184691' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE FELISBURGO' AND UPPER(TRIM(city)) = 'FELISBURGO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184691');

-- EE TRANQUILINO PINTO COELHO (FELISBURGO)
UPDATE schools SET inep_code = '184705' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE TRANQUILINO PINTO COELHO' AND UPPER(TRIM(city)) = 'FELISBURGO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184705');

-- EE ALÍPIO DE MORAES (JACINTO)
UPDATE schools SET inep_code = '184764' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALÍPIO DE MORAES' AND UPPER(TRIM(city)) = 'JACINTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184764');

-- EE DO HAVAÍ (JACINTO)
UPDATE schools SET inep_code = '184799' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DO HAVAÍ' AND UPPER(TRIM(city)) = 'JACINTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184799');

-- EE PROFESSOR ESTÊVÃO ARAÚJO (JACINTO)
UPDATE schools SET inep_code = '184756' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ESTÊVÃO ARAÚJO' AND UPPER(TRIM(city)) = 'JACINTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184756');

-- CESEC ZEMARIA DO NORTE (JEQUITINHONHA)
UPDATE schools SET inep_code = '184969' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC ZEMARIA DO NORTE' AND UPPER(TRIM(city)) = 'JEQUITINHONHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184969');

-- EE CORONEL JOÃO DA CUNHA (JEQUITINHONHA)
UPDATE schools SET inep_code = '184977' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL JOÃO DA CUNHA' AND UPPER(TRIM(city)) = 'JEQUITINHONHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184977');

-- EE CORONEL RAMIRO PEREIRA (JEQUITINHONHA)
UPDATE schools SET inep_code = '184837' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL RAMIRO PEREIRA' AND UPPER(TRIM(city)) = 'JEQUITINHONHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184837');

-- EE DOUTOR HENRIQUE HEITMANN (JEQUITINHONHA)
UPDATE schools SET inep_code = '232084' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR HENRIQUE HEITMANN' AND UPPER(TRIM(city)) = 'JEQUITINHONHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '232084');

-- EE PREFEITO EPAMINONDAS RAMOS (JEQUITINHONHA)
UPDATE schools SET inep_code = '185001' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PREFEITO EPAMINONDAS RAMOS' AND UPPER(TRIM(city)) = 'JEQUITINHONHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185001');

-- EE PROFESSOR MANUEL DO NORTE (JEQUITINHONHA)
UPDATE schools SET inep_code = '184900' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR MANUEL DO NORTE' AND UPPER(TRIM(city)) = 'JEQUITINHONHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184900');

-- EE SÃO MIGUEL (JEQUITINHONHA)
UPDATE schools SET inep_code = '184918' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO MIGUEL' AND UPPER(TRIM(city)) = 'JEQUITINHONHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184918');

-- EE DE GIRU (JOAÍMA)
UPDATE schools SET inep_code = '185043' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE GIRU' AND UPPER(TRIM(city)) = 'JOAÍMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185043');

-- EE PROFESSOR ANTÔNIO GOMES MOREIRA (JOAÍMA)
UPDATE schools SET inep_code = '185019' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ANTÔNIO GOMES MOREIRA' AND UPPER(TRIM(city)) = 'JOAÍMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185019');

-- EE PROFESSOR MANOEL DO NORTE (JOAÍMA)
UPDATE schools SET inep_code = '185051' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR MANOEL DO NORTE' AND UPPER(TRIM(city)) = 'JOAÍMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185051');

-- EE DE JORDÂNIA (JORDÂNIA)
UPDATE schools SET inep_code = '185078' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE JORDÂNIA' AND UPPER(TRIM(city)) = 'JORDÂNIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185078');

-- EE FREI HENRIQUE DE COIMBRA (JORDÂNIA)
UPDATE schools SET inep_code = '185086' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE FREI HENRIQUE DE COIMBRA' AND UPPER(TRIM(city)) = 'JORDÂNIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185086');

-- EE PROFESSOR MANOEL DA ROCHA PINTO (JORDÂNIA)
UPDATE schools SET inep_code = '185116' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR MANOEL DA ROCHA PINTO' AND UPPER(TRIM(city)) = 'JORDÂNIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185116');

-- EE DE MATA VERDE (MATA VERDE)
UPDATE schools SET inep_code = '184594' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE MATA VERDE' AND UPPER(TRIM(city)) = 'MATA VERDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184594');

-- EE JOSÉ FERREIRA DA ROCHA (MATA VERDE)
UPDATE schools SET inep_code = '209643' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ FERREIRA DA ROCHA' AND UPPER(TRIM(city)) = 'MATA VERDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '209643');

-- EE MANOEL DE SOUZA SANTOS (MONTE FORMOSO)
UPDATE schools SET inep_code = '185035' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MANOEL DE SOUZA SANTOS' AND UPPER(TRIM(city)) = 'MONTE FORMOSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185035');

-- EE DOIS DE ABRIL (PALMÓPOLIS)
UPDATE schools SET inep_code = '185329' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOIS DE ABRIL' AND UPPER(TRIM(city)) = 'PALMÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185329');

-- EE GOVERNADOR CLÓVIS SALGADO (PALMÓPOLIS)
UPDATE schools SET inep_code = '185353' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GOVERNADOR CLÓVIS SALGADO' AND UPPER(TRIM(city)) = 'PALMÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185353');

-- CESEC EDIRALVA DE OLIVEIRA ALMEIDA (PEDRA AZUL)
UPDATE schools SET inep_code = '311952' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC EDIRALVA DE OLIVEIRA ALMEIDA' AND UPPER(TRIM(city)) = 'PEDRA AZUL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '311952');

-- EE ANA FARIA (PEDRA AZUL)
UPDATE schools SET inep_code = '185213' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANA FARIA' AND UPPER(TRIM(city)) = 'PEDRA AZUL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185213');

-- EE CASSIANO MENDES (PEDRA AZUL)
UPDATE schools SET inep_code = '185205' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CASSIANO MENDES' AND UPPER(TRIM(city)) = 'PEDRA AZUL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185205');

-- EE CORONEL PACÍFICO FARIA (PEDRA AZUL)
UPDATE schools SET inep_code = '185221' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL PACÍFICO FARIA' AND UPPER(TRIM(city)) = 'PEDRA AZUL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185221');

-- EE DEPUTADO JOÃO DE ALMEIDA (PEDRA AZUL)
UPDATE schools SET inep_code = '212831' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DEPUTADO JOÃO DE ALMEIDA' AND UPPER(TRIM(city)) = 'PEDRA AZUL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '212831');

-- EE GENI MARIA DE SOUZA (RIO DO PRADO)
UPDATE schools SET inep_code = '353558' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GENI MARIA DE SOUZA' AND UPPER(TRIM(city)) = 'RIO DO PRADO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '353558');

-- EE TEREZINHA PORTO FAGUNDES (RIO DO PRADO)
UPDATE schools SET inep_code = '245160' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE TEREZINHA PORTO FAGUNDES' AND UPPER(TRIM(city)) = 'RIO DO PRADO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '245160');

-- EE LÍDIO ALMEIDA (RUBIM)
UPDATE schools SET inep_code = '185396' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LÍDIO ALMEIDA' AND UPPER(TRIM(city)) = 'RUBIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185396');

-- EE WALMIR ALMEIDA COSTA (RUBIM)
UPDATE schools SET inep_code = '185388' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE WALMIR ALMEIDA COSTA' AND UPPER(TRIM(city)) = 'RUBIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185388');

-- EE CORONEL ELPÍDIO ALVES FERREIRA (SALTO DA DIVISA)
UPDATE schools SET inep_code = '185400' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL ELPÍDIO ALVES FERREIRA' AND UPPER(TRIM(city)) = 'SALTO DA DIVISA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185400');

-- EE CORONEL TINÔ (SALTO DA DIVISA)
UPDATE schools SET inep_code = '185418' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL TINÔ' AND UPPER(TRIM(city)) = 'SALTO DA DIVISA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185418');

-- EE JOSÉ JOAQUIM CABRAL (SANTA MARIA DO SALTO)
UPDATE schools SET inep_code = '185442' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ JOAQUIM CABRAL' AND UPPER(TRIM(city)) = 'SANTA MARIA DO SALTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185442');

-- EE CLEMENTE DA ROCHA BANDEIRA (SANTO ANTÔNIO DO JACINTO)
UPDATE schools SET inep_code = '185451' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CLEMENTE DA ROCHA BANDEIRA' AND UPPER(TRIM(city)) = 'SANTO ANTÔNIO DO JACINTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185451');

-- EE DE CATAJÁS (SANTO ANTÔNIO DO JACINTO)
UPDATE schools SET inep_code = '185469' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE CATAJÁS' AND UPPER(TRIM(city)) = 'SANTO ANTÔNIO DO JACINTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185469');

-- EE DO POVOADO DE CRISTIANÓPOLIS (SANTO ANTÔNIO DO JACINTO)
UPDATE schools SET inep_code = '246301' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DO POVOADO DE CRISTIANÓPOLIS' AND UPPER(TRIM(city)) = 'SANTO ANTÔNIO DO JACINTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246301');

-- EE JOÃO VIEIRA DE SOUZA (SANTO ANTÔNIO DO JACINTO)
UPDATE schools SET inep_code = '218324' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO VIEIRA DE SOUZA' AND UPPER(TRIM(city)) = 'SANTO ANTÔNIO DO JACINTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218324');

-- EE BOM JESUS DE AGUADA NOVA (ARAÇUAÍ)
UPDATE schools SET inep_code = '146013' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BOM JESUS DE AGUADA NOVA' AND UPPER(TRIM(city)) = 'ARAÇUAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146013');

-- EE DA FAZENDA DIAMANTINO (ARAÇUAÍ)
UPDATE schools SET inep_code = '146048' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DA FAZENDA DIAMANTINO' AND UPPER(TRIM(city)) = 'ARAÇUAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146048');

-- EE DOM JOSÉ DE HAAS (ARAÇUAÍ)
UPDATE schools SET inep_code = '146081' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOM JOSÉ DE HAAS' AND UPPER(TRIM(city)) = 'ARAÇUAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146081');

-- EE FREI ROGATO (ARAÇUAÍ)
UPDATE schools SET inep_code = '247707' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE FREI ROGATO' AND UPPER(TRIM(city)) = 'ARAÇUAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '247707');

-- EE HILÁRIO PINHEIRO JARDIM (ARAÇUAÍ)
UPDATE schools SET inep_code = '146161' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE HILÁRIO PINHEIRO JARDIM' AND UPPER(TRIM(city)) = 'ARAÇUAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146161');

-- EE INDUSTRIAL SÃO JOSÉ (ARAÇUAÍ)
UPDATE schools SET inep_code = '146099' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE INDUSTRIAL SÃO JOSÉ' AND UPPER(TRIM(city)) = 'ARAÇUAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146099');

-- EE ISALTINA CAJUBI FULGÊNCIO (ARAÇUAÍ)
UPDATE schools SET inep_code = '146102' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ISALTINA CAJUBI FULGÊNCIO' AND UPPER(TRIM(city)) = 'ARAÇUAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146102');

-- EE JOSÉ DOS SANTOS NEIVA (ARAÇUAÍ)
UPDATE schools SET inep_code = '146170' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ DOS SANTOS NEIVA' AND UPPER(TRIM(city)) = 'ARAÇUAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146170');

-- EE PROFESSOR LEOPOLDO PEREIRA (ARAÇUAÍ)
UPDATE schools SET inep_code = '146129' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR LEOPOLDO PEREIRA' AND UPPER(TRIM(city)) = 'ARAÇUAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146129');

-- EE ANTÔNIO MARQUES DE ABREU (CHAPADA DO NORTE)
UPDATE schools SET inep_code = '338729' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO MARQUES DE ABREU' AND UPPER(TRIM(city)) = 'CHAPADA DO NORTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338729');

-- EE ALPHONSUS DE GUIMARÃES (COMERCINHO)
UPDATE schools SET inep_code = '184641' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALPHONSUS DE GUIMARÃES' AND UPPER(TRIM(city)) = 'COMERCINHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184641');

-- EE FERNANDO DA COSTA AMARAL (COMERCINHO)
UPDATE schools SET inep_code = '184667' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE FERNANDO DA COSTA AMARAL' AND UPPER(TRIM(city)) = 'COMERCINHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184667');

-- EE ARTHUR ANTÔNIO FERNANDES (CORONEL MURTA)
UPDATE schools SET inep_code = '146676' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ARTHUR ANTÔNIO FERNANDES' AND UPPER(TRIM(city)) = 'CORONEL MURTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146676');

-- EE CORONEL MARIANO MURTA (CORONEL MURTA)
UPDATE schools SET inep_code = '146650' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL MARIANO MURTA' AND UPPER(TRIM(city)) = 'CORONEL MURTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146650');

-- EE ANTÔNIO MIRANDA (INDAIABIRA)
UPDATE schools SET inep_code = '276898' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO MIRANDA' AND UPPER(TRIM(city)) = 'INDAIABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '276898');

-- EE CHAVES RIBEIRO (ITAOBIM)
UPDATE schools SET inep_code = '146889' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CHAVES RIBEIRO' AND UPPER(TRIM(city)) = 'ITAOBIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146889');

-- EE DE ITAOBIM (ITAOBIM)
UPDATE schools SET inep_code = '146897' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ITAOBIM' AND UPPER(TRIM(city)) = 'ITAOBIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146897');

-- EE IRMÃOS FERNANDES (ITAOBIM)
UPDATE schools SET inep_code = '146901' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE IRMÃOS FERNANDES' AND UPPER(TRIM(city)) = 'ITAOBIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146901');

-- EE PROFESSORA DEYS LOPES JARDIM (ITAOBIM)
UPDATE schools SET inep_code = '310271' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA DEYS LOPES JARDIM' AND UPPER(TRIM(city)) = 'ITAOBIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310271');

-- EE COMENDADOR MURTA (ITINGA)
UPDATE schools SET inep_code = '146951' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE COMENDADOR MURTA' AND UPPER(TRIM(city)) = 'ITINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146951');

-- EE DE ITINGA (ITINGA)
UPDATE schools SET inep_code = '322504' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ITINGA' AND UPPER(TRIM(city)) = 'ITINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322504');

-- EE DO POVOADO DE TAQUARAL (ITINGA)
UPDATE schools SET inep_code = '146978' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DO POVOADO DE TAQUARAL' AND UPPER(TRIM(city)) = 'ITINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146978');

-- EE MANOEL DA SILVA GUSMÃO (ITINGA)
UPDATE schools SET inep_code = '146986' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MANOEL DA SILVA GUSMÃO' AND UPPER(TRIM(city)) = 'ITINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146986');

-- EE ANTÔNIO RAMALHO MOTA (JENIPAPO DE MINAS)
UPDATE schools SET inep_code = '330621' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO RAMALHO MOTA' AND UPPER(TRIM(city)) = 'JENIPAPO DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '330621');

-- EE PADRE WILLY (JENIPAPO DE MINAS)
UPDATE schools SET inep_code = '330612' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE WILLY' AND UPPER(TRIM(city)) = 'JENIPAPO DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '330612');

-- EE ANÍBAL MELO (MEDINA)
UPDATE schools SET inep_code = '185175' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANÍBAL MELO' AND UPPER(TRIM(city)) = 'MEDINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185175');

-- EE DOUTOR MAX MACHADO (MEDINA)
UPDATE schools SET inep_code = '185191' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR MAX MACHADO' AND UPPER(TRIM(city)) = 'MEDINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185191');

-- EE JOÃO FRANCISCO COSTA (MEDINA)
UPDATE schools SET inep_code = '185183' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO FRANCISCO COSTA' AND UPPER(TRIM(city)) = 'MEDINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185183');

-- EE LUIZ TANURE (MEDINA)
UPDATE schools SET inep_code = '185159' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LUIZ TANURE' AND UPPER(TRIM(city)) = 'MEDINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185159');

-- EE MONSENHOR MANOEL (MEDINA)
UPDATE schools SET inep_code = '185124' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MONSENHOR MANOEL' AND UPPER(TRIM(city)) = 'MEDINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185124');

-- EE PROFESSOR QUERUBIM CIRINO DE MATOS (MEDINA)
UPDATE schools SET inep_code = '185167' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR QUERUBIM CIRINO DE MATOS' AND UPPER(TRIM(city)) = 'MEDINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185167');

-- EE DAVID FERRAZ DE OLIVEIRA (NINHEIRA)
UPDATE schools SET inep_code = '349259' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DAVID FERRAZ DE OLIVEIRA' AND UPPER(TRIM(city)) = 'NINHEIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349259');

-- EE PROFESSOR MARCIONILO PEREIRA DUTRA (NINHEIRA)
UPDATE schools SET inep_code = '338737' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR MARCIONILO PEREIRA DUTRA' AND UPPER(TRIM(city)) = 'NINHEIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338737');

-- EE DOUTOR OSVALDO PREDILIANO SANT'ANA (SALINAS)
UPDATE schools SET inep_code = '218189' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR OSVALDO PREDILIANO SANT''ANA' AND UPPER(TRIM(city)) = 'SALINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218189');

-- EE VICENTE JOSÉ FERREIRA (SALINAS)
UPDATE schools SET inep_code = '342807' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE VICENTE JOSÉ FERREIRA' AND UPPER(TRIM(city)) = 'SALINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342807');

-- EE DE ENSINO FUNDAMENTAL E MÉDIO (SANTA CRUZ DE SALINAS)
UPDATE schools SET inep_code = '361674' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL E MÉDIO' AND UPPER(TRIM(city)) = 'SANTA CRUZ DE SALINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '361674');

-- EE NOSSA SENHORA DA LAPA (VIRGEM DA LAPA)
UPDATE schools SET inep_code = '148521' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DA LAPA' AND UPPER(TRIM(city)) = 'VIRGEM DA LAPA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148521');

-- EE OLEGÁRIO MACIEL (VIRGEM DA LAPA)
UPDATE schools SET inep_code = '148482' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE OLEGÁRIO MACIEL' AND UPPER(TRIM(city)) = 'VIRGEM DA LAPA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148482');

-- EE SÃO DOMINGOS (VIRGEM DA LAPA)
UPDATE schools SET inep_code = '148491' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO DOMINGOS' AND UPPER(TRIM(city)) = 'VIRGEM DA LAPA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148491');

-- EE SÃO JOÃO DO VACARIA (VIRGEM DA LAPA)
UPDATE schools SET inep_code = '148504' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO JOÃO DO VACARIA' AND UPPER(TRIM(city)) = 'VIRGEM DA LAPA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148504');

-- EE VALDOMIRO SILVA COSTA (VIRGEM DA LAPA)
UPDATE schools SET inep_code = '148512' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE VALDOMIRO SILVA COSTA' AND UPPER(TRIM(city)) = 'VIRGEM DA LAPA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148512');

-- EE LIMA DUARTE (ANTÔNIO CARLOS)
UPDATE schools SET inep_code = '239372' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LIMA DUARTE' AND UPPER(TRIM(city)) = 'ANTÔNIO CARLOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '239372');

-- EE DE ENSINO FUNDAMENTAL E MÉDIO (BARBACENA)
UPDATE schools SET inep_code = '356905' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL E MÉDIO' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '356905');

-- EE DEPUTADO JOSÉ BONIFÁCIO LAFAYETTE DE ANDRADA (BARBACENA)
UPDATE schools SET inep_code = '273376' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DEPUTADO JOSÉ BONIFÁCIO LAFAYETTE DE ANDRADA' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '273376');

-- EE SENHORA DAS DORES (BARBACENA)
UPDATE schools SET inep_code = '302627' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SENHORA DAS DORES' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '302627');

-- EE RUBEM ESTEVES RUFFO (OLIVEIRA FORTES)
UPDATE schools SET inep_code = '338664' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE RUBEM ESTEVES RUFFO' AND UPPER(TRIM(city)) = 'OLIVEIRA FORTES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338664');

-- EE DOUTOR ANTÔNIO BATISTA DO NASCIMENTO (PIEDADE DO RIO GRANDE)
UPDATE schools SET inep_code = '248479' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR ANTÔNIO BATISTA DO NASCIMENTO' AND UPPER(TRIM(city)) = 'PIEDADE DO RIO GRANDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '248479');

-- EE PADRE EGYDIO REIS (SENHORA DOS REMÉDIOS)
UPDATE schools SET inep_code = '255611' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE EGYDIO REIS' AND UPPER(TRIM(city)) = 'SENHORA DOS REMÉDIOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '255611');

-- EE PROFESSOR LEONIDES ALVARENGA (AGUANIL)
UPDATE schools SET inep_code = '202134' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR LEONIDES ALVARENGA' AND UPPER(TRIM(city)) = 'AGUANIL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '202134');

-- EE NÉLSON FERNANDES FRIAÇA (CAMACHO)
UPDATE schools SET inep_code = '202177' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NÉLSON FERNANDES FRIAÇA' AND UPPER(TRIM(city)) = 'CAMACHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '202177');

-- CESEC PROFESSOR JOÃO DE OLIVEIRA  BARBOSA (CAMPO BELO)
UPDATE schools SET inep_code = '305219' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC PROFESSOR JOÃO DE OLIVEIRA  BARBOSA' AND UPPER(TRIM(city)) = 'CAMPO BELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305219');

-- EE ABÍLIO NEVES (CAMPO BELO)
UPDATE schools SET inep_code = '202185' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ABÍLIO NEVES' AND UPPER(TRIM(city)) = 'CAMPO BELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '202185');

-- EE JARBAS GAMBOGI (CAMPO BELO)
UPDATE schools SET inep_code = '202304' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JARBAS GAMBOGI' AND UPPER(TRIM(city)) = 'CAMPO BELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '202304');

-- EE MARIA BAUAB GIBRAM (CAMPO BELO)
UPDATE schools SET inep_code = '202355' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARIA BAUAB GIBRAM' AND UPPER(TRIM(city)) = 'CAMPO BELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '202355');

-- EE MIGUEL ROGANA (CAMPO BELO)
UPDATE schools SET inep_code = '202321' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MIGUEL ROGANA' AND UPPER(TRIM(city)) = 'CAMPO BELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '202321');

-- EE PADRE ALBERTO FUGER (CAMPO BELO)
UPDATE schools SET inep_code = '202193' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE ALBERTO FUGER' AND UPPER(TRIM(city)) = 'CAMPO BELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '202193');

-- EE PROFESSOR JOSÉ MONTEIRO (CAMPO BELO)
UPDATE schools SET inep_code = '202339' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOSÉ MONTEIRO' AND UPPER(TRIM(city)) = 'CAMPO BELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '202339');

-- EE DOUTOR JOSÉ ESTEVES DE ANDRADE BOTELHO (CANA VERDE)
UPDATE schools SET inep_code = '202401' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR JOSÉ ESTEVES DE ANDRADE BOTELHO' AND UPPER(TRIM(city)) = 'CANA VERDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '202401');

-- EE PADRE AMÉRICO (CANDEIAS)
UPDATE schools SET inep_code = '202487' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE AMÉRICO' AND UPPER(TRIM(city)) = 'CANDEIAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '202487');

-- EE PRESIDENTE KENNEDY (CANDEIAS)
UPDATE schools SET inep_code = '202495' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE KENNEDY' AND UPPER(TRIM(city)) = 'CANDEIAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '202495');

-- EE DOUTOR OSMAR BICALHO (CRISTAIS)
UPDATE schools SET inep_code = '202665' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR OSMAR BICALHO' AND UPPER(TRIM(city)) = 'CRISTAIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '202665');

-- COLÉGIO TIRADENTES PMMG (LAVRAS)
UPDATE schools SET inep_code = '203122' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '203122');

-- EE AZARIAS RIBEIRO (LAVRAS)
UPDATE schools SET inep_code = '202894' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE AZARIAS RIBEIRO' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '202894');

-- EE CINIRA CARVALHO (LAVRAS)
UPDATE schools SET inep_code = '217743' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CINIRA CARVALHO' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217743');

-- EE CRISTIANO DE SOUZA (LAVRAS)
UPDATE schools SET inep_code = '202908' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CRISTIANO DE SOUZA' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '202908');

-- EE DORA MATARAZZO (LAVRAS)
UPDATE schools SET inep_code = '202967' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DORA MATARAZZO' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '202967');

-- EE DOUTOR JOÃO BATISTA HERMETO (LAVRAS)
UPDATE schools SET inep_code = '202975' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR JOÃO BATISTA HERMETO' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '202975');

-- EE FIRMINO COSTA (LAVRAS)
UPDATE schools SET inep_code = '203009' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE FIRMINO COSTA' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '203009');

-- EE TIRADENTES (LAVRAS)
UPDATE schools SET inep_code = '203106' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE TIRADENTES' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '203106');

-- EE CARMELITA CARVALHO GARCIA (PERDÕES)
UPDATE schools SET inep_code = '203483' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CARMELITA CARVALHO GARCIA' AND UPPER(TRIM(city)) = 'PERDÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '203483');

-- EE ELVIRA LOPES RESENDE (PERDÕES)
UPDATE schools SET inep_code = '203491' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ELVIRA LOPES RESENDE' AND UPPER(TRIM(city)) = 'PERDÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '203491');

-- EE JOÃO MELO GOMIDE (PERDÕES)
UPDATE schools SET inep_code = '203441' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO MELO GOMIDE' AND UPPER(TRIM(city)) = 'PERDÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '203441');

-- EE PROFESSOR GETÚLIO JOSÉ SOARES (PERDÕES)
UPDATE schools SET inep_code = '203475' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR GETÚLIO JOSÉ SOARES' AND UPPER(TRIM(city)) = 'PERDÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '203475');

-- EE ANTÔNIO NOVAIS (RIBEIRÃO VERMELHO)
UPDATE schools SET inep_code = '203521' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO NOVAIS' AND UPPER(TRIM(city)) = 'RIBEIRÃO VERMELHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '203521');

-- EE CARMELITA CARVALHO GARCIA (SANTANA DO JACARÉ)
UPDATE schools SET inep_code = '203530' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CARMELITA CARVALHO GARCIA' AND UPPER(TRIM(city)) = 'SANTANA DO JACARÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '203530');

-- EE ALBERICO FERREIRA NAVES (SANTO ANTÔNIO DO AMPARO)
UPDATE schools SET inep_code = '134473' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALBERICO FERREIRA NAVES' AND UPPER(TRIM(city)) = 'SANTO ANTÔNIO DO AMPARO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134473');

-- EE DOUTOR CÍCERO FERREIRA (SANTO ANTÔNIO DO AMPARO)
UPDATE schools SET inep_code = '134490' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR CÍCERO FERREIRA' AND UPPER(TRIM(city)) = 'SANTO ANTÔNIO DO AMPARO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134490');

-- EE NEWTON FERREIRA DE PAIVA (SANTO ANTÔNIO DO AMPARO)
UPDATE schools SET inep_code = '134511' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NEWTON FERREIRA DE PAIVA' AND UPPER(TRIM(city)) = 'SANTO ANTÔNIO DO AMPARO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134511');

-- EE CORONEL MÁRIO CAMPOS (SÃO FRANCISCO DE PAULA)
UPDATE schools SET inep_code = '203564' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL MÁRIO CAMPOS' AND UPPER(TRIM(city)) = 'SÃO FRANCISCO DE PAULA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '203564');

-- EE MARIA ROSA DE FREITAS (FERVEDOURO)
UPDATE schools SET inep_code = '351148' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARIA ROSA DE FREITAS' AND UPPER(TRIM(city)) = 'FERVEDOURO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '351148');

-- EE MARIA CONCEIÇÃO GONÇALVES CARRARA (PEDRA DOURADA)
UPDATE schools SET inep_code = '322652' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARIA CONCEIÇÃO GONÇALVES CARRARA' AND UPPER(TRIM(city)) = 'PEDRA DOURADA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322652');

-- EE JOÃO PAULO II (BOM JESUS DO GALHO)
UPDATE schools SET inep_code = '213314' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO PAULO II' AND UPPER(TRIM(city)) = 'BOM JESUS DO GALHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '213314');

-- EE FELICIANO MIGUEL ABDALLA (CARATINGA)
UPDATE schools SET inep_code = '353450' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE FELICIANO MIGUEL ABDALLA' AND UPPER(TRIM(city)) = 'CARATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '353450');

-- EE MOACYR DE MATTOS (CARATINGA)
UPDATE schools SET inep_code = '253855' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MOACYR DE MATTOS' AND UPPER(TRIM(city)) = 'CARATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253855');

-- EE PROFESSOR JOAQUIM NUNES (CARATINGA)
UPDATE schools SET inep_code = '218766' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOAQUIM NUNES' AND UPPER(TRIM(city)) = 'CARATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218766');

-- EE PROFESSORA DINALVA MARIA DE SOUZA (PINGO-D'ÁGUA)
UPDATE schools SET inep_code = '213306' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA DINALVA MARIA DE SOUZA' AND UPPER(TRIM(city)) = 'PINGO-D''ÁGUA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '213306');

-- EE CONSELHEIRO FIDÉLIS (AIURUOCA)
UPDATE schools SET inep_code = '170682' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CONSELHEIRO FIDÉLIS' AND UPPER(TRIM(city)) = 'AIURUOCA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170682');

-- EE MARIA DO CARMO LIMA PINTO (ALAGOA)
UPDATE schools SET inep_code = '276464' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARIA DO CARMO LIMA PINTO' AND UPPER(TRIM(city)) = 'ALAGOA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '276464');

-- EE ANÍSIO ESAÚ DOS SANTOS (BAEPENDI)
UPDATE schools SET inep_code = '171026' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANÍSIO ESAÚ DOS SANTOS' AND UPPER(TRIM(city)) = 'BAEPENDI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '171026');

-- EE JOAQUIM ALVARENGA MACIEL (BAEPENDI)
UPDATE schools SET inep_code = '170984' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOAQUIM ALVARENGA MACIEL' AND UPPER(TRIM(city)) = 'BAEPENDI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170984');

-- EE NOSSA SENHORA DE MONTSERRAT (BAEPENDI)
UPDATE schools SET inep_code = '171042' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DE MONTSERRAT' AND UPPER(TRIM(city)) = 'BAEPENDI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '171042');

-- EE VARGEM DA LAGE (BAEPENDI)
UPDATE schools SET inep_code = '171051' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE VARGEM DA LAGE' AND UPPER(TRIM(city)) = 'BAEPENDI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '171051');

-- EE CÔNEGO JOÃO SEVERO (BOCAINA DE MINAS)
UPDATE schools SET inep_code = '294667' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CÔNEGO JOÃO SEVERO' AND UPPER(TRIM(city)) = 'BOCAINA DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '294667');

-- CEP-CENTRO DE EDUCAÇÃO PROFISSIONAL DE CAXAMBU (CAXAMBU)
UPDATE schools SET inep_code = '344656' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CEP-CENTRO DE EDUCAÇÃO PROFISSIONAL DE CAXAMBU' AND UPPER(TRIM(city)) = 'CAXAMBU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '344656');

-- EE CABO LUIZ DE QUEIROZ (CAXAMBU)
UPDATE schools SET inep_code = '311880' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CABO LUIZ DE QUEIROZ' AND UPPER(TRIM(city)) = 'CAXAMBU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '311880');

-- EE DOMINGOS GONÇALVES DE MELLO MINGOTE (CAXAMBU)
UPDATE schools SET inep_code = '172073' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOMINGOS GONÇALVES DE MELLO MINGOTE' AND UPPER(TRIM(city)) = 'CAXAMBU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '172073');

-- EE RUTH MARTINS DE ALMEIDA (CAXAMBU)
UPDATE schools SET inep_code = '172081' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE RUTH MARTINS DE ALMEIDA' AND UPPER(TRIM(city)) = 'CAXAMBU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '172081');

-- EE DOM OTHON MOTTA (CONCEIÇÃO DO RIO VERDE)
UPDATE schools SET inep_code = '172146' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOM OTHON MOTTA' AND UPPER(TRIM(city)) = 'CONCEIÇÃO DO RIO VERDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '172146');

-- EE PADRE PEDRO RIBEIRO DE CASTRO (CONCEIÇÃO DO RIO VERDE)
UPDATE schools SET inep_code = '172120' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE PEDRO RIBEIRO DE CASTRO' AND UPPER(TRIM(city)) = 'CONCEIÇÃO DO RIO VERDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '172120');

-- EE MONSENHOR JOÃO CÂNCIO (CRUZÍLIA)
UPDATE schools SET inep_code = '172456' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MONSENHOR JOÃO CÂNCIO' AND UPPER(TRIM(city)) = 'CRUZÍLIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '172456');

-- EE SÃO SEBASTIÃO (CRUZÍLIA)
UPDATE schools SET inep_code = '172464' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO SEBASTIÃO' AND UPPER(TRIM(city)) = 'CRUZÍLIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '172464');

-- EE NILO PEÇANHA (ITAMONTE)
UPDATE schools SET inep_code = '172847' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NILO PEÇANHA' AND UPPER(TRIM(city)) = 'ITAMONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '172847');

-- EE DONA SEMIANA (ITANHANDU)
UPDATE schools SET inep_code = '172910' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DONA SEMIANA' AND UPPER(TRIM(city)) = 'ITANHANDU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '172910');

-- EE PROFESSOR SOUZA NILO (ITANHANDU)
UPDATE schools SET inep_code = '172936' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR SOUZA NILO' AND UPPER(TRIM(city)) = 'ITANHANDU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '172936');

-- EE JOÃO DE ALMEIDA LISBOA (JESUÂNIA)
UPDATE schools SET inep_code = '172961' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO DE ALMEIDA LISBOA' AND UPPER(TRIM(city)) = 'JESUÂNIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '172961');

-- EE PROFESSORA MARIA ANTONIETA ROMANO SALGADO (OLÍMPIO NORONHA)
UPDATE schools SET inep_code = '173487' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA ANTONIETA ROMANO SALGADO' AND UPPER(TRIM(city)) = 'OLÍMPIO NORONHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '173487');

-- EE NOSSA SENHORA APARECIDA (PASSA QUATRO)
UPDATE schools SET inep_code = '173762' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA APARECIDA' AND UPPER(TRIM(city)) = 'PASSA QUATRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '173762');

-- EE PROFESSORA LOURDES CASTILHO FREITAS (PASSA QUATRO)
UPDATE schools SET inep_code = '173665' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA LOURDES CASTILHO FREITAS' AND UPPER(TRIM(city)) = 'PASSA QUATRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '173665');

-- EE FELIZARDA RUSSANO (POUSO ALTO)
UPDATE schools SET inep_code = '173916' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE FELIZARDA RUSSANO' AND UPPER(TRIM(city)) = 'POUSO ALTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '173916');

-- CESEC PROFESSORA NOÊMIA GOULART FERREIRA (SÃO LOURENÇO)
UPDATE schools SET inep_code = '174203' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC PROFESSORA NOÊMIA GOULART FERREIRA' AND UPPER(TRIM(city)) = 'SÃO LOURENÇO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174203');

-- EE DOUTOR HUMBERTO SANCHES (SÃO LOURENÇO)
UPDATE schools SET inep_code = '174149' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR HUMBERTO SANCHES' AND UPPER(TRIM(city)) = 'SÃO LOURENÇO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174149');

-- EE PROFESSOR ANTÔNIO MAGALHÃES ALVES (SÃO LOURENÇO)
UPDATE schools SET inep_code = '174190' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ANTÔNIO MAGALHÃES ALVES' AND UPPER(TRIM(city)) = 'SÃO LOURENÇO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174190');

-- EE PROFESSOR MÁRIO JUNQUEIRA FERRAZ (SÃO LOURENÇO)
UPDATE schools SET inep_code = '174181' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR MÁRIO JUNQUEIRA FERRAZ' AND UPPER(TRIM(city)) = 'SÃO LOURENÇO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174181');

-- EE PROFESSOR TÚLIO BENTO (SÃO LOURENÇO)
UPDATE schools SET inep_code = '356832' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR TÚLIO BENTO' AND UPPER(TRIM(city)) = 'SÃO LOURENÇO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '356832');

-- EE JOSÉ RIBEIRO MIRA (SÃO SEBASTIÃO DO RIO VERDE)
UPDATE schools SET inep_code = '330744' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ RIBEIRO MIRA' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO RIO VERDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '330744');

-- EE DO SOBRADINHO (SÃO THOMÉ DAS LETRAS)
UPDATE schools SET inep_code = '174220' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DO SOBRADINHO' AND UPPER(TRIM(city)) = 'SÃO THOMÉ DAS LETRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174220');

-- EE JOSÉ CRISTIANO ALVES (SÃO THOMÉ DAS LETRAS)
UPDATE schools SET inep_code = '174246' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ CRISTIANO ALVES' AND UPPER(TRIM(city)) = 'SÃO THOMÉ DAS LETRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174246');

-- EE MINISTRO CLÓVIS SALGADO (SERITINGA)
UPDATE schools SET inep_code = '174289' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MINISTRO CLÓVIS SALGADO' AND UPPER(TRIM(city)) = 'SERITINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174289');

-- EE NOSSA SENHORA DO BONSUCESSO (SERRANOS)
UPDATE schools SET inep_code = '305260' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DO BONSUCESSO' AND UPPER(TRIM(city)) = 'SERRANOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305260');

-- EE DONA MARIANA CARVALHAL COSTA (SOLEDADE DE MINAS)
UPDATE schools SET inep_code = '174319' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DONA MARIANA CARVALHAL COSTA' AND UPPER(TRIM(city)) = 'SOLEDADE DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174319');

-- EE SILVESTRE NUNES (CASA GRANDE)
UPDATE schools SET inep_code = '193348' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SILVESTRE NUNES' AND UPPER(TRIM(city)) = 'CASA GRANDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193348');

-- EE GUSTAVO AUGUSTO DA SILVA (CATAS ALTAS DA NORUEGA)
UPDATE schools SET inep_code = '193356' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GUSTAVO AUGUSTO DA SILVA' AND UPPER(TRIM(city)) = 'CATAS ALTAS DA NORUEGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193356');

-- EE BARÃO DE PARAOPEBA (CONGONHAS)
UPDATE schools SET inep_code = '193399' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BARÃO DE PARAOPEBA' AND UPPER(TRIM(city)) = 'CONGONHAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193399');

-- EE FELICIANO MENDES (CONGONHAS)
UPDATE schools SET inep_code = '193429' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE FELICIANO MENDES' AND UPPER(TRIM(city)) = 'CONGONHAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193429');

-- EE LAMARTINE DE FREITAS (CONGONHAS)
UPDATE schools SET inep_code = '193453' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LAMARTINE DE FREITAS' AND UPPER(TRIM(city)) = 'CONGONHAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193453');

-- EE AUGUSTO JOSÉ VIEIRA (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '193551' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE AUGUSTO JOSÉ VIEIRA' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193551');

-- EE DOMINGOS BEBIANO (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '193577' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOMINGOS BEBIANO' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193577');

-- EE DOUTOR ANTERO CHAVES (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '193593' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR ANTERO CHAVES' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193593');

-- EE DOUTOR ANTONIO NOGUEIRA DE REZENDE (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '193801' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR ANTONIO NOGUEIRA DE REZENDE' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193801');

-- EE GENERAL SYLVIO RAULINO DE OLIVEIRA (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '193631' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GENERAL SYLVIO RAULINO DE OLIVEIRA' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193631');

-- EE GERALDO BITTENCOURT (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '193658' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GERALDO BITTENCOURT' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193658');

-- EE ISAURA FERREIRA (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '193691' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ISAURA FERREIRA' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193691');

-- EE LOPES FRANCO (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '193747' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LOPES FRANCO' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193747');

-- EE LUIZ DE MELLO VIANNA SOBRINHO (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '193755' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LUIZ DE MELLO VIANNA SOBRINHO' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193755');

-- EE MOACIR DE SOUZA DIAS (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '219037' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MOACIR DE SOUZA DIAS' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '219037');

-- EE MONSENHOR ANTÔNIO JOSÉ FERREIRA (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '193682' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MONSENHOR ANTÔNIO JOSÉ FERREIRA' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193682');

-- EE MONSENHOR HORTA (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '193666' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MONSENHOR HORTA' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193666');

-- EE NARCISO DE QUEIRÓS (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '193771' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NARCISO DE QUEIRÓS' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193771');

-- EE PACÍFICO VIEIRA (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '193780' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PACÍFICO VIEIRA' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193780');

-- EE PROFESSOR ASTOR VIANNA (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '193542' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ASTOR VIANNA' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193542');

-- EE QUEIROZ JÚNIOR (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '193585' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE QUEIROZ JÚNIOR' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193585');

-- EE CORONEL ALCIDES DUTRA (CRISTIANO OTONI)
UPDATE schools SET inep_code = '193828' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL ALCIDES DUTRA' AND UPPER(TRIM(city)) = 'CRISTIANO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193828');

-- EE CARMELA DUTRA (DESTERRO DE ENTRE RIOS)
UPDATE schools SET inep_code = '193879' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CARMELA DUTRA' AND UPPER(TRIM(city)) = 'DESTERRO DE ENTRE RIOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193879');

-- EE EVARISTO AUGUSTO DE OLIVEIRA (DESTERRO DE ENTRE RIOS)
UPDATE schools SET inep_code = '193895' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE EVARISTO AUGUSTO DE OLIVEIRA' AND UPPER(TRIM(city)) = 'DESTERRO DE ENTRE RIOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193895');

-- EE NOSSA SENHORA DE FÁTIMA (DESTERRO DE ENTRE RIOS)
UPDATE schools SET inep_code = '193852' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DE FÁTIMA' AND UPPER(TRIM(city)) = 'DESTERRO DE ENTRE RIOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193852');

-- EE DOM RODOLFO (ENTRE RIOS DE MINAS)
UPDATE schools SET inep_code = '218383' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOM RODOLFO' AND UPPER(TRIM(city)) = 'ENTRE RIOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218383');

-- EE EXPEDICIONÁRIO GERALDO BAETA (ENTRE RIOS DE MINAS)
UPDATE schools SET inep_code = '193925' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE EXPEDICIONÁRIO GERALDO BAETA' AND UPPER(TRIM(city)) = 'ENTRE RIOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193925');

-- EE PEDRO DOMINGUES (ENTRE RIOS DE MINAS)
UPDATE schools SET inep_code = '193950' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PEDRO DOMINGUES' AND UPPER(TRIM(city)) = 'ENTRE RIOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193950');

-- EE RIBEIRO DE OLIVEIRA (ENTRE RIOS DE MINAS)
UPDATE schools SET inep_code = '193968' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE RIBEIRO DE OLIVEIRA' AND UPPER(TRIM(city)) = 'ENTRE RIOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193968');

-- EE CONSELHEIRO ANTÃO (ITAVERAVA)
UPDATE schools SET inep_code = '193992' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CONSELHEIRO ANTÃO' AND UPPER(TRIM(city)) = 'ITAVERAVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '193992');

-- EE PROFESSORA NOEMI NOGUEIRA (ITAVERAVA)
UPDATE schools SET inep_code = '194000' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA NOEMI NOGUEIRA' AND UPPER(TRIM(city)) = 'ITAVERAVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '194000');

-- EE SANTOS REIS (JECEABA)
UPDATE schools SET inep_code = '194042' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SANTOS REIS' AND UPPER(TRIM(city)) = 'JECEABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '194042');

-- EE NAPOLEÃO REIS (LAMIM)
UPDATE schools SET inep_code = '194107' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NAPOLEÃO REIS' AND UPPER(TRIM(city)) = 'LAMIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '194107');

-- EE CÔNEGO LUIZ VIEIRA DA SILVA (OURO BRANCO)
UPDATE schools SET inep_code = '194123' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CÔNEGO LUIZ VIEIRA DA SILVA' AND UPPER(TRIM(city)) = 'OURO BRANCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '194123');

-- EE IRACEMA DE ALMEIDA (OURO BRANCO)
UPDATE schools SET inep_code = '194158' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE IRACEMA DE ALMEIDA' AND UPPER(TRIM(city)) = 'OURO BRANCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '194158');

-- EE LEVINDO COSTA CARVALHO (OURO BRANCO)
UPDATE schools SET inep_code = '194182' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LEVINDO COSTA CARVALHO' AND UPPER(TRIM(city)) = 'OURO BRANCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '194182');

-- EE ANTÔNIO DE PAULA DIAS (PIRANGA)
UPDATE schools SET inep_code = '194298' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO DE PAULA DIAS' AND UPPER(TRIM(city)) = 'PIRANGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '194298');

-- EE CORONEL AMANTINO MACIEL (PIRANGA)
UPDATE schools SET inep_code = '194191' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL AMANTINO MACIEL' AND UPPER(TRIM(city)) = 'PIRANGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '194191');

-- EE CORONEL JOSÉ ILDEFONSO (PIRANGA)
UPDATE schools SET inep_code = '194204' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL JOSÉ ILDEFONSO' AND UPPER(TRIM(city)) = 'PIRANGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '194204');

-- EE FRANCISCO FERREIRA MACIEL (PIRANGA)
UPDATE schools SET inep_code = '194263' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE FRANCISCO FERREIRA MACIEL' AND UPPER(TRIM(city)) = 'PIRANGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '194263');

-- EE FRANCISCO SALES FERREIRA (PIRANGA)
UPDATE schools SET inep_code = '194255' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE FRANCISCO SALES FERREIRA' AND UPPER(TRIM(city)) = 'PIRANGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '194255');

-- EE SANTO AMARO (QUELUZITO)
UPDATE schools SET inep_code = '194328' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SANTO AMARO' AND UPPER(TRIM(city)) = 'QUELUZITO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '194328');

-- EE MONSENHOR FRANCISCO MIGUEL FERNANDES (RIO ESPERA)
UPDATE schools SET inep_code = '196347' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MONSENHOR FRANCISCO MIGUEL FERNANDES' AND UPPER(TRIM(city)) = 'RIO ESPERA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196347');

-- EE DR JOÃO NOGUEIRA DE ALMEIDA (SANTANA DOS MONTES)
UPDATE schools SET inep_code = '194395' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DR JOÃO NOGUEIRA DE ALMEIDA' AND UPPER(TRIM(city)) = 'SANTANA DOS MONTES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '194395');

-- EE DESEMBARGADOR APRÍGIO RIBEIRO DE OLIVEIRA (SÃO BRÁS DO SUAÇUÍ)
UPDATE schools SET inep_code = '194425' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DESEMBARGADOR APRÍGIO RIBEIRO DE OLIVEIRA' AND UPPER(TRIM(city)) = 'SÃO BRÁS DO SUAÇUÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '194425');

-- EE QUINZINHO INÁCIO (SENHORA DE OLIVEIRA)
UPDATE schools SET inep_code = '194468' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE QUINZINHO INÁCIO' AND UPPER(TRIM(city)) = 'SENHORA DE OLIVEIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '194468');

-- EE GERMANO PEDRO DE SOUZA (ANTÔNIO DIAS)
UPDATE schools SET inep_code = '190705' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GERMANO PEDRO DE SOUZA' AND UPPER(TRIM(city)) = 'ANTÔNIO DIAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '190705');

-- EE PROFESSOR LETRO (ANTÔNIO DIAS)
UPDATE schools SET inep_code = '190683' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR LETRO' AND UPPER(TRIM(city)) = 'ANTÔNIO DIAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '190683');

-- EE VICENTE INÁCIO BISPO (ANTÔNIO DIAS)
UPDATE schools SET inep_code = '190659' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE VICENTE INÁCIO BISPO' AND UPPER(TRIM(city)) = 'ANTÔNIO DIAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '190659');

-- EE JOÃO HEMÉTRIO DE MENEZES (BELO ORIENTE)
UPDATE schools SET inep_code = '273368' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO HEMÉTRIO DE MENEZES' AND UPPER(TRIM(city)) = 'BELO ORIENTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '273368');

-- EE PRESIDENTE TANCREDO NEVES (BELO ORIENTE)
UPDATE schools SET inep_code = '190756' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE TANCREDO NEVES' AND UPPER(TRIM(city)) = 'BELO ORIENTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '190756');

-- EE FAGUNDES VARELA (BRAÚNAS)
UPDATE schools SET inep_code = '190772' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE FAGUNDES VARELA' AND UPPER(TRIM(city)) = 'BRAÚNAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '190772');

-- EE MARIA IZABEL MOREIRA PINTO (BRAÚNAS)
UPDATE schools SET inep_code = '190799' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARIA IZABEL MOREIRA PINTO' AND UPPER(TRIM(city)) = 'BRAÚNAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '190799');

-- EE ALBERTO GIOVANNINI (CORONEL FABRICIANO)
UPDATE schools SET inep_code = '190802' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALBERTO GIOVANNINI' AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '190802');

-- EE CORONEL SILVINO PEREIRA (CORONEL FABRICIANO)
UPDATE schools SET inep_code = '190926' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL SILVINO PEREIRA' AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '190926');

-- EE DOUTOR GERALDO PERLINGEIRO DE ABREU (CORONEL FABRICIANO)
UPDATE schools SET inep_code = '221449' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR GERALDO PERLINGEIRO DE ABREU' AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '221449');

-- EE DOUTOR JOAQUIM GOMES DA SILVEIRA NETO (CORONEL FABRICIANO)
UPDATE schools SET inep_code = '190829' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR JOAQUIM GOMES DA SILVEIRA NETO' AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '190829');

-- EE PADRE JOSÉ MARIA DE MAN (CORONEL FABRICIANO)
UPDATE schools SET inep_code = '190942' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE JOSÉ MARIA DE MAN' AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '190942');

-- EE PROFESSOR PEDRO CALMON (CORONEL FABRICIANO)
UPDATE schools SET inep_code = '190888' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR PEDRO CALMON' AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '190888');

-- EE PROFESSORA CELINA MACHADO (CORONEL FABRICIANO)
UPDATE schools SET inep_code = '190900' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA CELINA MACHADO' AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '190900');

-- EE RAULINO COTTA PACHECO (CORONEL FABRICIANO)
UPDATE schools SET inep_code = '190918' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE RAULINO COTTA PACHECO' AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '190918');

-- EE ROTILDINO AVELINO (CORONEL FABRICIANO)
UPDATE schools SET inep_code = '190969' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ROTILDINO AVELINO' AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '190969');

-- EE TANCREDO DE ALMEIDA NEVES (CORONEL FABRICIANO)
UPDATE schools SET inep_code = '190985' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE TANCREDO DE ALMEIDA NEVES' AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '190985');

-- EE ZACARIAS ROQUE (CORONEL FABRICIANO)
UPDATE schools SET inep_code = '190977' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ZACARIAS ROQUE' AND UPPER(TRIM(city)) = 'CORONEL FABRICIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '190977');

-- CESEC JOÃO GUIMARÃES ROSA (IPATINGA)
UPDATE schools SET inep_code = '313726' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC JOÃO GUIMARÃES ROSA' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '313726');

-- COLÉGIO TIRADENTES PMMG (IPATINGA)
UPDATE schools SET inep_code = '191132' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191132');

-- EE ALMIRANTE TOYODA (IPATINGA)
UPDATE schools SET inep_code = '190993' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALMIRANTE TOYODA' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '190993');

-- EE CHICO MENDES (IPATINGA)
UPDATE schools SET inep_code = '191281' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CHICO MENDES' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191281');

-- EE DOM HELVÉCIO (IPATINGA)
UPDATE schools SET inep_code = '191027' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOM HELVÉCIO' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191027');

-- EE DONA CAETANA AMÉRICA MENEZES (IPATINGA)
UPDATE schools SET inep_code = '191191' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DONA CAETANA AMÉRICA MENEZES' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191191');

-- EE DONA CANUTA ROSA OLIVEIRA BARBOSA (IPATINGA)
UPDATE schools SET inep_code = '191221' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DONA CANUTA ROSA OLIVEIRA BARBOSA' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191221');

-- EE DOUTOR OVÍDIO DE ANDRADE (IPATINGA)
UPDATE schools SET inep_code = '191035' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR OVÍDIO DE ANDRADE' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191035');