-- EE PROFESSOR MENDONÇA (SENADOR JOSÉ BENTO)
UPDATE schools SET inep_code = '124982' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR MENDONÇA' AND UPPER(TRIM(city)) = 'SENADOR JOSÉ BENTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '124982');

-- EE ANTÔNIO CARLOS DE CARVALHO (BOM SUCESSO)
UPDATE schools SET inep_code = '133728' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO CARLOS DE CARVALHO' AND UPPER(TRIM(city)) = 'BOM SUCESSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '133728');

-- EE BENJAMIM GUIMARÃES (BOM SUCESSO)
UPDATE schools SET inep_code = '133744' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BENJAMIM GUIMARÃES' AND UPPER(TRIM(city)) = 'BOM SUCESSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '133744');

-- EE SARA KUBITSCHEK (CARRANCAS)
UPDATE schools SET inep_code = '133922' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SARA KUBITSCHEK' AND UPPER(TRIM(city)) = 'CARRANCAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '133922');

-- EE ADÍLIO JOSÉ BORGES (CONCEIÇÃO DA BARRA DE MINAS)
UPDATE schools SET inep_code = '133931' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ADÍLIO JOSÉ BORGES' AND UPPER(TRIM(city)) = 'CONCEIÇÃO DA BARRA DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '133931');

-- EE CORONEL XAVIER CHAVES (CORONEL XAVIER CHAVES)
UPDATE schools SET inep_code = '133949' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL XAVIER CHAVES' AND UPPER(TRIM(city)) = 'CORONEL XAVIER CHAVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '133949');

-- EE DUQUE DE CAXIAS (DORES DE CAMPOS)
UPDATE schools SET inep_code = '133973' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DUQUE DE CAXIAS' AND UPPER(TRIM(city)) = 'DORES DE CAMPOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '133973');

-- EE PROFESSOR JÚLIO BUENO (IBITURUNA)
UPDATE schools SET inep_code = '134007' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JÚLIO BUENO' AND UPPER(TRIM(city)) = 'IBITURUNA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134007');

-- EE MAURÍCIO ZAKHIA (IJACI)
UPDATE schools SET inep_code = '134040' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MAURÍCIO ZAKHIA' AND UPPER(TRIM(city)) = 'IJACI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134040');

-- EE RAMIRO DE SOUZA ANDRADE (INGAÍ)
UPDATE schools SET inep_code = '134104' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE RAMIRO DE SOUZA ANDRADE' AND UPPER(TRIM(city)) = 'INGAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134104');

-- EE CERRADO DO ROSÁRIO (ITUMIRIM)
UPDATE schools SET inep_code = '134139' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CERRADO DO ROSÁRIO' AND UPPER(TRIM(city)) = 'ITUMIRIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134139');

-- EE DE MACUCO DE MINAS (ITUMIRIM)
UPDATE schools SET inep_code = '134147' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE MACUCO DE MINAS' AND UPPER(TRIM(city)) = 'ITUMIRIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134147');

-- EE DOM DELFIM (ITUMIRIM)
UPDATE schools SET inep_code = '134121' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOM DELFIM' AND UPPER(TRIM(city)) = 'ITUMIRIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134121');

-- EE JAIME FERREIRA LEITE (ITUTINGA)
UPDATE schools SET inep_code = '134163' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JAIME FERREIRA LEITE' AND UPPER(TRIM(city)) = 'ITUTINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134163');

-- EE ABEILARD PEREIRA (LAGOA DOURADA)
UPDATE schools SET inep_code = '305600' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ABEILARD PEREIRA' AND UPPER(TRIM(city)) = 'LAGOA DOURADA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305600');

-- EE PROFESSOR BASÍLIO DE MAGALHÃES (NAZARENO)
UPDATE schools SET inep_code = '134295' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR BASÍLIO DE MAGALHÃES' AND UPPER(TRIM(city)) = 'NAZARENO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134295');

-- EE DOUTOR VIVIANO CALDAS (PRADOS)
UPDATE schools SET inep_code = '134333' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR VIVIANO CALDAS' AND UPPER(TRIM(city)) = 'PRADOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134333');

-- EE ASSIS RESENDE (RESENDE COSTA)
UPDATE schools SET inep_code = '134368' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ASSIS RESENDE' AND UPPER(TRIM(city)) = 'RESENDE COSTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134368');

-- EE PADRE CRISPINIANO (RITÁPOLIS)
UPDATE schools SET inep_code = '134414' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE CRISPINIANO' AND UPPER(TRIM(city)) = 'RITÁPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134414');

-- EE AMÉLIA PASSOS (SANTA CRUZ DE MINAS)
UPDATE schools SET inep_code = '134911' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE AMÉLIA PASSOS' AND UPPER(TRIM(city)) = 'SANTA CRUZ DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134911');

-- CESEC PROFESSOR JOSÉ AMÉRICO DA COSTA (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '134759' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC PROFESSOR JOSÉ AMÉRICO DA COSTA' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134759');

-- COLÉGIO TIRADENTES PMMG - UNIDADE SÃO JOÃO DEL REI (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '368148' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG - UNIDADE SÃO JOÃO DEL REI' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368148');

-- EE BRIGHENTI CESARE (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '134546' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BRIGHENTI CESARE' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134546');

-- EE CÔNEGO OSVALDO LUSTOSA (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '134562' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CÔNEGO OSVALDO LUSTOSA' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134562');

-- EE DOUTOR GARCIA DE LIMA (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '134619' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR GARCIA DE LIMA' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134619');

-- EE EVANDRO ÁVILA (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '134791' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE EVANDRO ÁVILA' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134791');

-- EE GOVERNADOR MILTON CAMPOS (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '134635' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GOVERNADOR MILTON CAMPOS' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134635');

-- EE IDALINA HORTA GALVÃO (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '134643' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE IDALINA HORTA GALVÃO' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134643');

-- EE INÁCIO PASSOS (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '134651' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE INÁCIO PASSOS' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134651');

-- EE JOÃO DOS SANTOS (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '134660' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO DOS SANTOS' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134660');

-- EE MINISTRO GABRIEL PASSOS (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '134694' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MINISTRO GABRIEL PASSOS' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134694');

-- EE PADRE LOPES (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '134805' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE LOPES' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134805');

-- EE PROFESSOR IAGO PIMENTEL (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '134716' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR IAGO PIMENTEL' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134716');

-- EE TOMÉ PORTES DEL REI (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '134724' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE TOMÉ PORTES DEL REI' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134724');

-- EE AFONSO PENA JÚNIOR (SÃO TIAGO)
UPDATE schools SET inep_code = '134813' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE AFONSO PENA JÚNIOR' AND UPPER(TRIM(city)) = 'SÃO TIAGO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134813');

-- EE DE MERCÊS DE ÁGUA LIMPA (SÃO TIAGO)
UPDATE schools SET inep_code = '134872' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE MERCÊS DE ÁGUA LIMPA' AND UPPER(TRIM(city)) = 'SÃO TIAGO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134872');

-- EE BASÍLIO DA GAMA (TIRADENTES)
UPDATE schools SET inep_code = '134881' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BASÍLIO DA GAMA' AND UPPER(TRIM(city)) = 'TIRADENTES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134881');

-- EE CORONEL LUCAS MAGALHÃES (ARCEBURGO)
UPDATE schools SET inep_code = '136875' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL LUCAS MAGALHÃES' AND UPPER(TRIM(city)) = 'ARCEBURGO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '136875');

-- EE DOUTOR JOSÉ TEODORO DE SOUZA (CAPETINGA)
UPDATE schools SET inep_code = '136891' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR JOSÉ TEODORO DE SOUZA' AND UPPER(TRIM(city)) = 'CAPETINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '136891');

-- EE MELO VIANA (CÁSSIA)
UPDATE schools SET inep_code = '137006' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MELO VIANA' AND UPPER(TRIM(city)) = 'CÁSSIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137006');

-- EE SÃO GABRIEL (CÁSSIA)
UPDATE schools SET inep_code = '136948' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO GABRIEL' AND UPPER(TRIM(city)) = 'CÁSSIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '136948');

-- EE IARBAS RODRIGUES (CLARAVAL)
UPDATE schools SET inep_code = '137065' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE IARBAS RODRIGUES' AND UPPER(TRIM(city)) = 'CLARAVAL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137065');

-- EE ALICE AUTRAN DOURADO (GUARANÉSIA)
UPDATE schools SET inep_code = '137073' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALICE AUTRAN DOURADO' AND UPPER(TRIM(city)) = 'GUARANÉSIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137073');

-- EE GERALDO RIBEIRO DIAS (GUARANÉSIA)
UPDATE schools SET inep_code = '137146' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GERALDO RIBEIRO DIAS' AND UPPER(TRIM(city)) = 'GUARANÉSIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137146');

-- EE DONA QUERIDINHA BIAS FORTES (GUAXUPÉ)
UPDATE schools SET inep_code = '137227' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DONA QUERIDINHA BIAS FORTES' AND UPPER(TRIM(city)) = 'GUAXUPÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137227');

-- EE DOUTOR ANDRÉ CORTEZ GRANERO (GUAXUPÉ)
UPDATE schools SET inep_code = '137324' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR ANDRÉ CORTEZ GRANERO' AND UPPER(TRIM(city)) = 'GUAXUPÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137324');

-- EE DOUTOR BENEDITO LEITE RIBEIRO (GUAXUPÉ)
UPDATE schools SET inep_code = '137235' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR BENEDITO LEITE RIBEIRO' AND UPPER(TRIM(city)) = 'GUAXUPÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137235');

-- EE MAJOR LUIZ ZERBINI (GUAXUPÉ)
UPDATE schools SET inep_code = '137251' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MAJOR LUIZ ZERBINI' AND UPPER(TRIM(city)) = 'GUAXUPÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137251');

-- EE NOSSA SENHORA APARECIDA (GUAXUPÉ)
UPDATE schools SET inep_code = '137278' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA APARECIDA' AND UPPER(TRIM(city)) = 'GUAXUPÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137278');

-- EE DE IBIRACI (IBIRACI)
UPDATE schools SET inep_code = '137341' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE IBIRACI' AND UPPER(TRIM(city)) = 'IBIRACI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137341');

-- EE DE ITAMOGI (ITAMOGI)
UPDATE schools SET inep_code = '137413' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ITAMOGI' AND UPPER(TRIM(city)) = 'ITAMOGI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137413');

-- EE JOSÉ SOARES DE ARAÚJO (ITAMOGI)
UPDATE schools SET inep_code = '137456' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ SOARES DE ARAÚJO' AND UPPER(TRIM(city)) = 'ITAMOGI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137456');

-- EE ARY PIMENTA BUGELLI (ITAÚ DE MINAS)
UPDATE schools SET inep_code = '240800' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ARY PIMENTA BUGELLI' AND UPPER(TRIM(city)) = 'ITAÚ DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '240800');

-- EE PROFESSORA MARIA LEONOR NASSER (JACUÍ)
UPDATE schools SET inep_code = '137502' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA LEONOR NASSER' AND UPPER(TRIM(city)) = 'JACUÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137502');

-- EE EDUARDO SENEDESE (JURUAIA)
UPDATE schools SET inep_code = '137529' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE EDUARDO SENEDESE' AND UPPER(TRIM(city)) = 'JURUAIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137529');

-- EE AMÉRICO DE PAIVA (MONTE SANTO DE MINAS)
UPDATE schools SET inep_code = '137545' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE AMÉRICO DE PAIVA' AND UPPER(TRIM(city)) = 'MONTE SANTO DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137545');

-- EE DE MILAGRE (MONTE SANTO DE MINAS)
UPDATE schools SET inep_code = '137669' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE MILAGRE' AND UPPER(TRIM(city)) = 'MONTE SANTO DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137669');

-- EE DOUTOR WENCESLAU BRAZ (MONTE SANTO DE MINAS)
UPDATE schools SET inep_code = '137618' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR WENCESLAU BRAZ' AND UPPER(TRIM(city)) = 'MONTE SANTO DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137618');

-- EE DOUTOR FARID SILVA (PRATÁPOLIS)
UPDATE schools SET inep_code = '137707' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR FARID SILVA' AND UPPER(TRIM(city)) = 'PRATÁPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137707');

-- EE CORONEL JOÃO FERREIRA BARBOSA (SÃO PEDRO DA UNIÃO)
UPDATE schools SET inep_code = '137847' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL JOÃO FERREIRA BARBOSA' AND UPPER(TRIM(city)) = 'SÃO PEDRO DA UNIÃO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137847');

-- CESEC ALDA POLASTRE (SÃO SEBASTIÃO DO PARAÍSO)
UPDATE schools SET inep_code = '138011' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC ALDA POLASTRE' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '138011');

-- EE BENEDITO FERREIRA CALAFIORI (SÃO SEBASTIÃO DO PARAÍSO)
UPDATE schools SET inep_code = '137987' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BENEDITO FERREIRA CALAFIORI' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137987');

-- EE CLÓVIS SALGADO (SÃO SEBASTIÃO DO PARAÍSO)
UPDATE schools SET inep_code = '137880' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CLÓVIS SALGADO' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137880');

-- EE COMENDADOR JOÃO ALVES DE FIGUEIREDO (SÃO SEBASTIÃO DO PARAÍSO)
UPDATE schools SET inep_code = '137936' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE COMENDADOR JOÃO ALVES DE FIGUEIREDO' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137936');

-- EE COMENDADORA ANA CÂNDIDA DE FIGUEIREDO (SÃO SEBASTIÃO DO PARAÍSO)
UPDATE schools SET inep_code = '137910' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE COMENDADORA ANA CÂNDIDA DE FIGUEIREDO' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137910');

-- EE CORONEL JOSÉ CÂNDIDO (SÃO SEBASTIÃO DO PARAÍSO)
UPDATE schools SET inep_code = '137898' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL JOSÉ CÂNDIDO' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137898');

-- EE PARAISENSE (SÃO SEBASTIÃO DO PARAÍSO)
UPDATE schools SET inep_code = '137944' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PARAISENSE' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137944');

-- EE PAULA FRASSINETTI (SÃO SEBASTIÃO DO PARAÍSO)
UPDATE schools SET inep_code = '137928' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PAULA FRASSINETTI' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137928');

-- EE PROFESSORA INÊS MIRANDA ALMEIDA (SÃO SEBASTIÃO DO PARAÍSO)
UPDATE schools SET inep_code = '212431' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA INÊS MIRANDA ALMEIDA' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '212431');

-- EE SÃO JOÃO DA ESCÓCIA (SÃO SEBASTIÃO DO PARAÍSO)
UPDATE schools SET inep_code = '137961' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO JOÃO DA ESCÓCIA' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137961');

-- EE DOUTOR TANCREDO DE ALMEIDA NEVES (SÃO TOMÁS DE AQUINO)
UPDATE schools SET inep_code = '138053' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR TANCREDO DE ALMEIDA NEVES' AND UPPER(TRIM(city)) = 'SÃO TOMÁS DE AQUINO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '138053');

-- EE PROFESSORA MARIA DA CONCEIÇÃO SILVA (ARAÇAÍ)
UPDATE schools SET inep_code = '311189' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA DA CONCEIÇÃO SILVA' AND UPPER(TRIM(city)) = 'ARAÇAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '311189');

-- EE JOSÉ RIBEIRO DA SILVA (BALDIM)
UPDATE schools SET inep_code = '140325' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ RIBEIRO DA SILVA' AND UPPER(TRIM(city)) = 'BALDIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140325');

-- EE OSCAR ARTUR GUIMARÃES (BALDIM)
UPDATE schools SET inep_code = '140376' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE OSCAR ARTUR GUIMARÃES' AND UPPER(TRIM(city)) = 'BALDIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140376');

-- EE MARIA ANÁLIA MENDES FERREIRA (CACHOEIRA DA PRATA)
UPDATE schools SET inep_code = '267805' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARIA ANÁLIA MENDES FERREIRA' AND UPPER(TRIM(city)) = 'CACHOEIRA DA PRATA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '267805');

-- EE PROFESSORA DORA SILVA (CAETANÓPOLIS)
UPDATE schools SET inep_code = '140465' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA DORA SILVA' AND UPPER(TRIM(city)) = 'CAETANÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140465');

-- EE FRANCISCO SALES (CAPIM BRANCO)
UPDATE schools SET inep_code = '140481' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE FRANCISCO SALES' AND UPPER(TRIM(city)) = 'CAPIM BRANCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140481');

-- EE MESTRE CORNÉLIO (CAPIM BRANCO)
UPDATE schools SET inep_code = '310611' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MESTRE CORNÉLIO' AND UPPER(TRIM(city)) = 'CAPIM BRANCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310611');

-- EE CLÁUDIO PINHEIRO DE LIMA (CORDISBURGO)
UPDATE schools SET inep_code = '140538' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CLÁUDIO PINHEIRO DE LIMA' AND UPPER(TRIM(city)) = 'CORDISBURGO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140538');

-- EE MESTRE CANDINHO (CORDISBURGO)
UPDATE schools SET inep_code = '140554' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MESTRE CANDINHO' AND UPPER(TRIM(city)) = 'CORDISBURGO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140554');

-- EE PROFESSOR ANÍSIO TEIXEIRA (CORDISBURGO)
UPDATE schools SET inep_code = '140589' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ANÍSIO TEIXEIRA' AND UPPER(TRIM(city)) = 'CORDISBURGO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140589');

-- EE CORONEL AMÉRICO TEIXEIRA GUIMARÃES (FORTUNA DE MINAS)
UPDATE schools SET inep_code = '141003' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL AMÉRICO TEIXEIRA GUIMARÃES' AND UPPER(TRIM(city)) = 'FORTUNA DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141003');

-- EE ALUÍSIO FERREIRA DE SOUZA (FUNILÂNDIA)
UPDATE schools SET inep_code = '141038' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALUÍSIO FERREIRA DE SOUZA' AND UPPER(TRIM(city)) = 'FUNILÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141038');

-- EE DIOLINO MOREIRA (FUNILÂNDIA)
UPDATE schools SET inep_code = '141054' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DIOLINO MOREIRA' AND UPPER(TRIM(city)) = 'FUNILÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141054');

-- EE MESSIAS ANTÔNIO GUIMARÃES (INHAÚMA)
UPDATE schools SET inep_code = '141101' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MESSIAS ANTÔNIO GUIMARÃES' AND UPPER(TRIM(city)) = 'INHAÚMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141101');

-- EE PROFESSOR VÍTOR PINTO (JEQUITIBÁ)
UPDATE schools SET inep_code = '141135' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR VÍTOR PINTO' AND UPPER(TRIM(city)) = 'JEQUITIBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141135');

-- EE BENTO GONÇALVES (MATOZINHOS)
UPDATE schools SET inep_code = '141194' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BENTO GONÇALVES' AND UPPER(TRIM(city)) = 'MATOZINHOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141194');

-- EE FELÍCIA FERNANDES CAMPOS (MATOZINHOS)
UPDATE schools SET inep_code = '141275' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE FELÍCIA FERNANDES CAMPOS' AND UPPER(TRIM(city)) = 'MATOZINHOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141275');

-- EE HERMELITA SOARES HORTA (MATOZINHOS)
UPDATE schools SET inep_code = '141259' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE HERMELITA SOARES HORTA' AND UPPER(TRIM(city)) = 'MATOZINHOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141259');

-- EE PROFESSORA VITIZA OCTAVIANO VIANA (MATOZINHOS)
UPDATE schools SET inep_code = '141186' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA VITIZA OCTAVIANO VIANA' AND UPPER(TRIM(city)) = 'MATOZINHOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141186');

-- EE VISCONDE DO RIO DAS VELHAS (MATOZINHOS)
UPDATE schools SET inep_code = '141216' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE VISCONDE DO RIO DAS VELHAS' AND UPPER(TRIM(city)) = 'MATOZINHOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141216');

-- EE AGNALDO EDMUNDO SILVA (PARAOPEBA)
UPDATE schools SET inep_code = '230995' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE AGNALDO EDMUNDO SILVA' AND UPPER(TRIM(city)) = 'PARAOPEBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '230995');

-- EE CONSELHEIRO AFONSO PENA (PARAOPEBA)
UPDATE schools SET inep_code = '141321' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CONSELHEIRO AFONSO PENA' AND UPPER(TRIM(city)) = 'PARAOPEBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141321');

-- EE PADRE AUGUSTO HORTA (PARAOPEBA)
UPDATE schools SET inep_code = '141356' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE AUGUSTO HORTA' AND UPPER(TRIM(city)) = 'PARAOPEBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141356');

-- EE DONA FRANCISCA DE OLIVEIRA (POMPÉU)
UPDATE schools SET inep_code = '141437' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DONA FRANCISCA DE OLIVEIRA' AND UPPER(TRIM(city)) = 'POMPÉU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141437');

-- EE DR JACINTO CAMPOS (POMPÉU)
UPDATE schools SET inep_code = '141445' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DR JACINTO CAMPOS' AND UPPER(TRIM(city)) = 'POMPÉU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141445');

-- EE MINISTRO FRANCISCO CAMPOS (POMPÉU)
UPDATE schools SET inep_code = '141399' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MINISTRO FRANCISCO CAMPOS' AND UPPER(TRIM(city)) = 'POMPÉU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141399');

-- EE PAULO CAMPOS GUIMARÃES (POMPÉU)
UPDATE schools SET inep_code = '231762' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PAULO CAMPOS GUIMARÃES' AND UPPER(TRIM(city)) = 'POMPÉU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '231762');

-- EE PEDRO ROBERTO DE MENEZES (POMPÉU)
UPDATE schools SET inep_code = '141470' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PEDRO ROBERTO DE MENEZES' AND UPPER(TRIM(city)) = 'POMPÉU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141470');

-- EE ANTÔNIO DELPHINO DOS SANTOS (PRUDENTE DE MORAIS)
UPDATE schools SET inep_code = '231550' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO DELPHINO DOS SANTOS' AND UPPER(TRIM(city)) = 'PRUDENTE DE MORAIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '231550');

-- EE JOÃO RODRIGUES DA SILVA (PRUDENTE DE MORAIS)
UPDATE schools SET inep_code = '141488' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO RODRIGUES DA SILVA' AND UPPER(TRIM(city)) = 'PRUDENTE DE MORAIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141488');

-- EE VIRGÍLIO DE MELO FRANCO (PRUDENTE DE MORAIS)
UPDATE schools SET inep_code = '310662' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE VIRGÍLIO DE MELO FRANCO' AND UPPER(TRIM(city)) = 'PRUDENTE DE MORAIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310662');

-- EE CORONEL DOMINGOS DINIZ COUTO (SANTANA DE PIRAPAMA)
UPDATE schools SET inep_code = '141526' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL DOMINGOS DINIZ COUTO' AND UPPER(TRIM(city)) = 'SANTANA DE PIRAPAMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141526');

-- EE JOÃO MARTINS GUIMARÃES (SANTANA DE PIRAPAMA)
UPDATE schools SET inep_code = '141585' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO MARTINS GUIMARÃES' AND UPPER(TRIM(city)) = 'SANTANA DE PIRAPAMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141585');

-- EE JUVELINO VIEIRA DE ÁVILA (SANTANA DE PIRAPAMA)
UPDATE schools SET inep_code = '141542' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JUVELINO VIEIRA DE ÁVILA' AND UPPER(TRIM(city)) = 'SANTANA DE PIRAPAMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141542');

-- COLÉGIO TIRADENTES PMMG (SETE LAGOAS)
UPDATE schools SET inep_code = '368237' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368237');

-- EE ÁPIO SÓLON CARDOSO (SETE LAGOAS)
UPDATE schools SET inep_code = '229288' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ÁPIO SÓLON CARDOSO' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '229288');

-- EE BERNARDO VALADARES DE VASCONCELLOS (SETE LAGOAS)
UPDATE schools SET inep_code = '141925' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BERNARDO VALADARES DE VASCONCELLOS' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141925');

-- EE DE ENSINO  MÉDIO (SETE LAGOAS)
UPDATE schools SET inep_code = '372110' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO  MÉDIO' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '372110');

-- EE DEPUTADO RENATO AZEREDO (SETE LAGOAS)
UPDATE schools SET inep_code = '141801' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DEPUTADO RENATO AZEREDO' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141801');

-- EE DOUTOR AFONSO VIANA (SETE LAGOAS)
UPDATE schools SET inep_code = '141593' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR AFONSO VIANA' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141593');

-- EE DOUTOR ALONSO MARQUES FERREIRA (SETE LAGOAS)
UPDATE schools SET inep_code = '141887' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR ALONSO MARQUES FERREIRA' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141887');

-- EE DOUTOR ARTHUR BERNARDES (SETE LAGOAS)
UPDATE schools SET inep_code = '141631' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR ARTHUR BERNARDES' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141631');

-- EE DOUTOR AVELAR (SETE LAGOAS)
UPDATE schools SET inep_code = '141674' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR AVELAR' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141674');

-- EE DOUTOR OLINTO SÁTYRO ALVIM (SETE LAGOAS)
UPDATE schools SET inep_code = '141704' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR OLINTO SÁTYRO ALVIM' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141704');

-- EE EDITE FURST (SETE LAGOAS)
UPDATE schools SET inep_code = '141640' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE EDITE FURST' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141640');

-- EE EMÍLIO DE VASCONCELOS COSTA (SETE LAGOAS)
UPDATE schools SET inep_code = '141682' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE EMÍLIO DE VASCONCELOS COSTA' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141682');

-- EE EPONINA SOARES DOS SANTOS (SETE LAGOAS)
UPDATE schools SET inep_code = '141658' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE EPONINA SOARES DOS SANTOS' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141658');

-- EE GOVERNADOR JUSCELINO (SETE LAGOAS)
UPDATE schools SET inep_code = '310689' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GOVERNADOR JUSCELINO' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310689');

-- EE JOSÉ EVANGELISTA FRANÇA (SETE LAGOAS)
UPDATE schools SET inep_code = '141763' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ EVANGELISTA FRANÇA' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141763');

-- EE JÚLIO CÉSAR REIS OLIVEIRA (SETE LAGOAS)
UPDATE schools SET inep_code = '213675' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JÚLIO CÉSAR REIS OLIVEIRA' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '213675');

-- EE MAURILO DE JESUS PEIXOTO (SETE LAGOAS)
UPDATE schools SET inep_code = '141798' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MAURILO DE JESUS PEIXOTO' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141798');

-- EE MAURO FACCIO GONÇALVES (SETE LAGOAS)
UPDATE schools SET inep_code = '353469' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MAURO FACCIO GONÇALVES' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '353469');

-- EE MODESTINO ANDRADE SOBRINHO (SETE LAGOAS)
UPDATE schools SET inep_code = '141810' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MODESTINO ANDRADE SOBRINHO' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141810');

-- EE PREFEITO ZICO PAIVA (SETE LAGOAS)
UPDATE schools SET inep_code = '218944' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PREFEITO ZICO PAIVA' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218944');

-- EE PROFESSOR CÂNDIDO AZEREDO (SETE LAGOAS)
UPDATE schools SET inep_code = '141844' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR CÂNDIDO AZEREDO' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141844');

-- EE PROFESSOR JOÃO FERNANDINO JÚNIOR (SETE LAGOAS)
UPDATE schools SET inep_code = '141852' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOÃO FERNANDINO JÚNIOR' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141852');

-- EE PROFESSOR ROUSSET (SETE LAGOAS)
UPDATE schools SET inep_code = '141861' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ROUSSET' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141861');

-- EE PROFESSORA ELZA MOREIRA LOPES (SETE LAGOAS)
UPDATE schools SET inep_code = '141933' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ELZA MOREIRA LOPES' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141933');

-- EE RUTH BRANDÃO DE AZEREDO (SETE LAGOAS)
UPDATE schools SET inep_code = '349305' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE RUTH BRANDÃO DE AZEREDO' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349305');

-- EE SINHÁ ANDRADE (SETE LAGOAS)
UPDATE schools SET inep_code = '141895' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SINHÁ ANDRADE' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141895');

-- EE VENCESLAU BRÁS (SETE LAGOAS)
UPDATE schools SET inep_code = '342572' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE VENCESLAU BRÁS' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342572');

-- EE CAPITÃO INÁCIO SOARES (ÁGUAS FORMOSAS)
UPDATE schools SET inep_code = '145912' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CAPITÃO INÁCIO SOARES' AND UPPER(TRIM(city)) = 'ÁGUAS FORMOSAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '145912');

-- EE DE ÁGUA QUENTE (ÁGUAS FORMOSAS)
UPDATE schools SET inep_code = '145947' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ÁGUA QUENTE' AND UPPER(TRIM(city)) = 'ÁGUAS FORMOSAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '145947');

-- EE JOSÉ QUARESMA DA COSTA (ÁGUAS FORMOSAS)
UPDATE schools SET inep_code = '145955' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ QUARESMA DA COSTA' AND UPPER(TRIM(city)) = 'ÁGUAS FORMOSAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '145955');

-- EE DANIEL PEREIRA OTTONI (ATALÉIA)
UPDATE schools SET inep_code = '338818' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DANIEL PEREIRA OTTONI' AND UPPER(TRIM(city)) = 'ATALÉIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338818');

-- EE DE NOVO HORIZONTE (ATALÉIA)
UPDATE schools SET inep_code = '146412' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE NOVO HORIZONTE' AND UPPER(TRIM(city)) = 'ATALÉIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146412');

-- EE DE SÃO MIGUEL (ATALÉIA)
UPDATE schools SET inep_code = '146391' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE SÃO MIGUEL' AND UPPER(TRIM(city)) = 'ATALÉIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146391');

-- EE PREFEITO CLEMENTE ESTEVES FERRAZ (ATALÉIA)
UPDATE schools SET inep_code = '146285' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PREFEITO CLEMENTE ESTEVES FERRAZ' AND UPPER(TRIM(city)) = 'ATALÉIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146285');

-- EE PROFESSORA ALNEDA DE MATOS MACHADO (ATALÉIA)
UPDATE schools SET inep_code = '146331' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ALNEDA DE MATOS MACHADO' AND UPPER(TRIM(city)) = 'ATALÉIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146331');

-- EE PROFESSORA HERMÍNIA P DE ALMEIDA (ATALÉIA)
UPDATE schools SET inep_code = '146323' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA HERMÍNIA P DE ALMEIDA' AND UPPER(TRIM(city)) = 'ATALÉIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146323');

-- EE DE BERTÓPOLIS (BERTÓPOLIS)
UPDATE schools SET inep_code = '146421' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE BERTÓPOLIS' AND UPPER(TRIM(city)) = 'BERTÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146421');

-- EE DE UMBURANINHA (BERTÓPOLIS)
UPDATE schools SET inep_code = '146439' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE UMBURANINHA' AND UPPER(TRIM(city)) = 'BERTÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146439');

-- EE INDÍGENA CAPITÃOZINHO MAXAKALI (BERTÓPOLIS)
UPDATE schools SET inep_code = '269867' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE INDÍGENA CAPITÃOZINHO MAXAKALI' AND UPPER(TRIM(city)) = 'BERTÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '269867');

-- EE ANTÔNIO DUARTE SOBRINHO (CAMPANÁRIO)
UPDATE schools SET inep_code = '146471' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO DUARTE SOBRINHO' AND UPPER(TRIM(city)) = 'CAMPANÁRIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146471');

-- EE DE CARAÍ (CARAÍ)
UPDATE schools SET inep_code = '146510' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE CARAÍ' AND UPPER(TRIM(city)) = 'CARAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146510');

-- EE DE ENSINO MÉDIO (CARAÍ)
UPDATE schools SET inep_code = '372072' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' AND UPPER(TRIM(city)) = 'CARAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '372072');

-- EE DOM JOSÉ DE HAAS (CARAÍ)
UPDATE schools SET inep_code = '146536' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOM JOSÉ DE HAAS' AND UPPER(TRIM(city)) = 'CARAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146536');

-- EE ORLANDO TAVARES (CARAÍ)
UPDATE schools SET inep_code = '146544' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ORLANDO TAVARES' AND UPPER(TRIM(city)) = 'CARAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146544');

-- EE DOUTOR JOÃO BERALDO (CARLOS CHAGAS)
UPDATE schools SET inep_code = '146579' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR JOÃO BERALDO' AND UPPER(TRIM(city)) = 'CARLOS CHAGAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146579');

-- EE EPAMINONDAS OTONI (CARLOS CHAGAS)
UPDATE schools SET inep_code = '146625' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE EPAMINONDAS OTONI' AND UPPER(TRIM(city)) = 'CARLOS CHAGAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146625');

-- EE GERALDO DE SOUZA NORTE (CARLOS CHAGAS)
UPDATE schools SET inep_code = '146561' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GERALDO DE SOUZA NORTE' AND UPPER(TRIM(city)) = 'CARLOS CHAGAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146561');

-- EE OLGA PRATES (CARLOS CHAGAS)
UPDATE schools SET inep_code = '146633' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE OLGA PRATES' AND UPPER(TRIM(city)) = 'CARLOS CHAGAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146633');

-- EE PROFESSORA ANTÔNIA BERNARDO RODRIGUES (CARLOS CHAGAS)
UPDATE schools SET inep_code = '346179' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ANTÔNIA BERNARDO RODRIGUES' AND UPPER(TRIM(city)) = 'CARLOS CHAGAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346179');

-- EE DOUTOR CIRO MACIEL (CATUJI)
UPDATE schools SET inep_code = '146749' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR CIRO MACIEL' AND UPPER(TRIM(city)) = 'CATUJI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146749');

-- EE GEORGINA FERREIRA BATISTA (CATUJI)
UPDATE schools SET inep_code = '330591' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GEORGINA FERREIRA BATISTA' AND UPPER(TRIM(city)) = 'CATUJI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '330591');

-- EE RAUL FERREIRA SOUTO (CRISÓLITA)
UPDATE schools SET inep_code = '145980' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE RAUL FERREIRA SOUTO' AND UPPER(TRIM(city)) = 'CRISÓLITA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '145980');

-- EE DE ANTÔNIO FERREIRA (FRANCISCÓPOLIS)
UPDATE schools SET inep_code = '147222' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ANTÔNIO FERREIRA' AND UPPER(TRIM(city)) = 'FRANCISCÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147222');

-- EE MARIA DA SILVA ROCHA (FRANCISCÓPOLIS)
UPDATE schools SET inep_code = '147249' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARIA DA SILVA ROCHA' AND UPPER(TRIM(city)) = 'FRANCISCÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147249');

-- EE SALMEN BUKZEM (FREI GASPAR)
UPDATE schools SET inep_code = '146706' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SALMEN BUKZEM' AND UPPER(TRIM(city)) = 'FREI GASPAR' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146706');

-- EE DE PAMPÃ (FRONTEIRA DOS VALES)
UPDATE schools SET inep_code = '146714' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE PAMPÃ' AND UPPER(TRIM(city)) = 'FRONTEIRA DOS VALES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146714');

-- EE CORONEL CLEMENTE LUIZ (ITAIPÉ)
UPDATE schools SET inep_code = '146731' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL CLEMENTE LUIZ' AND UPPER(TRIM(city)) = 'ITAIPÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146731');

-- EE PROFESSORA FRANCISCA MATOS (ITAIPÉ)
UPDATE schools SET inep_code = '319082' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA FRANCISCA MATOS' AND UPPER(TRIM(city)) = 'ITAIPÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '319082');

-- EE DOUTOR TRISTÃO DA CUNHA (ITAMBACURI)
UPDATE schools SET inep_code = '146757' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR TRISTÃO DA CUNHA' AND UPPER(TRIM(city)) = 'ITAMBACURI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146757');

-- EE MADRE SERAFINA DE JESUS (ITAMBACURI)
UPDATE schools SET inep_code = '146820' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MADRE SERAFINA DE JESUS' AND UPPER(TRIM(city)) = 'ITAMBACURI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146820');

-- EE RAMIRO SOUZA E SILVA (ITAMBACURI)
UPDATE schools SET inep_code = '146871' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE RAMIRO SOUZA E SILVA' AND UPPER(TRIM(city)) = 'ITAMBACURI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146871');

-- EE VEREADOR JÚLIO LAGES (ITAMBACURI)
UPDATE schools SET inep_code = '146862' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE VEREADOR JÚLIO LAGES' AND UPPER(TRIM(city)) = 'ITAMBACURI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146862');

-- EE CASSIMIRO DE ABREU (JAMPRUCA)
UPDATE schools SET inep_code = '146501' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CASSIMIRO DE ABREU' AND UPPER(TRIM(city)) = 'JAMPRUCA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146501');

-- EE CORONEL ANTÔNIO LOPES (JAMPRUCA)
UPDATE schools SET inep_code = '146480' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL ANTÔNIO LOPES' AND UPPER(TRIM(city)) = 'JAMPRUCA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146480');

-- EE DE ENSINO FUNDAMENTAL (JAMPRUCA)
UPDATE schools SET inep_code = '369870' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL' AND UPPER(TRIM(city)) = 'JAMPRUCA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369870');

-- EE DE CONCÓRDIA DO MUCURI (LADAINHA)
UPDATE schools SET inep_code = '147109' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE CONCÓRDIA DO MUCURI' AND UPPER(TRIM(city)) = 'LADAINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147109');

-- EE DE LADAINHA (LADAINHA)
UPDATE schools SET inep_code = '147052' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE LADAINHA' AND UPPER(TRIM(city)) = 'LADAINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147052');

-- EE INDÍGENA IZABEL DA SILVA MAXAKALI (LADAINHA)
UPDATE schools SET inep_code = '338826' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE INDÍGENA IZABEL DA SILVA MAXAKALI' AND UPPER(TRIM(city)) = 'LADAINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338826');

-- EE NOSSA SENHORA DO ROSÁRIO (LADAINHA)
UPDATE schools SET inep_code = '147095' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DO ROSÁRIO' AND UPPER(TRIM(city)) = 'LADAINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147095');

-- EE ANTÔNIO DIAS DOS SANTOS (MACHACALIS)
UPDATE schools SET inep_code = '253839' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO DIAS DOS SANTOS' AND UPPER(TRIM(city)) = 'MACHACALIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253839');

-- EE JOSÉ DE ALENCAR (MACHACALIS)
UPDATE schools SET inep_code = '147133' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ DE ALENCAR' AND UPPER(TRIM(city)) = 'MACHACALIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147133');

-- EE DE JAGUARITIRA (MALACACHETA)
UPDATE schools SET inep_code = '147281' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE JAGUARITIRA' AND UPPER(TRIM(city)) = 'MALACACHETA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147281');

-- EE DE SANTO ANTÔNIO DO MUCURI (MALACACHETA)
UPDATE schools SET inep_code = '147311' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE SANTO ANTÔNIO DO MUCURI' AND UPPER(TRIM(city)) = 'MALACACHETA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147311');

-- EE GERALDO DOS SANTOS COIMBRA (MALACACHETA)
UPDATE schools SET inep_code = '147290' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GERALDO DOS SANTOS COIMBRA' AND UPPER(TRIM(city)) = 'MALACACHETA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147290');

-- EE MESTRA ZULMIRA (MALACACHETA)
UPDATE schools SET inep_code = '147206' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MESTRA ZULMIRA' AND UPPER(TRIM(city)) = 'MALACACHETA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147206');

-- EE MONSENHOR CLÓVIS VIEIRA DA FONSECA (MALACACHETA)
UPDATE schools SET inep_code = '147141' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MONSENHOR CLÓVIS VIEIRA DA FONSECA' AND UPPER(TRIM(city)) = 'MALACACHETA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147141');

-- EE STELLA ABRANTES (MALACACHETA)
UPDATE schools SET inep_code = '147192' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE STELLA ABRANTES' AND UPPER(TRIM(city)) = 'MALACACHETA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147192');

-- EE ÁLVARO ROMANO (NANUQUE)
UPDATE schools SET inep_code = '147419' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ÁLVARO ROMANO' AND UPPER(TRIM(city)) = 'NANUQUE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147419');

-- EE ANTÔNIO BATISTA DA MOTA (NANUQUE)
UPDATE schools SET inep_code = '147451' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO BATISTA DA MOTA' AND UPPER(TRIM(city)) = 'NANUQUE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147451');

-- EE JOSEPH STALIM ROMANO (NANUQUE)
UPDATE schools SET inep_code = '147486' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSEPH STALIM ROMANO' AND UPPER(TRIM(city)) = 'NANUQUE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147486');

-- EE PASTOR PAULO NOBRE NASCIMENTO (NANUQUE)
UPDATE schools SET inep_code = '147494' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PASTOR PAULO NOBRE NASCIMENTO' AND UPPER(TRIM(city)) = 'NANUQUE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147494');

-- EE PÉRICLES COELHO (NANUQUE)
UPDATE schools SET inep_code = '147508' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PÉRICLES COELHO' AND UPPER(TRIM(city)) = 'NANUQUE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147508');

-- EE STELLA MATUTINA (NANUQUE)
UPDATE schools SET inep_code = '147460' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE STELLA MATUTINA' AND UPPER(TRIM(city)) = 'NANUQUE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147460');

-- EE VALE DO MUCURI (NANUQUE)
UPDATE schools SET inep_code = '147389' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE VALE DO MUCURI' AND UPPER(TRIM(city)) = 'NANUQUE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147389');

-- EE ANTÔNIO RAMOS DE SOUZA (NOVO CRUZEIRO)
UPDATE schools SET inep_code = '147575' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO RAMOS DE SOUZA' AND UPPER(TRIM(city)) = 'NOVO CRUZEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147575');

-- EE AUGUSTO SOARES (NOVO CRUZEIRO)
UPDATE schools SET inep_code = '326119' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE AUGUSTO SOARES' AND UPPER(TRIM(city)) = 'NOVO CRUZEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '326119');

-- EE DA FAZENDA ARUEGA (NOVO CRUZEIRO)
UPDATE schools SET inep_code = '218430' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DA FAZENDA ARUEGA' AND UPPER(TRIM(city)) = 'NOVO CRUZEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218430');

-- EE DE LAMBARI (NOVO CRUZEIRO)
UPDATE schools SET inep_code = '147583' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE LAMBARI' AND UPPER(TRIM(city)) = 'NOVO CRUZEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147583');

-- EE DE SANTA BÁRBARA (NOVO CRUZEIRO)
UPDATE schools SET inep_code = '147648' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE SANTA BÁRBARA' AND UPPER(TRIM(city)) = 'NOVO CRUZEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147648');

-- EE DO LUFA (NOVO CRUZEIRO)
UPDATE schools SET inep_code = '147621' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DO LUFA' AND UPPER(TRIM(city)) = 'NOVO CRUZEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147621');

-- EE EDUARDO MILTON DA SILVA (NOVO CRUZEIRO)
UPDATE schools SET inep_code = '147541' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE EDUARDO MILTON DA SILVA' AND UPPER(TRIM(city)) = 'NOVO CRUZEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147541');

-- EE INÁCIO MURTA (NOVO CRUZEIRO)
UPDATE schools SET inep_code = '147567' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE INÁCIO MURTA' AND UPPER(TRIM(city)) = 'NOVO CRUZEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147567');

-- EE JOSÉ MENDES BARBOSA (NOVO CRUZEIRO)
UPDATE schools SET inep_code = '147656' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ MENDES BARBOSA' AND UPPER(TRIM(city)) = 'NOVO CRUZEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147656');

-- EE MARIA CÂNDIDA REIS (NOVO CRUZEIRO)
UPDATE schools SET inep_code = '147664' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARIA CÂNDIDA REIS' AND UPPER(TRIM(city)) = 'NOVO CRUZEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147664');

-- EE SUL AMÉRICA (NOVO CRUZEIRO)
UPDATE schools SET inep_code = '147613' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SUL AMÉRICA' AND UPPER(TRIM(city)) = 'NOVO CRUZEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147613');

-- EE ADOLFO TEIXEIRA DE SOUZA (NOVO ORIENTE DE MINAS)
UPDATE schools SET inep_code = '346144' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ADOLFO TEIXEIRA DE SOUZA' AND UPPER(TRIM(city)) = 'NOVO ORIENTE DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346144');

-- EE DE FREI GONZAGA (NOVO ORIENTE DE MINAS)
UPDATE schools SET inep_code = '148393' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE FREI GONZAGA' AND UPPER(TRIM(city)) = 'NOVO ORIENTE DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148393');

-- EE PAULO PINHEIRO CHAGAS (NOVO ORIENTE DE MINAS)
UPDATE schools SET inep_code = '148385' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PAULO PINHEIRO CHAGAS' AND UPPER(TRIM(city)) = 'NOVO ORIENTE DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148385');

-- EE ELISA LEAL (OURO VERDE DE MINAS)
UPDATE schools SET inep_code = '254487' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ELISA LEAL' AND UPPER(TRIM(city)) = 'OURO VERDE DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '254487');

-- EE VEREADOR LUZO FREITAS DE ARAÚJO (OURO VERDE DE MINAS)
UPDATE schools SET inep_code = '147672' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE VEREADOR LUZO FREITAS DE ARAÚJO' AND UPPER(TRIM(city)) = 'OURO VERDE DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147672');

-- EE DE ENSINO MÉDIO (PADRE PARAÍSO)
UPDATE schools SET inep_code = '330574' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' AND UPPER(TRIM(city)) = 'PADRE PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '330574');

-- EE DOUTOR CÂNDIDO ULHOA (PADRE PARAÍSO)
UPDATE schools SET inep_code = '147699' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR CÂNDIDO ULHOA' AND UPPER(TRIM(city)) = 'PADRE PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147699');

-- EE PRESIDENTE JOÃO PINHEIRO (PADRE PARAÍSO)
UPDATE schools SET inep_code = '147702' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE JOÃO PINHEIRO' AND UPPER(TRIM(city)) = 'PADRE PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147702');

-- EE PROFESSOR JOSÉ MONTEIRO FONSECA (PADRE PARAÍSO)
UPDATE schools SET inep_code = '147711' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOSÉ MONTEIRO FONSECA' AND UPPER(TRIM(city)) = 'PADRE PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147711');

-- EE CAIO NÉLSON DE SENA (PAVÃO)
UPDATE schools SET inep_code = '147737' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CAIO NÉLSON DE SENA' AND UPPER(TRIM(city)) = 'PAVÃO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147737');

-- EE DO POVOADO DE LIMEIRA (PAVÃO)
UPDATE schools SET inep_code = '147753' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DO POVOADO DE LIMEIRA' AND UPPER(TRIM(city)) = 'PAVÃO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147753');

-- EE DOUTOR TRISTÃO DA CUNHA (PESCADOR)
UPDATE schools SET inep_code = '147788' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR TRISTÃO DA CUNHA' AND UPPER(TRIM(city)) = 'PESCADOR' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147788');

-- EE ALONZO BARBUDA (PONTO DOS VOLANTES)
UPDATE schools SET inep_code = '147010' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALONZO BARBUDA' AND UPPER(TRIM(city)) = 'PONTO DOS VOLANTES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147010');

-- EE DE ENSINO MÉDIO (PONTO DOS VOLANTES)
UPDATE schools SET inep_code = '372080' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' AND UPPER(TRIM(city)) = 'PONTO DOS VOLANTES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '372080');

-- EE SANTANA DO ARAÇUAÍ (PONTO DOS VOLANTES)
UPDATE schools SET inep_code = '147028' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SANTANA DO ARAÇUAÍ' AND UPPER(TRIM(city)) = 'PONTO DOS VOLANTES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147028');

-- EE CLÁUDIO MANOEL (POTÉ)
UPDATE schools SET inep_code = '147796' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CLÁUDIO MANOEL' AND UPPER(TRIM(city)) = 'POTÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147796');

-- EE JOÃO FERREIRA DE OLIVEIRA (POTÉ)
UPDATE schools SET inep_code = '147818' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO FERREIRA DE OLIVEIRA' AND UPPER(TRIM(city)) = 'POTÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147818');

-- EE JOSÉ ARAUJO FONSECA (POTÉ)
UPDATE schools SET inep_code = '147834' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ ARAUJO FONSECA' AND UPPER(TRIM(city)) = 'POTÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147834');

-- EE RIBEIRÃO DE SANTA CRUZ (POTÉ)
UPDATE schools SET inep_code = '147826' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE RIBEIRÃO DE SANTA CRUZ' AND UPPER(TRIM(city)) = 'POTÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147826');

-- EE VEREADOR SEBASTIÃO MAGALHÃES (POTÉ)
UPDATE schools SET inep_code = '147869' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE VEREADOR SEBASTIÃO MAGALHÃES' AND UPPER(TRIM(city)) = 'POTÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147869');

-- EE INDÍGENA MAXAKALI (SANTA HELENA DE MINAS)
UPDATE schools SET inep_code = '269859' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE INDÍGENA MAXAKALI' AND UPPER(TRIM(city)) = 'SANTA HELENA DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '269859');

-- EE RAUL RODRIGUES SALOMÃO (SANTA HELENA DE MINAS)
UPDATE schools SET inep_code = '146447' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE RAUL RODRIGUES SALOMÃO' AND UPPER(TRIM(city)) = 'SANTA HELENA DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146447');

-- EE PEDRO GONZAGA (SERRA DOS AIMORÉS)
UPDATE schools SET inep_code = '147923' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PEDRO GONZAGA' AND UPPER(TRIM(city)) = 'SERRA DOS AIMORÉS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147923');

-- EE VANDA REUTER (SERRA DOS AIMORÉS)
UPDATE schools SET inep_code = '147931' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE VANDA REUTER' AND UPPER(TRIM(city)) = 'SERRA DOS AIMORÉS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147931');

-- EE DE SETÚBAL (SETUBINHA)
UPDATE schools SET inep_code = '147354' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE SETÚBAL' AND UPPER(TRIM(city)) = 'SETUBINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147354');

-- EE GENTIL BARBOSA SENA (SETUBINHA)
UPDATE schools SET inep_code = '147320' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GENTIL BARBOSA SENA' AND UPPER(TRIM(city)) = 'SETUBINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147320');

-- EE MADALENA PEREIRA JORGE (SETUBINHA)
UPDATE schools SET inep_code = '326101' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MADALENA PEREIRA JORGE' AND UPPER(TRIM(city)) = 'SETUBINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '326101');

-- EE NAGIB MAHMUD NÉDIR (SETUBINHA)
UPDATE schools SET inep_code = '147362' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NAGIB MAHMUD NÉDIR' AND UPPER(TRIM(city)) = 'SETUBINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147362');

-- EE PROFESSORA LEONOR ESTEVES LIMA (SETUBINHA)
UPDATE schools SET inep_code = '147338' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA LEONOR ESTEVES LIMA' AND UPPER(TRIM(city)) = 'SETUBINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147338');

-- EE SOTURNO DA MATA (SETUBINHA)
UPDATE schools SET inep_code = '240818' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SOTURNO DA MATA' AND UPPER(TRIM(city)) = 'SETUBINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '240818');

-- CEP - CENTRO DE EDUCAÇÃO PROFISSIONAL PAULO VIANA (TEÓFILO OTONI)
UPDATE schools SET inep_code = '298913' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CEP - CENTRO DE EDUCAÇÃO PROFISSIONAL PAULO VIANA' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '298913');

-- CESEC  DE TEÓFILO OTONI (TEÓFILO OTONI)
UPDATE schools SET inep_code = '148199' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC  DE TEÓFILO OTONI' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148199');

-- COLÉGIO TIRADENTES PMMG (TEÓFILO OTONI)
UPDATE schools SET inep_code = '281204' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '281204');

-- EE ALBERTO BARREIROS (TEÓFILO OTONI)
UPDATE schools SET inep_code = '147940' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALBERTO BARREIROS' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147940');

-- EE ALFREDO SÁ (TEÓFILO OTONI)
UPDATE schools SET inep_code = '147966' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALFREDO SÁ' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147966');

-- EE ALTINO BARBOSA (TEÓFILO OTONI)
UPDATE schools SET inep_code = '147982' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALTINO BARBOSA' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147982');

-- EE CLOTILDE ONOFRI DE CAMPOS (TEÓFILO OTONI)
UPDATE schools SET inep_code = '148059' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CLOTILDE ONOFRI DE CAMPOS' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148059');

-- EE DA CABECEIRA DE SÃO PEDRO (TEÓFILO OTONI)
UPDATE schools SET inep_code = '148164' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DA CABECEIRA DE SÃO PEDRO' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148164');

-- EE DE BARRA DO CEDRO (TEÓFILO OTONI)
UPDATE schools SET inep_code = '148121' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE BARRA DO CEDRO' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148121');

-- EE DE ENSINO FUNDAMENTAL E MÉDIO (TEÓFILO OTONI)
UPDATE schools SET inep_code = '326828' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL E MÉDIO' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '326828');

-- EE DE LIBERDADE (TEÓFILO OTONI)
UPDATE schools SET inep_code = '148229' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE LIBERDADE' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148229');

-- EE DE MUCURI (TEÓFILO OTONI)
UPDATE schools SET inep_code = '148431' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE MUCURI' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148431');

-- EE DE PEDRO VERSIANI (TEÓFILO OTONI)
UPDATE schools SET inep_code = '148407' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE PEDRO VERSIANI' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148407');

-- EE DEPUTADO GERALDO LANDI (TEÓFILO OTONI)
UPDATE schools SET inep_code = '148288' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DEPUTADO GERALDO LANDI' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148288');

-- EE DOUTOR MANOEL ESTEVES OTONI (TEÓFILO OTONI)
UPDATE schools SET inep_code = '148334' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR MANOEL ESTEVES OTONI' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148334');

-- EE DOUTOR WALDEMAR NEVES DA ROCHA (TEÓFILO OTONI)
UPDATE schools SET inep_code = '148113' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR WALDEMAR NEVES DA ROCHA' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148113');

-- EE GLÓRIA PENCHEL (TEÓFILO OTONI)
UPDATE schools SET inep_code = '148041' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GLÓRIA PENCHEL' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148041');

-- EE IONE LEWICK CUNHA MELO (TEÓFILO OTONI)
UPDATE schools SET inep_code = '148075' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE IONE LEWICK CUNHA MELO' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148075');

-- EE IRMÃ ARCÂNGELA (TEÓFILO OTONI)
UPDATE schools SET inep_code = '148130' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE IRMÃ ARCÂNGELA' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148130');

-- EE JOSÉ EXPEDITO SOUZA CAMPOS (TEÓFILO OTONI)
UPDATE schools SET inep_code = '148440' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ EXPEDITO SOUZA CAMPOS' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148440');