-- EE MAGID LAUAR (TEÓFILO OTONI)
UPDATE schools SET inep_code = '148261' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MAGID LAUAR' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148261');

-- EE NOSSA SENHORA DE FÁTIMA (TEÓFILO OTONI)
UPDATE schools SET inep_code = '148342' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DE FÁTIMA' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148342');

-- EE PASTOR HOLLERBACH (TEÓFILO OTONI)
UPDATE schools SET inep_code = '148024' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PASTOR HOLLERBACH' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148024');

-- EE PRESIDENTE TANCREDO NEVES (TEÓFILO OTONI)
UPDATE schools SET inep_code = '148351' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE TANCREDO NEVES' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148351');

-- EE PROFESSOR PATRÍCIO FERREIRA GOMES (TEÓFILO OTONI)
UPDATE schools SET inep_code = '147958' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR PATRÍCIO FERREIRA GOMES' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147958');

-- EE PROFESSORA MARIA LÚCIA GOMES RIBEIRO (TEÓFILO OTONI)
UPDATE schools SET inep_code = '338834' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA LÚCIA GOMES RIBEIRO' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338834');

-- EE SÃO SEBASTIÃO (TEÓFILO OTONI)
UPDATE schools SET inep_code = '148016' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO SEBASTIÃO' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148016');

-- EE SEBASTIÃO ALVES DA CRUZ (TEÓFILO OTONI)
UPDATE schools SET inep_code = '349330' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SEBASTIÃO ALVES DA CRUZ' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349330');

-- EE SEBASTIÃO RAMOS (TEÓFILO OTONI)
UPDATE schools SET inep_code = '148032' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SEBASTIÃO RAMOS' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148032');

-- EE TRISTÃO DA CUNHA (TEÓFILO OTONI)
UPDATE schools SET inep_code = '148091' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE TRISTÃO DA CUNHA' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148091');

-- EE APARÍCIO ALVES MURTA (UMBURATIBA)
UPDATE schools SET inep_code = '148458' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE APARÍCIO ALVES MURTA' AND UPPER(TRIM(city)) = 'UMBURATIBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148458');

-- EE DEPUTADO EDSON RESENDE (ASTOLFO DUTRA)
UPDATE schools SET inep_code = '180769' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DEPUTADO EDSON RESENDE' AND UPPER(TRIM(city)) = 'ASTOLFO DUTRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180769');

-- EE OLINTO ALMADA (ASTOLFO DUTRA)
UPDATE schools SET inep_code = '180751' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE OLINTO ALMADA' AND UPPER(TRIM(city)) = 'ASTOLFO DUTRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180751');

-- EE PROFESSOR SOUZA PRIMO (ASTOLFO DUTRA)
UPDATE schools SET inep_code = '180742' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR SOUZA PRIMO' AND UPPER(TRIM(city)) = 'ASTOLFO DUTRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180742');

-- EE JOSÉ ALVES DE MAGALHÃES (BRÁS PIRES)
UPDATE schools SET inep_code = '180785' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ ALVES DE MAGALHÃES' AND UPPER(TRIM(city)) = 'BRÁS PIRES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180785');

-- EE SÃO LUÍS (BRÁS PIRES)
UPDATE schools SET inep_code = '180793' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO LUÍS' AND UPPER(TRIM(city)) = 'BRÁS PIRES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180793');

-- EE EMÍLIO JARDIM (COIMBRA)
UPDATE schools SET inep_code = '128635' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE EMÍLIO JARDIM' AND UPPER(TRIM(city)) = 'COIMBRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128635');

-- EE PROFESSOR BIOLKINO DE ANDRADE (DIVINÉSIA)
UPDATE schools SET inep_code = '180807' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR BIOLKINO DE ANDRADE' AND UPPER(TRIM(city)) = 'DIVINÉSIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180807');

-- EE CORINA VIEIRA HENRIQUES (DONA EUSÉBIA)
UPDATE schools SET inep_code = '180831' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORINA VIEIRA HENRIQUES' AND UPPER(TRIM(city)) = 'DONA EUSÉBIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180831');

-- EE DOMICIANO ESTEVES (DONA EUSÉBIA)
UPDATE schools SET inep_code = '180815' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOMICIANO ESTEVES' AND UPPER(TRIM(city)) = 'DONA EUSÉBIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180815');

-- EE TEREZINHA PEREIRA (DORES DO TURVO)
UPDATE schools SET inep_code = '180858' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE TEREZINHA PEREIRA' AND UPPER(TRIM(city)) = 'DORES DO TURVO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180858');

-- EE DOM FRANCISCO DAS CHAGAS (ERVÁLIA)
UPDATE schools SET inep_code = '180904' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOM FRANCISCO DAS CHAGAS' AND UPPER(TRIM(city)) = 'ERVÁLIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180904');

-- EE MONSENHOR RODOLFO (ERVÁLIA)
UPDATE schools SET inep_code = '180912' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MONSENHOR RODOLFO' AND UPPER(TRIM(city)) = 'ERVÁLIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180912');

-- EE PROFESSOR DAVID PROCÓPIO (ERVÁLIA)
UPDATE schools SET inep_code = '180891' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR DAVID PROCÓPIO' AND UPPER(TRIM(city)) = 'ERVÁLIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180891');

-- EE JOSÉ ALVAREZ FILHO (GUARANI)
UPDATE schools SET inep_code = '215384' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ ALVAREZ FILHO' AND UPPER(TRIM(city)) = 'GUARANI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '215384');

-- EE PROFESSOR ALBERTO PACHECO (GUARANI)
UPDATE schools SET inep_code = '181030' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ALBERTO PACHECO' AND UPPER(TRIM(city)) = 'GUARANI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181030');

-- EE CORONEL JOAQUIM MARTINS (GUIDOVAL)
UPDATE schools SET inep_code = '181102' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL JOAQUIM MARTINS' AND UPPER(TRIM(city)) = 'GUIDOVAL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181102');

-- EE MARIANA DE PAIVA (GUIDOVAL)
UPDATE schools SET inep_code = '181137' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARIANA DE PAIVA' AND UPPER(TRIM(city)) = 'GUIDOVAL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181137');

-- EE CASTORINA GOMES SOARES (GUIRICEMA)
UPDATE schools SET inep_code = '181200' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CASTORINA GOMES SOARES' AND UPPER(TRIM(city)) = 'GUIRICEMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181200');

-- EE GALDINO LEOCÁDIO (GUIRICEMA)
UPDATE schools SET inep_code = '181234' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GALDINO LEOCÁDIO' AND UPPER(TRIM(city)) = 'GUIRICEMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181234');

-- EE PREFEITO ANTÔNIO ARRUDA (GUIRICEMA)
UPDATE schools SET inep_code = '181188' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PREFEITO ANTÔNIO ARRUDA' AND UPPER(TRIM(city)) = 'GUIRICEMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181188');

-- EE JOSÉ MAURÍLIO VALENTE (PAULA CÂNDIDO)
UPDATE schools SET inep_code = '181251' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ MAURÍLIO VALENTE' AND UPPER(TRIM(city)) = 'PAULA CÂNDIDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181251');

-- EE PROFESSOR SAMUEL JOÃO DE DEUS (PAULA CÂNDIDO)
UPDATE schools SET inep_code = '181277' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR SAMUEL JOÃO DE DEUS' AND UPPER(TRIM(city)) = 'PAULA CÂNDIDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181277');

-- EE AURÉLIO BENTO SALGADO (PIRAÚBA)
UPDATE schools SET inep_code = '181307' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE AURÉLIO BENTO SALGADO' AND UPPER(TRIM(city)) = 'PIRAÚBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181307');

-- EE LAFAYETE MAURÍCIO LOPES (PIRAÚBA)
UPDATE schools SET inep_code = '181366' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LAFAYETE MAURÍCIO LOPES' AND UPPER(TRIM(city)) = 'PIRAÚBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181366');

-- EE PROFESSORA FRANCISCA PEREIRA RODRIGUES (PIRAÚBA)
UPDATE schools SET inep_code = '181382' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA FRANCISCA PEREIRA RODRIGUES' AND UPPER(TRIM(city)) = 'PIRAÚBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181382');

-- EE ANTÔNIO LUCAS MARTINS (PRESIDENTE BERNARDES)
UPDATE schools SET inep_code = '181404' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO LUCAS MARTINS' AND UPPER(TRIM(city)) = 'PRESIDENTE BERNARDES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181404');

-- EE PADRE VICENTE CARVALHO (PRESIDENTE BERNARDES)
UPDATE schools SET inep_code = '181412' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE VICENTE CARVALHO' AND UPPER(TRIM(city)) = 'PRESIDENTE BERNARDES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181412');

-- EE PROFESSOR JOSÉ BORGES DE MORAIS (RIO POMBA)
UPDATE schools SET inep_code = '181498' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOSÉ BORGES DE MORAIS' AND UPPER(TRIM(city)) = 'RIO POMBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181498');

-- EE MÁRCIO NICOLATO (RODEIRO)
UPDATE schools SET inep_code = '181528' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MÁRCIO NICOLATO' AND UPPER(TRIM(city)) = 'RODEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181528');

-- EE ÁLVARO GIESTA (SÃO GERALDO)
UPDATE schools SET inep_code = '181536' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ÁLVARO GIESTA' AND UPPER(TRIM(city)) = 'SÃO GERALDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181536');

-- EE MINISTRO ALOÍSIO COSTA (SÃO GERALDO)
UPDATE schools SET inep_code = '181579' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MINISTRO ALOÍSIO COSTA' AND UPPER(TRIM(city)) = 'SÃO GERALDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181579');

-- EE PROFESSOR CÍCERO TORRES GALINDO (SENADOR FIRMINO)
UPDATE schools SET inep_code = '181609' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR CÍCERO TORRES GALINDO' AND UPPER(TRIM(city)) = 'SENADOR FIRMINO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181609');

-- EE SANTO ANTÔNIO (SILVEIRÂNIA)
UPDATE schools SET inep_code = '181641' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SANTO ANTÔNIO' AND UPPER(TRIM(city)) = 'SILVEIRÂNIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181641');

-- EE MENELICK DE CARVALHO (TABULEIRO)
UPDATE schools SET inep_code = '181692' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MENELICK DE CARVALHO' AND UPPER(TRIM(city)) = 'TABULEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181692');

-- EE DR JOÃO PINTO (TOCANTINS)
UPDATE schools SET inep_code = '181854' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DR JOÃO PINTO' AND UPPER(TRIM(city)) = 'TOCANTINS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181854');

-- EE PROFESSOR JOÃO LOYOLA (TOCANTINS)
UPDATE schools SET inep_code = '181757' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOÃO LOYOLA' AND UPPER(TRIM(city)) = 'TOCANTINS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181757');

-- CESEC PROFESSOR JOSÉ CARNEIRO DE CASTRO (UBÁ)
UPDATE schools SET inep_code = '182028' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC PROFESSOR JOSÉ CARNEIRO DE CASTRO' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '182028');

-- COLÉGIO TIRADENTES DA PMMG - CTPM - UNIDADE CÂNDIDO MARTINS DE OLIVEIRA (UBÁ)
UPDATE schools SET inep_code = '369985' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES DA PMMG - CTPM - UNIDADE CÂNDIDO MARTINS DE OLIVEIRA' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369985');

-- EE BARÃO DO RIO BRANCO (UBÁ)
UPDATE schools SET inep_code = '182109' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BARÃO DO RIO BRANCO' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '182109');

-- EE CESÁRIO ALVIM (UBÁ)
UPDATE schools SET inep_code = '181919' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CESÁRIO ALVIM' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181919');

-- EE CORONEL CAMILO SOARES (UBÁ)
UPDATE schools SET inep_code = '181935' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL CAMILO SOARES' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181935');

-- EE CORONEL JOÃO FERREIRA DE ANDRADE (UBÁ)
UPDATE schools SET inep_code = '182095' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL JOÃO FERREIRA DE ANDRADE' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '182095');

-- EE CORONEL TEIXEIRA ERVILHA (UBÁ)
UPDATE schools SET inep_code = '182087' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL TEIXEIRA ERVILHA' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '182087');

-- EE DEPUTADO CARLOS PEIXOTO FILHO (UBÁ)
UPDATE schools SET inep_code = '181951' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DEPUTADO CARLOS PEIXOTO FILHO' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181951');

-- EE DOUTOR JOSÉ JANUÁRIO CARNEIRO (UBÁ)
UPDATE schools SET inep_code = '181978' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR JOSÉ JANUÁRIO CARNEIRO' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181978');

-- EE DOUTOR LEVINDO COELHO (UBÁ)
UPDATE schools SET inep_code = '181994' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR LEVINDO COELHO' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181994');

-- EE EUNICE WEAVER (UBÁ)
UPDATE schools SET inep_code = '181820' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE EUNICE WEAVER' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181820');

-- EE GOVERNADOR VALADARES (UBÁ)
UPDATE schools SET inep_code = '182036' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GOVERNADOR VALADARES' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '182036');

-- EE PADRE JOÃOZINHO (UBÁ)
UPDATE schools SET inep_code = '182001' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE JOÃOZINHO' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '182001');

-- EE PROFESSOR LÍVIO DE CASTRO CARNEIRO (UBÁ)
UPDATE schools SET inep_code = '181943' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR LÍVIO DE CASTRO CARNEIRO' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181943');

-- EE RAUL SOARES (UBÁ)
UPDATE schools SET inep_code = '182052' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE RAUL SOARES' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '182052');

-- EE SÃO JOSÉ (UBÁ)
UPDATE schools SET inep_code = '182079' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO JOSÉ' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '182079');

-- EE SENADOR LEVINDO COELHO (UBÁ)
UPDATE schools SET inep_code = '181862' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SENADOR LEVINDO COELHO' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '181862');

-- CESEC PROFESSOR PAULO ROBERTO REIS DE ALMEIDA (VISCONDE DO RIO BRANCO)
UPDATE schools SET inep_code = '182214' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC PROFESSOR PAULO ROBERTO REIS DE ALMEIDA' AND UPPER(TRIM(city)) = 'VISCONDE DO RIO BRANCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '182214');

-- EE CORONEL AVELINO CARDOSO (VISCONDE DO RIO BRANCO)
UPDATE schools SET inep_code = '182184' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL AVELINO CARDOSO' AND UPPER(TRIM(city)) = 'VISCONDE DO RIO BRANCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '182184');

-- EE DOUTOR CELSO MACHADO (VISCONDE DO RIO BRANCO)
UPDATE schools SET inep_code = '182222' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR CELSO MACHADO' AND UPPER(TRIM(city)) = 'VISCONDE DO RIO BRANCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '182222');

-- EE TENENTE ROBERTO SOARES DE SOUZA LIMA (VISCONDE DO RIO BRANCO)
UPDATE schools SET inep_code = '182150' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE TENENTE ROBERTO SOARES DE SOUZA LIMA' AND UPPER(TRIM(city)) = 'VISCONDE DO RIO BRANCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '182150');

-- EE JOSÉ ACÁCIO DA SILVA (ÁGUA COMPRIDA)
UPDATE schools SET inep_code = '311863' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ ACÁCIO DA SILVA' AND UPPER(TRIM(city)) = 'ÁGUA COMPRIDA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '311863');

-- EE ARMANDO SANTOS (ARAXÁ)
UPDATE schools SET inep_code = '158178' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ARMANDO SANTOS' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158178');

-- EE CORONEL JOSÉ ADOLFO AGUIAR (ARAXÁ)
UPDATE schools SET inep_code = '158186' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL JOSÉ ADOLFO AGUIAR' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158186');

-- EE DOM JOSÉ GASPAR (ARAXÁ)
UPDATE schools SET inep_code = '158224' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOM JOSÉ GASPAR' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158224');

-- EE LOREN RIOS FERES (ARAXÁ)
UPDATE schools SET inep_code = '158330' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LOREN RIOS FERES' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158330');

-- EE LUIZA DE OLIVEIRA FARIA (ARAXÁ)
UPDATE schools SET inep_code = '158267' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LUIZA DE OLIVEIRA FARIA' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158267');

-- EE MARIA DE MAGALHÃES (ARAXÁ)
UPDATE schools SET inep_code = '158275' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARIA DE MAGALHÃES' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158275');

-- EE PADRE ANACLETO GIRALDI (ARAXÁ)
UPDATE schools SET inep_code = '158216' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE ANACLETO GIRALDI' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158216');

-- EE PROFESSOR LUIZ ANTÔNIO CORRÊA OLIVEIRA (ARAXÁ)
UPDATE schools SET inep_code = '158194' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR LUIZ ANTÔNIO CORRÊA OLIVEIRA' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158194');

-- EE ROTARY (ARAXÁ)
UPDATE schools SET inep_code = '218502' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ROTARY' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218502');

-- EE VASCO SANTOS (ARAXÁ)
UPDATE schools SET inep_code = '158313' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE VASCO SANTOS' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158313');

-- EE PADRE HENRIQUE PEETERS (CAMPO FLORIDO)
UPDATE schools SET inep_code = '278904' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE HENRIQUE PEETERS' AND UPPER(TRIM(city)) = 'CAMPO FLORIDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '278904');

-- EE DOUTOR JOSÉ CORDEIRO DE CAMPOS (CAMPOS ALTOS)
UPDATE schools SET inep_code = '158534' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR JOSÉ CORDEIRO DE CAMPOS' AND UPPER(TRIM(city)) = 'CAMPOS ALTOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158534');

-- EE PADRE CLEMENTE DE MALETO (CAMPOS ALTOS)
UPDATE schools SET inep_code = '158569' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE CLEMENTE DE MALETO' AND UPPER(TRIM(city)) = 'CAMPOS ALTOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158569');

-- EE BOM SUCESSO (CARNEIRINHO)
UPDATE schools SET inep_code = '159255' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BOM SUCESSO' AND UPPER(TRIM(city)) = 'CARNEIRINHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159255');

-- EE MARECHAL HERMES (CARNEIRINHO)
UPDATE schools SET inep_code = '159271' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARECHAL HERMES' AND UPPER(TRIM(city)) = 'CARNEIRINHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159271');

-- EE PROFESSOR ANTÔNIO DA SILVA (CARNEIRINHO)
UPDATE schools SET inep_code = '159301' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ANTÔNIO DA SILVA' AND UPPER(TRIM(city)) = 'CARNEIRINHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159301');

-- EE COMENDADOR GOMES (COMENDADOR GOMES)
UPDATE schools SET inep_code = '330671' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE COMENDADOR GOMES' AND UPPER(TRIM(city)) = 'COMENDADOR GOMES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '330671');

-- EE HERCULÉGIO ANTÔNIO BORGES (CONCEIÇÃO DAS ALAGOAS)
UPDATE schools SET inep_code = '316041' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE HERCULÉGIO ANTÔNIO BORGES' AND UPPER(TRIM(city)) = 'CONCEIÇÃO DAS ALAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '316041');

-- EE JOSÉ ALEXANDRE MIZIARA (CONCEIÇÃO DAS ALAGOAS)
UPDATE schools SET inep_code = '158674' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ ALEXANDRE MIZIARA' AND UPPER(TRIM(city)) = 'CONCEIÇÃO DAS ALAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158674');

-- EE DR LINDOLFO BERNARDES (CONQUISTA)
UPDATE schools SET inep_code = '310883' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DR LINDOLFO BERNARDES' AND UPPER(TRIM(city)) = 'CONQUISTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310883');

-- EE IVAN MATTAR SOUKEF (DELTA)
UPDATE schools SET inep_code = '322644' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE IVAN MATTAR SOUKEF' AND UPPER(TRIM(city)) = 'DELTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322644');

-- EE JOÃO KOPKE (FRONTEIRA)
UPDATE schools SET inep_code = '158801' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO KOPKE' AND UPPER(TRIM(city)) = 'FRONTEIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158801');

-- EE PROFESSORA MARIA DO CARMO PIRES ROSA (FRONTEIRA)
UPDATE schools SET inep_code = '361356' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA DO CARMO PIRES ROSA' AND UPPER(TRIM(city)) = 'FRONTEIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '361356');

-- EE LAURISTON SOUZA (FRUTAL)
UPDATE schools SET inep_code = '158909' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LAURISTON SOUZA' AND UPPER(TRIM(city)) = 'FRUTAL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158909');

-- EE MAESTRO JOSINO DE OLIVEIRA (FRUTAL)
UPDATE schools SET inep_code = '158879' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MAESTRO JOSINO DE OLIVEIRA' AND UPPER(TRIM(city)) = 'FRUTAL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158879');

-- EE PRESIDENTE TANCREDO NEVES (FRUTAL)
UPDATE schools SET inep_code = '319201' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE TANCREDO NEVES' AND UPPER(TRIM(city)) = 'FRUTAL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '319201');

-- EE PROFESSOR BANDEIRA (FRUTAL)
UPDATE schools SET inep_code = '319104' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR BANDEIRA' AND UPPER(TRIM(city)) = 'FRUTAL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '319104');

-- EE VICENTE MACEDO (FRUTAL)
UPDATE schools SET inep_code = '158941' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE VICENTE MACEDO' AND UPPER(TRIM(city)) = 'FRUTAL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158941');

-- EE ALONSO DE MORAIS ANDRADE (ITAPAGIPE)
UPDATE schools SET inep_code = '159131' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALONSO DE MORAIS ANDRADE' AND UPPER(TRIM(city)) = 'ITAPAGIPE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159131');

-- EE SANTO ANTÔNIO (ITAPAGIPE)
UPDATE schools SET inep_code = '159158' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SANTO ANTÔNIO' AND UPPER(TRIM(city)) = 'ITAPAGIPE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159158');

-- EE SERRA DA MOEDA (ITAPAGIPE)
UPDATE schools SET inep_code = '159140' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SERRA DA MOEDA' AND UPPER(TRIM(city)) = 'ITAPAGIPE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159140');

-- EE ANTÔNIO FERREIRA BARBOSA (ITURAMA)
UPDATE schools SET inep_code = '159166' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO FERREIRA BARBOSA' AND UPPER(TRIM(city)) = 'ITURAMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159166');

-- EE DOM ALEXANDRE (ITURAMA)
UPDATE schools SET inep_code = '159247' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOM ALEXANDRE' AND UPPER(TRIM(city)) = 'ITURAMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159247');

-- EE JOAQUIM TIAGO DE QUEIROZ (ITURAMA)
UPDATE schools SET inep_code = '205605' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOAQUIM TIAGO DE QUEIROZ' AND UPPER(TRIM(city)) = 'ITURAMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '205605');

-- EE NOSSA SENHORA DE LOURDES (ITURAMA)
UPDATE schools SET inep_code = '159182' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DE LOURDES' AND UPPER(TRIM(city)) = 'ITURAMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159182');

-- EE TIRADENTES (ITURAMA)
UPDATE schools SET inep_code = '159212' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE TIRADENTES' AND UPPER(TRIM(city)) = 'ITURAMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159212');

-- EE IZOLDINO SOARES DE FREITAS (LIMEIRA DO OESTE)
UPDATE schools SET inep_code = '159280' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE IZOLDINO SOARES DE FREITAS' AND UPPER(TRIM(city)) = 'LIMEIRA DO OESTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159280');

-- EE PROFESSOR LEÃO COELHO DE ALMEIDA (PEDRINÓPOLIS)
UPDATE schools SET inep_code = '159328' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR LEÃO COELHO DE ALMEIDA' AND UPPER(TRIM(city)) = 'PEDRINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159328');

-- EE CORONEL OSCAR DE CASTRO (PIRAJUBA)
UPDATE schools SET inep_code = '311855' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL OSCAR DE CASTRO' AND UPPER(TRIM(city)) = 'PIRAJUBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '311855');

-- EE ALYSSON ROBERTO BRUNO (PLANURA)
UPDATE schools SET inep_code = '159417' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALYSSON ROBERTO BRUNO' AND UPPER(TRIM(city)) = 'PLANURA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159417');

-- EE MARLENE MARTINS REIS (PRATINHA)
UPDATE schools SET inep_code = '319112' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARLENE MARTINS REIS' AND UPPER(TRIM(city)) = 'PRATINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '319112');

-- EE BARÃO DA RIFAINA (SACRAMENTO)
UPDATE schools SET inep_code = '159484' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BARÃO DA RIFAINA' AND UPPER(TRIM(city)) = 'SACRAMENTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159484');

-- EE CORONEL JOSÉ AFONSO DE ALMEIDA (SACRAMENTO)
UPDATE schools SET inep_code = '159506' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL JOSÉ AFONSO DE ALMEIDA' AND UPPER(TRIM(city)) = 'SACRAMENTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159506');

-- EE ESCRITORA CAROLINA MARIA DE JESUS (SACRAMENTO)
UPDATE schools SET inep_code = '361224' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ESCRITORA CAROLINA MARIA DE JESUS' AND UPPER(TRIM(city)) = 'SACRAMENTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '361224');

-- EE SINHANA BORGES (SACRAMENTO)
UPDATE schools SET inep_code = '159565' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SINHANA BORGES' AND UPPER(TRIM(city)) = 'SACRAMENTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159565');

-- EE SANTA JULIANA (SANTA JULIANA)
UPDATE schools SET inep_code = '159611' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SANTA JULIANA' AND UPPER(TRIM(city)) = 'SANTA JULIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159611');

-- EE SÃO FRANCISCO DE SALES (SÃO FRANCISCO DE SALES)
UPDATE schools SET inep_code = '159646' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO FRANCISCO DE SALES' AND UPPER(TRIM(city)) = 'SÃO FRANCISCO DE SALES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159646');

-- EE PROFESSORA CECÍLIA MARIA DE REZENDE NEVES (TAPIRA)
UPDATE schools SET inep_code = '310166' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA CECÍLIA MARIA DE REZENDE NEVES' AND UPPER(TRIM(city)) = 'TAPIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310166');

-- CENTRO DE ORIENTAÇÃO E PESQUISA EM EDUCAÇÃO ESPECIAL (UBERABA)
UPDATE schools SET inep_code = '218588' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE ORIENTAÇÃO E PESQUISA EM EDUCAÇÃO ESPECIAL' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218588');

-- CESEC PROFESSORA MARIA EMÍLIA DA ROCHA (UBERABA)
UPDATE schools SET inep_code = '313751' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC PROFESSORA MARIA EMÍLIA DA ROCHA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '313751');

-- COLÉGIO TIRADENTES PMMG (UBERABA)
UPDATE schools SET inep_code = '160253' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '160253');

-- EE ALOÍZIO CASTANHEIRA (UBERABA)
UPDATE schools SET inep_code = '342556' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALOÍZIO CASTANHEIRA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342556');

-- EE AMÉRICA (UBERABA)
UPDATE schools SET inep_code = '159735' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE AMÉRICA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159735');

-- EE AURÉLIO LUIZ DA COSTA (UBERABA)
UPDATE schools SET inep_code = '159662' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE AURÉLIO LUIZ DA COSTA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159662');

-- EE BERNARDO VASCONCELOS (UBERABA)
UPDATE schools SET inep_code = '159786' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BERNARDO VASCONCELOS' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159786');

-- EE BOULANGER PUCCI (UBERABA)
UPDATE schools SET inep_code = '159841' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BOULANGER PUCCI' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159841');

-- EE CARMELITA CARVALHO GARCIA (UBERABA)
UPDATE schools SET inep_code = '160261' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CARMELITA CARVALHO GARCIA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '160261');

-- EE DOUTOR JOSÉ MENDONÇA (UBERABA)
UPDATE schools SET inep_code = '160024' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR JOSÉ MENDONÇA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '160024');

-- EE FELÍCIO DE PAIVA (UBERABA)
UPDATE schools SET inep_code = '160067' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE FELÍCIO DE PAIVA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '160067');

-- EE FRANCISCO CÂNDIDO XAVIER (UBERABA)
UPDATE schools SET inep_code = '349321' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE FRANCISCO CÂNDIDO XAVIER' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349321');

-- EE FREI LEOPOLDO DE CASTELNUOVO (UBERABA)
UPDATE schools SET inep_code = '160083' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE FREI LEOPOLDO DE CASTELNUOVO' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '160083');

-- EE GABRIEL TOTI (UBERABA)
UPDATE schools SET inep_code = '160105' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GABRIEL TOTI' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '160105');

-- EE GERALDINO RODRIGUES CUNHA (UBERABA)
UPDATE schools SET inep_code = '160237' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GERALDINO RODRIGUES CUNHA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '160237');

-- EE HENRIQUE KRUGER (UBERABA)
UPDATE schools SET inep_code = '160121' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE HENRIQUE KRUGER' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '160121');

-- EE HORIZONTA LEMOS (UBERABA)
UPDATE schools SET inep_code = '160148' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE HORIZONTA LEMOS' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '160148');

-- EE IRMÃO AFONSO (UBERABA)
UPDATE schools SET inep_code = '160164' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE IRMÃO AFONSO' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '160164');

-- EE LAURO FONTOURA (UBERABA)
UPDATE schools SET inep_code = '160172' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LAURO FONTOURA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '160172');

-- EE LEANDRO ANTÔNIO DE VITO (UBERABA)
UPDATE schools SET inep_code = '160245' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LEANDRO ANTÔNIO DE VITO' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '160245');

-- EE MARECHAL HUMBERTO ALENCAR CASTELO BRANCO (UBERABA)
UPDATE schools SET inep_code = '159671' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARECHAL HUMBERTO ALENCAR CASTELO BRANCO' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159671');

-- EE MINAS GERAIS (UBERABA)
UPDATE schools SET inep_code = '159751' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MINAS GERAIS' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159751');

-- EE NOSSA SENHORA DA ABADIA (UBERABA)
UPDATE schools SET inep_code = '159794' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DA ABADIA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159794');

-- EE PAULO JOSÉ DERENUSSON (UBERABA)
UPDATE schools SET inep_code = '159891' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PAULO JOSÉ DERENUSSON' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159891');

-- EE PRESIDENTE JOÃO PINHEIRO (UBERABA)
UPDATE schools SET inep_code = '159956' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE JOÃO PINHEIRO' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159956');

-- EE PROFESSOR ALCEU NOVAES (UBERABA)
UPDATE schools SET inep_code = '159999' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ALCEU NOVAES' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159999');

-- EE PROFESSOR CHAVES (UBERABA)
UPDATE schools SET inep_code = '160016' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR CHAVES' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '160016');

-- EE PROFESSOR HILDEBRANDO PONTES (UBERABA)
UPDATE schools SET inep_code = '160059' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR HILDEBRANDO PONTES' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '160059');

-- EE PROFESSORA CORINA DE OLIVEIRA (UBERABA)
UPDATE schools SET inep_code = '159972' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA CORINA DE OLIVEIRA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159972');

-- EE PROFESSORA NEIDE OLIVEIRA GOMES (UBERABA)
UPDATE schools SET inep_code = '349313' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA NEIDE OLIVEIRA GOMES' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349313');

-- EE QUINTILIANO JARDIM (UBERABA)
UPDATE schools SET inep_code = '160075' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE QUINTILIANO JARDIM' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '160075');

-- EE ROTARY (UBERABA)
UPDATE schools SET inep_code = '160091' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ROTARY' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '160091');

-- EE SANTA TEREZINHA (UBERABA)
UPDATE schools SET inep_code = '160130' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SANTA TEREZINHA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '160130');

-- EE SÃO BENEDITO (UBERABA)
UPDATE schools SET inep_code = '160156' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO BENEDITO' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '160156');

-- EE DOM PEDRO II (UNIÃO DE MINAS)
UPDATE schools SET inep_code = '159310' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOM PEDRO II' AND UPPER(TRIM(city)) = 'UNIÃO DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159310');

-- EE GERALDINO RODRIGUES DA CUNHA (VERÍSSIMO)
UPDATE schools SET inep_code = '160326' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GERALDINO RODRIGUES DA CUNHA' AND UPPER(TRIM(city)) = 'VERÍSSIMO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '160326');

-- CESEC JK (ARAGUARI)
UPDATE schools SET inep_code = '166821' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC JK' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166821');

-- COLÉGIO TIRADENTES DA PMMG - CTPM - UNIDADE ARAGUARI (ARAGUARI)
UPDATE schools SET inep_code = '369993' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES DA PMMG - CTPM - UNIDADE ARAGUARI' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369993');

-- CONSERVATÓRIO ESTADUAL MÚSICA E CENTRO INTERESCOLAR ARTES RAUL BELÉM (ARAGUARI)
UPDATE schools SET inep_code = '166642' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CONSERVATÓRIO ESTADUAL MÚSICA E CENTRO INTERESCOLAR ARTES RAUL BELÉM' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166642');

-- EE ANTÔNIO NUNES CARVALHO FILHO (ARAGUARI)
UPDATE schools SET inep_code = '166618' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO NUNES CARVALHO FILHO' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166618');

-- EE ARTUR BERNARDES (ARAGUARI)
UPDATE schools SET inep_code = '166839' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ARTUR BERNARDES' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166839');

-- EE CORONEL LINDOLFO RODRIGUES CUNHA (ARAGUARI)
UPDATE schools SET inep_code = '166855' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL LINDOLFO RODRIGUES CUNHA' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166855');

-- EE COSTA SENA (ARAGUARI)
UPDATE schools SET inep_code = '166626' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE COSTA SENA' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166626');

-- EE DONA ELEONORA PIERUCCETTI (ARAGUARI)
UPDATE schools SET inep_code = '166634' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DONA ELEONORA PIERUCCETTI' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166634');

-- EE ISOLINA FRANÇA SOARES TORRES (ARAGUARI)
UPDATE schools SET inep_code = '166651' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ISOLINA FRANÇA SOARES TORRES' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166651');

-- EE JOSÉ CARNEIRO DA CUNHA (ARAGUARI)
UPDATE schools SET inep_code = '166812' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ CARNEIRO DA CUNHA' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166812');

-- EE MADRE MARIA BLANDINA (ARAGUARI)
UPDATE schools SET inep_code = '166685' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MADRE MARIA BLANDINA' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166685');

-- EE PADRE DAMIÃO (ARAGUARI)
UPDATE schools SET inep_code = '166693' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE DAMIÃO' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166693');

-- EE PAES DE ALMEIDA (ARAGUARI)
UPDATE schools SET inep_code = '166715' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PAES DE ALMEIDA' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166715');

-- EE PROFESSOR ANTÔNIO MARQUES (ARAGUARI)
UPDATE schools SET inep_code = '166731' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ANTÔNIO MARQUES' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166731');

-- EE PROFESSORA KATY BELEM (ARAGUARI)
UPDATE schools SET inep_code = '166782' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA KATY BELEM' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166782');

-- EE RAUL SOARES (ARAGUARI)
UPDATE schools SET inep_code = '166740' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE RAUL SOARES' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166740');

-- EE SÃO JUDAS TADEU (ARAGUARI)
UPDATE schools SET inep_code = '166766' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO JUDAS TADEU' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166766');

-- EE MÁRIO SIDNEY FRANCESCHI (ARAPORÃ)
UPDATE schools SET inep_code = '167207' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MÁRIO SIDNEY FRANCESCHI' AND UPPER(TRIM(city)) = 'ARAPORÃ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167207');

-- CESEC PROFESSORA ROMILDA DINIZ (CAMPINA VERDE)
UPDATE schools SET inep_code = '158429' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC PROFESSORA ROMILDA DINIZ' AND UPPER(TRIM(city)) = 'CAMPINA VERDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158429');

-- EE ANA CHAVES (CAMPINA VERDE)
UPDATE schools SET inep_code = '158356' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANA CHAVES' AND UPPER(TRIM(city)) = 'CAMPINA VERDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158356');

-- EE DOUTOR NICODEMUS DE MACEDO (CAMPINA VERDE)
UPDATE schools SET inep_code = '319147' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR NICODEMUS DE MACEDO' AND UPPER(TRIM(city)) = 'CAMPINA VERDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '319147');

-- EE NOSSA SENHORA DAS GRAÇAS (CAMPINA VERDE)
UPDATE schools SET inep_code = '158399' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DAS GRAÇAS' AND UPPER(TRIM(city)) = 'CAMPINA VERDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158399');

-- EE OLINDA CORREA BORGES (CAMPINA VERDE)
UPDATE schools SET inep_code = '158437' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE OLINDA CORREA BORGES' AND UPPER(TRIM(city)) = 'CAMPINA VERDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158437');

-- EE NÉLSON SOARES DE OLIVEIRA (INDIANÓPOLIS)
UPDATE schools SET inep_code = '166871' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NÉLSON SOARES DE OLIVEIRA' AND UPPER(TRIM(city)) = 'INDIANÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166871');

-- EE EUFRAUSINA DA COSTA ARAÚJO (MONTE ALEGRE DE MINAS)
UPDATE schools SET inep_code = '166961' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE EUFRAUSINA DA COSTA ARAÚJO' AND UPPER(TRIM(city)) = 'MONTE ALEGRE DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166961');

-- EE MONTE ALEGRE DE MINAS (MONTE ALEGRE DE MINAS)
UPDATE schools SET inep_code = '166936' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MONTE ALEGRE DE MINAS' AND UPPER(TRIM(city)) = 'MONTE ALEGRE DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166936');

-- EE TANCREDO MARTINS (MONTE ALEGRE DE MINAS)
UPDATE schools SET inep_code = '166952' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE TANCREDO MARTINS' AND UPPER(TRIM(city)) = 'MONTE ALEGRE DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166952');

-- EE JOSIAS PINTO (NOVA PONTE)
UPDATE schools SET inep_code = '166979' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSIAS PINTO' AND UPPER(TRIM(city)) = 'NOVA PONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166979');

-- EE CORONEL PEDRO NERY (PRATA)
UPDATE schools SET inep_code = '319163' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL PEDRO NERY' AND UPPER(TRIM(city)) = 'PRATA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '319163');

-- EE DO PRATA (PRATA)
UPDATE schools SET inep_code = '167045' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DO PRATA' AND UPPER(TRIM(city)) = 'PRATA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167045');

-- EE NORALDINO LIMA (PRATA)
UPDATE schools SET inep_code = '319171' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NORALDINO LIMA' AND UPPER(TRIM(city)) = 'PRATA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '319171');

-- EE PROFESSOR VALENTIN (PRATA)
UPDATE schools SET inep_code = '167053' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR VALENTIN' AND UPPER(TRIM(city)) = 'PRATA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167053');

-- EE ANA ESTERLITA ALVES (TUPACIGUARA)
UPDATE schools SET inep_code = '167118' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANA ESTERLITA ALVES' AND UPPER(TRIM(city)) = 'TUPACIGUARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167118');

-- EE CLERTAN MOREIRA DO VALE (TUPACIGUARA)
UPDATE schools SET inep_code = '167169' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CLERTAN MOREIRA DO VALE' AND UPPER(TRIM(city)) = 'TUPACIGUARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167169');

-- EE DE ENSINO MÉDIO (TUPACIGUARA)
UPDATE schools SET inep_code = '361305' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' AND UPPER(TRIM(city)) = 'TUPACIGUARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '361305');

-- EE SEBASTIÃO DIAS FERRAZ (TUPACIGUARA)
UPDATE schools SET inep_code = '167193' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SEBASTIÃO DIAS FERRAZ' AND UPPER(TRIM(city)) = 'TUPACIGUARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167193');

-- COLÉGIO TIRADENTES PMMG (UBERLÂNDIA)
UPDATE schools SET inep_code = '362298' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '362298');

-- EE 13 DE MAIO (UBERLÂNDIA)
UPDATE schools SET inep_code = '167657' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE 13 DE MAIO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167657');

-- EE AFONSO ARINOS (UBERLÂNDIA)
UPDATE schools SET inep_code = '167240' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE AFONSO ARINOS' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167240');

-- EE ALDA MOTA BATISTA (UBERLÂNDIA)
UPDATE schools SET inep_code = '167282' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALDA MOTA BATISTA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167282');

-- EE AMADOR NAVES (UBERLÂNDIA)
UPDATE schools SET inep_code = '167363' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE AMADOR NAVES' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167363');

-- EE AMÉRICO RENÉ GIANNETTI (UBERLÂNDIA)
UPDATE schools SET inep_code = '167321' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE AMÉRICO RENÉ GIANNETTI' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167321');

-- EE ÂNGELA TEIXEIRA DA SILVA (UBERLÂNDIA)
UPDATE schools SET inep_code = '167401' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ÂNGELA TEIXEIRA DA SILVA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167401');

-- EE ANGELINO PAVAN (UBERLÂNDIA)
UPDATE schools SET inep_code = '167461' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANGELINO PAVAN' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167461');

-- EE ANTÔNIO LUIS BASTOS (UBERLÂNDIA)
UPDATE schools SET inep_code = '167487' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO LUIS BASTOS' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167487');

-- EE ANTÔNIO THOMAZ FERREIRA DE REZENDE (UBERLÂNDIA)
UPDATE schools SET inep_code = '167771' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO THOMAZ FERREIRA DE REZENDE' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167771');

-- EE BUENO BRANDÃO (UBERLÂNDIA)
UPDATE schools SET inep_code = '167568' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BUENO BRANDÃO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167568');

-- EE CLARIMUNDO CARNEIRO (UBERLÂNDIA)
UPDATE schools SET inep_code = '167681' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CLARIMUNDO CARNEIRO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167681');

-- EE CUSTÓDIO DA COSTA PEREIRA (UBERLÂNDIA)
UPDATE schools SET inep_code = '167223' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CUSTÓDIO DA COSTA PEREIRA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167223');

-- EE DA CIDADE INDUSTRIAL (UBERLÂNDIA)
UPDATE schools SET inep_code = '167649' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DA CIDADE INDUSTRIAL' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167649');

-- EE DE ENSINO FUNDAMENTAL E MÉDIO (UBERLÂNDIA)
UPDATE schools SET inep_code = '338893' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL E MÉDIO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338893');

-- EE DE UBERLÂNDIA (UBERLÂNDIA)
UPDATE schools SET inep_code = '167690' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE UBERLÂNDIA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167690');

-- EE DO BAIRRO JARDIM DAS PALMEIRAS (UBERLÂNDIA)
UPDATE schools SET inep_code = '167665' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DO BAIRRO JARDIM DAS PALMEIRAS' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167665');

-- EE DO PARQUE SÃO JORGE (UBERLÂNDIA)
UPDATE schools SET inep_code = '167797' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DO PARQUE SÃO JORGE' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167797');

-- EE DR DUARTE PIMENTEL DE ULHOA (UBERLÂNDIA)
UPDATE schools SET inep_code = '167827' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DR DUARTE PIMENTEL DE ULHOA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167827');

-- EE ENÉIAS VASCONCELOS (UBERLÂNDIA)
UPDATE schools SET inep_code = '167215' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ENÉIAS VASCONCELOS' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167215');

-- EE FELISBERTO ALVES CARREJO (UBERLÂNDIA)
UPDATE schools SET inep_code = '167231' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE FELISBERTO ALVES CARREJO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167231');

-- EE FREI EGÍDIO PARISI (UBERLÂNDIA)
UPDATE schools SET inep_code = '167584' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE FREI EGÍDIO PARISI' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167584');

-- EE GUIOMAR DE FREITAS COSTA (UBERLÂNDIA)
UPDATE schools SET inep_code = '167258' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GUIOMAR DE FREITAS COSTA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167258');

-- EE HERCÍLIA MARTINS REZENDE (UBERLÂNDIA)
UPDATE schools SET inep_code = '167703' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE HERCÍLIA MARTINS REZENDE' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167703');

-- EE HONÓRIO GUIMARÃES (UBERLÂNDIA)
UPDATE schools SET inep_code = '167274' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE HONÓRIO GUIMARÃES' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167274');

-- EE HORTÊNCIO DINIZ (UBERLÂNDIA)
UPDATE schools SET inep_code = '167266' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE HORTÊNCIO DINIZ' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167266');

-- EE IGNÁCIO PAES LEME (UBERLÂNDIA)
UPDATE schools SET inep_code = '167291' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE IGNÁCIO PAES LEME' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167291');

-- EE JARDIM IPANEMA (UBERLÂNDIA)
UPDATE schools SET inep_code = '167878' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JARDIM IPANEMA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167878');

-- EE JERÔNIMO ARANTES (UBERLÂNDIA)
UPDATE schools SET inep_code = '167606' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JERÔNIMO ARANTES' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167606');

-- EE JOÃO REZENDE (UBERLÂNDIA)
UPDATE schools SET inep_code = '167622' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO REZENDE' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167622');

-- EE JOAQUIM SARAIVA (UBERLÂNDIA)
UPDATE schools SET inep_code = '167312' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOAQUIM SARAIVA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167312');

-- EE JOSÉ GOMES JUNQUEIRA (UBERLÂNDIA)
UPDATE schools SET inep_code = '207403' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ GOMES JUNQUEIRA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '207403');

-- EE LOURDES DE CARVALHO (UBERLÂNDIA)
UPDATE schools SET inep_code = '167509' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LOURDES DE CARVALHO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167509');

-- EE MARECHAL CASTELO BRANCO (UBERLÂNDIA)
UPDATE schools SET inep_code = '167371' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARECHAL CASTELO BRANCO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167371');

-- EE MARIA DA CONCEIÇÃO BARBOSA DE SOUZA (UBERLÂNDIA)
UPDATE schools SET inep_code = '167410' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARIA DA CONCEIÇÃO BARBOSA DE SOUZA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167410');

-- EE MÁRIO PORTO (UBERLÂNDIA)
UPDATE schools SET inep_code = '167398' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MÁRIO PORTO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167398');

-- EE MESSIAS PEDREIRO (UBERLÂNDIA)
UPDATE schools SET inep_code = '167436' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MESSIAS PEDREIRO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167436');

-- EE NEUZA REZENDE (UBERLÂNDIA)
UPDATE schools SET inep_code = '167746' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NEUZA REZENDE' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167746');

-- EE NO CONJUNTO HABITACIONAL CRUZEIRO DO SUL (UBERLÂNDIA)
UPDATE schools SET inep_code = '167347' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NO CONJUNTO HABITACIONAL CRUZEIRO DO SUL' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167347');

-- EE PADRE MARIO FORESTAN (UBERLÂNDIA)
UPDATE schools SET inep_code = '167495' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE MARIO FORESTAN' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167495');

-- EE PRESIDENTE JUSCELINO KUBITSCHEK (UBERLÂNDIA)
UPDATE schools SET inep_code = '167754' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE JUSCELINO KUBITSCHEK' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167754');

-- EE PRESIDENTE TANCREDO NEVES (UBERLÂNDIA)
UPDATE schools SET inep_code = '167711' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE TANCREDO NEVES' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167711');

-- EE PROFESSOR EDERLINDO LANNES BERNARDES (UBERLÂNDIA)
UPDATE schools SET inep_code = '167843' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR EDERLINDO LANNES BERNARDES' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167843');

-- EE PROFESSOR INÁCIO CASTILHO (UBERLÂNDIA)
UPDATE schools SET inep_code = '167541' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR INÁCIO CASTILHO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167541');

-- EE PROFESSOR JOSÉ IGNÁCIO DE SOUSA (UBERLÂNDIA)
UPDATE schools SET inep_code = '167339' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOSÉ IGNÁCIO DE SOUSA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167339');

-- EE PROFESSOR LEÔNIDAS DE CASTRO SERRA (UBERLÂNDIA)
UPDATE schools SET inep_code = '167380' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR LEÔNIDAS DE CASTRO SERRA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167380');

-- EE PROFESSOR NELSON CUPERTINO (UBERLÂNDIA)
UPDATE schools SET inep_code = '167428' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR NELSON CUPERTINO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167428');

-- EE PROFESSORA ALICE PAES (UBERLÂNDIA)
UPDATE schools SET inep_code = '167517' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ALICE PAES' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167517');

-- EE PROFESSORA JUVENÍLIA  FERREIRA DOS SANTOS (UBERLÂNDIA)
UPDATE schools SET inep_code = '167304' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA JUVENÍLIA  FERREIRA DOS SANTOS' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167304');

-- EE ROTARY (UBERLÂNDIA)
UPDATE schools SET inep_code = '167550' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ROTARY' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167550');

-- EE SEGISMUNDO PEREIRA (UBERLÂNDIA)
UPDATE schools SET inep_code = '167614' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SEGISMUNDO PEREIRA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167614');

-- EE SEIS DE JUNHO (UBERLÂNDIA)
UPDATE schools SET inep_code = '167576' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SEIS DE JUNHO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167576');

-- EE SÉRGIO DE FREITAS PACHECO (UBERLÂNDIA)
UPDATE schools SET inep_code = '167592' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÉRGIO DE FREITAS PACHECO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167592');

-- EE SETE DE SETEMBRO (UBERLÂNDIA)
UPDATE schools SET inep_code = '167631' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SETE DE SETEMBRO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167631');

-- EE TEOTÔNIO VILELA (UBERLÂNDIA)
UPDATE schools SET inep_code = '167738' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE TEOTÔNIO VILELA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167738');

-- EE TUBAL VILELA DA SILVA (UBERLÂNDIA)
UPDATE schools SET inep_code = '167673' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE TUBAL VILELA DA SILVA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167673');

-- CESEC AFONSO ARINOS (ARINOS)
UPDATE schools SET inep_code = '346268' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC AFONSO ARINOS' AND UPPER(TRIM(city)) = 'ARINOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346268');

-- EE CARMOSINA DURÃES MARTINS (ARINOS)
UPDATE schools SET inep_code = '108227' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CARMOSINA DURÃES MARTINS' AND UPPER(TRIM(city)) = 'ARINOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108227');

-- EE CHICO MENDES (ARINOS)
UPDATE schools SET inep_code = '349291' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CHICO MENDES' AND UPPER(TRIM(city)) = 'ARINOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349291');

-- EE GARIBALDINA FERNANDES VALADARES (ARINOS)
UPDATE schools SET inep_code = '108219' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GARIBALDINA FERNANDES VALADARES' AND UPPER(TRIM(city)) = 'ARINOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108219');

-- EE MAJOR SAINT CLAIR FERNANDES VALADARES (ARINOS)
UPDATE schools SET inep_code = '108197' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MAJOR SAINT CLAIR FERNANDES VALADARES' AND UPPER(TRIM(city)) = 'ARINOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108197');