-- ESCOLA PARTICULAR DORENSE (DORES DO INDAIÁ)
UPDATE schools SET inep_code = '251551' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA PARTICULAR DORENSE' AND UPPER(TRIM(city)) = 'DORES DO INDAIÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '251551');

-- COLÉGIO APOGEU PARÁ DE MINAS (PARÁ DE MINAS)
UPDATE schools SET inep_code = '258512' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO APOGEU PARÁ DE MINAS' AND UPPER(TRIM(city)) = 'PARÁ DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '258512');

-- COLÉGIO CIDADE DE PARÁ DE MINAS (PARÁ DE MINAS)
UPDATE schools SET inep_code = '342327' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CIDADE DE PARÁ DE MINAS' AND UPPER(TRIM(city)) = 'PARÁ DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342327');

-- COLÉGIO TÉCNICO SÃO FRANCISCO DE ASSIS (PARÁ DE MINAS)
UPDATE schools SET inep_code = '246158' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TÉCNICO SÃO FRANCISCO DE ASSIS' AND UPPER(TRIM(city)) = 'PARÁ DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246158');

-- ESCOLA SESI DOUTOR CELSO CHARURI (PARÁ DE MINAS)
UPDATE schools SET inep_code = '369616' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SESI DOUTOR CELSO CHARURI' AND UPPER(TRIM(city)) = 'PARÁ DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369616');

-- SENAI CENTRO DE FORMAÇÃO PROFISSIONAL CELSO CHARURI (PARÁ DE MINAS)
UPDATE schools SET inep_code = '322962' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI CENTRO DE FORMAÇÃO PROFISSIONAL CELSO CHARURI' AND UPPER(TRIM(city)) = 'PARÁ DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322962');

-- CENTRO EDUCACIONAL PROFESSOR FRANCISCO SALDANHA (PITANGUI)
UPDATE schools SET inep_code = '253367' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL PROFESSOR FRANCISCO SALDANHA' AND UPPER(TRIM(city)) = 'PITANGUI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253367');

-- CENTRO PEDAGÓGICO OTONI BRAGA (PITANGUI)
UPDATE schools SET inep_code = '296287' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO PEDAGÓGICO OTONI BRAGA' AND UPPER(TRIM(city)) = 'PITANGUI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '296287');

-- COTEFER – COLÉGIO TÉCNICO FERNANDES (PITANGUI)
UPDATE schools SET inep_code = '351490' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COTEFER – COLÉGIO TÉCNICO FERNANDES' AND UPPER(TRIM(city)) = 'PITANGUI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '351490');

-- INSTITUTO ESTHER VALÉRIO (PITANGUI)
UPDATE schools SET inep_code = '279382' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO ESTHER VALÉRIO' AND UPPER(TRIM(city)) = 'PITANGUI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '279382');

-- CENTRO DE ENSINO BALUARTE (JOÃO PINHEIRO)
UPDATE schools SET inep_code = '330817' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE ENSINO BALUARTE' AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '330817');

-- CENTRO EDUCACIONAL VISÃO (JOÃO PINHEIRO)
UPDATE schools SET inep_code = '317284' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL VISÃO' AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '317284');

-- COLÉGIO CENECISTA JOÃO PINHEIRO (JOÃO PINHEIRO)
UPDATE schools SET inep_code = '245003' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CENECISTA JOÃO PINHEIRO' AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '245003');

-- COLÉGIO DARCÍLIA COIMBRA (JOÃO PINHEIRO)
UPDATE schools SET inep_code = '374652' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DARCÍLIA COIMBRA' AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '374652');

-- COLÉGIO ATENAS - UNIDADE II (PARACATU)
UPDATE schools SET inep_code = '357138' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ATENAS - UNIDADE II' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '357138');

-- COLÉGIO ATENAS- UNIDADE I (PARACATU)
UPDATE schools SET inep_code = '260941' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ATENAS- UNIDADE I' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '260941');

-- COLÉGIO IMPÉRIO EDUCACIONAL (PARACATU)
UPDATE schools SET inep_code = '334251' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO IMPÉRIO EDUCACIONAL' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '334251');

-- COLÉGIO SOMA (PARACATU)
UPDATE schools SET inep_code = '215571' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SOMA' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '215571');

-- ESCOLA DOM ELIZEU VAN DE WEIJER (PARACATU)
UPDATE schools SET inep_code = '114774' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DOM ELIZEU VAN DE WEIJER' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '114774');

-- ESCOLA MULTI-TECH CURSOS E INFORMÁTICA (PARACATU)
UPDATE schools SET inep_code = '334030' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA MULTI-TECH CURSOS E INFORMÁTICA' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '334030');

-- ESCOLA POLITÉCNICA DE PARACATU (PARACATU)
UPDATE schools SET inep_code = '368482' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA POLITÉCNICA DE PARACATU' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368482');

-- ESCOLA TÉCNICA DE PARACATU (PARACATU)
UPDATE schools SET inep_code = '292605' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA DE PARACATU' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '292605');

-- SENAI CENTRO DE FORMAÇÃO PROFISSIONAL EPITÁCIO CARDOSO NAVES (PARACATU)
UPDATE schools SET inep_code = '342165' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI CENTRO DE FORMAÇÃO PROFISSIONAL EPITÁCIO CARDOSO NAVES' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342165');

-- CENTRO EDUCACIONAL SEBASTIANA ALVES (VAZANTE)
UPDATE schools SET inep_code = '245372' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL SEBASTIANA ALVES' AND UPPER(TRIM(city)) = 'VAZANTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '245372');

-- ESCOLA TÉCNICA DE VAZANTE (VAZANTE)
UPDATE schools SET inep_code = '352691' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA DE VAZANTE' AND UPPER(TRIM(city)) = 'VAZANTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '352691');

-- SENAI CENTRO DE FORMAÇÃO PROFISSIONAL MARCELO IANHEZ (VAZANTE)
UPDATE schools SET inep_code = '321915' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI CENTRO DE FORMAÇÃO PROFISSIONAL MARCELO IANHEZ' AND UPPER(TRIM(city)) = 'VAZANTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '321915');

-- SEV - SOCIEDADE EDUCACIONAL DE VAZANTE (VAZANTE)
UPDATE schools SET inep_code = '310751' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SEV - SOCIEDADE EDUCACIONAL DE VAZANTE' AND UPPER(TRIM(city)) = 'VAZANTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310751');

-- COLÉGIO ALBERTINO GONÇALVES DOS REIS (ALPINÓPOLIS)
UPDATE schools SET inep_code = '298905' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ALBERTINO GONÇALVES DOS REIS' AND UPPER(TRIM(city)) = 'ALPINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '298905');

-- INSTITUTO EDUCACIONAL PADRE UBIRAJARA CABRAL (ALPINÓPOLIS)
UPDATE schools SET inep_code = '254291' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL PADRE UBIRAJARA CABRAL' AND UPPER(TRIM(city)) = 'ALPINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '254291');

-- COLÉGIO VENCER (CARMO DO RIO CLARO)
UPDATE schools SET inep_code = '295175' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO VENCER' AND UPPER(TRIM(city)) = 'CARMO DO RIO CLARO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '295175');

-- INST EDUC CULT CARMO DO RIO CLARO (CARMO DO RIO CLARO)
UPDATE schools SET inep_code = '249203' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INST EDUC CULT CARMO DO RIO CLARO' AND UPPER(TRIM(city)) = 'CARMO DO RIO CLARO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '249203');

-- COLÉGIO LOSANGO DE FORMIGA-UNIDADE I (FORMIGA)
UPDATE schools SET inep_code = '309770' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO LOSANGO DE FORMIGA-UNIDADE I' AND UPPER(TRIM(city)) = 'FORMIGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '309770');

-- COLÉGIO SANTA TERESINHA (FORMIGA)
UPDATE schools SET inep_code = '118311' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SANTA TERESINHA' AND UPPER(TRIM(city)) = 'FORMIGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '118311');

-- COLÉGIO TÉCNICO CECON FORMIGA (FORMIGA)
UPDATE schools SET inep_code = '317748' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TÉCNICO CECON FORMIGA' AND UPPER(TRIM(city)) = 'FORMIGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '317748');

-- COLÉGIO UNIFOR (FORMIGA)
UPDATE schools SET inep_code = '118281' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO UNIFOR' AND UPPER(TRIM(city)) = 'FORMIGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '118281');

-- COLÉGIO UNIFOR - UNIDADE II (FORMIGA)
UPDATE schools SET inep_code = '355313' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO UNIFOR - UNIDADE II' AND UPPER(TRIM(city)) = 'FORMIGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '355313');

-- SENAI FORMIGA CT LUIZ RODRIGUES DA COSTA (FORMIGA)
UPDATE schools SET inep_code = '380369' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI FORMIGA CT LUIZ RODRIGUES DA COSTA' AND UPPER(TRIM(city)) = 'FORMIGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '380369');

-- COLÉGIO DEL REY (PASSOS)
UPDATE schools SET inep_code = '294900' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DEL REY' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '294900');

-- COLÉGIO ETEP- ESCOLA TÉCNICA DE PASSOS (PASSOS)
UPDATE schools SET inep_code = '321133' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ETEP- ESCOLA TÉCNICA DE PASSOS' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '321133');

-- COLÉGIO IMACULADA CONCEIÇÃO (PASSOS)
UPDATE schools SET inep_code = '118320' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO IMACULADA CONCEIÇÃO' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '118320');

-- COLÉGIO OBJETIVO DE PASSOS (PASSOS)
UPDATE schools SET inep_code = '223883' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO OBJETIVO DE PASSOS' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '223883');

-- COLÉGIO SÃO FRANCISCO – UNIDADE II (PASSOS)
UPDATE schools SET inep_code = '362735' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SÃO FRANCISCO – UNIDADE II' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '362735');

-- COLÉGIO STATUS (PASSOS)
UPDATE schools SET inep_code = '118346' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO STATUS' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '118346');

-- ESCOLA TÉCNICA PROFESSOR JOSÉ PAULO DE SOUZA (PASSOS)
UPDATE schools SET inep_code = '324779' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA PROFESSOR JOSÉ PAULO DE SOUZA' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '324779');

-- INSTITUTO EDUCACIONAL FIT - MG (PASSOS)
UPDATE schools SET inep_code = '374199' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL FIT - MG' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '374199');

-- INSTITUTO EDUCACIONAL MÁRIS CÉLIS (PASSOS)
UPDATE schools SET inep_code = '311553' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL MÁRIS CÉLIS' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '311553');

-- PRO EDUCAR ESCOLA TÉCNICA (PASSOS)
UPDATE schools SET inep_code = '368490' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'PRO EDUCAR ESCOLA TÉCNICA' AND UPPER(TRIM(city)) = 'PASSOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368490');

-- COLÉGIO LOSANGO DE PIUMHI (PIUMHI)
UPDATE schools SET inep_code = '310956' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO LOSANGO DE PIUMHI' AND UPPER(TRIM(city)) = 'PIUMHI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310956');

-- COLÉGIO PRESBITERIANO DE PIUMHI (PIUMHI)
UPDATE schools SET inep_code = '257664' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PRESBITERIANO DE PIUMHI' AND UPPER(TRIM(city)) = 'PIUMHI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '257664');

-- INSTITUTO PERFIL DE EDUCAÇÃO (PIUMHI)
UPDATE schools SET inep_code = '241776' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO PERFIL DE EDUCAÇÃO' AND UPPER(TRIM(city)) = 'PIUMHI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '241776');

-- INSTITUTO ELLOS DE EDUCAÇÃO (SÃO ROQUE DE MINAS)
UPDATE schools SET inep_code = '295345' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO ELLOS DE EDUCAÇÃO' AND UPPER(TRIM(city)) = 'SÃO ROQUE DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '295345');

-- COLÉGIO PÓLIS (CARMO DO PARANAÍBA)
UPDATE schools SET inep_code = '276227' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PÓLIS' AND UPPER(TRIM(city)) = 'CARMO DO PARANAÍBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '276227');

-- COLÉGIO EDUCAR (LAGAMAR)
UPDATE schools SET inep_code = '302422' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO EDUCAR' AND UPPER(TRIM(city)) = 'LAGAMAR' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '302422');

-- CENTRO POLITÉCNICO TREINAMENTO ENSINO E PESQUISA (PATOS DE MINAS)
UPDATE schools SET inep_code = '279048' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO POLITÉCNICO TREINAMENTO ENSINO E PESQUISA' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '279048');

-- COLÉGIO CIDADE DE PATOS DE MINAS (PATOS DE MINAS)
UPDATE schools SET inep_code = '321079' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CIDADE DE PATOS DE MINAS' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '321079');

-- COLÉGIO CORAÇÃO MATERNO (PATOS DE MINAS)
UPDATE schools SET inep_code = '305286' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CORAÇÃO MATERNO' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305286');

-- COLÉGIO FONSECA RODRIGUES (PATOS DE MINAS)
UPDATE schools SET inep_code = '123501' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO FONSECA RODRIGUES' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '123501');

-- COLÉGIO LEONARDO DA VINCI (PATOS DE MINAS)
UPDATE schools SET inep_code = '123544' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO LEONARDO DA VINCI' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '123544');

-- COLÉGIO MARISTA (PATOS DE MINAS)
UPDATE schools SET inep_code = '123510' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MARISTA' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '123510');

-- COLÉGIO NOSSA SENHORA DAS GRAÇAS (PATOS DE MINAS)
UPDATE schools SET inep_code = '123536' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO NOSSA SENHORA DAS GRAÇAS' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '123536');

-- COLÉGIO UNIVERSITÁRIO (PATOS DE MINAS)
UPDATE schools SET inep_code = '371696' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO UNIVERSITÁRIO' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '371696');

-- ESCOLA TÉCNICA DE PATOS DE MINAS (PATOS DE MINAS)
UPDATE schools SET inep_code = '364380' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA DE PATOS DE MINAS' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '364380');

-- INSTITUTO PRESBITERIANO DE EDUCAÇÃO (PATOS DE MINAS)
UPDATE schools SET inep_code = '281174' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO PRESBITERIANO DE EDUCAÇÃO' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '281174');

-- NÚCLEO INTEGRAL FORMAÇÃO E PESQUISA TECNICO PROFISSIONAL (PATOS DE MINAS)
UPDATE schools SET inep_code = '322024' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'NÚCLEO INTEGRAL FORMAÇÃO E PESQUISA TECNICO PROFISSIONAL' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322024');

-- SENAC UNIDADE DE ENSINO TÉCNICO - CFP PATOS DE MINAS (PATOS DE MINAS)
UPDATE schools SET inep_code = '321729' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAC UNIDADE DE ENSINO TÉCNICO - CFP PATOS DE MINAS' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '321729');

-- SENAI- CENTRO PROFISSIONAL ANÁVIO BRAZ QUEIROZ (PATOS DE MINAS)
UPDATE schools SET inep_code = '312347' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI- CENTRO PROFISSIONAL ANÁVIO BRAZ QUEIROZ' AND UPPER(TRIM(city)) = 'PATOS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312347');

-- CENTRO EDUCACIONAL PAULO FREIRE (RIO PARANAÍBA)
UPDATE schools SET inep_code = '355488' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL PAULO FREIRE' AND UPPER(TRIM(city)) = 'RIO PARANAÍBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '355488');

--  ESCOLA PARTICULAR GAMA – CENTRO EDUCACIONAL GARCIA MARQUES (SÃO GOTARDO)
UPDATE schools SET inep_code = '253324' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA PARTICULAR GAMA – CENTRO EDUCACIONAL GARCIA MARQUES' AND UPPER(TRIM(city)) = 'SÃO GOTARDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253324');

-- COLÉGIO DIMENSÃO (SÃO GOTARDO)
UPDATE schools SET inep_code = '260711' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DIMENSÃO' AND UPPER(TRIM(city)) = 'SÃO GOTARDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '260711');

-- COLÉGIO GAMA DE SÃO GOTARDO (SÃO GOTARDO)
UPDATE schools SET inep_code = '305294' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO GAMA DE SÃO GOTARDO' AND UPPER(TRIM(city)) = 'SÃO GOTARDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305294');

-- ETEC - SG ESCOLA TÉCNICA DE SÃO GOTARDO (SÃO GOTARDO)
UPDATE schools SET inep_code = '369306' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ETEC - SG ESCOLA TÉCNICA DE SÃO GOTARDO' AND UPPER(TRIM(city)) = 'SÃO GOTARDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369306');

-- FETEP - FUTURISTA ENSINO TÉCNICO PROFISSIONALIZANTE (SÃO GOTARDO)
UPDATE schools SET inep_code = '365076' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'FETEP - FUTURISTA ENSINO TÉCNICO PROFISSIONALIZANTE' AND UPPER(TRIM(city)) = 'SÃO GOTARDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '365076');

-- CENTRO EDUCACIONAL EDUQUE (TIROS)
UPDATE schools SET inep_code = '295108' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL EDUQUE' AND UPPER(TRIM(city)) = 'TIROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '295108');

-- SISTEMA PÓLIS DE ENSINO (GUIMARÂNIA)
UPDATE schools SET inep_code = '312584' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SISTEMA PÓLIS DE ENSINO' AND UPPER(TRIM(city)) = 'GUIMARÂNIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312584');

-- COLÉGIO ÁRCADE DE IBIÁ (IBIÁ)
UPDATE schools SET inep_code = '276260' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ÁRCADE DE IBIÁ' AND UPPER(TRIM(city)) = 'IBIÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '276260');

-- COLÉGIO NOVA DIMENSÃO (IBIÁ)
UPDATE schools SET inep_code = '215759' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO NOVA DIMENSÃO' AND UPPER(TRIM(city)) = 'IBIÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '215759');

-- CENTRO EDUCACIONAL CANTINHO DA ALEGRIA (IRAÍ DE MINAS)
UPDATE schools SET inep_code = '295868' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL CANTINHO DA ALEGRIA' AND UPPER(TRIM(city)) = 'IRAÍ DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '295868');

-- COLÉGIO ATENAS (PATROCÍNIO)
UPDATE schools SET inep_code = '200247' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ATENAS' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '200247');

-- COLÉGIO BERLAAR NOSSA SENHORA DO PATROCÍNIO (PATROCÍNIO)
UPDATE schools SET inep_code = '200212' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO BERLAAR NOSSA SENHORA DO PATROCÍNIO' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '200212');

-- COLÉGIO BIAS DE PRIENE (PATROCÍNIO)
UPDATE schools SET inep_code = '372463' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO BIAS DE PRIENE' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '372463');

-- COLÉGIO EDUCACIONAL ABC (PATROCÍNIO)
UPDATE schools SET inep_code = '223417' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO EDUCACIONAL ABC' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '223417');

-- COLÉGIO EDUCACIONAL CRIARTE (PATROCÍNIO)
UPDATE schools SET inep_code = '324876' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO EDUCACIONAL CRIARTE' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '324876');

-- COLÉGIO EDUCACIONAL CRIARTE (PATROCÍNIO)
UPDATE schools SET inep_code = '377120' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO EDUCACIONAL CRIARTE' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '377120');

-- COLÉGIO MONTEIRO LOBATO (PATROCÍNIO)
UPDATE schools SET inep_code = '325741' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MONTEIRO LOBATO' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '325741');

-- COLÉGIO PRISMA (PATROCÍNIO)
UPDATE schools SET inep_code = '277487' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PRISMA' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '277487');

-- ESCOLA AGROTÉCNICA SERGIO DE FREITAS PACHECO / EASFP (PATROCÍNIO)
UPDATE schools SET inep_code = '200239' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA AGROTÉCNICA SERGIO DE FREITAS PACHECO / EASFP' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '200239');

-- PEOPLE FORMAÇÃO COMPLETA (PATROCÍNIO)
UPDATE schools SET inep_code = '378372' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'PEOPLE FORMAÇÃO COMPLETA' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '378372');

-- UNIDADE DE ENSINO TÉCNICO DO CEP SENAC PATROCÍNIO (PATROCÍNIO)
UPDATE schools SET inep_code = '376574' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'UNIDADE DE ENSINO TÉCNICO DO CEP SENAC PATROCÍNIO' AND UPPER(TRIM(city)) = 'PATROCÍNIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '376574');

-- COLÉGIO SÃO JOÃO BATISTA (PIRAPORA)
UPDATE schools SET inep_code = '213896' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SÃO JOÃO BATISTA' AND UPPER(TRIM(city)) = 'PIRAPORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '213896');

-- COLÉGIO SÓLIDO - UNIDADE PIRAPORA (PIRAPORA)
UPDATE schools SET inep_code = '381101' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SÓLIDO - UNIDADE PIRAPORA' AND UPPER(TRIM(city)) = 'PIRAPORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '381101');

-- SENAI PIRAPORA CFP PIRAPORA (PIRAPORA)
UPDATE schools SET inep_code = '371092' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI PIRAPORA CFP PIRAPORA' AND UPPER(TRIM(city)) = 'PIRAPORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '371092');

-- COLÉGIO DARCÍLIA COIMBRA - UNIDADE VÁRZEA DA PALMA (VÁRZEA DA PALMA)
UPDATE schools SET inep_code = '379905' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DARCÍLIA COIMBRA - UNIDADE VÁRZEA DA PALMA' AND UPPER(TRIM(city)) = 'VÁRZEA DA PALMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '379905');

-- COLÉGIO DESTAQUE (VÁRZEA DA PALMA)
UPDATE schools SET inep_code = '223433' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DESTAQUE' AND UPPER(TRIM(city)) = 'VÁRZEA DA PALMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '223433');

-- SENAI CENTRO DE FORMAÇÃO JOAQUIM DE PAULA FERREIRA (VÁRZEA DA PALMA)
UPDATE schools SET inep_code = '325457' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI CENTRO DE FORMAÇÃO JOAQUIM DE PAULA FERREIRA' AND UPPER(TRIM(city)) = 'VÁRZEA DA PALMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '325457');

-- COLÉGIO JUNQUEIRA - UNIDADE I (ANDRADAS)
UPDATE schools SET inep_code = '272957' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO JUNQUEIRA - UNIDADE I' AND UPPER(TRIM(city)) = 'ANDRADAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '272957');

-- COLÉGIO JUNQUEIRA - UNIDADE II (ANDRADAS)
UPDATE schools SET inep_code = '343447' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO JUNQUEIRA - UNIDADE II' AND UPPER(TRIM(city)) = 'ANDRADAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '343447');

-- ESCOLA ADVENTISTA DE ANDRADAS (ANDRADAS)
UPDATE schools SET inep_code = '312860' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA ADVENTISTA DE ANDRADAS' AND UPPER(TRIM(city)) = 'ANDRADAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312860');

-- ESCOLA ULTRA (ANDRADAS)
UPDATE schools SET inep_code = '127833' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA ULTRA' AND UPPER(TRIM(city)) = 'ANDRADAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '127833');

-- ESCOLA ULTRA DE ENSINO MÉDIO E PROFISSIONAL (ANDRADAS)
UPDATE schools SET inep_code = '310808' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA ULTRA DE ENSINO MÉDIO E PROFISSIONAL' AND UPPER(TRIM(city)) = 'ANDRADAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310808');

-- INSTITUTO DE EDUCAÇÃO ALFA (ANDRADAS)
UPDATE schools SET inep_code = '127841' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO DE EDUCAÇÃO ALFA' AND UPPER(TRIM(city)) = 'ANDRADAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '127841');

-- INSTITUTO DE EDUCAÇÃO ALFA I (ANDRADAS)
UPDATE schools SET inep_code = '355356' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO DE EDUCAÇÃO ALFA I' AND UPPER(TRIM(city)) = 'ANDRADAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '355356');

-- LOGOS COLÉGIO E CURSO - FORMAÇÃO INTEGRAL (AREADO)
UPDATE schools SET inep_code = '127868' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'LOGOS COLÉGIO E CURSO - FORMAÇÃO INTEGRAL' AND UPPER(TRIM(city)) = 'AREADO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '127868');

-- CENTRO  EDUCACIONAL ANTÔNIO DE SOUZA GONÇALVES (BOTELHOS)
UPDATE schools SET inep_code = '305146' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO  EDUCACIONAL ANTÔNIO DE SOUZA GONÇALVES' AND UPPER(TRIM(city)) = 'BOTELHOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305146');

-- CEMA - CENTRO EDUCACIONAL MOURA ALMEIDA (MUZAMBINHO)
UPDATE schools SET inep_code = '358436' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CEMA - CENTRO EDUCACIONAL MOURA ALMEIDA' AND UPPER(TRIM(city)) = 'MUZAMBINHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '358436');

-- COLÉGIO DELTA PROFESSORA ANTÔNIA FERNANDES (MUZAMBINHO)
UPDATE schools SET inep_code = '342416' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DELTA PROFESSORA ANTÔNIA FERNANDES' AND UPPER(TRIM(city)) = 'MUZAMBINHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342416');

-- COLÉGIO LYCEU (MUZAMBINHO)
UPDATE schools SET inep_code = '230642' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO LYCEU' AND UPPER(TRIM(city)) = 'MUZAMBINHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '230642');

-- CENTRO EDUCACIONAL NOVA RESENDE (NOVA RESENDE)
UPDATE schools SET inep_code = '349690' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL NOVA RESENDE' AND UPPER(TRIM(city)) = 'NOVA RESENDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349690');

-- CENTRO EDUCACIONAL INOVAÇÃO (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '310841' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL INOVAÇÃO' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310841');

-- CENTRO EDUCACIONAL POÇOS (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '310191' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL POÇOS' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310191');

-- COLÉGIO JESUS MARIA JOSÉ (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '127965' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO JESUS MARIA JOSÉ' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '127965');

-- COLÉGIO NINI MOURÃO (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '127949' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO NINI MOURÃO' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '127949');

-- COLÉGIO PIO XII (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '127973' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PIO XII' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '127973');

-- COLÉGIO SÃO JOSÉ DA IMACULADA CONCEIÇÃO (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '371831' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SÃO JOSÉ DA IMACULADA CONCEIÇÃO' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '371831');

-- COLÉGIO SETE DE SETEMBRO (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '128031' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SETE DE SETEMBRO' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128031');

-- ESC PROFIS DOM BOSCO (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '128023' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESC PROFIS DOM BOSCO' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128023');

-- ESCOLA CRIATIVA IDADE SISTEMA EDUCACIONAL (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '245968' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA CRIATIVA IDADE SISTEMA EDUCACIONAL' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '245968');

-- ESCOLA LUMIAR (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '372307' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA LUMIAR' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '372307');

-- ESCOLA RUTH SEE (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '378330' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA RUTH SEE' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '378330');

-- ESCOLA SANTA ROSA (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '340839' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SANTA ROSA' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '340839');

-- INSTITUTO EDUCACIONAL SÃO JOÃO DA ESCÓCIA (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '128058' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL SÃO JOÃO DA ESCÓCIA' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128058');

-- REDE PROSPER POÇOS DE CALDAS (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '222976' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'REDE PROSPER POÇOS DE CALDAS' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '222976');

-- SENAC UNIDADE DE ENSINO TÉCNICO - CFP POÇOS DE CALDAS (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '313459' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAC UNIDADE DE ENSINO TÉCNICO - CFP POÇOS DE CALDAS' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '313459');

-- SENAI CENTRO DE FORMAÇÃO PROFISSIONAL JOÃO MOREIRA SALLES (POÇOS DE CALDAS)
UPDATE schools SET inep_code = '259454' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI CENTRO DE FORMAÇÃO PROFISSIONAL JOÃO MOREIRA SALLES' AND UPPER(TRIM(city)) = 'POÇOS DE CALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '259454');

-- ESCOLA FAMÍLIA AGRÍCOLA PURIS DE ARAPONGA (ARAPONGA)
UPDATE schools SET inep_code = '343064' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA FAMÍLIA AGRÍCOLA PURIS DE ARAPONGA' AND UPPER(TRIM(city)) = 'ARAPONGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '343064');

-- ESCOLA FAMÍLIA AGRÍCOLA DE JEQUERI (JEQUERI)
UPDATE schools SET inep_code = '312631' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA FAMÍLIA AGRÍCOLA DE JEQUERI' AND UPPER(TRIM(city)) = 'JEQUERI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312631');

-- CENTRO EDUCACIONAL MACIEL AGUIAR PRIMEIRO - UNIDADE II (PONTE NOVA)
UPDATE schools SET inep_code = '370274' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL MACIEL AGUIAR PRIMEIRO - UNIDADE II' AND UPPER(TRIM(city)) = 'PONTE NOVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '370274');

-- CENTRO EDUCACIONAL MACIEL AGUIAR PRIMEIRO-CEMAP (PONTE NOVA)
UPDATE schools SET inep_code = '259527' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL MACIEL AGUIAR PRIMEIRO-CEMAP' AND UPPER(TRIM(city)) = 'PONTE NOVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '259527');

-- CENTRO TÉCNICO PROFISSIONAL DE PONTE NOVA (PONTE NOVA)
UPDATE schools SET inep_code = '379980' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO TÉCNICO PROFISSIONAL DE PONTE NOVA' AND UPPER(TRIM(city)) = 'PONTE NOVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '379980');

-- COLÉGIO ATHENAS EQUIPE DE PONTE NOVA (PONTE NOVA)
UPDATE schools SET inep_code = '231088' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ATHENAS EQUIPE DE PONTE NOVA' AND UPPER(TRIM(city)) = 'PONTE NOVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '231088');

-- CÓLEGIO CERP (PONTE NOVA)
UPDATE schools SET inep_code = '363090' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CÓLEGIO CERP' AND UPPER(TRIM(city)) = 'PONTE NOVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '363090');

-- ESCOLA NOSSA SENHORA AUXILIADORA (PONTE NOVA)
UPDATE schools SET inep_code = '133612' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA NOSSA SENHORA AUXILIADORA' AND UPPER(TRIM(city)) = 'PONTE NOVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '133612');

-- INSTITUTO MONTESSORI (PONTE NOVA)
UPDATE schools SET inep_code = '133621' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO MONTESSORI' AND UPPER(TRIM(city)) = 'PONTE NOVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '133621');

-- COLÉGIO DARWIN DE RAUL SOARES (RAUL SOARES)
UPDATE schools SET inep_code = '325694' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DARWIN DE RAUL SOARES' AND UPPER(TRIM(city)) = 'RAUL SOARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '325694');

-- COLÉGIO ATHENAS EQUIPE DE RIO CASCA (RIO CASCA)
UPDATE schools SET inep_code = '239526' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ATHENAS EQUIPE DE RIO CASCA' AND UPPER(TRIM(city)) = 'RIO CASCA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '239526');

-- COLÉGIO EDUCAR DE RIO CASCA (RIO CASCA)
UPDATE schools SET inep_code = '376299' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO EDUCAR DE RIO CASCA' AND UPPER(TRIM(city)) = 'RIO CASCA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '376299');

-- ESCOLA FAMÍLIA AGRÍCOLA DE CAMÕES (SEM-PEIXE)
UPDATE schools SET inep_code = '277991' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA FAMÍLIA AGRÍCOLA DE CAMÕES' AND UPPER(TRIM(city)) = 'SEM-PEIXE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '277991');

-- CENTRO EDUCACIONAL RAINHA DA PAZ (TEIXEIRAS)
UPDATE schools SET inep_code = '268682' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL RAINHA DA PAZ' AND UPPER(TRIM(city)) = 'TEIXEIRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '268682');

-- CENTRO EDUCACIONAL COEDUCAR (VIÇOSA)
UPDATE schools SET inep_code = '246395' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL COEDUCAR' AND UPPER(TRIM(city)) = 'VIÇOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246395');

-- CENTRO EDUCACIONAL PRÓ-EFEITO (VIÇOSA)
UPDATE schools SET inep_code = '253332' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL PRÓ-EFEITO' AND UPPER(TRIM(city)) = 'VIÇOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253332');

-- CENTRO REFERENCIAL DE ENSINO EM SAÚDE (VIÇOSA)
UPDATE schools SET inep_code = '368040' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO REFERENCIAL DE ENSINO EM SAÚDE' AND UPPER(TRIM(city)) = 'VIÇOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368040');

-- COLÉGIO ÁGORA (VIÇOSA)
UPDATE schools SET inep_code = '242233' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ÁGORA' AND UPPER(TRIM(city)) = 'VIÇOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '242233');

-- COLÉGIO ÂNGULO DE VIÇOSA (VIÇOSA)
UPDATE schools SET inep_code = '242241' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ÂNGULO DE VIÇOSA' AND UPPER(TRIM(city)) = 'VIÇOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '242241');

-- COLÉGIO CIDADE DE VIÇOSA (VIÇOSA)
UPDATE schools SET inep_code = '380202' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CIDADE DE VIÇOSA' AND UPPER(TRIM(city)) = 'VIÇOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '380202');

-- COLÉGIO EQUIPE (VIÇOSA)
UPDATE schools SET inep_code = '133680' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO EQUIPE' AND UPPER(TRIM(city)) = 'VIÇOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '133680');

-- COLÉGIO NOSSA SENHORA DO CARMO (VIÇOSA)
UPDATE schools SET inep_code = '133701' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO NOSSA SENHORA DO CARMO' AND UPPER(TRIM(city)) = 'VIÇOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '133701');

-- COLÉGIO ÔMEGA (VIÇOSA)
UPDATE schools SET inep_code = '371971' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ÔMEGA' AND UPPER(TRIM(city)) = 'VIÇOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '371971');

-- COLÉGIO PASSO A PASSO (VIÇOSA)
UPDATE schools SET inep_code = '220043' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PASSO A PASSO' AND UPPER(TRIM(city)) = 'VIÇOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '220043');

-- ESCOLA TÉCNICA ÂNCORA (VIÇOSA)
UPDATE schools SET inep_code = '314501' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA ÂNCORA' AND UPPER(TRIM(city)) = 'VIÇOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '314501');

-- EVATA -  EDUCAÇÃO AVANÇADA (VIÇOSA)
UPDATE schools SET inep_code = '324418' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EVATA -  EDUCAÇÃO AVANÇADA' AND UPPER(TRIM(city)) = 'VIÇOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '324418');

-- CENTRO PAULISTA DE ESTUDOS EM AGRONEGÓCIO (BOM REPOUSO)
UPDATE schools SET inep_code = '379859' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO PAULISTA DE ESTUDOS EM AGRONEGÓCIO' AND UPPER(TRIM(city)) = 'BOM REPOUSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '379859');

-- ESCOLA WASHINGTON CÁSSIO MARIANO (BOM REPOUSO)
UPDATE schools SET inep_code = '255459' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA WASHINGTON CÁSSIO MARIANO' AND UPPER(TRIM(city)) = 'BOM REPOUSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '255459');

-- CENTRO EDUCACIONAL MARANATHA (CAMANDUCAIA)
UPDATE schools SET inep_code = '292524' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL MARANATHA' AND UPPER(TRIM(city)) = 'CAMANDUCAIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '292524');

-- CENTRO EDUCATIVO NOVA VIDA (CAMANDUCAIA)
UPDATE schools SET inep_code = '347850' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCATIVO NOVA VIDA' AND UPPER(TRIM(city)) = 'CAMANDUCAIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '347850');

-- CENTRO EDUCATIVO VIDA NOVA (CAMANDUCAIA)
UPDATE schools SET inep_code = '357251' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCATIVO VIDA NOVA' AND UPPER(TRIM(city)) = 'CAMANDUCAIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '357251');

-- COLÉGIO NILTA D'ONOFRIO DE CARVALHO (CAMBUÍ)
UPDATE schools SET inep_code = '343889' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO NILTA D''ONOFRIO DE CARVALHO' AND UPPER(TRIM(city)) = 'CAMBUÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '343889');

-- ESCOLA ANA BUENO (CAMBUÍ)
UPDATE schools SET inep_code = '235725' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA ANA BUENO' AND UPPER(TRIM(city)) = 'CAMBUÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '235725');

-- ESCOLA DOCE SABER (CONGONHAL)
UPDATE schools SET inep_code = '306720' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DOCE SABER' AND UPPER(TRIM(city)) = 'CONGONHAL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '306720');

-- CENTRO DE EDUCAÇÃO FUTURO (EXTREMA)
UPDATE schools SET inep_code = '250058' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE EDUCAÇÃO FUTURO' AND UPPER(TRIM(city)) = 'EXTREMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '250058');

-- CENTRO DE FORMAÇAO PROFISSIONAL JANEZ HLEBANJA (EXTREMA)
UPDATE schools SET inep_code = '348252' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE FORMAÇAO PROFISSIONAL JANEZ HLEBANJA' AND UPPER(TRIM(city)) = 'EXTREMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '348252');

-- CENTRO EDUCACIONAL TERRA - UNIDADE CENTRO (EXTREMA)
UPDATE schools SET inep_code = '358681' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL TERRA - UNIDADE CENTRO' AND UPPER(TRIM(city)) = 'EXTREMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '358681');

-- CENTRO MÉDIO PROFISSIONALIZANTE DE EXTREMA - CEMPRE (EXTREMA)
UPDATE schools SET inep_code = '370746' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO MÉDIO PROFISSIONALIZANTE DE EXTREMA - CEMPRE' AND UPPER(TRIM(city)) = 'EXTREMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '370746');

-- NÚCLEO DE EDUCAÇÃO BOM PASTOR (EXTREMA)
UPDATE schools SET inep_code = '264342' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'NÚCLEO DE EDUCAÇÃO BOM PASTOR' AND UPPER(TRIM(city)) = 'EXTREMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '264342');

-- PRIVEST -  SISTEMA COC DE ENSINO (EXTREMA)
UPDATE schools SET inep_code = '250040' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'PRIVEST -  SISTEMA COC DE ENSINO' AND UPPER(TRIM(city)) = 'EXTREMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '250040');

-- ESCOLA YOLANDA FERREIRA FRANCO (IPUIÚNA)
UPDATE schools SET inep_code = '279978' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA YOLANDA FERREIRA FRANCO' AND UPPER(TRIM(city)) = 'IPUIÚNA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '279978');

-- COLÉGIO APLICATIVO (JACUTINGA)
UPDATE schools SET inep_code = '365742' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO APLICATIVO' AND UPPER(TRIM(city)) = 'JACUTINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '365742');

-- COLÉGIO EDUCAÇÃO E CULTURA (JACUTINGA)
UPDATE schools SET inep_code = '230898' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO EDUCAÇÃO E CULTURA' AND UPPER(TRIM(city)) = 'JACUTINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '230898');

-- COLÉGIO INTEGRADO JEAN PIAGET (JACUTINGA)
UPDATE schools SET inep_code = '302520' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO INTEGRADO JEAN PIAGET' AND UPPER(TRIM(city)) = 'JACUTINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '302520');

-- COLÉGIO MONTE SIONENSE (MONTE SIÃO)
UPDATE schools SET inep_code = '256927' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MONTE SIONENSE' AND UPPER(TRIM(city)) = 'MONTE SIÃO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '256927');

-- COLÉGIO VILLA LOBOS - UNIDADE MONTE SIÃO (MONTE SIÃO)
UPDATE schools SET inep_code = '319091' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO VILLA LOBOS - UNIDADE MONTE SIÃO' AND UPPER(TRIM(city)) = 'MONTE SIÃO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '319091');

-- COLÉGIO ABNARA (OURO FINO)
UPDATE schools SET inep_code = '354163' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ABNARA' AND UPPER(TRIM(city)) = 'OURO FINO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '354163');

-- COLÉGIO E CURSO MÁXIMUS (OURO FINO)
UPDATE schools SET inep_code = '340030' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO E CURSO MÁXIMUS' AND UPPER(TRIM(city)) = 'OURO FINO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '340030');

-- ESCOLA ROCHEL (OURO FINO)
UPDATE schools SET inep_code = '235776' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA ROCHEL' AND UPPER(TRIM(city)) = 'OURO FINO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '235776');

-- CENTRO EDUCACIONAL EUROPA (POUSO ALEGRE)
UPDATE schools SET inep_code = '368520' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL EUROPA' AND UPPER(TRIM(city)) = 'POUSO ALEGRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368520');

-- CENTRO EDUCACIONAL REIS MAGOS (POUSO ALEGRE)
UPDATE schools SET inep_code = '290963' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL REIS MAGOS' AND UPPER(TRIM(city)) = 'POUSO ALEGRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '290963');

-- CENTRO EDUCACIONAL RENOVAÇÃO (POUSO ALEGRE)
UPDATE schools SET inep_code = '327026' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL RENOVAÇÃO' AND UPPER(TRIM(city)) = 'POUSO ALEGRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '327026');

-- COLÉGIO ADVENTISTA DE POUSO ALEGRE (POUSO ALEGRE)
UPDATE schools SET inep_code = '372838' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ADVENTISTA DE POUSO ALEGRE' AND UPPER(TRIM(city)) = 'POUSO ALEGRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '372838');

-- COLÉGIO APOGEU - UNIDADE V (POUSO ALEGRE)
UPDATE schools SET inep_code = '368385' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO APOGEU - UNIDADE V' AND UPPER(TRIM(city)) = 'POUSO ALEGRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368385');

-- COLÉGIO FÊNIX (POUSO ALEGRE)
UPDATE schools SET inep_code = '358266' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO FÊNIX' AND UPPER(TRIM(city)) = 'POUSO ALEGRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '358266');

-- COLÉGIO FOCH (POUSO ALEGRE)
UPDATE schools SET inep_code = '369748' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO FOCH' AND UPPER(TRIM(city)) = 'POUSO ALEGRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369748');

-- COLÉGIO JOÃO PAULO II (POUSO ALEGRE)
UPDATE schools SET inep_code = '210307' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO JOÃO PAULO II' AND UPPER(TRIM(city)) = 'POUSO ALEGRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '210307');

-- COLÉGIO TÉCNICO ENDEX (POUSO ALEGRE)
UPDATE schools SET inep_code = '375349' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TÉCNICO ENDEX' AND UPPER(TRIM(city)) = 'POUSO ALEGRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '375349');

-- COLÉGIO VALE DO SAPUCAÍ (POUSO ALEGRE)
UPDATE schools SET inep_code = '343781' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO VALE DO SAPUCAÍ' AND UPPER(TRIM(city)) = 'POUSO ALEGRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '343781');

-- ESCOLA SESI ORLANDO CHIARINI (POUSO ALEGRE)
UPDATE schools SET inep_code = '258393' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SESI ORLANDO CHIARINI' AND UPPER(TRIM(city)) = 'POUSO ALEGRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '258393');

-- ETEMG - ESCOLA TÉCNICA MINAS GERIAS (POUSO ALEGRE)
UPDATE schools SET inep_code = '368873' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ETEMG - ESCOLA TÉCNICA MINAS GERIAS' AND UPPER(TRIM(city)) = 'POUSO ALEGRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368873');

-- MAPLE BEAR CANADIAN SCHOOL (POUSO ALEGRE)
UPDATE schools SET inep_code = '356514' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'MAPLE BEAR CANADIAN SCHOOL' AND UPPER(TRIM(city)) = 'POUSO ALEGRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '356514');

-- SENAC UNIDADE DE ENSINO TÉCNICO - CFP POUSO ALEGRE (POUSO ALEGRE)
UPDATE schools SET inep_code = '338958' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAC UNIDADE DE ENSINO TÉCNICO - CFP POUSO ALEGRE' AND UPPER(TRIM(city)) = 'POUSO ALEGRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338958');

-- SENAI CENTRO DE FORMAÇÃO  PROFISSIONAL ORLANDO CHIARINII (POUSO ALEGRE)
UPDATE schools SET inep_code = '268500' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI CENTRO DE FORMAÇÃO  PROFISSIONAL ORLANDO CHIARINII' AND UPPER(TRIM(city)) = 'POUSO ALEGRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '268500');

-- INST PRESBITERIANO (SANTA RITA DO SAPUCAÍ)
UPDATE schools SET inep_code = '262005' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INST PRESBITERIANO' AND UPPER(TRIM(city)) = 'SANTA RITA DO SAPUCAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '262005');

-- SENAI CENTRO DE DESENVIMENTO TECNOLÓGICO STEFAN BOGDAN SALEJ (SANTA RITA DO SAPUCAÍ)
UPDATE schools SET inep_code = '320498' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI CENTRO DE DESENVIMENTO TECNOLÓGICO STEFAN BOGDAN SALEJ' AND UPPER(TRIM(city)) = 'SANTA RITA DO SAPUCAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '320498');

-- CENTRO DE EDUCAÇÃO INTEGRADA PAULO FREIRE (BOM SUCESSO)
UPDATE schools SET inep_code = '365866' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE EDUCAÇÃO INTEGRADA PAULO FREIRE' AND UPPER(TRIM(city)) = 'BOM SUCESSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '365866');

-- CENTRO EDUCACIONAL WANDERLEY ARRUDA - CEWA (DORES DE CAMPOS)
UPDATE schools SET inep_code = '304395' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL WANDERLEY ARRUDA - CEWA' AND UPPER(TRIM(city)) = 'DORES DE CAMPOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '304395');

-- ESCOLA DE ENSINO TÉCNICO CARVALHO CHIARINI (NAZARENO)
UPDATE schools SET inep_code = '337510' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DE ENSINO TÉCNICO CARVALHO CHIARINI' AND UPPER(TRIM(city)) = 'NAZARENO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '337510');

--  CENTRO FORMAÇÃO PROFISSIONAL SÍLVIO ASSUNÇÃO TEIXEIRA-SENAI (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '259462' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO FORMAÇÃO PROFISSIONAL SÍLVIO ASSUNÇÃO TEIXEIRA-SENAI' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '259462');

-- CENTRO EDUCACIONAL FREI SERÁFICO (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '245976' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL FREI SERÁFICO' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '245976');

-- COLÉGIO CAMINHO DO SOL (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '232602' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CAMINHO DO SOL' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '232602');

-- COLÉGIO IMPACTO (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '376817' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO IMPACTO' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '376817');

-- COLÉGIO NOSSA SENHORA DAS DORES (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '136760' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO NOSSA SENHORA DAS DORES' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '136760');

-- COLÉGIO REVISÃO (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '326577' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO REVISÃO' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '326577');

-- COMPANHIA EDUCACIONAL ENLACE (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '281701' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COMPANHIA EDUCACIONAL ENLACE' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '281701');

-- ESCOLA DE EDUCAÇÃO BÁSICA E PROFISSIONAL DONA SINHÁ NEVES (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '136816' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DE EDUCAÇÃO BÁSICA E PROFISSIONAL DONA SINHÁ NEVES' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '136816');

-- ESCOLA DE SAÚDE ANTONINA NEVES (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '250783' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DE SAÚDE ANTONINA NEVES' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '250783');

-- ESCOLA SESI DOM BOSCO (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '136727' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SESI DOM BOSCO' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '136727');

-- INSTITUTO AUXILIADORA (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '136751' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO AUXILIADORA' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '136751');

-- SERVIÇO NACIONAL DE APRENDIZAGEM COMERCIAL - SENAC SÃO JOÃO DEL REI (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '363103' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SERVIÇO NACIONAL DE APRENDIZAGEM COMERCIAL - SENAC SÃO JOÃO DEL REI' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '363103');

-- CENTRO EDUCACIONAL CORY (ARCEBURGO)
UPDATE schools SET inep_code = '317161' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL CORY' AND UPPER(TRIM(city)) = 'ARCEBURGO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '317161');

-- ESCOLA ANA DE MELO AZEVEDO (CÁSSIA)
UPDATE schools SET inep_code = '210471' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA ANA DE MELO AZEVEDO' AND UPPER(TRIM(city)) = 'CÁSSIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '210471');

-- CENTRO EDUCACIONAL PRIMEIROS PASSOS (GUARANÉSIA)
UPDATE schools SET inep_code = '333395' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL PRIMEIROS PASSOS' AND UPPER(TRIM(city)) = 'GUARANÉSIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '333395');

-- COLÉGIO ALTERNATIVO (GUARANÉSIA)
UPDATE schools SET inep_code = '261971' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ALTERNATIVO' AND UPPER(TRIM(city)) = 'GUARANÉSIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '261971');

-- ACADEMIA DE COMÉRCIO SÃO JOSÉ (GUAXUPÉ)
UPDATE schools SET inep_code = '140163' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ACADEMIA DE COMÉRCIO SÃO JOSÉ' AND UPPER(TRIM(city)) = 'GUAXUPÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140163');

-- COLÉGIO BORA PASSAR (GUAXUPÉ)
UPDATE schools SET inep_code = '376078' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO BORA PASSAR' AND UPPER(TRIM(city)) = 'GUAXUPÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '376078');

-- COLÉGIO DOM INÁCIO (GUAXUPÉ)
UPDATE schools SET inep_code = '140171' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DOM INÁCIO' AND UPPER(TRIM(city)) = 'GUAXUPÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140171');

-- COLÉGIO OBJETIVO DE GUAXUPÉ UNIDADE I (GUAXUPÉ)
UPDATE schools SET inep_code = '240443' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO OBJETIVO DE GUAXUPÉ UNIDADE I' AND UPPER(TRIM(city)) = 'GUAXUPÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '240443');

-- COLÉGIO OBJETIVO DE GUAXUPÉ UNIDADE II (GUAXUPÉ)
UPDATE schools SET inep_code = '316687' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO OBJETIVO DE GUAXUPÉ UNIDADE II' AND UPPER(TRIM(city)) = 'GUAXUPÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '316687');

-- COLÉGIO PHD (GUAXUPÉ)
UPDATE schools SET inep_code = '364533' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PHD' AND UPPER(TRIM(city)) = 'GUAXUPÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '364533');

-- ESCOLA INTERATIVA (GUAXUPÉ)
UPDATE schools SET inep_code = '280071' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA INTERATIVA' AND UPPER(TRIM(city)) = 'GUAXUPÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '280071');

-- SENAC- CENTRO DE FORMAÇÃO PROFISSIONAL DE GUAXUPÉ (GUAXUPÉ)
UPDATE schools SET inep_code = '320200' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAC- CENTRO DE FORMAÇÃO PROFISSIONAL DE GUAXUPÉ' AND UPPER(TRIM(city)) = 'GUAXUPÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '320200');

-- COLÉGIO EDUC IBIRACI (IBIRACI)
UPDATE schools SET inep_code = '347744' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO EDUC IBIRACI' AND UPPER(TRIM(city)) = 'IBIRACI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '347744');

-- ESCOLA NOVA ARTE & CIA (ITAMOGI)
UPDATE schools SET inep_code = '295078' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA NOVA ARTE & CIA' AND UPPER(TRIM(city)) = 'ITAMOGI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '295078');

-- COLÉGIO EDUCACIONAL DE ITAÚ DE MINAS (ITAÚ DE MINAS)
UPDATE schools SET inep_code = '341398' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO EDUCACIONAL DE ITAÚ DE MINAS' AND UPPER(TRIM(city)) = 'ITAÚ DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '341398');

-- COLÉGIO INTERATIVO (ITAÚ DE MINAS)
UPDATE schools SET inep_code = '332402' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO INTERATIVO' AND UPPER(TRIM(city)) = 'ITAÚ DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '332402');

-- ESCOLA DEGRAUS (MONTE SANTO DE MINAS)
UPDATE schools SET inep_code = '231916' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DEGRAUS' AND UPPER(TRIM(city)) = 'MONTE SANTO DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '231916');

-- ESCOLA NOVA CRIANÇA E CIA (MONTE SANTO DE MINAS)
UPDATE schools SET inep_code = '247251' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA NOVA CRIANÇA E CIA' AND UPPER(TRIM(city)) = 'MONTE SANTO DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '247251');

-- CENTRO DE EDUCAÇÃO PROFISSIONAL DO SUDOESTE MINEIRO (SÃO SEBASTIÃO DO PARAÍSO)
UPDATE schools SET inep_code = '315958' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE EDUCAÇÃO PROFISSIONAL DO SUDOESTE MINEIRO' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '315958');

-- COLÉGIO CRESCER (SÃO SEBASTIÃO DO PARAÍSO)
UPDATE schools SET inep_code = '256943' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CRESCER' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '256943');

-- COLÉGIO GALILEU (SÃO SEBASTIÃO DO PARAÍSO)
UPDATE schools SET inep_code = '281883' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO GALILEU' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '281883');

-- COLÉGIO NESFA-NÚCLEO EDUCACIONAL SÃO FRANCISCO DE ASSIS (SÃO SEBASTIÃO DO PARAÍSO)
UPDATE schools SET inep_code = '296139' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO NESFA-NÚCLEO EDUCACIONAL SÃO FRANCISCO DE ASSIS' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '296139');

-- COLÉGIO OBJETIVO DE SÃO SEBASTIÃO DO PARAÍSO NHNEC (SÃO SEBASTIÃO DO PARAÍSO)
UPDATE schools SET inep_code = '316644' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO OBJETIVO DE SÃO SEBASTIÃO DO PARAÍSO NHNEC' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '316644');

-- COLÉGIO OBJETIVO DE SÃO SEBASTIÃO PARAÍSO-NHN (SÃO SEBASTIÃO DO PARAÍSO)
UPDATE schools SET inep_code = '230669' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO OBJETIVO DE SÃO SEBASTIÃO PARAÍSO-NHN' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '230669');

-- COLÉGIO PAULA FRASSINETTI (SÃO SEBASTIÃO DO PARAÍSO)
UPDATE schools SET inep_code = '140252' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PAULA FRASSINETTI' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140252');

-- COLÉGIO TESLA - SISTEMA MACKENZIE DE ENSINO (SÃO SEBASTIÃO DO PARAÍSO)
UPDATE schools SET inep_code = '376264' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TESLA - SISTEMA MACKENZIE DE ENSINO' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '376264');

-- ESCOLA CAIXINHA DE SURPRESA (SÃO SEBASTIÃO DO PARAÍSO)
UPDATE schools SET inep_code = '298255' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA CAIXINHA DE SURPRESA' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '298255');

-- SENAI CENTRO DE FORMAÇÃO PROFISSIONAL MONSENHOR JERÔNIMO MANCINI (SÃO SEBASTIÃO DO PARAÍSO)
UPDATE schools SET inep_code = '358797' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI CENTRO DE FORMAÇÃO PROFISSIONAL MONSENHOR JERÔNIMO MANCINI' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '358797');

-- COLÉGIO CENECISTA BERNARDO MASCARENHAS (CAETANÓPOLIS)
UPDATE schools SET inep_code = '145548' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CENECISTA BERNARDO MASCARENHAS' AND UPPER(TRIM(city)) = 'CAETANÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '145548');

-- C EDUC NOSSO MUNDO (MATOZINHOS)
UPDATE schools SET inep_code = '278050' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'C EDUC NOSSO MUNDO' AND UPPER(TRIM(city)) = 'MATOZINHOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '278050');

-- EDUCACIONAL ALTERNATIVA (MATOZINHOS)
UPDATE schools SET inep_code = '239534' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EDUCACIONAL ALTERNATIVA' AND UPPER(TRIM(city)) = 'MATOZINHOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '239534');

-- EDUCANDÁRIO CECÍLIA MEIRELES (PAPAGAIOS)
UPDATE schools SET inep_code = '254118' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EDUCANDÁRIO CECÍLIA MEIRELES' AND UPPER(TRIM(city)) = 'PAPAGAIOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '254118');

-- COLEGIO NOSSA SRA DO CARMO (PARAOPEBA)
UPDATE schools SET inep_code = '230715' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLEGIO NOSSA SRA DO CARMO' AND UPPER(TRIM(city)) = 'PARAOPEBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '230715');

-- INSTITUTO DE EDUCAÇÃO SANTA MARIA (POMPÉU)
UPDATE schools SET inep_code = '259764' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO DE EDUCAÇÃO SANTA MARIA' AND UPPER(TRIM(city)) = 'POMPÉU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '259764');

-- CEFAP- CENTRO DE FORMAÇÃO  E APERFEIÇOAMENTO PROFISSIONAL (SETE LAGOAS)
UPDATE schools SET inep_code = '312363' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CEFAP- CENTRO DE FORMAÇÃO  E APERFEIÇOAMENTO PROFISSIONAL' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312363');

-- COLÉGIO ALPHA (SETE LAGOAS)
UPDATE schools SET inep_code = '357154' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ALPHA' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '357154');

-- COLÉGIO ÂNGULO DE SETE LAGOAS (SETE LAGOAS)
UPDATE schools SET inep_code = '278033' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ÂNGULO DE SETE LAGOAS' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '278033');

-- COLÉGIO BATISTA MINEIRO - UNIDADE SETE LAGOAS (SETE LAGOAS)
UPDATE schools SET inep_code = '374202' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO BATISTA MINEIRO - UNIDADE SETE LAGOAS' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '374202');

-- COLÉGIO CAETANO (SETE LAGOAS)
UPDATE schools SET inep_code = '334049' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CAETANO' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '334049');

-- COLÉGIO ELITE MASTER (SETE LAGOAS)
UPDATE schools SET inep_code = '367672' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ELITE MASTER' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '367672');

-- COLÉGIO FRANCISCANO REGINA PACIS (SETE LAGOAS)
UPDATE schools SET inep_code = '145734' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO FRANCISCANO REGINA PACIS' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '145734');

-- COLÉGIO IMPULSO (SETE LAGOAS)
UPDATE schools SET inep_code = '260908' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO IMPULSO' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '260908');

-- COLÉGIO LAIS FARNETTI (SETE LAGOAS)
UPDATE schools SET inep_code = '335746' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO LAIS FARNETTI' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '335746');

-- COLÉGIO PROFESSOR ROBERTO HERBSTER GUSMÃO (SETE LAGOAS)
UPDATE schools SET inep_code = '361500' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PROFESSOR ROBERTO HERBSTER GUSMÃO' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '361500');

-- COLÉGIO PROMOVE DE SETE LAGOAS (SETE LAGOAS)
UPDATE schools SET inep_code = '368687' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PROMOVE DE SETE LAGOAS' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368687');

-- COLÉGIO RUTHERFORD (SETE LAGOAS)
UPDATE schools SET inep_code = '379719' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO RUTHERFORD' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '379719');