-- EE ENGENHEIRO AMARO LANARI JÚNIOR (IPATINGA)
UPDATE schools SET inep_code = '191183' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ENGENHEIRO AMARO LANARI JÚNIOR' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191183');

-- EE ENGENHEIRO MÁRCIO AGUIAR DA CUNHA (IPATINGA)
UPDATE schools SET inep_code = '191043' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ENGENHEIRO MÁRCIO AGUIAR DA CUNHA' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191043');

-- EE GERALDO GOMES RIBEIRO (IPATINGA)
UPDATE schools SET inep_code = '191205' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GERALDO GOMES RIBEIRO' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191205');

-- EE HAYDÉE MARIA IMACULADA SCHITTINI (IPATINGA)
UPDATE schools SET inep_code = '191159' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE HAYDÉE MARIA IMACULADA SCHITTINI' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191159');

-- EE JOÃO WALMICK (IPATINGA)
UPDATE schools SET inep_code = '191078' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO WALMICK' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191078');

-- EE JOÃO XXIII (IPATINGA)
UPDATE schools SET inep_code = '191060' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO XXIII' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191060');

-- EE LAURA XAVIER SANTANA (IPATINGA)
UPDATE schools SET inep_code = '191001' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LAURA XAVIER SANTANA' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191001');

-- EE MANOEL IZÍDIO (IPATINGA)
UPDATE schools SET inep_code = '191086' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MANOEL IZÍDIO' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191086');

-- EE MANOELA SOARES BICALHO (IPATINGA)
UPDATE schools SET inep_code = '191264' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MANOELA SOARES BICALHO' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191264');

-- EE MAURÍLIO ALBANESE NOVAES (IPATINGA)
UPDATE schools SET inep_code = '191124' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MAURÍLIO ALBANESE NOVAES' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191124');

-- EE NACIF SELIM DE SALES (IPATINGA)
UPDATE schools SET inep_code = '191213' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NACIF SELIM DE SALES' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191213');

-- EE NILZA LUZIA DE SOUZA BUTTA (IPATINGA)
UPDATE schools SET inep_code = '217310' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NILZA LUZIA DE SOUZA BUTTA' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217310');

-- EE PROFESSORA ELZA DE OLIVEIRA LAGE (IPATINGA)
UPDATE schools SET inep_code = '191299' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ELZA DE OLIVEIRA LAGE' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191299');

-- EE PROFESSORA MARIA ANTONIETA (IPATINGA)
UPDATE schools SET inep_code = '191116' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA ANTONIETA' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191116');

-- EE SELIM JOSÉ DE SALLES (IPATINGA)
UPDATE schools SET inep_code = '191256' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SELIM JOSÉ DE SALLES' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191256');

-- EE SÔNIA MARIA SILVA GOMES (IPATINGA)
UPDATE schools SET inep_code = '191302' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÔNIA MARIA SILVA GOMES' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191302');

-- EE WILSON ALVARENGA (IPATINGA)
UPDATE schools SET inep_code = '191248' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE WILSON ALVARENGA' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191248');

-- EE PROFESSORA SEBASTIANA DE ALMEIDA E SILVA (JAGUARAÇU)
UPDATE schools SET inep_code = '361453' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA SEBASTIANA DE ALMEIDA E SILVA' AND UPPER(TRIM(city)) = 'JAGUARAÇU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '361453');

-- EE PROFESSOR ANTÔNIO MARCIANO (JOANÉSIA)
UPDATE schools SET inep_code = '205621' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ANTÔNIO MARCIANO' AND UPPER(TRIM(city)) = 'JOANÉSIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '205621');

-- EE PROFESSOR MANOEL GONÇALVES FERREIRA (JOANÉSIA)
UPDATE schools SET inep_code = '191353' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR MANOEL GONÇALVES FERREIRA' AND UPPER(TRIM(city)) = 'JOANÉSIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191353');

-- EE PROFESSORA EUNICE DOS SANTOS COSTA (JOANÉSIA)
UPDATE schools SET inep_code = '191345' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA EUNICE DOS SANTOS COSTA' AND UPPER(TRIM(city)) = 'JOANÉSIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191345');

-- EE HORTO BELÉM (MARLIÉRIA)
UPDATE schools SET inep_code = '191396' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE HORTO BELÉM' AND UPPER(TRIM(city)) = 'MARLIÉRIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191396');

-- EE LIBERATO DE CASTRO (MARLIÉRIA)
UPDATE schools SET inep_code = '191361' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LIBERATO DE CASTRO' AND UPPER(TRIM(city)) = 'MARLIÉRIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191361');

-- EE CAETANO DIAS (MESQUITA)
UPDATE schools SET inep_code = '191434' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CAETANO DIAS' AND UPPER(TRIM(city)) = 'MESQUITA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191434');

-- EE PRUDENTE DE MORAIS (MESQUITA)
UPDATE schools SET inep_code = '191418' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PRUDENTE DE MORAIS' AND UPPER(TRIM(city)) = 'MESQUITA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191418');

-- EE ALBERTINO FERREIRA DRUMOND (SANTANA DO PARAÍSO)
UPDATE schools SET inep_code = '191442' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALBERTINO FERREIRA DRUMOND' AND UPPER(TRIM(city)) = 'SANTANA DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191442');

-- EE ANTÔNIO LUIZ (SANTANA DO PARAÍSO)
UPDATE schools SET inep_code = '191451' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO LUIZ' AND UPPER(TRIM(city)) = 'SANTANA DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191451');

-- EE HERBERT JOSÉ DE SOUZA BETINHO (SANTANA DO PARAÍSO)
UPDATE schools SET inep_code = '330540' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE HERBERT JOSÉ DE SOUZA BETINHO' AND UPPER(TRIM(city)) = 'SANTANA DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '330540');

-- EE JOAQUIM ELIZIÁRIO DA SILVA (SANTANA DO PARAÍSO)
UPDATE schools SET inep_code = '191469' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOAQUIM ELIZIÁRIO DA SILVA' AND UPPER(TRIM(city)) = 'SANTANA DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191469');

-- EE JOSÉ ROSA DAMASCENO (SANTANA DO PARAÍSO)
UPDATE schools SET inep_code = '191426' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ ROSA DAMASCENO' AND UPPER(TRIM(city)) = 'SANTANA DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191426');

-- EE SALVELINO FERNANDES MADEIRA (SANTANA DO PARAÍSO)
UPDATE schools SET inep_code = '191477' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SALVELINO FERNANDES MADEIRA' AND UPPER(TRIM(city)) = 'SANTANA DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191477');

-- EE ANTÔNIO SILVA (TIMÓTEO)
UPDATE schools SET inep_code = '191540' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO SILVA' AND UPPER(TRIM(city)) = 'TIMÓTEO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191540');

-- EE JOÃO COTTA DE FIGUEIREDO BARCELOS (TIMÓTEO)
UPDATE schools SET inep_code = '191663' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO COTTA DE FIGUEIREDO BARCELOS' AND UPPER(TRIM(city)) = 'TIMÓTEO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191663');

-- EE LEÔNCIO DE ARAÚJO (TIMÓTEO)
UPDATE schools SET inep_code = '191639' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LEÔNCIO DE ARAÚJO' AND UPPER(TRIM(city)) = 'TIMÓTEO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191639');

-- EE PROFESSORA ANA LETRO STAACKS (TIMÓTEO)
UPDATE schools SET inep_code = '191531' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ANA LETRO STAACKS' AND UPPER(TRIM(city)) = 'TIMÓTEO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191531');

-- EE PROFESSORA HAYDÉE DE SOUZA ABREU (TIMÓTEO)
UPDATE schools SET inep_code = '326445' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA HAYDÉE DE SOUZA ABREU' AND UPPER(TRIM(city)) = 'TIMÓTEO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '326445');

-- EE PROFESSORA HILDA DE ARAÚJO OSÓRIO ZAUZA (TIMÓTEO)
UPDATE schools SET inep_code = '191566' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA HILDA DE ARAÚJO OSÓRIO ZAUZA' AND UPPER(TRIM(city)) = 'TIMÓTEO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191566');

-- EE SÃO SEBASTIÃO (TIMÓTEO)
UPDATE schools SET inep_code = '191507' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO SEBASTIÃO' AND UPPER(TRIM(city)) = 'TIMÓTEO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '191507');

-- EE AFONSO SOARES DE FREITAS (AUGUSTO DE LIMA)
UPDATE schools SET inep_code = '140309' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE AFONSO SOARES DE FREITAS' AND UPPER(TRIM(city)) = 'AUGUSTO DE LIMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140309');

-- EE NOSSA SENHORA DO CARMO (BUENÓPOLIS)
UPDATE schools SET inep_code = '140384' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DO CARMO' AND UPPER(TRIM(city)) = 'BUENÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140384');

-- EE PADRE LAERTE ESPERANÇA OLIVEIRA (BUENÓPOLIS)
UPDATE schools SET inep_code = '140392' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE LAERTE ESPERANÇA OLIVEIRA' AND UPPER(TRIM(city)) = 'BUENÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140392');

-- EE ALENCASTRO GUIMARÃES (CORINTO)
UPDATE schools SET inep_code = '140597' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALENCASTRO GUIMARÃES' AND UPPER(TRIM(city)) = 'CORINTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140597');

-- EE ANTÔNIO VIEIRA MACHADO (CORINTO)
UPDATE schools SET inep_code = '140601' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO VIEIRA MACHADO' AND UPPER(TRIM(city)) = 'CORINTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140601');

-- EE DESEMBARGADOR CANEDO (CORINTO)
UPDATE schools SET inep_code = '140627' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DESEMBARGADOR CANEDO' AND UPPER(TRIM(city)) = 'CORINTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140627');

-- EE JOSÉ BRÍGIDO PEREIRA PEDRA (CORINTO)
UPDATE schools SET inep_code = '140619' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ BRÍGIDO PEREIRA PEDRA' AND UPPER(TRIM(city)) = 'CORINTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140619');

-- EE MAJOR CLARINDO DE PAIVA (CORINTO)
UPDATE schools SET inep_code = '140651' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MAJOR CLARINDO DE PAIVA' AND UPPER(TRIM(city)) = 'CORINTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140651');

-- EE PROFESSORA MARIA AMÁLIA CAMPOS (CORINTO)
UPDATE schools SET inep_code = '140686' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA AMÁLIA CAMPOS' AND UPPER(TRIM(city)) = 'CORINTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140686');

-- EE WALDEMAR ARAÚJO (CORINTO)
UPDATE schools SET inep_code = '140694' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE WALDEMAR ARAÚJO' AND UPPER(TRIM(city)) = 'CORINTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140694');

-- CESEC DE CURVELO (CURVELO)
UPDATE schools SET inep_code = '346080' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC DE CURVELO' AND UPPER(TRIM(city)) = 'CURVELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346080');

-- COLÉGIO TIRADENTES PMMG - UNIDADE CURVELO (CURVELO)
UPDATE schools SET inep_code = '368288' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG - UNIDADE CURVELO' AND UPPER(TRIM(city)) = 'CURVELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368288');

-- EE ANTONINA MASCARENHAS GONZAGA (CURVELO)
UPDATE schools SET inep_code = '140864' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTONINA MASCARENHAS GONZAGA' AND UPPER(TRIM(city)) = 'CURVELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140864');

-- EE BASÍLIO FRANCISCO XAVIER (CURVELO)
UPDATE schools SET inep_code = '140899' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BASÍLIO FRANCISCO XAVIER' AND UPPER(TRIM(city)) = 'CURVELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140899');

-- EE BOLÍVAR DE FREITAS (CURVELO)
UPDATE schools SET inep_code = '140716' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BOLÍVAR DE FREITAS' AND UPPER(TRIM(city)) = 'CURVELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140716');

-- EE EURÍPEDES DE PAULA (CURVELO)
UPDATE schools SET inep_code = '140767' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE EURÍPEDES DE PAULA' AND UPPER(TRIM(city)) = 'CURVELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140767');

-- EE INTERVENTOR ALCIDES LINS (CURVELO)
UPDATE schools SET inep_code = '140775' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE INTERVENTOR ALCIDES LINS' AND UPPER(TRIM(city)) = 'CURVELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140775');

-- EE IRMÃ CLARENTINA (CURVELO)
UPDATE schools SET inep_code = '140856' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE IRMÃ CLARENTINA' AND UPPER(TRIM(city)) = 'CURVELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140856');

-- EE IRMÃ RAIMUNDA MARQUES (CURVELO)
UPDATE schools SET inep_code = '140848' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE IRMÃ RAIMUNDA MARQUES' AND UPPER(TRIM(city)) = 'CURVELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140848');

-- EE MAJOR ANTÔNIO SALVO (CURVELO)
UPDATE schools SET inep_code = '140791' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MAJOR ANTÔNIO SALVO' AND UPPER(TRIM(city)) = 'CURVELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140791');

-- EE MINISTRO ADAUTO LÚCIO CARDOSO (CURVELO)
UPDATE schools SET inep_code = '140708' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MINISTRO ADAUTO LÚCIO CARDOSO' AND UPPER(TRIM(city)) = 'CURVELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140708');

-- EE PADRE AUGUSTO HORTA (CURVELO)
UPDATE schools SET inep_code = '140872' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE AUGUSTO HORTA' AND UPPER(TRIM(city)) = 'CURVELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140872');

-- EE SÃO GERALDO (CURVELO)
UPDATE schools SET inep_code = '140821' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO GERALDO' AND UPPER(TRIM(city)) = 'CURVELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140821');

-- EE SÃO VICENTE DE PAULO (CURVELO)
UPDATE schools SET inep_code = '140830' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO VICENTE DE PAULO' AND UPPER(TRIM(city)) = 'CURVELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140830');

-- EE SÉRGIO EUGÊNIO DA SILVA (CURVELO)
UPDATE schools SET inep_code = '253421' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÉRGIO EUGÊNIO DA SILVA' AND UPPER(TRIM(city)) = 'CURVELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253421');

-- CESEC HUMBERTO JOSÉ ELIAS (FELIXLÂNDIA)
UPDATE schools SET inep_code = '218685' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC HUMBERTO JOSÉ ELIAS' AND UPPER(TRIM(city)) = 'FELIXLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218685');

-- EE PADRE JOSÉ GONÇALVES DE SOUZA (FELIXLÂNDIA)
UPDATE schools SET inep_code = '140953' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE JOSÉ GONÇALVES DE SOUZA' AND UPPER(TRIM(city)) = 'FELIXLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140953');

-- EE SÃO JOSÉ DO BURITI (FELIXLÂNDIA)
UPDATE schools SET inep_code = '140988' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO JOSÉ DO BURITI' AND UPPER(TRIM(city)) = 'FELIXLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140988');

-- EE DOUTOR PACÍFICO MASCARENHAS (INIMUTABA)
UPDATE schools SET inep_code = '141119' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR PACÍFICO MASCARENHAS' AND UPPER(TRIM(city)) = 'INIMUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141119');

-- EE NOSSA SENHORA DAS DORES (JOAQUIM FELÍCIO)
UPDATE schools SET inep_code = '141178' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DAS DORES' AND UPPER(TRIM(city)) = 'JOAQUIM FELÍCIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141178');

-- EE PREFEITO WALTER COELHO DA ROCHA (MORRO DA GARÇA)
UPDATE schools SET inep_code = '312070' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PREFEITO WALTER COELHO DA ROCHA' AND UPPER(TRIM(city)) = 'MORRO DA GARÇA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312070');

-- EE CARLOS ALEXANDRE DE OLIVEIRA (TRÊS MARIAS)
UPDATE schools SET inep_code = '142042' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CARLOS ALEXANDRE DE OLIVEIRA' AND UPPER(TRIM(city)) = 'TRÊS MARIAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '142042');

-- EE JOÃO GUIMARÃES ROSA (TRÊS MARIAS)
UPDATE schools SET inep_code = '246417' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO GUIMARÃES ROSA' AND UPPER(TRIM(city)) = 'TRÊS MARIAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246417');

-- EE JOSÉ ERMÍRIO DE MORAIS (TRÊS MARIAS)
UPDATE schools SET inep_code = '141976' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ ERMÍRIO DE MORAIS' AND UPPER(TRIM(city)) = 'TRÊS MARIAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141976');

-- EE MANOEL PEREIRA DE FREITAS (TRÊS MARIAS)
UPDATE schools SET inep_code = '142026' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MANOEL PEREIRA DE FREITAS' AND UPPER(TRIM(city)) = 'TRÊS MARIAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '142026');

-- EE IVETA GOMES SANTANA (ANGELÂNDIA)
UPDATE schools SET inep_code = '330604' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE IVETA GOMES SANTANA' AND UPPER(TRIM(city)) = 'ANGELÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '330604');

-- EE BENTO ROCHA DE JESUS (CAPELINHA)
UPDATE schools SET inep_code = '319376' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BENTO ROCHA DE JESUS' AND UPPER(TRIM(city)) = 'CAPELINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '319376');

-- EE DOMINGOS PIMENTA DE FIGUEIREDO (CAPELINHA)
UPDATE schools SET inep_code = '205893' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOMINGOS PIMENTA DE FIGUEIREDO' AND UPPER(TRIM(city)) = 'CAPELINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '205893');

-- EE ROSARINHA PIMENTINHA (CAPELINHA)
UPDATE schools SET inep_code = '217646' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ROSARINHA PIMENTINHA' AND UPPER(TRIM(city)) = 'CAPELINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217646');

-- EE SEBASTIÃO PEÇANHA DE OLIVEIRA (CAPELINHA)
UPDATE schools SET inep_code = '342718' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SEBASTIÃO PEÇANHA DE OLIVEIRA' AND UPPER(TRIM(city)) = 'CAPELINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342718');

-- EE JULIANA CATARINA DA SILVEIRA (DATAS)
UPDATE schools SET inep_code = '254355' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JULIANA CATARINA DA SILVEIRA' AND UPPER(TRIM(city)) = 'DATAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '254355');

-- EE MESTRA BEZINHA GANDRA (ITAMARANDIBA)
UPDATE schools SET inep_code = '217611' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MESTRA BEZINHA GANDRA' AND UPPER(TRIM(city)) = 'ITAMARANDIBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217611');

-- EE ERNESTO ALVES DE MENDONÇA (MINAS NOVAS)
UPDATE schools SET inep_code = '218448' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ERNESTO ALVES DE MENDONÇA' AND UPPER(TRIM(city)) = 'MINAS NOVAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218448');

-- EE JOÃO FERNANDES DE AZEVEDO (MINAS NOVAS)
UPDATE schools SET inep_code = '218421' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO FERNANDES DE AZEVEDO' AND UPPER(TRIM(city)) = 'MINAS NOVAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218421');

-- EE SEBASTIÃO GOMES DE ALMEIDA (MINAS NOVAS)
UPDATE schools SET inep_code = '217638' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SEBASTIÃO GOMES DE ALMEIDA' AND UPPER(TRIM(city)) = 'MINAS NOVAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217638');

-- CESEC SENHORA DA PIEDADE (TURMALINA)
UPDATE schools SET inep_code = '218367' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC SENHORA DA PIEDADE' AND UPPER(TRIM(city)) = 'TURMALINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218367');

-- EE PROFESSORA EDITE GOMES (TURMALINA)
UPDATE schools SET inep_code = '246344' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA EDITE GOMES' AND UPPER(TRIM(city)) = 'TURMALINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246344');

-- EE SÃO FRANCISCO DE ASSIS (CARMO DO CAJURU)
UPDATE schools SET inep_code = '307335' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO FRANCISCO DE ASSIS' AND UPPER(TRIM(city)) = 'CARMO DO CAJURU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '307335');

-- COLÉGIO TIRADENTES PMMG (DIVINÓPOLIS)
UPDATE schools SET inep_code = '364592' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG' AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '364592');

-- EE CARMELO MESQUITA (ITAPECERICA)
UPDATE schools SET inep_code = '202851' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CARMELO MESQUITA' AND UPPER(TRIM(city)) = 'ITAPECERICA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '202851');

-- EE IMACULADA CONCEIÇÃO (ITAPECERICA)
UPDATE schools SET inep_code = '202762' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE IMACULADA CONCEIÇÃO' AND UPPER(TRIM(city)) = 'ITAPECERICA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '202762');

-- EE INDÍGENA PATAXÓ MUÃ MIMATXI (ITAPECERICA)
UPDATE schools SET inep_code = '342521' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE INDÍGENA PATAXÓ MUÃ MIMATXI' AND UPPER(TRIM(city)) = 'ITAPECERICA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342521');

-- EE LAMOUNIER GODOFREDO (ITAPECERICA)
UPDATE schools SET inep_code = '202843' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LAMOUNIER GODOFREDO' AND UPPER(TRIM(city)) = 'ITAPECERICA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '202843');

-- EE PADRE HERCULANO PAZ (ITAPECERICA)
UPDATE schools SET inep_code = '202797' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE HERCULANO PAZ' AND UPPER(TRIM(city)) = 'ITAPECERICA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '202797');

-- EE PEDRO LUIZ (ITAPECERICA)
UPDATE schools SET inep_code = '202860' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PEDRO LUIZ' AND UPPER(TRIM(city)) = 'ITAPECERICA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '202860');

-- EE PROFESSORA GERALDA MAGELA LEÃO DE MELO (ITAÚNA)
UPDATE schools SET inep_code = '330841' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA GERALDA MAGELA LEÃO DE MELO' AND UPPER(TRIM(city)) = 'ITAÚNA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '330841');

-- EE PROFESSORA GILKA DRUMOND DE FARIA (ITAÚNA)
UPDATE schools SET inep_code = '305642' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA GILKA DRUMOND DE FARIA' AND UPPER(TRIM(city)) = 'ITAÚNA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305642');

-- EE JOSÉ TEOTÔNIO DE CASTRO (LAGOA DA PRATA)
UPDATE schools SET inep_code = '231746' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ TEOTÔNIO DE CASTRO' AND UPPER(TRIM(city)) = 'LAGOA DA PRATA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '231746');

-- EE DONA LICA RAPOSO (LUZ)
UPDATE schools SET inep_code = '218405' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DONA LICA RAPOSO' AND UPPER(TRIM(city)) = 'LUZ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218405');

-- EE MARIA ZELI DINIZ FONSECA (NOVA SERRANA)
UPDATE schools SET inep_code = '342530' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARIA ZELI DINIZ FONSECA' AND UPPER(TRIM(city)) = 'NOVA SERRANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342530');

-- EE PADRE LAURO (NOVA SERRANA)
UPDATE schools SET inep_code = '326135' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE LAURO' AND UPPER(TRIM(city)) = 'NOVA SERRANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '326135');

-- EE DOUTOR JOSÉ MARIA LOBATO (OLIVEIRA)
UPDATE schools SET inep_code = '203301' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR JOSÉ MARIA LOBATO' AND UPPER(TRIM(city)) = 'OLIVEIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '203301');

-- EE MÁRIO CAMPOS E SILVA (OLIVEIRA)
UPDATE schools SET inep_code = '203343' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MÁRIO CAMPOS E SILVA' AND UPPER(TRIM(city)) = 'OLIVEIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '203343');

-- EE PROFESSOR PINHEIRO CAMPOS (OLIVEIRA)
UPDATE schools SET inep_code = '203360' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR PINHEIRO CAMPOS' AND UPPER(TRIM(city)) = 'OLIVEIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '203360');

-- EE SÃO JOÃO BATISTA (OLIVEIRA)
UPDATE schools SET inep_code = '203408' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO JOÃO BATISTA' AND UPPER(TRIM(city)) = 'OLIVEIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '203408');

-- EE PADRE PAULO (SANTO ANTÔNIO DO MONTE)
UPDATE schools SET inep_code = '224014' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE PAULO' AND UPPER(TRIM(city)) = 'SANTO ANTÔNIO DO MONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '224014');

-- EE DE TAPIRAÍ (TAPIRAÍ)
UPDATE schools SET inep_code = '307416' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE TAPIRAÍ' AND UPPER(TRIM(city)) = 'TAPIRAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '307416');

-- EE PROFESSORA ELGE RENAN BRAGA (COROACI)
UPDATE schools SET inep_code = '267228' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ELGE RENAN BRAGA' AND UPPER(TRIM(city)) = 'COROACI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '267228');

-- EE CECÍLIA MEIRELES (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '354716' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CECÍLIA MEIRELES' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '354716');

-- EE DO BAIRRO JARDIM DO IPÊ (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '205371' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DO BAIRRO JARDIM DO IPÊ' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '205371');

-- EE PROFESSOR DARCY RIBEIRO (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '271241' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR DARCY RIBEIRO' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '271241');

-- EE PROFESSORA MARIA DAMÁZIO DE BARROS MENEZES (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '354724' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA DAMÁZIO DE BARROS MENEZES' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '354724');

-- EE SÃO FRANCISCO DE ASSIS (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '326861' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO FRANCISCO DE ASSIS' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '326861');

-- CESEC DE ITABIRINHA (ITABIRINHA)
UPDATE schools SET inep_code = '351423' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC DE ITABIRINHA' AND UPPER(TRIM(city)) = 'ITABIRINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '351423');

-- EE DOUTOR ALAIR ALVES COSTA (NOVA MÓDICA)
UPDATE schools SET inep_code = '147532' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR ALAIR ALVES COSTA' AND UPPER(TRIM(city)) = 'NOVA MÓDICA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147532');

-- EE TRANQUILINO DIAS BRITO (SÃO JOSÉ DO DIVINO)
UPDATE schools SET inep_code = '147885' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE TRANQUILINO DIAS BRITO' AND UPPER(TRIM(city)) = 'SÃO JOSÉ DO DIVINO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147885');

-- EE PRIMEIRO DE JUNHO (TUMIRITINGA)
UPDATE schools SET inep_code = '246379' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PRIMEIRO DE JUNHO' AND UPPER(TRIM(city)) = 'TUMIRITINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246379');

-- EE JOSÉ BONIFÁCIO SANTANA (ÁGUA BOA)
UPDATE schools SET inep_code = '254045' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ BONIFÁCIO SANTANA' AND UPPER(TRIM(city)) = 'ÁGUA BOA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '254045');

-- EE INDÍGENA ÃGOHÓ KUÂP PATAXÓ (CARMÉSIA)
UPDATE schools SET inep_code = '369802' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE INDÍGENA ÃGOHÓ KUÂP PATAXÓ' AND UPPER(TRIM(city)) = 'CARMÉSIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369802');

-- EE INDÍGENA PATAXÓ BACUMUXÁ (CARMÉSIA)
UPDATE schools SET inep_code = '277657' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE INDÍGENA PATAXÓ BACUMUXÁ' AND UPPER(TRIM(city)) = 'CARMÉSIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '277657');

-- EE PROFESSORA ALMERINDA AGUIAR (COLUNA)
UPDATE schools SET inep_code = '213969' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ALMERINDA AGUIAR' AND UPPER(TRIM(city)) = 'COLUNA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '213969');

-- EE NADIM NOMAN (DORES DE GUANHÃES)
UPDATE schools SET inep_code = '322857' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NADIM NOMAN' AND UPPER(TRIM(city)) = 'DORES DE GUANHÃES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322857');

-- EE PROFESSORA MARGARET BARROSO PINTO (SABINÓPOLIS)
UPDATE schools SET inep_code = '330680' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARGARET BARROSO PINTO' AND UPPER(TRIM(city)) = 'SABINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '330680');

-- EE ALTAIR ANDRADE GUIMARÃES (SÃO SEBASTIÃO DO MARANHÃO)
UPDATE schools SET inep_code = '253316' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALTAIR ANDRADE GUIMARÃES' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO MARANHÃO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253316');

-- EE PROFESSORA CIVA SIMÕES FONSECA (SENHORA DO PORTO)
UPDATE schools SET inep_code = '342548' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA CIVA SIMÕES FONSECA' AND UPPER(TRIM(city)) = 'SENHORA DO PORTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342548');

-- EE DO POVOADO DE BOM JESUS DA BOA VISTA (VIRGINÓPOLIS)
UPDATE schools SET inep_code = '218146' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DO POVOADO DE BOM JESUS DA BOA VISTA' AND UPPER(TRIM(city)) = 'VIRGINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218146');

-- EE GABRIEL RIBEIRO (CARMO DE MINAS)
UPDATE schools SET inep_code = '171956' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GABRIEL RIBEIRO' AND UPPER(TRIM(city)) = 'CARMO DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '171956');

-- EE PROFESSOR GUEDES FERNANDES (CARMO DE MINAS)
UPDATE schools SET inep_code = '171964' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR GUEDES FERNANDES' AND UPPER(TRIM(city)) = 'CARMO DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '171964');

-- EE CÔNEGO JOSÉ DIVINO (DOM VIÇOSO)
UPDATE schools SET inep_code = '305375' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CÔNEGO JOSÉ DIVINO' AND UPPER(TRIM(city)) = 'DOM VIÇOSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305375');

-- CEP - CENTRO DE EDUCAÇÃO PROFISSIONAL DE ITAJUBÁ (ITAJUBÁ)
UPDATE schools SET inep_code = '310778' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CEP - CENTRO DE EDUCAÇÃO PROFISSIONAL DE ITAJUBÁ' AND UPPER(TRIM(city)) = 'ITAJUBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310778');

-- EE EULÁLIA GOMES DE OLIVEIRA (PARAISÓPOLIS)
UPDATE schools SET inep_code = '305383' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE EULÁLIA GOMES DE OLIVEIRA' AND UPPER(TRIM(city)) = 'PARAISÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305383');

-- EE DELFIM MOREIRA (VIRGÍNIA)
UPDATE schools SET inep_code = '175137' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DELFIM MOREIRA' AND UPPER(TRIM(city)) = 'VIRGÍNIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '175137');

-- EE PROFESSOR MANOEL MACHADO (VIRGÍNIA)
UPDATE schools SET inep_code = '175153' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR MANOEL MACHADO' AND UPPER(TRIM(city)) = 'VIRGÍNIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '175153');

-- EE JOÃO GONÇALVES DE OLIVEIRA (CACHOEIRA DOURADA)
UPDATE schools SET inep_code = '322814' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO GONÇALVES DE OLIVEIRA' AND UPPER(TRIM(city)) = 'CACHOEIRA DOURADA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322814');

-- EE JOSÉ EZEQUIEL DE QUEIRÓS (CANÁPOLIS)
UPDATE schools SET inep_code = '312045' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ EZEQUIEL DE QUEIRÓS' AND UPPER(TRIM(city)) = 'CANÁPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312045');

-- EE SÃO FRANCISCO DE ASSIS (CANÁPOLIS)
UPDATE schools SET inep_code = '196380' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO FRANCISCO DE ASSIS' AND UPPER(TRIM(city)) = 'CANÁPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196380');

-- EE GOVERNADOR JUSCELINO (CAPINÓPOLIS)
UPDATE schools SET inep_code = '196401' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GOVERNADOR JUSCELINO' AND UPPER(TRIM(city)) = 'CAPINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196401');

-- EE SÉRGIO DE FREITAS PACHECO (CAPINÓPOLIS)
UPDATE schools SET inep_code = '196398' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÉRGIO DE FREITAS PACHECO' AND UPPER(TRIM(city)) = 'CAPINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196398');

-- EE WILSON DE MELO (CENTRALINA)
UPDATE schools SET inep_code = '196452' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE WILSON DE MELO' AND UPPER(TRIM(city)) = 'CENTRALINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196452');

-- EE DE GURINHATÃ (GURINHATÃ)
UPDATE schools SET inep_code = '196461' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE GURINHATÃ' AND UPPER(TRIM(city)) = 'GURINHATÃ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196461');

-- EE HEITOR JOSÉ DE CASTRO (GURINHATÃ)
UPDATE schools SET inep_code = '196487' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE HEITOR JOSÉ DE CASTRO' AND UPPER(TRIM(city)) = 'GURINHATÃ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196487');

-- EE BENEDITO WALDEMAR DA SILVA (IPIAÇU)
UPDATE schools SET inep_code = '196517' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BENEDITO WALDEMAR DA SILVA' AND UPPER(TRIM(city)) = 'IPIAÇU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196517');

-- CESEC CLORINDA MARTINS TAVARES (ITUIUTABA)
UPDATE schools SET inep_code = '196703' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC CLORINDA MARTINS TAVARES' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196703');

-- CONSERVATÓRIO ESTADUAL DE MÚSICA DOUTOR JOSÉ ZÓCCOLI DE ANDRADE (ITUIUTABA)
UPDATE schools SET inep_code = '196622' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CONSERVATÓRIO ESTADUAL DE MÚSICA DOUTOR JOSÉ ZÓCCOLI DE ANDRADE' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196622');

-- EE ANTÔNIO SOUZA MARTINS (ITUIUTABA)
UPDATE schools SET inep_code = '196631' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO SOUZA MARTINS' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196631');

-- EE ARTHUR JUNQUEIRA DE ALMEIDA (ITUIUTABA)
UPDATE schools SET inep_code = '196576' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ARTHUR JUNQUEIRA DE ALMEIDA' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196576');

-- EE CÔNEGO ÂNGELO (ITUIUTABA)
UPDATE schools SET inep_code = '196541' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CÔNEGO ÂNGELO' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196541');

-- EE CORONEL JOÃO MARTINS (ITUIUTABA)
UPDATE schools SET inep_code = '196525' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL JOÃO MARTINS' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196525');

-- EE CORONEL TONICO FRANCO (ITUIUTABA)
UPDATE schools SET inep_code = '196533' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL TONICO FRANCO' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196533');

-- EE DOUTOR FERNANDO ALEXANDRE (ITUIUTABA)
UPDATE schools SET inep_code = '196550' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR FERNANDO ALEXANDRE' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196550');

-- EE GOVERNADOR BIAS FORTES (ITUIUTABA)
UPDATE schools SET inep_code = '196568' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GOVERNADOR BIAS FORTES' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196568');

-- EE GOVERNADOR CLÓVIS SALGADO (ITUIUTABA)
UPDATE schools SET inep_code = '196681' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GOVERNADOR CLÓVIS SALGADO' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196681');

-- EE GOVERNADOR ISRAEL PINHEIRO (ITUIUTABA)
UPDATE schools SET inep_code = '196584' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GOVERNADOR ISRAEL PINHEIRO' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196584');

-- EE JOÃO PINHEIRO (ITUIUTABA)
UPDATE schools SET inep_code = '196606' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO PINHEIRO' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196606');

-- EE PROFESSOR ÁLVARO BRANDÃO DE ANDRADE (ITUIUTABA)
UPDATE schools SET inep_code = '196657' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ÁLVARO BRANDÃO DE ANDRADE' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196657');

-- EE PROFESSORA MARIA DE BARROS (ITUIUTABA)
UPDATE schools SET inep_code = '196592' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA DE BARROS' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196592');

-- EE ROTARY (ITUIUTABA)
UPDATE schools SET inep_code = '196665' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ROTARY' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196665');

-- EE SENADOR CAMILO CHAVES (ITUIUTABA)
UPDATE schools SET inep_code = '196673' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SENADOR CAMILO CHAVES' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196673');

-- EE JOSÉ PARANAÍBA (SANTA VITÓRIA)
UPDATE schools SET inep_code = '196738' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ PARANAÍBA' AND UPPER(TRIM(city)) = 'SANTA VITÓRIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196738');

-- EE PREFEITO JOSÉ FRANCO DE GOUVEIA (SANTA VITÓRIA)
UPDATE schools SET inep_code = '196720' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PREFEITO JOSÉ FRANCO DE GOUVEIA' AND UPPER(TRIM(city)) = 'SANTA VITÓRIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '196720');

-- EE PROFESSORA DIRCE MARIA DE OLIVEIRA (SANTA VITÓRIA)
UPDATE schools SET inep_code = '338672' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA DIRCE MARIA DE OLIVEIRA' AND UPPER(TRIM(city)) = 'SANTA VITÓRIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338672');

-- EE JOAQUIM TEIXEIRA DE BRITO (CATUTI)
UPDATE schools SET inep_code = '239194' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOAQUIM TEIXEIRA DE BRITO' AND UPPER(TRIM(city)) = 'CATUTI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '239194');

-- EE ALVACY DE FREITAS (ESPINOSA)
UPDATE schools SET inep_code = '362484' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALVACY DE FREITAS' AND UPPER(TRIM(city)) = 'ESPINOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '362484');

-- EE BETÂNIA TOLENTINO SILVEIRA (ESPINOSA)
UPDATE schools SET inep_code = '212261' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BETÂNIA TOLENTINO SILVEIRA' AND UPPER(TRIM(city)) = 'ESPINOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '212261');

-- EE SANTOS DUMONT (ESPINOSA)
UPDATE schools SET inep_code = '218286' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SANTOS DUMONT' AND UPPER(TRIM(city)) = 'ESPINOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218286');

-- EE DO NÚCLEO HABITACIONAL I (JAÍBA)
UPDATE schools SET inep_code = '231843' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DO NÚCLEO HABITACIONAL I' AND UPPER(TRIM(city)) = 'JAÍBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '231843');

-- EE GUIMARÃES ROSA (JAÍBA)
UPDATE schools SET inep_code = '295086' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GUIMARÃES ROSA' AND UPPER(TRIM(city)) = 'JAÍBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '295086');

-- EE PEQUENOS IRRIGANTES (JAÍBA)
UPDATE schools SET inep_code = '231835' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PEQUENOS IRRIGANTES' AND UPPER(TRIM(city)) = 'JAÍBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '231835');

-- EE TIMÓTEO LISBOA GUERRA (JAÍBA)
UPDATE schools SET inep_code = '239208' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE TIMÓTEO LISBOA GUERRA' AND UPPER(TRIM(city)) = 'JAÍBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '239208');

-- EE CECÍLIA MARIA DE JESUS (JANAÚBA)
UPDATE schools SET inep_code = '218251' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CECÍLIA MARIA DE JESUS' AND UPPER(TRIM(city)) = 'JANAÚBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218251');

-- EE DOUTOR JOSÉ ESTEVES RODRIGUES (JANAÚBA)
UPDATE schools SET inep_code = '338680' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR JOSÉ ESTEVES RODRIGUES' AND UPPER(TRIM(city)) = 'JANAÚBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338680');

-- EE JOAQUIM MAURÍCIO DE AZEVEDO (JANAÚBA)
UPDATE schools SET inep_code = '233374' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOAQUIM MAURÍCIO DE AZEVEDO' AND UPPER(TRIM(city)) = 'JANAÚBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '233374');

-- EE JULIÃO MENDES FERREIRA (JANAÚBA)
UPDATE schools SET inep_code = '338699' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JULIÃO MENDES FERREIRA' AND UPPER(TRIM(city)) = 'JANAÚBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338699');

-- EE EREZINHA ANTUNES MARTINS (NOVA PORTEIRINHA)
UPDATE schools SET inep_code = '205648' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE EREZINHA ANTUNES MARTINS' AND UPPER(TRIM(city)) = 'NOVA PORTEIRINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '205648');

-- EE MESTRE TOMAZ VALERIANO DE ARAÚJO (PORTEIRINHA)
UPDATE schools SET inep_code = '338702' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MESTRE TOMAZ VALERIANO DE ARAÚJO' AND UPPER(TRIM(city)) = 'PORTEIRINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338702');

-- EE DE ENSINO MÉDIO (RIO PARDO DE MINAS)
UPDATE schools SET inep_code = '349267' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' AND UPPER(TRIM(city)) = 'RIO PARDO DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349267');

-- EE PROFESSORA MARLENE CARMO (RIO PARDO DE MINAS)
UPDATE schools SET inep_code = '212253' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARLENE CARMO' AND UPPER(TRIM(city)) = 'RIO PARDO DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '212253');

-- EE ALICE DE JESUS RODRIGUES (VERDELÂNDIA)
UPDATE schools SET inep_code = '351091' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALICE DE JESUS RODRIGUES' AND UPPER(TRIM(city)) = 'VERDELÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '351091');

-- EE ANTONINA FERNANDES SAMPAIO (VERDELÂNDIA)
UPDATE schools SET inep_code = '351083' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTONINA FERNANDES SAMPAIO' AND UPPER(TRIM(city)) = 'VERDELÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '351083');

-- EE CESÁRIO NUNES DOS SANTOS (BONITO DE MINAS)
UPDATE schools SET inep_code = '205532' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CESÁRIO NUNES DOS SANTOS' AND UPPER(TRIM(city)) = 'BONITO DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '205532');

-- EE DE BONFIM (BONITO DE MINAS)
UPDATE schools SET inep_code = '205516' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE BONFIM' AND UPPER(TRIM(city)) = 'BONITO DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '205516');

-- EE DE ENSINO FUNDAMENTAL ANOS FINAIS E ENSINO MÉDIO (BONITO DE MINAS)
UPDATE schools SET inep_code = '369810' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL ANOS FINAIS E ENSINO MÉDIO' AND UPPER(TRIM(city)) = 'BONITO DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369810');

-- EE MANOEL PEREIRA MAGALHÃES (BONITO DE MINAS)
UPDATE schools SET inep_code = '205451' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MANOEL PEREIRA MAGALHÃES' AND UPPER(TRIM(city)) = 'BONITO DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '205451');

-- EE SÃO JOSÉ DO GIBÃO (BONITO DE MINAS)
UPDATE schools SET inep_code = '205508' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO JOSÉ DO GIBÃO' AND UPPER(TRIM(city)) = 'BONITO DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '205508');

-- EE MOACIR CÂNDIDO (CHAPADA GAÚCHA)
UPDATE schools SET inep_code = '205460' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MOACIR CÂNDIDO' AND UPPER(TRIM(city)) = 'CHAPADA GAÚCHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '205460');

-- EE DE ENSINO FUNDAMENTAL ANOS FINAIS E ENSINO MÉDIO (CÔNEGO MARINHO)
UPDATE schools SET inep_code = '369829' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL ANOS FINAIS E ENSINO MÉDIO' AND UPPER(TRIM(city)) = 'CÔNEGO MARINHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369829');

-- EE ANTÔNIO FERNANDES VIANA (JANUÁRIA)
UPDATE schools SET inep_code = '246271' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO FERNANDES VIANA' AND UPPER(TRIM(city)) = 'JANUÁRIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246271');

-- EE DE BOA VISTA (JANUÁRIA)
UPDATE schools SET inep_code = '212822' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE BOA VISTA' AND UPPER(TRIM(city)) = 'JANUÁRIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '212822');

-- EE DE ENSINO MÉDIO (JANUÁRIA)
UPDATE schools SET inep_code = '356778' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' AND UPPER(TRIM(city)) = 'JANUÁRIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '356778');

-- EE EULER TUPINÁ BASTOS (JANUÁRIA)
UPDATE schools SET inep_code = '253685' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE EULER TUPINÁ BASTOS' AND UPPER(TRIM(city)) = 'JANUÁRIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253685');

-- EE FELIPE DIAS CORRÊA (JANUÁRIA)
UPDATE schools SET inep_code = '253677' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE FELIPE DIAS CORRÊA' AND UPPER(TRIM(city)) = 'JANUÁRIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253677');

-- EE MARIA ROSA NUNES (JANUÁRIA)
UPDATE schools SET inep_code = '246280' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARIA ROSA NUNES' AND UPPER(TRIM(city)) = 'JANUÁRIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246280');

-- EE NOVA ESPERANÇA (JANUÁRIA)
UPDATE schools SET inep_code = '253651' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NOVA ESPERANÇA' AND UPPER(TRIM(city)) = 'JANUÁRIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253651');

-- EE MANOEL FERNANDES DA SILVA (JUVENÍLIA)
UPDATE schools SET inep_code = '342726' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MANOEL FERNANDES DA SILVA' AND UPPER(TRIM(city)) = 'JUVENÍLIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342726');

-- EE DE ENSINO MÉDIO (MATIAS CARDOSO)
UPDATE schools SET inep_code = '342734' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' AND UPPER(TRIM(city)) = 'MATIAS CARDOSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342734');

-- EE DA VILA NOVO HORIZONTE (MONTALVÂNIA)
UPDATE schools SET inep_code = '217913' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DA VILA NOVO HORIZONTE' AND UPPER(TRIM(city)) = 'MONTALVÂNIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217913');

-- EE DE POÇÃOZINHO (PEDRAS DE MARIA DA CRUZ)
UPDATE schools SET inep_code = '239429' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE POÇÃOZINHO' AND UPPER(TRIM(city)) = 'PEDRAS DE MARIA DA CRUZ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '239429');

-- EE DONA CILA (PEDRAS DE MARIA DA CRUZ)
UPDATE schools SET inep_code = '239330' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DONA CILA' AND UPPER(TRIM(city)) = 'PEDRAS DE MARIA DA CRUZ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '239330');

-- EE PRIMAVERA (PINTÓPOLIS)
UPDATE schools SET inep_code = '253847' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PRIMAVERA' AND UPPER(TRIM(city)) = 'PINTÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253847');

-- EE BRASILIANO BRAZ (SÃO FRANCISCO)
UPDATE schools SET inep_code = '240222' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BRASILIANO BRAZ' AND UPPER(TRIM(city)) = 'SÃO FRANCISCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '240222');

-- EE DA FAZENDA PASSAGEM FUNDA (SÃO FRANCISCO)
UPDATE schools SET inep_code = '239411' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DA FAZENDA PASSAGEM FUNDA' AND UPPER(TRIM(city)) = 'SÃO FRANCISCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '239411');

-- EE EPAMINONDAS LEITE (SÃO FRANCISCO)
UPDATE schools SET inep_code = '253588' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE EPAMINONDAS LEITE' AND UPPER(TRIM(city)) = 'SÃO FRANCISCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253588');

-- EE EVERARDO GONÇALVES BOTELHO (SÃO FRANCISCO)
UPDATE schools SET inep_code = '239313' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE EVERARDO GONÇALVES BOTELHO' AND UPPER(TRIM(city)) = 'SÃO FRANCISCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '239313');

-- EE ALINE DIAS NEVES (SÃO JOÃO DAS MISSÕES)
UPDATE schools SET inep_code = '338761' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALINE DIAS NEVES' AND UPPER(TRIM(city)) = 'SÃO JOÃO DAS MISSÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338761');

-- EE INDÍGENA BUKIMUJU (SÃO JOÃO DAS MISSÕES)
UPDATE schools SET inep_code = '269875' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE INDÍGENA BUKIMUJU' AND UPPER(TRIM(city)) = 'SÃO JOÃO DAS MISSÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '269875');

-- EE INDÍGENA BUKINUK (SÃO JOÃO DAS MISSÕES)
UPDATE schools SET inep_code = '322571' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE INDÍGENA BUKINUK' AND UPPER(TRIM(city)) = 'SÃO JOÃO DAS MISSÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322571');

-- EE INDÍGENA DE EDUCAÇÃO INFANTIL E ENSINO FUNDAMENTAL (SÃO JOÃO DAS MISSÕES)
UPDATE schools SET inep_code = '369837' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE INDÍGENA DE EDUCAÇÃO INFANTIL E ENSINO FUNDAMENTAL' AND UPPER(TRIM(city)) = 'SÃO JOÃO DAS MISSÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369837');

-- EE INDÍGENA DE EDUCAÇÃO INFANTIL ENSINO FUNDAMENTAL E ENSINO MÉDIO (SÃO JOÃO DAS MISSÕES)
UPDATE schools SET inep_code = '356786' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE INDÍGENA DE EDUCAÇÃO INFANTIL ENSINO FUNDAMENTAL E ENSINO MÉDIO' AND UPPER(TRIM(city)) = 'SÃO JOÃO DAS MISSÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '356786');

-- EE INDÍGENA DE EDUCAÇÃO INFANTIL ENSINO FUNDAMENTAL E ENSINO MÉDIO (SÃO JOÃO DAS MISSÕES)
UPDATE schools SET inep_code = '361461' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE INDÍGENA DE EDUCAÇÃO INFANTIL ENSINO FUNDAMENTAL E ENSINO MÉDIO' AND UPPER(TRIM(city)) = 'SÃO JOÃO DAS MISSÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '361461');

-- EE INDÍGENA KUHINAN XACRIABÁ (SÃO JOÃO DAS MISSÕES)
UPDATE schools SET inep_code = '319058' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE INDÍGENA KUHINAN XACRIABÁ' AND UPPER(TRIM(city)) = 'SÃO JOÃO DAS MISSÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '319058');

-- EE INDÍGENA MAMBUKA (SÃO JOÃO DAS MISSÕES)
UPDATE schools SET inep_code = '338753' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE INDÍGENA MAMBUKA' AND UPPER(TRIM(city)) = 'SÃO JOÃO DAS MISSÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338753');

-- EE INDÍGENA OAYTOMORIM (SÃO JOÃO DAS MISSÕES)
UPDATE schools SET inep_code = '338770' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE INDÍGENA OAYTOMORIM' AND UPPER(TRIM(city)) = 'SÃO JOÃO DAS MISSÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338770');

-- EE INDÍGENA UIKITU KUHINÃ (SÃO JOÃO DAS MISSÕES)
UPDATE schools SET inep_code = '338745' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE INDÍGENA UIKITU KUHINÃ' AND UPPER(TRIM(city)) = 'SÃO JOÃO DAS MISSÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338745');

-- EE INDÍGENA XUKURANK (SÃO JOÃO DAS MISSÕES)
UPDATE schools SET inep_code = '297518' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE INDÍGENA XUKURANK' AND UPPER(TRIM(city)) = 'SÃO JOÃO DAS MISSÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '297518');

-- EE DA FAZENDA CAMPO LINDO (UBAÍ)
UPDATE schools SET inep_code = '213543' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DA FAZENDA CAMPO LINDO' AND UPPER(TRIM(city)) = 'UBAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '213543');

-- EE AMÉLIA CAVALCANTE PIMENTA (VARZELÂNDIA)
UPDATE schools SET inep_code = '253499' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE AMÉLIA CAVALCANTE PIMENTA' AND UPPER(TRIM(city)) = 'VARZELÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253499');

-- EE DEUSÂNIA DE BRITO SALES (VARZELÂNDIA)
UPDATE schools SET inep_code = '253481' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DEUSÂNIA DE BRITO SALES' AND UPPER(TRIM(city)) = 'VARZELÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253481');

-- EE GILBERTO ALVES COUTINHO (VARZELÂNDIA)
UPDATE schools SET inep_code = '253511' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GILBERTO ALVES COUTINHO' AND UPPER(TRIM(city)) = 'VARZELÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253511');

-- EE ISABEL SOARES DE JESUS (VARZELÂNDIA)
UPDATE schools SET inep_code = '217344' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ISABEL SOARES DE JESUS' AND UPPER(TRIM(city)) = 'VARZELÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217344');

-- EE JOSÉ FERNANDES DE SOUZA (VARZELÂNDIA)
UPDATE schools SET inep_code = '213527' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ FERNANDES DE SOUZA' AND UPPER(TRIM(city)) = 'VARZELÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '213527');

-- EE JUCA VELOSO (VARZELÂNDIA)
UPDATE schools SET inep_code = '223999' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JUCA VELOSO' AND UPPER(TRIM(city)) = 'VARZELÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '223999');

-- EE MANOEL ALVES DE ALMEIDA (VARZELÂNDIA)
UPDATE schools SET inep_code = '217352' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MANOEL ALVES DE ALMEIDA' AND UPPER(TRIM(city)) = 'VARZELÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217352');

-- EE NILZA MARIA DOS SANTOS (VARZELÂNDIA)
UPDATE schools SET inep_code = '253472' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NILZA MARIA DOS SANTOS' AND UPPER(TRIM(city)) = 'VARZELÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253472');

-- EE SANTO ANTÔNIO (CHIADOR)
UPDATE schools SET inep_code = '346217' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SANTO ANTÔNIO' AND UPPER(TRIM(city)) = 'CHIADOR' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346217');

-- EE PROFESSOR MILTON SANTOS (CORONEL PACHECO)
UPDATE schools SET inep_code = '322512' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR MILTON SANTOS' AND UPPER(TRIM(city)) = 'CORONEL PACHECO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322512');

-- EE CARLOS HENRIQUE RIBEIRO DOS SANTOS (GOIANÁ)
UPDATE schools SET inep_code = '369845' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CARLOS HENRIQUE RIBEIRO DOS SANTOS' AND UPPER(TRIM(city)) = 'GOIANÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369845');

-- EE PROFESSOR IRINEU GUIMARÃES (GUARARÁ)
UPDATE schools SET inep_code = '330558' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR IRINEU GUIMARÃES' AND UPPER(TRIM(city)) = 'GUARARÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '330558');

-- EE NYRCE VILLA VERDE COELHO DE MAGALHÃES (JUIZ DE FORA)
UPDATE schools SET inep_code = '342637' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NYRCE VILLA VERDE COELHO DE MAGALHÃES' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342637');

-- EE PREFEITO WALTER TREZZA (MARIPÁ DE MINAS)
UPDATE schools SET inep_code = '322539' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PREFEITO WALTER TREZZA' AND UPPER(TRIM(city)) = 'MARIPÁ DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322539');

-- EE JOAQUIM ALVES DE CARVALHO (OLARIA)
UPDATE schools SET inep_code = '330566' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOAQUIM ALVES DE CARVALHO' AND UPPER(TRIM(city)) = 'OLARIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '330566');

-- EE DE ENSINO MÉDIO (PEDRO TEIXEIRA)
UPDATE schools SET inep_code = '338788' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' AND UPPER(TRIM(city)) = 'PEDRO TEIXEIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338788');

-- EE PADRE JOÃO BATISTA DE OLIVEIRA (PEQUERI)
UPDATE schools SET inep_code = '322547' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE JOÃO BATISTA DE OLIVEIRA' AND UPPER(TRIM(city)) = 'PEQUERI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322547');

-- EE DE ENSINO MÉDIO (ROCHEDO DE MINAS)
UPDATE schools SET inep_code = '342645' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' AND UPPER(TRIM(city)) = 'ROCHEDO DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342645');

-- EE JOÃO AUGUSTO DA SILVA BARRETO (SANTA BÁRBARA DO MONTE VERDE)
UPDATE schools SET inep_code = '342653' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO AUGUSTO DA SILVA BARRETO' AND UPPER(TRIM(city)) = 'SANTA BÁRBARA DO MONTE VERDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342653');

-- EE DYRCE JOSÉ  DA SILVA E SOUZA (SANTANA DO DESERTO)
UPDATE schools SET inep_code = '338796' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DYRCE JOSÉ  DA SILVA E SOUZA' AND UPPER(TRIM(city)) = 'SANTANA DO DESERTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338796');

-- EE PROFESSORA ROMILDA BARBOSA (SENADOR CORTES)
UPDATE schools SET inep_code = '342661' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ROMILDA BARBOSA' AND UPPER(TRIM(city)) = 'SENADOR CORTES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342661');

-- EE DE ENSINO MÉDIO (SIMÃO PEREIRA)
UPDATE schools SET inep_code = '338800' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' AND UPPER(TRIM(city)) = 'SIMÃO PEREIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338800');

-- EE PROFESSOR LUIZ ANTÔNIO PIRES DE SOUZA (ARGIRITA)
UPDATE schools SET inep_code = '305316' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR LUIZ ANTÔNIO PIRES DE SOUZA' AND UPPER(TRIM(city)) = 'ARGIRITA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305316');

-- EE ISA MORAES FREITAS (ITAMARATI DE MINAS)
UPDATE schools SET inep_code = '305324' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ISA MORAES FREITAS' AND UPPER(TRIM(city)) = 'ITAMARATI DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305324');

-- EE EMÍLIA MARIA DINIZ (DURANDÉ)
UPDATE schools SET inep_code = '319066' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE EMÍLIA MARIA DINIZ' AND UPPER(TRIM(city)) = 'DURANDÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '319066');

-- EE ANTÔNIO SILVA ROCHA (MANHUAÇU)
UPDATE schools SET inep_code = '364940' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO SILVA ROCHA' AND UPPER(TRIM(city)) = 'MANHUAÇU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '364940');

-- EE DO BAIRRO BOA VISTA (MATIPÓ)
UPDATE schools SET inep_code = '205541' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DO BAIRRO BOA VISTA' AND UPPER(TRIM(city)) = 'MATIPÓ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '205541');

-- CESEC VALDIR PINHEIRO DE LACERDA (MUTUM)
UPDATE schools SET inep_code = '312479' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC VALDIR PINHEIRO DE LACERDA' AND UPPER(TRIM(city)) = 'MUTUM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312479');

-- EE DALILA CERQUEIRA PESSOA (SANTA MARGARIDA)
UPDATE schools SET inep_code = '346381' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DALILA CERQUEIRA PESSOA' AND UPPER(TRIM(city)) = 'SANTA MARGARIDA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346381');

-- EE VIOLETA MAGESTE PEREIRA (SANTA MARGARIDA)
UPDATE schools SET inep_code = '346187' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE VIOLETA MAGESTE PEREIRA' AND UPPER(TRIM(city)) = 'SANTA MARGARIDA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346187');

-- EE EFIGÊNIA DE BARROS OLIVEIRA (BARÃO DE COCAIS)
UPDATE schools SET inep_code = '218723' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE EFIGÊNIA DE BARROS OLIVEIRA' AND UPPER(TRIM(city)) = 'BARÃO DE COCAIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218723');

-- CENTRO INTERESCOLAR DE CULTURA ARTE LINGUAGENS E TECNOLOGIAS (BELO HORIZONTE)
UPDATE schools SET inep_code = '364932' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO INTERESCOLAR DE CULTURA ARTE LINGUAGENS E TECNOLOGIAS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '364932');

-- CESEC POETA MURILO MENDES (BELO HORIZONTE)
UPDATE schools SET inep_code = '307068' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC POETA MURILO MENDES' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '307068');

-- EE JOVEM PROTAGONISTA (BELO HORIZONTE)
UPDATE schools SET inep_code = '322563' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOVEM PROTAGONISTA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322563');

-- EE LAR DOS MENINOS (BELO HORIZONTE)
UPDATE schools SET inep_code = '322555' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LAR DOS MENINOS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322555');

-- EE PROFESSOR NEIDSON RODRIGUES (BELO HORIZONTE)
UPDATE schools SET inep_code = '342432' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR NEIDSON RODRIGUES' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342432');

-- EE PROFESSORA ALAÍDE LISBOA DE OLIVEIRA (BELO HORIZONTE)
UPDATE schools SET inep_code = '342459' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ALAÍDE LISBOA DE OLIVEIRA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342459');