-- SENAI TIMÓTEO CFP LUCIANO JOSÉ DE ARAÚJO (TIMÓTEO)
UPDATE schools SET inep_code = '359440' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI TIMÓTEO CFP LUCIANO JOSÉ DE ARAÚJO' AND UPPER(TRIM(city)) = 'TIMÓTEO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '359440');

-- INSTITUTO EDUCACIONAL RAIO DE SOL (BUENÓPOLIS)
UPDATE schools SET inep_code = '325520' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL RAIO DE SOL' AND UPPER(TRIM(city)) = 'BUENÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '325520');

-- COL DOM SERAFIM COOPENCOR (CORINTO)
UPDATE schools SET inep_code = '145564' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COL DOM SERAFIM COOPENCOR' AND UPPER(TRIM(city)) = 'CORINTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '145564');

-- COLÉGIO BOM COMEÇO E LEME (CURVELO)
UPDATE schools SET inep_code = '377040' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO BOM COMEÇO E LEME' AND UPPER(TRIM(city)) = 'CURVELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '377040');

-- COLÉGIO DARWIN DE CURVELO (CURVELO)
UPDATE schools SET inep_code = '306169' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DARWIN DE CURVELO' AND UPPER(TRIM(city)) = 'CURVELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '306169');

-- COLÉGIO FRANCISCANO SANTO ANTÔNIO (CURVELO)
UPDATE schools SET inep_code = '145602' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO FRANCISCANO SANTO ANTÔNIO' AND UPPER(TRIM(city)) = 'CURVELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '145602');

-- COLÉGIO PADRE CURVELO (CURVELO)
UPDATE schools SET inep_code = '145581' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PADRE CURVELO' AND UPPER(TRIM(city)) = 'CURVELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '145581');

-- COLÉGIO TÉCNICO DA FACIC - COTEC (CURVELO)
UPDATE schools SET inep_code = '327506' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TÉCNICO DA FACIC - COTEC' AND UPPER(TRIM(city)) = 'CURVELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '327506');

-- INSTITUTO PEQUENO PRÍNCIPE EXPANSÃO (CURVELO)
UPDATE schools SET inep_code = '210498' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO PEQUENO PRÍNCIPE EXPANSÃO' AND UPPER(TRIM(city)) = 'CURVELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '210498');

-- REDE M2 - CURVELO (CURVELO)
UPDATE schools SET inep_code = '374830' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'REDE M2 - CURVELO' AND UPPER(TRIM(city)) = 'CURVELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '374830');

-- SENAC UNIDADE TÉCNICA DO CEP DE CURVELO (CURVELO)
UPDATE schools SET inep_code = '359092' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAC UNIDADE TÉCNICA DO CEP DE CURVELO' AND UPPER(TRIM(city)) = 'CURVELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '359092');

-- COLÉGIO DARWIN DE FELIXLÂNDIA (FELIXLÂNDIA)
UPDATE schools SET inep_code = '354368' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DARWIN DE FELIXLÂNDIA' AND UPPER(TRIM(city)) = 'FELIXLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '354368');

-- CENTRO DE TREINAMENTO ADEMAR MARRA (TRÊS MARIAS)
UPDATE schools SET inep_code = '339725' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE TREINAMENTO ADEMAR MARRA' AND UPPER(TRIM(city)) = 'TRÊS MARIAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '339725');

-- INSTITUTO EDUCACIONAL BARREIRO GRANDE (TRÊS MARIAS)
UPDATE schools SET inep_code = '145891' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL BARREIRO GRANDE' AND UPPER(TRIM(city)) = 'TRÊS MARIAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '145891');

-- NÚCLEO EDUCACIONAL DOCE MUNDO (TRÊS MARIAS)
UPDATE schools SET inep_code = '263966' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'NÚCLEO EDUCACIONAL DOCE MUNDO' AND UPPER(TRIM(city)) = 'TRÊS MARIAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '263966');

-- CENTRO EDUCACIONAL CRESCER (CAPELINHA)
UPDATE schools SET inep_code = '325503' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL CRESCER' AND UPPER(TRIM(city)) = 'CAPELINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '325503');

-- COLÉGIO VENCER (CAPELINHA)
UPDATE schools SET inep_code = '365106' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO VENCER' AND UPPER(TRIM(city)) = 'CAPELINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '365106');

-- COLÉGIO INTEGRA (CONCEIÇÃO DO MATO DENTRO)
UPDATE schools SET inep_code = '374709' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO INTEGRA' AND UPPER(TRIM(city)) = 'CONCEIÇÃO DO MATO DENTRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '374709');

-- COLEGUIUM - UNIDADE CONCEIÇÃO DO MATO DENTRO (CONCEIÇÃO DO MATO DENTRO)
UPDATE schools SET inep_code = '359610' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLEGUIUM - UNIDADE CONCEIÇÃO DO MATO DENTRO' AND UPPER(TRIM(city)) = 'CONCEIÇÃO DO MATO DENTRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '359610');

-- SENAI DE CONCEIÇÃO DE MATO DENTRO CENTRO DE FORMAÇÃO PROFISSIONAL JOSÉ APARECIDO DE OLIVEIRA (CONCEIÇÃO DO MATO DENTRO)
UPDATE schools SET inep_code = '358932' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI DE CONCEIÇÃO DE MATO DENTRO CENTRO DE FORMAÇÃO PROFISSIONAL JOSÉ APARECIDO DE OLIVEIRA' AND UPPER(TRIM(city)) = 'CONCEIÇÃO DO MATO DENTRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '358932');

-- COLÉGIO DE EDUCAÇÃO INTEGRADA - CEI (DIAMANTINA)
UPDATE schools SET inep_code = '350320' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DE EDUCAÇÃO INTEGRADA - CEI' AND UPPER(TRIM(city)) = 'DIAMANTINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '350320');

-- MESTRA - CENTRO EDUCACIONAL MESTRA JOANA LOPES (DIAMANTINA)
UPDATE schools SET inep_code = '346357' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'MESTRA - CENTRO EDUCACIONAL MESTRA JOANA LOPES' AND UPPER(TRIM(city)) = 'DIAMANTINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346357');

-- SENAC UNIDADE DE ENSINO TÉCNICO DO CEP DE DIAMANTINA (DIAMANTINA)
UPDATE schools SET inep_code = '359106' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAC UNIDADE DE ENSINO TÉCNICO DO CEP DE DIAMANTINA' AND UPPER(TRIM(city)) = 'DIAMANTINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '359106');

-- CENTRO EDUCACIONAL CONEXÃO (ITAMARANDIBA)
UPDATE schools SET inep_code = '356301' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL CONEXÃO' AND UPPER(TRIM(city)) = 'ITAMARANDIBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '356301');

-- COLÉGIO POLITÉCNICO JOÃO PAULO II (ITAMARANDIBA)
UPDATE schools SET inep_code = '344842' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO POLITÉCNICO JOÃO PAULO II' AND UPPER(TRIM(city)) = 'ITAMARANDIBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '344842');

-- ESCOLA TÉCNICA YMBALO (SERRO)
UPDATE schools SET inep_code = '375187' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA YMBALO' AND UPPER(TRIM(city)) = 'SERRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '375187');

-- INSTITUTO EDUCACIONAL NOSSA SENHORA DA CONCEIÇÃO (SERRO)
UPDATE schools SET inep_code = '342076' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL NOSSA SENHORA DA CONCEIÇÃO' AND UPPER(TRIM(city)) = 'SERRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342076');

-- SENAI TURMALINA CENTRO DE FORMAÇÃO PROFISSIONAL (TURMALINA)
UPDATE schools SET inep_code = '358762' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI TURMALINA CENTRO DE FORMAÇÃO PROFISSIONAL' AND UPPER(TRIM(city)) = 'TURMALINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '358762');

-- ESCOLA FAMILIA AGRÍCOLA DE VEREDINHA (VEREDINHA)
UPDATE schools SET inep_code = '350133' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA FAMILIA AGRÍCOLA DE VEREDINHA' AND UPPER(TRIM(city)) = 'VEREDINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '350133');

-- CECON CENTRO EDUCACIONAL CONCEIÇÃO FERREIRA NUNES (ARCOS)
UPDATE schools SET inep_code = '304441' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CECON CENTRO EDUCACIONAL CONCEIÇÃO FERREIRA NUNES' AND UPPER(TRIM(city)) = 'ARCOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '304441');

-- CENTRO DE FORMAÇÃO PROFISSIONAL ELIEZER VITORINO COSTA (ARCOS)
UPDATE schools SET inep_code = '349666' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE FORMAÇÃO PROFISSIONAL ELIEZER VITORINO COSTA' AND UPPER(TRIM(city)) = 'ARCOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349666');

-- COLÉGIO LOSANGO DE ARCOS (ARCOS)
UPDATE schools SET inep_code = '321257' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO LOSANGO DE ARCOS' AND UPPER(TRIM(city)) = 'ARCOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '321257');

-- DOMINUS EDUCAÇÃO (ARCOS)
UPDATE schools SET inep_code = '350842' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'DOMINUS EDUCAÇÃO' AND UPPER(TRIM(city)) = 'ARCOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '350842');

-- ESCOLA NOSSA SENHORA DO CARMO (ARCOS)
UPDATE schools SET inep_code = '213721' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA NOSSA SENHORA DO CARMO' AND UPPER(TRIM(city)) = 'ARCOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '213721');

-- INPA - INSTITUTO PEDAGÓGICO ARCOENSE (ARCOS)
UPDATE schools SET inep_code = '260797' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INPA - INSTITUTO PEDAGÓGICO ARCOENSE' AND UPPER(TRIM(city)) = 'ARCOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '260797');

-- INSTITUTO EDUCACIONAL MARIA APARECIDA RIBEIRO (ARCOS)
UPDATE schools SET inep_code = '312835' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL MARIA APARECIDA RIBEIRO' AND UPPER(TRIM(city)) = 'ARCOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312835');

-- CENTRO EDUCACIONAL EVOLUÇÃO (BAMBUÍ)
UPDATE schools SET inep_code = '306576' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL EVOLUÇÃO' AND UPPER(TRIM(city)) = 'BAMBUÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '306576');

-- ESCOLA COOPERATIVA DE ENSINO DE BAMBUÍ (BAMBUÍ)
UPDATE schools SET inep_code = '266582' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA COOPERATIVA DE ENSINO DE BAMBUÍ' AND UPPER(TRIM(city)) = 'BAMBUÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '266582');

-- VS2 EDUCAÇÃO (BAMBUÍ)
UPDATE schools SET inep_code = '371718' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'VS2 EDUCAÇÃO' AND UPPER(TRIM(city)) = 'BAMBUÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '371718');

-- COLÉGIO DIAMANTE - UNIDADE IV (CARMO DA MATA)
UPDATE schools SET inep_code = '356999' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DIAMANTE - UNIDADE IV' AND UPPER(TRIM(city)) = 'CARMO DA MATA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '356999');

-- ESCOLA MONTEIRO LOBATO (CARMO DO CAJURU)
UPDATE schools SET inep_code = '293784' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA MONTEIRO LOBATO' AND UPPER(TRIM(city)) = 'CARMO DO CAJURU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '293784');

-- COLÉGIO PENTÁGONO (CARMÓPOLIS DE MINAS)
UPDATE schools SET inep_code = '368091' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PENTÁGONO' AND UPPER(TRIM(city)) = 'CARMÓPOLIS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368091');

-- NÚCLEO PEDAGÓGICO APRENDIZ (CARMÓPOLIS DE MINAS)
UPDATE schools SET inep_code = '254541' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'NÚCLEO PEDAGÓGICO APRENDIZ' AND UPPER(TRIM(city)) = 'CARMÓPOLIS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '254541');

-- CENTRO DE EDUCAÇÃO SAGRADO CORAÇÃO DE JESUS (CLÁUDIO)
UPDATE schools SET inep_code = '325864' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE EDUCAÇÃO SAGRADO CORAÇÃO DE JESUS' AND UPPER(TRIM(city)) = 'CLÁUDIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '325864');

-- SENAI CENTRO DE FORMAÇÃO PROFISSIONAL RISOLETA TOLENTINO NEVES (CLÁUDIO)
UPDATE schools SET inep_code = '346241' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI CENTRO DE FORMAÇÃO PROFISSIONAL RISOLETA TOLENTINO NEVES' AND UPPER(TRIM(city)) = 'CLÁUDIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346241');

-- CENTRO EDUCACIONAL CONCEIÇÃO FERREIRA NUNES - CECON (DIVINÓPOLIS)
UPDATE schools SET inep_code = '296279' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL CONCEIÇÃO FERREIRA NUNES - CECON' AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '296279');

-- CENTRO EDUCACIONAL CRIATIVO - CRECI (DIVINÓPOLIS)
UPDATE schools SET inep_code = '281921' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL CRIATIVO - CRECI' AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '281921');

-- CENTRO EDUCACIONAL DIVINÓPOLIS (DIVINÓPOLIS)
UPDATE schools SET inep_code = '291986' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL DIVINÓPOLIS' AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '291986');

-- CENTRO EDUCACIONAL JEAN PIAGET (DIVINÓPOLIS)
UPDATE schools SET inep_code = '252832' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL JEAN PIAGET' AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '252832');

-- COLÉGIO APOGEU (DIVINÓPOLIS)
UPDATE schools SET inep_code = '340014' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO APOGEU' AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '340014');

-- COLÉGIO MAGNIFICAT (DIVINÓPOLIS)
UPDATE schools SET inep_code = '376051' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MAGNIFICAT' AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '376051');

-- COLÉGIO PRESBITERIANO (DIVINÓPOLIS)
UPDATE schools SET inep_code = '327824' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PRESBITERIANO' AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '327824');

-- COLÉGIO SÍNTESE (DIVINÓPOLIS)
UPDATE schools SET inep_code = '321303' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SÍNTESE' AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '321303');

-- COLEGUIUM - UNIDADE DIVINÓPOLIS (DIVINÓPOLIS)
UPDATE schools SET inep_code = '374644' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLEGUIUM - UNIDADE DIVINÓPOLIS' AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '374644');

-- ESCOLA CRESCER PODIUM (DIVINÓPOLIS)
UPDATE schools SET inep_code = '236306' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA CRESCER PODIUM' AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '236306');

-- ESCOLA DE ENFERMAGEM SÃO JOÃO DE DEUS (DIVINÓPOLIS)
UPDATE schools SET inep_code = '258521' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DE ENFERMAGEM SÃO JOÃO DE DEUS' AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '258521');

-- OPÇÃO ENGETEC CURSOS TÉCNICOS (DIVINÓPOLIS)
UPDATE schools SET inep_code = '381454' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'OPÇÃO ENGETEC CURSOS TÉCNICOS' AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '381454');

-- PEREIRA E AMABILI CENTRO DE EDUCAÇÃO (DIVINÓPOLIS)
UPDATE schools SET inep_code = '338036' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'PEREIRA E AMABILI CENTRO DE EDUCAÇÃO' AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338036');

-- PROZ - UNIDADE DIVINÓPOLIS (DIVINÓPOLIS)
UPDATE schools SET inep_code = '379883' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'PROZ - UNIDADE DIVINÓPOLIS' AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '379883');

-- SENAC - UNIDADE DE ENSINO TÉCNICO DO CEP DE DIVINÓPOLIS (DIVINÓPOLIS)
UPDATE schools SET inep_code = '359050' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAC - UNIDADE DE ENSINO TÉCNICO DO CEP DE DIVINÓPOLIS' AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '359050');

-- SOPHIS EDUCACIONAL (DIVINÓPOLIS)
UPDATE schools SET inep_code = '371726' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SOPHIS EDUCACIONAL' AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '371726');

-- INSTITUTO EDUCACIONAL DE IGUATAMA (IGUATAMA)
UPDATE schools SET inep_code = '293792' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL DE IGUATAMA' AND UPPER(TRIM(city)) = 'IGUATAMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '293792');

-- ESCOLA TÉCNICA DE ITAGUARA (ITAGUARA)
UPDATE schools SET inep_code = '379867' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA DE ITAGUARA' AND UPPER(TRIM(city)) = 'ITAGUARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '379867');

-- CEC CENTRO EDUCACIONAL CONSTRUIR (ITAPECERICA)
UPDATE schools SET inep_code = '274216' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CEC CENTRO EDUCACIONAL CONSTRUIR' AND UPPER(TRIM(city)) = 'ITAPECERICA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '274216');

-- CENTRO TECNOLÓGICO DE FUNDIÇÃO MARCELINO CORRADI - SENAI (ITAÚNA)
UPDATE schools SET inep_code = '259250' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO TECNOLÓGICO DE FUNDIÇÃO MARCELINO CORRADI - SENAI' AND UPPER(TRIM(city)) = 'ITAÚNA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '259250');

-- COLÉGIO CENECISTA EDUCARE DE ITAÚNA (ITAÚNA)
UPDATE schools SET inep_code = '230014' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CENECISTA EDUCARE DE ITAÚNA' AND UPPER(TRIM(city)) = 'ITAÚNA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '230014');

-- COLÉGIO CIDADE DE ITAÚNA (ITAÚNA)
UPDATE schools SET inep_code = '312177' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CIDADE DE ITAÚNA' AND UPPER(TRIM(city)) = 'ITAÚNA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312177');

-- COLÉGIO RECANTO DO ESPÍRITO SANTO (ITAÚNA)
UPDATE schools SET inep_code = '376060' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO RECANTO DO ESPÍRITO SANTO' AND UPPER(TRIM(city)) = 'ITAÚNA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '376060');

-- SESI DARIO GONÇALVES DE SOUZA (ITAÚNA)
UPDATE schools SET inep_code = '313068' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SESI DARIO GONÇALVES DE SOUZA' AND UPPER(TRIM(city)) = 'ITAÚNA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '313068');

-- TEOREMA CENTRO DE ESTUDOS EDUCACIONAIS (ITAÚNA)
UPDATE schools SET inep_code = '315761' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'TEOREMA CENTRO DE ESTUDOS EDUCACIONAIS' AND UPPER(TRIM(city)) = 'ITAÚNA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '315761');

-- COLÉGIO ÁGUIA DE PRATA (LAGOA DA PRATA)
UPDATE schools SET inep_code = '222232' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ÁGUIA DE PRATA' AND UPPER(TRIM(city)) = 'LAGOA DA PRATA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '222232');

-- COLÉGIO LOSANGO (LAGOA DA PRATA)
UPDATE schools SET inep_code = '376272' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO LOSANGO' AND UPPER(TRIM(city)) = 'LAGOA DA PRATA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '376272');

-- ESCOLA DE ENFERMAGEM SANTA CLARA (LAGOA DA PRATA)
UPDATE schools SET inep_code = '294918' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DE ENFERMAGEM SANTA CLARA' AND UPPER(TRIM(city)) = 'LAGOA DA PRATA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '294918');

-- IMAM- INSTITUTO MARIA AUGUSTA MACHADO (LAGOA DA PRATA)
UPDATE schools SET inep_code = '246166' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'IMAM- INSTITUTO MARIA AUGUSTA MACHADO' AND UPPER(TRIM(city)) = 'LAGOA DA PRATA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246166');

-- INSTITUTO TUTORES DA EDUCAÇÃO (LAGOA DA PRATA)
UPDATE schools SET inep_code = '376507' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO TUTORES DA EDUCAÇÃO' AND UPPER(TRIM(city)) = 'LAGOA DA PRATA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '376507');

-- COLÉGIO MAIS (LUZ)
UPDATE schools SET inep_code = '367966' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MAIS' AND UPPER(TRIM(city)) = 'LUZ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '367966');

-- COLÉGIO SÃO RAFAEL (LUZ)
UPDATE schools SET inep_code = '318523' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SÃO RAFAEL' AND UPPER(TRIM(city)) = 'LUZ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '318523');

-- CENTRO EDUCACIONAL ESTRELA VERDE (NOVA SERRANA)
UPDATE schools SET inep_code = '325970' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL ESTRELA VERDE' AND UPPER(TRIM(city)) = 'NOVA SERRANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '325970');

-- COLÉGIO CIDADE NOVA SERRANA (NOVA SERRANA)
UPDATE schools SET inep_code = '320153' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CIDADE NOVA SERRANA' AND UPPER(TRIM(city)) = 'NOVA SERRANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '320153');

-- ESCOLA MODELO (NOVA SERRANA)
UPDATE schools SET inep_code = '296261' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA MODELO' AND UPPER(TRIM(city)) = 'NOVA SERRANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '296261');

-- INSTITUTO EDUCACIONAL SABER (NOVA SERRANA)
UPDATE schools SET inep_code = '342122' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL SABER' AND UPPER(TRIM(city)) = 'NOVA SERRANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342122');

-- SENAI CENTRO DE FORMAÇÃO PROFISSIONAL GENY JOSÉ FERREIRA (NOVA SERRANA)
UPDATE schools SET inep_code = '331236' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI CENTRO DE FORMAÇÃO PROFISSIONAL GENY JOSÉ FERREIRA' AND UPPER(TRIM(city)) = 'NOVA SERRANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '331236');

-- COLÉGIO DIAMANTE (OLIVEIRA)
UPDATE schools SET inep_code = '351598' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DIAMANTE' AND UPPER(TRIM(city)) = 'OLIVEIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '351598');

-- COLÉGIO PENTÁGONO (OLIVEIRA)
UPDATE schools SET inep_code = '349348' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PENTÁGONO' AND UPPER(TRIM(city)) = 'OLIVEIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349348');

-- INSTITUTO EDUCACIONAL APOGEU (OLIVEIRA)
UPDATE schools SET inep_code = '253391' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL APOGEU' AND UPPER(TRIM(city)) = 'OLIVEIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253391');

-- CENTRO EDUCACIONAL TUTORES (SANTO ANTÔNIO DO MONTE)
UPDATE schools SET inep_code = '377147' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL TUTORES' AND UPPER(TRIM(city)) = 'SANTO ANTÔNIO DO MONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '377147');

-- ESCOLA CHAVE DO SABER (SANTO ANTÔNIO DO MONTE)
UPDATE schools SET inep_code = '339172' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA CHAVE DO SABER' AND UPPER(TRIM(city)) = 'SANTO ANTÔNIO DO MONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '339172');

-- IMAC- INSTITUTO MARIA ANGÉLICA DE CASTRO (SANTO ANTÔNIO DO MONTE)
UPDATE schools SET inep_code = '292770' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'IMAC- INSTITUTO MARIA ANGÉLICA DE CASTRO' AND UPPER(TRIM(city)) = 'SANTO ANTÔNIO DO MONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '292770');

-- CENTRO EDUCACIONAL CRESCER (AIMORÉS)
UPDATE schools SET inep_code = '246174' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL CRESCER' AND UPPER(TRIM(city)) = 'AIMORÉS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246174');

-- ESCOLA TÉCNICA JOSÉ RODRIGUES DA SILVA (AIMORÉS)
UPDATE schools SET inep_code = '335070' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA JOSÉ RODRIGUES DA SILVA' AND UPPER(TRIM(city)) = 'AIMORÉS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '335070');

-- ESCOLA TIRADENTES (CONSELHEIRO PENA)
UPDATE schools SET inep_code = '351512' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TIRADENTES' AND UPPER(TRIM(city)) = 'CONSELHEIRO PENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '351512');

-- COLÉGIO BARROS OLIVEIRA (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '280135' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO BARROS OLIVEIRA' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '280135');

-- COLÉGIO CASTELO NEVES BARROS (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '314226' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CASTELO NEVES BARROS' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '314226');

-- COLÉGIO E PRÉ VESTIBULAR UNIVALE - FIBONACCI (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '369900' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO E PRÉ VESTIBULAR UNIVALE - FIBONACCI' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369900');

-- COLÉGIO GENOMA (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '329762' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO GENOMA' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '329762');

-- COLÉGIO HERINGER (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '303241' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO HERINGER' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '303241');

-- COLÉGIO RÚBIA COELHO (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '280283' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO RÚBIA COELHO' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '280283');

-- COLÉGIO VITORINO (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '303186' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO VITORINO' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '303186');

-- ESCOLA DO FUTURO (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '346454' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DO FUTURO' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346454');

-- ESCOLA NOVO SABER (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '303127' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA NOVO SABER' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '303127');

-- ESCOLA PROFISSIONALIZANTE EDUCAR E SAÚDE - PROES (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '318574' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA PROFISSIONALIZANTE EDUCAR E SAÚDE - PROES' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '318574');

-- ESCOLA SÃO CAMILO DE LELIS (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '369454' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SÃO CAMILO DE LELIS' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369454');

-- ESCOLA TÉCNICA JOSÉ RODRIGUES DA SILVA (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '313548' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA JOSÉ RODRIGUES DA SILVA' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '313548');

-- INSTITUTO EDUCACIONAL MILLENIUM (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '302961' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL MILLENIUM' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '302961');

-- SENAC- UNIDIDADE DE ENSINO TÉCNICO - CFP GOVERNADOR VALADARES (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '323934' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAC- UNIDIDADE DE ENSINO TÉCNICO - CFP GOVERNADOR VALADARES' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '323934');

-- SENAI CENTRO DE FORMAÇÃO PROFISSIONAL LUÍS CHAVES (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '276693' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI CENTRO DE FORMAÇÃO PROFISSIONAL LUÍS CHAVES' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '276693');

-- SESI ABÍLIO RODRIGUES PATTO (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '244163' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SESI ABÍLIO RODRIGUES PATTO' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '244163');

-- CEB - CENTRO EDUCACIONAL BATISTA (MANTENA)
UPDATE schools SET inep_code = '319236' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CEB - CENTRO EDUCACIONAL BATISTA' AND UPPER(TRIM(city)) = 'MANTENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '319236');

-- CENTRO TÉCNICO EDUCACIONAL DE SAÚDE (MANTENA)
UPDATE schools SET inep_code = '339377' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO TÉCNICO EDUCACIONAL DE SAÚDE' AND UPPER(TRIM(city)) = 'MANTENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '339377');

-- COLÉGIO BATISTA DE MANTENA (MANTENA)
UPDATE schools SET inep_code = '350567' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO BATISTA DE MANTENA' AND UPPER(TRIM(city)) = 'MANTENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '350567');

-- CENTRO EDUCACIONAL DIRCE PELEGRINI (RESPLENDOR)
UPDATE schools SET inep_code = '295302' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL DIRCE PELEGRINI' AND UPPER(TRIM(city)) = 'RESPLENDOR' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '295302');

-- COLÉGIO INTEGRAL DE RESPLENDOR (RESPLENDOR)
UPDATE schools SET inep_code = '366218' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO INTEGRAL DE RESPLENDOR' AND UPPER(TRIM(city)) = 'RESPLENDOR' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '366218');

-- COLÉGIO SOUZA SIMAN (GUANHÃES)
UPDATE schools SET inep_code = '377619' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SOUZA SIMAN' AND UPPER(TRIM(city)) = 'GUANHÃES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '377619');

-- ESPAÇO EDUCACIONAL NOVO SER (GUANHÃES)
UPDATE schools SET inep_code = '374385' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESPAÇO EDUCACIONAL NOVO SER' AND UPPER(TRIM(city)) = 'GUANHÃES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '374385');

-- IESGE - INSTITUTO DE ENSINO E GESTÃO EDUCACIONAL (GUANHÃES)
UPDATE schools SET inep_code = '354872' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'IESGE - INSTITUTO DE ENSINO E GESTÃO EDUCACIONAL' AND UPPER(TRIM(city)) = 'GUANHÃES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '354872');

-- INSTITUTO PRESBITERIANO GAMMON (GUANHÃES)
UPDATE schools SET inep_code = '254673' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO PRESBITERIANO GAMMON' AND UPPER(TRIM(city)) = 'GUANHÃES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '254673');

-- INSTITUTO EDUCACIONAL BRAVIEIRA (PEÇANHA)
UPDATE schools SET inep_code = '295256' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL BRAVIEIRA' AND UPPER(TRIM(city)) = 'PEÇANHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '295256');

-- ATUAL SISTEMA DE ENSINO (SABINÓPOLIS)
UPDATE schools SET inep_code = '331619' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ATUAL SISTEMA DE ENSINO' AND UPPER(TRIM(city)) = 'SABINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '331619');

-- CENTRO PEDAGÓGICO MOTIVAR (SABINÓPOLIS)
UPDATE schools SET inep_code = '253944' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO PEDAGÓGICO MOTIVAR' AND UPPER(TRIM(city)) = 'SABINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253944');

-- ESCOLA CURSOS PROFISSIONALIZANTES EDUCAR E SAÚDE (SÃO JOÃO EVANGELISTA)
UPDATE schools SET inep_code = '312312' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA CURSOS PROFISSIONALIZANTES EDUCAR E SAÚDE' AND UPPER(TRIM(city)) = 'SÃO JOÃO EVANGELISTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312312');

-- INSTITUTO CONEXÃO DE VIRGINÓPOLIS (VIRGINÓPOLIS)
UPDATE schools SET inep_code = '376604' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO CONEXÃO DE VIRGINÓPOLIS' AND UPPER(TRIM(city)) = 'VIRGINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '376604');

-- COLÉGIO IMACULADA CONCEIÇÃO (BRAZÓPOLIS)
UPDATE schools SET inep_code = '302848' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO IMACULADA CONCEIÇÃO' AND UPPER(TRIM(city)) = 'BRAZÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '302848');

-- COLÉGIO FÊNIX (CRISTINA)
UPDATE schools SET inep_code = '325538' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO FÊNIX' AND UPPER(TRIM(city)) = 'CRISTINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '325538');

-- CENTRO EDUCACIONAL LIMASSIS (DELFIM MOREIRA)
UPDATE schools SET inep_code = '316016' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL LIMASSIS' AND UPPER(TRIM(city)) = 'DELFIM MOREIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '316016');

-- COLÉGIO ÂNGULO (ITAJUBÁ)
UPDATE schools SET inep_code = '325848' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ÂNGULO' AND UPPER(TRIM(city)) = 'ITAJUBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '325848');

-- COLÉGIO CASTELO DO SABER (ITAJUBÁ)
UPDATE schools SET inep_code = '302911' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CASTELO DO SABER' AND UPPER(TRIM(city)) = 'ITAJUBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '302911');

-- COLÉGIO DA FEPI  - UNIDADE II (ITAJUBÁ)
UPDATE schools SET inep_code = '376361' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DA FEPI  - UNIDADE II' AND UPPER(TRIM(city)) = 'ITAJUBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '376361');

-- COLÉGIO EMPREENDER (ITAJUBÁ)
UPDATE schools SET inep_code = '364886' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO EMPREENDER' AND UPPER(TRIM(city)) = 'ITAJUBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '364886');

-- COLÉGIO GÊNESIS (ITAJUBÁ)
UPDATE schools SET inep_code = '257150' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO GÊNESIS' AND UPPER(TRIM(city)) = 'ITAJUBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '257150');

-- COLÉGIO SUCESSO (ITAJUBÁ)
UPDATE schools SET inep_code = '324434' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SUCESSO' AND UPPER(TRIM(city)) = 'ITAJUBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '324434');

-- CURSO G9 (ITAJUBÁ)
UPDATE schools SET inep_code = '239682' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CURSO G9' AND UPPER(TRIM(city)) = 'ITAJUBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '239682');

-- ESCOLA SESI VITOR VIEIRA DOS SANTOS (ITAJUBÁ)
UPDATE schools SET inep_code = '348503' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SESI VITOR VIEIRA DOS SANTOS' AND UPPER(TRIM(city)) = 'ITAJUBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '348503');

-- INSTITUTO MÁRIO BRAGANÇA (ITAJUBÁ)
UPDATE schools SET inep_code = '377627' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO MÁRIO BRAGANÇA' AND UPPER(TRIM(city)) = 'ITAJUBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '377627');

-- SENAC UNIDADE DE ENSINO TÉCNICO - CFP ITAJUBÁ (ITAJUBÁ)
UPDATE schools SET inep_code = '320099' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAC UNIDADE DE ENSINO TÉCNICO - CFP ITAJUBÁ' AND UPPER(TRIM(city)) = 'ITAJUBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '320099');

-- SENAI CENTRO DE FORMAÇÃO PROFISSIONAL AURELIANO CHAVES (ITAJUBÁ)
UPDATE schools SET inep_code = '250848' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI CENTRO DE FORMAÇÃO PROFISSIONAL AURELIANO CHAVES' AND UPPER(TRIM(city)) = 'ITAJUBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '250848');

-- SESI AURELIANO CHAVES (ITAJUBÁ)
UPDATE schools SET inep_code = '365289' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SESI AURELIANO CHAVES' AND UPPER(TRIM(city)) = 'ITAJUBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '365289');

-- COLÉGIO PRIMEIRO DE JUNHO (MARIA DA FÉ)
UPDATE schools SET inep_code = '279064' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PRIMEIRO DE JUNHO' AND UPPER(TRIM(city)) = 'MARIA DA FÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '279064');

-- ESCOLA DE EDUCAÇÃO PRIMEIRO MUNDO (PARAISÓPOLIS)
UPDATE schools SET inep_code = '302864' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DE EDUCAÇÃO PRIMEIRO MUNDO' AND UPPER(TRIM(city)) = 'PARAISÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '302864');

-- ESCOLA POLITÉCNICA DE PARAISÓPOLIS (PARAISÓPOLIS)
UPDATE schools SET inep_code = '294390' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA POLITÉCNICA DE PARAISÓPOLIS' AND UPPER(TRIM(city)) = 'PARAISÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '294390');

-- COLÉGIO RH+ (PEDRALVA)
UPDATE schools SET inep_code = '277843' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO RH+' AND UPPER(TRIM(city)) = 'PEDRALVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '277843');

-- ESC CULTURAL (PIRANGUINHO)
UPDATE schools SET inep_code = '280623' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESC CULTURAL' AND UPPER(TRIM(city)) = 'PIRANGUINHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '280623');

-- INSTITUTO AXIOMA - UNIDADE II (CAPINÓPOLIS)
UPDATE schools SET inep_code = '374857' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO AXIOMA - UNIDADE II' AND UPPER(TRIM(city)) = 'CAPINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '374857');

-- ÁPICE CENTRO EDUCACIONAL (ITUIUTABA)
UPDATE schools SET inep_code = '198862' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ÁPICE CENTRO EDUCACIONAL' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '198862');

-- CENTRO DE FORMAÇÃO PROFISSIONAL BEBÉ MARTINS (ITUIUTABA)
UPDATE schools SET inep_code = '313475' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE FORMAÇÃO PROFISSIONAL BEBÉ MARTINS' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '313475');

-- COL DOM BOSCO (ITUIUTABA)
UPDATE schools SET inep_code = '243051' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COL DOM BOSCO' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '243051');

-- COL GILDO VILELLA CANCELLA UNID II (ITUIUTABA)
UPDATE schools SET inep_code = '215686' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COL GILDO VILELLA CANCELLA UNID II' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '215686');

-- COLEGIO  MENEZES (ITUIUTABA)
UPDATE schools SET inep_code = '233048' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLEGIO  MENEZES' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '233048');

-- COLÉGIO EDUCAÇÃO (ITUIUTABA)
UPDATE schools SET inep_code = '198871' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO EDUCAÇÃO' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '198871');

-- COLÉGIO GILDO VILELLA CANCELLA UNID II (ITUIUTABA)
UPDATE schools SET inep_code = '332721' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO GILDO VILELLA CANCELLA UNID II' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '332721');

-- COLÉGIO SANTA TERESA (ITUIUTABA)
UPDATE schools SET inep_code = '198846' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SANTA TERESA' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '198846');

-- INSTITUTO AXIOMA (ITUIUTABA)
UPDATE schools SET inep_code = '370649' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO AXIOMA' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '370649');

-- SENAC UNID ENS TEC - CFP ITUIUTABA (ITUIUTABA)
UPDATE schools SET inep_code = '327182' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAC UNID ENS TEC - CFP ITUIUTABA' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '327182');

-- SESI  DOLORES PERES GOMES DA SILVA (ITUIUTABA)
UPDATE schools SET inep_code = '316628' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SESI  DOLORES PERES GOMES DA SILVA' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '316628');

-- CENTRO EDUCACIONAL DE SANTA VITÓRIA (SANTA VITÓRIA)
UPDATE schools SET inep_code = '243078' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL DE SANTA VITÓRIA' AND UPPER(TRIM(city)) = 'SANTA VITÓRIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '243078');

-- INSTITUTO AXIOMA - UNIDADE III (SANTA VITÓRIA)
UPDATE schools SET inep_code = '376795' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO AXIOMA - UNIDADE III' AND UPPER(TRIM(city)) = 'SANTA VITÓRIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '376795');

-- CENTRO EDUCACIONAL FLORISVALDO LOPES CRUZ (ESPINOSA)
UPDATE schools SET inep_code = '312339' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL FLORISVALDO LOPES CRUZ' AND UPPER(TRIM(city)) = 'ESPINOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312339');

-- COLÉGIO LÍDER (JAÍBA)
UPDATE schools SET inep_code = '369667' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO LÍDER' AND UPPER(TRIM(city)) = 'JAÍBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369667');

-- COLÉGIO PILARES (JAÍBA)
UPDATE schools SET inep_code = '347841' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PILARES' AND UPPER(TRIM(city)) = 'JAÍBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '347841');

-- ESCOLA SESI JAÍBA (JAÍBA)
UPDATE schools SET inep_code = '349488' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SESI JAÍBA' AND UPPER(TRIM(city)) = 'JAÍBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349488');

-- COLÉGIO PILARES (JANAÚBA)
UPDATE schools SET inep_code = '238155' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PILARES' AND UPPER(TRIM(city)) = 'JANAÚBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '238155');

-- COLÉGIO PRÊMIO (JANAÚBA)
UPDATE schools SET inep_code = '262153' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PRÊMIO' AND UPPER(TRIM(city)) = 'JANAÚBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '262153');

-- ESCOLA JANAUBENSE (JANAÚBA)
UPDATE schools SET inep_code = '210358' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA JANAUBENSE' AND UPPER(TRIM(city)) = 'JANAÚBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '210358');

-- INSTITUTO EDUCACIONAL NOVA CIDADANIA (JANAÚBA)
UPDATE schools SET inep_code = '363740' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO EDUCACIONAL NOVA CIDADANIA' AND UPPER(TRIM(city)) = 'JANAÚBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '363740');

-- COLÉGIO BASE (MATO VERDE)
UPDATE schools SET inep_code = '364673' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO BASE' AND UPPER(TRIM(city)) = 'MATO VERDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '364673');

-- COLÉGIO PODIUM (MATO VERDE)
UPDATE schools SET inep_code = '307815' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PODIUM' AND UPPER(TRIM(city)) = 'MATO VERDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '307815');

-- COLÉGIO ADIÇÃO (MONTE AZUL)
UPDATE schools SET inep_code = '344869' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ADIÇÃO' AND UPPER(TRIM(city)) = 'MONTE AZUL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '344869');

-- COLÉGIO FAVENORTE (MONTE AZUL)
UPDATE schools SET inep_code = '381020' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO FAVENORTE' AND UPPER(TRIM(city)) = 'MONTE AZUL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '381020');

-- SISTEMA PODIUM DE EDUCAÇÃO (MONTE AZUL)
UPDATE schools SET inep_code = '316849' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SISTEMA PODIUM DE EDUCAÇÃO' AND UPPER(TRIM(city)) = 'MONTE AZUL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '316849');

--  FAVEPORT (PORTEIRINHA)
UPDATE schools SET inep_code = '361488' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'FAVEPORT' AND UPPER(TRIM(city)) = 'PORTEIRINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '361488');

-- INSTITUTO PEDAGÓGICO CRESCER (PORTEIRINHA)
UPDATE schools SET inep_code = '322474' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO PEDAGÓGICO CRESCER' AND UPPER(TRIM(city)) = 'PORTEIRINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322474');

-- NÚCLEO EDUCACIONAL DE PORTEIRINHA (PORTEIRINHA)
UPDATE schools SET inep_code = '230502' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'NÚCLEO EDUCACIONAL DE PORTEIRINHA' AND UPPER(TRIM(city)) = 'PORTEIRINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '230502');

-- COLÉGIO CEIVA (JANUÁRIA)
UPDATE schools SET inep_code = '311821' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CEIVA' AND UPPER(TRIM(city)) = 'JANUÁRIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '311821');

-- COLÉGIO POLITÉCNICO DOM LUCIANO (JANUÁRIA)
UPDATE schools SET inep_code = '339245' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO POLITÉCNICO DOM LUCIANO' AND UPPER(TRIM(city)) = 'JANUÁRIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '339245');

-- ESCOLA TÉCNICA DE JANUÁRIA - ETEJ (JANUÁRIA)
UPDATE schools SET inep_code = '373532' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA DE JANUÁRIA - ETEJ' AND UPPER(TRIM(city)) = 'JANUÁRIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '373532');

-- INSTITUTO POLIVALENTE DE FORMAÇÃO TÉCNICA (JUVENÍLIA)
UPDATE schools SET inep_code = '366110' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO POLIVALENTE DE FORMAÇÃO TÉCNICA' AND UPPER(TRIM(city)) = 'JUVENÍLIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '366110');

-- COLÉGIO PENTÁGONO (SÃO FRANCISCO)
UPDATE schools SET inep_code = '291862' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PENTÁGONO' AND UPPER(TRIM(city)) = 'SÃO FRANCISCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '291862');

-- COLÉGIO PLANO (SÃO FRANCISCO)
UPDATE schools SET inep_code = '378143' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PLANO' AND UPPER(TRIM(city)) = 'SÃO FRANCISCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '378143');

-- ESCOLA FAMÍLIA AGRÍCOLA TABOCAL (SÃO FRANCISCO)
UPDATE schools SET inep_code = '338559' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA FAMÍLIA AGRÍCOLA TABOCAL' AND UPPER(TRIM(city)) = 'SÃO FRANCISCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338559');

-- CENTRO EDUCACIONAL UBAÍ (UBAÍ)
UPDATE schools SET inep_code = '342890' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL UBAÍ' AND UPPER(TRIM(city)) = 'UBAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342890');

-- COLÉGIO ELITTE (BICAS)
UPDATE schools SET inep_code = '343072' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ELITTE' AND UPPER(TRIM(city)) = 'BICAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '343072');

-- COLÉGIO FUTURO (BICAS)
UPDATE schools SET inep_code = '311481' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO FUTURO' AND UPPER(TRIM(city)) = 'BICAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '311481');

-- CEFORTEC - SAÚDE CENTRO EDUCACIONAL DE FORMAÇÃO (JUIZ DE FORA)
UPDATE schools SET inep_code = '310867' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CEFORTEC - SAÚDE CENTRO EDUCACIONAL DE FORMAÇÃO' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310867');

-- CENTRO DE EDUCAÇÃO INTERATIVA (JUIZ DE FORA)
UPDATE schools SET inep_code = '296473' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE EDUCAÇÃO INTERATIVA' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '296473');

-- CENTRO EDUCACIONAL AGUIAR CELEGHINI (JUIZ DE FORA)
UPDATE schools SET inep_code = '306240' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL AGUIAR CELEGHINI' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '306240');

-- CENTRO EDUCACIONAL CAVE (JUIZ DE FORA)
UPDATE schools SET inep_code = '354910' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL CAVE' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '354910');

-- CENTRO EDUCACIONAL PROFESSOR SANT'ANNA (JUIZ DE FORA)
UPDATE schools SET inep_code = '220001' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL PROFESSOR SANT''ANNA' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '220001');

-- CENTRO EDUCACIONAL RAS (JUIZ DE FORA)
UPDATE schools SET inep_code = '311103' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL RAS' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '311103');

-- CENTRO EDUCACIONAL SABER É VIVER (JUIZ DE FORA)
UPDATE schools SET inep_code = '306207' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL SABER É VIVER' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '306207');

-- CENTRO INTEGRADO DE DESENVOLVIMENTO DO TRABALHADOR LUIZ ADELAR  SCHEUER-SENAI (JUIZ DE FORA)
UPDATE schools SET inep_code = '316733' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO INTEGRADO DE DESENVOLVIMENTO DO TRABALHADOR LUIZ ADELAR  SCHEUER-SENAI' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '316733');

-- COLÉGIO APOGEU - UNIDADE II (JUIZ DE FORA)
UPDATE schools SET inep_code = '356816' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO APOGEU - UNIDADE II' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '356816');

-- COLÉGIO APOGEU - UNIDADE III (JUIZ DE FORA)
UPDATE schools SET inep_code = '256285' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO APOGEU - UNIDADE III' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '256285');

-- COLÉGIO APOGEU - UNIDADE VI (JUIZ DE FORA)
UPDATE schools SET inep_code = '230278' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO APOGEU - UNIDADE VI' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '230278');

-- COLÉGIO APOGEU DE EDUCAÇÃO INFANTIL - UNIDADE NOVA ERA (JUIZ DE FORA)
UPDATE schools SET inep_code = '363383' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO APOGEU DE EDUCAÇÃO INFANTIL - UNIDADE NOVA ERA' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '363383');

-- COLÉGIO APOGEU- UNIDADE I (JUIZ DE FORA)
UPDATE schools SET inep_code = '317101' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO APOGEU- UNIDADE I' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '317101');

-- COLÉGIO ARAUTOS DO EVANGELHO - JUIZ DE FORA (JUIZ DE FORA)
UPDATE schools SET inep_code = '357227' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ARAUTOS DO EVANGELHO - JUIZ DE FORA' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '357227');

-- COLÉGIO CASCATINHA (JUIZ DE FORA)
UPDATE schools SET inep_code = '348279' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CASCATINHA' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '348279');

-- COLÉGIO CATÓLICO COMUNIDADE RESGATE (JUIZ DE FORA)
UPDATE schools SET inep_code = '369640' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CATÓLICO COMUNIDADE RESGATE' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369640');

-- COLÉGIO CERQUEIRA (JUIZ DE FORA)
UPDATE schools SET inep_code = '316571' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CERQUEIRA' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '316571');

-- COLÉGIO CONEXÃO (JUIZ DE FORA)
UPDATE schools SET inep_code = '310735' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CONEXÃO' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310735');

-- COLÉGIO CONEXÃO - UNIDADE II (JUIZ DE FORA)
UPDATE schools SET inep_code = '233102' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CONEXÃO - UNIDADE II' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '233102');

-- COLÉGIO CONEXÃO KIDS (JUIZ DE FORA)
UPDATE schools SET inep_code = '306266' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CONEXÃO KIDS' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '306266');

-- COLÉGIO DINÂMICO (JUIZ DE FORA)
UPDATE schools SET inep_code = '252018' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DINÂMICO' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '252018');

-- COLÉGIO E CURSO CATEDRAL VESTIBULARES (JUIZ DE FORA)
UPDATE schools SET inep_code = '312924' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO E CURSO CATEDRAL VESTIBULARES' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312924');

-- COLÉGIO E CURSO NOTA 10 (JUIZ DE FORA)
UPDATE schools SET inep_code = '367036' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO E CURSO NOTA 10' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '367036');

-- COLÉGIO EQUIPE DE JUIZ DE FORA (JUIZ DE FORA)
UPDATE schools SET inep_code = '324515' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO EQUIPE DE JUIZ DE FORA' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '324515');

-- COLÉGIO EXATO (JUIZ DE FORA)
UPDATE schools SET inep_code = '296554' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO EXATO' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '296554');

-- COLÉGIO MAGNUS (JUIZ DE FORA)
UPDATE schools SET inep_code = '246883' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MAGNUS' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246883');

-- COLÉGIO NOVA ERA (JUIZ DE FORA)
UPDATE schools SET inep_code = '341355' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO NOVA ERA' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '341355');

-- COLÉGIO PIRÂMIDE (JUIZ DE FORA)
UPDATE schools SET inep_code = '338923' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO PIRÂMIDE' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338923');

-- COLÉGIO RENASCER (JUIZ DE FORA)
UPDATE schools SET inep_code = '369764' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO RENASCER' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369764');

-- COLÉGIO ZONA NORTE (JUIZ DE FORA)
UPDATE schools SET inep_code = '340979' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ZONA NORTE' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '340979');

-- ESCOLA ADVENTISTA DE JUIZ DE FORA (JUIZ DE FORA)
UPDATE schools SET inep_code = '233137' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA ADVENTISTA DE JUIZ DE FORA' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '233137');

-- ESCOLA CULTURA VIVA (JUIZ DE FORA)
UPDATE schools SET inep_code = '219983' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA CULTURA VIVA' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '219983');

-- ESCOLA DE ENFERMAGEM SANTA CASA MISERICÓRDIA (JUIZ DE FORA)
UPDATE schools SET inep_code = '212300' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DE ENFERMAGEM SANTA CASA MISERICÓRDIA' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '212300');

-- ESCOLA DEGRAUS DE ENSINO (JUIZ DE FORA)
UPDATE schools SET inep_code = '212326' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DEGRAUS DE ENSINO' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '212326');

-- ESCOLA DIRETRIZES (JUIZ DE FORA)
UPDATE schools SET inep_code = '238244' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DIRETRIZES' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '238244');

-- ESCOLA ESTÁCIO JUIZ DE FORA (JUIZ DE FORA)
UPDATE schools SET inep_code = '371734' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA ESTÁCIO JUIZ DE FORA' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '371734');

-- ESCOLA HUB (JUIZ DE FORA)
UPDATE schools SET inep_code = '371785' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA HUB' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '371785');

-- ESCOLA TÉCNICA ELISABETH ROMBACH (JUIZ DE FORA)
UPDATE schools SET inep_code = '299031' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA ELISABETH ROMBACH' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '299031');

-- ESCOLA TÉCNICA PAULO CÉSAR DE MATTOS (JUIZ DE FORA)
UPDATE schools SET inep_code = '381462' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA PAULO CÉSAR DE MATTOS' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '381462');

-- ESCOLA TÉCNICA PLENARIUS (JUIZ DE FORA)
UPDATE schools SET inep_code = '373249' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA PLENARIUS' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '373249');

-- ESCOLA UIRANDÊ (JUIZ DE FORA)
UPDATE schools SET inep_code = '296465' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA UIRANDÊ' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '296465');

-- GRAU TÉCNICO - UNIDADE JUIZ DE FORA (JUIZ DE FORA)
UPDATE schools SET inep_code = '380300' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'GRAU TÉCNICO - UNIDADE JUIZ DE FORA' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '380300');

-- IMPACTO ESCOLA DE SAÚDE (JUIZ DE FORA)
UPDATE schools SET inep_code = '306258' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'IMPACTO ESCOLA DE SAÚDE' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '306258');

-- IRME - UNIDADE II (JUIZ DE FORA)
UPDATE schools SET inep_code = '332828' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'IRME - UNIDADE II' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '332828');

-- IRMEP INSTITUTO REGINA MATER DE EDUCAÇÃO PROFISSIONAL (JUIZ DE FORA)
UPDATE schools SET inep_code = '356506' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'IRMEP INSTITUTO REGINA MATER DE EDUCAÇÃO PROFISSIONAL' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '356506');

-- PAINEIRA ESCOLA WALDORF (JUIZ DE FORA)
UPDATE schools SET inep_code = '230308' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'PAINEIRA ESCOLA WALDORF' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '230308');

-- SENAC UNIDADE ENSINO TÉCNICO DE JUIZ DE FORA (JUIZ DE FORA)
UPDATE schools SET inep_code = '318671' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAC UNIDADE ENSINO TÉCNICO DE JUIZ DE FORA' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '318671');

-- SENAI CENTRO DE FORMAÇÃO PROFISSIONAL JOSÉ FAGUNDES NETO (JUIZ DE FORA)
UPDATE schools SET inep_code = '268348' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI CENTRO DE FORMAÇÃO PROFISSIONAL JOSÉ FAGUNDES NETO' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '268348');

-- SISTEMA DEGRAUS DE ENSINO (JUIZ DE FORA)
UPDATE schools SET inep_code = '353990' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SISTEMA DEGRAUS DE ENSINO' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '353990');

-- UNITEC EDUCACIONAL (JUIZ DE FORA)
UPDATE schools SET inep_code = '343420' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'UNITEC EDUCACIONAL' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '343420');

-- CENTRO TÉCNICO PROFISSIONAL DE LIMA DUARTE (LIMA DUARTE)
UPDATE schools SET inep_code = '356239' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO TÉCNICO PROFISSIONAL DE LIMA DUARTE' AND UPPER(TRIM(city)) = 'LIMA DUARTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '356239');

-- INSTITUTO PIAGET DE ENSINO (LIMA DUARTE)
UPDATE schools SET inep_code = '304981' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO PIAGET DE ENSINO' AND UPPER(TRIM(city)) = 'LIMA DUARTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '304981');

-- ESCOLA RECREAR - CASA DA EDUCAÇÃO E DA CULTURA (MATIAS BARBOSA)
UPDATE schools SET inep_code = '327433' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA RECREAR - CASA DA EDUCAÇÃO E DA CULTURA' AND UPPER(TRIM(city)) = 'MATIAS BARBOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '327433');

-- BIOTÉCNICO COLÉGIO E CURSOS (SANTOS DUMONT)
UPDATE schools SET inep_code = '372366' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'BIOTÉCNICO COLÉGIO E CURSOS' AND UPPER(TRIM(city)) = 'SANTOS DUMONT' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '372366');

-- INSTITUTO PROMOVE (SANTOS DUMONT)
UPDATE schools SET inep_code = '352640' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO PROMOVE' AND UPPER(TRIM(city)) = 'SANTOS DUMONT' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '352640');

-- NÚCLEO DE ENSINO ARCO-ÍRIS (SANTOS DUMONT)
UPDATE schools SET inep_code = '361119' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'NÚCLEO DE ENSINO ARCO-ÍRIS' AND UPPER(TRIM(city)) = 'SANTOS DUMONT' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '361119');

-- COLÉGIO SÃO JOÃO NEPOMUCENO (SÃO JOÃO NEPOMUCENO)
UPDATE schools SET inep_code = '325872' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SÃO JOÃO NEPOMUCENO' AND UPPER(TRIM(city)) = 'SÃO JOÃO NEPOMUCENO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '325872');

-- ESCOLA SESI  ROBSON BRAGA DE ANDRADE (SÃO JOÃO NEPOMUCENO)
UPDATE schools SET inep_code = '323748' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA SESI  ROBSON BRAGA DE ANDRADE' AND UPPER(TRIM(city)) = 'SÃO JOÃO NEPOMUCENO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '323748');

-- SENAI SÃO JOÃO NEPOMUCENO UI - ROBSON BRAGA DE ANDRADE (SÃO JOÃO NEPOMUCENO)
UPDATE schools SET inep_code = '368075' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'SENAI SÃO JOÃO NEPOMUCENO UI - ROBSON BRAGA DE ANDRADE' AND UPPER(TRIM(city)) = 'SÃO JOÃO NEPOMUCENO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368075');

-- CENTRO DE FORMAÇÃO PROFISSIONAL DE ALÉM PARAÍBA (ALÉM PARAÍBA)
UPDATE schools SET inep_code = '333662' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO DE FORMAÇÃO PROFISSIONAL DE ALÉM PARAÍBA' AND UPPER(TRIM(city)) = 'ALÉM PARAÍBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '333662');

-- CENTRO TÉCNICO DE EDUCAÇÃO PROFISSIONAL-CENTEP (ALÉM PARAÍBA)
UPDATE schools SET inep_code = '354058' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO TÉCNICO DE EDUCAÇÃO PROFISSIONAL-CENTEP' AND UPPER(TRIM(city)) = 'ALÉM PARAÍBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '354058');

-- COLÉGIO CENECISTA PROFESSOR SÉRGIO FERREIRA (ALÉM PARAÍBA)
UPDATE schools SET inep_code = '102326' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CENECISTA PROFESSOR SÉRGIO FERREIRA' AND UPPER(TRIM(city)) = 'ALÉM PARAÍBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '102326');

-- COLÉGIO DOS SANTOS ANJOS (ALÉM PARAÍBA)
UPDATE schools SET inep_code = '102318' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DOS SANTOS ANJOS' AND UPPER(TRIM(city)) = 'ALÉM PARAÍBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '102318');

-- EMAC -ESCOLA MARIA ANTONIETA CORTES (ALÉM PARAÍBA)
UPDATE schools SET inep_code = '266566' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EMAC -ESCOLA MARIA ANTONIETA CORTES' AND UPPER(TRIM(city)) = 'ALÉM PARAÍBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '266566');

-- CENTRO EDUCACIONAL CATAGUASES (CATAGUASES)
UPDATE schools SET inep_code = '322695' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL CATAGUASES' AND UPPER(TRIM(city)) = 'CATAGUASES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322695');

-- COLÉGIO CECÍLIA MEIRELES (CATAGUASES)
UPDATE schools SET inep_code = '357030' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CECÍLIA MEIRELES' AND UPPER(TRIM(city)) = 'CATAGUASES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '357030');

-- COLÉGIO CIDADE DE CATAGUASES (CATAGUASES)
UPDATE schools SET inep_code = '240761' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO CIDADE DE CATAGUASES' AND UPPER(TRIM(city)) = 'CATAGUASES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '240761');

-- COLÉGIO SOBERANO (CATAGUASES)
UPDATE schools SET inep_code = '334103' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO SOBERANO' AND UPPER(TRIM(city)) = 'CATAGUASES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '334103');

-- ESCOLA DE FORMAÇÃO GERENCIAL - EFG  - CATAGUASES (CATAGUASES)
UPDATE schools SET inep_code = '267627' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DE FORMAÇÃO GERENCIAL - EFG  - CATAGUASES' AND UPPER(TRIM(city)) = 'CATAGUASES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '267627');