-- EE PROFESSORA HENRIQUETA LISBOA (BELO HORIZONTE)
UPDATE schools SET inep_code = '342424' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA HENRIQUETA LISBOA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342424');

-- EE ZILDA ARNS NEUMANN (BELO HORIZONTE)
UPDATE schools SET inep_code = '342440' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ZILDA ARNS NEUMANN' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342440');

-- EE DOUTOR GAMA CERQUEIRA (BELO VALE)
UPDATE schools SET inep_code = '106020' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR GAMA CERQUEIRA' AND UPPER(TRIM(city)) = 'BELO VALE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106020');

-- EE EDMUNDO PENA (BOM JESUS DO AMPARO)
UPDATE schools SET inep_code = '102792' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE EDMUNDO PENA' AND UPPER(TRIM(city)) = 'BOM JESUS DO AMPARO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '102792');

-- EE ABELARDO DUARTE PASSOS (BRUMADINHO)
UPDATE schools SET inep_code = '351075' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ABELARDO DUARTE PASSOS' AND UPPER(TRIM(city)) = 'BRUMADINHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '351075');

-- EE SENADOR MELO VIANA (MOEDA)
UPDATE schools SET inep_code = '106437' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SENADOR MELO VIANA' AND UPPER(TRIM(city)) = 'MOEDA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106437');

-- EE MARIA JOSEFINA SALES WARDI (NOVA LIMA)
UPDATE schools SET inep_code = '305014' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARIA JOSEFINA SALES WARDI' AND UPPER(TRIM(city)) = 'NOVA LIMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305014');

-- EE JUQUINHA DE ALMEIDA (SABARÁ)
UPDATE schools SET inep_code = '222470' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JUQUINHA DE ALMEIDA' AND UPPER(TRIM(city)) = 'SABARÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '222470');

-- EE PRESIDENTE JUSCELINO KUBITSCHEK DE OLIVEIRA (SABARÁ)
UPDATE schools SET inep_code = '318418' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE JUSCELINO KUBITSCHEK DE OLIVEIRA' AND UPPER(TRIM(city)) = 'SABARÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '318418');

-- EE PROFESSOR JOÃO DE ARRUDA PINTO (SABARÁ)
UPDATE schools SET inep_code = '291102' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOÃO DE ARRUDA PINTO' AND UPPER(TRIM(city)) = 'SABARÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '291102');

-- EE PROFESSORA NHANITA (SANTA BÁRBARA)
UPDATE schools SET inep_code = '346284' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA NHANITA' AND UPPER(TRIM(city)) = 'SANTA BÁRBARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346284');

-- COLÉGIO TIRADENTES PMMG - UNIDADE GAMELEIRA (BELO HORIZONTE)
UPDATE schools SET inep_code = '307696' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG - UNIDADE GAMELEIRA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '307696');

-- COLÉGIO TIRADENTES PMMG- UNIDADE NOSSA SENHORA DAS VITÓRIAS (BELO HORIZONTE)
UPDATE schools SET inep_code = '307718' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG- UNIDADE NOSSA SENHORA DAS VITÓRIAS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '307718');

-- EE EMÍLIA CERDEIRA (BELO HORIZONTE)
UPDATE schools SET inep_code = '246433' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE EMÍLIA CERDEIRA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246433');

-- COLÉGIO TIRADENTES PMMG (BETIM)
UPDATE schools SET inep_code = '321061' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '321061');

-- EE ANTÔNIO AUGUSTO RIBEIRO (BETIM)
UPDATE schools SET inep_code = '212598' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO AUGUSTO RIBEIRO' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '212598');

-- EE DO BAIRRO AMAZONAS (BETIM)
UPDATE schools SET inep_code = '215082' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DO BAIRRO AMAZONAS' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '215082');

-- EE GABRIEL PASSOS (BETIM)
UPDATE schools SET inep_code = '361445' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GABRIEL PASSOS' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '361445');

-- EE PROFESSOR OSVALDO FRANCO (BETIM)
UPDATE schools SET inep_code = '212601' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR OSVALDO FRANCO' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '212601');

-- EE VINÍCIUS DE MORAES (BETIM)
UPDATE schools SET inep_code = '353787' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE VINÍCIUS DE MORAES' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '353787');

-- COLÉGIO TIRADENTES PMMG (CONTAGEM)
UPDATE schools SET inep_code = '307726' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '307726');

-- COLÉGIO TIRADENTES PMMG - UNIDADE AVELINO CAMARGOS (CONTAGEM)
UPDATE schools SET inep_code = '368903' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG - UNIDADE AVELINO CAMARGOS' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368903');

-- EE DE ENSINO MÉDIO (CONTAGEM)
UPDATE schools SET inep_code = '349283' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349283');

-- EE MARIA DE SALLES FERREIRA (CONTAGEM)
UPDATE schools SET inep_code = '212644' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARIA DE SALLES FERREIRA' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '212644');

-- EE ROBERTO FERNANDES (CONTAGEM)
UPDATE schools SET inep_code = '349275' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ROBERTO FERNANDES' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349275');

-- EE VINÍCIUS DE MORAES (CONTAGEM)
UPDATE schools SET inep_code = '212652' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE VINÍCIUS DE MORAES' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '212652');

-- EE MONTE SINAI (ESMERALDAS)
UPDATE schools SET inep_code = '353868' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MONTE SINAI' AND UPPER(TRIM(city)) = 'ESMERALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '353868');

-- EE PROFESSOR RAYMUNDO CÂNDIDO (ESMERALDAS)
UPDATE schools SET inep_code = '330647' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR RAYMUNDO CÂNDIDO' AND UPPER(TRIM(city)) = 'ESMERALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '330647');

-- EE ANTÔNIO MARINHO CAMPOS (IBIRITÉ)
UPDATE schools SET inep_code = '231665' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO MARINHO CAMPOS' AND UPPER(TRIM(city)) = 'IBIRITÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '231665');

-- EE ANTÔNIO PINHEIRO DINIZ (IBIRITÉ)
UPDATE schools SET inep_code = '322989' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO PINHEIRO DINIZ' AND UPPER(TRIM(city)) = 'IBIRITÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322989');

-- EE CORA CORALINA (IBIRITÉ)
UPDATE schools SET inep_code = '270407' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORA CORALINA' AND UPPER(TRIM(city)) = 'IBIRITÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '270407');

-- EE DE ENSINO FUNDAMENTAL E MÉDIO (IBIRITÉ)
UPDATE schools SET inep_code = '353507' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL E MÉDIO' AND UPPER(TRIM(city)) = 'IBIRITÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '353507');

-- EE IMPERATRIZ PIMENTA (IBIRITÉ)
UPDATE schools SET inep_code = '232483' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE IMPERATRIZ PIMENTA' AND UPPER(TRIM(city)) = 'IBIRITÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '232483');

-- EE JOÃO FERREIRA DE FREITAS (IBIRITÉ)
UPDATE schools SET inep_code = '223590' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO FERREIRA DE FREITAS' AND UPPER(TRIM(city)) = 'IBIRITÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '223590');

-- EE PROFESSORA ELZA CARDOSO RANGEL (IBIRITÉ)
UPDATE schools SET inep_code = '231673' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ELZA CARDOSO RANGEL' AND UPPER(TRIM(city)) = 'IBIRITÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '231673');

-- EE CRISTIANO CHAVES DE OLIVEIRA (IGARAPÉ)
UPDATE schools SET inep_code = '254720' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CRISTIANO CHAVES DE OLIVEIRA' AND UPPER(TRIM(city)) = 'IGARAPÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '254720');

-- EE JOELMA ALVES DE OLIVEIRA (IGARAPÉ)
UPDATE schools SET inep_code = '212466' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOELMA ALVES DE OLIVEIRA' AND UPPER(TRIM(city)) = 'IGARAPÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '212466');

-- EE PADRE CARLOS ROBERTO MARQUES (SÃO JOAQUIM DE BICAS)
UPDATE schools SET inep_code = '309842' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE CARLOS ROBERTO MARQUES' AND UPPER(TRIM(city)) = 'SÃO JOAQUIM DE BICAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '309842');

-- EE JOSÉ PEREIRA DOS SANTOS (SARZEDO)
UPDATE schools SET inep_code = '266094' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ PEREIRA DOS SANTOS' AND UPPER(TRIM(city)) = 'SARZEDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '266094');

-- EE PROFESSORA NILZA GOMES BERGMAN (SARZEDO)
UPDATE schools SET inep_code = '367826' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA NILZA GOMES BERGMAN' AND UPPER(TRIM(city)) = 'SARZEDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '367826');

-- COLÉGIO TIRADENTES PMMG- UNIDADE MINASCAIXA (BELO HORIZONTE)
UPDATE schools SET inep_code = '307700' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG- UNIDADE MINASCAIXA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '307700');

-- EE MARIA ANDRADE RESENDE (BELO HORIZONTE)
UPDATE schools SET inep_code = '253413' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARIA ANDRADE RESENDE' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253413');

-- EE PADRE JOÃO DE MATTOS ALMEIDA (BELO HORIZONTE)
UPDATE schools SET inep_code = '322636' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE JOÃO DE MATTOS ALMEIDA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322636');

-- EE PROFESSOR AGNELO CORREIA VIANA (BELO HORIZONTE)
UPDATE schools SET inep_code = '317357' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR AGNELO CORREIA VIANA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '317357');

-- EE INTENDENTE CÂMARA (MORRO DO PILAR)
UPDATE schools SET inep_code = '141291' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE INTENDENTE CÂMARA' AND UPPER(TRIM(city)) = 'MORRO DO PILAR' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141291');

-- EE ALESSANDRA SALUM CADAR (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '231720' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALESSANDRA SALUM CADAR' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '231720');

-- EE ALIZON THEMÓTER COSTA (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '339156' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALIZON THEMÓTER COSTA' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '339156');

-- EE ANTÔNIO RIGUEIRA DA FONSECA (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '222461' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO RIGUEIRA DA FONSECA' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '222461');

-- EE CARLOS DRUMMOND DE ANDRADE (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '310221' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CARLOS DRUMMOND DE ANDRADE' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310221');

-- EE CIDADE DOS MENINOS (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '277037' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CIDADE DOS MENINOS' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '277037');

-- EE CUSTÓDIO FÉLIX (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '317195' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CUSTÓDIO FÉLIX' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '317195');

-- EE DE ENSINO FUNDAMENTAL E MÉDIO (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '342564' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL E MÉDIO' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342564');

-- EE DJALMA MARQUES (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '317489' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DJALMA MARQUES' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '317489');

-- EE DR REYNALDO MARTINS MARQUES (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '342491' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DR REYNALDO MARTINS MARQUES' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342491');

-- EE GUADALAJARA (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '219045' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GUADALAJARA' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '219045');

-- EE HENRIQUE DE SOUZA FILHO - HENFIL (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '239381' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE HENRIQUE DE SOUZA FILHO - HENFIL' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '239381');

-- EE ITÁLIA CAUTIERO FRANCO (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '317349' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ITÁLIA CAUTIERO FRANCO' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '317349');

-- EE JOÃO CORREA ARMOND (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '231738' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO CORREA ARMOND' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '231738');

-- EE JOÃO DE ALMEIDA (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '218758' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO DE ALMEIDA' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218758');

-- EE JOSÉ SOARES DINIZ E SILVA (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '218715' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ SOARES DINIZ E SILVA' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218715');

-- EE MANOEL MARTINS DE MELO (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '218995' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MANOEL MARTINS DE MELO' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218995');

-- EE MARIA DA GLÓRIA ASSUNÇÃO (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '212679' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARIA DA GLÓRIA ASSUNÇÃO' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '212679');

-- EE MARIA DA PIEDADE SOUZA ROCHA (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '231711' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARIA DA PIEDADE SOUZA ROCHA' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '231711');

-- EE MARIA PEREIRA DE ARAÚJO (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '322628' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARIA PEREIRA DE ARAÚJO' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322628');

-- EE NOSSA SENHORA DAS NEVES (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '280160' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DAS NEVES' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '280160');

-- EE PROFESSOR PAULO FREIRE (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '310212' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR PAULO FREIRE' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310212');

-- EE SÃO JUDAS TADEU (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '219053' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO JUDAS TADEU' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '219053');

-- EE WASHINGTON MODESTO GONTIJO DE FARIA (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '339105' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE WASHINGTON MODESTO GONTIJO DE FARIA' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '339105');

-- EE EPHIGENIA DE JESUS WERNECK (SANTA LUZIA)
UPDATE schools SET inep_code = '351040' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE EPHIGENIA DE JESUS WERNECK' AND UPPER(TRIM(city)) = 'SANTA LUZIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '351040');

-- EE PRESIDENTE ITAMAR FRANCO (SANTA LUZIA)
UPDATE schools SET inep_code = '356727' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE ITAMAR FRANCO' AND UPPER(TRIM(city)) = 'SANTA LUZIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '356727');

-- EE DEPUTADO EMÍLIO DE VASCONCELOS (SANTANA DO RIACHO)
UPDATE schools SET inep_code = '330761' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DEPUTADO EMÍLIO DE VASCONCELOS' AND UPPER(TRIM(city)) = 'SANTANA DO RIACHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '330761');

-- EE BEATRIZ MARIA DE JESUS (SÃO JOSÉ DA LAPA)
UPDATE schools SET inep_code = '224103' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BEATRIZ MARIA DE JESUS' AND UPPER(TRIM(city)) = 'SÃO JOSÉ DA LAPA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '224103');

-- CESEC DE VESPASIANO (VESPASIANO)
UPDATE schools SET inep_code = '346306' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC DE VESPASIANO' AND UPPER(TRIM(city)) = 'VESPASIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346306');

-- COLÉGIO TIRADENTES PMMG (VESPASIANO)
UPDATE schools SET inep_code = '331121' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES PMMG' AND UPPER(TRIM(city)) = 'VESPASIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '331121');

-- EE  DE ENSINO FUNDAMENTAL E MÉDIO (VESPASIANO)
UPDATE schools SET inep_code = '374270' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE  DE ENSINO FUNDAMENTAL E MÉDIO' AND UPPER(TRIM(city)) = 'VESPASIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '374270');

-- EE DE ENSINO MÉDIO (VESPASIANO)
UPDATE schools SET inep_code = '374288' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' AND UPPER(TRIM(city)) = 'VESPASIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '374288');

-- EE JOSÉ GABRIEL DE OLIVEIRA (VESPASIANO)
UPDATE schools SET inep_code = '218979' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ GABRIEL DE OLIVEIRA' AND UPPER(TRIM(city)) = 'VESPASIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218979');

-- EE NILA FARAJ (VESPASIANO)
UPDATE schools SET inep_code = '218740' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NILA FARAJ' AND UPPER(TRIM(city)) = 'VESPASIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218740');

-- EE PEDRO ÁLVARES CABRAL (ABADIA DOS DOURADOS)
UPDATE schools SET inep_code = '200271' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PEDRO ÁLVARES CABRAL' AND UPPER(TRIM(city)) = 'ABADIA DOS DOURADOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '200271');

-- EE BENEDITO VALADARES (CASCALHO RICO)
UPDATE schools SET inep_code = '200280' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BENEDITO VALADARES' AND UPPER(TRIM(city)) = 'CASCALHO RICO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '200280');

-- EE ALÍRIO HERVAL (COROMANDEL)
UPDATE schools SET inep_code = '219011' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALÍRIO HERVAL' AND UPPER(TRIM(city)) = 'COROMANDEL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '219011');

-- EE JOAQUIM BOTELHO (COROMANDEL)
UPDATE schools SET inep_code = '200395' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOAQUIM BOTELHO' AND UPPER(TRIM(city)) = 'COROMANDEL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '200395');

-- EE JOAQUIM JOSÉ DE ASSUNÇÃO (COROMANDEL)
UPDATE schools SET inep_code = '200433' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOAQUIM JOSÉ DE ASSUNÇÃO' AND UPPER(TRIM(city)) = 'COROMANDEL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '200433');

-- EE PADRE LÁZARO MENEZES (COROMANDEL)
UPDATE schools SET inep_code = '219002' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE LÁZARO MENEZES' AND UPPER(TRIM(city)) = 'COROMANDEL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '219002');

-- EE SÃO GERALDO (COROMANDEL)
UPDATE schools SET inep_code = '200344' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO GERALDO' AND UPPER(TRIM(city)) = 'COROMANDEL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '200344');

-- EE ANITA RAMOS (DOURADOQUARA)
UPDATE schools SET inep_code = '307980' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANITA RAMOS' AND UPPER(TRIM(city)) = 'DOURADOQUARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '307980');

-- EE DE DOLEARINA (ESTRELA DO SUL)
UPDATE schools SET inep_code = '200531' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE DOLEARINA' AND UPPER(TRIM(city)) = 'ESTRELA DO SUL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '200531');

-- EE ROBERT KENNEDY (ESTRELA DO SUL)
UPDATE schools SET inep_code = '200484' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ROBERT KENNEDY' AND UPPER(TRIM(city)) = 'ESTRELA DO SUL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '200484');

-- EE CORONEL JOSÉ FALEIROS DE AGUIAR (GRUPIARA)
UPDATE schools SET inep_code = '200549' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL JOSÉ FALEIROS DE AGUIAR' AND UPPER(TRIM(city)) = 'GRUPIARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '200549');

-- CESEC ZENITH CAMPOS (MONTE CARMELO)
UPDATE schools SET inep_code = '200671' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC ZENITH CAMPOS' AND UPPER(TRIM(city)) = 'MONTE CARMELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '200671');

-- EE CLARA CHAVES (MONTE CARMELO)
UPDATE schools SET inep_code = '200573' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CLARA CHAVES' AND UPPER(TRIM(city)) = 'MONTE CARMELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '200573');

-- EE ELIAS DE MORAES (MONTE CARMELO)
UPDATE schools SET inep_code = '200603' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ELIAS DE MORAES' AND UPPER(TRIM(city)) = 'MONTE CARMELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '200603');

-- EE GREGORIANO CANEDO (MONTE CARMELO)
UPDATE schools SET inep_code = '200611' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GREGORIANO CANEDO' AND UPPER(TRIM(city)) = 'MONTE CARMELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '200611');

-- EE MELO VIANA (MONTE CARMELO)
UPDATE schools SET inep_code = '200638' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MELO VIANA' AND UPPER(TRIM(city)) = 'MONTE CARMELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '200638');

-- EE PROFESSOR VICENTE LOPES PEREZ (MONTE CARMELO)
UPDATE schools SET inep_code = '200654' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR VICENTE LOPES PEREZ' AND UPPER(TRIM(city)) = 'MONTE CARMELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '200654');

-- EE SANTA MARIA GORETTI (ROMARIA)
UPDATE schools SET inep_code = '200689' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SANTA MARIA GORETTI' AND UPPER(TRIM(city)) = 'ROMARIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '200689');

-- EE CARLOS ANTÔNIO DOS SANTOS (BRASÍLIA DE MINAS)
UPDATE schools SET inep_code = '231533' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CARLOS ANTÔNIO DOS SANTOS' AND UPPER(TRIM(city)) = 'BRASÍLIA DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '231533');

-- EE FRANCISCO XAVIER ANTUNES (BRASÍLIA DE MINAS)
UPDATE schools SET inep_code = '214981' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE FRANCISCO XAVIER ANTUNES' AND UPPER(TRIM(city)) = 'BRASÍLIA DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '214981');

-- EE BARREIRO DE BAIXO (CORAÇÃO DE JESUS)
UPDATE schools SET inep_code = '239291' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BARREIRO DE BAIXO' AND UPPER(TRIM(city)) = 'CORAÇÃO DE JESUS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '239291');

-- EE MARIA DA CONCEIÇÃO CHAVES (CORAÇÃO DE JESUS)
UPDATE schools SET inep_code = '239275' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARIA DA CONCEIÇÃO CHAVES' AND UPPER(TRIM(city)) = 'CORAÇÃO DE JESUS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '239275');

-- EE NOSSA SENHORA DA CONCEIÇÃO (CORAÇÃO DE JESUS)
UPDATE schools SET inep_code = '239259' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DA CONCEIÇÃO' AND UPPER(TRIM(city)) = 'CORAÇÃO DE JESUS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '239259');

-- EE NOSSA SENHORA DAS GRAÇAS (CORAÇÃO DE JESUS)
UPDATE schools SET inep_code = '239267' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DAS GRAÇAS' AND UPPER(TRIM(city)) = 'CORAÇÃO DE JESUS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '239267');

-- EE SÃO JOSÉ (CORAÇÃO DE JESUS)
UPDATE schools SET inep_code = '239241' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO JOSÉ' AND UPPER(TRIM(city)) = 'CORAÇÃO DE JESUS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '239241');

-- EE SÃO LUÍS (CORAÇÃO DE JESUS)
UPDATE schools SET inep_code = '239704' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO LUÍS' AND UPPER(TRIM(city)) = 'CORAÇÃO DE JESUS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '239704');

-- EE SÃO SEBASTIÃO (CORAÇÃO DE JESUS)
UPDATE schools SET inep_code = '239232' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO SEBASTIÃO' AND UPPER(TRIM(city)) = 'CORAÇÃO DE JESUS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '239232');

-- EE DE ENSINO FUNDAMENTAL E MÉDIO (CRISTÁLIA)
UPDATE schools SET inep_code = '351067' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL E MÉDIO' AND UPPER(TRIM(city)) = 'CRISTÁLIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '351067');

-- EE DE ENSINO MÉDIO (GRÃO MOGOL)
UPDATE schools SET inep_code = '346098' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' AND UPPER(TRIM(city)) = 'GRÃO MOGOL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346098');

-- EE SÃO JOSÉ DO RIO PRETO (ITACAMBIRA)
UPDATE schools SET inep_code = '253430' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO JOSÉ DO RIO PRETO' AND UPPER(TRIM(city)) = 'ITACAMBIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253430');

-- EE MANOEL PEREIRA DE ARAÚJO (JAPONVAR)
UPDATE schools SET inep_code = '239054' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MANOEL PEREIRA DE ARAÚJO' AND UPPER(TRIM(city)) = 'JAPONVAR' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '239054');

-- EE SÃO JUDAS TADEU (LUISLÂNDIA)
UPDATE schools SET inep_code = '276880' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO JUDAS TADEU' AND UPPER(TRIM(city)) = 'LUISLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '276880');

-- EE SANTA MARIA (MIRABELA)
UPDATE schools SET inep_code = '242217' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SANTA MARIA' AND UPPER(TRIM(city)) = 'MIRABELA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '242217');

-- EE DE ENSINO FUNDAMENTAL E MÉDIO (MONTES CLAROS)
UPDATE schools SET inep_code = '326682' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO FUNDAMENTAL E MÉDIO' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '326682');

-- EE DE ENSINO MÉDIO (MONTES CLAROS)
UPDATE schools SET inep_code = '346128' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346128');

-- EE DE ENSINO MÉDIO (MONTES CLAROS)
UPDATE schools SET inep_code = '353833' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '353833');

-- EE DE ENSINO MÉDIO (MONTES CLAROS)
UPDATE schools SET inep_code = '353841' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '353841');

-- EE GUTEMBERG TEODORO PENHA (MONTES CLAROS)
UPDATE schools SET inep_code = '346110' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GUTEMBERG TEODORO PENHA' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346110');

-- EE JOÃO MIGUEL TEIXEIRA DE JESUS (MONTES CLAROS)
UPDATE schools SET inep_code = '369861' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO MIGUEL TEIXEIRA DE JESUS' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369861');

-- EE LEVI DURÃES PERES (MONTES CLAROS)
UPDATE schools SET inep_code = '205664' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LEVI DURÃES PERES' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '205664');

-- EE PROFESSORA ELIZABETE PEREIRA SOARES (MONTES CLAROS)
UPDATE schools SET inep_code = '346101' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ELIZABETE PEREIRA SOARES' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346101');

-- EE PROFESSORA MARIA EMÍLIA SILVA SANTOS (MONTES CLAROS)
UPDATE schools SET inep_code = '369853' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA EMÍLIA SILVA SANTOS' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369853');

-- ESCOLA TÉCNICA DE SAÚDE DO CENTRO DE EDUCAÇÃO PROFISSIONAL E TECNOLÓGICA DA UNIMONTES (MONTES CLAROS)
UPDATE schools SET inep_code = '261891' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA DE SAÚDE DO CENTRO DE EDUCAÇÃO PROFISSIONAL E TECNOLÓGICA DA UNIMONTES' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '261891');

-- EE DE ENSINO MÉDIO (SÃO JOÃO DA PONTE)
UPDATE schools SET inep_code = '346160' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' AND UPPER(TRIM(city)) = 'SÃO JOÃO DA PONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346160');

-- EE DE ENSINO MÉDIO (SÃO JOÃO DA PONTE)
UPDATE schools SET inep_code = '353850' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE ENSINO MÉDIO' AND UPPER(TRIM(city)) = 'SÃO JOÃO DA PONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '353850');

-- EE LIODORA MARIA DA CONCEIÇÃO (SÃO JOÃO DA PONTE)
UPDATE schools SET inep_code = '356735' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LIODORA MARIA DA CONCEIÇÃO' AND UPPER(TRIM(city)) = 'SÃO JOÃO DA PONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '356735');

-- EE DIVANE ROCHA DE SÁ (SÃO JOÃO DO PARAÍSO)
UPDATE schools SET inep_code = '254321' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DIVANE ROCHA DE SÁ' AND UPPER(TRIM(city)) = 'SÃO JOÃO DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '254321');

-- EE MÁRIO COELHO (SÃO JOÃO DO PARAÍSO)
UPDATE schools SET inep_code = '319074' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MÁRIO COELHO' AND UPPER(TRIM(city)) = 'SÃO JOÃO DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '319074');

-- EE SANTO ANTÔNIO (SÃO JOÃO DO PARAÍSO)
UPDATE schools SET inep_code = '246255' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SANTO ANTÔNIO' AND UPPER(TRIM(city)) = 'SÃO JOÃO DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246255');

-- EE SÃO TIAGO (SÃO JOÃO DO PARAÍSO)
UPDATE schools SET inep_code = '254312' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO TIAGO' AND UPPER(TRIM(city)) = 'SÃO JOÃO DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '254312');

-- EE GERALDO ROCHA (ANTÔNIO PRADO DE MINAS)
UPDATE schools SET inep_code = '305278' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GERALDO ROCHA' AND UPPER(TRIM(city)) = 'ANTÔNIO PRADO DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305278');

-- EE ORMEZINDA ALVES DUARTE (SÃO SEBASTIÃO DA VARGEM ALEGRE)
UPDATE schools SET inep_code = '276901' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ORMEZINDA ALVES DUARTE' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DA VARGEM ALEGRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '276901');

-- EE JOSÉ MODESTO ÁVILA (BELA VISTA DE MINAS)
UPDATE schools SET inep_code = '102750' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ MODESTO ÁVILA' AND UPPER(TRIM(city)) = 'BELA VISTA DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '102750');

-- EE PADRE OSWALDO DE PODESTÁ (BELA VISTA DE MINAS)
UPDATE schools SET inep_code = '102733' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE OSWALDO DE PODESTÁ' AND UPPER(TRIM(city)) = 'BELA VISTA DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '102733');

-- EE PROFESSORA ADELINA DA CONCEIÇÃO MENDES (BELA VISTA DE MINAS)
UPDATE schools SET inep_code = '102784' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ADELINA DA CONCEIÇÃO MENDES' AND UPPER(TRIM(city)) = 'BELA VISTA DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '102784');

-- EE DONA JACY FRANCISCA GARCIA (DIONÍSIO)
UPDATE schools SET inep_code = '102831' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DONA JACY FRANCISCA GARCIA' AND UPPER(TRIM(city)) = 'DIONÍSIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '102831');

-- EE JOSÉ MARTINS DRUMOND (DIONÍSIO)
UPDATE schools SET inep_code = '102873' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ MARTINS DRUMOND' AND UPPER(TRIM(city)) = 'DIONÍSIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '102873');

-- EE PROFESSOR BENJAMIM ARAÚJO (DIONÍSIO)
UPDATE schools SET inep_code = '102814' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR BENJAMIM ARAÚJO' AND UPPER(TRIM(city)) = 'DIONÍSIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '102814');

-- CESEC PROFESSOR JÚLIO CARVALHO SOARES (FERROS)
UPDATE schools SET inep_code = '102971' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC PROFESSOR JÚLIO CARVALHO SOARES' AND UPPER(TRIM(city)) = 'FERROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '102971');

-- EE LEOPOLDINA BARROS DRUMOND (FERROS)
UPDATE schools SET inep_code = '103021' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LEOPOLDINA BARROS DRUMOND' AND UPPER(TRIM(city)) = 'FERROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103021');

-- EE PONCIANO PEREIRA DA COSTA (FERROS)
UPDATE schools SET inep_code = '103012' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PONCIANO PEREIRA DA COSTA' AND UPPER(TRIM(city)) = 'FERROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103012');

-- EE PROFESSOR ALCIDES FERNANDES DE ASSUNÇÃO (FERROS)
UPDATE schools SET inep_code = '102911' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ALCIDES FERNANDES DE ASSUNÇÃO' AND UPPER(TRIM(city)) = 'FERROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '102911');

-- CESEC PROFESSORA DORINHA FERREIRA (ITABIRA)
UPDATE schools SET inep_code = '103284' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC PROFESSORA DORINHA FERREIRA' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103284');

-- COLÉGIO TIRADENTES DA PMMG - CTPM - UNIDADE DOUTOR JOSÉ DE GRISOLIA (ITABIRA)
UPDATE schools SET inep_code = '370002' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO TIRADENTES DA PMMG - CTPM - UNIDADE DOUTOR JOSÉ DE GRISOLIA' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '370002');

-- EE ANTÔNIO LINHARES GUERRA (ITABIRA)
UPDATE schools SET inep_code = '103098' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO LINHARES GUERRA' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103098');

-- EE ANTÔNIO MARTINS PEREIRA (ITABIRA)
UPDATE schools SET inep_code = '103314' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO MARTINS PEREIRA' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103314');

-- EE DA FAZENDA DA BETÂNIA (ITABIRA)
UPDATE schools SET inep_code = '103179' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DA FAZENDA DA BETÂNIA' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103179');

-- EE DONA ELEONORA NUNES PEREIRA (ITABIRA)
UPDATE schools SET inep_code = '103101' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DONA ELEONORA NUNES PEREIRA' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103101');

-- EE JOSÉ RICARDO MARTINS FONSECA (ITABIRA)
UPDATE schools SET inep_code = '103152' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ RICARDO MARTINS FONSECA' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103152');

-- EE MAJOR LAGE (ITABIRA)
UPDATE schools SET inep_code = '103144' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MAJOR LAGE' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103144');

-- EE MESTRE ZECA AMÂNCIO (ITABIRA)
UPDATE schools SET inep_code = '103161' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MESTRE ZECA AMÂNCIO' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103161');

-- EE PROFESSOR EMÍLIO PEREIRA DE MAGALHÃES (ITABIRA)
UPDATE schools SET inep_code = '103209' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR EMÍLIO PEREIRA DE MAGALHÃES' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103209');

-- EE PROFESSOR MANOEL SOARES (ITABIRA)
UPDATE schools SET inep_code = '103306' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR MANOEL SOARES' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103306');

-- EE PROFESSORA MARCIANA MAGALHÃES (ITABIRA)
UPDATE schools SET inep_code = '103241' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARCIANA MAGALHÃES' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103241');

-- EE PROFESSORA PALMIRA MORAIS (ITABIRA)
UPDATE schools SET inep_code = '103225' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA PALMIRA MORAIS' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103225');

-- EE TRAJANO PROCÓPIO DE ALVARENGA SILVA MONTEIRO (ITABIRA)
UPDATE schools SET inep_code = '103187' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE TRAJANO PROCÓPIO DE ALVARENGA SILVA MONTEIRO' AND UPPER(TRIM(city)) = 'ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103187');

-- EE EMÍDIO DE SALES (ITAMBÉ DO MATO DENTRO)
UPDATE schools SET inep_code = '103331' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE EMÍDIO DE SALES' AND UPPER(TRIM(city)) = 'ITAMBÉ DO MATO DENTRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103331');

-- CESEC PROFESSORA ELZA MARIA (JOÃO MONLEVADE)
UPDATE schools SET inep_code = '103373' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC PROFESSORA ELZA MARIA' AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103373');

-- EE ALBERTO PEREIRA LIMA (JOÃO MONLEVADE)
UPDATE schools SET inep_code = '103349' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALBERTO PEREIRA LIMA' AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103349');

-- EE DONA JENNY FARIA (JOÃO MONLEVADE)
UPDATE schools SET inep_code = '103420' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DONA JENNY FARIA' AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103420');

-- EE DOUTOR GERALDO PARREIRAS (JOÃO MONLEVADE)
UPDATE schools SET inep_code = '103527' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR GERALDO PARREIRAS' AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103527');

-- EE LUIZ PRISCO DE BRAGA (JOÃO MONLEVADE)
UPDATE schools SET inep_code = '103489' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LUIZ PRISCO DE BRAGA' AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103489');

-- EE MANOEL LOUREIRO (JOÃO MONLEVADE)
UPDATE schools SET inep_code = '103497' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MANOEL LOUREIRO' AND UPPER(TRIM(city)) = 'JOÃO MONLEVADE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103497');

-- EE DA VILA SANTA ROSA (NOVA ERA)
UPDATE schools SET inep_code = '103616' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DA VILA SANTA ROSA' AND UPPER(TRIM(city)) = 'NOVA ERA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103616');

-- EE NOSSA SENHORA DE FÁTIMA (NOVA ERA)
UPDATE schools SET inep_code = '103586' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DE FÁTIMA' AND UPPER(TRIM(city)) = 'NOVA ERA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103586');

-- EE PADRE VIDIGAL (NOVA ERA)
UPDATE schools SET inep_code = '103594' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE VIDIGAL' AND UPPER(TRIM(city)) = 'NOVA ERA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103594');

-- EE LUIZA DOS SANTOS FERREIRA (PASSABÉM)
UPDATE schools SET inep_code = '103641' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LUIZA DOS SANTOS FERREIRA' AND UPPER(TRIM(city)) = 'PASSABÉM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103641');

-- CESEC MARTINHA DE OLIVEIRA ARAÚJO (RIO PIRACICABA)
UPDATE schools SET inep_code = '103721' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC MARTINHA DE OLIVEIRA ARAÚJO' AND UPPER(TRIM(city)) = 'RIO PIRACICABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103721');

-- EE ANTONINO FERREIRA MENDES (RIO PIRACICABA)
UPDATE schools SET inep_code = '103730' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTONINO FERREIRA MENDES' AND UPPER(TRIM(city)) = 'RIO PIRACICABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103730');

-- EE MARINHO SILVA (RIO PIRACICABA)
UPDATE schools SET inep_code = '338656' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARINHO SILVA' AND UPPER(TRIM(city)) = 'RIO PIRACICABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338656');

-- EE PROFESSOR ANTÔNIO FERNANDES PINTO (RIO PIRACICABA)
UPDATE schools SET inep_code = '103691' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ANTÔNIO FERNANDES PINTO' AND UPPER(TRIM(city)) = 'RIO PIRACICABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103691');

-- EE AGENOR GUERRA (SANTA MARIA DE ITABIRA)
UPDATE schools SET inep_code = '103802' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE AGENOR GUERRA' AND UPPER(TRIM(city)) = 'SANTA MARIA DE ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103802');

-- EE DOUTOR COSTA (SANTA MARIA DE ITABIRA)
UPDATE schools SET inep_code = '103756' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR COSTA' AND UPPER(TRIM(city)) = 'SANTA MARIA DE ITABIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103756');

-- EE PROFESSOR JOSÉ MADUREIRA DE OLIVEIRA (SANTO ANTÔNIO DO RIO ABAIXO)
UPDATE schools SET inep_code = '103829' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOSÉ MADUREIRA DE OLIVEIRA' AND UPPER(TRIM(city)) = 'SANTO ANTÔNIO DO RIO ABAIXO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103829');

-- EE CORONEL FRANCISCO ROLLA (SÃO DOMINGOS DO PRATA)
UPDATE schools SET inep_code = '103845' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL FRANCISCO ROLLA' AND UPPER(TRIM(city)) = 'SÃO DOMINGOS DO PRATA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103845');

-- EE CORONEL JOSÉ GOMES DE ARAÚJO (SÃO DOMINGOS DO PRATA)
UPDATE schools SET inep_code = '103900' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL JOSÉ GOMES DE ARAÚJO' AND UPPER(TRIM(city)) = 'SÃO DOMINGOS DO PRATA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103900');

-- EE CRISTIANO MACHADO (SÃO DOMINGOS DO PRATA)
UPDATE schools SET inep_code = '103969' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CRISTIANO MACHADO' AND UPPER(TRIM(city)) = 'SÃO DOMINGOS DO PRATA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103969');

-- EE MARQUES AFONSO (SÃO DOMINGOS DO PRATA)
UPDATE schools SET inep_code = '103888' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARQUES AFONSO' AND UPPER(TRIM(city)) = 'SÃO DOMINGOS DO PRATA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103888');

-- EE VICENTE DE PAULA FRAGA (SÃO DOMINGOS DO PRATA)
UPDATE schools SET inep_code = '103993' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE VICENTE DE PAULA FRAGA' AND UPPER(TRIM(city)) = 'SÃO DOMINGOS DO PRATA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '103993');

-- EE DESEMBARGADOR MOREIRA SANTOS (SÃO GONÇALO DO RIO ABAIXO)
UPDATE schools SET inep_code = '104051' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DESEMBARGADOR MOREIRA SANTOS' AND UPPER(TRIM(city)) = 'SÃO GONÇALO DO RIO ABAIXO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '104051');

-- EE ROMEU PERDIGÃO (SÃO JOSÉ DO GOIABAL)
UPDATE schools SET inep_code = '104108' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ROMEU PERDIGÃO' AND UPPER(TRIM(city)) = 'SÃO JOSÉ DO GOIABAL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '104108');

-- EE ODILON BEHRENS (SÃO SEBASTIÃO DO RIO PRETO)
UPDATE schools SET inep_code = '104141' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ODILON BEHRENS' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO RIO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '104141');

-- EE PADRE SIMIM (ACAIACA)
UPDATE schools SET inep_code = '106003' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE SIMIM' AND UPPER(TRIM(city)) = 'ACAIACA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106003');

-- EE PROFESSOR MARTINS (ACAIACA)
UPDATE schools SET inep_code = '330663' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR MARTINS' AND UPPER(TRIM(city)) = 'ACAIACA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '330663');

-- EE CORONEL NICOLAU SAMPAIO (DIOGO DE VASCONCELOS)
UPDATE schools SET inep_code = '106101' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL NICOLAU SAMPAIO' AND UPPER(TRIM(city)) = 'DIOGO DE VASCONCELOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106101');

-- EE DOUTOR RAUL SOARES (ITABIRITO)
UPDATE schools SET inep_code = '106143' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR RAUL SOARES' AND UPPER(TRIM(city)) = 'ITABIRITO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106143');

-- EE ENGENHEIRO QUEIROZ JÚNIOR (ITABIRITO)
UPDATE schools SET inep_code = '106151' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ENGENHEIRO QUEIROZ JÚNIOR' AND UPPER(TRIM(city)) = 'ITABIRITO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106151');

-- EE HENRIQUE MICHEL (ITABIRITO)
UPDATE schools SET inep_code = '106160' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE HENRIQUE MICHEL' AND UPPER(TRIM(city)) = 'ITABIRITO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106160');

-- EE INTENDENTE CÂMARA (ITABIRITO)
UPDATE schools SET inep_code = '106178' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE INTENDENTE CÂMARA' AND UPPER(TRIM(city)) = 'ITABIRITO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106178');

-- EE PROFESSOR TIBÚRCIO (ITABIRITO)
UPDATE schools SET inep_code = '106127' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR TIBÚRCIO' AND UPPER(TRIM(city)) = 'ITABIRITO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106127');

-- EE CÔNEGO BRAGA (MARIANA)
UPDATE schools SET inep_code = '106372' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CÔNEGO BRAGA' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106372');

-- EE CÔNEGO MAURO DE FARIA (MARIANA)
UPDATE schools SET inep_code = '106348' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CÔNEGO MAURO DE FARIA' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106348');

-- EE CORONEL BENJAMIM GUIMARÃES (MARIANA)
UPDATE schools SET inep_code = '106399' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL BENJAMIM GUIMARÃES' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106399');

-- EE DOM BENEVIDES (MARIANA)
UPDATE schools SET inep_code = '106275' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOM BENEVIDES' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106275');

-- EE DOM SILVÉRIO (MARIANA)
UPDATE schools SET inep_code = '106291' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOM SILVÉRIO' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106291');

-- EE DONA REPARATA DIAS DE OLIVEIRA (MARIANA)
UPDATE schools SET inep_code = '106259' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DONA REPARATA DIAS DE OLIVEIRA' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106259');

-- EE JOÃO RAMOS FILHO (MARIANA)
UPDATE schools SET inep_code = '356808' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO RAMOS FILHO' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '356808');

-- EE MONSENHOR MORAIS (MARIANA)
UPDATE schools SET inep_code = '106364' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MONSENHOR MORAIS' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106364');

-- EE PADRE VIEGAS (MARIANA)
UPDATE schools SET inep_code = '106381' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE VIEGAS' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106381');

-- EE PROFESSOR SOARES FERREIRA (MARIANA)
UPDATE schools SET inep_code = '106321' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR SOARES FERREIRA' AND UPPER(TRIM(city)) = 'MARIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106321');

-- EE ANTÔNIO PEREIRA (OURO PRETO)
UPDATE schools SET inep_code = '106631' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO PEREIRA' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106631');

-- EE DE OURO PRETO (OURO PRETO)
UPDATE schools SET inep_code = '106488' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE OURO PRETO' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106488');

-- EE DESEMBARGADOR HORÁCIO ANDRADE (OURO PRETO)
UPDATE schools SET inep_code = '106496' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DESEMBARGADOR HORÁCIO ANDRADE' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106496');

-- EE DOM PEDRO II (OURO PRETO)
UPDATE schools SET inep_code = '106500' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOM PEDRO II' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106500');

-- EE DOM VELLOSO (OURO PRETO)
UPDATE schools SET inep_code = '106470' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOM VELLOSO' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106470');

-- EE JOSÉ LEANDRO (OURO PRETO)
UPDATE schools SET inep_code = '106721' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ LEANDRO' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106721');

-- EE MARÍLIA DE DIRCEU (OURO PRETO)
UPDATE schools SET inep_code = '106526' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARÍLIA DE DIRCEU' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106526');

-- EE PADRE AFONSO DE LEMOS (OURO PRETO)
UPDATE schools SET inep_code = '106666' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE AFONSO DE LEMOS' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '106666');

-- EE PROFESSORA DAURA DE CARVALHO NETO (OURO PRETO)
UPDATE schools SET inep_code = '338915' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA DAURA DE CARVALHO NETO' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338915');

-- EE PROFESSORA MARIA DO CARMO ALMEIDA (OURO PRETO)
UPDATE schools SET inep_code = '351059' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA DO CARMO ALMEIDA' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '351059');

-- EE SORAMA GERALDA RICHARD XAVIER (BIQUINHAS)
UPDATE schools SET inep_code = '305626' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SORAMA GERALDA RICHARD XAVIER' AND UPPER(TRIM(city)) = 'BIQUINHAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305626');

-- EE JOSÉ RIBEIRO DE ANDRADE (CEDRO DO ABAETÉ)
UPDATE schools SET inep_code = '307343' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ RIBEIRO DE ANDRADE' AND UPPER(TRIM(city)) = 'CEDRO DO ABAETÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '307343');

-- EE INDÍGENA CAXIXÓ TAOCA SÉRGIA (MARTINHO CAMPOS)
UPDATE schools SET inep_code = '322865' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE INDÍGENA CAXIXÓ TAOCA SÉRGIA' AND UPPER(TRIM(city)) = 'MARTINHO CAMPOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322865');

-- EE AVANY VILLENA DINIZ (PARÁ DE MINAS)
UPDATE schools SET inep_code = '346152' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE AVANY VILLENA DINIZ' AND UPPER(TRIM(city)) = 'PARÁ DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346152');

-- EE PADRE LIBÉRIO (PARÁ DE MINAS)
UPDATE schools SET inep_code = '353477' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE LIBÉRIO' AND UPPER(TRIM(city)) = 'PARÁ DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '353477');

-- EE PROFESSOR WILSON DE MELO GUIMARÃES (PARÁ DE MINAS)
UPDATE schools SET inep_code = '233391' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR WILSON DE MELO GUIMARÃES' AND UPPER(TRIM(city)) = 'PARÁ DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '233391');

-- EE GUSTAVO CAPANEMA (PITANGUI)
UPDATE schools SET inep_code = '310522' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GUSTAVO CAPANEMA' AND UPPER(TRIM(city)) = 'PITANGUI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310522');

-- INSTITUTO TECNOLÓGICO DE AGROPECUÁRIA DE PITANGUI - ITAP (PITANGUI)
UPDATE schools SET inep_code = '217905' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO TECNOLÓGICO DE AGROPECUÁRIA DE PITANGUI - ITAP' AND UPPER(TRIM(city)) = 'PITANGUI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217905');

-- EE SEBASTIÃO CAMPOS (QUARTEL GERAL)
UPDATE schools SET inep_code = '305651' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SEBASTIÃO CAMPOS' AND UPPER(TRIM(city)) = 'QUARTEL GERAL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305651');

-- EE ALMINDA ALVES DA SILVA (BRASILÂNDIA DE MINAS)
UPDATE schools SET inep_code = '239402' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALMINDA ALVES DA SILVA' AND UPPER(TRIM(city)) = 'BRASILÂNDIA DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '239402');

-- EE CYRO GÓES (BRASILÂNDIA DE MINAS)
UPDATE schools SET inep_code = '108731' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CYRO GÓES' AND UPPER(TRIM(city)) = 'BRASILÂNDIA DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108731');

-- EE DOUTOR JOSÉ PACHECO PIMENTA (BRASILÂNDIA DE MINAS)
UPDATE schools SET inep_code = '108669' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR JOSÉ PACHECO PIMENTA' AND UPPER(TRIM(city)) = 'BRASILÂNDIA DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108669');

-- EE DOUTOR ANTÔNIO RIBEIRO (GUARDA-MOR)
UPDATE schools SET inep_code = '108481' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR ANTÔNIO RIBEIRO' AND UPPER(TRIM(city)) = 'GUARDA-MOR' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108481');

-- EE ARMINDA MARIA DA COSTA (JOÃO PINHEIRO)
UPDATE schools SET inep_code = '108553' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ARMINDA MARIA DA COSTA' AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108553');

-- EE CAPITÃO SPERIDIÃO (JOÃO PINHEIRO)
UPDATE schools SET inep_code = '108511' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CAPITÃO SPERIDIÃO' AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108511');

-- EE JOÃO GUIMARÃES ROSA (JOÃO PINHEIRO)
UPDATE schools SET inep_code = '108596' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO GUIMARÃES ROSA' AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108596');

-- EE JOSÉ ROMERO DA SILVEIRA (JOÃO PINHEIRO)
UPDATE schools SET inep_code = '220671' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ ROMERO DA SILVEIRA' AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '220671');

-- EE MARIA GONÇALVES AZEVEDO (JOÃO PINHEIRO)
UPDATE schools SET inep_code = '108561' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARIA GONÇALVES AZEVEDO' AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108561');

-- EE PROFESSORA ORLINDA SARAIVA SIMÕES (JOÃO PINHEIRO)
UPDATE schools SET inep_code = '108545' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ORLINDA SARAIVA SIMÕES' AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108545');

-- EE QUINTINO VARGAS (JOÃO PINHEIRO)
UPDATE schools SET inep_code = '108537' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE QUINTINO VARGAS' AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108537');

-- EE SEBASTIÃO SIMÃO DE MELO (JOÃO PINHEIRO)
UPDATE schools SET inep_code = '256234' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SEBASTIÃO SIMÃO DE MELO' AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '256234');

-- EE TANCREDO DE ALMEIDA NEVES (JOÃO PINHEIRO)
UPDATE schools SET inep_code = '108588' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE TANCREDO DE ALMEIDA NEVES' AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108588');

-- EE TEOTÔNIO BRANDÃO VILELA (JOÃO PINHEIRO)
UPDATE schools SET inep_code = '108766' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE TEOTÔNIO BRANDÃO VILELA' AND UPPER(TRIM(city)) = 'JOÃO PINHEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108766');

-- EE AFFONSO ROQUETTE (PARACATU)
UPDATE schools SET inep_code = '108839' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE AFFONSO ROQUETTE' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108839');

-- EE ALTINA DE PAULA GUIMARÃES (PARACATU)
UPDATE schools SET inep_code = '108863' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALTINA DE PAULA GUIMARÃES' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108863');

-- EE ANTÔNIO CARLOS (PARACATU)
UPDATE schools SET inep_code = '108855' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANTÔNIO CARLOS' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108855');

-- EE DA FAZENDA RIACHO LAFERSA (PARACATU)
UPDATE schools SET inep_code = '108901' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DA FAZENDA RIACHO LAFERSA' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108901');

-- EE DELANO BROCHADO ADJUTO (PARACATU)
UPDATE schools SET inep_code = '220663' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DELANO BROCHADO ADJUTO' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '220663');

-- EE DOM SERAFIM GOMES JARDIM (PARACATU)
UPDATE schools SET inep_code = '108952' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOM SERAFIM GOMES JARDIM' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108952');

-- EE DOUTOR VIRGÍLIO DE MELO FRANCO (PARACATU)
UPDATE schools SET inep_code = '108847' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR VIRGÍLIO DE MELO FRANCO' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108847');

-- EE JÚLIA CAMARGOS (PARACATU)
UPDATE schools SET inep_code = '108979' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JÚLIA CAMARGOS' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108979');

-- EE NEUSA PIMENTEL BARBOSA (PARACATU)
UPDATE schools SET inep_code = '353205' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NEUSA PIMENTEL BARBOSA' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '353205');

-- EE OLINDINA LOUREIRO (PARACATU)
UPDATE schools SET inep_code = '108880' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE OLINDINA LOUREIRO' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108880');

-- EE TEMÍSTOCLES ROCHA (PARACATU)
UPDATE schools SET inep_code = '108821' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE TEMÍSTOCLES ROCHA' AND UPPER(TRIM(city)) = 'PARACATU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108821');

-- EE CAROLINA SILVA (VAZANTE)
UPDATE schools SET inep_code = '308412' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CAROLINA SILVA' AND UPPER(TRIM(city)) = 'VAZANTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '308412');

-- EE DEPUTADO CÂNDIDO ULHOA (VAZANTE)
UPDATE schools SET inep_code = '109134' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DEPUTADO CÂNDIDO ULHOA' AND UPPER(TRIM(city)) = 'VAZANTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '109134');

-- EE DONA MARIANA SOLIS ROSA (VAZANTE)
UPDATE schools SET inep_code = '109177' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DONA MARIANA SOLIS ROSA' AND UPPER(TRIM(city)) = 'VAZANTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '109177');

-- EE PEDRO PEREIRA GUIMARÃES (VAZANTE)
UPDATE schools SET inep_code = '109151' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PEDRO PEREIRA GUIMARÃES' AND UPPER(TRIM(city)) = 'VAZANTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '109151');

-- EE PRESIDENTE JUSCELINO KUBITSCHEK DE OLIVEIRA (VAZANTE)
UPDATE schools SET inep_code = '109169' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE JUSCELINO KUBITSCHEK DE OLIVEIRA' AND UPPER(TRIM(city)) = 'VAZANTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '109169');

-- CESEC DOUTOR HÉLIO FERREIRA LOPES (ALPINÓPOLIS)
UPDATE schools SET inep_code = '114898' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC DOUTOR HÉLIO FERREIRA LOPES' AND UPPER(TRIM(city)) = 'ALPINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '114898');

-- EE DOM JOÃO VI (ALPINÓPOLIS)
UPDATE schools SET inep_code = '114863' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOM JOÃO VI' AND UPPER(TRIM(city)) = 'ALPINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '114863');

-- EE DONA INDÁ (ALPINÓPOLIS)
UPDATE schools SET inep_code = '114855' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DONA INDÁ' AND UPPER(TRIM(city)) = 'ALPINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '114855');