-- EE PROFESSOR BENEVIDES (ARINOS)
UPDATE schools SET inep_code = '231860' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR BENEVIDES' AND UPPER(TRIM(city)) = 'ARINOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '231860');

-- CESEC ESMÉRIA MARIA DO CARMO (BONFINÓPOLIS DE MINAS)
UPDATE schools SET inep_code = '108367' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC ESMÉRIA MARIA DO CARMO' AND UPPER(TRIM(city)) = 'BONFINÓPOLIS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108367');

-- EE CÂNDIDO ULHÔA (BONFINÓPOLIS DE MINAS)
UPDATE schools SET inep_code = '108243' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CÂNDIDO ULHÔA' AND UPPER(TRIM(city)) = 'BONFINÓPOLIS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108243');

-- EE ANÁLIA CARNEIRO DOS SANTOS (BURITIS)
UPDATE schools SET inep_code = '246204' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ANÁLIA CARNEIRO DOS SANTOS' AND UPPER(TRIM(city)) = 'BURITIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246204');

-- EE ARGEMIRO ANTÔNIO PRADO (BURITIS)
UPDATE schools SET inep_code = '108413' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ARGEMIRO ANTÔNIO PRADO' AND UPPER(TRIM(city)) = 'BURITIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108413');

-- EE JOSÉ GOMES PIMENTEL (BURITIS)
UPDATE schools SET inep_code = '108430' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ GOMES PIMENTEL' AND UPPER(TRIM(city)) = 'BURITIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108430');

-- EE SÃO DOMINGOS (BURITIS)
UPDATE schools SET inep_code = '108421' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO DOMINGOS' AND UPPER(TRIM(city)) = 'BURITIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108421');

-- EE DEPUTADO EDUARDO LUCAS (CABECEIRA GRANDE)
UPDATE schools SET inep_code = '109100' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DEPUTADO EDUARDO LUCAS' AND UPPER(TRIM(city)) = 'CABECEIRA GRANDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '109100');

-- EE JUVENAL DIOGO PIRES (CABECEIRA GRANDE)
UPDATE schools SET inep_code = '322598' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JUVENAL DIOGO PIRES' AND UPPER(TRIM(city)) = 'CABECEIRA GRANDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322598');

-- EE DOM BOSCO (DOM BOSCO)
UPDATE schools SET inep_code = '108375' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOM BOSCO' AND UPPER(TRIM(city)) = 'DOM BOSCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108375');

-- EE MARTINHO ANTÔNIO ORNELAS (FORMOSO)
UPDATE schools SET inep_code = '108456' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARTINHO ANTÔNIO ORNELAS' AND UPPER(TRIM(city)) = 'FORMOSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108456');

-- EE NOSSA SENHORA DE ABADIA (FORMOSO)
UPDATE schools SET inep_code = '205559' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DE ABADIA' AND UPPER(TRIM(city)) = 'FORMOSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '205559');

-- EE ALVARENGA PEIXOTO (NATALÂNDIA)
UPDATE schools SET inep_code = '108383' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ALVARENGA PEIXOTO' AND UPPER(TRIM(city)) = 'NATALÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108383');

-- EE DELVITO ALVES DA SILVA (UNAÍ)
UPDATE schools SET inep_code = '213292' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DELVITO ALVES DA SILVA' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '213292');

-- EE DOM ELISEU (UNAÍ)
UPDATE schools SET inep_code = '108987' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOM ELISEU' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108987');

-- EE DOMINGOS PINTO BROCHADO (UNAÍ)
UPDATE schools SET inep_code = '108995' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOMINGOS PINTO BROCHADO' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108995');

-- EE ELISA DE OLIVEIRA CAMPOS (UNAÍ)
UPDATE schools SET inep_code = '342475' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ELISA DE OLIVEIRA CAMPOS' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342475');

-- EE JUVÊNCIO MARTINS FERREIRA (UNAÍ)
UPDATE schools SET inep_code = '239399' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JUVÊNCIO MARTINS FERREIRA' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '239399');

-- EE MANOELA FARIA SOARES (UNAÍ)
UPDATE schools SET inep_code = '109037' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MANOELA FARIA SOARES' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '109037');

-- EE MARIA ASSUNES GONÇALVES (UNAÍ)
UPDATE schools SET inep_code = '109045' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARIA ASSUNES GONÇALVES' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '109045');

-- EE TANCREDO DE ALMEIDA NEVES (UNAÍ)
UPDATE schools SET inep_code = '109053' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE TANCREDO DE ALMEIDA NEVES' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '109053');

-- EE TEÓFILO MARTINS FERREIRA (UNAÍ)
UPDATE schools SET inep_code = '109002' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE TEÓFILO MARTINS FERREIRA' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '109002');

-- EE VIGÁRIO TORRES (UNAÍ)
UPDATE schools SET inep_code = '109011' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE VIGÁRIO TORRES' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '109011');

-- EE VIRGÍLIO DE MELO FRANCO (UNAÍ)
UPDATE schools SET inep_code = '109029' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE VIRGÍLIO DE MELO FRANCO' AND UPPER(TRIM(city)) = 'UNAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '109029');

-- EE DARCI RIBEIRO (URUANA DE MINAS)
UPDATE schools SET inep_code = '322601' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DARCI RIBEIRO' AND UPPER(TRIM(city)) = 'URUANA DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322601');

-- EE DIRCE MOURA LEITE (ALFENAS)
UPDATE schools SET inep_code = '170828' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DIRCE MOURA LEITE' AND UPPER(TRIM(city)) = 'ALFENAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170828');

-- EE DOUTOR EMÍLIO SILVEIRA (ALFENAS)
UPDATE schools SET inep_code = '170798' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR EMÍLIO SILVEIRA' AND UPPER(TRIM(city)) = 'ALFENAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170798');

-- EE DOUTOR NAPOLEÃO SALLES (ALFENAS)
UPDATE schools SET inep_code = '170887' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR NAPOLEÃO SALLES' AND UPPER(TRIM(city)) = 'ALFENAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170887');

-- EE JUDITH VIANNA (ALFENAS)
UPDATE schools SET inep_code = '170810' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JUDITH VIANNA' AND UPPER(TRIM(city)) = 'ALFENAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170810');

-- EE PADRE JOSÉ GRIMMINCK (ALFENAS)
UPDATE schools SET inep_code = '170895' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE JOSÉ GRIMMINCK' AND UPPER(TRIM(city)) = 'ALFENAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170895');

-- EE PREFEITO ISMAEL BRASIL CORRÊA (ALFENAS)
UPDATE schools SET inep_code = '170844' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PREFEITO ISMAEL BRASIL CORRÊA' AND UPPER(TRIM(city)) = 'ALFENAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170844');

-- EE PROFESSOR LEVINDO LAMBERT (ALFENAS)
UPDATE schools SET inep_code = '170852' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR LEVINDO LAMBERT' AND UPPER(TRIM(city)) = 'ALFENAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170852');

-- EE PROFESSOR VIANA (ALFENAS)
UPDATE schools SET inep_code = '170861' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR VIANA' AND UPPER(TRIM(city)) = 'ALFENAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170861');

-- EE SAMUEL ENGEL (ALFENAS)
UPDATE schools SET inep_code = '170879' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SAMUEL ENGEL' AND UPPER(TRIM(city)) = 'ALFENAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170879');

-- CESEC PROFESSORA SINHÁ LEITE (BOA ESPERANÇA)
UPDATE schools SET inep_code = '171280' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC PROFESSORA SINHÁ LEITE' AND UPPER(TRIM(city)) = 'BOA ESPERANÇA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '171280');

-- EE CASIMIRO SILVA (BOA ESPERANÇA)
UPDATE schools SET inep_code = '171123' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CASIMIRO SILVA' AND UPPER(TRIM(city)) = 'BOA ESPERANÇA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '171123');

-- EE DOUTOR JOAQUIM VILELA (BOA ESPERANÇA)
UPDATE schools SET inep_code = '171174' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR JOAQUIM VILELA' AND UPPER(TRIM(city)) = 'BOA ESPERANÇA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '171174');

-- EE DOUTOR SÁ BRITO (BOA ESPERANÇA)
UPDATE schools SET inep_code = '171191' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR SÁ BRITO' AND UPPER(TRIM(city)) = 'BOA ESPERANÇA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '171191');

-- EE PADRE JOÃO VIEIRA DA FONSECA (BOA ESPERANÇA)
UPDATE schools SET inep_code = '171212' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE JOÃO VIEIRA DA FONSECA' AND UPPER(TRIM(city)) = 'BOA ESPERANÇA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '171212');

-- EE PROFESSORA SÍLVIA MESQUITA (BOA ESPERANÇA)
UPDATE schools SET inep_code = '171255' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA SÍLVIA MESQUITA' AND UPPER(TRIM(city)) = 'BOA ESPERANÇA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '171255');

-- EE CLÓVIS SALGADO (CAMBUQUIRA)
UPDATE schools SET inep_code = '171301' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CLÓVIS SALGADO' AND UPPER(TRIM(city)) = 'CAMBUQUIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '171301');

-- EE MARIA UMBELINA DE ANDRADE GOMES (CAMBUQUIRA)
UPDATE schools SET inep_code = '171361' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MARIA UMBELINA DE ANDRADE GOMES' AND UPPER(TRIM(city)) = 'CAMBUQUIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '171361');

-- EE DOM INOCÊNCIO (CAMPANHA)
UPDATE schools SET inep_code = '171468' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOM INOCÊNCIO' AND UPPER(TRIM(city)) = 'CAMPANHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '171468');

-- EE VITAL BRASIL (CAMPANHA)
UPDATE schools SET inep_code = '171484' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE VITAL BRASIL' AND UPPER(TRIM(city)) = 'CAMPANHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '171484');

-- EE ZOROASTRO DE OLIVEIRA (CAMPANHA)
UPDATE schools SET inep_code = '171492' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE ZOROASTRO DE OLIVEIRA' AND UPPER(TRIM(city)) = 'CAMPANHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '171492');

-- EE DR JOSÉ MESQUITA NETTO (CAMPO DO MEIO)
UPDATE schools SET inep_code = '171581' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DR JOSÉ MESQUITA NETTO' AND UPPER(TRIM(city)) = 'CAMPO DO MEIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '171581');

-- EE PADRE CHICO (CAMPO DO MEIO)
UPDATE schools SET inep_code = '171549' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE CHICO' AND UPPER(TRIM(city)) = 'CAMPO DO MEIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '171549');

-- EE MONSENHOR TEÓFILO SAEZ (CAMPOS GERAIS)
UPDATE schools SET inep_code = '239143' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MONSENHOR TEÓFILO SAEZ' AND UPPER(TRIM(city)) = 'CAMPOS GERAIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '239143');

-- EE PADRE ANTÔNIO VIEIRA (CAMPOS GERAIS)
UPDATE schools SET inep_code = '171701' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE ANTÔNIO VIEIRA' AND UPPER(TRIM(city)) = 'CAMPOS GERAIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '171701');

-- EE PROFESSOR EDUARDO DANIEL FERREIRA DIAS (CAMPOS GERAIS)
UPDATE schools SET inep_code = '171646' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR EDUARDO DANIEL FERREIRA DIAS' AND UPPER(TRIM(city)) = 'CAMPOS GERAIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '171646');

-- EE PROFESSOR JOAQUIM JOSÉ DE OLIVEIRA (CAMPOS GERAIS)
UPDATE schools SET inep_code = '171689' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR JOAQUIM JOSÉ DE OLIVEIRA' AND UPPER(TRIM(city)) = 'CAMPOS GERAIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '171689');

-- EE PEDRO MESTRE (CARMO DA CACHOEIRA)
UPDATE schools SET inep_code = '171824' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PEDRO MESTRE' AND UPPER(TRIM(city)) = 'CARMO DA CACHOEIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '171824');

-- EE PROFESSOR WANDERLEY FERREIRA DE REZENDE (CARMO DA CACHOEIRA)
UPDATE schools SET inep_code = '171786' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR WANDERLEY FERREIRA DE REZENDE' AND UPPER(TRIM(city)) = 'CARMO DA CACHOEIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '171786');

-- EE JOÃO DE PAULA CAPRONI (CARVALHÓPOLIS)
UPDATE schools SET inep_code = '171999' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO DE PAULA CAPRONI' AND UPPER(TRIM(city)) = 'CARVALHÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '171999');

-- EE PADRE ANCHIETA (COQUEIRAL)
UPDATE schools SET inep_code = '172316' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE ANCHIETA' AND UPPER(TRIM(city)) = 'COQUEIRAL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '172316');

-- EE PROFESSORA CELINA DE REZENDE VILELA (CORDISLÂNDIA)
UPDATE schools SET inep_code = '172375' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA CELINA DE REZENDE VILELA' AND UPPER(TRIM(city)) = 'CORDISLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '172375');

-- EE BRASILINO ALVES PEREIRA (ELÓI MENDES)
UPDATE schools SET inep_code = '172499' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BRASILINO ALVES PEREIRA' AND UPPER(TRIM(city)) = 'ELÓI MENDES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '172499');

-- EE PROFESSORA NORMA DE BRITO PIEDADE MARTINS (ELÓI MENDES)
UPDATE schools SET inep_code = '172618' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA NORMA DE BRITO PIEDADE MARTINS' AND UPPER(TRIM(city)) = 'ELÓI MENDES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '172618');

-- EE SÃO LUIZ GONZAGA (ELÓI MENDES)
UPDATE schools SET inep_code = '319198' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO LUIZ GONZAGA' AND UPPER(TRIM(city)) = 'ELÓI MENDES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '319198');

-- EE TARGINO NOGUEIRA (ELÓI MENDES)
UPDATE schools SET inep_code = '172600' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE TARGINO NOGUEIRA' AND UPPER(TRIM(city)) = 'ELÓI MENDES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '172600');

-- EE PROFESSORA MARIA OLÍMPIA OLIVEIRA (FAMA)
UPDATE schools SET inep_code = '305006' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA OLÍMPIA OLIVEIRA' AND UPPER(TRIM(city)) = 'FAMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305006');

-- EE DR LAURO CORREA DO AMARAL (GUAPÉ)
UPDATE schools SET inep_code = '172693' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DR LAURO CORREA DO AMARAL' AND UPPER(TRIM(city)) = 'GUAPÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '172693');

-- EE PROFESSOR ANTÔNIO PASSOS SILVA (GUAPÉ)
UPDATE schools SET inep_code = '229326' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ANTÔNIO PASSOS SILVA' AND UPPER(TRIM(city)) = 'GUAPÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '229326');

-- EE NOSSA SENHORA APARECIDA (ILICÍNEA)
UPDATE schools SET inep_code = '172804' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA APARECIDA' AND UPPER(TRIM(city)) = 'ILICÍNEA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '172804');

-- EE JOÃO DE ALMEIDA LISBOA (LAMBARI)
UPDATE schools SET inep_code = '173011' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO DE ALMEIDA LISBOA' AND UPPER(TRIM(city)) = 'LAMBARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '173011');

-- EE JOÃO NUNES FERREIRA (LAMBARI)
UPDATE schools SET inep_code = '173029' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOÃO NUNES FERREIRA' AND UPPER(TRIM(city)) = 'LAMBARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '173029');

-- EE PROFESSORA MARIA RITA LISBOA PEREIRA SANTORO (LAMBARI)
UPDATE schools SET inep_code = '172987' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA RITA LISBOA PEREIRA SANTORO' AND UPPER(TRIM(city)) = 'LAMBARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '172987');

-- EE PROFESSOR FABREGAS (LUMINÁRIAS)
UPDATE schools SET inep_code = '134287' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR FABREGAS' AND UPPER(TRIM(city)) = 'LUMINÁRIAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134287');

-- CESEC DOUTOR TANCREDO DE ALMEIDA NEVES (MACHADO)
UPDATE schools SET inep_code = '173100' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CESEC DOUTOR TANCREDO DE ALMEIDA NEVES' AND UPPER(TRIM(city)) = 'MACHADO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '173100');

-- EE DE DOURADINHO (MACHADO)
UPDATE schools SET inep_code = '173223' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE DOURADINHO' AND UPPER(TRIM(city)) = 'MACHADO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '173223');

-- EE GABRIEL ODORICO (MACHADO)
UPDATE schools SET inep_code = '173045' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GABRIEL ODORICO' AND UPPER(TRIM(city)) = 'MACHADO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '173045');

-- EE IRACEMA RODRIGUES (MACHADO)
UPDATE schools SET inep_code = '173061' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE IRACEMA RODRIGUES' AND UPPER(TRIM(city)) = 'MACHADO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '173061');

-- EE PAULINA RIGOTTI DE CASTRO (MACHADO)
UPDATE schools SET inep_code = '173088' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PAULINA RIGOTTI DE CASTRO' AND UPPER(TRIM(city)) = 'MACHADO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '173088');

-- EE RUBENS GARCIA (MACHADO)
UPDATE schools SET inep_code = '173169' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE RUBENS GARCIA' AND UPPER(TRIM(city)) = 'MACHADO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '173169');

-- EE PADRE ROGÉRIO ABDALA (MONSENHOR PAULO)
UPDATE schools SET inep_code = '173266' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE ROGÉRIO ABDALA' AND UPPER(TRIM(city)) = 'MONSENHOR PAULO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '173266');

-- EE CORONEL JOAQUIM RIBEIRO (NEPOMUCENO)
UPDATE schools SET inep_code = '173282' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL JOAQUIM RIBEIRO' AND UPPER(TRIM(city)) = 'NEPOMUCENO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '173282');

-- EE DA FAZENDA BELA VISTA (NEPOMUCENO)
UPDATE schools SET inep_code = '173291' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DA FAZENDA BELA VISTA' AND UPPER(TRIM(city)) = 'NEPOMUCENO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '173291');

-- EE DE NAZARÉ DE MINAS (NEPOMUCENO)
UPDATE schools SET inep_code = '173428' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE NAZARÉ DE MINAS' AND UPPER(TRIM(city)) = 'NEPOMUCENO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '173428');

-- EE DE SANTO ANTÔNIO DO CRUZEIRO (NEPOMUCENO)
UPDATE schools SET inep_code = '173436' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DE SANTO ANTÔNIO DO CRUZEIRO' AND UPPER(TRIM(city)) = 'NEPOMUCENO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '173436');

-- EE DOUTOR ERNANE VILELA LIMA (NEPOMUCENO)
UPDATE schools SET inep_code = '173371' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR ERNANE VILELA LIMA' AND UPPER(TRIM(city)) = 'NEPOMUCENO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '173371');

-- EE LICAS DE LIMA (NEPOMUCENO)
UPDATE schools SET inep_code = '173380' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LICAS DE LIMA' AND UPPER(TRIM(city)) = 'NEPOMUCENO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '173380');

-- EE PADRE PICCININI (PARAGUAÇU)
UPDATE schools SET inep_code = '173533' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE PICCININI' AND UPPER(TRIM(city)) = 'PARAGUAÇU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '173533');

-- EE PEDRO LEITE (PARAGUAÇU)
UPDATE schools SET inep_code = '173622' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PEDRO LEITE' AND UPPER(TRIM(city)) = 'PARAGUAÇU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '173622');

-- EE PROFESSOR ALFREDO GALDINO (PARAGUAÇU)
UPDATE schools SET inep_code = '173631' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ALFREDO GALDINO' AND UPPER(TRIM(city)) = 'PARAGUAÇU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '173631');

-- EE JOSÉ BONIFÁCIO (POÇO FUNDO)
UPDATE schools SET inep_code = '173860' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE JOSÉ BONIFÁCIO' AND UPPER(TRIM(city)) = 'POÇO FUNDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '173860');

-- EE SÃO MARCOS (POÇO FUNDO)
UPDATE schools SET inep_code = '173878' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO MARCOS' AND UPPER(TRIM(city)) = 'POÇO FUNDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '173878');

-- EE DONA AUGUSTA (SANTANA DA VARGEM)
UPDATE schools SET inep_code = '174009' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DONA AUGUSTA' AND UPPER(TRIM(city)) = 'SANTANA DA VARGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174009');

-- EE PADRE JOÃO NEIVA (SANTANA DA VARGEM)
UPDATE schools SET inep_code = '173975' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PADRE JOÃO NEIVA' AND UPPER(TRIM(city)) = 'SANTANA DA VARGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '173975');

-- EE PROFESSORA ALDA DE MOURA CARVALHO (SÃO BENTO ABADE)
UPDATE schools SET inep_code = '174017' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ALDA DE MOURA CARVALHO' AND UPPER(TRIM(city)) = 'SÃO BENTO ABADE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174017');

-- EE BÁRBARA HELIODORA (SÃO GONÇALO DO SAPUCAÍ)
UPDATE schools SET inep_code = '174033' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BÁRBARA HELIODORA' AND UPPER(TRIM(city)) = 'SÃO GONÇALO DO SAPUCAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174033');

-- EE DOUTOR JOÃO PINHEIRO (SÃO GONÇALO DO SAPUCAÍ)
UPDATE schools SET inep_code = '174025' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR JOÃO PINHEIRO' AND UPPER(TRIM(city)) = 'SÃO GONÇALO DO SAPUCAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174025');

-- EE MINISTRO LUCIO DE MENDONÇA (SÃO GONÇALO DO SAPUCAÍ)
UPDATE schools SET inep_code = '174084' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MINISTRO LUCIO DE MENDONÇA' AND UPPER(TRIM(city)) = 'SÃO GONÇALO DO SAPUCAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174084');

-- EE AMÉRICO DIAS PEREIRA (TRÊS CORAÇÕES)
UPDATE schools SET inep_code = '174416' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE AMÉRICO DIAS PEREIRA' AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174416');

-- EE BUENO BRANDÃO (TRÊS CORAÇÕES)
UPDATE schools SET inep_code = '174386' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BUENO BRANDÃO' AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174386');

-- EE GODOFREDO RANGEL (TRÊS CORAÇÕES)
UPDATE schools SET inep_code = '174475' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE GODOFREDO RANGEL' AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174475');

-- EE LUIZA GOMES LEMOS (TRÊS CORAÇÕES)
UPDATE schools SET inep_code = '174432' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE LUIZA GOMES LEMOS' AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174432');

-- EE OLÍMPIA DE BRITO (TRÊS CORAÇÕES)
UPDATE schools SET inep_code = '174467' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE OLÍMPIA DE BRITO' AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174467');

-- EE PROFESSOR  CLÓVIS SALGADO (TRÊS CORAÇÕES)
UPDATE schools SET inep_code = '174394' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR  CLÓVIS SALGADO' AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174394');

-- EE PROFESSOR FRANCO DA ROSA (TRÊS CORAÇÕES)
UPDATE schools SET inep_code = '174483' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR FRANCO DA ROSA' AND UPPER(TRIM(city)) = 'TRÊS CORAÇÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174483');

-- EE CÔNEGO JOSÉ MARIA (TRÊS PONTAS)
UPDATE schools SET inep_code = '174530' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CÔNEGO JOSÉ MARIA' AND UPPER(TRIM(city)) = 'TRÊS PONTAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174530');

-- EE DEPUTADO TEODÓSIO BANDEIRA (TRÊS PONTAS)
UPDATE schools SET inep_code = '174688' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DEPUTADO TEODÓSIO BANDEIRA' AND UPPER(TRIM(city)) = 'TRÊS PONTAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174688');

-- EE MONSENHOR JOÃO BATISTA DA SILVEIRA (TRÊS PONTAS)
UPDATE schools SET inep_code = '174785' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE MONSENHOR JOÃO BATISTA DA SILVEIRA' AND UPPER(TRIM(city)) = 'TRÊS PONTAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174785');

-- EE PREFEITO JACY JUNQUEIRA GAZOLA (TRÊS PONTAS)
UPDATE schools SET inep_code = '174700' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PREFEITO JACY JUNQUEIRA GAZOLA' AND UPPER(TRIM(city)) = 'TRÊS PONTAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174700');

-- EE PRESIDENTE TANCREDO NEVES (TRÊS PONTAS)
UPDATE schools SET inep_code = '174831' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PRESIDENTE TANCREDO NEVES' AND UPPER(TRIM(city)) = 'TRÊS PONTAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174831');

-- EE PROFESSORA MARIA AUGUSTA VIEIRA CORREA (TRÊS PONTAS)
UPDATE schools SET inep_code = '174769' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIA AUGUSTA VIEIRA CORREA' AND UPPER(TRIM(city)) = 'TRÊS PONTAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174769');

-- EE PROFESSORA MARIETA CASTRO (TRÊS PONTAS)
UPDATE schools SET inep_code = '174718' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA MARIETA CASTRO' AND UPPER(TRIM(city)) = 'TRÊS PONTAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174718');

-- EE NOSSA SENHORA DA PIEDADE (TURVOLÂNDIA)
UPDATE schools SET inep_code = '174858' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE NOSSA SENHORA DA PIEDADE' AND UPPER(TRIM(city)) = 'TURVOLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174858');

-- CONSERVATÓRIO ESTADUAL DE MÚSICA MAESTRO MARCILIANO BRAGA (VARGINHA)
UPDATE schools SET inep_code = '175111' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CONSERVATÓRIO ESTADUAL DE MÚSICA MAESTRO MARCILIANO BRAGA' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '175111');

-- EE AFONSO PENA (VARGINHA)
UPDATE schools SET inep_code = '174882' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE AFONSO PENA' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174882');

-- EE BRASIL (VARGINHA)
UPDATE schools SET inep_code = '174921' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE BRASIL' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174921');

-- EE CORAÇÃO DE JESUS (VARGINHA)
UPDATE schools SET inep_code = '175099' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORAÇÃO DE JESUS' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '175099');

-- EE CORONEL GABRIEL PENHA DE PAIVA (VARGINHA)
UPDATE schools SET inep_code = '174912' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE CORONEL GABRIEL PENHA DE PAIVA' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174912');

-- EE DEPUTADO DOMINGOS DE FIGUEIREDO (VARGINHA)
UPDATE schools SET inep_code = '175013' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DEPUTADO DOMINGOS DE FIGUEIREDO' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '175013');

-- EE DOUTOR WLADIMIR DE REZENDE PINTO (VARGINHA)
UPDATE schools SET inep_code = '175030' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE DOUTOR WLADIMIR DE REZENDE PINTO' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '175030');

-- EE IRMÃO MÁRIO ESDRAS (VARGINHA)
UPDATE schools SET inep_code = '175048' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE IRMÃO MÁRIO ESDRAS' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '175048');

-- EE PEDRO DE ALCÂNTARA (VARGINHA)
UPDATE schools SET inep_code = '175064' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PEDRO DE ALCÂNTARA' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '175064');

-- EE PROFESSOR ANTÔNIO CORREA CARVALHO (VARGINHA)
UPDATE schools SET inep_code = '217719' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ANTÔNIO CORREA CARVALHO' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217719');

-- EE PROFESSOR ANTÔNIO DOMINGUES CHAVES (VARGINHA)
UPDATE schools SET inep_code = '175072' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR ANTÔNIO DOMINGUES CHAVES' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '175072');

-- EE PROFESSOR FÁBIO SALLES (VARGINHA)
UPDATE schools SET inep_code = '174904' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSOR FÁBIO SALLES' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '174904');

-- EE PROFESSORA ARACY MIRANDA (VARGINHA)
UPDATE schools SET inep_code = '175102' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA ARACY MIRANDA' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '175102');

-- EE PROFESSORA SELMA BASTOS (VARGINHA)
UPDATE schools SET inep_code = '356719' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE PROFESSORA SELMA BASTOS' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '356719');

-- EE SÃO SEBASTIÃO (VARGINHA)
UPDATE schools SET inep_code = '175081' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EE SÃO SEBASTIÃO' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '175081');

-- INSTITUTO FEDERAL DE EDUCAÇÃO DO NORTE DE MINAS - CAMPUS ALMENARA (ALMENARA)
UPDATE schools SET inep_code = '349658' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO FEDERAL DE EDUCAÇÃO DO NORTE DE MINAS - CAMPUS ALMENARA' AND UPPER(TRIM(city)) = 'ALMENARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349658');

-- INSTITUTO FEDERA DE EDUCAÇÃO, CIÊNCIA E  TECNOLOGIA DO NORTE DE MINAS GERIAS- CAMPUS ARAÇUAÍ (ARAÇUAÍ)
UPDATE schools SET inep_code = '347272' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO FEDERA DE EDUCAÇÃO, CIÊNCIA E  TECNOLOGIA DO NORTE DE MINAS GERIAS- CAMPUS ARAÇUAÍ' AND UPPER(TRIM(city)) = 'ARAÇUAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '347272');

-- INSTITUTO FEDERAL DE EDUCAÇÃO TENCOLOGICA DO NORTE DE MINAS-CAMPUS SALINAS (SALINAS)
UPDATE schools SET inep_code = '233269' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO FEDERAL DE EDUCAÇÃO TENCOLOGICA DO NORTE DE MINAS-CAMPUS SALINAS' AND UPPER(TRIM(city)) = 'SALINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '233269');

-- INSTITUTO FEDERAL DE EDUCAÇÃO CIÊNCIA E TECNOLOGIA DE MINAS GERAIS-CAMPUS CONGONHAS (CONGONHAS)
UPDATE schools SET inep_code = '345385' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO FEDERAL DE EDUCAÇÃO CIÊNCIA E TECNOLOGIA DE MINAS GERAIS-CAMPUS CONGONHAS' AND UPPER(TRIM(city)) = 'CONGONHAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '345385');

-- INSTITUTO FEDERAL DE MINAS GERIAS-CAMPUS AVANÇADO  DE CONSELHEIRO LAFAIETE (CONSELHEIRO LAFAIETE)
UPDATE schools SET inep_code = '365890' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO FEDERAL DE MINAS GERIAS-CAMPUS AVANÇADO  DE CONSELHEIRO LAFAIETE' AND UPPER(TRIM(city)) = 'CONSELHEIRO LAFAIETE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '365890');

-- INSTITUTO FEDERAL DE EDUCAÇÃO - CAMPUS AVANÇADO DE IPATINGA (IPATINGA)
UPDATE schools SET inep_code = '359017' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO FEDERAL DE EDUCAÇÃO - CAMPUS AVANÇADO DE IPATINGA' AND UPPER(TRIM(city)) = 'IPATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '359017');

-- CENTRO FEDERAL DE EDUCAÇÃO TECNOLÓGICA DE MINAS GERAIS - CAMPUS TIMÓTEO (TIMÓTEO)
UPDATE schools SET inep_code = '333361' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO FEDERAL DE EDUCAÇÃO TECNOLÓGICA DE MINAS GERAIS - CAMPUS TIMÓTEO' AND UPPER(TRIM(city)) = 'TIMÓTEO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '333361');

-- CENTRO FEDERAL DE EDUCAÇÃO TECNOLÓGICA DE MINAS GERAIS - CAMPUS CURVELO (CURVELO)
UPDATE schools SET inep_code = '347787' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO FEDERAL DE EDUCAÇÃO TECNOLÓGICA DE MINAS GERAIS - CAMPUS CURVELO' AND UPPER(TRIM(city)) = 'CURVELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '347787');

-- INSTITUTO FEDERAL DE EDUCAÇÃO CIÊNCIA E TECNOLOGIA DO NORTE DE MINAS GERAIS - CAMPUS DIAMANTINA (DIAMANTINA)
UPDATE schools SET inep_code = '366765' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO FEDERAL DE EDUCAÇÃO CIÊNCIA E TECNOLOGIA DO NORTE DE MINAS GERAIS - CAMPUS DIAMANTINA' AND UPPER(TRIM(city)) = 'DIAMANTINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '366765');

-- CENTRO FEDERAL DE EDUCAÇÃO TECNOLÓGICA DE MINAS GERAIS- CAMPUS DIVINÓPOLIS (DIVINÓPOLIS)
UPDATE schools SET inep_code = '268631' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO FEDERAL DE EDUCAÇÃO TECNOLÓGICA DE MINAS GERAIS- CAMPUS DIVINÓPOLIS' AND UPPER(TRIM(city)) = 'DIVINÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '268631');

-- INSTITUTO FEDERAL DE EDUCAÇÃO CIÊNCIA E TECNOLOGIA DE MINAS GERAIS - CAMPUS GOVERNADOR VALADARES (GOVERNADOR VALADARES)
UPDATE schools SET inep_code = '347701' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO FEDERAL DE EDUCAÇÃO CIÊNCIA E TECNOLOGIA DE MINAS GERAIS - CAMPUS GOVERNADOR VALADARES' AND UPPER(TRIM(city)) = 'GOVERNADOR VALADARES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '347701');

-- INSTITUTO FEDERAL DO TRIANGULO MINEIRO - CAMPUS ITUIUTABA (ITUIUTABA)
UPDATE schools SET inep_code = '345407' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO FEDERAL DO TRIANGULO MINEIRO - CAMPUS ITUIUTABA' AND UPPER(TRIM(city)) = 'ITUIUTABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '345407');

-- COLÉGIO MILITAR DE JUIZ DE FORA (JUIZ DE FORA)
UPDATE schools SET inep_code = '294471' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MILITAR DE JUIZ DE FORA' AND UPPER(TRIM(city)) = 'JUIZ DE FORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '294471');

-- CEFET DE LEOPOLDINA (LEOPOLDINA)
UPDATE schools SET inep_code = '224278' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CEFET DE LEOPOLDINA' AND UPPER(TRIM(city)) = 'LEOPOLDINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '224278');

-- INSTITUTO FEDERAL DE MINAS GERAIS - CAMPUS SABARÁ (SABARÁ)
UPDATE schools SET inep_code = '355402' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO FEDERAL DE MINAS GERAIS - CAMPUS SABARÁ' AND UPPER(TRIM(city)) = 'SABARÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '355402');

-- CENTRO FEDERAL DE EDUCAÇÃO TECNOLÓGICA DE MINAS GERAIS CAMPUS I BH (BELO HORIZONTE)
UPDATE schools SET inep_code = '245488' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO FEDERAL DE EDUCAÇÃO TECNOLÓGICA DE MINAS GERAIS CAMPUS I BH' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '245488');

-- COLÉGIO MILITAR DE BELO HORIZONTE (BELO HORIZONTE)
UPDATE schools SET inep_code = '291030' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MILITAR DE BELO HORIZONTE' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '291030');

-- ESCOLA DE EDUCAÇÃO BASICA E PROFISSIONAL DA UFMG - CENTRO PEDAGOGICO (BELO HORIZONTE)
UPDATE schools SET inep_code = '258377' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DE EDUCAÇÃO BASICA E PROFISSIONAL DA UFMG - CENTRO PEDAGOGICO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '258377');

-- INSTITUTO FEDERAL DE EDUCAÇÃO CIÊNCIA E TECNOLOGIA DE MINAS GERAIS- CAMPUS SANTA LUZIA (SANTA LUZIA)
UPDATE schools SET inep_code = '358150' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO FEDERAL DE EDUCAÇÃO CIÊNCIA E TECNOLOGIA DE MINAS GERAIS- CAMPUS SANTA LUZIA' AND UPPER(TRIM(city)) = 'SANTA LUZIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '358150');

-- INSTITUTO FEDERAL DO NORTE DE MINAS - CAMPUS MONTES CLAROS (MONTES CLAROS)
UPDATE schools SET inep_code = '349607' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO FEDERAL DO NORTE DE MINAS - CAMPUS MONTES CLAROS' AND UPPER(TRIM(city)) = 'MONTES CLAROS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349607');

-- INSTITUTO FEDERAL DE EDUCAÇÃO CIÊNCIA E TECNOLOGIA DO SUDESTE  DE MINAS GERAIS-CAMPUS MURIAÉ (MURIAÉ)
UPDATE schools SET inep_code = '347914' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO FEDERAL DE EDUCAÇÃO CIÊNCIA E TECNOLOGIA DO SUDESTE  DE MINAS GERAIS-CAMPUS MURIAÉ' AND UPPER(TRIM(city)) = 'MURIAÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '347914');

-- INSTITUTO FEDERAL DE EDUCAÇÃO CIÊNCIA E TECNOLOGIA DE MINAS GERAIS - CAMPUS OURO PRETO (OURO PRETO)
UPDATE schools SET inep_code = '253227' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO FEDERAL DE EDUCAÇÃO CIÊNCIA E TECNOLOGIA DE MINAS GERAIS - CAMPUS OURO PRETO' AND UPPER(TRIM(city)) = 'OURO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253227');

-- INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DE MINAS GERAIS - CAMPUS FORMIGA (FORMIGA)
UPDATE schools SET inep_code = '344664' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DE MINAS GERAIS - CAMPUS FORMIGA' AND UPPER(TRIM(city)) = 'FORMIGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '344664');

-- INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO NORTE DE MINAS- CAMPUS PIRAPORA (PIRAPORA)
UPDATE schools SET inep_code = '349410' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO NORTE DE MINAS- CAMPUS PIRAPORA' AND UPPER(TRIM(city)) = 'PIRAPORA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349410');

-- INSTITUTO FEDERAL DE EDUCAÇÃO CIENCIA E TECNOLOGIA SUL DE MINAS- CAMPUS MUZAMBINHO (MUZAMBINHO)
UPDATE schools SET inep_code = '242624' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO FEDERAL DE EDUCAÇÃO CIENCIA E TECNOLOGIA SUL DE MINAS- CAMPUS MUZAMBINHO' AND UPPER(TRIM(city)) = 'MUZAMBINHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '242624');

-- COLÉGIO DE APLICAÇÃO DA UFV COLUNI (VIÇOSA)
UPDATE schools SET inep_code = '128074' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO DE APLICAÇÃO DA UFV COLUNI' AND UPPER(TRIM(city)) = 'VIÇOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '128074');

-- INSTITUTO FEDERAL DO SUL DE MINAS GERAIS-CAMPUS POUSO ALEGRE (POUSO ALEGRE)
UPDATE schools SET inep_code = '355291' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO FEDERAL DO SUL DE MINAS GERAIS-CAMPUS POUSO ALEGRE' AND UPPER(TRIM(city)) = 'POUSO ALEGRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '355291');

-- INSTITUTO FEDERAL DE EDUCAÇÃO CIÊNCIA E TECNOLOGIA DO SUDESTE DE MINAS GERAIS CAMPUS SÃO JOÃO DEL RE (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '348031' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO FEDERAL DE EDUCAÇÃO CIÊNCIA E TECNOLOGIA DO SUDESTE DE MINAS GERAIS CAMPUS SÃO JOÃO DEL RE' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '348031');

-- INSTITUTO FEDERAL DE EDUCAÇÃO CIENCIA E TECNOLOGIA DO SUDESTE DE MINAS GERAIS - CAMPUS RIO POMBA (RIO POMBA)
UPDATE schools SET inep_code = '180696' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO FEDERAL DE EDUCAÇÃO CIENCIA E TECNOLOGIA DO SUDESTE DE MINAS GERAIS - CAMPUS RIO POMBA' AND UPPER(TRIM(city)) = 'RIO POMBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '180696');

-- CEFET DE ARAXÁ (ARAXÁ)
UPDATE schools SET inep_code = '237736' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CEFET DE ARAXÁ' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '237736');

-- CEFORES CENTRO FORMAÇÃO ESPECIAL EM SAÚDE (UBERABA)
UPDATE schools SET inep_code = '308251' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CEFORES CENTRO FORMAÇÃO ESPECIAL EM SAÚDE' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '308251');

-- INSTITUTO FEDERAL DE EDUCAÇÃO TECNOLÓGICA DO TRIANGULO MINEIRO - CAMPUS UBERABA (UBERABA)
UPDATE schools SET inep_code = '158151' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO FEDERAL DE EDUCAÇÃO TECNOLÓGICA DO TRIANGULO MINEIRO - CAMPUS UBERABA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158151');

-- ESCOLA DE EDUCAÇÃO BÁSICA DA UFU (UBERLÂNDIA)
UPDATE schools SET inep_code = '166545' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA DE EDUCAÇÃO BÁSICA DA UFU' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166545');

-- ESCOLA TÉCNICA DE SAÚDE DA UNIVERSIDADE FEDERAL UBERLÂNDIA (UBERLÂNDIA)
UPDATE schools SET inep_code = '166561' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TÉCNICA DE SAÚDE DA UNIVERSIDADE FEDERAL UBERLÂNDIA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166561');

-- INSTITUTO FEDERAL DE EDUCAÇÃO TECNOLOGICA DO TRIANGULO MINEIRO CAMPUS UBERLANDIA (UBERLÂNDIA)
UPDATE schools SET inep_code = '166553' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO FEDERAL DE EDUCAÇÃO TECNOLOGICA DO TRIANGULO MINEIRO CAMPUS UBERLANDIA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166553');

-- INSTITUTO FEDERAL DE EDUC CIÊNCIAS E TEC DO NORTE DE MINAS GERAIS - CAMPUS ARINOS (ARINOS)
UPDATE schools SET inep_code = '345440' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO FEDERAL DE EDUC CIÊNCIAS E TEC DO NORTE DE MINAS GERAIS - CAMPUS ARINOS' AND UPPER(TRIM(city)) = 'ARINOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '345440');

-- INSTITUTO FEDERAL DE EDUCAÇÃO CIENCIA E TECNOLOGIA DO SUL DE MINAS GERAIS - CAMPUS MACHADO (MACHADO)
UPDATE schools SET inep_code = '170674' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'INSTITUTO FEDERAL DE EDUCAÇÃO CIENCIA E TECNOLOGIA DO SUL DE MINAS GERAIS - CAMPUS MACHADO' AND UPPER(TRIM(city)) = 'MACHADO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170674');

-- CEFET DE NEPOMUCENO (NEPOMUCENO)
UPDATE schools SET inep_code = '334260' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CEFET DE NEPOMUCENO' AND UPPER(TRIM(city)) = 'NEPOMUCENO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '334260');

-- CENTRO FEDERAL DE EDUCAÇÃO TECNOLÓGICA DE MINAS GERAIS-CAMPUS VARGINHA (VARGINHA)
UPDATE schools SET inep_code = '334073' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO FEDERAL DE EDUCAÇÃO TECNOLÓGICA DE MINAS GERAIS-CAMPUS VARGINHA' AND UPPER(TRIM(city)) = 'VARGINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '334073');

-- EM BOA SORTE (ALMENARA)
UPDATE schools SET inep_code = '185833' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM BOA SORTE' AND UPPER(TRIM(city)) = 'ALMENARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185833');

-- EM CORINA FERRAZ DE BRITO (ALMENARA)
UPDATE schools SET inep_code = '274330' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CORINA FERRAZ DE BRITO' AND UPPER(TRIM(city)) = 'ALMENARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '274330');

-- EM JOSÉ MANOEL DA SILVA (ALMENARA)
UPDATE schools SET inep_code = '209651' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ MANOEL DA SILVA' AND UPPER(TRIM(city)) = 'ALMENARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '209651');

-- EM JOSÉ MARIA MORAES (ALMENARA)
UPDATE schools SET inep_code = '185841' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ MARIA MORAES' AND UPPER(TRIM(city)) = 'ALMENARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185841');

-- EM SÃO JOSÉ DO PRATA (ALMENARA)
UPDATE schools SET inep_code = '272752' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SÃO JOSÉ DO PRATA' AND UPPER(TRIM(city)) = 'ALMENARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '272752');

-- EM RAQUEL ALVES PORTO (BANDEIRA)
UPDATE schools SET inep_code = '186872' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM RAQUEL ALVES PORTO' AND UPPER(TRIM(city)) = 'BANDEIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '186872');

-- EM CASTELO BRANCO (CACHOEIRA DE PAJEÚ)
UPDATE schools SET inep_code = '186473' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CASTELO BRANCO' AND UPPER(TRIM(city)) = 'CACHOEIRA DE PAJEÚ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '186473');

-- EM JOSIAS SANTOS (DIVISA ALEGRE)
UPDATE schools SET inep_code = '340340' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSIAS SANTOS' AND UPPER(TRIM(city)) = 'DIVISA ALEGRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '340340');

-- EM LEOLINO CHAPADEIRO (FELISBURGO)
UPDATE schools SET inep_code = '187496' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM LEOLINO CHAPADEIRO' AND UPPER(TRIM(city)) = 'FELISBURGO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '187496');

-- EM EMANUEL SOARES DE O CAMPOS (JACINTO)
UPDATE schools SET inep_code = '184781' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM EMANUEL SOARES DE O CAMPOS' AND UPPER(TRIM(city)) = 'JACINTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184781');

-- EM NOSSA SENHORA DA CONCEIÇÃO (JACINTO)
UPDATE schools SET inep_code = '187640' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM NOSSA SENHORA DA CONCEIÇÃO' AND UPPER(TRIM(city)) = 'JACINTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '187640');

-- EM MINISTRO CLÓVIS SALGADO (JEQUITINHONHA)
UPDATE schools SET inep_code = '187895' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MINISTRO CLÓVIS SALGADO' AND UPPER(TRIM(city)) = 'JEQUITINHONHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '187895');

-- ESCOLA MUNICIPAL CRAÚNO (JEQUITINHONHA)
UPDATE schools SET inep_code = '370304' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA MUNICIPAL CRAÚNO' AND UPPER(TRIM(city)) = 'JEQUITINHONHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '370304');

-- EM DOUTOR ANTÔNIO GERÔNIMO OLIVEIRA (JOAÍMA)
UPDATE schools SET inep_code = '246298' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOUTOR ANTÔNIO GERÔNIMO OLIVEIRA' AND UPPER(TRIM(city)) = 'JOAÍMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246298');

-- EM MARIANOS (JOAÍMA)
UPDATE schools SET inep_code = '188174' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIANOS' AND UPPER(TRIM(city)) = 'JOAÍMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '188174');

-- EM SÃO JOSÉ (JOAÍMA)
UPDATE schools SET inep_code = '325040' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SÃO JOSÉ' AND UPPER(TRIM(city)) = 'JOAÍMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '325040');

-- EM RIBEIRA DO CAPIM ASSÚ (JORDÂNIA)
UPDATE schools SET inep_code = '246841' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM RIBEIRA DO CAPIM ASSÚ' AND UPPER(TRIM(city)) = 'JORDÂNIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246841');

-- EM ROBERTO MARTINS MAGNO (MATA VERDE)
UPDATE schools SET inep_code = '270521' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ROBERTO MARTINS MAGNO' AND UPPER(TRIM(city)) = 'MATA VERDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '270521');

-- EM OURO VERDE (PALMÓPOLIS)
UPDATE schools SET inep_code = '337730' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM OURO VERDE' AND UPPER(TRIM(city)) = 'PALMÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '337730');

-- EM TERTULIANA PARAGUASSU (PEDRA AZUL)
UPDATE schools SET inep_code = '189243' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM TERTULIANA PARAGUASSU' AND UPPER(TRIM(city)) = 'PEDRA AZUL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '189243');

-- EM VIRGOLINO LENCY (RIO DO PRADO)
UPDATE schools SET inep_code = '185299' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM VIRGOLINO LENCY' AND UPPER(TRIM(city)) = 'RIO DO PRADO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185299');

-- EM CORONEL MELVINO FERRAZ (RUBIM)
UPDATE schools SET inep_code = '185370' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CORONEL MELVINO FERRAZ' AND UPPER(TRIM(city)) = 'RUBIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '185370');

-- EM MARECHAL CASTELO BRANCO (SANTA MARIA DO SALTO)
UPDATE schools SET inep_code = '190209' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARECHAL CASTELO BRANCO' AND UPPER(TRIM(city)) = 'SANTA MARIA DO SALTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '190209');

-- EM IRMÃ MARIA GEMA (ARAÇUAÍ)
UPDATE schools SET inep_code = '149217' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM IRMÃ MARIA GEMA' AND UPPER(TRIM(city)) = 'ARAÇUAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '149217');

-- EM JOAQUIM VIANA GONÇALVES (ARAÇUAÍ)
UPDATE schools SET inep_code = '149349' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOAQUIM VIANA GONÇALVES' AND UPPER(TRIM(city)) = 'ARAÇUAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '149349');

-- EM JOSÉ GONÇALVES SOARES (ARAÇUAÍ)
UPDATE schools SET inep_code = '149501' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ GONÇALVES SOARES' AND UPPER(TRIM(city)) = 'ARAÇUAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '149501');

-- EM OLINTO RAMALHO (ARAÇUAÍ)
UPDATE schools SET inep_code = '149403' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM OLINTO RAMALHO' AND UPPER(TRIM(city)) = 'ARAÇUAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '149403');

-- EM SÃO VICENTE (ARAÇUAÍ)
UPDATE schools SET inep_code = '149187' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SÃO VICENTE' AND UPPER(TRIM(city)) = 'ARAÇUAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '149187');

-- EM ANFRÍSIO JOSÉ DA ROCHA (COMERCINHO)
UPDATE schools SET inep_code = '344010' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANFRÍSIO JOSÉ DA ROCHA' AND UPPER(TRIM(city)) = 'COMERCINHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '344010');

-- EM MANOEL COSTA BARRETO (CORONEL MURTA)
UPDATE schools SET inep_code = '151289' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MANOEL COSTA BARRETO' AND UPPER(TRIM(city)) = 'CORONEL MURTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '151289');

-- EM MARIA CECÍLIA DOS SANTOS (CORONEL MURTA)
UPDATE schools SET inep_code = '151301' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA CECÍLIA DOS SANTOS' AND UPPER(TRIM(city)) = 'CORONEL MURTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '151301');

-- EM ROSSANA FERREIRA MURTA (CORONEL MURTA)
UPDATE schools SET inep_code = '314421' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ROSSANA FERREIRA MURTA' AND UPPER(TRIM(city)) = 'CORONEL MURTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '314421');

-- EM DO SÃO JOÃO (ITAOBIM)
UPDATE schools SET inep_code = '146943' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DO SÃO JOÃO' AND UPPER(TRIM(city)) = 'ITAOBIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146943');

-- EM OLYNTHO RODRIGUES CARDOSO (ITAOBIM)
UPDATE schools SET inep_code = '146935' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM OLYNTHO RODRIGUES CARDOSO' AND UPPER(TRIM(city)) = 'ITAOBIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146935');

-- EM ARCEMIRO OLIVEIRA CHAVES (ITINGA)
UPDATE schools SET inep_code = '153184' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ARCEMIRO OLIVEIRA CHAVES' AND UPPER(TRIM(city)) = 'ITINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '153184');

-- EM ARMÍNIO INÁCIO (ITINGA)
UPDATE schools SET inep_code = '153222' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ARMÍNIO INÁCIO' AND UPPER(TRIM(city)) = 'ITINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '153222');

-- EM DA FAZENDA SANTA MARIA (ITINGA)
UPDATE schools SET inep_code = '146960' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DA FAZENDA SANTA MARIA' AND UPPER(TRIM(city)) = 'ITINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146960');

-- EM PADRE JOSÉ DE ANCHIETA (ITINGA)
UPDATE schools SET inep_code = '146994' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PADRE JOSÉ DE ANCHIETA' AND UPPER(TRIM(city)) = 'ITINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146994');

-- EM TOMÉ DE SOUZA (ITINGA)
UPDATE schools SET inep_code = '153338' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM TOMÉ DE SOUZA' AND UPPER(TRIM(city)) = 'ITINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '153338');

-- EM JOÃO NARCISO DE OLIVEIRA (ANDRELÂNDIA)
UPDATE schools SET inep_code = '258717' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOÃO NARCISO DE OLIVEIRA' AND UPPER(TRIM(city)) = 'ANDRELÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '258717');

-- EM ALBERTO CÔRREA (BARBACENA)
UPDATE schools SET inep_code = '212474' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ALBERTO CÔRREA' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '212474');

-- EM INÊS PIACESI (BARBACENA)
UPDATE schools SET inep_code = '212482' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM INÊS PIACESI' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '212482');

-- EM JOSÉ BENEDITO CAMPARA (BARBACENA)
UPDATE schools SET inep_code = '236560' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ BENEDITO CAMPARA' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '236560');

-- EM PROFESSORA YAYÁ MOREIRA (BARBACENA)
UPDATE schools SET inep_code = '299073' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA YAYÁ MOREIRA' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '299073');

-- EM SEBASTIÃO FRANCISCO DO VALLE (BARBACENA)
UPDATE schools SET inep_code = '212491' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SEBASTIÃO FRANCISCO DO VALLE' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '212491');

-- EM TONY MARCOS DE ANDRADE (BARBACENA)
UPDATE schools SET inep_code = '306134' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM TONY MARCOS DE ANDRADE' AND UPPER(TRIM(city)) = 'BARBACENA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '306134');

-- EM PROFESSORA TITA TAFURI (DESTERRO DO MELO)
UPDATE schools SET inep_code = '268895' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA TITA TAFURI' AND UPPER(TRIM(city)) = 'DESTERRO DO MELO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '268895');

-- EM TEÓFILO FERREIRA DE PAIVA (PAIVA)
UPDATE schools SET inep_code = '271586' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM TEÓFILO FERREIRA DE PAIVA' AND UPPER(TRIM(city)) = 'PAIVA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '271586');

-- EM ANTÔNIO FRANCISCO DA SILVA (SANTA BÁRBARA DO TUGÚRIO)
UPDATE schools SET inep_code = '269034' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANTÔNIO FRANCISCO DA SILVA' AND UPPER(TRIM(city)) = 'SANTA BÁRBARA DO TUGÚRIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '269034');

-- EM EUNICE SILVA MOREIRA (SANTANA DO GARAMBÉU)
UPDATE schools SET inep_code = '270938' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM EUNICE SILVA MOREIRA' AND UPPER(TRIM(city)) = 'SANTANA DO GARAMBÉU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '270938');

-- EM PADRE JUSTINO OBERS (AGUANIL)
UPDATE schools SET inep_code = '271306' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PADRE JUSTINO OBERS' AND UPPER(TRIM(city)) = 'AGUANIL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '271306');

-- EM JOÃO DE ASSIS CAMPOS (CRISTAIS)
UPDATE schools SET inep_code = '202533' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOÃO DE ASSIS CAMPOS' AND UPPER(TRIM(city)) = 'CRISTAIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '202533');

-- EM PREFEITO ARISTEU MAIA (CRISTAIS)
UPDATE schools SET inep_code = '204196' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PREFEITO ARISTEU MAIA' AND UPPER(TRIM(city)) = 'CRISTAIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '204196');

--  EM ITÁLIA CAUTIERO FRANCO - CAIC (LAVRAS)
UPDATE schools SET inep_code = '244279' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ITÁLIA CAUTIERO FRANCO - CAIC' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '244279');

-- EM ÁLVARO BOTELHO (LAVRAS)
UPDATE schools SET inep_code = '202878' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ÁLVARO BOTELHO' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '202878');

-- EM DOUTORA DAMINA (LAVRAS)
UPDATE schools SET inep_code = '202983' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOUTORA DAMINA' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '202983');

-- EM ÉDIO DO NASCIMENTO BIRINDIBA (LAVRAS)
UPDATE schools SET inep_code = '202932' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ÉDIO DO NASCIMENTO BIRINDIBA' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '202932');

-- EM FRANCISCO SALES (LAVRAS)
UPDATE schools SET inep_code = '203017' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM FRANCISCO SALES' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '203017');

-- EM JOSÉ SERAFIM (LAVRAS)
UPDATE schools SET inep_code = '251933' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ SERAFIM' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '251933');

-- EM LAFAIETE PEREIRA (LAVRAS)
UPDATE schools SET inep_code = '204536' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM LAFAIETE PEREIRA' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '204536');

-- EM PAULO MENICUCCI (LAVRAS)
UPDATE schools SET inep_code = '203092' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PAULO MENICUCCI' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '203092');

-- EM PROFESSOR JOSÉ LUIZ DE MESQUITA (LAVRAS)
UPDATE schools SET inep_code = '217751' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR JOSÉ LUIZ DE MESQUITA' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217751');

-- EM PROFESSOR PAULO DE SOUZA (LAVRAS)
UPDATE schools SET inep_code = '204552' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR PAULO DE SOUZA' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '204552');

-- EM SEBASTIÃO VICENTE FERREIRA (LAVRAS)
UPDATE schools SET inep_code = '274119' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SEBASTIÃO VICENTE FERREIRA' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '274119');

-- EM UMBELINA AZEVEDO AVELLAR (LAVRAS)
UPDATE schools SET inep_code = '316245' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM UMBELINA AZEVEDO AVELLAR' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '316245');

-- EM VICENTINA DE ABREU SILVA (LAVRAS)
UPDATE schools SET inep_code = '202916' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM VICENTINA DE ABREU SILVA' AND UPPER(TRIM(city)) = 'LAVRAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '202916');

-- EM OTAVIANO ALVARENGA (PERDÕES)
UPDATE schools SET inep_code = '203459' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM OTAVIANO ALVARENGA' AND UPPER(TRIM(city)) = 'PERDÕES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '203459');

-- EM JOSÉ CÂNDIDO FERREIRA (SANTO ANTÔNIO DO AMPARO)
UPDATE schools SET inep_code = '136158' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ CÂNDIDO FERREIRA' AND UPPER(TRIM(city)) = 'SANTO ANTÔNIO DO AMPARO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '136158');

-- EM DONA MARIQUITA BEZE (SÃO FRANCISCO DE PAULA)
UPDATE schools SET inep_code = '209996' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DONA MARIQUITA BEZE' AND UPPER(TRIM(city)) = 'SÃO FRANCISCO DE PAULA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '209996');

-- EM JOSÉ NORONHA MACHADO (ESPERA FELIZ)
UPDATE schools SET inep_code = '100480' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ NORONHA MACHADO' AND UPPER(TRIM(city)) = 'ESPERA FELIZ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '100480');

-- EM DOUTOR XENOFONTE MERCADANTE (ORIZÂNIA)
UPDATE schools SET inep_code = '100382' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOUTOR XENOFONTE MERCADANTE' AND UPPER(TRIM(city)) = 'ORIZÂNIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '100382');

-- EM DONA SEBASTIANA RITA THEODORO (CARATINGA)
UPDATE schools SET inep_code = '347566' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DONA SEBASTIANA RITA THEODORO' AND UPPER(TRIM(city)) = 'CARATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '347566');

-- EM GERALDO MARQUES CEVIDANES (CARATINGA)
UPDATE schools SET inep_code = '219665' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM GERALDO MARQUES CEVIDANES' AND UPPER(TRIM(city)) = 'CARATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '219665');

-- EM ILHA DA FANTASIA (CARATINGA)
UPDATE schools SET inep_code = '370142' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ILHA DA FANTASIA' AND UPPER(TRIM(city)) = 'CARATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '370142');

-- EM MARIA APARECIDA DE OLIVEIRA (CARATINGA)
UPDATE schools SET inep_code = '347540' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA APARECIDA DE OLIVEIRA' AND UPPER(TRIM(city)) = 'CARATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '347540');

-- EM NAYTIARA FRANCO CASSIANO DE EDUCAÇÃO INFANTIL E ENSINO FUNDAMENTAL (CARATINGA)
UPDATE schools SET inep_code = '233625' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM NAYTIARA FRANCO CASSIANO DE EDUCAÇÃO INFANTIL E ENSINO FUNDAMENTAL' AND UPPER(TRIM(city)) = 'CARATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '233625');

-- EM PEDRINA ALEXANDRE DO NASCIMENTO (CARATINGA)
UPDATE schools SET inep_code = '347558' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PEDRINA ALEXANDRE DO NASCIMENTO' AND UPPER(TRIM(city)) = 'CARATINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '347558');

-- EM IMACULADA CONCEIÇÃO (IPANEMA)
UPDATE schools SET inep_code = '374504' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM IMACULADA CONCEIÇÃO' AND UPPER(TRIM(city)) = 'IPANEMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '374504');

-- EM MARIA SIQUEIRA FONSECA (IPANEMA)
UPDATE schools SET inep_code = '272124' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA SIQUEIRA FONSECA' AND UPPER(TRIM(city)) = 'IPANEMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '272124');

-- EM MARLON DOS REIS LOPES (SANTA BÁRBARA DO LESTE)
UPDATE schools SET inep_code = '261408' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARLON DOS REIS LOPES' AND UPPER(TRIM(city)) = 'SANTA BÁRBARA DO LESTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '261408');

-- EM MAURO JACINTO DE FREITAS (SÃO SEBASTIÃO DO ANTA)
UPDATE schools SET inep_code = '274607' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MAURO JACINTO DE FREITAS' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO ANTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '274607');

-- EM JOAQUIM DE ABREU (TAPARUBA)
UPDATE schools SET inep_code = '270156' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOAQUIM DE ABREU' AND UPPER(TRIM(city)) = 'TAPARUBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '270156');

-- EM NOSSA SENHORA DO SAGRADO CORAÇÃO (AIURUOCA)
UPDATE schools SET inep_code = '175251' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM NOSSA SENHORA DO SAGRADO CORAÇÃO' AND UPPER(TRIM(city)) = 'AIURUOCA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '175251');

-- EM CORONEL PORFÍRIO MENDES PINTO (ALAGOA)
UPDATE schools SET inep_code = '170721' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CORONEL PORFÍRIO MENDES PINTO' AND UPPER(TRIM(city)) = 'ALAGOA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170721');

-- EM SENADOR ALFREDO CATÃO (BAEPENDI)
UPDATE schools SET inep_code = '171034' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SENADOR ALFREDO CATÃO' AND UPPER(TRIM(city)) = 'BAEPENDI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '171034');

-- EM DONA BENVINDA IMACULADA CONCEIÇÃO (CRUZÍLIA)
UPDATE schools SET inep_code = '172430' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DONA BENVINDA IMACULADA CONCEIÇÃO' AND UPPER(TRIM(city)) = 'CRUZÍLIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '172430');

-- EM PADRE DOUTOR JOÃO SCOTTI (ITAMONTE)
UPDATE schools SET inep_code = '172855' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PADRE DOUTOR JOÃO SCOTTI' AND UPPER(TRIM(city)) = 'ITAMONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '172855');

-- EM VIRGÍLIO ALVES PEREIRA (OLÍMPIO NORONHA)
UPDATE schools SET inep_code = '268828' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM VIRGÍLIO ALVES PEREIRA' AND UPPER(TRIM(city)) = 'OLÍMPIO NORONHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '268828');

-- EM JOSÉ DE ANCHIETA (PASSA-VINTE)
UPDATE schools SET inep_code = '269123' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ DE ANCHIETA' AND UPPER(TRIM(city)) = 'PASSA-VINTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '269123');