-- EM PROFESSOR JOÃO ORSI DE MORAIS (EXTREMA)
UPDATE schools SET inep_code = '321982' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR JOÃO ORSI DE MORAIS' AND UPPER(TRIM(city)) = 'EXTREMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '321982');

-- EM BENEDITO DORTA DE SOUZA (MONTE SIÃO)
UPDATE schools SET inep_code = '381535' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM BENEDITO DORTA DE SOUZA' AND UPPER(TRIM(city)) = 'MONTE SIÃO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '381535');

-- EM DOM OTÁVIO CHAGAS (MONTE SIÃO)
UPDATE schools SET inep_code = '375250' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOM OTÁVIO CHAGAS' AND UPPER(TRIM(city)) = 'MONTE SIÃO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '375250');

-- EM PADRE REINALDO (MONTE SIÃO)
UPDATE schools SET inep_code = '264334' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PADRE REINALDO' AND UPPER(TRIM(city)) = 'MONTE SIÃO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '264334');

-- EM ANATHÁLIA LOURDES CAMANDUCAIA (POUSO ALEGRE)
UPDATE schools SET inep_code = '258407' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANATHÁLIA LOURDES CAMANDUCAIA' AND UPPER(TRIM(city)) = 'POUSO ALEGRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '258407');

-- EM ANITA FARIA AMARAL (POUSO ALEGRE)
UPDATE schools SET inep_code = '233404' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANITA FARIA AMARAL' AND UPPER(TRIM(city)) = 'POUSO ALEGRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '233404');

-- EM DOUTOR ÂNGELO CÔNSOLI (POUSO ALEGRE)
UPDATE schools SET inep_code = '233412' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOUTOR ÂNGELO CÔNSOLI' AND UPPER(TRIM(city)) = 'POUSO ALEGRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '233412');

-- EM JANDYRA TOSTA DE SOUZA (POUSO ALEGRE)
UPDATE schools SET inep_code = '215490' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JANDYRA TOSTA DE SOUZA' AND UPPER(TRIM(city)) = 'POUSO ALEGRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '215490');

-- EM PROFESSORA CLARISSE TOLEDO (POUSO ALEGRE)
UPDATE schools SET inep_code = '269956' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA CLARISSE TOLEDO' AND UPPER(TRIM(city)) = 'POUSO ALEGRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '269956');

-- EM PROFESSORA ISABEL COUTINHO GALVÃO (POUSO ALEGRE)
UPDATE schools SET inep_code = '242497' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA ISABEL COUTINHO GALVÃO' AND UPPER(TRIM(city)) = 'POUSO ALEGRE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '242497');

-- EM PROFESSORA ALMERINDA SILVA MOSTI (SÃO SEBASTIÃO DA BELA VISTA)
UPDATE schools SET inep_code = '269964' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA ALMERINDA SILVA MOSTI' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DA BELA VISTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '269964');

-- EM PROFESSORA MARIA DA COSTA FERREIRA (SENADOR JOSÉ BENTO)
UPDATE schools SET inep_code = '127710' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA MARIA DA COSTA FERREIRA' AND UPPER(TRIM(city)) = 'SENADOR JOSÉ BENTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '127710');

-- EM ANGELINA MEDRADO (LAGOA DOURADA)
UPDATE schools SET inep_code = '134180' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANGELINA MEDRADO' AND UPPER(TRIM(city)) = 'LAGOA DOURADA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134180');

-- EM PROFESSORA MARIA MARCÍLIA REZENDE (LAGOA DOURADA)
UPDATE schools SET inep_code = '134228' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA MARIA MARCÍLIA REZENDE' AND UPPER(TRIM(city)) = 'LAGOA DOURADA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134228');

-- EM PAULA ASSIS (RESENDE COSTA)
UPDATE schools SET inep_code = '135968' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PAULA ASSIS' AND UPPER(TRIM(city)) = 'RESENDE COSTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '135968');

-- EM PROFA LUZIA FERREIRA (SANTA CRUZ DE MINAS)
UPDATE schools SET inep_code = '265128' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFA LUZIA FERREIRA' AND UPPER(TRIM(city)) = 'SANTA CRUZ DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '265128');

-- EM CARLOS DAMIANO FUZATTO (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '136310' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CARLOS DAMIANO FUZATTO' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '136310');

-- EM CELSO RAIMUNDO DA SILVA (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '312738' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CELSO RAIMUNDO DA SILVA' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312738');

-- EM DE EMBOABAS (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '134783' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DE EMBOABAS' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '134783');

-- EM PADRE MIGUEL AFONSO A LEITE (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '324051' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PADRE MIGUEL AFONSO A LEITE' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '324051');

-- EM PIO XII (SÃO JOÃO DEL REI)
UPDATE schools SET inep_code = '234834' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PIO XII' AND UPPER(TRIM(city)) = 'SÃO JOÃO DEL REI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '234834');

-- COLÉGIO ARCEBURGUENSE (ARCEBURGO)
UPDATE schools SET inep_code = '138061' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO ARCEBURGUENSE' AND UPPER(TRIM(city)) = 'ARCEBURGO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '138061');

-- EM DOM INÁCIO JOÃO DAL MONTE (GUARANÉSIA)
UPDATE schools SET inep_code = '137103' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOM INÁCIO JOÃO DAL MONTE' AND UPPER(TRIM(city)) = 'GUARANÉSIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137103');

-- EM ENGENHEIRO JORGE OLIVA (ITAÚ DE MINAS)
UPDATE schools SET inep_code = '137782' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ENGENHEIRO JORGE OLIVA' AND UPPER(TRIM(city)) = 'ITAÚ DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137782');

-- EM MONSENHOR ERNESTO CAVICCHIOLI (ITAÚ DE MINAS)
UPDATE schools SET inep_code = '305430' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MONSENHOR ERNESTO CAVICCHIOLI' AND UPPER(TRIM(city)) = 'ITAÚ DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305430');

-- EM DE TERMÓPOLIS DE ENSINO FUNDAMENTAL (SÃO SEBASTIÃO DO PARAÍSO)
UPDATE schools SET inep_code = '137979' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DE TERMÓPOLIS DE ENSINO FUNDAMENTAL' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '137979');

-- EM FRANCISCO DANIEL (SÃO SEBASTIÃO DO PARAÍSO)
UPDATE schools SET inep_code = '138037' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM FRANCISCO DANIEL' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '138037');

-- EM IBRANTINA AMARAL (SÃO SEBASTIÃO DO PARAÍSO)
UPDATE schools SET inep_code = '139904' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM IBRANTINA AMARAL' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '139904');

-- EM NAPOLEÃO VOLPE (SÃO SEBASTIÃO DO PARAÍSO)
UPDATE schools SET inep_code = '139718' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM NAPOLEÃO VOLPE' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '139718');

-- EM ROQUE SCARANO (SÃO SEBASTIÃO DO PARAÍSO)
UPDATE schools SET inep_code = '139858' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ROQUE SCARANO' AND UPPER(TRIM(city)) = 'SÃO SEBASTIÃO DO PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '139858');

-- EM JORGE MASCARENHAS (ARAÇAÍ)
UPDATE schools SET inep_code = '140287' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JORGE MASCARENHAS' AND UPPER(TRIM(city)) = 'ARAÇAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140287');

-- EM CEL AMÉRICO TEIXEIRA (CACHOEIRA DA PRATA)
UPDATE schools SET inep_code = '140431' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CEL AMÉRICO TEIXEIRA' AND UPPER(TRIM(city)) = 'CACHOEIRA DA PRATA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140431');

-- EM EMÍLIO DE VASCONCELOS COSTA (CAETANÓPOLIS)
UPDATE schools SET inep_code = '142611' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM EMÍLIO DE VASCONCELOS COSTA' AND UPPER(TRIM(city)) = 'CAETANÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '142611');

-- EM OLÍVIA DALLE MASCARENHAS (CAETANÓPOLIS)
UPDATE schools SET inep_code = '140457' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM OLÍVIA DALLE MASCARENHAS' AND UPPER(TRIM(city)) = 'CAETANÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '140457');

-- EM MÁRIO DINIZ PONTES (FORTUNA DE MINAS)
UPDATE schools SET inep_code = '268844' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MÁRIO DINIZ PONTES' AND UPPER(TRIM(city)) = 'FORTUNA DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '268844');

-- EM LOURISMAR PALHARES MACHADO (JEQUITIBÁ)
UPDATE schools SET inep_code = '141143' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM LOURISMAR PALHARES MACHADO' AND UPPER(TRIM(city)) = 'JEQUITIBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141143');

-- EM DONA VINA (MARAVILHAS)
UPDATE schools SET inep_code = '219061' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DONA VINA' AND UPPER(TRIM(city)) = 'MARAVILHAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '219061');

-- COLÉGIO MUNICIPAL PROFESSOR EURICO VIANA (MATOZINHOS)
UPDATE schools SET inep_code = '221431' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MUNICIPAL PROFESSOR EURICO VIANA' AND UPPER(TRIM(city)) = 'MATOZINHOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '221431');

-- EM DONA ELZA ALVES OLIVEIRA (MATOZINHOS)
UPDATE schools SET inep_code = '246557' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DONA ELZA ALVES OLIVEIRA' AND UPPER(TRIM(city)) = 'MATOZINHOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246557');

-- EM DONA JOVINA DE MELLO VEADO (MATOZINHOS)
UPDATE schools SET inep_code = '246549' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DONA JOVINA DE MELLO VEADO' AND UPPER(TRIM(city)) = 'MATOZINHOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246549');

-- EM AMÉRICO VAZ DA SILVA (PARAOPEBA)
UPDATE schools SET inep_code = '229610' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM AMÉRICO VAZ DA SILVA' AND UPPER(TRIM(city)) = 'PARAOPEBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '229610');

-- EM DR TEÓFILO NASCIMENTO (PARAOPEBA)
UPDATE schools SET inep_code = '144533' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DR TEÓFILO NASCIMENTO' AND UPPER(TRIM(city)) = 'PARAOPEBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '144533');

-- EM JOSÉ LUCAS DE FIGUEIREDO (PARAOPEBA)
UPDATE schools SET inep_code = '141330' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ LUCAS DE FIGUEIREDO' AND UPPER(TRIM(city)) = 'PARAOPEBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141330');

-- EM PROFESSORA ÂNGELA MARIA R CAMPOS (POMPÉU)
UPDATE schools SET inep_code = '144754' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA ÂNGELA MARIA R CAMPOS' AND UPPER(TRIM(city)) = 'POMPÉU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '144754');

-- EM JELIOMAR BRANDÃO (PRUDENTE DE MORAIS)
UPDATE schools SET inep_code = '219436' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JELIOMAR BRANDÃO' AND UPPER(TRIM(city)) = 'PRUDENTE DE MORAIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '219436');

-- EM JOSÉ MARIA DA FONSECA (SANTANA DE PIRAPAMA)
UPDATE schools SET inep_code = '314510' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ MARIA DA FONSECA' AND UPPER(TRIM(city)) = 'SANTANA DE PIRAPAMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '314510');

-- EM ALÍPIO MACIEL DE OLIVEIRA (SETE LAGOAS)
UPDATE schools SET inep_code = '219070' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ALÍPIO MACIEL DE OLIVEIRA' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '219070');

-- EM AURETE PONTES FONSECA (SETE LAGOAS)
UPDATE schools SET inep_code = '145181' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM AURETE PONTES FONSECA' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '145181');

-- EM DALVA FERREIRA DINIZ (SETE LAGOAS)
UPDATE schools SET inep_code = '233323' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DALVA FERREIRA DINIZ' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '233323');

-- EM DR MÁRCIO PAULINO (SETE LAGOAS)
UPDATE schools SET inep_code = '141712' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DR MÁRCIO PAULINO' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '141712');

-- EM FRANCISCA FERREIRA DE AVELAR (SETE LAGOAS)
UPDATE schools SET inep_code = '145220' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM FRANCISCA FERREIRA DE AVELAR' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '145220');

-- EM HILÁRIO PEREIRA DA FONSECA (SETE LAGOAS)
UPDATE schools SET inep_code = '343633' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM HILÁRIO PEREIRA DA FONSECA' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '343633');

-- EM JOSÉ JACINTO MARTINS GODOY - PROFESSOR GODOY (SETE LAGOAS)
UPDATE schools SET inep_code = '371076' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ JACINTO MARTINS GODOY - PROFESSOR GODOY' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '371076');

-- EM MARILZA FLEURY COSTA FIGUEIREDO (SETE LAGOAS)
UPDATE schools SET inep_code = '363847' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARILZA FLEURY COSTA FIGUEIREDO' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '363847');

-- EM PROF EDSON ABREU (SETE LAGOAS)
UPDATE schools SET inep_code = '233315' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROF EDSON ABREU' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '233315');

-- EM PROF GALVÃO (SETE LAGOAS)
UPDATE schools SET inep_code = '233307' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROF GALVÃO' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '233307');

-- EM PROF MARCOS VALENTINO (SETE LAGOAS)
UPDATE schools SET inep_code = '250341' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROF MARCOS VALENTINO' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '250341');

-- EM PROF VASCO DAMIÃO (SETE LAGOAS)
UPDATE schools SET inep_code = '210722' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROF VASCO DAMIÃO' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '210722');

-- EM RAIMUNDO GRAVITO - PROFESSOR GRAVITO (SETE LAGOAS)
UPDATE schools SET inep_code = '373168' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM RAIMUNDO GRAVITO - PROFESSOR GRAVITO' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '373168');

-- ESCOLA TEC MUNICIPAL DE SETE LAGOAS (SETE LAGOAS)
UPDATE schools SET inep_code = '145670' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA TEC MUNICIPAL DE SETE LAGOAS' AND UPPER(TRIM(city)) = 'SETE LAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '145670');

-- EM SEBASTIÃO LIMA FILHO (ÁGUAS FORMOSAS)
UPDATE schools SET inep_code = '312169' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SEBASTIÃO LIMA FILHO' AND UPPER(TRIM(city)) = 'ÁGUAS FORMOSAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312169');

-- EM DUQUE DE CAXIAS (ATALÉIA)
UPDATE schools SET inep_code = '213080' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DUQUE DE CAXIAS' AND UPPER(TRIM(city)) = 'ATALÉIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '213080');

-- EM ARÃO REIS (CARAÍ)
UPDATE schools SET inep_code = '150398' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ARÃO REIS' AND UPPER(TRIM(city)) = 'CARAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '150398');

-- EM OLEGÁRIO MACIEL (CARAÍ)
UPDATE schools SET inep_code = '150444' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM OLEGÁRIO MACIEL' AND UPPER(TRIM(city)) = 'CARAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '150444');

-- EM PRIMEIRO DE MAIO (CARAÍ)
UPDATE schools SET inep_code = '150711' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PRIMEIRO DE MAIO' AND UPPER(TRIM(city)) = 'CARAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '150711');

-- EM QUINZE DE NOVEMBRO (CARAÍ)
UPDATE schools SET inep_code = '150720' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM QUINZE DE NOVEMBRO' AND UPPER(TRIM(city)) = 'CARAÍ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '150720');

-- EM BRAZILINO RODRIGUES DE SOUZA (CARLOS CHAGAS)
UPDATE schools SET inep_code = '150924' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM BRAZILINO RODRIGUES DE SOUZA' AND UPPER(TRIM(city)) = 'CARLOS CHAGAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '150924');

-- EM DOUTOR MANOEL ESTEVES OTONI (CARLOS CHAGAS)
UPDATE schools SET inep_code = '146587' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOUTOR MANOEL ESTEVES OTONI' AND UPPER(TRIM(city)) = 'CARLOS CHAGAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146587');

-- EM OSCAR JOÃO KRETLI (CARLOS CHAGAS)
UPDATE schools SET inep_code = '151025' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM OSCAR JOÃO KRETLI' AND UPPER(TRIM(city)) = 'CARLOS CHAGAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '151025');

-- EM PRESIDENTE TANCREDO NEVES (CARLOS CHAGAS)
UPDATE schools SET inep_code = '146617' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PRESIDENTE TANCREDO NEVES' AND UPPER(TRIM(city)) = 'CARLOS CHAGAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146617');

-- EM DA FAZENDA AVENIDA (CRISÓLITA)
UPDATE schools SET inep_code = '145971' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DA FAZENDA AVENIDA' AND UPPER(TRIM(city)) = 'CRISÓLITA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '145971');

-- EM ESTÊVÃO MONTEIRO (FREI GASPAR)
UPDATE schools SET inep_code = '151556' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ESTÊVÃO MONTEIRO' AND UPPER(TRIM(city)) = 'FREI GASPAR' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '151556');

-- EM ZELITA CARLOS DE OLIVEIRA (FREI GASPAR)
UPDATE schools SET inep_code = '151599' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ZELITA CARLOS DE OLIVEIRA' AND UPPER(TRIM(city)) = 'FREI GASPAR' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '151599');

-- EM JOAQUIM DIAS ALMEIDA (FRONTEIRA DOS VALES)
UPDATE schools SET inep_code = '146722' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOAQUIM DIAS ALMEIDA' AND UPPER(TRIM(city)) = 'FRONTEIRA DOS VALES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '146722');

-- EM MARIA DE FÁTIMA BATISTA MATIAS (ITAIPÉ)
UPDATE schools SET inep_code = '338478' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA DE FÁTIMA BATISTA MATIAS' AND UPPER(TRIM(city)) = 'ITAIPÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338478');

-- EM DOUTOR EDSON LAGO PINHEIRO (ITAMBACURI)
UPDATE schools SET inep_code = '152412' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOUTOR EDSON LAGO PINHEIRO' AND UPPER(TRIM(city)) = 'ITAMBACURI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '152412');

-- EM HERMÍNIA LOPES (ITAMBACURI)
UPDATE schools SET inep_code = '152463' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM HERMÍNIA LOPES' AND UPPER(TRIM(city)) = 'ITAMBACURI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '152463');

-- EM JOÃO CHAVES (ITAMBACURI)
UPDATE schools SET inep_code = '152480' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOÃO CHAVES' AND UPPER(TRIM(city)) = 'ITAMBACURI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '152480');

-- EM RUI BARBOSA (ITAMBACURI)
UPDATE schools SET inep_code = '152579' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM RUI BARBOSA' AND UPPER(TRIM(city)) = 'ITAMBACURI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '152579');

-- EM ZÉLIA DE CAMPOS NEVES (ITAMBACURI)
UPDATE schools SET inep_code = '236039' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ZÉLIA DE CAMPOS NEVES' AND UPPER(TRIM(city)) = 'ITAMBACURI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '236039');

-- EM SEBASTIÃO PEREIRA CAMPOS (LADAINHA)
UPDATE schools SET inep_code = '153711' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SEBASTIÃO PEREIRA CAMPOS' AND UPPER(TRIM(city)) = 'LADAINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '153711');

-- EM ARISTIDES GOMES PEREIRA (MALACACHETA)
UPDATE schools SET inep_code = '222151' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ARISTIDES GOMES PEREIRA' AND UPPER(TRIM(city)) = 'MALACACHETA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '222151');

-- EM MANOEL GOMES DE PAULA (MALACACHETA)
UPDATE schools SET inep_code = '154059' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MANOEL GOMES DE PAULA' AND UPPER(TRIM(city)) = 'MALACACHETA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '154059');

-- EM AMÉRICO MACHADO (NANUQUE)
UPDATE schools SET inep_code = '347795' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM AMÉRICO MACHADO' AND UPPER(TRIM(city)) = 'NANUQUE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '347795');

-- EM MIGUEL VIANA DE OLIVEIRA (NANUQUE)
UPDATE schools SET inep_code = '154733' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MIGUEL VIANA DE OLIVEIRA' AND UPPER(TRIM(city)) = 'NANUQUE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '154733');

-- EM SERAFIM MACHADO NAYA (NANUQUE)
UPDATE schools SET inep_code = '154717' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SERAFIM MACHADO NAYA' AND UPPER(TRIM(city)) = 'NANUQUE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '154717');

-- EM JOSÉ DE ANCHIETA (NOVO CRUZEIRO)
UPDATE schools SET inep_code = '155144' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ DE ANCHIETA' AND UPPER(TRIM(city)) = 'NOVO CRUZEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '155144');

-- EM LEONÍDIA COSTA FREIRE (NOVO CRUZEIRO)
UPDATE schools SET inep_code = '351687' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM LEONÍDIA COSTA FREIRE' AND UPPER(TRIM(city)) = 'NOVO CRUZEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '351687');

-- EM PROFESSORA MARIA DAS DORES GOMES DE SOUZA (NOVO CRUZEIRO)
UPDATE schools SET inep_code = '349976' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA MARIA DAS DORES GOMES DE SOUZA' AND UPPER(TRIM(city)) = 'NOVO CRUZEIRO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349976');

-- EM DOMÍCIO PINTO MIRANDA (NOVO ORIENTE DE MINAS)
UPDATE schools SET inep_code = '157279' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOMÍCIO PINTO MIRANDA' AND UPPER(TRIM(city)) = 'NOVO ORIENTE DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '157279');

-- EM MANOEL GONÇALVES SOARES (NOVO ORIENTE DE MINAS)
UPDATE schools SET inep_code = '156892' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MANOEL GONÇALVES SOARES' AND UPPER(TRIM(city)) = 'NOVO ORIENTE DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '156892');

-- EM LOURIVALDO FRANCISCO DA PAZ (OURO VERDE DE MINAS)
UPDATE schools SET inep_code = '155543' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM LOURIVALDO FRANCISCO DA PAZ' AND UPPER(TRIM(city)) = 'OURO VERDE DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '155543');

-- EM DOM JOSÉ DE HAAS (PADRE PARAÍSO)
UPDATE schools SET inep_code = '155748' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOM JOSÉ DE HAAS' AND UPPER(TRIM(city)) = 'PADRE PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '155748');

-- EM RAMIRO LOPES (PADRE PARAÍSO)
UPDATE schools SET inep_code = '155667' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM RAMIRO LOPES' AND UPPER(TRIM(city)) = 'PADRE PARAÍSO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '155667');

-- EM DE VIRGEM DAS GRAÇAS (PONTO DOS VOLANTES)
UPDATE schools SET inep_code = '147036' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DE VIRGEM DAS GRAÇAS' AND UPPER(TRIM(city)) = 'PONTO DOS VOLANTES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147036');

-- EM MARIA GERALDA MIRANDA BRITO SALOMÃO (PONTO DOS VOLANTES)
UPDATE schools SET inep_code = '353426' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA GERALDA MIRANDA BRITO SALOMÃO' AND UPPER(TRIM(city)) = 'PONTO DOS VOLANTES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '353426');

-- EM MODESTO DA COSTA (PONTO DOS VOLANTES)
UPDATE schools SET inep_code = '153036' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MODESTO DA COSTA' AND UPPER(TRIM(city)) = 'PONTO DOS VOLANTES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '153036');

-- EM FREI GASPAR (POTÉ)
UPDATE schools SET inep_code = '156299' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM FREI GASPAR' AND UPPER(TRIM(city)) = 'POTÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '156299');

-- EM PREFEITO OMAR AFFONSO DA SILVA (POTÉ)
UPDATE schools SET inep_code = '347396' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PREFEITO OMAR AFFONSO DA SILVA' AND UPPER(TRIM(city)) = 'POTÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '347396');

-- EM BARÃO DO RIO BRANCO (SANTA HELENA DE MINAS)
UPDATE schools SET inep_code = '150037' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM BARÃO DO RIO BRANCO' AND UPPER(TRIM(city)) = 'SANTA HELENA DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '150037');

-- EM ANGELIM SAÚDE (SERRA DOS AIMORÉS)
UPDATE schools SET inep_code = '156671' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANGELIM SAÚDE' AND UPPER(TRIM(city)) = 'SERRA DOS AIMORÉS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '156671');

-- EM DE PAI DOMINGOS (SETUBINHA)
UPDATE schools SET inep_code = '147346' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DE PAI DOMINGOS' AND UPPER(TRIM(city)) = 'SETUBINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '147346');

-- EM AGRÍCOLA GERALDO LEÃO LOPES (TEÓFILO OTONI)
UPDATE schools SET inep_code = '156868' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM AGRÍCOLA GERALDO LEÃO LOPES' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '156868');

-- EM AGRÍCOLA INÁCIO PEREIRA GUIMARÃES (TEÓFILO OTONI)
UPDATE schools SET inep_code = '157163' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM AGRÍCOLA INÁCIO PEREIRA GUIMARÃES' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '157163');

-- EM IRMÃ MARIA AMÁLIA (TEÓFILO OTONI)
UPDATE schools SET inep_code = '228591' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM IRMÃ MARIA AMÁLIA' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '228591');

-- EM NOSSA SENHORA APARECIDA (TEÓFILO OTONI)
UPDATE schools SET inep_code = '305669' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM NOSSA SENHORA APARECIDA' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305669');

-- EM SIDÔNIO OTTONI (TEÓFILO OTONI)
UPDATE schools SET inep_code = '157155' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SIDÔNIO OTTONI' AND UPPER(TRIM(city)) = 'TEÓFILO OTONI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '157155');

-- EM COLATINA GONÇALVES DE SOUZA (UMBURATIBA)
UPDATE schools SET inep_code = '148466' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM COLATINA GONÇALVES DE SOUZA' AND UPPER(TRIM(city)) = 'UMBURATIBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '148466');

-- EM PROFESSORA MARLY MONTEIRO (SÃO GERALDO)
UPDATE schools SET inep_code = '183628' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA MARLY MONTEIRO' AND UPPER(TRIM(city)) = 'SÃO GERALDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '183628');

-- EM DOUTOR TANUS FERES DE ANDRADE (UBÁ)
UPDATE schools SET inep_code = '293041' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOUTOR TANUS FERES DE ANDRADE' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '293041');

-- EM PROFESSOR MANOEL ARTHIDORO DE CASTRO (UBÁ)
UPDATE schools SET inep_code = '330281' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR MANOEL ARTHIDORO DE CASTRO' AND UPPER(TRIM(city)) = 'UBÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '330281');

-- COLÉGIO MUNICIPAL RIO BRANCO (VISCONDE DO RIO BRANCO)
UPDATE schools SET inep_code = '184152' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MUNICIPAL RIO BRANCO' AND UPPER(TRIM(city)) = 'VISCONDE DO RIO BRANCO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '184152');

-- EM ANTÔNIO AUGUSTO DE PAIVA (ARAXÁ)
UPDATE schools SET inep_code = '160466' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANTÔNIO AUGUSTO DE PAIVA' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '160466');

-- EM AZIZ J CHAER (ARAXÁ)
UPDATE schools SET inep_code = '160521' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM AZIZ J CHAER' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '160521');

-- EM EUNICE WEAWER (ARAXÁ)
UPDATE schools SET inep_code = '158241' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM EUNICE WEAWER' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158241');

-- EM FRANCISCO PRIMO DE MELO (ARAXÁ)
UPDATE schools SET inep_code = '160504' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM FRANCISCO PRIMO DE MELO' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '160504');

-- EM JOSÉ BENTO (ARAXÁ)
UPDATE schools SET inep_code = '160431' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ BENTO' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '160431');

-- EM MÚSICA MAESTRO ELIAS PORFÍRIO AZEVEDO (ARAXÁ)
UPDATE schools SET inep_code = '321931' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MÚSICA MAESTRO ELIAS PORFÍRIO AZEVEDO' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '321931');

-- EM PADRE INÁCIO (ARAXÁ)
UPDATE schools SET inep_code = '160512' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PADRE INÁCIO' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '160512');

-- EM PROFESSORA AUXILIADORA PAIVA (ARAXÁ)
UPDATE schools SET inep_code = '277452' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA AUXILIADORA PAIVA' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '277452');

-- EM PROFESSORA LEONILDA MONTANDON (ARAXÁ)
UPDATE schools SET inep_code = '241041' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA LEONILDA MONTANDON' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '241041');

-- EM PROFESSORA ROMÁLIA PORFÍRIO DE AZEVEDO LEITE (ARAXÁ)
UPDATE schools SET inep_code = '368555' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA ROMÁLIA PORFÍRIO DE AZEVEDO LEITE' AND UPPER(TRIM(city)) = 'ARAXÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '368555');

-- EM AMÉLIA FRANCO (CAMPOS ALTOS)
UPDATE schools SET inep_code = '213802' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM AMÉLIA FRANCO' AND UPPER(TRIM(city)) = 'CAMPOS ALTOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '213802');

-- EM JOAQUIM DOMINGOS DA SILVA (CAMPOS ALTOS)
UPDATE schools SET inep_code = '158551' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOAQUIM DOMINGOS DA SILVA' AND UPPER(TRIM(city)) = 'CAMPOS ALTOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158551');

-- EM LINDOLFO DE ALMEIDA FERREIRA (COMENDADOR GOMES)
UPDATE schools SET inep_code = '158607' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM LINDOLFO DE ALMEIDA FERREIRA' AND UPPER(TRIM(city)) = 'COMENDADOR GOMES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158607');

-- EM CARLOS LUZ (CONCEIÇÃO DAS ALAGOAS)
UPDATE schools SET inep_code = '158623' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CARLOS LUZ' AND UPPER(TRIM(city)) = 'CONCEIÇÃO DAS ALAGOAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158623');

-- EM DR PRADO LOPES (CONQUISTA)
UPDATE schools SET inep_code = '158704' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DR PRADO LOPES' AND UPPER(TRIM(city)) = 'CONQUISTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158704');

-- EM ANA DE CASTRO CANÇADO (DELTA)
UPDATE schools SET inep_code = '159778' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANA DE CASTRO CANÇADO' AND UPPER(TRIM(city)) = 'DELTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159778');

-- EM OLAVO DE OLIVEIRA FERREIRA (DELTA)
UPDATE schools SET inep_code = '165662' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM OLAVO DE OLIVEIRA FERREIRA' AND UPPER(TRIM(city)) = 'DELTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '165662');

-- EM ÂNGELO RICARDO (FRUTAL)
UPDATE schools SET inep_code = '311731' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ÂNGELO RICARDO' AND UPPER(TRIM(city)) = 'FRUTAL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '311731');

-- EM ANTÔNIO PRADO (FRUTAL)
UPDATE schools SET inep_code = '162264' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANTÔNIO PRADO' AND UPPER(TRIM(city)) = 'FRUTAL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '162264');

-- EM BELMIRO BATISTA MIRANDA (FRUTAL)
UPDATE schools SET inep_code = '255009' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM BELMIRO BATISTA MIRANDA' AND UPPER(TRIM(city)) = 'FRUTAL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '255009');

-- EM JOAQUIM BARROSO (FRUTAL)
UPDATE schools SET inep_code = '158933' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOAQUIM BARROSO' AND UPPER(TRIM(city)) = 'FRUTAL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158933');

-- EM ODÍLIO FERNANDES (FRUTAL)
UPDATE schools SET inep_code = '255017' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ODÍLIO FERNANDES' AND UPPER(TRIM(city)) = 'FRUTAL' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '255017');

-- EM ALONSO DE MORAIS ANDRADE (ITAPAGIPE)
UPDATE schools SET inep_code = '162680' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ALONSO DE MORAIS ANDRADE' AND UPPER(TRIM(city)) = 'ITAPAGIPE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '162680');

-- EM AGRÍCOLA ALÍPIO SOARES BARBOSA (ITURAMA)
UPDATE schools SET inep_code = '254991' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM AGRÍCOLA ALÍPIO SOARES BARBOSA' AND UPPER(TRIM(city)) = 'ITURAMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '254991');

-- EM JOÃO RIBEIRO ROSA (ITURAMA)
UPDATE schools SET inep_code = '271128' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOÃO RIBEIRO ROSA' AND UPPER(TRIM(city)) = 'ITURAMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '271128');

-- EM CORONEL JÚLIO BORGES (SACRAMENTO)
UPDATE schools SET inep_code = '164593' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CORONEL JÚLIO BORGES' AND UPPER(TRIM(city)) = 'SACRAMENTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '164593');

-- EM DONA MARIA SANT'ANA (SACRAMENTO)
UPDATE schools SET inep_code = '159590' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DONA MARIA SANT''ANA' AND UPPER(TRIM(city)) = 'SACRAMENTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159590');

-- EM DOUTOR AFONSO PENA JÚNIOR (SACRAMENTO)
UPDATE schools SET inep_code = '377031' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOUTOR AFONSO PENA JÚNIOR' AND UPPER(TRIM(city)) = 'SACRAMENTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '377031');

-- EM DOUTOR DJALMA AFONSO DO PRADO (SACRAMENTO)
UPDATE schools SET inep_code = '164372' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOUTOR DJALMA AFONSO DO PRADO' AND UPPER(TRIM(city)) = 'SACRAMENTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '164372');

-- EM DOUTOR JOÃO CORDEIRO (SACRAMENTO)
UPDATE schools SET inep_code = '164399' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOUTOR JOÃO CORDEIRO' AND UPPER(TRIM(city)) = 'SACRAMENTO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '164399');

-- EM TARCILA NEVES DA COSTA (SANTA JULIANA)
UPDATE schools SET inep_code = '159638' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM TARCILA NEVES DA COSTA' AND UPPER(TRIM(city)) = 'SANTA JULIANA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159638');

-- EM STA TEREZINHA (SÃO FRANCISCO DE SALES)
UPDATE schools SET inep_code = '165051' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM STA TEREZINHA' AND UPPER(TRIM(city)) = 'SÃO FRANCISCO DE SALES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '165051');

-- EM ALVINA ALVES DE REZENDE (TAPIRA)
UPDATE schools SET inep_code = '159654' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ALVINA ALVES DE REZENDE' AND UPPER(TRIM(city)) = 'TAPIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159654');

-- EM PAOLLA CAROLINA DE MELO (TAPIRA)
UPDATE schools SET inep_code = '378364' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PAOLLA CAROLINA DE MELO' AND UPPER(TRIM(city)) = 'TAPIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '378364');

-- EM VICENTE PEREIRA FERNANDES (TAPIRA)
UPDATE schools SET inep_code = '165174' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM VICENTE PEREIRA FERNANDES' AND UPPER(TRIM(city)) = 'TAPIRA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '165174');

-- EM ADOLFO BEZERRA DE MENEZES (UBERABA)
UPDATE schools SET inep_code = '165212' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ADOLFO BEZERRA DE MENEZES' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '165212');

-- EM ARTUR DE MELO TEIXEIRA (UBERABA)
UPDATE schools SET inep_code = '165336' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ARTUR DE MELO TEIXEIRA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '165336');

-- EM BOA VISTA (UBERABA)
UPDATE schools SET inep_code = '165395' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM BOA VISTA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '165395');

-- EM CELINA SOARES DE PAIVA (UBERABA)
UPDATE schools SET inep_code = '165450' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CELINA SOARES DE PAIVA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '165450');

-- EM FREDERICO PEIRÓ (UBERABA)
UPDATE schools SET inep_code = '165701' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM FREDERICO PEIRÓ' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '165701');

-- EM GASTÃO MESQUITA FILHO (UBERABA)
UPDATE schools SET inep_code = '165930' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM GASTÃO MESQUITA FILHO' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '165930');

-- EM JOSÉ MARCUS CHEREM (UBERABA)
UPDATE schools SET inep_code = '165778' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ MARCUS CHEREM' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '165778');

-- EM JOUBERT DE CARVALHO (UBERABA)
UPDATE schools SET inep_code = '234699' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOUBERT DE CARVALHO' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '234699');

-- EM MADRE MARIA GEORGINA (UBERABA)
UPDATE schools SET inep_code = '165841' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MADRE MARIA GEORGINA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '165841');

-- EM MARIA CAROLINA MENDES (UBERABA)
UPDATE schools SET inep_code = '165328' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA CAROLINA MENDES' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '165328');

-- EM MONTEIRO LOBATO (UBERABA)
UPDATE schools SET inep_code = '165441' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MONTEIRO LOBATO' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '165441');

-- EM NORMA SUELY BORGES (UBERABA)
UPDATE schools SET inep_code = '165263' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM NORMA SUELY BORGES' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '165263');

-- EM PADRE EDDIE BERNARDES (UBERABA)
UPDATE schools SET inep_code = '165514' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PADRE EDDIE BERNARDES' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '165514');

-- EM PROFA ESTER LIMIRIO BRIGAGAO (UBERABA)
UPDATE schools SET inep_code = '331562' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFA ESTER LIMIRIO BRIGAGAO' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '331562');

-- EM PROFESSOR ANÍSIO TEIXEIRA (UBERABA)
UPDATE schools SET inep_code = '159832' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR ANÍSIO TEIXEIRA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '159832');

-- EM PROFESSOR JOSÉ GERALDO GUIMARÃES (UBERABA)
UPDATE schools SET inep_code = '165727' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR JOSÉ GERALDO GUIMARÃES' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '165727');

-- EM PROFESSOR JOSÉ MACCIOTTI (UBERABA)
UPDATE schools SET inep_code = '165484' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR JOSÉ MACCIOTTI' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '165484');

-- EM PROFESSORA GENI CHAVES (UBERABA)
UPDATE schools SET inep_code = '165859' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA GENI CHAVES' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '165859');

-- EM PROFESSORA MARIA LOURENCINA PALMERIO (UBERABA)
UPDATE schools SET inep_code = '241083' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA MARIA LOURENCINA PALMERIO' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '241083');

-- EM PROFESSORA NIZA MARQUEZ GUARITA (UBERABA)
UPDATE schools SET inep_code = '260347' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA NIZA MARQUEZ GUARITA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '260347');

-- EM PROFESSORA OLGA DE OLIVEIRA (UBERABA)
UPDATE schools SET inep_code = '165760' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA OLGA DE OLIVEIRA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '165760');

-- EM PROFESSORA STELA CHAVES (UBERABA)
UPDATE schools SET inep_code = '165344' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA STELA CHAVES' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '165344');

-- EM PROFESSORA TEREZINHA HUEB MENEZES (UBERABA)
UPDATE schools SET inep_code = '380296' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA TEREZINHA HUEB MENEZES' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '380296');

-- EM REIS JÚNIOR (UBERABA)
UPDATE schools SET inep_code = '241091' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM REIS JÚNIOR' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '241091');

-- EM SANTA MARIA (UBERABA)
UPDATE schools SET inep_code = '165875' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SANTA MARIA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '165875');

-- EM SEBASTIÃO ANTÔNIO LEAL (UBERABA)
UPDATE schools SET inep_code = '165620' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SEBASTIÃO ANTÔNIO LEAL' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '165620');

-- EM TOTONHO DE MORAIS (UBERABA)
UPDATE schools SET inep_code = '165221' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM TOTONHO DE MORAIS' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '165221');

-- EM UBERABA (UBERABA)
UPDATE schools SET inep_code = '160199' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM UBERABA' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '160199');

-- EM URBANA FREI EUGÊNIO (UBERABA)
UPDATE schools SET inep_code = '165301' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM URBANA FREI EUGÊNIO' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '165301');

-- EM VICENTE ALVES TRINDADE (UBERABA)
UPDATE schools SET inep_code = '165549' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM VICENTE ALVES TRINDADE' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '165549');

-- ESCOLA MUNICIPAL DE ENSINO TÉCNICO PROFISSIONALIZANTE PROFESSOR FRANCISCO SALES JERÔNIMO - CHICÃO (UBERABA)
UPDATE schools SET inep_code = '380059' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA MUNICIPAL DE ENSINO TÉCNICO PROFISSIONALIZANTE PROFESSOR FRANCISCO SALES JERÔNIMO - CHICÃO' AND UPPER(TRIM(city)) = 'UBERABA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '380059');

-- CAIC EM DR ARCINO SANTOS LAUREANO (ARAGUARI)
UPDATE schools SET inep_code = '250601' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CAIC EM DR ARCINO SANTOS LAUREANO' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '250601');

-- CEM MÁRIO DA SILVA PEREIRA (ARAGUARI)
UPDATE schools SET inep_code = '276626' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CEM MÁRIO DA SILVA PEREIRA' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '276626');

-- CEM OZÓRIO VIEIRA CARRIJO (ARAGUARI)
UPDATE schools SET inep_code = '168335' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CEM OZÓRIO VIEIRA CARRIJO' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '168335');

-- CEM PROF HERMENEGILDO M VELOSO (ARAGUARI)
UPDATE schools SET inep_code = '262498' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CEM PROF HERMENEGILDO M VELOSO' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '262498');

-- CENTRO EDUCACIONAL MUNICIPAL  PAPA JOÃO XXIII (ARAGUARI)
UPDATE schools SET inep_code = '168114' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL MUNICIPAL  PAPA JOÃO XXIII' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '168114');

-- CENTRO EDUCACIONAL MUNICIPAL TENENTE CORONEL VILAGRAN CABRITA (ARAGUARI)
UPDATE schools SET inep_code = '168173' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL MUNICIPAL TENENTE CORONEL VILAGRAN CABRITA' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '168173');

-- EM JOSÉ INÁCIO (ARAGUARI)
UPDATE schools SET inep_code = '167941' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ INÁCIO' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167941');

-- EM JUSTINO RODRIGUES DA CUNHA (ARAGUARI)
UPDATE schools SET inep_code = '248215' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JUSTINO RODRIGUES DA CUNHA' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '248215');

-- EM ROSA MAMERI RADE (ARAGUARI)
UPDATE schools SET inep_code = '166588' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ROSA MAMERI RADE' AND UPPER(TRIM(city)) = 'ARAGUARI' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166588');

-- EM DE FORMAÇÃO TÉCNICA PROFISSIONAL JOSÉ INÁCIO FERREIRA (ARAPORÃ)
UPDATE schools SET inep_code = '327221' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DE FORMAÇÃO TÉCNICA PROFISSIONAL JOSÉ INÁCIO FERREIRA' AND UPPER(TRIM(city)) = 'ARAPORÃ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '327221');

-- EM OLINTHA DE OLIVEIRA VALE (ARAPORÃ)
UPDATE schools SET inep_code = '269638' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM OLINTHA DE OLIVEIRA VALE' AND UPPER(TRIM(city)) = 'ARAPORÃ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '269638');

-- EM FELICIANO ANTÔNIO DE FARIA (CAMPINA VERDE)
UPDATE schools SET inep_code = '348570' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM FELICIANO ANTÔNIO DE FARIA' AND UPPER(TRIM(city)) = 'CAMPINA VERDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '348570');

-- EM OTÁVIO SEVERINO DA SILVA (CAMPINA VERDE)
UPDATE schools SET inep_code = '160989' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM OTÁVIO SEVERINO DA SILVA' AND UPPER(TRIM(city)) = 'CAMPINA VERDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '160989');

-- EM SÃO VICENTE DE PAULO (CAMPINA VERDE)
UPDATE schools SET inep_code = '158411' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SÃO VICENTE DE PAULO' AND UPPER(TRIM(city)) = 'CAMPINA VERDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '158411');

-- CMNER JOSÉ BARBOSA DE MIRANDA (INDIANÓPOLIS)
UPDATE schools SET inep_code = '168467' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CMNER JOSÉ BARBOSA DE MIRANDA' AND UPPER(TRIM(city)) = 'INDIANÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '168467');

-- EM DE INDIANÓPOLIS (INDIANÓPOLIS)
UPDATE schools SET inep_code = '269514' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DE INDIANÓPOLIS' AND UPPER(TRIM(city)) = 'INDIANÓPOLIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '269514');

-- EM FERNANDO VILELA (MONTE ALEGRE DE MINAS)
UPDATE schools SET inep_code = '168602' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM FERNANDO VILELA' AND UPPER(TRIM(city)) = 'MONTE ALEGRE DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '168602');

-- EM JOSÉ CABRAL VIEIRA (MONTE ALEGRE DE MINAS)
UPDATE schools SET inep_code = '166928' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ CABRAL VIEIRA' AND UPPER(TRIM(city)) = 'MONTE ALEGRE DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166928');

-- EM MÁRCIA CAETANO ALVES (MONTE ALEGRE DE MINAS)
UPDATE schools SET inep_code = '219304' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MÁRCIA CAETANO ALVES' AND UPPER(TRIM(city)) = 'MONTE ALEGRE DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '219304');

-- EM NICANOR PARREIRA (MONTE ALEGRE DE MINAS)
UPDATE schools SET inep_code = '166944' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM NICANOR PARREIRA' AND UPPER(TRIM(city)) = 'MONTE ALEGRE DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166944');

-- EM PRESIDENTE VARGAS (NOVA PONTE)
UPDATE schools SET inep_code = '168874' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PRESIDENTE VARGAS' AND UPPER(TRIM(city)) = 'NOVA PONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '168874');

-- EM PROFESSORA NEUZA LOPES PINTO (NOVA PONTE)
UPDATE schools SET inep_code = '347728' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA NEUZA LOPES PINTO' AND UPPER(TRIM(city)) = 'NOVA PONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '347728');

-- EM SÃO MIGUEL (NOVA PONTE)
UPDATE schools SET inep_code = '166987' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SÃO MIGUEL' AND UPPER(TRIM(city)) = 'NOVA PONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '166987');

-- EM AFONSINA MARIA DE JESUS (PRATA)
UPDATE schools SET inep_code = '167100' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM AFONSINA MARIA DE JESUS' AND UPPER(TRIM(city)) = 'PRATA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167100');

-- EM DOM PEDRO II (PRATA)
UPDATE schools SET inep_code = '168955' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOM PEDRO II' AND UPPER(TRIM(city)) = 'PRATA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '168955');

-- EM MARIANA CLARA GOUVEIA (PRATA)
UPDATE schools SET inep_code = '167096' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIANA CLARA GOUVEIA' AND UPPER(TRIM(city)) = 'PRATA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '167096');

-- EM PADRE JOÃO ANESI (PRATA)
UPDATE schools SET inep_code = '169129' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PADRE JOÃO ANESI' AND UPPER(TRIM(city)) = 'PRATA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '169129');

-- EM MARIA CONCEIÇÃO BORGES (TUPACIGUARA)
UPDATE schools SET inep_code = '233731' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA CONCEIÇÃO BORGES' AND UPPER(TRIM(city)) = 'TUPACIGUARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '233731');

-- EM PAZ E AMOR (TUPACIGUARA)
UPDATE schools SET inep_code = '169439' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PAZ E AMOR' AND UPPER(TRIM(city)) = 'TUPACIGUARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '169439');

-- EM AFRÂNIO RODRIGUES DA CUNHA (UBERLÂNDIA)
UPDATE schools SET inep_code = '169528' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM AFRÂNIO RODRIGUES DA CUNHA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '169528');

-- EM ANTONINO MARTINS DA SILVA (UBERLÂNDIA)
UPDATE schools SET inep_code = '170143' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANTONINO MARTINS DA SILVA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170143');

-- EM CARLOS TUCCI (UBERLÂNDIA)
UPDATE schools SET inep_code = '169561' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CARLOS TUCCI' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '169561');

-- EM DE SOBRADINHO (UBERLÂNDIA)
UPDATE schools SET inep_code = '228699' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DE SOBRADINHO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '228699');

-- EM DO BAIRRO SHOPPING PARK (UBERLÂNDIA)
UPDATE schools SET inep_code = '319651' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DO BAIRRO SHOPPING PARK' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '319651');

-- EM DO MORENO (UBERLÂNDIA)
UPDATE schools SET inep_code = '169676' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DO MORENO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '169676');

-- EM DOM BOSCO (UBERLÂNDIA)
UPDATE schools SET inep_code = '214141' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOM BOSCO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '214141');

-- EM DOMINGAS CAMIN (UBERLÂNDIA)
UPDATE schools SET inep_code = '170151' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOMINGAS CAMIN' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170151');

-- EM DR GLADSEN GUERRA DE REZENDE (UBERLÂNDIA)
UPDATE schools SET inep_code = '271578' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DR GLADSEN GUERRA DE REZENDE' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '271578');

-- EM DR JOEL CUPERTINO RODRIGUES (UBERLÂNDIA)
UPDATE schools SET inep_code = '245917' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DR JOEL CUPERTINO RODRIGUES' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '245917');

-- EM EMÍLIO RIBAS (UBERLÂNDIA)
UPDATE schools SET inep_code = '169820' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM EMÍLIO RIBAS' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '169820');

-- EM FREITAS AZEVEDO (UBERLÂNDIA)
UPDATE schools SET inep_code = '169889' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM FREITAS AZEVEDO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '169889');

-- EM HILDA LEÃO CARNEIRO (UBERLÂNDIA)
UPDATE schools SET inep_code = '246743' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM HILDA LEÃO CARNEIRO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '246743');

-- EM JOSÉ MARRA DA FONSECA (UBERLÂNDIA)
UPDATE schools SET inep_code = '170135' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ MARRA DA FONSECA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170135');

-- EM LEANDRO JOSÉ DE OLIVEIRA (UBERLÂNDIA)
UPDATE schools SET inep_code = '214175' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM LEANDRO JOSÉ DE OLIVEIRA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '214175');

-- EM ODILON CUSTÓDIO PEREIRA (UBERLÂNDIA)
UPDATE schools SET inep_code = '319716' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ODILON CUSTÓDIO PEREIRA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '319716');

-- EM OLHOS D'ÁGUA (UBERLÂNDIA)
UPDATE schools SET inep_code = '170054' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM OLHOS D''ÁGUA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170054');

-- EM PROFA MARIA REGINA ARANTES LEMES (UBERLÂNDIA)
UPDATE schools SET inep_code = '170089' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFA MARIA REGINA ARANTES LEMES' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170089');

-- EM PROFA STELLA SARAIVA PEANO (UBERLÂNDIA)
UPDATE schools SET inep_code = '249238' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFA STELLA SARAIVA PEANO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '249238');

-- EM PROFESSOR DOMINGOS PIMENTEL ULHOA (UBERLÂNDIA)
UPDATE schools SET inep_code = '245909' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR DOMINGOS PIMENTEL ULHOA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '245909');

-- EM PROFESSOR EURICO SILVA (UBERLÂNDIA)
UPDATE schools SET inep_code = '228745' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR EURICO SILVA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '228745');

-- EM PROFESSOR JACY DE ASSIS (UBERLÂNDIA)
UPDATE schools SET inep_code = '269832' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR JACY DE ASSIS' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '269832');

-- EM PROFESSOR LADÁRIO TEIXEIRA (UBERLÂNDIA)
UPDATE schools SET inep_code = '247499' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR LADÁRIO TEIXEIRA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '247499');

-- EM PROFESSOR LEÔNCIO DO CARMO CHAVES (UBERLÂNDIA)
UPDATE schools SET inep_code = '228761' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR LEÔNCIO DO CARMO CHAVES' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '228761');

-- EM PROFESSOR MÁRIO GODOY CASTANHO (UBERLÂNDIA)
UPDATE schools SET inep_code = '239631' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR MÁRIO GODOY CASTANHO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '239631');

-- EM PROFESSOR OTÁVIO BATISTA COELHO FILHO (UBERLÂNDIA)
UPDATE schools SET inep_code = '240371' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR OTÁVIO BATISTA COELHO FILHO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '240371');

-- EM PROFESSOR SÉRGIO DE OLIVEIRA MARQUEZ (UBERLÂNDIA)
UPDATE schools SET inep_code = '228753' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR SÉRGIO DE OLIVEIRA MARQUEZ' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '228753');

-- EM PROFESSORA CARLOTA DE ANDRADE MARQUEZ (UBERLÂNDIA)
UPDATE schools SET inep_code = '354210' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA CARLOTA DE ANDRADE MARQUEZ' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '354210');

-- EM PROFESSORA CECY CARDOSO PORFÍRIO (UBERLÂNDIA)
UPDATE schools SET inep_code = '239623' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA CECY CARDOSO PORFÍRIO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '239623');

-- EM PROFESSORA JOSIANY FRANÇA (UBERLÂNDIA)
UPDATE schools SET inep_code = '338400' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA JOSIANY FRANÇA' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '338400');

-- EM PROFESSORA OLGA DEL FÁVERO (UBERLÂNDIA)
UPDATE schools SET inep_code = '249190' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA OLGA DEL FÁVERO' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '249190');

-- EM PROFESSORA ORLANDA NEVES STRACK (UBERLÂNDIA)
UPDATE schools SET inep_code = '325473' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA ORLANDA NEVES STRACK' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '325473');

-- EM SEBASTIÃO RANGEL (UBERLÂNDIA)
UPDATE schools SET inep_code = '170160' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SEBASTIÃO RANGEL' AND UPPER(TRIM(city)) = 'UBERLÂNDIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '170160');

-- EM JOÃO FERNANDES PITANGUI (ARINOS)
UPDATE schools SET inep_code = '109762' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOÃO FERNANDES PITANGUI' AND UPPER(TRIM(city)) = 'ARINOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '109762');

-- EM JOÃO GONTIJO FERREIRA (ARINOS)
UPDATE schools SET inep_code = '272558' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOÃO GONTIJO FERREIRA' AND UPPER(TRIM(city)) = 'ARINOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '272558');

-- EM PRINCESA ISABEL (ARINOS)
UPDATE schools SET inep_code = '109690' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PRINCESA ISABEL' AND UPPER(TRIM(city)) = 'ARINOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '109690');

-- EM RIVALINO ÁLVARO DURÃES (ARINOS)
UPDATE schools SET inep_code = '109851' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM RIVALINO ÁLVARO DURÃES' AND UPPER(TRIM(city)) = 'ARINOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '109851');

-- EM SANTOS REIS (ARINOS)
UPDATE schools SET inep_code = '109967' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SANTOS REIS' AND UPPER(TRIM(city)) = 'ARINOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '109967');

-- EM VASCO BERNARDES DE OLIVEIRA (ARINOS)
UPDATE schools SET inep_code = '108201' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM VASCO BERNARDES DE OLIVEIRA' AND UPPER(TRIM(city)) = 'ARINOS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108201');

-- EM DERCÍLIO DUARTE MELGAÇO (BONFINÓPOLIS DE MINAS)
UPDATE schools SET inep_code = '108359' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DERCÍLIO DUARTE MELGAÇO' AND UPPER(TRIM(city)) = 'BONFINÓPOLIS DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108359');

-- EM ANTÃO ALVES DA SILVA (BURITIS)
UPDATE schools SET inep_code = '214493' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANTÃO ALVES DA SILVA' AND UPPER(TRIM(city)) = 'BURITIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '214493');

-- EM ANTONINO CÂNDIDO LOPES (BURITIS)
UPDATE schools SET inep_code = '334332' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANTONINO CÂNDIDO LOPES' AND UPPER(TRIM(city)) = 'BURITIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '334332');

-- EM CÂNDIDO JOSÉ LOPES (BURITIS)
UPDATE schools SET inep_code = '108405' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CÂNDIDO JOSÉ LOPES' AND UPPER(TRIM(city)) = 'BURITIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '108405');