-- EM JOSÉ MARIA AMÂNCIO (MATIAS BARBOSA)
UPDATE schools SET inep_code = '269042' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ MARIA AMÂNCIO' AND UPPER(TRIM(city)) = 'MATIAS BARBOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '269042');

-- EM LUCY DE CASTRO CABRAL (MATIAS BARBOSA)
UPDATE schools SET inep_code = '269051' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM LUCY DE CASTRO CABRAL' AND UPPER(TRIM(city)) = 'MATIAS BARBOSA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '269051');

-- EM DOUTOR JOSÉ ROGÉRIO MOURA ALMEIDA (RIO PRETO)
UPDATE schools SET inep_code = '271055' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOUTOR JOSÉ ROGÉRIO MOURA ALMEIDA' AND UPPER(TRIM(city)) = 'RIO PRETO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '271055');

-- EM PADRE MACHADO (SANTA RITA DE JACUTINGA)
UPDATE schools SET inep_code = '269344' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PADRE MACHADO' AND UPPER(TRIM(city)) = 'SANTA RITA DE JACUTINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '269344');

-- COLÉGIO MUNICIPAL SANTO ANTÔNIO (SANTOS DUMONT)
UPDATE schools SET inep_code = '311014' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'COLÉGIO MUNICIPAL SANTO ANTÔNIO' AND UPPER(TRIM(city)) = 'SANTOS DUMONT' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '311014');

-- EM ANITA SOARES DULCI (SANTOS DUMONT)
UPDATE schools SET inep_code = '343757' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANITA SOARES DULCI' AND UPPER(TRIM(city)) = 'SANTOS DUMONT' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '343757');

-- EM DOUTOR AUGUSTO GLÓRIA (SÃO JOÃO NEPOMUCENO)
UPDATE schools SET inep_code = '344931' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOUTOR AUGUSTO GLÓRIA' AND UPPER(TRIM(city)) = 'SÃO JOÃO NEPOMUCENO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '344931');

-- EM TRÊS MARIAS (SÃO JOÃO NEPOMUCENO)
UPDATE schools SET inep_code = '267724' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM TRÊS MARIAS' AND UPPER(TRIM(city)) = 'SÃO JOÃO NEPOMUCENO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '267724');

-- EM JOÃO IGNÁCIO PEIXOTO (CATAGUASES)
UPDATE schools SET inep_code = '100102' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOÃO IGNÁCIO PEIXOTO' AND UPPER(TRIM(city)) = 'CATAGUASES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '100102');

-- EM LYSIS BRANDÃO DA ROCHA (CATAGUASES)
UPDATE schools SET inep_code = '257028' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM LYSIS BRANDÃO DA ROCHA' AND UPPER(TRIM(city)) = 'CATAGUASES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '257028');

-- ESC TEC MUN JOANA D'ARC (CATAGUASES)
UPDATE schools SET inep_code = '222003' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESC TEC MUN JOANA D''ARC' AND UPPER(TRIM(city)) = 'CATAGUASES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '222003');

-- EM JUDITH LINTZ GUEDES MACHADO (LEOPOLDINA)
UPDATE schools SET inep_code = '268381' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JUDITH LINTZ GUEDES MACHADO' AND UPPER(TRIM(city)) = 'LEOPOLDINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '268381');

-- EM OSMAR LACERDA FRANÇA (LEOPOLDINA)
UPDATE schools SET inep_code = '320528' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM OSMAR LACERDA FRANÇA' AND UPPER(TRIM(city)) = 'LEOPOLDINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '320528');

-- EM PROFESSORA MARIA DA CONCEIÇÃO MONTEIRO DE RESENDE (LEOPOLDINA)
UPDATE schools SET inep_code = '250821' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA MARIA DA CONCEIÇÃO MONTEIRO DE RESENDE' AND UPPER(TRIM(city)) = 'LEOPOLDINA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '250821');

-- CENTRO EDUCACIONAL MUNICIPAL 2000 (PIRAPETINGA)
UPDATE schools SET inep_code = '274780' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL MUNICIPAL 2000' AND UPPER(TRIM(city)) = 'PIRAPETINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '274780');

-- CENTRO EDUCACIONAL MUNICIPAL DE PIRAPETINGA - CEMP COLINA DO SOL (PIRAPETINGA)
UPDATE schools SET inep_code = '260428' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CENTRO EDUCACIONAL MUNICIPAL DE PIRAPETINGA - CEMP COLINA DO SOL' AND UPPER(TRIM(city)) = 'PIRAPETINGA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '260428');

-- EM JOÃO DAMASCENO FERREIRA (RECREIO)
UPDATE schools SET inep_code = '272825' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOÃO DAMASCENO FERREIRA' AND UPPER(TRIM(city)) = 'RECREIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '272825');

-- EM PROFESSORA NICE DAMASCENO ALMEIDA MUNIZ (RECREIO)
UPDATE schools SET inep_code = '275581' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA NICE DAMASCENO ALMEIDA MUNIZ' AND UPPER(TRIM(city)) = 'RECREIO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '275581');

-- EM N SRA DO ROSÁRIO (VOLTA GRANDE)
UPDATE schools SET inep_code = '315583' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM N SRA DO ROSÁRIO' AND UPPER(TRIM(city)) = 'VOLTA GRANDE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '315583');

-- EM GIDIEL CÂMARA (DURANDÉ)
UPDATE schools SET inep_code = '217000' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM GIDIEL CÂMARA' AND UPPER(TRIM(city)) = 'DURANDÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217000');

-- EM PAULO CÉZAR HASTENREITER PORTES (LAJINHA)
UPDATE schools SET inep_code = '295221' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PAULO CÉZAR HASTENREITER PORTES' AND UPPER(TRIM(city)) = 'LAJINHA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '295221');

-- EM JAIR GUALBERTO DA ROCHA (MATIPÓ)
UPDATE schools SET inep_code = '331465' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JAIR GUALBERTO DA ROCHA' AND UPPER(TRIM(city)) = 'MATIPÓ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '331465');

-- EM AGROPECUÁRIA MAJOLO COSTA MACHADO (SANTA MARGARIDA)
UPDATE schools SET inep_code = '312495' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM AGROPECUÁRIA MAJOLO COSTA MACHADO' AND UPPER(TRIM(city)) = 'SANTA MARGARIDA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312495');

-- EM DONA DURVALINA (SÃO JOÃO DO MANHUAÇU)
UPDATE schools SET inep_code = '236250' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DONA DURVALINA' AND UPPER(TRIM(city)) = 'SÃO JOÃO DO MANHUAÇU' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '236250');

-- EM ROSALINA CALEGÁRIO DE SOUZA (SIMONÉSIA)
UPDATE schools SET inep_code = '314307' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ROSALINA CALEGÁRIO DE SOUZA' AND UPPER(TRIM(city)) = 'SIMONÉSIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '314307');

-- EM JOSÉ MARIA DOS MARES GUIA (BARÃO DE COCAIS)
UPDATE schools SET inep_code = '267074' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ MARIA DOS MARES GUIA' AND UPPER(TRIM(city)) = 'BARÃO DE COCAIS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '267074');

-- EM ANÍSIO TEIXEIRA (BELO HORIZONTE)
UPDATE schools SET inep_code = '250651' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANÍSIO TEIXEIRA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '250651');

-- EM DOUTOR JÚLIO SOARES (BELO HORIZONTE)
UPDATE schools SET inep_code = '346853' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOUTOR JÚLIO SOARES' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346853');

-- EM FERNANDO DIAS COSTA (BELO HORIZONTE)
UPDATE schools SET inep_code = '217875' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM FERNANDO DIAS COSTA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217875');

-- EM GOVERNADOR OZANAN COELHO (BELO HORIZONTE)
UPDATE schools SET inep_code = '224111' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM GOVERNADOR OZANAN COELHO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '224111');

-- EM HENRIQUETA LISBOA (BELO HORIZONTE)
UPDATE schools SET inep_code = '212768' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM HENRIQUETA LISBOA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '212768');

-- EM JARDIM VITÓRIA II (BELO HORIZONTE)
UPDATE schools SET inep_code = '362581' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JARDIM VITÓRIA II' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '362581');

-- EM JOSÉ DE CALASANZ (BELO HORIZONTE)
UPDATE schools SET inep_code = '305499' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ DE CALASANZ' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305499');

-- EM MARIA DA ASSUNÇÃO DE MARCO (BELO HORIZONTE)
UPDATE schools SET inep_code = '231991' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA DA ASSUNÇÃO DE MARCO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '231991');

-- EM MURILO RUBIÃO (BELO HORIZONTE)
UPDATE schools SET inep_code = '217883' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MURILO RUBIÃO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217883');

-- EM OSWALDO FRANÇA JÚNIOR (BELO HORIZONTE)
UPDATE schools SET inep_code = '219223' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM OSWALDO FRANÇA JÚNIOR' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '219223');

-- EM PADRE FRANCISCO CARVALHO MOREIRA (BELO HORIZONTE)
UPDATE schools SET inep_code = '218618' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PADRE FRANCISCO CARVALHO MOREIRA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218618');

-- EM PAULO MENDES CAMPOS (BELO HORIZONTE)
UPDATE schools SET inep_code = '223689' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PAULO MENDES CAMPOS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '223689');

-- EM PRESIDENTE JOÃO PESSOA (BELO HORIZONTE)
UPDATE schools SET inep_code = '232017' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PRESIDENTE JOÃO PESSOA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '232017');

-- EM PROFESSOR EDGAR DA MATTA MACHADO (BELO HORIZONTE)
UPDATE schools SET inep_code = '283002' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR EDGAR DA MATTA MACHADO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '283002');

-- EM PROFESSOR EDSON PISANI (BELO HORIZONTE)
UPDATE schools SET inep_code = '212784' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR EDSON PISANI' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '212784');

-- EM PROFESSOR PAULO FREIRE (BELO HORIZONTE)
UPDATE schools SET inep_code = '305481' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR PAULO FREIRE' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '305481');

-- EM PROFESSORA MARIA MAZARELLO (BELO HORIZONTE)
UPDATE schools SET inep_code = '219193' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA MARIA MAZARELLO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '219193');

-- EM SOBRAL PINTO (BELO HORIZONTE)
UPDATE schools SET inep_code = '219550' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SOBRAL PINTO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '219550');

-- EM ULISSES GUIMARÃES (BELO HORIZONTE)
UPDATE schools SET inep_code = '231983' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ULISSES GUIMARÃES' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '231983');

-- EM VILA FAZENDINHA (BELO HORIZONTE)
UPDATE schools SET inep_code = '330868' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM VILA FAZENDINHA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '330868');

-- EM LIDIMANHA AUGUSTA MAIA (BRUMADINHO)
UPDATE schools SET inep_code = '240435' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM LIDIMANHA AUGUSTA MAIA' AND UPPER(TRIM(city)) = 'BRUMADINHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '240435');

-- EM PADRE MACHADO (BRUMADINHO)
UPDATE schools SET inep_code = '361070' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PADRE MACHADO' AND UPPER(TRIM(city)) = 'BRUMADINHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '361070');

-- EM BENVINDA PINTO ROCHA (NOVA LIMA)
UPDATE schools SET inep_code = '226459' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM BENVINDA PINTO ROCHA' AND UPPER(TRIM(city)) = 'NOVA LIMA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '226459');

-- CAIC EM ANÍBAL MACHADO (SABARÁ)
UPDATE schools SET inep_code = '277851' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CAIC EM ANÍBAL MACHADO' AND UPPER(TRIM(city)) = 'SABARÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '277851');

-- EM ADÃO DE FÁTIMA PEREIRA (SABARÁ)
UPDATE schools SET inep_code = '329436' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ADÃO DE FÁTIMA PEREIRA' AND UPPER(TRIM(city)) = 'SABARÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '329436');

-- EM EDITH DE ASSISTÊNCIA COSTA (SABARÁ)
UPDATE schools SET inep_code = '294250' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM EDITH DE ASSISTÊNCIA COSTA' AND UPPER(TRIM(city)) = 'SABARÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '294250');

-- EM GABRIELA LEITE ARAÚJO (SABARÁ)
UPDATE schools SET inep_code = '223069' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM GABRIELA LEITE ARAÚJO' AND UPPER(TRIM(city)) = 'SABARÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '223069');

-- EM ORDÁLIA FERREIRA CAMPOS (SABARÁ)
UPDATE schools SET inep_code = '296635' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ORDÁLIA FERREIRA CAMPOS' AND UPPER(TRIM(city)) = 'SABARÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '296635');

-- EM PROFESSORA ELZA SOARES (SABARÁ)
UPDATE schools SET inep_code = '253154' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA ELZA SOARES' AND UPPER(TRIM(city)) = 'SABARÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253154');

-- EM PROFESSORA IRENE PINTO (SABARÁ)
UPDATE schools SET inep_code = '226505' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA IRENE PINTO' AND UPPER(TRIM(city)) = 'SABARÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '226505');

-- EM PROFESSORA MARITA DIAS (SABARÁ)
UPDATE schools SET inep_code = '323721' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA MARITA DIAS' AND UPPER(TRIM(city)) = 'SABARÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '323721');

-- EM VEREADOR JOSÉ LOPES (SABARÁ)
UPDATE schools SET inep_code = '323705' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM VEREADOR JOSÉ LOPES' AND UPPER(TRIM(city)) = 'SABARÁ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '323705');

-- EM ADÉLIA HOSKEN AYRES (SANTA BÁRBARA)
UPDATE schools SET inep_code = '330302' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ADÉLIA HOSKEN AYRES' AND UPPER(TRIM(city)) = 'SANTA BÁRBARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '330302');

-- EM IRMA AMANDINA MARIA (SANTA BÁRBARA)
UPDATE schools SET inep_code = '211435' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM IRMA AMANDINA MARIA' AND UPPER(TRIM(city)) = 'SANTA BÁRBARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '211435');

-- EM IVETA MOREIRA NOVAIS (SANTA BÁRBARA)
UPDATE schools SET inep_code = '247197' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM IVETA MOREIRA NOVAIS' AND UPPER(TRIM(city)) = 'SANTA BÁRBARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '247197');

-- EM MARPHIZA MAGALHÃES SANTOS (SANTA BÁRBARA)
UPDATE schools SET inep_code = '234621' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARPHIZA MAGALHÃES SANTOS' AND UPPER(TRIM(city)) = 'SANTA BÁRBARA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '234621');

-- CIAC EM LUCAS MONTEIRO MACHADO (BELO HORIZONTE)
UPDATE schools SET inep_code = '244473' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CIAC EM LUCAS MONTEIRO MACHADO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '244473');

-- EM AURÉLIO BUARQUE DE HOLANDA (BELO HORIZONTE)
UPDATE schools SET inep_code = '217786' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM AURÉLIO BUARQUE DE HOLANDA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217786');

-- EM DA VILA PINHO (BELO HORIZONTE)
UPDATE schools SET inep_code = '217859' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DA VILA PINHO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217859');

-- EM DOM BOSCO (BELO HORIZONTE)
UPDATE schools SET inep_code = '331589' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOM BOSCO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '331589');

-- EM DULCE MARIA HOMEM (BELO HORIZONTE)
UPDATE schools SET inep_code = '212776' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DULCE MARIA HOMEM' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '212776');

-- EM EDITH PIMENTA DA VEIGA (BELO HORIZONTE)
UPDATE schools SET inep_code = '217867' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM EDITH PIMENTA DA VEIGA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217867');

-- EM ELOY HERALDO LIMA (BELO HORIZONTE)
UPDATE schools SET inep_code = '217824' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ELOY HERALDO LIMA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217824');

-- EM IGNÁCIO DE ANDRADE MELO (BELO HORIZONTE)
UPDATE schools SET inep_code = '205699' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM IGNÁCIO DE ANDRADE MELO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '205699');

-- EM LUIZ GONZAGA JÚNIOR (BELO HORIZONTE)
UPDATE schools SET inep_code = '217832' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM LUIZ GONZAGA JÚNIOR' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217832');

-- EM MARLENE PEREIRA RANCANTE (BELO HORIZONTE)
UPDATE schools SET inep_code = '217794' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARLENE PEREIRA RANCANTE' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217794');

-- EM PEDRO NAVA (BELO HORIZONTE)
UPDATE schools SET inep_code = '231975' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PEDRO NAVA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '231975');

-- EM PREFEITO OSWALDO PIERUCCETTI (BELO HORIZONTE)
UPDATE schools SET inep_code = '219398' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PREFEITO OSWALDO PIERUCCETTI' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '219398');

-- EM PRESIDENTE ITAMAR FRANCO (BELO HORIZONTE)
UPDATE schools SET inep_code = '353760' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PRESIDENTE ITAMAR FRANCO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '353760');

-- EM PROFESSOR HÍLTON ROCHA (BELO HORIZONTE)
UPDATE schools SET inep_code = '294659' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR HÍLTON ROCHA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '294659');

-- EM SOLAR RUBI (BELO HORIZONTE)
UPDATE schools SET inep_code = '358614' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SOLAR RUBI' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '358614');

-- EM UNIÃO COMUNITÁRIA (BELO HORIZONTE)
UPDATE schools SET inep_code = '273252' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM UNIÃO COMUNITÁRIA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '273252');

-- EM VINÍCIUS DE MORAIS (BELO HORIZONTE)
UPDATE schools SET inep_code = '217841' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM VINÍCIUS DE MORAIS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217841');

-- ESCOLA MUNICIPAL POLO DE EDUCAÇÃO INTEGRADA (BELO HORIZONTE)
UPDATE schools SET inep_code = '369446' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'ESCOLA MUNICIPAL POLO DE EDUCAÇÃO INTEGRADA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '369446');

-- CAIC EM ISRAEL JOSÉ CARLOS (BETIM)
UPDATE schools SET inep_code = '251356' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CAIC EM ISRAEL JOSÉ CARLOS' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '251356');

-- EM ABÍLIO GOMES DA COSTA (BETIM)
UPDATE schools SET inep_code = '240702' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ABÍLIO GOMES DA COSTA' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '240702');

-- EM ADELINA GONÇALVES CAMPOS (BETIM)
UPDATE schools SET inep_code = '226360' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ADELINA GONÇALVES CAMPOS' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '226360');

-- EM ADELINA MESQUITA JANUZZI (BETIM)
UPDATE schools SET inep_code = '251321' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ADELINA MESQUITA JANUZZI' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '251321');

-- EM ANA CÂNDIDA DE JESUS (BETIM)
UPDATE schools SET inep_code = '354244' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANA CÂNDIDA DE JESUS' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '354244');

-- EM ANGELA RIBEIRO BATISTA MAIA (BETIM)
UPDATE schools SET inep_code = '331325' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANGELA RIBEIRO BATISTA MAIA' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '331325');

-- EM ANTÔNIO TEREZA DOS SANTOS (BETIM)
UPDATE schools SET inep_code = '332941' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANTÔNIO TEREZA DOS SANTOS' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '332941');

-- EM ARISTIDES JOSÉ DA SILVA (BETIM)
UPDATE schools SET inep_code = '226581' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ARISTIDES JOSÉ DA SILVA' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '226581');

-- EM ARTHUR TRINDADE (BETIM)
UPDATE schools SET inep_code = '226351' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ARTHUR TRINDADE' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '226351');

-- EM BELIZÁRIO FERREIRA CAMINHAS (BETIM)
UPDATE schools SET inep_code = '251313' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM BELIZÁRIO FERREIRA CAMINHAS' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '251313');

-- EM BENTO MACHADO RIBEIRO (BETIM)
UPDATE schools SET inep_code = '251305' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM BENTO MACHADO RIBEIRO' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '251305');

-- EM EDIR TEREZINHA A FAGUNDES (BETIM)
UPDATE schools SET inep_code = '260991' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM EDIR TEREZINHA A FAGUNDES' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '260991');

-- EM EDMÉIA DUARTE DE OLIVEIRA BRAGA (BETIM)
UPDATE schools SET inep_code = '260045' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM EDMÉIA DUARTE DE OLIVEIRA BRAGA' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '260045');

-- EM EDVALDO FALEIRO DE AGUIAR (BETIM)
UPDATE schools SET inep_code = '365262' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM EDVALDO FALEIRO DE AGUIAR' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '365262');

-- EM FAUSTO FIGUEIREDO OLIVEIRA (BETIM)
UPDATE schools SET inep_code = '240711' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM FAUSTO FIGUEIREDO OLIVEIRA' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '240711');

-- EM FLORESTAN FERNANDES (BETIM)
UPDATE schools SET inep_code = '281069' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM FLORESTAN FERNANDES' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '281069');

-- EM GERALDO JORGE MEIRA (BETIM)
UPDATE schools SET inep_code = '303593' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM GERALDO JORGE MEIRA' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '303593');

-- EM GILBERTO ALVES DA SILVA (BETIM)
UPDATE schools SET inep_code = '354465' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM GILBERTO ALVES DA SILVA' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '354465');

-- EM JOÃO BATISTA MACHADO DE BRITO (BETIM)
UPDATE schools SET inep_code = '349585' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOÃO BATISTA MACHADO DE BRITO' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349585');

-- EM JOSÉ MIRANDA SOBRINHO (BETIM)
UPDATE schools SET inep_code = '239470' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ MIRANDA SOBRINHO' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '239470');

-- EM JOSÉ VILAÇA GUIMARÃES (BETIM)
UPDATE schools SET inep_code = '330914' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ VILAÇA GUIMARÃES' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '330914');

-- EM JOSEFINA MACEDO GONTIJO (BETIM)
UPDATE schools SET inep_code = '226602' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSEFINA MACEDO GONTIJO' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '226602');

-- EM LÚCIA FARAGE FREITAS GUMIERO (BETIM)
UPDATE schools SET inep_code = '250589' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM LÚCIA FARAGE FREITAS GUMIERO' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '250589');

-- EM MARGARIDA SOARES GUIMARÃES (BETIM)
UPDATE schools SET inep_code = '226572' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARGARIDA SOARES GUIMARÃES' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '226572');

-- EM MARIA ARACÉLIA ALVES (BETIM)
UPDATE schools SET inep_code = '312410' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA ARACÉLIA ALVES' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312410');

-- EM MARIA DA CONCEIÇÃO BRITO (BETIM)
UPDATE schools SET inep_code = '242730' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA DA CONCEIÇÃO BRITO' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '242730');

-- EM MARIA DA PENHA SANTOS ALMEIDA (BETIM)
UPDATE schools SET inep_code = '260029' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA DA PENHA SANTOS ALMEIDA' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '260029');

-- EM MARIA DE LOURDES OLIVEIRA (BETIM)
UPDATE schools SET inep_code = '251330' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA DE LOURDES OLIVEIRA' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '251330');

-- EM MARIA ELENA DA CUNHA BRAZ (BETIM)
UPDATE schools SET inep_code = '317136' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA ELENA DA CUNHA BRAZ' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '317136');

-- EM MARIA JOSÉ CAMPOS (BETIM)
UPDATE schools SET inep_code = '354252' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA JOSÉ CAMPOS' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '354252');

-- EM MÁRIO MARCOS C TUPYNAMBÁ (BETIM)
UPDATE schools SET inep_code = '311430' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MÁRIO MARCOS C TUPYNAMBÁ' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '311430');

-- EM OLÍMPIA MARIA DA GLÓRIA (BETIM)
UPDATE schools SET inep_code = '226599' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM OLÍMPIA MARIA DA GLÓRIA' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '226599');

-- EM OSÓRIO ALEIXO DA SILVA (BETIM)
UPDATE schools SET inep_code = '234591' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM OSÓRIO ALEIXO DA SILVA' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '234591');

-- EM PROFESSOR KÁSSIO VINÍCIUS CASTRO GOMES (BETIM)
UPDATE schools SET inep_code = '354406' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR KÁSSIO VINÍCIUS CASTRO GOMES' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '354406');

-- EM RITA MARIA SILVA (BETIM)
UPDATE schools SET inep_code = '323781' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM RITA MARIA SILVA' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '323781');

-- EM SEBASTIÃO FERREIRA DE OLIVEIRA (BETIM)
UPDATE schools SET inep_code = '226564' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SEBASTIÃO FERREIRA DE OLIVEIRA' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '226564');

-- EM TITO FLÁVIUS LIMA ANDRADE (BETIM)
UPDATE schools SET inep_code = '226556' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM TITO FLÁVIUS LIMA ANDRADE' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '226556');

-- EM VALÉRIO FERREIRA PALHARES (BETIM)
UPDATE schools SET inep_code = '243141' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM VALÉRIO FERREIRA PALHARES' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '243141');

-- EM VEREADOR RAFAEL BARBIZAN (BETIM)
UPDATE schools SET inep_code = '321796' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM VEREADOR RAFAEL BARBIZAN' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '321796');

-- EM WALDEMAR DA LUZ GONÇALVES (BETIM)
UPDATE schools SET inep_code = '223026' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM WALDEMAR DA LUZ GONÇALVES' AND UPPER(TRIM(city)) = 'BETIM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '223026');

-- CAIC EM MARIA SILVA LUCAS (CONTAGEM)
UPDATE schools SET inep_code = '236799' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'CAIC EM MARIA SILVA LUCAS' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '236799');

-- EM  SENADOR JOSÉ DE ALENCAR (CONTAGEM)
UPDATE schools SET inep_code = '372137' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM  SENADOR JOSÉ DE ALENCAR' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '372137');

-- EM ALBERTINA ALVES DO NASCIMENTO (CONTAGEM)
UPDATE schools SET inep_code = '350109' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ALBERTINA ALVES DO NASCIMENTO' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '350109');

-- EM CARLOS DRUMOND DE ANDRADE (CONTAGEM)
UPDATE schools SET inep_code = '220957' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CARLOS DRUMOND DE ANDRADE' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '220957');

-- EM DOMINGOS JOSÉ DINIZ COSTA BELÉM (CONTAGEM)
UPDATE schools SET inep_code = '342912' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOMINGOS JOSÉ DINIZ COSTA BELÉM' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '342912');

-- EM ELI HORTA COSTA (CONTAGEM)
UPDATE schools SET inep_code = '350117' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ELI HORTA COSTA' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '350117');

-- EM ESTUDANTE LEONARDO SADRA (CONTAGEM)
UPDATE schools SET inep_code = '220965' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ESTUDANTE LEONARDO SADRA' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '220965');

-- EM FRANCISCO SALES DA SILVA DINIZ (CONTAGEM)
UPDATE schools SET inep_code = '307891' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM FRANCISCO SALES DA SILVA DINIZ' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '307891');

-- EM GIOVANINI CHIODI (CONTAGEM)
UPDATE schools SET inep_code = '307904' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM GIOVANINI CHIODI' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '307904');

-- EM GLÓRIA MARQUES DINIZ (CONTAGEM)
UPDATE schools SET inep_code = '247405' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM GLÓRIA MARQUES DINIZ' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '247405');

-- EM HEITOR VILLA LOBOS (CONTAGEM)
UPDATE schools SET inep_code = '217115' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM HEITOR VILLA LOBOS' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217115');

-- EM HILDA NUNES DOS SANTOS (CONTAGEM)
UPDATE schools SET inep_code = '322377' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM HILDA NUNES DOS SANTOS' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322377');

-- EM IVAN DINIZ MACEDO (CONTAGEM)
UPDATE schools SET inep_code = '277258' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM IVAN DINIZ MACEDO' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '277258');

-- EM JOSÉ LUCAS FILHO (CONTAGEM)
UPDATE schools SET inep_code = '222992' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ LUCAS FILHO' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '222992');

-- EM MACHADO DE ASSIS (CONTAGEM)
UPDATE schools SET inep_code = '220981' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MACHADO DE ASSIS' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '220981');

-- EM MARIA DO CARMO ORECHIO (CONTAGEM)
UPDATE schools SET inep_code = '348597' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA DO CARMO ORECHIO' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '348597');

-- EM OTACIR NUNES DOS SANTOS (CONTAGEM)
UPDATE schools SET inep_code = '307882' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM OTACIR NUNES DOS SANTOS' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '307882');

-- EM PADRE JOAQUIM DE SOUZA SILVA (CONTAGEM)
UPDATE schools SET inep_code = '222984' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PADRE JOAQUIM DE SOUZA SILVA' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '222984');

-- EM PAULO CÉZAR CUNHA (CONTAGEM)
UPDATE schools SET inep_code = '322709' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PAULO CÉZAR CUNHA' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322709');

-- EM PREFEITO LUIZ DA CUNHA (CONTAGEM)
UPDATE schools SET inep_code = '223018' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PREFEITO LUIZ DA CUNHA' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '223018');

-- EM PROFESSOR GERALDO BASÍLIO RAMOS (CONTAGEM)
UPDATE schools SET inep_code = '343811' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR GERALDO BASÍLIO RAMOS' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '343811');

-- EM PROFESSOR HÍLTON ROCHA (CONTAGEM)
UPDATE schools SET inep_code = '253871' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR HÍLTON ROCHA' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253871');

-- EM PROFESSOR RICARDO BRÁS GOMES BARRETO (CONTAGEM)
UPDATE schools SET inep_code = '350125' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR RICARDO BRÁS GOMES BARRETO' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '350125');

-- EM PROFESSOR WANCLEBER PACHECO (CONTAGEM)
UPDATE schools SET inep_code = '223000' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR WANCLEBER PACHECO' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '223000');

-- EM PROFESSORA ANA GUEDES VIEIRA (CONTAGEM)
UPDATE schools SET inep_code = '231304' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA ANA GUEDES VIEIRA' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '231304');

-- EM PROFESSORA LÍGIA MAGALHÃES (CONTAGEM)
UPDATE schools SET inep_code = '212563' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA LÍGIA MAGALHÃES' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '212563');

-- EM PROFESSORA MARIA DE MATOS SILVEIRA (CONTAGEM)
UPDATE schools SET inep_code = '223042' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA MARIA DE MATOS SILVEIRA' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '223042');

-- EM PROFESSORA MARIA MARTINS MARIINHA (CONTAGEM)
UPDATE schools SET inep_code = '372129' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA MARIA MARTINS MARIINHA' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '372129');

-- EM PROFESSORA MARIA OLINTHA (CONTAGEM)
UPDATE schools SET inep_code = '376400' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA MARIA OLINTHA' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '376400');

-- EM SANDRA ROCHA (CONTAGEM)
UPDATE schools SET inep_code = '212571' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SANDRA ROCHA' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '212571');

-- EM TEMPO INTEGRAL PROFESSORA AUDREI CONSOLAÇÃO FERREIRA DE FREITAS COSTA (CONTAGEM)
UPDATE schools SET inep_code = '374881' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM TEMPO INTEGRAL PROFESSORA AUDREI CONSOLAÇÃO FERREIRA DE FREITAS COSTA' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '374881');

-- EM VALTER FAUSTO DO AMARAL (CONTAGEM)
UPDATE schools SET inep_code = '226386' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM VALTER FAUSTO DO AMARAL' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '226386');

-- EM VASCO PINTO DA FONSECA (CONTAGEM)
UPDATE schools SET inep_code = '220990' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM VASCO PINTO DA FONSECA' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '220990');

-- EM VEREADOR BENEDITO BATISTA (CONTAGEM)
UPDATE schools SET inep_code = '343870' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM VEREADOR BENEDITO BATISTA' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '343870');

-- EM VEREADOR JESUS MÍLTON DOS SANTOS (CONTAGEM)
UPDATE schools SET inep_code = '250724' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM VEREADOR JESUS MÍLTON DOS SANTOS' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '250724');

-- EM VEREADOR JOSÉ FERREIRA DE AGUIAR (CONTAGEM)
UPDATE schools SET inep_code = '226378' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM VEREADOR JOSÉ FERREIRA DE AGUIAR' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '226378');

-- EM WALTER LOPES (CONTAGEM)
UPDATE schools SET inep_code = '310344' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM WALTER LOPES' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310344');

-- IEC - UNIDADE OITIS (CONTAGEM)
UPDATE schools SET inep_code = '360171' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'IEC - UNIDADE OITIS' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '360171');

-- IEC UNIDADE INDUSTRIAL (CONTAGEM)
UPDATE schools SET inep_code = '223174' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'IEC UNIDADE INDUSTRIAL' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '223174');

-- IEC UNIDADE NOVA CONTAGEM (CONTAGEM)
UPDATE schools SET inep_code = '315486' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'IEC UNIDADE NOVA CONTAGEM' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '315486');

-- IEC UNIDADE PETROLÂNDIA (CONTAGEM)
UPDATE schools SET inep_code = '223182' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'IEC UNIDADE PETROLÂNDIA' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '223182');

-- IEC UNIDADE XANGRILÁ (CONTAGEM)
UPDATE schools SET inep_code = '315478' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'IEC UNIDADE XANGRILÁ' AND UPPER(TRIM(city)) = 'CONTAGEM' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '315478');

-- EM EURICA ALVES MOREIRA (ESMERALDAS)
UPDATE schools SET inep_code = '325431' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM EURICA ALVES MOREIRA' AND UPPER(TRIM(city)) = 'ESMERALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '325431');

-- EM FELICIANO ALVES DINIZ (ESMERALDAS)
UPDATE schools SET inep_code = '222844' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM FELICIANO ALVES DINIZ' AND UPPER(TRIM(city)) = 'ESMERALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '222844');

-- EM JOSÉ LUCAS FILHO (ESMERALDAS)
UPDATE schools SET inep_code = '222852' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ LUCAS FILHO' AND UPPER(TRIM(city)) = 'ESMERALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '222852');

-- EM JOSEFINA LUCAS MUNIZ (ESMERALDAS)
UPDATE schools SET inep_code = '222861' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSEFINA LUCAS MUNIZ' AND UPPER(TRIM(city)) = 'ESMERALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '222861');

-- EM MARIETA RODRIGUES SOARES (ESMERALDAS)
UPDATE schools SET inep_code = '310930' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIETA RODRIGUES SOARES' AND UPPER(TRIM(city)) = 'ESMERALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '310930');

-- EM SADI ALVES VIEIRA (ESMERALDAS)
UPDATE schools SET inep_code = '222879' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SADI ALVES VIEIRA' AND UPPER(TRIM(city)) = 'ESMERALDAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '222879');

-- EM CORONEL DURVAL DE BARROS (IBIRITÉ)
UPDATE schools SET inep_code = '239542' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CORONEL DURVAL DE BARROS' AND UPPER(TRIM(city)) = 'IBIRITÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '239542');

-- EM DA VILA IDEAL SERRA DOURADA (IBIRITÉ)
UPDATE schools SET inep_code = '322717' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DA VILA IDEAL SERRA DOURADA' AND UPPER(TRIM(city)) = 'IBIRITÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322717');

-- EM DO BAIRRO ÁGUIA DOURADA (IBIRITÉ)
UPDATE schools SET inep_code = '363715' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DO BAIRRO ÁGUIA DOURADA' AND UPPER(TRIM(city)) = 'IBIRITÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '363715');

-- EM DO BAIRRO DUVAL DE BARROS (IBIRITÉ)
UPDATE schools SET inep_code = '362700' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DO BAIRRO DUVAL DE BARROS' AND UPPER(TRIM(city)) = 'IBIRITÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '362700');

-- EM DO BAIRRO JARDIM DAS ROSAS (IBIRITÉ)
UPDATE schools SET inep_code = '348902' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DO BAIRRO JARDIM DAS ROSAS' AND UPPER(TRIM(city)) = 'IBIRITÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '348902');

-- EM DO BAIRRO JARDIM MONTREAL OURO NEGRO (IBIRITÉ)
UPDATE schools SET inep_code = '331287' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DO BAIRRO JARDIM MONTREAL OURO NEGRO' AND UPPER(TRIM(city)) = 'IBIRITÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '331287');

-- EM DO BAIRRO PALMEIRAS (IBIRITÉ)
UPDATE schools SET inep_code = '362719' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DO BAIRRO PALMEIRAS' AND UPPER(TRIM(city)) = 'IBIRITÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '362719');

-- EM DO BAIRRO SERRA DOURADA (IBIRITÉ)
UPDATE schools SET inep_code = '348899' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DO BAIRRO SERRA DOURADA' AND UPPER(TRIM(city)) = 'IBIRITÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '348899');

-- EM MARIA DAS MERCÊS AGUIAR (IBIRITÉ)
UPDATE schools SET inep_code = '348880' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA DAS MERCÊS AGUIAR' AND UPPER(TRIM(city)) = 'IBIRITÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '348880');

-- EM MARINETE DAMASCENO PINHEIRO (IBIRITÉ)
UPDATE schools SET inep_code = '249271' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARINETE DAMASCENO PINHEIRO' AND UPPER(TRIM(city)) = 'IBIRITÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '249271');

-- EM MORADA DA SERRA (IBIRITÉ)
UPDATE schools SET inep_code = '211419' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MORADA DA SERRA' AND UPPER(TRIM(city)) = 'IBIRITÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '211419');

-- EM PETRINA DE FREITAS CAMPOS (IBIRITÉ)
UPDATE schools SET inep_code = '348872' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PETRINA DE FREITAS CAMPOS' AND UPPER(TRIM(city)) = 'IBIRITÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '348872');

-- EM PROFESSORA CARMELITA  CARVALHO GARCIA (IBIRITÉ)
UPDATE schools SET inep_code = '231681' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA CARMELITA  CARVALHO GARCIA' AND UPPER(TRIM(city)) = 'IBIRITÉ' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '231681');

-- EM ALÍPIO NOGUEIRA DO AMARAL (JUATUBA)
UPDATE schools SET inep_code = '258733' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ALÍPIO NOGUEIRA DO AMARAL' AND UPPER(TRIM(city)) = 'JUATUBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '258733');

-- EM ELZA DE OLIVEIRA SARAIVA (JUATUBA)
UPDATE schools SET inep_code = '236829' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ELZA DE OLIVEIRA SARAIVA' AND UPPER(TRIM(city)) = 'JUATUBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '236829');

-- EM ETELVINA DE OLIVEIRA GUIMARÃES (JUATUBA)
UPDATE schools SET inep_code = '297658' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ETELVINA DE OLIVEIRA GUIMARÃES' AND UPPER(TRIM(city)) = 'JUATUBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '297658');

-- EM JUQUITA FIRMINO (JUATUBA)
UPDATE schools SET inep_code = '236811' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JUQUITA FIRMINO' AND UPPER(TRIM(city)) = 'JUATUBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '236811');

-- EM MARIA LUZIA DE ANDRADE (JUATUBA)
UPDATE schools SET inep_code = '258741' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA LUZIA DE ANDRADE' AND UPPER(TRIM(city)) = 'JUATUBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '258741');

-- EM MARIA RENILDA FERREIRA (JUATUBA)
UPDATE schools SET inep_code = '234613' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA RENILDA FERREIRA' AND UPPER(TRIM(city)) = 'JUATUBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '234613');

-- EM MIGUEL RODRIGUES DUARTE (JUATUBA)
UPDATE schools SET inep_code = '205362' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MIGUEL RODRIGUES DUARTE' AND UPPER(TRIM(city)) = 'JUATUBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '205362');

-- EM PADRE MOACIR CÂNDIDO RODRIGUES (JUATUBA)
UPDATE schools SET inep_code = '259331' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PADRE MOACIR CÂNDIDO RODRIGUES' AND UPPER(TRIM(city)) = 'JUATUBA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '259331');

-- EM JOSÉ ANTÔNIO JÚNIOR (SÃO JOAQUIM DE BICAS)
UPDATE schools SET inep_code = '226432' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ ANTÔNIO JÚNIOR' AND UPPER(TRIM(city)) = 'SÃO JOAQUIM DE BICAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '226432');

-- EM MARIA JOSÉ DE ANDRADE HENRIQUES (SÃO JOAQUIM DE BICAS)
UPDATE schools SET inep_code = '226416' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA JOSÉ DE ANDRADE HENRIQUES' AND UPPER(TRIM(city)) = 'SÃO JOAQUIM DE BICAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '226416');

-- EM ACADÊMICO VIVALDI MOREIRA (BELO HORIZONTE)
UPDATE schools SET inep_code = '312614' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ACADÊMICO VIVALDI MOREIRA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312614');

-- EM ANNE FRANK (BELO HORIZONTE)
UPDATE schools SET inep_code = '219185' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ANNE FRANK' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '219185');

-- EM ARMANDO ZILLER (BELO HORIZONTE)
UPDATE schools SET inep_code = '232009' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ARMANDO ZILLER' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '232009');

-- EM CARLOS DRUMMOND DE ANDRADE (BELO HORIZONTE)
UPDATE schools SET inep_code = '247294' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CARLOS DRUMMOND DE ANDRADE' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '247294');

-- EM DOUTOR JOSÉ XAVIER NOGUEIRA (BELO HORIZONTE)
UPDATE schools SET inep_code = '330850' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOUTOR JOSÉ XAVIER NOGUEIRA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '330850');

-- EM FLORESTAN FERNANDES (BELO HORIZONTE)
UPDATE schools SET inep_code = '283011' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM FLORESTAN FERNANDES' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '283011');

-- EM FRANCISCO MAGALHÃES GOMES (BELO HORIZONTE)
UPDATE schools SET inep_code = '217891' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM FRANCISCO MAGALHÃES GOMES' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '217891');

-- EM HÉLIO PELLEGRINO (BELO HORIZONTE)
UPDATE schools SET inep_code = '247308' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM HÉLIO PELLEGRINO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '247308');

-- EM HERBERT JOSÉ DE SOUZA (BELO HORIZONTE)
UPDATE schools SET inep_code = '312622' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM HERBERT JOSÉ DE SOUZA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '312622');

-- EM JARDIM FELICIDADE (BELO HORIZONTE)
UPDATE schools SET inep_code = '212792' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JARDIM FELICIDADE' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '212792');

-- EM JARDIM LEBLON (BELO HORIZONTE)
UPDATE schools SET inep_code = '362247' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JARDIM LEBLON' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '362247');

-- EM JOSÉ MARIA DOS MARES GUIA (BELO HORIZONTE)
UPDATE schools SET inep_code = '223654' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ MARIA DOS MARES GUIA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '223654');

-- EM PADRE MARZANO MATIAS (BELO HORIZONTE)
UPDATE schools SET inep_code = '294641' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PADRE MARZANO MATIAS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '294641');

-- EM PROFESSOR AMÍLCAR MARTINS (BELO HORIZONTE)
UPDATE schools SET inep_code = '219568' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR AMÍLCAR MARTINS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '219568');

-- EM PROFESSOR DANIEL ALVARENGA (BELO HORIZONTE)
UPDATE schools SET inep_code = '294632' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR DANIEL ALVARENGA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '294632');

-- EM PROFESSOR TABAJARA PEDROSO (BELO HORIZONTE)
UPDATE schools SET inep_code = '206521' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR TABAJARA PEDROSO' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '206521');

-- EM RUI DA COSTA VAL (BELO HORIZONTE)
UPDATE schools SET inep_code = '233366' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM RUI DA COSTA VAL' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '233366');

-- EM SANTA TEREZINHA (BELO HORIZONTE)
UPDATE schools SET inep_code = '219231' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SANTA TEREZINHA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '219231');

-- EM SÉRGIO MIRANDA (BELO HORIZONTE)
UPDATE schools SET inep_code = '353752' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM SÉRGIO MIRANDA' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '353752');

-- EM ZILDA ARNS (BELO HORIZONTE)
UPDATE schools SET inep_code = '346900' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ZILDA ARNS' AND UPPER(TRIM(city)) = 'BELO HORIZONTE' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '346900');

-- EM DE LAPINHA (LAGOA SANTA)
UPDATE schools SET inep_code = '352942' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DE LAPINHA' AND UPPER(TRIM(city)) = 'LAGOA SANTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '352942');

-- EM DONA ARAMITA (LAGOA SANTA)
UPDATE schools SET inep_code = '253898' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DONA ARAMITA' AND UPPER(TRIM(city)) = 'LAGOA SANTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '253898');

-- EM LÍVIO MÚCIO CONRADO SILVA SENHOR TITO (LAGOA SANTA)
UPDATE schools SET inep_code = '354740' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM LÍVIO MÚCIO CONRADO SILVA SENHOR TITO' AND UPPER(TRIM(city)) = 'LAGOA SANTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '354740');

-- EM PROFESSORA MÉRCIA MARGARIDA LACERDA MACHADO (LAGOA SANTA)
UPDATE schools SET inep_code = '345393' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSORA MÉRCIA MARGARIDA LACERDA MACHADO' AND UPPER(TRIM(city)) = 'LAGOA SANTA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '345393');

-- EM DONA CARMEM BARROSO (PEDRO LEOPOLDO)
UPDATE schools SET inep_code = '321516' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DONA CARMEM BARROSO' AND UPPER(TRIM(city)) = 'PEDRO LEOPOLDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '321516');

-- EM IZABEL GOMES TEIXEIRA (PEDRO LEOPOLDO)
UPDATE schools SET inep_code = '248461' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM IZABEL GOMES TEIXEIRA' AND UPPER(TRIM(city)) = 'PEDRO LEOPOLDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '248461');

-- EM JOSÉ ELIAS DA COSTA (PEDRO LEOPOLDO)
UPDATE schools SET inep_code = '223034' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ ELIAS DA COSTA' AND UPPER(TRIM(city)) = 'PEDRO LEOPOLDO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '223034');

-- EM ALICE MARIA SMÉRIA (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '347159' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ALICE MARIA SMÉRIA' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '347159');

-- EM CARLINDA RITTA DA SILVA (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '322415' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CARLINDA RITTA DA SILVA' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '322415');

-- EM DERALDO JOSÉ DE SOUSA (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '345962' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DERALDO JOSÉ DE SOUSA' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '345962');

-- EM DO BAIRRO METROPOLITANO (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '345946' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DO BAIRRO METROPOLITANO' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '345946');

-- EM EDSON CARLOS LOPES (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '347124' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM EDSON CARLOS LOPES' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '347124');

-- EM JAIR AMÂNCIO (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '247472' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JAIR AMÂNCIO' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '247472');

-- EM JANDIR CLEMENTE ROCHA (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '349844' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JANDIR CLEMENTE ROCHA' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '349844');

-- EM JOSÉ PINTO PIMENTA (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '345954' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ PINTO PIMENTA' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '345954');

-- EM MARIA DA CRUZ RESENDE (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '278190' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA DA CRUZ RESENDE' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '278190');

-- EM MARIA VIEIRA BARBOSA (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '238945' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA VIEIRA BARBOSA' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '238945');

-- EM PROFESSOR AENDER MARQUES DA COSTA (RIBEIRÃO DAS NEVES)
UPDATE schools SET inep_code = '347140' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PROFESSOR AENDER MARQUES DA COSTA' AND UPPER(TRIM(city)) = 'RIBEIRÃO DAS NEVES' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '347140');

-- EM DONA QUITA (SANTA LUZIA)
UPDATE schools SET inep_code = '224766' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DONA QUITA' AND UPPER(TRIM(city)) = 'SANTA LUZIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '224766');

-- EM DOUTOR OSWALDO FERREIRA (SANTA LUZIA)
UPDATE schools SET inep_code = '333107' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM DOUTOR OSWALDO FERREIRA' AND UPPER(TRIM(city)) = 'SANTA LUZIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '333107');

-- EM ETELVINO SOUZA LIMA (SANTA LUZIA)
UPDATE schools SET inep_code = '218359' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ETELVINO SOUZA LIMA' AND UPPER(TRIM(city)) = 'SANTA LUZIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '218359');

-- EM LUISA ROSÁLIA DINIZ KENTISH (SANTA LUZIA)
UPDATE schools SET inep_code = '339873' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM LUISA ROSÁLIA DINIZ KENTISH' AND UPPER(TRIM(city)) = 'SANTA LUZIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '339873');

-- EM MARIA JOSÉ DE BRITO CARVALHO (SANTA LUZIA)
UPDATE schools SET inep_code = '245852' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA JOSÉ DE BRITO CARVALHO' AND UPPER(TRIM(city)) = 'SANTA LUZIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '245852');

-- EM MIGUEL RESENDE (SANTA LUZIA)
UPDATE schools SET inep_code = '327115' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MIGUEL RESENDE' AND UPPER(TRIM(city)) = 'SANTA LUZIA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '327115');

-- EM GERALDA JORGE DOS SANTOS (SANTANA DO RIACHO)
UPDATE schools SET inep_code = '267341' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM GERALDA JORGE DOS SANTOS' AND UPPER(TRIM(city)) = 'SANTANA DO RIACHO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '267341');

-- EM ODETE RODRIGUES FERREIRA (SÃO JOSÉ DA LAPA)
UPDATE schools SET inep_code = '236730' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ODETE RODRIGUES FERREIRA' AND UPPER(TRIM(city)) = 'SÃO JOSÉ DA LAPA' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '236730');

-- EM RAIMUNDO DAS CHAGAS QUINTÃO (TAQUARAÇU DE MINAS)
UPDATE schools SET inep_code = '272051' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM RAIMUNDO DAS CHAGAS QUINTÃO' AND UPPER(TRIM(city)) = 'TAQUARAÇU DE MINAS' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '272051');

-- EM BÁRBARA MARIA SALOMÃO (VESPASIANO)
UPDATE schools SET inep_code = '324183' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM BÁRBARA MARIA SALOMÃO' AND UPPER(TRIM(city)) = 'VESPASIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '324183');

-- EM CAROLINA CORRÊA DA COSTA (VESPASIANO)
UPDATE schools SET inep_code = '363839' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM CAROLINA CORRÊA DA COSTA' AND UPPER(TRIM(city)) = 'VESPASIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '363839');

-- EM ELIZIO ANTONIO DE ALMEIDA (VESPASIANO)
UPDATE schools SET inep_code = '352373' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ELIZIO ANTONIO DE ALMEIDA' AND UPPER(TRIM(city)) = 'VESPASIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '352373');

-- EM JOSÉ PAULO DE BARROS (VESPASIANO)
UPDATE schools SET inep_code = '321028' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ PAULO DE BARROS' AND UPPER(TRIM(city)) = 'VESPASIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '321028');

-- EM JOSÉ SILVA (VESPASIANO)
UPDATE schools SET inep_code = '251348' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSÉ SILVA' AND UPPER(TRIM(city)) = 'VESPASIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '251348');

-- EM JOSEFINA ALVES VIEIRA (VESPASIANO)
UPDATE schools SET inep_code = '293962' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JOSEFINA ALVES VIEIRA' AND UPPER(TRIM(city)) = 'VESPASIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '293962');

-- EM JUSSARA GALEGO (VESPASIANO)
UPDATE schools SET inep_code = '358720' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM JUSSARA GALEGO' AND UPPER(TRIM(city)) = 'VESPASIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '358720');

-- EM MANOEL FONSECA VIANA SOBRINHO (VESPASIANO)
UPDATE schools SET inep_code = '351890' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MANOEL FONSECA VIANA SOBRINHO' AND UPPER(TRIM(city)) = 'VESPASIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '351890');

-- EM MARIA APARECIDA BARROS SANTOS (VESPASIANO)
UPDATE schools SET inep_code = '340146' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA APARECIDA BARROS SANTOS' AND UPPER(TRIM(city)) = 'VESPASIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '340146');

-- EM MARIA DO CARMO SOARES - DONA NHANHÁ (VESPASIANO)
UPDATE schools SET inep_code = '371610' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM MARIA DO CARMO SOARES - DONA NHANHÁ' AND UPPER(TRIM(city)) = 'VESPASIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '371610');

-- EM ORDELINA DE LOURDES COSTA (VESPASIANO)
UPDATE schools SET inep_code = '324191' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM ORDELINA DE LOURDES COSTA' AND UPPER(TRIM(city)) = 'VESPASIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '324191');

-- EM PREFEITO MARCONI ISSA (VESPASIANO)
UPDATE schools SET inep_code = '358711' WHERE id = (SELECT id FROM schools WHERE UPPER(TRIM(name)) = 'EM PREFEITO MARCONI ISSA' AND UPPER(TRIM(city)) = 'VESPASIANO' AND inep_code IS NULL LIMIT 1) AND NOT EXISTS (SELECT 1 FROM schools WHERE inep_code = '358711');