-- Migration: Create PDI Documents table
-- Description: Comprehensive PDI (Individual Development Plan) system with 11 blocks
-- Date: 2026-01-24

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create pdi_documents table
CREATE TABLE IF NOT EXISTS pdi_documents (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    student_id UUID REFERENCES school_students(id) ON DELETE CASCADE NOT NULL,
    school_id TEXT REFERENCES schools(id) NOT NULL,
    
    -- Blocos 1-8: Formulário Base (preenchido pelo Supervisor)
    -- Estrutura JSONB contendo os 8 blocos iniciais
    block_1_8 JSONB DEFAULT '{
        "bloco_1_identificacao": {},
        "bloco_2_diagnostico": {},
        "bloco_3_objetivos": {},
        "bloco_4_recursos": {},
        "bloco_5_equipe": {},
        "bloco_6_atendimento": {},
        "bloco_7_familia": {},
        "bloco_8_observacoes": {}
    }'::jsonb,
    block_1_8_filled_by UUID REFERENCES auth.users(id),
    block_1_8_filled_at TIMESTAMP WITH TIME ZONE,
    
    -- Bloco 9: Planejamento Pedagógico (gerado automaticamente pela IA)
    -- Array de adaptações curriculares por aula
    block_9_content JSONB DEFAULT '[]'::jsonb,
    block_9_last_generated TIMESTAMP WITH TIME ZONE,
    
    -- Bloco 10: Avaliação e Acompanhamento (Professor + IA)
    -- Array de registros de avaliação
    block_10_entries JSONB DEFAULT '[]'::jsonb,
    
    -- Bloco 11: Relatório Final (IA + Supervisor)
    block_11_ai_generated TEXT,
    block_11_supervisor_edit TEXT,
    block_11_approved BOOLEAN DEFAULT false,
    block_11_approved_by UUID REFERENCES auth.users(id),
    block_11_approved_at TIMESTAMP WITH TIME ZONE,
    
    -- Metadados
    period TEXT, -- Ex: "1º Bimestre 2026", "2026"
    status TEXT DEFAULT 'em_andamento' CHECK (status IN ('em_andamento', 'finalizado', 'arquivado')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Constraint: Um PDI por aluno por período
    UNIQUE(student_id, period)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_pdi_documents_student ON pdi_documents(student_id);
CREATE INDEX IF NOT EXISTS idx_pdi_documents_school ON pdi_documents(school_id);
CREATE INDEX IF NOT EXISTS idx_pdi_documents_period ON pdi_documents(period);
CREATE INDEX IF NOT EXISTS idx_pdi_documents_status ON pdi_documents(status);

-- Enable Row Level Security
ALTER TABLE pdi_documents ENABLE ROW LEVEL SECURITY;

-- RLS Policies

-- 1. Supervisores/Gestores podem ver, criar e editar PDIs de sua escola
DROP POLICY IF EXISTS "Supervisors manage PDI documents" ON pdi_documents;
CREATE POLICY "Supervisors manage PDI documents" ON pdi_documents
FOR ALL TO authenticated
USING (
    school_id IN (
        SELECT school_id FROM profiles 
        WHERE id = auth.uid() 
        AND role IN ('school_manager', 'school_admin', 'admin')
    )
);

-- 2. Professores podem visualizar PDIs dos alunos de suas turmas
DROP POLICY IF EXISTS "Teachers view PDI documents" ON pdi_documents;
CREATE POLICY "Teachers view PDI documents" ON pdi_documents
FOR SELECT TO authenticated
USING (
    student_id IN (
        SELECT ss.id FROM school_students ss
        WHERE ss.school_id IN (
            SELECT school_id FROM profiles WHERE id = auth.uid()
        )
    )
    OR
    -- Permitir se o professor leciona na mesma escola
    school_id IN (
        SELECT school_id FROM profiles WHERE id = auth.uid()
    )
);

-- 3. Professores podem atualizar APENAS o Bloco 10 (avaliações)
DROP POLICY IF EXISTS "Teachers update Block 10 only" ON pdi_documents;
CREATE POLICY "Teachers update Block 10 only" ON pdi_documents
FOR UPDATE TO authenticated
USING (
    school_id IN (
        SELECT school_id FROM profiles WHERE id = auth.uid()
    )
    AND
    EXISTS (
        SELECT 1 FROM profiles 
        WHERE id = auth.uid() 
        AND role = 'teacher'
    )
);

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_pdi_documents_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to update updated_at
DROP TRIGGER IF EXISTS trigger_update_pdi_documents_updated_at ON pdi_documents;
CREATE TRIGGER trigger_update_pdi_documents_updated_at
    BEFORE UPDATE ON pdi_documents
    FOR EACH ROW
    EXECUTE FUNCTION update_pdi_documents_updated_at();

-- Comments for documentation
COMMENT ON TABLE pdi_documents IS 'Comprehensive PDI (Individual Development Plan) documents with 11 blocks';
COMMENT ON COLUMN pdi_documents.block_1_8 IS 'Blocks 1-8: Base form filled by supervisor (JSONB structure)';
COMMENT ON COLUMN pdi_documents.block_9_content IS 'Block 9: Automatic pedagogical adaptations generated by AI (Array)';
COMMENT ON COLUMN pdi_documents.block_10_entries IS 'Block 10: Evaluation entries (Professor fills grades, AI generates diagnosis)';
COMMENT ON COLUMN pdi_documents.block_11_ai_generated IS 'Block 11: Final report generated by AI';
COMMENT ON COLUMN pdi_documents.block_11_supervisor_edit IS 'Block 11: Supervisor edited version of the report';
COMMENT ON COLUMN pdi_documents.period IS 'Academic period for this PDI (e.g., "1º Bimestre 2026")';
