-- Database Schema for PROFEPLAN ERP Transformation

-- 1. Teacher Profile (Extension of existing users/settings)
-- Stores long-term preferences and context
CREATE TABLE IF NOT EXISTS teacher_profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id),
  full_name TEXT,
  state_uf VARCHAR(2),
  school_name TEXT,
  teaching_style TEXT, -- "Gamification", "Traditional", etc.
  preferences JSONB DEFAULT '{}'::jsonb, -- Stores dynamic feedback "ESTILO_PROFESSOR"
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Academic Calendar
-- Stores holidays, school days, etc.
CREATE TABLE IF NOT EXISTS academic_calendars (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  year INTEGER NOT NULL,
  holidays JSONB, -- Array of dates
  work_days JSONB, -- ["Mon", "Wed", "Fri"]
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Quarterly Plans (The Execution Core)
-- Stores the "Skeleton" of the trimester
CREATE TABLE IF NOT EXISTS quarterly_plans (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  title TEXT, -- "Planejamento 1º Tri - Geografia 9º Ano"
  grade_level TEXT,
  discipline TEXT,
  quarter TEXT, -- "Q1", "Q2", etc.
  status TEXT DEFAULT 'draft',
  structure JSONB, -- THE ARRAY OF CLASSES: [{id: 1, theme: "Globalização", bncc: "EF09GE01", status: "pending"}]
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Class Details (The "Monte a aula X" result)
-- Stores the detailed generated content for a specific class ID within a plan
CREATE TABLE IF NOT EXISTS class_details (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  plan_id UUID REFERENCES quarterly_plans(id),
  class_index INTEGER, -- 1, 2, 3...
  content TEXT, -- Full markdown content generated by Gemini
  resources JSONB, -- List of materials/slides prompts
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. ENEM Question Bank
-- Central repository for parsed ENEM questions with full taxonomy
CREATE TABLE IF NOT EXISTS enem_questions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  exam_year INTEGER, -- e.g., 2024
  exam_color TEXT, -- "Azul", "Amarelo", "Branco", "Rosa"
  question_number INTEGER,
  
  -- Content
  intro_text TEXT, -- The support text before the question
  question_text TEXT, -- The actual question command
  alternatives JSONB, -- {"A": "text", "B": "text", ...}
  image_url TEXT, -- Path to extracted image if any
  correct_answer CHAR(1), -- "A", "B", "C", "D", "E"
  
  -- Taxonomy / Classification
  area TEXT, -- "Linguagens, Códigos e suas Tecnologias"
  component TEXT, -- "Lígua Portuguesa"
  knowledge_object TEXT, -- "Morfossintaxe"
  specific_topic TEXT, -- "Verbos Transitivos"
  bncc_skill TEXT, -- "EM13LGG101"
  
  -- Metadata
  embedding_id TEXT, -- Reference to Vector DB ID (usually same as UUID but explicit is good)
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
